### ISSUE TITLE
Impending Doom incorrect level calculation with +1 to all chaos skull amulet.

### ISSUE THREAD

**Issue by ERHL** [PathOfBuildingCommunity/PathOfBuilding#6003] opened 2023-04-09 22:42 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

In game shows that the mod "+1 to level of all chaos skill gems" does not increase the level of the Impending Doom Support.

### What is the value from the calculation in Path of Building?

PoB shows that the mod _does_ increase the level of Impending Doom Support. This is incorrect as far as I can tell.

### How to reproduce the issue

Wear a +1 to level of all chaos skill gems amulet. Check your in game gem and PoB gem.

### Character build code

```shell
https://pobb.in/MNYK1YGKA_di
```

### Screenshots

![image](https://user-images.githubusercontent.com/10897591/230799808-2d835d15-f25f-44c4-b114-c2f865a849b3.png)
![image](https://user-images.githubusercontent.com/10897591/230799816-868e3701-9b11-4726-a91e-38f5f150bc81.png)
![image](https://user-images.githubusercontent.com/10897591/230799833-2fa43994-d207-4ca9-b6c0-548e59e255db.png)

**Comment by Wires77** [comment] 2023-04-10 00:20
Essentially a duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2719

**Closed by Wires77** 2023-04-10 00:20 UTC
Labels: bug:calculation
