### ISSUE TITLE
Simulated impact of linked spells

### ISSUE THREAD

**Issue by Yasur7** [PathOfBuildingCommunity/PathOfBuilding#6172] opened 2023-04-30 03:42 UTC
Hey, sorry to interrupt but I searched whole internet and couldnt find the answer.
What is "Simulated impact of linked spells: exactly? I can see everyone have exact value of "1" but I have it on "1.04" and i have no clue how to change it.
Could you please help me?
Thanks
Someone:
![image](https://user-images.githubusercontent.com/45875856/235334420-251a2167-549f-4f4e-bf37-49f2448d4868.png)

Me:
![image](https://user-images.githubusercontent.com/45875856/235334613-b95d6507-ab47-4a08-bb59-ac8b95736b9a.png)

I just noticed it changes when "Have you crit recently" is checked but it changed only for me not for others.

**Comment by Paliak** [comment] 2023-04-30 19:15
Pob runs a simulation of the skill group to determine how often certain skills trigger compared to others.

There are 3 main factors that contribute to trigger rate:

- source rate (the thing that triggers a trigger, e.g. a crit from cyclone)
- Cooldown of the trigger
- Cooldown of the triggered gem

In "resting" state, triggering a spell with coc works as you'd expect: source -> trigger -> triggered

But you have to keep in mind that the source will only trigger the trigger so often, and that both the trigger and the trigger**ed** skill can have cooldowns.

If your attack speed is 10.24 and every single hit hits (accuracy) and every one is a crit (crit chance) that means you will trigger the trigger support (CoC in your case) every 1/10.24 = 0.09765625 seconds but CoC can only trigger every 0.15 seconds (default cool down excluding mods). Let's round that source rate (1/10.24) to 0.1 for this example.

You start with everything at rest. Then you hit (T = 0s), Cast on Crit goes on a 0.15s cooldown. Then you hit again(T= 0.10s) but Cast on Crit is on cooldown so nothing happens. 0.05s later (T=0.15s) the cooldown of CoC wears off and can be triggered again, but you won't hit for another 0.05s (T= 0.20s). Meaning that not only you've missed a trigger opportunity, you're also not using CoC to its full potential because it has to wait for you to hit again.

A similar thing happens when you trigger a skill that has a cooldown (just with triggers of the trigger as the "source") but Ice spear has none, so I'll omit the explanation.

What POB does is it runs a simulation similar to what I've described above (including all triggered gems, so if you have 2 triggered skills with no cooldown the best max is 0.5) and shows you a sort of simulated estimate on how close you are to fully utilizing your trigger support.

Note that the current implementation of triggers in POB has some issues that I've addressed in #4599 (but that pr seems to keep getting pushed back for one reason or another) so the value you're seeing may not be entirely accurate on top of being just a simulation.

It's hard for me to say for certain what you could do to optimize your build without a link, but the root cause is that your attack speed is either too low or too high for the cool down breakpoint you've hit on CoC.

**Comment by Yasur7** [comment] 2023-04-30 22:27
Thank you for such in-depth answer to my qiestion, it was very helpful.
I find out I had too much attack speed, would never expect that too many of a stat can lower your dmg.

**Closed** 2023-05-01 01:22 UTC
Labels: question
