### ISSUE TITLE
2Handed Mace, Shaper Suffix Modifier "+1 to Maximum Endurance Charges" not present

### ISSUE THREAD

**Issue by Zalkenth** [PathOfBuildingCommunity/PathOfBuilding#5775] opened 2023-03-21 13:52 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour ingame?

A shaper influenced suffix mod with "+1 to Maximum Endurance Charges" can be applied to Two Handed Maces, with the correct influence.  No such mod is present in the PoB list with influence selected. I am attaching screenshots:

screenshots 1) + 2) proof of non-existance of modifier, screenshot 2 includes pob version for verification
3) poedb mod list which includes the modifier
4) craft of exile mod list which includes the modifier
5) Item found in trade with said modifier
![item 1](https://user-images.githubusercontent.com/128490838/226623839-37fc90cb-a922-46cc-b174-475d1f92d545.png)
![item 2](https://user-images.githubusercontent.com/128490838/226623871-a830d01b-f396-4cc2-b5eb-90df5563c245.png)
![poedb](https://user-images.githubusercontent.com/128490838/226623945-50647d2b-d841-4052-a071-8d7f83205141.png)
![craftofexile](https://user-images.githubusercontent.com/128490838/226623974-6098f2d1-ff8a-4546-9ab1-5624941c9b1e.png)
![trade](https://user-images.githubusercontent.com/128490838/226623999-b0e558c5-be70-47a9-b385-9d1dad01daab.png)

### What is the behaviour in Path of Building?

Check above. Sorry for missuse of the report function. Thanks for reading.

### How to reproduce the issue

E.g.
1) In a build, switch to items tab
2) Press "Craft item..."
3) Select "Two Handed Mace"
4) Select any base
5) Select Shaper Influence
6) Check Suffixes list for "+1 to Maximum Endurance Charges" "Of Shaping" modifier

### Character build code

```shell
I do not see how this is of any use but:
https://pobb.in/e9gWR7Y3pOAR
```

### Screenshots

![item 1](https://user-images.githubusercontent.com/128490838/226623839-37fc90cb-a922-46cc-b174-475d1f92d545.png)
![item 2](https://user-images.githubusercontent.com/128490838/226623871-a830d01b-f396-4cc2-b5eb-90df5563c245.png)
![poedb](https://user-images.githubusercontent.com/128490838/226623945-50647d2b-d841-4052-a071-8d7f83205141.png)
![craftofexile](https://user-images.githubusercontent.com/128490838/226623974-6098f2d1-ff8a-4546-9ab1-5624941c9b1e.png)
![trade](https://user-images.githubusercontent.com/128490838/226623999-b0e558c5-be70-47a9-b385-9d1dad01daab.png)

**Comment by QuickStick123** [comment] 2023-03-21 13:54
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5448 and fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5375
![image](https://user-images.githubusercontent.com/31533893/226627381-47e7ed0c-1d99-4309-8829-428e04751195.png)

**Closed by QuickStick123** 2023-03-21 13:54 UTC
Labels: bug:behaviour
