### ISSUE TITLE
Wrong "Current Shock" calculations for Lightning damage skills while using Shaper of Storms

### ISSUE THREAD

**Issue by Balline** [PathOfBuildingCommunity/PathOfBuilding#1879] opened 2021-01-13 17:11 UTC
https://pastebin.com/a1nUL6T9
Current Shock calculation, when using Shaper of Storms, seems to completely ignore the 25% more Shock effect whether or not you're using a lightning damage skill. It also seems to ignore the increase% bonuses on skills which have built-in Shock effect.

Simple example above: I use a 90% increased effect of Shock item +10% from the small node leading to Shaper of Storms, giving me 100% increased Shock Effect. With minimum 15% shock from ANY hit, I should always get at least 30% Shock. The problem is that my Current Shock is always set at 30% whether I use Ethereal Knives (normal, since I do no lightning damage), Ball Lightning (lightning damage, but no 25% more multiplier), or Vaal Arc (which has a built in extra +100% increased effect of Shock).

**Comment by Quotae** [comment] 2021-01-13 18:59
This is working as intended, but might be a little unintuitive. The automatic Shock from Elementalist only considers global increases to Shock effect. The Effect of Shock on Vaal Arc doesn't affect it because it's local to the skill, and the 25% more from Shaper of Storms doesn't affect it because it relies on the skill itself dealing mostly Lightning damage. 

You can override the automatic Shock with a bigger one in the Config options:
![image](https://user-images.githubusercontent.com/39030429/104496500-b3858d80-559e-11eb-9abc-59038e59a9d6.png)

The Shock Effect Mod is shown so you can easily calculate bigger Shocks when you need to. On the Pastebin you linked you would be inflicting a 56.25% Shock with Vaal Arc, but Shock is capped at 50% by default.

This behavior most likely won't be changed, so I'm going to close this issue.

**Closed by Quotae** 2021-01-13 18:59 UTC
Labels: bug
