### ISSUE TITLE
Thread of hope does not work when imported from a character directly

### ISSUE THREAD

**Issue by Tartarus762** [PathOfBuildingCommunity/PathOfBuilding#734] opened 2020-04-07 12:40 UTC
See the following pastebin:

https://pastebin.com/aEnqMRM5

I imported the skills, tree and items from my in-game character and the Thread of Hope jewel does not work and any passives that were previously allocated with Thread of Hope are not allocated and cannot be allocated.

The method of importing was: 
Click Import/Export build
In the "Character Import" section enter my account name and click start
Select my character and click "Passive tree and Jewels" and "Items and Skills"

If I remove and resocket the jewel it does not work. 

If I delete the jewel and make a new, identical jewel, it DOES work.

I have the latest version as of time of writing (1.4.167.2)

**Comment by ppoelzl** [comment] 2020-04-09 20:12
Known issue, duplicate of #664 , will be fixed in the next update.

**Closed by ppoelzl** 2020-04-09 20:12 UTC
Labels: duplicate
