### ISSUE TITLE
Awakened Void Manipulation incorrectly +1 level to Impending Doom support gem

### ISSUE THREAD

**Issue by etios365** [PathOfBuildingCommunity/PathOfBuilding#5496] opened 2022-12-30 04:38 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

Awakened Void Manipulation +1 level to supported chaos skill gems shouldn't affect impending doom support gem

### How does Path of Building behave?

Awakened Void Manipulation +1 level to supported chaos skill gems added 1 level to Impending Doom support gem

### How to reproduce the issue

1. Select Temporal Chain as main skill
2. Add Impending Doom support gem
3. Add level 5 Awakened Void Manipulation support gem

### Screenshots

![image](https://user-images.githubusercontent.com/121654412/210034923-c81c545b-c5c5-4eb1-8fa5-49e08719b03f.png)

**Comment by QuickStick123** [comment] 2022-12-30 05:24
Functional duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2719

**Closed by QuickStick123** 2022-12-30 05:24 UTC
Labels: bug
