### ISSUE TITLE
Ashes of the Stars

### ISSUE THREAD

**Issue by Krinlok** [PathOfBuildingCommunity/PathOfBuilding#5984] opened 2023-04-08 22:43 UTC
The Ashes of the Stars Unique Onyx Amulet. The mods, +1 Skill Gems and +Quality are not working as of Version: 2.27.1.

**Comment by LocalIdentity** [comment] 2023-04-08 22:49
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5976

**Closed by LocalIdentity** 2023-04-08 22:49 UTC
