### ISSUE TITLE
Skill mana cost incorrectly rounded up

### ISSUE THREAD

**Issue by aiolos01** [PathOfBuildingCommunity/PathOfBuilding#5299] opened 2022-12-11 21:51 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the wording ingame?

Frostblink level 22 has a mana cost of 24. Supported by 2 130% gems the final cost is 40,56.
PoB displays a mana cost of 41 which is incorrect. The game shows 40. It seems mana cost is always rounded down.

### What is the wording in Path of Building?

The game shows a cost of 40, while PoB displays 41.

**Comment by Lilylicious** [comment] 2022-12-11 22:25
Duplicate of #5268

**Closed by Lilylicious** 2022-12-11 22:25 UTC
Labels: bug:accuracy
