### ISSUE TITLE
Support for High-DPI scaling.

### ISSUE THREAD

**Issue by lavadrop** [PathOfBuildingCommunity/PathOfBuilding#4545] opened 2022-07-09 22:12 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Text and UI elements should scale according to desktop DPI settings.

### What is the actual behaviour/value?

Text is unreadable and UI elements detach from background tree graphic. Running the linux flatpak version.

### How to reproduce the issue

Open program.

### Character build code

```shell
N/A
```

### Screenshots

![Screenshot from 2022-07-09 17-08-57](https://user-images.githubusercontent.com/6760790/178124175-1f8d83de-801a-48a9-ad12-5de183f6e0b5.jpg)

**Comment by Nightblade** [comment] 2022-07-10 02:17
Possible dupe of #218 ?

**Comment by Wires77** [comment] 2022-07-10 02:43
The flatpak version is not supported by this team.  Linux users have had success running it under wine (which the flatpak seems to use under the hood) but you may need to adjust the DPI or resolution Wine uses in some cases.  A flatpak repo for PoE I found also suggested trying winepak: https://github.com/winepak/applications/tree/master/com.pathofexile.Client

We'd love to change our graphics API to support all kinds of resolutions and font sizes, but it's out of scope for us at the moment.

**Closed by Wires77** 2022-07-10 02:43 UTC
Labels: bug
