### ISSUE TITLE
Explosive Arrow Base Radius

### ISSUE THREAD

**Issue by Lothrik** [PathOfBuildingCommunity/PathOfBuilding#2713] opened 2021-05-01 12:25 UTC
Explosive Arrow specifically states that it gains +2 to Explosion Radius per Explosive Arrow on Target, capped to +12:
![](http://puu.sh/HD2gA/97961e564b.png)

The cap of +12 is not implemented at all.

This is the end result with a 20 fuse Explosive Arrow explosion in PoB:
![](http://puu.sh/HD2jr/6aa9dce3d2.png)

Note the base radius of 55 (15 + 40). The correct base radius here should be 27 (15 + 12).

**Comment by pundm** [comment] 2021-05-02 09:12
Duplicate of #2434

**Closed by pundm** 2021-05-02 09:12 UTC
Labels: bug
