### ISSUE TITLE
impending doom incorrectly receiving gem level bonuses

### ISSUE THREAD

**Issue by umn-anon** [PathOfBuildingCommunity/PathOfBuilding#6012] opened 2023-04-10 19:42 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour in-game?

in-game, Impending Doom does NOT receive gem levels from gems like empower/Woke Added Chaos lv5, amulet gem levels, shield/weapon mod "+x to level of all chaos spell skill gem". 

It DOES receive gem levels from the corrupted implicit +2 to level of socketed AOE gems", and presumably from the similar implicit for +1 to level of all socketed gems.

This bug has been listed before, but all previous tickets were closed as not being worth the effort for a one-off gem issue. Given that we now have a similar gem behavior in Prismatic Burst (i.e. being a support gem that grants a damage skill), and the fact that impending doom is gaining popularity as a viable build, I would humbly implore the dev team to reconsider the value proposition of fixing this issue.

### What is the behaviour in Path of Building?

In PoB, Impending Doom receives gem levels from all the above listed sources as if it was a chaos skill gem.

### How to reproduce the issue

1. add some curse and support with impending doom
2. Verify that impending doom has no gem level bonuses by hovering over the gem
3. add awakened added chaos support lv 5
4. Verify that impending doom now has a +1 gem level bonus in tooltip panel
5. rinse and repeat for any other sources of chaos / global gem levels

### Character build code

```shell
https://pobb.in/7KWiVpSJVgSm
```

### Screenshots

![image](https://user-images.githubusercontent.com/55676303/230983593-93fde5e1-2fed-493a-913f-2edf2bb56e6f.png)

**Comment by QuickStick123** [comment] 2023-04-11 00:20
Essentially a duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2719

Please use the issue browser like you say.
> I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

**Closed by QuickStick123** 2023-04-11 00:20 UTC
Labels: bug:behaviour
