### ISSUE TITLE
Paid exposure for guides is very bad for new poe pob builders

### ISSUE THREAD

**Issue by GioGr** [PathOfBuildingCommunity/PathOfBuilding#7941] opened 2024-07-25 15:24 UTC
a guide does not have be good,
just the maker just has to have a lot of money 
and now its at the top.

are you sure you want this on POB?

**Comment by Wires77** [comment] 2024-07-25 18:52
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7944

**Comment by aminoginji** [comment] 2024-07-25 20:02
I've seen this comment 2 times now and i don't see how this is relevant as when you search for Latest builds as well as Trending it sorts them by how you want them to be sorted it doesn't pull promoted builds to the top of the list. If it did it wouldn't be sorted by upvotes for trending as some one with a "newly promoted build would be on top" Unless I'm mistaken I've only seen promoted builds not based off of Latest and Trending in meta, and under youtuber in the menus

**Closed** 2024-07-25 20:04 UTC
