### ISSUE TITLE
missing unique

### ISSUE THREAD

**Issue by makleikle** [PathOfBuildingCommunity/PathOfBuilding#3084] opened 2021-08-03 08:26 UTC
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Usurpers Penance is missing from the latest pob version

### Describe the solution you'd like

to add it

**Comment by PJacek** [comment] 2021-08-03 08:51
Duplicate of #3058

**Closed by PJacek** 2021-08-03 08:51 UTC
