### ISSUE TITLE
Adding nodes for "Glorious Vanity" timeless jewel gives crash error when you input "Legacy of the Vaal"

### ISSUE THREAD

**Issue by rng42069** [PathOfBuildingCommunity/PathOfBuilding#2075] opened 2021-01-29 19:53 UTC
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
* **What were you trying to do?**
* **What steps will reproduce the bug?**
* **Does it reproduce every time?**
* **Provide a build code:**
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by rng42069** [comment] 2021-01-29 19:55
![image](https://user-images.githubusercontent.com/78232798/106321143-91695c00-627c-11eb-92bf-99fdb35d8a7f.png)
This shows when I want to check my stats with this specific node that I want to add from the game to PoB
![image](https://user-images.githubusercontent.com/78232798/106321231-a7771c80-627c-11eb-8e41-572ec8b38d63.png)

**Comment by Wires77** [comment] 2021-01-29 21:45
Duplicate of #2061

**Closed by Wires77** 2021-01-29 21:45 UTC
Labels: bug
