### ISSUE TITLE
Inactive Large cluster Jewel

### ISSUE THREAD

**Issue by Dantes09666** [PathOfBuildingCommunity/PathOfBuilding#894] opened 2020-05-11 08:29 UTC
Hi. You can see: Dantes09666 / Frostiko_Dantes

My large cluster is inactive but without it other medium cluster are fine and active.

**Comment by ppoelzl** [comment] 2020-05-11 08:41
Duplicate of #820

**Closed by ppoelzl** 2020-05-11 08:41 UTC
Labels: bug
