### ISSUE TITLE
Import throws error - attempt to index a nil value

### ISSUE THREAD

**Issue by Unknown-Guy** [PathOfBuildingCommunity/PathOfBuilding#5576] opened 2023-01-10 16:39 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

![image](https://user-images.githubusercontent.com/640231/211607125-d48068a0-4d75-4f9a-934a-ed23bdc33239.png)

### What are your system specifications and configuration?

 Operating System: Windows 11 Home 64-bit (10.0, Build 22621) (22621.ni_release.220506-1250)

### How to reproduce the issue

Trying to import character for account `1_mana_left` and  character `AllenIvoryson`, pressing `Items and Skills` throws error

### Character build code

```shell
Build code from ninja works fine poe.ninja/challenge/builds/char/1_mana_left/AllenIvoryson
```

**Comment by tuc3** [comment] 2023-01-15 18:05
This looks to be an error with having an abyssal jewel socketed in the weapon swap. I had this issue importing that character and my own and solved it by removing the abyssal jewel before importing.

**Comment by QuickStick123** [comment] 2023-01-16 00:14
Duplicate of #5592

**Closed by QuickStick123** 2023-01-16 00:14 UTC
Labels: bug, duplicate, crash
