### ISSUE TITLE
Summon Holy Relic's Boon Aura not Working

### ISSUE THREAD

**Issue by b1osx** [PathOfBuildingCommunity/PathOfBuilding#984] opened 2020-06-16 09:51 UTC
Ticking "Enable Holy Relic's Boon Aura" neither adds life regen to the player nor any minions. 

Tested also on a fresh character with just a Tabula Rasa, a Marble Amulet for player regen, allocated Sacrifice for minion regen and just Summon Holy Relic as well as Summon Flame Golem to check the numbers:

[Without the Boon Aura.](
https://i.imgur.com/cOYDOnH.png)

[With the Boon Aura.](https://i.imgur.com/1GmWqBI.png)

**Comment by ppoelzl** [comment] 2020-10-26 23:01
Duplicate of #187

**Closed by ppoelzl** 2020-10-26 23:01 UTC
Labels: bug
