### ISSUE TITLE
Error prevents saving of Builds

### ISSUE THREAD

**Issue by stgmihnea** [PathOfBuildingCommunity/PathOfBuilding#4954] opened 2022-08-21 08:19 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Expected PoB to load normally without errors.

### What is the actual behaviour/value?

Hi there, the moment I start PoB I get a bunch of errors in the green loading box culminating in this error at the end:
![PoB Error](https://user-images.githubusercontent.com/64543231/185782126-a0486f89-b4e5-4e49-8a36-400148d5758e.png)

I can ignore the error temporarily but whenever I try to save a build I get it again and the builds won't save.

### Character build code

```shell
Error appears before attempting to import anything but I was trying to use this in PoB:

https://pastebin.com/Vt6GxkZ4
```

**Comment by QuickStick123** [comment] 2022-08-21 08:26
Can you provide screenshots of all the different errors and make sure you are running 2.21.1

**Comment by stgmihnea** [comment] 2022-08-21 08:31
I am running 2.21.1, just installed it fresh today (was getting same error with previous version from 3-4 days ago as well).

These are the other warnings I get on loading:
![PoBGreenError](https://user-images.githubusercontent.com/64543231/185782748-df3a95e3-b753-4dc6-ad06-74b26cd34f36.png)

**Comment by QuickStick123** [comment] 2022-08-21 08:33
Those errors are unrelated. Does the issue persist if you start in administator mode. Maybe poe doesn't have access to the save location?

**Comment by QuickStick123** [comment] 2022-08-21 08:34
You can try the portable version and see if that crashes in the same way.

**Comment by stgmihnea** [comment] 2022-08-21 08:38
I've tried to run PoB as admin, the error persisted. However, when using the portable version the error doesn't appear anymore and I have checked that build importing/saving works properly on the portable version.

**Comment by QuickStick123** [comment] 2022-09-16 01:14
Closing as duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4890

**Closed by QuickStick123** 2022-09-16 01:14 UTC
Labels: bug, crash
