### ISSUE TITLE
PoB show life reserved when Aura is supported by Arrogance even when Mortal Conviction is taken

### ISSUE THREAD

**Issue by mentatss** [PathOfBuildingCommunity/PathOfBuilding#3142] opened 2021-08-13 15:28 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

No life should be reserved when only one aura is activated with Mortal Conviction, even when it's supported by Arrogance.

### What is the actual behaviour/value?

When the aura is supported by Arrogance, PoB shows that life is reserved (Mortal Conviction already taken). Removing Arrogance solves the issue.

### How to reproduce the issue

1. Take Mortal Conviction
2. Active one aura (at this step PoB shows no life reserved)
3. Link aura to Arrogance (now PoB shows life is reserved, even though it isn't)

### Build code

```shell
https://pastebin.com/7x8VrtbP
```

**Comment by pundm** [comment] 2021-08-13 15:47
Duplicate of #1007

**Closed by pundm** 2021-08-13 15:47 UTC
Labels: bug
