### ISSUE TITLE
Lua error when trying to compare trade items.

### ISSUE THREAD

**Issue by adaroqui** [PathOfBuildingCommunity/PathOfBuilding#5983] opened 2023-04-08 22:12 UTC
Upgraded to 2.27.1 today. Issue was also occurring before the upgrade.

Can't search trade for item upgrades. It always pops up with this lua error. This happens on any kind of imported character.

I also can't seem to manually change the realm / league on the top of the trader window.

![image](https://user-images.githubusercontent.com/29459738/230744497-ad6f48af-e292-4b01-b51b-b599c6e9cbe8.png)

![image](https://user-images.githubusercontent.com/29459738/230744672-e6f5c06d-dfc6-4662-93d6-bffa3facb5cb.png)

**Comment by QuickStick123** [comment] 2023-04-08 23:10
Your session id probably expired and is unrelated to the update.

**Comment by QuickStick123** [comment] 2023-04-09 01:43
Pretty much a duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5621 which is a similar issue with an expired session ID.

**Closed by QuickStick123** 2023-04-09 01:43 UTC
