### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by 4monkw84** [PathOfBuildingCommunity/PathOfBuilding#4481] opened 2022-06-23 03:24 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Application continues running over course of normal use

### What is the actual behaviour/value?

Application will crash due to insufficient memory 

```
--- Render Shutdown ---
Unloading resources...
Deleting context...
Renderer shutdown complete.
Engine shutdown complete.

--- SCRIPT ERROR ---
Runtime error in 'C:\ProgramData\Path of Building\Launch.lua':
not enough memory
```

### How to reproduce the issue

Import or create a new build (import tends to crash faster)
Using scroll wheel, cycle between equipment in a given slot
Repeat until application crashes

Problem persists if done rapidly on a new instance of the application or over the course of an hour session of incremental actions.

### Character build code

```shell
eNqtWm1z4jgS_jz8ChVVe7VbtwGMgSQc2S1CyEtdkslCMnP3aUrYDWgjWx5bDsNu7X-_lmwHJ8OLrL1MVcbI_a5H3a0mg1-_BZy8QJwwEZ7VnUarTiD0hM_CxVn96fHy6KT-6y-1wQOVy4_z85Rx9eaX2oeBfiYcXoCf1U-RTdJ4AfJTIcr9gmsRDeUSRHhHfxfxlfDP6vcihDqZ0dBnsvjkcZok9zSAs_rUQ-Y6oYkHoT_arGeEAWXhVHjPIK9ikUZob528MFjdCR9pbu4ePk4eS0pZWFaKRn8YPHC6hngqqSQJ_jqrD9F3uoBrJlEU5SnK6XUbvXpzO_k0AvBfKZ1dZA8xjOdz8CR7gVHM5GhJQw9e-bq7-KrS3qVcsogziDc2NXZyPApJ-cXD1MjTjFhswtLaRfmZyeU5x7iYir5ZhExCmfrYbRz3jrsnp52267on-zR9z-y4pw33lbuzj_lBsESEVUNgYeko5RwPSplzZ_xGIpix8G34DH26oyEdicRgk27ZHMwox1MzugkeGzNKZeUDxHikpbmxlRhyDVPwBKaNKjqqsJT8sFNmwTme2jBYKJrKTQ7p7EwhF_Dtlaq9Gxrw9Q3h7kwQSgNxF_AipK4Lh5zQJ3Z8_bA5R2233eiedk6PW8ctd3e-Xq4T5lF-R7-xIA2wGjzSZ9godJzOnr1dLGWIh30X87HT3p2TL1kMVowjwX07xiUViRWnQrFRSLBKen1FfRN6ZofjKYwhgfilXFz3xnwOEwS3Kt4zDsY8GzX5Idlwtg4oW0Bo5sotgLe8wk5lQiWYJZVNsT_p7I2pIjaKqSLcEtM98t9yVAiPYnwbHqfVaO-jrhihzzT2DfJeCPFiPV0y4BWpcyCtRzQySJNqG8rcRtvxVp0RlMosFQM2fqFJOV2euPu9ycjNcAXY6CGDD-_a1NbuVlj8rhphXo1tGAcijQ33IyM2cqDI9Bc0wP5lAn7qmZWW137-DsES4NnQVwG8eZQ6b2dn6jzneG0x9R0lc16JYygl9Z4vhL-ASkqqc0zTKMIkoQBjyqdK3AQSVupCjnoG1B_xUBqdSVUKzRVsqI0VvJZ4cy3vWMx9UdW5gjMbcmMVl3g3MbqYPIgVilyqe31SjRrbi1eGncnnMobwj7Wx_DfkRgrGoZ_GCqPGOt5zfK9m0NSDD_V0E0QilnpxRLmXaJE3YZRKEuqhRcAS78ssnc_VfKKOKmI9VRlfXo5HjzefxrkVZZbkmXH-JUyDmbrSZ_9v5gxT0MmKeIJzGiXgn9VDxuuE4cNUcU4xPXvSgBobvywDGtBi_fVihuE7TKrmBQam6iHKYTo14TAgw32gHExD9LiOQO14YhalPMkdptUTEAO6bARh4pYedJgEHTy6NqB77SIMaMcchoyrMmcSpzsEelYfTaixWMVslkojROk7h4EFqos2cKvcJBoh34Qs71UM1OeN2WHKvAKYwA7bBMMtuoA5IJiNDrJODtndMEt7RYob6FOUkARz3xUEyfkaa8mlCui7SVZAJcINgls1In4UKqNST0J8m42M55QnKimWxZzVZZziog9zmnK1_ltKOZNrPR0oLecytLnJUqxUV5IJUsc7wS25vc3eDLnMZSgthdrMf-WInikPdWOnP2s39WCZhR5PfbzC5vUyV8fpTKmuk4UaQY9EGsrCEASBp-bQEoK-0x_OMHdTufwHjUTyr4RcC2wck5_JlcBF5gM5FwLPC4FQXWH9wveEC9UvZu_eGafsUqZ_GKAzOeMVFzPK24V1WWCO62_eOq_ClZQbja8IqMRyNF0iflb0BV9-LWLd-s4or-SmKlSq68YYZDhqats0SDJsqMfHGIDQzHRN7ORBxw_l8b4ypqUcTRAa6zyJqPCGWDMTdWM9cd06kSiu9NWCc5J_a5CxZzEZ-5gv_XvF18xWnia3-uHDUsoo6Tebq9WqEWH4xRy-4Y2k4YmgGaEYtPJIx-ZIKWoO8ed8MdQ_WlCzkDTIvn5ICs_RG-24clc93AtMa-qdWiw-6GB8YrAiCWAtXU5lrDz8Q4jgv9p7BdRr3I87GuVBVu9ykLs5xLFmXTCMT6zPcLEzivA_RUczUNBL8rCr5ylIjeU0gWwW-BkQjaFeVnqy_gMJ9aHPwTWhWHfXffJ0f_Pb07i2Hce1tzCu5amtT3rd4vmcJsXQE2PdJ04tP4l90m7V8kD2ydWR_lfT7k7gKxK2a1jTOfOYet-qPcZsscDNJ5qEHJP3Jl2m8ZqslhCS8deURRH4tT-xjVtAv9Xo_vXPH9utI7f1E5GCYOghXMhlzen-oE54DGikT4o7HdGtSZn5x96R0_rpB-LpPkCJyOpy7bNStxYp-bfKIjTM132CNSZY_4zC5-iBVG8AjcImUsnPiAhmXaDekoSIh9k6Y6k5ZYvUNYhkWZhEEGPENrafp7G6WaidmEfYU2L4FTSxy5wou4m2HjHR6GbJPB_G7KEopkJNhYXsnGIaynvSPBeh3cGNv2lGc3ztxFYZUmVxGRlxpisa4U6uk4RykqGBdDdqWoXRW1jfs7XN2PZTaTctDdrmywGjzoHLiiyXmPGeiWtkUnubSa5deM2C0P4_sXXsjOzZaevZR9MGTwd24Bqw55ZVFW1BUs9GzwH4YS_xAomNYNf-FDk2-jp2WHDskNc5vD0mga0qdhu8LB03yjtdC3sscqB7SI2_JtmFq-L2bY-yFb66NkxGR9JkI6z87FqHtW2x7z27k-TawdetjrKOfdq3wLRjHXzXBBAdEyILs_9G82O4k_a70LNApf02_A24mKZkxWt4asxJLSI3UTeLtk2KaVuH1zJdmO-njTuuQZwc-23oWEera-ONyXn57o5nDPIDJg2DlG-pbdl1Ey-MeoSiZxf6yxQRztkCKQbN9392-j-7ZF8m
```

**Comment by Wyrade** [comment] 2022-06-24 19:53
Duplicate of [https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/3733](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/3733)

**Closed** 2022-06-24 19:59 UTC
Labels: bug
