### ISSUE TITLE
Unnatural Instinct + Pure Talent 

### ISSUE THREAD

**Issue by Warmachine237** [PathOfBuildingCommunity/PathOfBuilding#7231] opened 2024-01-11 06:14 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour in-game?

Pure Talent only gives the bonuses if the starting nodes are manually allocated.

### What is the behaviour in Path of Building?

Pure talent gives bonuses even if the starting nodes are pseudo allocated with Unnatural Instinct

### How to reproduce the issue

As a non scion path to one the Scion Jewel sockets and equip Unnatural Instinct
Equip Pure talent in another jewel socket

### Character build code

```shell
https://pobb.in/3Fhud9QKlG8d
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/120766081/7254dd2c-f682-484b-b026-73c064a230e4)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/120766081/179d05f7-7018-48a1-bc42-c4cc4ba34c8d)

**Comment by QuickStick123** [comment] 2024-01-11 06:20
It is a duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2488 but since this a nicer issue I will just close the old one.

**Comment by Warmachine237** [comment] 2024-01-11 07:11
Yes i noticed the old issue, but it just had a comment asking to be in the newer format. so decided to make this instead.

**Closed** 2024-01-13 04:07 UTC
Labels: bug:behaviour
