### ISSUE TITLE
Show Node Power option

### ISSUE THREAD

**Issue by ElevatedBachman** [PathOfBuildingCommunity/PathOfBuilding#4980] opened 2022-08-23 20:01 UTC
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Hi
I have been suffering for a long time due to the fact that the building of the node power table using the "Show Node Power" checkbox takes a lot of time. I noticed that every time he counts the whole tree completely. In rare cases, this would make sense, but in fact, the setting for the rendering range of nodes is very much missing. It would be cool to have a line in which you can specify how far you need to count from existing nodes. An example in the picture.
![pobsug](https://user-images.githubusercontent.com/111916542/186260392-7f3da985-e417-4fc0-a84c-060082184d26.png)

### Describe the solution you'd like

Add the ability to control the range of rendering the tree when using the "Show Node Power" feature

**Comment by zulrang** [comment] 2022-08-27 20:39
Just came to suggest this exact feature.

**Comment by QuickStick123** [comment] 2022-12-03 21:41
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4553

**Closed by QuickStick123** 2022-12-03 21:41 UTC
Labels: enhancement
