### ISSUE TITLE
Hollow Palm Technique Cluster Notable not being computed into damage since update. 

### ISSUE THREAD

**Issue by Spazmeister** [PathOfBuildingCommunity/PathOfBuilding#2952] opened 2021-07-22 11:34 UTC
Hi All,

Please see the below:
![image](https://user-images.githubusercontent.com/87811252/126632919-f91b799d-dabf-404a-b89e-35c0b76dcbcf.png)

The attack speed and phys per dex are not being calculated at all into the total damage of the character.

**Comment by pundm** [comment] 2021-07-22 11:34
Duplicate of #2934

**Closed by pundm** 2021-07-22 11:34 UTC
Labels: bug
