### ISSUE TITLE
Curse aura mana reserved node doesn't work

### ISSUE THREAD

**Issue by Akhrone** [PathOfBuildingCommunity/PathOfBuilding#1557] opened 2020-10-01 10:13 UTC
Hello, firstly great work on this fork ;)

I found an issue : nodes as "reduced mana reservation of cruse skills" or the culster node Forbidden Words don't change mana reserved while using a blasphemy setup.

**Comment by LocalIdentity** [comment] 2020-10-01 10:23
I figured this out and will have a fix for the next update

**Comment by ppoelzl** [comment] 2020-10-02 16:23
Duplicate of #1419

**Closed by ppoelzl** 2020-10-02 16:23 UTC
Labels: bug
