### ISSUE TITLE
Skitter Bots scale with increased ailment and chill effects from gear/nodes, but does not in game.

### ISSUE THREAD

**Issue by evovolvo** [PathOfBuildingCommunity/PathOfBuilding#4413] opened 2022-06-02 10:59 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Skitter Bots should not get chill effect increase from nodes on the tree and stats on gear, but it currently does.

### What is the actual behaviour/value?

Skitter Bots gain chill effect from gear and nodes on the passive tree.

### How to reproduce the issue

1. Select Skitter Bots
2. Add chill or ailment effect nodes on the tree or on gear.
3. Look at chill effect for skitter bots on the calculations page.

### Character build code

```shell
eNrtPdty20ayz-FXoFS150W0NHdgfOzd0t1yJEsrSnaSl9QAGIiwQIAGQMlKKv9-egBeABKgIFo52U15UyuTQHfP9L17MAO--dfXUWTd6zQLk_jtFt5BW5aOvcQP49u3WzfXx6-crX_9s_fmUuXDi2B_Ekbmzj97P7wpPluRvtfR2y1bblm5Sm91_nFGiv4KpMYqzoc6ic_V5yQ9Sfy3Wx-SWG9Zror9MJ998yKVZR_USL_dutajcaTSLUtlno79g8Wdd6FOk_EQCG5ZIxXGg8S70_lJmkzGMNiWdR_qh_PEB8jT88uLq-vK4GFcHRwm_8Oby0g96nSQq9zK4M_brT2QgbrV70Igf6-iCdBBW7vNsIOx1v4cjOxg4nAbs_JvGxJQruPxHSnagC9TfRQE2svDe32QhvkB8O3pp2f2XNjzSZSH4whEO4fHO7wN4zrJVXR4OXiadgmZLGSJKWJ8h1JCJJWyVUifwnwIaNUxnoG5H4F8O83PQJ_exmGuO4NfJmGWxM_ifgM2DiZRBA7WaZiDZOSGcZ3jjsPspVpdBKWJXSk_nGQLc24dbz8Fr93Lc-UNRzoGvPh2YWZ0Pdp16N1VxpBtwOcqVgdJtjAc0mqNZ2Gga6CtMzgadIO7ggDQDdJM81KnEKLybghmss9CmI4w0F4CYfA5YzwHpcLHZoNtgHk02ARhg4EGeVqx6lZfuNJfqpCYtUblQ_214mjrCHaEPI0rht6eDYBgDRKT9hneJzmk344x6ujd5RzSlojSHW4LwQilrXMpFQApNRyp6Fx9DUeTEaS2a3WnF6MyYjtoR3JCHQR_19nQIh0Sti7heq8N9GnsLeQq1oaGmzjVmU7vqxl3zRB1lKnBLcZCaxGv9G2Fe8ztHcKcdQhnWnvDE6hirlSuu7lplbyzVlAGuiooh6yj2yAnGKEbxrKY5I5kkiIiMUcOYeuI1EUm-M7aST5TXp9U6neIK7FObx8Hw1BHftVb8VrpVrGqUua8yzh1tjtN7Zm8H92rrBoBMBZPONYUo8pMuyVqqLEAwddLZaag7bVs8tlUstEz8fbSUTKpxGUbMbqWjxKhppNWPi6Hj1noQZWmRpD0r7Q_8Wpx02k1gnldfp7ca1MHFVU9dB6VCpq0TnQ_grZlSQRErGErippQWvkqyrO7w8S_1V1RikGejzGYjMcQB4zlLOG1l53HYQqyzsJK9rb508AX0JsdqPFiANFeEhsX6zjAAnh5AIrbg_ftMI-hQu88yhLG8lC4nZehSrKlYWgH4OURWtV4DL1Gp0bjMnkAkkPT3y9qeNYFGgqEpxGOUx3_9rhMH3UCrw5A26OpP0mNiXbmYRljlY83u8UCiPl0OhonaW5FKsv3PC-ZxPk7lQ2BA0zcwFMaKcdmDiKKKV9Q30NUcEa4VFhoV2K2VaBeaRWNQHoH5VczsPJynZa0qE_swNWBFERJTjEnItCBr4ijBRIB1XBZI67LuR2oyMsKzk7j8SS34mIFZRRm3q_uJAjMMskWcJoWizxHx8dHB9enH4-mwqiiZHdhFP0aT0auWSEo_wX_m0IOdBE0LS-JIjXOtP92K1BRBrRD-DgwuAPIF17eCR6qyDIad4KGFO-lIeiyC7BZieg05WKBpgukWTzpBAjGoSLdXWDXj2NtDDHrKrNp8O0CXayPdIIsFzu6MVgso3RTg_bUYyfIec3TCfoo0nthZHJxN6mdgyOUabwbPCTVNHQneUdrK9qaTvMwZX0nBquVakfv6AY4LbI6TWJaWHaBnaatbkYJ5U1ntR3qQIO5d3T7IpyUrWkZs2eB8U3ha5mVQeA-0aNs_xES4bER79Ky2kjlYIh6dGbWua-TeVQ-K9e9p4PVyLzdytMJXPR1oCaRuf7viYrC_LFYW6tcntIwF7Nh8mAKqpKOiQEZ6ObsrLyzF-VTEmaQ2ailAAwfxXr4XlGUFt8LLt9uxWEEcoi9aOJD4zzN9tPLkXLN2FvWrVlAPzBJa3pHx8qNjCBLLrIoMQ2VVmMQM7EGD6ayWBqvxDTz-eENzHBK4iRKXBWR2YAls5hv1W7j-TiG0Klv0nuS5ftJlH9I7qHp_VIyflqEj0JyMGc9Mt_Pda58lavd0xzEsmtks1vMBz41UzFVxTKDXoV3k_RMK_F26yNoQn8trew7U_8tTL0pqf4FnoG_e0YTU-QpnqZBb8_3QxPIVfTT5fM5mwfORjJlhO3E21EcmW5tmi6--8gL-ch-4j9as-WcFQ_BHf3DeUrWp6NREimj_0F4azA3lPanMIYMn4e-Lh5dVeQNzXo3gS9IWCWN3RficWrrB0mcp1DzQJWioY-bLV5t7Djr6XU3tAUdq0rohbmHet8U-yo6Tjzz5HJjtlsIded3TsAqKbw0o0EQesp7_BYWl0k8g7kZ6gtzVZble7cQCMw6R2jM5Rs4XEuuO7fvHsdJPtTpKFR_eTHxTXXEk2o4joDpQ5UNN89HKxS6y7nAtQrkbnbFu9YQqadiPZikZlfC5iVEA5XuzJXYVon-N7eisiYZud9a1VQoPMOKDK5VIP91VU2SZ98kY_yUjD8qFZ1D2afjwVBHm1c0bXSeUUECBaskYZU0XrYBOFBZfhFXF2y-oZhppfWMQgZoWA9D4LakYy1WkV6iLThJlac3VmcduztTJd5LZXOYcWiWnvdVHJunAxsy00KmO1czAtaUwl8VD0BO9_rbAoL9pMwLYzRP-K7Dkd6bpJv3lGtIdZf9uYKpJ5GOu9uV3TWdw4wO4f_f2NkchvdhrPcj86Q6vt3EvAoC1pzCC7NpHhbkZuVoYw6XKXRnbYb5X-wxHaJUbmr6eEM7mgepJirPiVFV_GfJG7_0Gv5G8i7kaXb9JfHS5Cp3phcBIAd23SQ3Oyye0x_OEbPVEYvBNlTfYDIaFWQW5J-twpKG1TbHFbZfuGmeP-DcPFDcxC5w5q9Q6i6DKQWr_rT15YLhfhJrz3Tw38DlKo3u_C1w_xoXfadBrvmfW0LsR8q7ewc5e_NuIgn9wXioU73RUnToW1PsF7aeg0ma6Yu4OMKzefOwSuQZa0j6a55MvOGLOX_R5rpmf8U3Ndk1Cs9sst357o4X0NR8vRSS0V0MFdXGfLVT2mT1dk7k_6EUypJJ6pljasDUa8xenysdZXmajKyPYab71mGqbpM486C0tk4U4EXaBOs_q4J6UmWxZw7dGUFdBJ9UehH_CHfIBuJeFu70U7Ef4zrV2lIlBwUwnu5vgC_Vs4BmRkUFk0GqfZxu4nm79TslhOG-YNTBf_R_55xJ3KfwjZpvhAnS51JSAd8YYlT2CRIUmW82lnZfYCRt8w3QnT6zBSN_wMwT32zD4A7nok8chwMakaQvELNJn1BE7D6nyGA4FEYgNkG0z3BxVwK0IBz1BVDrU0ox6jMCU-oTLjhMFRNs95kkHO4SSWGCyDFEsOQOMEIAnlJJAF4iIvqMYYf1y8lTJBkQhoFwH3OGeJ87BKYhKGOGGcFpHyYEWJwJyeAKJxwoU4oAkiEYi9rUTFLCXYodmwOuFEBHYAfGQjbQhAnCbEtRlmLilIEkOJEgDsIp79uSOv1SvEwKMw-JDCZGTBgxwSyxDVPrg1wlMurhHGbmAIdTUSPbFn3sENKH8ZnTJ4LYwDjMGsRnY7gMIuN9aQCoDdjM3AdWHAkisaWEaYLQYR4C9I1BIJQKCn-xAOlSmDTm0qZ9TBECWIxhqhgkBsxIu5C2zYBHDohEYGCMcpvAFQmDEolB-pjBX0FBnRgBYcId-IuR-cyYRA7M3hbGMgSFERkB6ZbGCJjC8G8DKfgI42COQecYA1Af1Ixwn9tGxEQYxijMmAhHGMlRCXQZGOyWlYNnVA7VmpzhzTyBT338yIcg7X8w9jqN1DdXZ8WHH4Z5Ps5e7-4-PDzsjFU-TAL9NYz0jpeMdsdABhzuVeHrr8xAu3vwv_3bmwP3YuB4Z9mpvHhgn4LLy5P0ty_q7iLc25tcnpwkyj091eNP_t35K2f4cKL2xudq8tFzBUoGh96nH7PRe0qdfcc50x--SBk84J_JAVa_XN9M_h0ifYV_jB8PX_nU1WNn_4z8-vODPfTRh72b7Pj23buHs3M7e3fMY5S-nzz8fPUL-Xh2n3_-_OuX9MexPN3_KhQ7Ufru-EZdnP7o7vEvh-TrweSGkcmvD4Pf3v_45VizD8HhsXN1ds2j8_woHX12x8f46iPO765_iQZnn_e9-wNyfD2--vzT_p5_xx-9-5R8fX_zcZibQZyPlzdXNx6_-Zx9OHv_9fzs6pf735RzdUg-P4pXTHza2zu5ea98yX65JOeXky_u0Bfh4bmdJurLY2oHP9GvhSJ2Z5p4Ux5Yzkq1TL8VMcZosrBaSCZ5mfnwdAP6KmBhpRVAMsvNuxX68AXiZhFiTWA1Hz4kuS7umYuzL0XY_RjqByvTKvWGgzx9uwUfzd5P67ckGf0MM-PmPCkYNpg5-HK5I-2dVvm5Gs83wBnY6XY2Nt3Nlqv8MIT4nBb79WaZwQD-9HbrlTDHwxwG_kDZ9BzXmyLLT5OA-TzQeZGfJpkuT52VHWxxubIFzoAW2_3wdCfBlUohL722rvaujnon0eN4aB0An37vIA1HwJr1Xj_oqHcTh18m2jo9fG3ZAnsuBBpJPaQhGkqkhc9tijwfgYe62g9s7GDtO9J3EIKLVDBXesoXXEGc7BVzKARgiPVOR-Mo9MI8e22h3u-B2TI4SbX_h_yHKRdSELB5QF4swPUwWb1oQVZPLbMu17Ord0fleTvLLNwUajbjLgmBNAhhkETWRyhvgOuPYRr6oWoQAhRfTDEfBcKnkL2AWdfHPiU40K4vFJWKBwSCv88I475Lsa8cj3iO70qXB8qvC4FWhYB7mP_DSs0pG-CizNpWEliDIdisBRp5TCY9jJqkI6oXTWM9u9MumOaxiifDloLutTZqixTrQvxwcXW-d9a7gCLI-gQkqmJDkKs4xzQgrla250r4P1O2DmxiQ40hXIxdqA-UJ0Ckvud5fuB4DiMBkhzSad12hOxNd3oay5l69Gtr_xX81ytgrvSX1xZfki6pCaM4njMTUzN_TUayr4d6lORDs46um3n1mAalu3YglI9cLoFvzB1PIAdTjytpqwBuCcZtRyuXCtdnGHERQMaDvO7WTYSzjXiluJVX7CwUP9-zbQGVSZgWlX7W47QVe8_3MwszK08sii1z-mjmjXClgMx628I232bmZjZw97Zx8a9lNiAATbArUyAXVugVe_MNxjEEoN_atEGbXPYO2gnr6FH3rh-SV4M8iYGTML6tqkNqDwsoJm3pSea4RNEAQTGBoZ4MAu5oxwt86UiqHaK0EMgPOFSRtrYdSVzs87rpkYrQqVMVOun97qUqgBLjj5-hebGORmNzxgdmY12bD5k1VPfaIrwq29LzQDpw1QjAyNN43_w8lFVuEjcSAsESaaAOoYHWRgq9bRtVJV04dnF4UqcKlIp3nOKaNYZAmRXZobfN0IpycM1aSgmbaFDmmsCsZsEUaTFFZQQ-bwmrs2tWG6ur7Xzv5PSgdwCtG2Dl1r8n5pUHYWQi-TEUbHdm2HwIWlQu9NRVPQaSMkgstnKwzbGyqXIg0CLfRjYRrgs1K4I05HmaBbYdaCo1qJy6WHFbI4cENT3WvGqhUVZPSrgWMcpTTsCyZxLPY4_h9ghaxk3LnxT6Lzmb6prKBVpp8NbsCc46tGbp8ganOEjScaatg0mag7P1TgpriP4HqoLsfzNrPw1vzXtlIHqVmw1NLnamn_eB0elxZSh_QQQ7AoTcmx5qKCGnX1pAq6lS-MKRSgmb4oBrjAl3le1z14ESSVPKNXRWttIK-4GHHW57jhPwAAU--CSjpKYwp6IxshwI4b-TihbFUm2xTZxqlJmdyawHNl7zgVIchStO-V3KvPVc2nirjHuMLjx74S1wXRTXi2RduT6PIeZcj2UIg02dVwaDPt86-pqnan61PPdilQdfWuxENNY7aZo8gBRgar3rJI2Vn6wmMz-gWEru2YITbHpQnwYK_My2XQLaEw60ylq7cDFgEEMV144bYAk9o_J8rVqVWNehVU1mgi8ls_bEvU2okeJpnMPF8NZU0T2Onshe3KBAKJ0db57drRcIxeaG4qzbQinbJnnOtLZchVqL9wS1aMFuioWXaXIfGguDMUE6af5bPRKCZvIkzHRVK1QjkDyUVKAP6UG3zwn1tGAEUpd5pwDj1MZMIcdn0F5LqDB8qhQCp0PEdhxULzHs5mBInLobMbouGpJKPanLkMVkg0vVYpteF9ucpvLLNCdFmj8YJncg6IPQHNDU1t5oEulavkCeRkSAcZozoApaKCjGpI94wJAQLuJMayXgq_CljZjtui5VEKGgQKOKuwGtWy5ttc9K3t-LosSDxGs81NPjcpO9BVEySNJR6falvUILqeNbqCJNgKmkc-pU7wJ0GSTWWVpp0oVFL5dj5TF3KBuc1SphYdLEqdcUzcqQTV0jKMP6MZ54dxG41kjn4E_5Sv1l-0pyjIIAKaMOhynHN50yaMfGUNyzQHg-mKoUDpJCEIptH4Bc7EnsceEtt40VPbAXq79IGaWLA-K1ME3QUsVFiwvTpABlSm7Y3RZ0RcLblK2P8Nu4BFjUesYalqfQVldh1BRMBuFoVPI83ZFRpIx5PBloFS2pBxotRzAsTB0FDZft2xDxtY8D13Gh0rIDRTWmGJK1ltCS-Yg5JpcrrjQDL-HL6pmHEuxUVYXqsYRXosXeyCyEzyIJhFtMazqahRjL1LRFdAdO5hfV2PiBDymgqCijRzBL-DezTkejSWwKWRBxcabXSAUc0XKmpXBmhYFZNvGtB6jZ9ByoiQDUVOlkDFoDqCTx19JRhU3BV_dxGa9Nl7S9jBsk4FyfHtNR-ayj2E85r9ygsWyt3CgoalG5GcjWyq0ArbosUz7HAjIK4TZ0QYrJAMo2lxFCIXBKJLUWSvqBzxXcwEiwwCeQZwIIn9ptt4lq5Xb16urVyaurahOL63l_7im1loYX-l9qa4wKTOUMfq6td2FhTbqwhm2n3TWbuqweqWWt2ftLppWAWWlZVJKmmbUu4ixSEyBUGAWbG8WsxaUNAcdw8CGJXxWx2ow_2ytQiQ4datYWa2IN1lR_ftZrfHy2MCveblamtKiYFV9jVgVorZaEekQiKBVdxs2baoLAVlgJKQXkZodIqQLkQmUJLbuPFVWUaO4jgogDmSCoLwI5a8xq36qalbBbzOoaWqFbMKEjPyxV8kmlc7VtY_m0ArZ5g3Ex3ljxox1jWTDKvOws8_MsYRen-cFCoL4vOoeFJVDSbq0tJsCbkgOkgVuYPAS3WTP4Xvn6qb7bdxVSGNKztF0JOQFhbp7lBFBpgj6hBcAYMjsUm8gOHGjdhKBQTSHGAoQ85S7VUaSmtbZcXlHSTRlYdTytODPIG8obWsEElFQ0Sfb8TgFmwoCaRgGIwCo2DdLosUfFZu26eMF2HYsmvZyrLPGGoNGZWkwCCvMlzbybjEYwjBumtQYt8KB4VQxR1xXSCwLfLIU4gnJOuQtXkXkwGkBb5jtEUCjAMAENcfBEBX4l3bp6UIt6ONpYPaKbejBtbr6e0TBguyHwfQJdDcsKsHeZRGE2LJrC8M78U7bMi2gG5tkazYhDaa_Waxdiqb51YhUJC2HX10SURAHiDg6gGtaEIOV50ndtTD3hKldD98HgDnaErwTzCbYhnwaeE2gfqmSy3JS0r4lUV7VkXXnbvENkI6gDEOVNxTB2qkGxvjyxLXFDxFxdkpyl6OUoWo_Ke_dmo9RiOXKeRlsMpLGlLE4zW4MYrBKEpszxNmtfR7UgCE6GFIcg6HsMO4hS12Ge6zLXUxwyGhRAOvAYcxh1A04Dh2lXMmYW-BmR7lKV7LA12WmbylUBCd5wjawKjTnNi02zZYvl9obVlkpKF5t5a7lSX0tDhZpWl8Zmim8RelPreB4COlQiCThlePvqWJnwCu7jwZj5vA4hkrXXITYSC8-lyF5Th0iKq8okkihXUs4834V0pRAUskqBIl0ueMAdSogNKA5xXCJsBgWIxgqbpwfcYcsrA7ZcuzBZ1TRtiaGLxF6sxVnXqRpbPrRqmcWaHvcVjeOTvuk0-iYlTe7X2KhuY9RedyzMQqzaa80QBlEye1HW4szd7Mn87L1uFaDSCukChq3CzHZ0zR_wN8AYF65AOG0j8QWQvQoz22w6pyPb6FQ3JvA2IFYBQm1ApALUIKDFFvU5lN0ONX3lxhy0FRIvQZJVSLO0Ux2XNki9-haDGRxvIVURmWwiVWwfn8-8YbRy1W8BM1PydGPEmk0R1QfYTcIwsrD23Mcsg7Qy3V1SsRQ021DSJMclNNINbcUpVoWx4YSaeHliUsZ5nonS5reNVtk0JbqZeLsJgbwQGttskmKz0TqiNUkTP6HgJnt6QgNlLHzuQA2WJDYZ5wnza0sJHSjTzd0Ib8IJ28wY8Gamx57Wz2qabBDtc-k2GdiGnHeKPKt5_On5bBAF6VNsz_PfM_XXLOWNDIxvgtTJKVcLoW6VUAdO-caCJRtYotjMmehmBkyfb2ds89C_gVXjjYVPu_hmQ9nbre59cuLfUAJ11OVqmd1ZEWIDw9xcE99gMV3jcmMv8YxmorNunpBcSyPSIcqQjcW7YcTors-VfqkDO7SDnFa7rM5qYBtLi2-S7Lr4y2pD2NnKn5hTWzO5O-0mu3aWeZhHQM5LIt9PcrJV3Uv8n9Zqor9Hq4m-t5rfW82_rNVE3zvN53ea6O_QaKLvjeaf3miiLn0m-t5mfm8zn2JmpctE_4FNJvreY1YbR9S9x0R_bo-J_l49Jvqzekz0d-ox0Z_bYqLVFrP8XJw7P0jiILxd-bkp8-NU89fZuUkSaRVPT46v_jaVaVGLt_0Xu6zmL35-Ck0b6NNsPzGvjJn9BtZgqMbzV0fWZlS8U3KQq-Jnw2Y_gDX_XcEqKPTN9R9Ke2omxZvhs_IHlbV_nRR8LAah63gutlQWLzR8ahSY1urvn60ivdmd6eTN7vKPvf8fklzDqA==
```

### Screenshots

[https://ibb.co/xMWYkHM](url)

**Comment by QuickStick123** [comment] 2022-06-04 03:15
The wiki has a good summary of this.
https://www.poewiki.net/wiki/Summon_Skitterbots

**Comment by QuickStick123** [comment] 2022-07-07 09:37
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/3083

**Closed by QuickStick123** 2022-07-07 09:37 UTC
Labels: bug
