### ISSUE TITLE
Crashes after launch

### ISSUE THREAD

**Issue by SilentWarrior1** [PathOfBuildingCommunity/PathOfBuilding#1843] opened 2021-01-11 15:33 UTC
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
* Application crashed after some time after launch (when main winfow is visible) + already got 2 times BSOD.
* **What were you trying to do?**
* clicking any buttons/going to any pob-sub-windows
* **What steps will reproduce the bug?**
* clicking any buttons/going to any pob-sub-windows
* **Does it reproduce every time?**
* yes
* **Provide a build code:**
VERSION[1.4.170.20][2020/12/19]
I have Win10 x64 1809 LTSC. + 5700xt (20.12.1 driver version)
FIXED if  replacing SimpleGraphic.dll from the latest POB from Openarl 
btw. Theese crashes appeared only now (everything was alright for many months using POB fork). Several days ago i got Creative AE-5 plus soundcard (used onboard realtek before)
--- if this helps, i can provide my bsod minidumps : https://anonfiles.com/fdj2V47bpd/Minidump_rar

**Comment by Wires77** [comment] 2021-01-11 17:41
That link isn't working for me, unfortunately.  If you're getting a BSOD, though, that is almost definitely related to your hardware configuration.  We're working on getting a copy of the latest SimpleGraphic.dll source code from Openarl, so I'll check back here when we do and have you test our build of it to see if he has introduced a fix for this problem already.

**Comment by ppoelzl** [comment] 2021-01-11 17:51
It worked for me @Wires77, here are @SilentWarrior1's dumps repacked in a zipfile:

[Minidump.zip](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/5797460/Minidump.zip)

**Comment by PJacek** [comment] 2021-01-11 18:15
Looks like the graphics driver is crashing in the amdkmdag.sys module in kernel mode and that's why it's going straight to BSOD. It could be related to using the latest drivers.

**Comment by SilentWarrior1** [comment] 2021-02-04 16:04
greetings. so is this bug solved now?

**Comment by Wires77** [comment] 2021-02-04 18:36
> 
> 
> greetings. so is this bug solved now?
> upd. just checked with latest SimpleGraphic.dll. still crashing with video-driver crash-restart/BSOD~ing. (rx 5700xt with 20.12.1 driver v.)
> to avoid theese i'm using old dll from original PoB https://anonfiles.com/15acBfFcpb/SimpleGraphic_dll

Will you download the .dll from here and try that?  We're still looking at potentially fixing a minor bug with it, still, but see if this fixes your issue

**Comment by SilentWarrior1** [comment] 2021-02-05 05:54
Tried this new dll. There's no any gpu-driver crashing/BSODs, but PoB is eventually crashing just after starting (9/10 times)

**Comment by Wires77** [comment] 2021-02-05 06:12
Can you try updating your driver?  Looks like there's a 21.2.1 version out now.  If you remove your new soundcard do the crashes stop?  Searching around I see a lot of reports of BSOD with that card, but no one solution.

**Comment by SilentWarrior1** [comment] 2021-02-05 07:03
> Can you try updating your driver? Looks like there's a 21.2.1 version out now. If you remove your new soundcard do the crashes stop? Searching around I see a lot of reports of BSOD with that card, but no one solution.

* Updated to 21.2.1. Nothing changed.
* Disabled AE-5 plus card/restarted (without physically removing). Same situation.
maybe you can make some kind of debugging pob version to see what exactly make it crashes/driver crash?

**Comment by jvanattedev** [comment] 2021-03-15 17:42
**What happened?**
I experience the same thing; crashes right after start-up (every time). If PoE has started, that crashes too; PoE without PoB works fine.
**What were you trying to do?**
Wait for it to start-up
**What steps will reproduce the bug?**
Starting PoB
**Does it reproduce every time?**
Yes
**Provide a build code:**
Win10 64-bit, RTX 3xxx series with latest nvidia drivers

**Comment by zao** [comment] 2021-03-16 06:30
@jvanattedev I've got some questions that might help narrow down what kind of problem you have:

Which version of Windows 10 is this (consult `winver.exe` or the Win+Break dialog)?

In what way does it crash; does it terminate/freeze the program at some particular point of the green startup console, do your monitors flicker like they would when a GPU driver reset took place?

Do you have any optional components of the NVidia drivers installed like the GeForce Experience software?

Has this always problem always been around on this machine or has it recently appeared with a Windows upgrade or a driver update?

**Comment by jvanattedev** [comment] 2021-03-16 07:24
> @jvanattedev I've got some questions that might help narrow down what kind of problem you have:
> Which version of Windows 10 is this (consult `winver.exe` or the Win+Break dialog)?
20H2 build 19042.867 
> In what way does it crash; does it terminate/freeze the program at some particular point of the green startup console, do your monitors flicker like they would when a GPU driver reset took place?
Mostly, the green console thingie runs for a bit, and then I get a black screen and back to windows (PoB shuts down). Sometimes I'm able to get to the tree, then it does the same after af few seconds.
> Do you have any optional components of the NVidia drivers installed like the GeForce Experience software?
I have Geforce Experience enabled; also its overlay.
> Has this always problem always been around on this machine or has it recently appeared with a Windows upgrade or a driver update?
I installed PoE a couple of days a go; PoB started crashing since yesterday.

**Comment by jvanattedev** [comment] 2021-03-18 15:55
meanwhile, upgraded to nvidia drivers 461.92 WHQL, still have the issue

**Comment by SilentWarrior1** [comment] 2021-04-15 14:52
Greetings. 
Any info about fix of the SimpleGraphic.dll?
Still experiencing bsods/system crashes.

**Comment by zao** [comment] 2021-10-20 18:33
Could you please try my alternate `SimpleGraphic.dll` that uses a different method of graphics initialization?
https://zao.se/~zao/poe/pob/SimpleGraphic-portability-g7edabe2.zip

Make a backup of the existing file in your Path of Building installation and replace the file with the DLL from my archive.
The program will think that there's an "update" available because the file doesn't match the original one, so for this testing procedure don't let it update and the file should stay intact.

**Comment by mnefstead** [comment] 2022-02-13 03:27
This doesn't seem to be the same issue described above, but I have also been getting intolerable crashes. The program launches, runs through the initial console scroll, and displays the main window correctly for about 1 second before simply closing. About one in every 20 times I launch it, it stays open and I'm able to use it - until it inevitably crashes again at some later time.

It looks like I have just successfully fixed the issue by copying over the SimpleGraphics.dll file from Openarl's last release of POB (https://github.com/Openarl/PathOfBuilding/releases/tag/v1.4.170). I tried the one linked by @zao above and it didn't help.

I'm running Windows 11 (version 21H2), Intel i5-12600K, AMD Radeon RX 6700 XT with the latest Radeon Software version 21.12.1.

**Comment by Wires77** [comment] 2022-02-15 00:04
@mnefstead your edit made me think it might have to do with the amount of data PoB is trying to load.  How many builds do you have saved?  Can you change the build directory to a different location and see if it still crashes?

**Comment by mnefstead** [comment] 2022-02-15 22:03
@Wires77 The first thing I did when I started having this issue (using PoB on a new computer, for the first time in a couple years) was delete the folder with all my old builds from my hard drive, in case it was an incompatibility with the old files. I currently have zero builds saved.

**Comment by aestil** [comment] 2022-06-02 16:46
I have this problem and it is solved by using the alternative simplegraphics.dll

**Comment by MarkKoz** [comment] 2023-04-07 02:31
This issue is pinned, but the fix isn't here. Download the DLL from here https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4736#issuecomment-1211478087

Don't bother with any of the other DLL links in this issue. They are all dead links, and using the DLL from the original PoB may not resolve your crashes (it didn't for me).

**Comment by ZzZombo** [comment] 2023-12-14 12:21
Is this still an issue? I tried the linked archive but it didn't do anything to solve the crashes. First it used to crash until I removed Lua from my system. Then I successfully updated PoB to the then latest version as of a day ago, updated my whole system, including the NVIDIA graphics drivers, while the program was still running in background, and when the drivers updated it crashed, and now it crashes every time I try to launch it.

**Comment by Wires77** [comment] 2023-12-14 14:05
@ZzZombo (and anyone else finding this issue) we've recently updated the beta branch with a new graphics engine.  Since PoB won't even launch, you may have to reinstall it first, but once you do you can find the checkbox for the beta under Options.  Checking for an update after doing that should install it.  Let us know if that doesn't solve your issue.

**Comment by ZzZombo** [comment] 2023-12-14 14:23
Reinstalling doesn't help me.

**Comment by Wires77** [comment] 2023-12-14 14:32
Since you updated drivers while PoB was running, it might be a config issue, otherwise I'm not sure (there's a reason those updates usually say to close running programs first).  Try deleting this file before launching PoB: `%AppData%\Path of Building Community\SimpleGraphic`

Is there any error when it crashes?

**Comment by ZzZombo** [comment] 2023-12-14 14:46
Did you mean "folder"? Because it's a folder. No errors, just a silent crash after "Loading item databases".

**Comment by Wires77** [comment] 2023-12-14 15:12
Oops, forgot the filename at the end: `%AppData%\Path of Building Community\SimpleGraphic\SimpleGraphic.cfg`

**Comment by ZzZombo** [comment] 2023-12-17 06:21
Doesn't seem to change anything.

**Comment by ZzZombo** [comment] 2023-12-18 04:23
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/10889612/86d729da-de5c-4138-a3a9-88e5224cc0dc)
Managed to invoke the console before the application crashes, this is shown. Can't load any build due to an unknown skill tree version and can't update due to the error above.

**Comment by Wires77** [comment] 2023-12-18 04:33
> ![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/10889612/86d729da-de5c-4138-a3a9-88e5224cc0dc)
> Managed to invoke the console before the application crashes, this is shown. Can't load any build due to an unknown skill tree version and can't update due to the error above.
> 
> P. S.: I don't think any versions of the program has ever shipped with the module it tries to load?

Check out #4736.  From the error message it looks like you have Lua installed through scoop.  It seems to mangle the path in such a way to not let PoB use the bundled version of Lua.

**Comment by ZzZombo** [comment] 2023-12-18 14:58
But if I need to use Lua, what could be done about it?

**Comment by Wires77** [comment] 2023-12-18 15:27
This has a workaround, but the issue seems to be how scoop installs Lua https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/3497#issuecomment-1067449698

**Comment by Wires77** [comment] 2023-12-18 15:48
Found the comment I was looking for: https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5916#issuecomment-1501329815

Looks like this might be fixed in the beta, which may be complicated to have you install without being able to open PoB and let you update to it automatically

**Comment by ZzZombo** [comment] 2023-12-23 02:45
OK, got it working, thanks!

**Closed** 2024-03-22 16:35 UTC
Labels: bug, crash
