### ISSUE TITLE
Gem Variant bug

### ISSUE THREAD

**Issue by 70V07** [PathOfBuildingCommunity/PathOfBuilding#7033] opened 2023-12-14 10:51 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

in skill section POB it should show the ability to select gem variants

### How does Path of Building behave?

instead of this normal behaviour POB in last Afflictions related updates dont show anymore the variants, the only type the user can choose is Deafult normal gem

### Screenshots

https://imgbox.com/xwk2TI67

**Comment by LocalIdentity** [comment] 2023-12-14 11:20
There are no more alt quality gems, only alt variants that are not in poB yet
Duplicate of #6978

**Closed by LocalIdentity** 2023-12-14 11:20 UTC
Labels: bug
