### ISSUE TITLE
Power Report Error

### ISSUE THREAD

**Issue by xondoi** [PathOfBuildingCommunity/PathOfBuilding#3599] opened 2021-10-25 13:02 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When I click the "Show Power Report" function in the skill tree section I should see a list of nodes in ascending order.

### What is the actual behaviour/value?

When I choose "Full DPS" or any other sort of damage on the "Power Report" section of the skill tree, an error occurs when I click the "Show power report" feature 

### How to reproduce the issue

1. Go to Skill Tree
2. Tick power nodes
3. Choose the type of nodes you would like to optimize
4. Show power report

### Build code

```shell
https://pastebin.com/Dk0td1F8
```

### Screenshots

![image](https://user-images.githubusercontent.com/93134793/138696112-e3976057-33cd-4896-a102-bce862e7ac79.png)

**Comment by Challalala** [comment] 2021-11-05 02:27
If you let the "show node power" fully populate the tree and then select "show power report" ->Full DPS you can get around the error.

**Comment by xondoi** [comment] 2021-11-06 11:51
Hello,

Thank you for getting back to me regarding this issue.

I have tried what you suggested, and you are correct, no error is being
displayed if approached as you suggested.

This may be a separate issue, however, the PoB says "building table" but it
never actually loads the data in the table.

Should I open a fresh issue?

Regards,
Nathan

**Comment by jasonbassford** [comment] 2021-11-17 16:58
This is a duplicate of #3464.

**Closed** 2022-01-29 03:24 UTC
Labels: bug
