### ISSUE TITLE
PoB crashes after saving using more than 255 points in the tree or more

### ISSUE THREAD

**Issue by Acytra** [PathOfBuildingCommunity/PathOfBuilding#5370] opened 2022-12-16 01:20 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

![image](https://user-images.githubusercontent.com/28794689/207999848-bc9c005a-888e-4f40-bbf0-3caeac42468c.png)

### What are your system specifications and configuration?

Operating System: Windows 10
Graphics: Nvidia gtx 1660 ti
Path of Building Portable

### How to reproduce the issue

1. Create new build
2. Assign 254 points or less and save (this should work fine)
3. Assign a few more points and try to save again

### Character build code

```shell
https://pastebin.com/S2Vqmuij

Add a point, save and it should crash
```

**Comment by QuickStick123** [comment] 2022-12-16 01:23
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4781

**Closed by QuickStick123** 2022-12-16 01:23 UTC
Labels: bug, crash
