### ISSUE TITLE
Lone Messenger keystone causing bug when hovered in calc tab

### ISSUE THREAD

**Issue by Nimyron** [PathOfBuildingCommunity/PathOfBuilding#906] opened 2020-05-16 17:53 UTC
When Calamitous Visions, Small Cluster Jewel is socketed anywhere on the tree, hovering over it to see details in the tree is fine, but hovering over it in Calc tab (in the list of the more damage modifiers) causes a bug.
Tried to socket it somewhere else, same thing happens.

Here's the build link to reproduce : https://pastebin.com/zPvVz8Cj

![2020-05-16_19h47_34](https://user-images.githubusercontent.com/45174799/82126728-d0b75180-97ae-11ea-950e-d3c3076b8efe.png)

**Comment by AdmiralChopper** [comment] 2020-05-17 10:04
Tried but couldn't reproduce it.

**Comment by LocalIdentity** [comment] 2020-06-22 15:44
Fixed in 1.4.170.1

**Closed by LocalIdentity** 2020-06-22 15:44 UTC
Labels: bug
