### ISSUE TITLE
Mystic Bulwark mana regen per block not working properly

### ISSUE THREAD

**Issue by Pegoth** [PathOfBuildingCommunity/PathOfBuilding#1491] opened 2020-09-27 16:40 UTC
The mod of Mystic Bulwark "#% increased Mana Regeneration Rate per #% Chance to Block Spell Damage" does not work.

**Comment by PJacek** [comment] 2020-09-27 19:56
Duplicate of #1114

**Closed by PJacek** 2020-09-27 19:56 UTC
Labels: bug, duplicate
