### ISSUE TITLE
Swordstorm not count Wings of Entropy (or replica) as dual wield, doesn't show dps. While it works in game.

### ISSUE THREAD

**Issue by PaintMasterPoE** [PathOfBuildingCommunity/PathOfBuilding#8168] opened 2024-08-13 20:44 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the behaviour in-game?

Swordstorm work with Wings of Entropy

### What is the behaviour in Path of Building?

Swordstorm doesnt recognice wings of entropy as dual wield

### Character build code

```shell
https://pobb.in/Lr7MwDMXnFrW
```

**Comment by Nightblade** [comment] 2024-08-14 01:18
Is this a dupe of #8031?

**Comment by LocalIdentity** [comment] 2024-08-14 16:08
Duplicate of #8031

**Closed by LocalIdentity** 2024-08-14 16:08 UTC
