### ISSUE TITLE
Physical damage as extra cold damage also converts physical damage to cold damage

### ISSUE THREAD

**Issue by Norby93** [PathOfBuildingCommunity/PathOfBuilding#3888] opened 2022-01-12 20:08 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

hatred/taste of hate does not convert phys to cold

### What is the actual behaviour/value?

Physical damage as extra cold damage also converts physical damage to cold damage
using hatred/taste of hate make my phyd damage conver to cold.
maybe another element works same idk.

### Build code

```shell
https://pastebin.com/jNfBWuMK
```

**Comment by Lilylicious** [comment] 2022-01-12 20:11
The pastebin code given doesn't work. In addition, testing in my own build with just taste of hate and nothing else other than a phys weapon, I'm seeing no conversion.

**Comment by Lilylicious** [comment] 2022-01-12 20:24
What I believe is happening:

Internally in PoE, "Converted to" and "Added as extra" are functionally the same, except the former removes said percentage from the source type before adding it to the destination type. In effect, 100% phys to cold plus 15% phys as cold can be interpreted as 115% phys as extra cold, 0% phys.

Similarly. PoB displays X as Extra Y under the conversion heading. It does this without removing the source stat.

![image](https://user-images.githubusercontent.com/5985728/149215575-17b83c2e-023e-4f1a-8c03-52eeb8ebcaff.png)

In the example image above, I have manually edited taste of hate to also have a 13% phys converted to cold in addition to the 13% phys as extra cold. We can see in the calculation under hit damage that only 13% phys is being removed (before being added as cold), while we're showing both conversion and added as extra under the conversion heading.

Everything is working as intended, but we're displaying it in a confusing way.

Proposal: Move the current "Conversions" in the above image to the destination stat. Show actual value gained instead of percentage, since we aren't in the source stat anymore. Add a new conversions display in the source stat showing stat loss (in this case, -13%).

**Comment by Wires77** [comment] 2022-01-23 23:46
Closing, as this is working as intended

**Closed by Wires77** 2022-01-23 23:46 UTC
Labels: bug
