### ISSUE TITLE
Awakened Elemental Focus is providing +1 to Summon Skeletons

### ISSUE THREAD

**Issue by Essat1** [PathOfBuildingCommunity/PathOfBuilding#3721] opened 2021-11-04 16:30 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Awakened Elemental Focus should not provide +1 to (Vaal) Summon skeletons. It should only provide the other effects.

### What is the actual behaviour/value?

The +1 to Supported Elemental Skill gems from a level Awakened Elemental focus is providing +1 to (Vaal) Summon Skeletons.

### How to reproduce the issue

1. Equip (Vaal) Summon Skeletons
2. Link Awakened Elemental Focus
3. ???
4. Get +1

### Build code

```shell
https://pastebin.com/8tBLRb4V
```

**Comment by Wires77** [comment] 2021-11-04 16:30
Duplicate of #3709

**Closed by Wires77** 2021-11-04 16:30 UTC
Labels: bug
