### ISSUE TITLE
Dots and Degens Does not account for Damage taken as modifiers

### ISSUE THREAD

**Issue by Warmachine237** [PathOfBuildingCommunity/PathOfBuilding#6840] opened 2023-10-20 19:30 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

Damage taken as modifiers such as from Divine Flesh or Tempered by War affect both hits and damage over time effects. Meaning if a player converts all cold damage taken as fire then DoT damage taken should be the same for Fire and Cold

### What is the value from the calculation in Path of Building?

In path of build converting all elemental damage to fire does not affect the DoT pool shown in calculations. The calculation does not seem to be considering fire resistance and is only counting the cold/lightning resistance.

### How to reproduce the issue

Allocate Tempered by War Keystone from timeless jewel.
Equip Dawn Breaker with 20% cold and Lightning taken as Fire
Equip Purity of Fire Sublime Vision and Enable the Aura in gems.

In calculations tab the Dots and Degens section does not include Fire resistance multiplier and only considers cold/lightning resistance multipliers for the Dot Taken line.

### Character build code

```shell
https://pobb.in/LZqiuRYrcxoc
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/120766081/b0a8e102-c55b-47b9-86d7-f4c303021c3c)

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/120766081/e98af8bf-def7-42f4-b278-031dea83ef80)

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/120766081/1ced18f7-375e-4d9b-a516-fe6f23a2da55)

**Comment by Regisle** [comment] 2023-10-20 21:22
Duplicate of #3632
and Fixed by #6803

**Closed** 2023-12-05 00:24 UTC
Labels: bug:calculation
