### ISSUE TITLE
Text Size on Title of Builds

### ISSUE THREAD

**Issue by Garf412** [PathOfBuildingCommunity/PathOfBuilding#7968] opened 2024-07-26 15:44 UTC
### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### Is your feature request related to a problem?

NO ISSUE, FEATURE REQUEST I have configured my Windows settings for my medicla conditions but the text size of the name of the builds in PoB is just a little small.  any chance of giving an option to increase it at all?

and other text in the app

many thnks

### Describe the solution you'd like

see above, thanks

### Describe alternatives you've considered

N / A

**Comment by Wires77** [comment] 2024-07-30 17:15
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/218

**Closed by Wires77** 2024-07-30 17:15 UTC
Labels: enhancement
