### ISSUE TITLE
Rathpith Globe- Titanium Spirit Shield

### ISSUE THREAD

**Issue by CreazyXX** [PathOfBuildingCommunity/PathOfBuilding#1687] opened 2020-10-23 16:08 UTC
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?** different then in game
* **What were you trying to do?** minion build based on life
* **What steps will reproduce the bug?** wrong stat in the shield missing words
* **Does it reproduce every time? If not, why so?** its forever wrong created item
* **Additional information:**
its should be like this:  2% increased Critical Strike Chance for Spells per 100 Player Maximum Life
2% increased Spell Damage per 100 Player Maximum Life

but in pob is : {variant:4}2% increased Critical Strike Chance for Spells per 100 Maximum Life
{variant:4}2% increased Spell Damage per 100 Maximum Life

soo i loosed all me curency becous that i didnt check it in game its me fault but fix it !

If you receive an error or experience graphical bugs, include a screenshot.
Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.

**Comment by ppoelzl** [comment] 2020-10-23 20:42
Duplicate of #617

**Closed by ppoelzl** 2020-10-23 20:42 UTC
Labels: bug
