### ISSUE TITLE
Deal No Elemental Damage wrongly applies to Minion Damage ( Cold Iron Points, Animated Weapons )

### ISSUE THREAD

**Issue by KasimirFreeman** [PathOfBuildingCommunity/PathOfBuilding#3782] opened 2021-11-18 21:23 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Deal No Elemental Damage implicit **should not affect** Minion Based Elemental Damage (from Elemental Conversion and similar builds).

Detail:
Cold Iron Points - Ezomyte Dagger has a "Deal No Elemental Damage" implicit.
This implicit should not be affecting Minions, particularly Carrion Golems, Animated Weapons and Animated Guardians (they have Physical in gem description, so they should still get the CIP +3 buff).

Source 1: Personal experience running a Fire Conversion Animated Weapons Necro. Triad Grip, Mesh Gloves, converts all my physical minion damage to elemental, in this case Fire Damage. My minions seem to be doing just as much damage as specified with no problem in-game. 

Source 2: Only reference I found in searches, a reddit post from ~2019:
https://www.reddit.com/r/pathofexile/comments/d1mn71/cold_iron_point_interaction_with_minions/eznkbjg/

### What is the actual behaviour/value?

Path of Building claims that minions do 0.0 damage when Cold Iron Points is equipped in Weapon Slot 1, yet everything works fine when CIP is moved to Weapon Slot 2 or removed.

### How to reproduce the issue

PoB Community fork v 2.13.0
1. Insert Cold Iron Points into Weapon Slot 1
Test on Animated Weapons or similar Elemental Conversion Minion builds. Here is a PoB for reference.
https://pastebin.com/ippJRpKK

2. To see damage Disappear, put the Cold Iron Points in Weapon 1, and Matua in Weapon 2, and there is 0.0 damage reported.

3. Remove Cold Iron Points from Weapon 1, and the damage re-appears.

4. Place Cold Iron Points in Weapon 2, and the damage increases compared to the previous step. 

### Build code

```shell
N/A
```

### Screenshots

1. No Minion Damage (CIP in Weapon 1)
https://i.imgur.com/eLNlSxL.png

2. Minion Damage Working (CIP removed)
https://i.imgur.com/u6DGXjG.png

3. Minion Damage Working (CIP in Weapon 2)
https://i.imgur.com/Huojgwa.png

The last screenshot also shows the CIP increasing the damage, so the skill gem buffs seem to apply from Slot 2, but when in Slot 1 it removes all damage from minions.

**Comment by Wires77** [comment] 2021-11-18 22:56
This bug only affects Animate Weapon, because PoB assumes you're animating your own weapon (which can deal no elemental damage).  You can work around this by making another item set and assigning your animate weapon to that one instead of the default

**Comment by KasimirFreeman** [comment] 2021-11-19 04:48
My work around was to comment out //Deal no elemental damage, but your idea may be better. Thank you.

**Comment by QuickStick123** [comment] 2022-07-07 04:10
This is not a bug as if you animate a cip it should deal no elemental damage. I am closing as resolved as creating a separate weapon set fixes this issue.
![image](https://user-images.githubusercontent.com/31533893/177688590-a5355568-2c6a-408a-ae11-4cc5cdd0278d.png)
![image](https://user-images.githubusercontent.com/31533893/177688603-cf0d07b4-ebb2-42b9-92ef-62d72c4a9e77.png)

**Closed by QuickStick123** 2022-07-07 04:10 UTC
Labels: bug
