### ISSUE TITLE
PoB crashing often with following error on different builds

### ISSUE THREAD

**Issue by ashvinih** [PathOfBuildingCommunity/PathOfBuilding#1325] opened 2020-08-16 20:00 UTC
* **What happened?**
PoB Crashing often

* **What were you trying to do?**
Exploring "Tectonic Slam Chieftain Build Guide - Path of Exile: Harvest" of Navandis gaming & creating a different file of similar build
build pastebin
"https://pastebin.com/rwfJjTk9"

* **What steps will reproduce the bug?**
Browse around features like Calcs etc change some check boxes like frenzy, endurance & power charges etc.
a few seconds later app crashes some time app does not even load.

* **Does it reproduce every time? If not, why so?**
Yes

* **Additional information:**
Giving below error message

--- ERROR ---
Critical error at address 7587263Fh:
Access violation: attempted to write to address FFFFFFFCh

**Comment by ppoelzl** [comment] 2020-08-16 20:18
That seems to be an issue that is unrelated to the build you provided and more like a general problem that you experience with PoB.
Access violation errors can often be the result of outdated or unsupported hardware. Please ensure that you are using the latest stable version of all of your hardware drivers, your operating system, and PoB. If this issue persists for you, please post your computer model/computer part labels, graphics driver version and operating system version. While we might not be able to reproduce this error, it can help with troubleshooting and pinpointing the root cause.

**Comment by pHiney** [comment] 2020-08-30 11:23
It doesn't break for me either.

**Comment by ppoelzl** [comment] 2020-09-06 21:58
Closed as the user hasn't responded or provided more information.

**Closed by ppoelzl** 2020-09-06 21:58 UTC
Labels: bug
