### ISSUE TITLE
Wrong parsing of stats when creating custom item from text

### ISSUE THREAD

**Issue by kiwixz** [PathOfBuildingCommunity/PathOfBuilding#6214] opened 2023-05-09 03:11 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

I want to import items from the game buy copying them with Ctrl+Alt+C and pasting it in the "create custom" popup.

### How does Path of Building behave?

Path of Building fails to parse the stats.  It seems to prepend the actual value to the middle of the range, so `4(4-6)%` would be interpreted as `45%` and then I can change it from `44%` to `46%` with the slider.

Removing the range (`4(4-6)%` -> `4%`) for each stat seems to work around the issue by forcing the good value.  Alternatively, removing the value (`4(4-6)%` -> `(4-6)%`) enables the slider but set it to average at first.

### How to reproduce the issue

1. copy item with variable stats from the game
2. try to import them into Path of Building with the "create custom" button

### Character build code

```shell
Item Class: Jewels
Rarity: Rare
Sol Glimmer
Crimson Jewel
--------
Item Level: 72
--------
{ Prefix Modifier "Harmonic" (Tier: 1) — Attack, Speed }
4(4-6)% increased Attack Speed while Dual Wielding
{ Prefix Modifier "Piercing" (Tier: 1) — Damage, Attack, Critical }
+17(15-18)% to Critical Strike Multiplier with One Handed Melee Weapons
{ Suffix Modifier "of Stunning" (Tier: 1) }
11(10-14)% increased Stun Duration on Enemies
{ Suffix Modifier "of Bleeding" (Tier: 1) — Physical, Attack, Ailment }
Attacks have 5(3-5)% chance to cause Bleeding
(Bleeding deals Physical Damage over time, based on the base Physical Damage of the Skill. Damage is higher while moving)
14(12-16)% increased Bleeding Duration
--------
Place into an allocated Jewel Socket on the Passive Skill Tree. Right click to remove from the Socket.
```

### Screenshots

![image](https://user-images.githubusercontent.com/8900147/236984220-d08d6bd7-422c-4680-a970-3981df0256af.png)

**Comment by QuickStick123** [comment] 2023-05-09 03:13
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2684

Please just use regular copy paste (Ctrl + C) in the mean time as advanced (Ctrl + Alt + C) isn't supported.

**Closed by QuickStick123** 2023-05-09 03:13 UTC
Labels: bug, duplicate
