### ISSUE TITLE
Elemental Overload DOES NOT WORK with Perfect Agony

### ISSUE THREAD

**Issue by babanakov84** [PathOfBuildingCommunity/PathOfBuilding#8322] opened 2024-09-27 10:02 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the behaviour in-game?

Elemental Overload DOES NOT WORK with Perfect Agony. As Wiki says, "With Elemental Overload, you will no longer be able to apply ailments with hits, since the Ailments never count as being from Critical Strikes from Elemental Overload will always consider your hits as always being a non-crit for the purposes of applying ailments".
With allocated Perfect Agony and elemental poison or ignite crit builds Path of Building still recommends to use Elemental Jverload due to 40% more ele dmg. 

### What is the behaviour in Path of Building?

1

### How to reproduce the issue

1

### Character build code

```shell
1
```

**Comment by Regisle** [comment] 2024-09-27 10:09
Duplicate of #8137

**Closed by Regisle** 2024-09-27 10:09 UTC
