### ISSUE TITLE
Fertile Catalyst Reduces Intrinsic Mod of Marble Amulet instead of Increasing it at 19 and 20 % Quality

### ISSUE THREAD

**Issue by MediEvil-Q** [PathOfBuildingCommunity/PathOfBuilding#2560] opened 2021-04-16 07:35 UTC
[Here is a GIF on the latest version of the app](https://i.imgur.com/Y6MpGod.gif)

**Comment by Wires77** [comment] 2021-04-16 07:36
Duplicate of #838

**Closed by Wires77** 2021-04-16 07:36 UTC
