### ISSUE TITLE
+2 gems socket and green socket +30% quality not detected

### ISSUE THREAD

**Issue by Romhast** [PathOfBuildingCommunity/PathOfBuilding#5051] opened 2022-09-07 15:07 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

hello, you can easily see what I want to tell in the pictures below, the path of building does not perceive the bonuses that this unique armor provides us in the game.
![image](https://user-images.githubusercontent.com/109461554/188912551-bf1d52e3-f7b1-4dd4-a6bc-af61873bbb38.png)
![image](https://user-images.githubusercontent.com/109461554/188912462-72ab7d58-d5f9-4b4d-962b-e2192dd7fa2a.png)
![image](https://user-images.githubusercontent.com/109461554/188912877-f7601c56-37ee-4b2e-b6c6-c11f4d4cd772.png)

### What is the actual behaviour/value?

![image](https://user-images.githubusercontent.com/109461554/188913172-aa30c4cc-419c-4508-9839-62bfec41f62b.png)

### Character build code

```shell
https://pobb.in/knSRHuPyZNS9
```

**Comment by Paliak** [comment] 2022-09-07 16:23
Duplicate of  #4912 , added in #4981 .

**Closed** 2022-09-07 18:56 UTC
Labels: bug
