### ISSUE TITLE
Exsanguinate not affected by weapon mod Chance to Poison on Hit

### ISSUE THREAD

**Issue by dskinner** [PathOfBuildingCommunity/PathOfBuilding#2855] opened 2021-06-14 19:35 UTC
* **What steps will reproduce the bug?**
A weapon mod with chance to poison on hit does not update exsanguinate's chance to poison on hit.

https://pastebin.com/YVC1TWyX

Import the above and chance to poison is listed at 65%. Note the weapon mods. Unequipping a weapon does not reduce chance to poison on hit. Also note, that enabling the support gem Poison, which gives chance to poison on hit, does correctly apply.

* **Does it reproduce every time?**
Since league start, this has been the case.

* **Provide a build code:**
Version 2.3.0

**Comment by ALT-F-X** [comment] 2021-06-14 19:55
Duplicate of #2301 

Chance to Poison mods on weapons don't affect spells because of parsing inconsistency from GGG.

https://www.reddit.com/r/pathofexile/comments/jxsdf9/chance_to_poison_on_hit_on_weapons_can_be_global/

**Closed by ALT-F-X** 2021-06-14 19:55 UTC
Labels: bug
