### ISSUE TITLE
Wierd error message .png on bootup

### ISSUE THREAD

**Issue by thekalbb** [PathOfBuildingCommunity/PathOfBuilding#5516] opened 2023-01-02 08:03 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

When opening, it sais it cant open some .png´s? see ss

### How does Path of Building behave?

Not sure if this gives any real problems

Sometimes the support gems are real slow to load in the dropdowns sorted by dps - but maybe thats normal?
Also the Show node Power is slow aswell, again not sure if normal.

### How to reproduce the issue

Not sure, but i am opening through a shortcut of Path of Building on desktop

### Screenshots

![billede](https://user-images.githubusercontent.com/20153559/210206177-a22c2159-915f-4712-a1b1-25ed684f35d0.png)

**Comment by LocalIdentity** [comment] 2023-01-02 08:10
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5508

**Closed by LocalIdentity** 2023-01-02 08:10 UTC
Labels: bug

**Comment by thekalbb** [comment] 2023-01-02 08:18
Sorry for Duplicate

**Comment by QuickStick123** [comment] 2023-01-02 08:19
Feel free to open a new issue about the really slow performance with a build but yes the screenshot errors are a duplicate.
