### ISSUE TITLE
Augyre breaks builds in POB

### ISSUE THREAD

**Issue by CuddlyBooBear** [PathOfBuildingCommunity/PathOfBuilding#712] opened 2020-04-01 19:41 UTC
When Augyre is put into a build whatever version you have it on (EO or RT) cannot be taken off. If you take off the weapon and put something else on you will permanently have EO or RT on the build.

**Comment by ppoelzl** [comment] 2020-07-04 12:35
Duplicate of #105

**Closed by ppoelzl** 2020-07-04 12:35 UTC
Labels: bug
