### ISSUE TITLE
Attempting to check "include in full dps" for any skill results in "attempt to index nil value" error

### ISSUE THREAD

**Issue by cdrg** [PathOfBuildingCommunity/PathOfBuilding#3820] opened 2021-12-03 08:21 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

I should be able to use full dps calculation without errors.

### What is the actual behaviour/value?

After importing my character from pathofexile.com, attempting to check "include in full dps" for any skill results in a "attempt to index a nil value" error popup.

### How to reproduce the issue

Import build
Attempt to checkmark "include in full dps" on a skill

### Build code

```shell
https://pastebin.com/RbHBAmzN
```

**Comment by Nostrademous** [comment] 2021-12-08 02:52
Cannot reproduce

**Comment by Lothrik** [comment] 2022-06-25 00:00
I can't reproduce this issue either (as of 2.18.1) -- closing.

**Closed by Lothrik** 2022-06-25 00:00 UTC
Labels: bug
