### ISSUE TITLE
Lightning conduit hit damage incorrectly amplified by Area Damage

### ISSUE THREAD

**Issue by Haqyua** [PathOfBuildingCommunity/PathOfBuilding#4984] opened 2022-08-24 12:01 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Lightning conduit hit damage doesn't get amplified by Area Damage sources like Intensify or Concentrated Effect.
sources : 
- https://www.poewiki.net/wiki/Lightning_Conduit (targeting section) 
- personal test on pvp

### What is the actual behaviour/value?

Area Damage sources amplify Lightning Conduit hit damage on PoB Community Fork

### How to reproduce the issue

Launch PoB 
Main skill : Lightning Conduit
Support : Concentrated Effect

### Character build code

```shell
eNrNW1132jgTvu7-Ch_fNwQIbLuH7B4CJOGc0PBC2r571SNsAdrIEmvJSdhfvyPJBocgIyu92Fy0xppnvjQazch274-XhAZPOBWEs8uweXYeBphFPCZsdRl-fbj--Cn84_dfelMk1_fLq4xQNfL7Lx96-jqg-AlTwIWBROkKy28Fp_YP4LRBTK4xZxP0F09veHwZfuEMh8ECsZjI4ldEkRBfUIIvw3kE4DBAIsIsHuzvG8IEETbn0SOWNynPNpdhKwyeCH6e8BhoxpPp_eyhJJSwslDQ-UNvStEWp3OJZCDgn8uwD6ajFb4lElghmgGf5nm3dfa5GzaOI-YbjOMdcctGNk3xaLnEkSRPeJASOVgjFuEdzsq-Lu0ko5JsKMHp3oCzjg3xwCWiw-l8r3-z1Tn73Kqm53vnnNsovxO5vqLgmhrcFWa8YkTimqApJ4IzDzvKEKspg4xSCHI3Wp4sCKtldT_F6H5pgmOGYpKJ_cxd2EATxNCAi1KUWqPijizxK1Kr8qO5G90MVogbpVJzilNYvdINoJStBcglzHHEIUPUkVEHUrLDT5gHcjT3AXgImst9rmhZqYb4xYFqzKQD1Qz_XSZsdjp2qU9c6j3glBV6SY9up_s02bbm4vVWkAjRCXohSZZAsn9Aj3gvo1sxm6u1ZJAMbND2r_Zke01S7IMbcBp74daICx-gilkHZ8DOF_2maMcsclsIX1mKBU6fShtmtxIwgzBWO_KCYkfEXkS-GEr7-AlRK8xyeVs3c-4wjtY3UITMkMRuSWRH1al2q6J1cqsiPOLWjiOghpMU0OKks89VoJpu-o7S2CHZMZyutvM1wbQmdaH-AG0ccqOajDLaaVJei6sVV2VoTceNnpAop8pmt9oqQ-4WZRhKOQDE-KAWPbfXu_wvVe3SerB-mvAsdZwXQ-xkQJHyhyiB4mWG4yxy21auKDQYrtqDVpTWQvSlRNHjkMcrXEtIfcQ822xg1aspd8WpDWuGBSkVER-7DtT3EOpOq0vtbO4C9tTOAnb7tbuUA4i7LWq3rWHMntxZxK6BnEAySSBt694Tut39krdODvQwTg2MJnRsjKb8GTRfq0Zf1KOGqmRfiVhVSTH7Z-vM_xW5k4ARi7NULQVnGYeIY2IeSALZUoghkigQGKXR-g5m-TIMS7-uEaULWPlwV6F6DX18oq7GyYanUt8cIBoJzXPMNpkMmD77SIiIfiyy5VIdcwBPmeqzmdH19WjwMP42ytUoQ8QjofQHy5KFOhYw_--DZY51LgxEthDm8jL8RvDzXKGGWCJCwTURpxRtBI4vwyWiAiQTuNQ0c7A3khXcNBWUoCb72njtCeycRi84lWAvFAlRSrBVr934CaWMQLU3q2mzcVMnHnZGJocPkJBmn7Z4Sp8T2bmowxurOWqwAgsxg6hVcj56whNyu8ECdlWyJJGK-OopfwBqQ1XhlyiCxRJtK-Y734nsPPQRko2BGbSDzbGQDZ2PVnhVH0VZvWpG7fAhjpDVdjNoB-9KP870WeRxLjuqCk5fONNBDoumT6jaNawzO6J4R2JneC_XODVbkZXTBHJUQVK5cFKyyKR9GZcoKnyl21WLh9SYHWpaMosNaqwiE71qQCwOLdPYWZmOx5rIqqBFvWxxnxmtMKJoGSz658N2BqaCsc5fXg9VrW8olu3rWw3awWZ9vGUh08yRg47lIV5iyEKVwbyjqciiMmNDSHiywqGOrMyu1H_iJDaV-ru4aSOPM9t7qhYvkySO-q02R93JvNf1Bw3OT3F_fl5myd8lkhOMIPHeVmztbpx2pf8tRlQ98OD0fQzfnAu-y04uBWLxUB11OBvaaxT1bU-XFCIQUPje4ERcbaH9uFZJ8-CBSoIk7Hc4uVNPGR-4KsJRJHF6Z5465sKQdlRemUr9MPIV5yJIY7xEGVX3_5chSuRWFf6luzlXRsDVYs2fVYAZPqr6EZBe7-7MSJ_KnIUSUihi3JWroV3Q1Pfym_rxZX-vq_aG1pawiGYxHrO8a8t1oGih9LkbBM9ErgOUYhTEeUWNmToj3a2_A9Y7yR96oGBOfEP5AtFWAcmf3LbOw1fjzWJc9xDjuNQgDzh0Q6o4-dvYPtZ1jfZeTj5FqfH_CidqdALNRAxtUWMswU8N5ayGVlB528ZWz8qBfTvue6dFPGNGmOp51PlQSdVgx1QjJ4SZvJElCYfgmkIZKpFITIj_FC_lwQJy1fkq7Ao4Nmv4ve7aBWEF62MuO-afMosg52Fc0DPzcjpcdWQ6BSyHdvS_HbM_O0rdQvKNw_NLSBo6S5rkqC4fUoyL7KaZNfMcAz_K70goI86VQwXkxm1eh6vzB8Zjlbc6nz6122EggV3p_Yzm5_zVCwM3Wn2d3ZlJWEu5Eb81Gs_Pz2cbBLO5xC-E4rOIJ40NgECnj9rdHxXbRh_-rlZ9_WfMKzj1zBsbopGbCrprM5Vx6uILh2pfjambxQ9tujqTyI9Q5jJV9vzDefKntlVlYdga5QRt8uBTY3kGb-f5G_rVIQFvpLoAKGZJEf6_OPPp6TnPnayuix0kE9g8U_2O0YYzfVvJMWcthtBK9Dr5U16cyxiyoDl_Rpugv9gKgWhg_BN0ACVNQJ4XMXIEeghrucGqqa44bOieCh2z5YRSV5jKmpBrCNTHoO2kUuuYSm0_97o5ofWTYBd-Snb9pHX9vekTTydm4BZDkyHrCjoSSV0fOSfCD_aZJ9X41Gfc9l9FTR95F36x0PSLvIvT0-Pi2Lpsj4WXp-FOeafjoY9HDmyfEhNvA3PEU3P6jnvZK746PiCnJekyEV52drzd2vKY967fSmr7hW-7fpRd-Kd9j5hueju_7RIQFy5EHmq_o_hxnEn_Weh6RKX_NLwjXFxTssI6rhp3Ug_PzVSb1vJJMS1v93qmC_f59DGn7eCnpv80XHh7q-Njjct68Q_yEyr1k4we2dt6jbyH1L2wbkL1GwCcLcnqzfP8w08a9m8B6E8b3r4AgBlOtmNxxYU4SXv4kcZJgPl64yjZlKIIrzmNcVrWJP9mongR4dfyS4fH6NXj7-LdgQLUdsAULzoVmE415PVLYiX9ivPqfDZ6jcPPX_4FD7dtcA==
```

**Comment by QuickStick123** [comment] 2022-08-24 12:03
Pretty much a duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4953 and fixed in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4978

**Closed by QuickStick123** 2022-08-24 12:03 UTC
Labels: bug, duplicate
