### ISSUE TITLE
Ritual of Awakening ignores additional Totems of (Replica) Iron Commander for Life/Mana Regeneration

### ISSUE THREAD

**Issue by Gnomiro** [PathOfBuildingCommunity/PathOfBuilding#2269] opened 2021-02-25 10:59 UTC
* **What happened?**
Life and Mana Regenration doesn't scale if Totem-limit is extended by (Replica) Iron Commander. More Damage scaling from Ritual of Awakening seems to work.
* **What were you trying to do?**
Checking my life/mana regeneration in PoB while at maximum Totem count.
* **What steps will reproduce the bug?**
PoB with settings: https://pastebin.com/zEWqd9zY 
Seeting Totem Limit in Config to 9 mirrors the values of maximum Number of Totems (default) but the real limit shows (and is) at 28. More damage scale corretly. For life/mana regeneration being correct the limit has to be set in config manually.
* **Does it reproduce every time?**
Yes.
* **Provide a build code:**
https://pastebin.com/zEWqd9zY

**Comment by pundm** [comment] 2021-02-25 14:10
Thank you for your report. I looked around the code base to find where its going wrong. I don't have a solution yet but it seems to happen in:

CalcPerform.lua 

```lua
if activeSkill.skillFlags.totem then
        local limit = env.player.mainSkill.skillModList:Sum("BASE", env.player.mainSkill.skillCfg, "ActiveTotemLimit", "ActiveBallistaLimit" )
        ConPrintf('CalcPerform Limit= ' .. limit)
	output.ActiveTotemLimit = m_max(limit, output.ActiveTotemLimit or 0)
	ConPrintf('CalcPerform output.ActiveTotemLimi= ' .. output.ActiveTotemLimit)
	output.TotemsSummoned = modDB:Override(nil, "TotemsSummoned") or output.ActiveTotemLimit
	ConPrintf('CalcPerform output.TotemsSummoned= ' .. output.TotemsSummoned)
end
```

whereas in

CalcOffense.lua

```lua
output.ActiveTotemLimit = skillModList:Sum("BASE", skillCfg, "ActiveTotemLimit", "ActiveBallistaLimit")
ConPrintf("CalcOffence output.ActiveTotemLimit= " .. output.ActiveTotemLimit)
output.TotemsSummoned = env.modDB:Override(nil, "TotemsSummoned") or output.ActiveTotemLimit
ConPrintf("CalcOffence output.TotemsSummoned = " .. output.TotemsSummoned)

```


![image](https://user-images.githubusercontent.com/54453318/109164113-57f01780-777a-11eb-8288-80cb9c31213b.png)

I will see if i can solve it, but no guarantees as i just started and the code base is quite massive.

**Comment by Gnomiro** [comment] 2021-02-25 16:01
Had a short look into the code as I didn't saw the difference based on the snippets. It seems that Replica Iron Commander doesn't have a ModParser line yet. There is only one for the dex-stacking Iron Commander at 378 resp. 2138 in Modules/ModParser.lua

What I don't understand is why CalcOffence seems to know the correct "ActiveBallistaLimit". I tryied to understand when the calculation is done but I'm not sure if I understood correctly when the ModParser is called. 

Another thing I was wondering about is that in CalcSetup, line 50, only "ActiveTotemLimit" is initialised and no "ActiveBallistaLimit". It should probably be initialized with 0 as it seems that the active totem limit for ballistas is calculated as the sum of base totemlimit and ballistalimit. Which seems somehow weird but was done for the seperation of additional totems and ballistas.

At first it looked for me like a problem of calculation order because I assume that in CalcPerform "ActiveBallistaLimit" is 0 whereas in CalcOffence "ActiveBallistaLimit" must be 19. Or is ActiveTotemLimit already 29 before the some is calculated in CalcOffense?
After seeing the missing MadParsing I'm not sure about this anymore...

**Comment by pundm** [comment] 2021-02-25 16:48
I did some more digging:
If I equip Iron Commander, it counts towards the Ballista Limit

![image](https://user-images.githubusercontent.com/54453318/109185757-985a9000-7790-11eb-8c75-7740575c247a.png)

It still only counts 9 Totems/Ballistas, even with Iron Commander
![image](https://user-images.githubusercontent.com/54453318/109185981-ca6bf200-7790-11eb-91e0-9efb84f2cb57.png)
![image](https://user-images.githubusercontent.com/54453318/109186043-d6f04a80-7790-11eb-8cef-df7f0726bcec.png)


If I equip Replica Iron Commander, it counds towards the Totem Limit,
![image](https://user-images.githubusercontent.com/54453318/109186439-35b5c400-7791-11eb-9ce6-4b597f2dbcc4.png)

So it looks to me like it never correctly calculated the Life/Mana regen for any Iron Commander type.

**Comment by ppoelzl** [comment] 2021-03-04 03:46
Duplicate of #693

**Closed by ppoelzl** 2021-03-04 03:46 UTC
Labels: bug
