### ISSUE TITLE
Arcane cloak buff effect calculates incorrectly. Was correct in PoB version for 3.19 patch

### ISSUE THREAD

**Issue by Kuroukihime** [PathOfBuildingCommunity/PathOfBuilding#5529] opened 2023-01-03 16:26 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [x] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation ingame?

Swapping from normal quality to divergent(which gives arcane cloak buff effect) should always give dps boost which actually goes up in tooltip in game.

### What is the value from the calculation in Path of Building?

![image](https://user-images.githubusercontent.com/71021105/210397022-c97f9388-5028-440f-abb5-a0a5706c6957.png)
As it shown on screenshot 20 lvl arcane cloak with divergent qual actually counts as a dps loss, however for lvl 21 gem it calculates correctly.
![image](https://user-images.githubusercontent.com/71021105/210397349-a3643a6c-042f-400b-bc61-87051ecf3133.png)
Same issue with calculation even if i paste "Arcane cloak has 20% increased buff effect" into Custom Modifiers box, however if i change value from 20% to 40% it calculates with positive values.

### Character build code

```shell
https://pobb.in/oMD5Fa1NwCOv
```

**Comment by QuickStick123** [comment] 2023-01-04 00:33
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5336 I haven't gotten around to going over my PR to fix it as there were other oddities related to the fix and method.

**Closed by QuickStick123** 2023-01-04 00:33 UTC
Labels: bug:calculation
