### ISSUE TITLE
Catalyst Calculation for Non-Integer Numbers

### ISSUE THREAD

**Issue by Debugnium** [PathOfBuildingCommunity/PathOfBuilding#1895] opened 2021-01-13 22:56 UTC
* **What happened?**
Numbers such as 1.6% are incorrectly handled for the purpose of the Catalyst calculation resulting in 1.6% becoming 1.10% (one point ten per cent).

* **What were you trying to do?**
Add 20% Fertile catalyst to a Marble Amulet.

* **What steps will reproduce the bug?**
**1)** Create a new Marble Amulet.
**2)** Add the {tags:resource,life} tag to it's implicit to facilitate the Catalyst calculation correctly. _This is a minor issue of its own._
**3)** Add Fertile Catalyst and increase to 20%.

* **Does it reproduce every time?**
Yes.

* **Provide a build code:**
https://pastebin.com/XjdqEh3c (My Pastebins aren't working, it's easy to reproduce though).

* **Screenshots:**
https://i.imgur.com/n6D71Pb.png

**Comment by ppoelzl** [comment] 2021-02-11 03:21
Duplicate of #838

**Closed by ppoelzl** 2021-02-11 03:21 UTC
Labels: bug
