### ISSUE TITLE
Curses dont work in Configuration > Player is cursed by

### ISSUE THREAD

**Issue by 23landgraf** [PathOfBuildingCommunity/PathOfBuilding#954] opened 2020-06-04 08:15 UTC
Any curse in Configuration > Player is cursed by dint work at all, checked it at clear char and on improted (anti curse flas not enabled). This will be realy need for theorycrafting with Doryani’s Prototype body in 3.11

**Comment by ppoelzl** [comment] 2020-06-08 10:27
Duplicate of #725

**Closed by ppoelzl** 2020-06-08 10:27 UTC
Labels: bug, duplicate
