### ISSUE TITLE
Over RAM

### ISSUE THREAD

**Issue by chautv55** [PathOfBuildingCommunity/PathOfBuilding#3862] opened 2022-01-02 09:33 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

During the process of creating a new build, when adding a few items, the system starts to consume RAM and then gradually increases to a point where it is overloaded and the system shuts down, causing the build to be aborted.

### What is the actual behaviour/value?

hope can fix this increase in RAM

### How to reproduce the issue

.

### Build code

```shell
.
```

### Screenshots

.

**Comment by PJacek** [comment] 2022-01-04 15:54
Duplicate of #3733

**Closed by PJacek** 2022-01-04 15:54 UTC
Labels: bug
