### ISSUE TITLE
Determined Survivor causes miscalculation of +1 chance to block mastery

### ISSUE THREAD

**Issue by caseytoomey** [PathOfBuildingCommunity/PathOfBuilding#7978] opened 2024-07-27 12:41 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the value from the calculation in-game?

When using Determined Survivor with a shield with 23% block chance, and the "+1% Chance to Block Attack Damage per 5% Chance to Block on Equipped Shield", in game the calculation for the mastery has this as +4%, however POB is calculating this at 10% (the value that determined survivor sets) 

### What is the value from the calculation in Path of Building?

+10 base Block Chance from the mastery

### How to reproduce the issue

Equip shield with 23% (or whatever percentage) and Determined survivor. Change to a shield with a different multiple of 5 (e.g. 2.5%). In game percentage will change, however POB calculation will not.

### Character build code

```shell
https://pobb.in/CrI0ydIQvXDt
```

### Screenshots

In Game: https://i.imgur.com/crQnj8t.png
POB: https://i.imgur.com/W7tphdL.png

**Comment by Peechey** [comment] 2024-07-27 12:43
Duplicate of #7977

**Closed by Peechey** 2024-07-27 12:43 UTC
