### ISSUE TITLE
Cyclone of Tumult Movement Speed Reduction / Attack Speed from Stages 

### ISSUE THREAD

**Issue by mikemcleanuk** [PathOfBuildingCommunity/PathOfBuilding#8186] opened 2024-08-15 08:44 UTC
### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### Is your feature request related to a problem?

When using Cyclone of Tumult it gains stages 1 stage per 0.5 seconds up to 6 stages.
Each Stage increases the attack speed of Cyclone but reduces the movement speed. 
The only way to change  the stage's amount for cyclone of tumult is on the Skill Details on the Calcs page. But this doesn't update the DPS summaries in the left panel and the movement speed penalty is not being reflected in the movements speed calculations anywhere.

### Describe the solution you'd like

Make setting the stages of Cyclone of Tumult DPS and Move Speed be reflected in the build summary area.

**Comment by LocalIdentity** [comment] 2024-08-15 08:51
![image](https://github.com/user-attachments/assets/bff559ae-27e8-4bf3-adc3-7b5c0495aaaf)
The stages box sets the value for the skill. The moment speed issue is a duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/8140

**Closed by LocalIdentity** 2024-08-15 08:51 UTC
Labels: enhancement
