### ISSUE TITLE
New bases not showing, like Apothecary Gloves or the chaos damage ring 

### ISSUE THREAD

**Issue by nicospadea** [PathOfBuildingCommunity/PathOfBuilding#2643] opened 2021-04-21 21:21 UTC
**Is your feature request related to a problem? Please describe.**
I do not really know, bc i've seen a previous report of a bug with apothecary but i'm not seeing the chaos dmg ring also

**Describe the solution you'd like**
Include those items

**Additional context**
It shows my previous gloves before upgrading to apothecary 

![image](https://user-images.githubusercontent.com/62301023/115623393-84826480-a2cf-11eb-87a3-2c6563d6902e.png)

Actual items:

![image](https://user-images.githubusercontent.com/62301023/115623506-abd93180-a2cf-11eb-8cf1-13390e3f80da.png)
![image](https://user-images.githubusercontent.com/62301023/115623551-b98eb700-a2cf-11eb-9148-2fb26796f593.png)

pd: sorry about the first post

**Comment by Wires77** [comment] 2021-04-21 21:33
Duplicate of #2627 , #2612 

All the new base types will be in the next update

**Closed by Wires77** 2021-04-21 21:33 UTC
