### ISSUE TITLE
Unique jewels that are "limited to 1" still give stats when multiple are used

### ISSUE THREAD

**Issue by Insaneetii** [PathOfBuildingCommunity/PathOfBuilding#818] opened 2020-04-21 11:19 UTC
* **What happened?**
pob gave reduced mana reservation to my build when multiple Conqueror's Efficiency Crimson Jewels were used, when the limit is 1
* **What steps will reproduce the bug?**
Make a new build
Allocate 2 jewel sockets
Allocate some increased maximum mana nodes to have over 100 mana
Put an aura into skills tab and enable it
Go into the items tab and add 2x Conqueror's Efficiency Crimson Jewels
Placing in the first we see the mana reserved go down as expected
Then placing in the second jewel also reduces mana reserved when it doesnt work ingame

* **Does it reproduce every time? If not, why so?**
Yes

**Comment by LocalIdentity** [comment] 2022-06-24 17:50
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/227

**Closed by LocalIdentity** 2022-06-24 17:50 UTC
Labels: bug
