### ISSUE TITLE
Configuration tab multiple loadouts

### ISSUE THREAD

**Issue by ConKou** [PathOfBuildingCommunity/PathOfBuilding#6885] opened 2023-12-02 11:34 UTC
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

It's a feature request. Much like we have different loadouts for skill trees, gear sets and gems, it would be very useful to have a similar thing for the Configuration tab.
It has been sugested here #5933 as well but I don't know if bumping the old post helps with visibility.
Also it would be cool if this worked with Subtractem's build loadouts feature at #6659.

### Describe the solution you'd like

.

**Comment by Peechey** [comment] 2024-01-07 23:56
Duplicate of #2794

**Closed by Peechey** 2024-01-07 23:56 UTC
Labels: enhancement
