### ISSUE TITLE
pdps of a a wepon, which has tempering orb applied, is not getting correctly calculated.

### ISSUE THREAD

**Issue by melderispoe** [PathOfBuildingCommunity/PathOfBuilding#2131] opened 2021-02-07 06:30 UTC
https://pastebin.com/W4yZjKZX

example here shows 998 pdps, but it should be 960 (quality is manually edited to correct amount - 48%)

**Comment by Wires77** [comment] 2021-02-09 21:07
Duplicate of #2056

**Closed by Wires77** 2021-02-09 21:07 UTC
Labels: bug, duplicate
