### ISSUE TITLE
Impending Doom Numbers inflated by faulty level increases

### ISSUE THREAD

**Issue by IceMagma** [PathOfBuildingCommunity/PathOfBuilding#5397] opened 2022-12-17 14:50 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour ingame?

Impending Doom does not benefit from Global Level increases to Skill Gems nor can it be supported by Empower

### What is the behaviour in Path of Building?

Impending Doom does get extra levels from Global Skill Gem increases aswell as Empower

### How to reproduce the issue

Use Impending Doom and a Global Skill Gem increase or Empower

### Character build code

```shell
https://pastebin.com/ruwKa2hj
```

**Comment by QuickStick123** [comment] 2022-12-18 00:28
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2719

This has been a long standing issue people have tried to fix this a couple times but with no luck.

**Closed by QuickStick123** 2022-12-18 00:28 UTC
Labels: duplicate, bug:behaviour
