### ISSUE TITLE
Allocating Legacy of the Vaal via Glorious Vanity crashes

### ISSUE THREAD

**Issue by AkumaNoTsubasa** [PathOfBuildingCommunity/PathOfBuilding#2061] opened 2021-01-27 14:09 UTC
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
* Error Message, see Screenshot
* **What were you trying to do?**
* Allocating Legacy of the Vaal onto Arcanist's Dominion
* **What steps will reproduce the bug?**
* Allocating Legacy of the Vaal
* **Does it reproduce every time?**
* yes
* **Provide a build code:**
https://pastebin.com/m85jkM29
The node "Arcanist's Dominion" 
The node gets to "Legacy of the Vaal"
3% ES, 3% Curse Effect, 8% Physical Damage
https://i.imgur.com/2ZrqJx1.png
Jewel: https://i.imgur.com/ypasErO.png

* **Screenshots:**
https://i.imgur.com/PSY9o1Y.jpg

**Comment by Wires77** [comment] 2021-01-29 21:54
Duplicate of #1619 Fixed in the next release

**Closed by Wires77** 2021-01-29 21:54 UTC
Labels: bug
