### ISSUE TITLE
Mouse-over functions when windows is out of focus/behind another window

### ISSUE THREAD

**Issue by theillchemist** [PathOfBuildingCommunity/PathOfBuilding#1521] opened 2020-09-28 20:51 UTC
* **What happened?**
I noticed when holding Alt+Tab that my mouse was working in the background on PoB and showing tool tips in the preview windows of the window within the windows UI.
* **What were you trying to do?**
Change windows from Chrome to Discord.
* **What steps will reproduce the bug?**
Hold Alt+Tab while PoB is in the background (behind other Windows).
* **Does it reproduce every time? If not, why so?**
Yes
* **Additional information:**
Not sure if I can click through other windows, didn't seem so, but the mouse-over is definitely active.

Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster:
https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases/tag/v1.4.170.12
https://pastebin.com/Gx0aRS7k

**Comment by ppoelzl** [comment] 2020-09-29 00:48
Thanks for reporting! This is a known issue and we're already working on resolving it. Duplicate of #604

**Closed by ppoelzl** 2020-09-29 00:48 UTC
Labels: bug
