### ISSUE TITLE
Raw item data from clipboard doubles sockets, causing SetDisplayItem to fail.

### ISSUE THREAD

**Issue by hsj-1992** [PathOfBuildingCommunity/PathOfBuilding#2649] opened 2021-04-22 07:48 UTC
* **What happened?**

Importing in-game item data from clipboard will cause an Error upon focusing on it - trace provided below. Has something to do with `ItemsTabClass:SetDisplayItem` ... somewhere along the steps of processing parsed raw info, the amount of sockets are doubled. Symptomatically seems like an index-out-of-bounds issue: a rendering component (perhaps?) attempting to access a `socket` stored at index `i` in a container with `size < i`.

* **What steps will reproduce the bug?**

In the `Items` panel -> copy-paste any item from in-game -> add item -> double click to SetDisplayItem -> Error

* **Does it reproduce every time?**

Yep

* **Screenshots:**
![image](https://user-images.githubusercontent.com/83000795/115676147-2623a900-a304-11eb-9689-3ac953bac681.png)
![image](https://user-images.githubusercontent.com/83000795/115676345-5b2ffb80-a304-11eb-824e-d49361ae06e0.png)

**Comment by pundm** [comment] 2021-04-22 07:48
Duplicate of #2594

**Closed by pundm** 2021-04-22 07:48 UTC
Labels: bug
