### ISSUE TITLE
Life regen calculating wrong with catalyst

### ISSUE THREAD

**Issue by InVeRnyako** [PathOfBuildingCommunity/PathOfBuilding#983] opened 2020-06-15 09:19 UTC
I was trying to make Marble Amulet, aplied life catalyst to it and 1.6% life regen per sec "increased" to 1.10% life instead of 2.1% life
[ScreenShot](https://i.imgur.com/gOCElnu.png)

**Comment by Regisle** [comment] 2020-06-15 09:55
partial duplicate of #838

**Closed** 2020-06-15 10:43 UTC
