### ISSUE TITLE
Bleeding damage from elder mod does apply for Spectral shield

### ISSUE THREAD

**Issue by moltrex** [PathOfBuildingCommunity/PathOfBuilding#2344] opened 2021-03-12 10:48 UTC
The elder mod 60% chance for Bleeding inflicted with this Weapon to deal 100% more Damage applied to a weapon seems to apply for Spectral Shield.
https://pastebin.com/5fkWyJs5

**Comment by PJacek** [comment] 2021-03-12 13:23
Duplicate of #2019

**Closed by PJacek** 2021-03-12 13:23 UTC
