### ISSUE TITLE
Shock Ailment Effect Table is Empty

### ISSUE THREAD

**Issue by DylanReedy** [PathOfBuildingCommunity/PathOfBuilding#5265] opened 2022-12-09 15:35 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour ingame?

N/A.  PoB specific issue

### What is the behaviour in Path of Building?

After updating to 2.22.0, I noticed the ailment effect calculation table is populated entirely with 0 for ailment threshold.

### How to reproduce the issue

Create a new character. Add any skill with base shock chance (e.g. Arc). Look at the Calcs tab for that skill, and look at the shock effect calculation table.

### Character build code

```shell
https://pobb.in/9hjsPe2GlK3A
```

### Screenshots

![image](https://user-images.githubusercontent.com/32786043/206737099-f030bcd4-ae4a-4baa-b7f6-b70c7f4bdccd.png)

**Comment by moxaj** [comment] 2022-12-09 15:37
duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5253

**Comment by Lilylicious** [comment] 2022-12-09 15:38
Fix for this already pending.

**Closed by Lilylicious** 2022-12-09 15:38 UTC
Labels: bug:behaviour
