### ISSUE TITLE
Supreme Ego 3.17 - Haste

### ISSUE THREAD

**Issue by mythicsmt** [PathOfBuildingCommunity/PathOfBuilding#4266] opened 2022-03-04 21:50 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When utilizing Haste; Cast Speed, Attack Speed, and Movement Speed modifiers should update to reflect the More Aura Effect granted by Supreme Ego based on the mana allocation of Haste.

### What is the actual behaviour/value?

Only the unused mana (flat and percent) update, which matches the 40% more Mana Reservation of the keystone.

### How to reproduce the issue

Add an offensive attack/spell skill gem to your build.
Note the attack/cast/movement speed modifier values on the left stats panel.
Add a level 20 haste to the build.
Select nodes on the passive tree leading up to Supreme Ego.
Allocate and unallocate Supreme Ego, note the attack/cast/movement speed modifiers do not change.

### Build code

```shell
eNqtWlt32jgQfu7-Ch8_J4DxBdgDu4cQkrAnNGyctrtPPcIIUCNb1Jah7K_fkWSCw3KR1e0D9eWb-2hmJKf7-4-YWmucZoQlPdupNWwLJxGbkWTRsz-93F237d9_-6U7QXz5NL_JCRVvfvvlQ1deWxSvMQU62-IoXWD-ecfJ_QqcVijhS8ySMfrG0ns269kfWYJta4qSGeG7u4iiLPuIYtyzwwiIbQtlEU5mg_1zBYwRSUIWvWJ-n7J8JcWuCd6M2Qwwo_Hk6fmlJJQkZaGg84fuhKItTkOOuJXBT8_ug-logR8IB1aI5sDHaXeCmtf2vVbDc7zArh-nDFcYz_ZEtZbXbPstR_2eIpqkeDif44iTNR6khA-WKInwG5eTwqpixznlZEUJTksa-qcoXhhH9HYSvmFdt-HX3Ibb9NqeG3TO07G96xqnkF8IX95QcJiBlNEiIRyXCVvNVs1pNAKv7QRtt3lO6H-JPRBYgx-IctDwzxJPGMlY8hOOMVB6kFMKK6xMedKrAxZPSfLeqZrmjVGCBizbh67pnoI-kjl-Bz2pzzDUwz3DitNDCjUnOIVqwPUIhLKVCAoJIY4YVJwqMqqQlOwwE2ZAOQxNCAwEhXxfZZqng46_l4FB-xTwFv_YLxr_DLsy0PFPIkcJ11OvDOycUW_NuOxSl_wiq8DwYbK3uVVzA6_TCTpQCDqnO4v0PbQvEiM6Rj9InMfQoF7QK95LdVun67nImb3QxpkOFv0qsKMk0kvET0mKM5yuS40v0CQoUmsfsMZZwme8wImeUo8YR8t7GA2eEcd6S_EN5Z93jsBqOUcAjzin6esRHDrHPyvowDe1zjlwRe98QelMo1IkOF1swyXBVAMtXVkm0XJpmUAzG8okFe0erlFWXtRO67w1Cq6XGxgGHyCY4YMJrnF6SmTfxIxIq5H105jlqWY8FFjLgMlym5EIBhoUQ-N-xrM80iuAb6PumK1xDAkuZ2aY1ktDqeOdor6hMOrr2g6cKa1E0eccRa-3bLbAlYRUpwjz1QpWukgYXbo7koKjM1Jqv9eBBvoJtjMDtNIZHcWq0hWwR2sLeCSLJU9gktWXckCib8sSsayCMXu4tog7mMq1RvIJ2wDLpdgLZ9XQ0Oj3zf2kHilO_tlq838H1xIwTGZ5KnJUW8YhxX_FdOvyrEBcjeIVS7l8OEA0yiTLUbLKuZXIjX5MsujrNJ_PxZ7eBhGpPIgY3t0NBy-jz8NCizJJ9koo_Zrk8VTsdtX_4mhAIUMsi5UVMUrRKsOznp0QalsELkJBGUJ5jrgGGkYwVQE1sNBGo5SA-y5Dxf5ZQ1V52nAZJzb_GjCIA6JY10Uv2xUWEc_0vFQUuctYeSKggVP7cB2z5G5fx-k4QlsN3NsUoYEdUtwnVLQ5HT-NIdFVf9RBQ7NKyTTnWhklx38NDcQgrGFWedbTynwdWDGraIgvBrPLyKID6KQdjAmaIbrFcwzJrLWQZXFQuzRV9nYlritXUWZlUPvucZzdbKGX3AmHHpzhxIhDuuH4UZyqvjBRUVHEcfqoTlnniGaiKJbZ9Gye5vBwhucop-L5nzmihG9FyS49LVhIbbMl24ihRPERqzuDiDw-qjd9ygsWQshOqjJf2CGPYftyrpP30kp5FkuSiOYz2E4W7bIQR9FUiLathTi1HbA84cUbnKApFU5UNhwwFjyF2A9dUKTA3lM2RbS546yMajbsd6-dHUPZGkaiguTQmmzru7JrJCuA9AwohWNxP8YczRBH9REHq-vC9LrUAq7eU0vHHmgeKaPAB6IniQFbrIQ1ttjcGrBkTYqJWSokdvbiiDzM45hB6CdQLznKYpVj_4O1Dyjj5ta-p9a1VlGpVaJYySWgMl9cvqQYW0hFV1I4RU7BTfnAX6jXELkA_NJtUSJF9iQwEWTiCNb3_CvfabWDK6_TabWvmp7XCa78dtt1r5rtZtO5cjvtwIHngedeOb7jeVcdB3Btv-XZFgdFSp8pYKenvkAowSoEwxn0kdlHIbEIyqfnR3nxYcn5Kvu1Xt9sNrUV4ks2xz9gp1aLWFxfARuw71pG4loIqvfh382i3x-w8R_b1_T2iV5vpt-aU_7l5vZpu7il8TUGSE8Kqe-kdNVnjmznT_CRdKdworj4yKAViHfi4e5GuvgzwRsrwzB_LEOeCr_9w1j8d8_2PbW8HzDiY7Qqckq8LEqDWxQGaPS3BNyeysK3i7kA_gVztVt8EenKzCkCKq5DrFIiz7A6wPqC0Yol8rEQpeY2BTwJkoV0t-pDynYznoJZTrhBK6s_3WYZopbykeUDFVdp3dgtoSOkh2RNPbLzqBvGeGao0DFbLih1gymvSHIHqf1quVoqNY-p5Jq5V88Jzf-JzDNTMjCTFph70ySfLkTgAcPQyasKOpJJgYmcC-kHLWotdpHVGbvmq8gxkeeZ5YJjlnne5fDoOLYq22PpZWi4Vt3xDfQxqIHuJTGzraV2HBXDd9zLRvnlmxBpLUmdQBjZ6Ru7tWkQ98BsJblm6etWzzLPvOwb5LRj7HxXJyE8HZCB2j8x_GhG0jwKgUFWmofhJ9JFtyQLWs1Vow818NwzSRZ6k0DlQnHSvYblQj-eJua4Gn5yzMPgGXvLN7FGZ72YJ_kFlfpxTo_0tm692EPK_bDchMqvCSyZkwUguvXDP1X8F4KrwWE=
```

**Comment by Lothrik** [comment] 2022-06-24 22:17
Red text means the line isn't currently supported (making this a feature request, not a bug). Closing as a duplicate of #4290.

**Closed by Lothrik** 2022-06-24 22:17 UTC
Labels: bug
