### ISSUE TITLE
Rathpith Shield + Necromantic Aegis

### ISSUE THREAD

**Issue by netoprax** [PathOfBuildingCommunity/PathOfBuilding#2798] opened 2021-05-19 03:47 UTC
I did some search and apparently Rathpith Globe + Necromantic Aegis should not work together
however, path of building does make it seem like that combo work, it calculates the DPS increase of minions

here is a comment by Chris Wilson about that combo:
https://www.reddit.com/r/pathofexile/comments/bwzm8s/necromantic_aegis_rathpith

this should be fixed because other people may also think it works when it doesn't :)

**Comment by Wires77** [comment] 2021-05-19 03:58
Duplicate of #617

**Closed by Wires77** 2021-05-19 03:58 UTC
Labels: bug
