### ISSUE TITLE
Glorious Vanity increased curse effect small nodes' values are wrong

### ISSUE THREAD

**Issue by Gigachadette** [PathOfBuildingCommunity/PathOfBuilding#5668] opened 2023-02-10 09:07 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the wording ingame?

glorious vanity xibaqua small nodes"2%increased effect of your curses"

### What is the wording in Path of Building?

4% increased effect of your curses

### Character build code

```shell
https://pastebin.com/eBC5JAbU
```

### Screenshots

![image](https://user-images.githubusercontent.com/125015018/218050079-6dfb622d-30dc-4537-967d-2c29d527c669.png)
![image](https://user-images.githubusercontent.com/125015018/218050119-ab59ddb1-a0c9-40de-929d-95ee67a240c6.png)

**Comment by Regisle** [comment] 2023-02-10 09:22
duplicate of #5634, fixed by #5667

**Closed** 2023-02-10 11:45 UTC
Labels: duplicate, bug:accuracy
