### ISSUE TITLE
Lua error when hovering over mastery

### ISSUE THREAD

**Issue by Zodika** [PathOfBuildingCommunity/PathOfBuilding#5489] opened 2022-12-29 10:32 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

Whenever i hover over a master in this build:

https://pastebin.com/rCHGQTZ0

It returns me an error like this: 

https://i.imgur.com/0ODmnvT.png

### How does Path of Building behave?

Whenever i hover over a master in this build:

https://pastebin.com/rCHGQTZ0

It returns me an error like this: 

https://i.imgur.com/0ODmnvT.png

Not sure if its an error with just the build, i have tried converting it to 3.20, and it still happens.

### How to reproduce the issue

hover over any taken mastery in skill tree and error pops up

### Character build code

```shell
https://pastebin.com/rCHGQTZ0
```

### Screenshots

https://i.imgur.com/0ODmnvT.png

**Comment by QuickStick123** [comment] 2022-12-29 10:34
What version of PoB are you using?
Have you tried reinstalling?

**Comment by QuickStick123** [comment] 2022-12-29 10:38
```lua
			for _, node in pairs(env.spec.allocNodes) do
				if not override.removeNodes or not override.removeNodes[node] then
					nodes[node.id] = node
				elseif override.removeNodes[node] then
					if node.type == "Mastery" then
						allocatedMasteryCount = allocatedMasteryCount - 1

						allocatedMasteryTypes[node.name] = allocatedMasteryTypes[node.name] - 1
						if allocatedMasteryTypes[node.name] == 0 then
							allocatedMasteryTypeCount = allocatedMasteryTypeCount - 1
						end
					elseif node.type == "Notable" then
						allocatedNotableCount = allocatedNotableCount - 1
					end
				end
			end
```
Code that is crashing. Node exists but either node.name is nil or allocaatedMasteryTypes is either missing fields or they are nil.

Unable to reproduce on current release.

**Comment by Zodika** [comment] 2022-12-29 10:39
Latest community fork version 2.24.0
Just tried reinstalling, and it still happens

**Comment by QuickStick123** [comment] 2022-12-29 10:40
So if you hover like in the screenshot it crashes?
![image](https://user-images.githubusercontent.com/31533893/209939818-cd981cb2-51a1-4c67-acd7-9b22c2d1ba6f.png)

**Comment by Zodika** [comment] 2022-12-29 10:41
Program doesnt crash, i can just press enter, and i can look at other things fine.

but when i hover like you do above, i get the error popping up

**Comment by Zodika** [comment] 2022-12-29 10:45
Just tried reinstalling again, deleting folder in documents as well.

When i go to the "Endgame Maps" build in the selector in the buttom, it works fine, if i chose any other build from the list, i get the error from earlier.

**Comment by QuickStick123** [comment] 2022-12-29 10:48
Oh yeah I can reproduce on the other trees that are not "Endgame Maps".

**Comment by QuickStick123** [comment] 2023-04-15 07:14
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/6024. I am not sure if this tree was produced from poe.ninja though so maybe there is another issue that produced it.

**Closed** 2023-04-28 09:55 UTC
Labels: bug, crash
