### ISSUE TITLE
Importing rare items makes them appear as unique in PoB, and trying to modify causes it to crash.

### ISSUE THREAD

**Issue by Gumgajua** [PathOfBuildingCommunity/PathOfBuilding#2639] opened 2021-04-21 19:44 UTC
Anytime I try to import a rare item into PoB, it appears as unique. When I manually change the item to rare, and then try to modify the item with any craft, I crash with two errors.

Rare item importing as unique: 
![image](https://user-images.githubusercontent.com/49236864/115611484-2302cb80-a2b8-11eb-9f83-9895165697b6.png)

Crash error 1: 
![image](https://user-images.githubusercontent.com/49236864/115611611-49286b80-a2b8-11eb-8672-75a958d0ab4a.png)

Crash error 2: 
![image](https://user-images.githubusercontent.com/49236864/115611656-5ba2a500-a2b8-11eb-8ad6-a587a773e127.png)

Build Code: https://pastebin.com/UcSE7kMi

**Comment by Wires77** [comment] 2021-04-21 21:20
Duplicate of #2954

**Closed by Wires77** 2021-04-21 21:20 UTC
Labels: bug

**Comment by dc1wh** [comment] 2021-04-22 06:27
#2954 does not exist..... :(

**Comment by LocalIdentity** [comment] 2021-04-22 06:30
Duplicate of #2594
