### ISSUE TITLE
Mana multipliers haven't been fully updated to mid league patch 3.15.0d

### ISSUE THREAD

**Issue by Kroohpyyh** [PathOfBuildingCommunity/PathOfBuilding#3099] opened 2021-08-07 18:55 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

> Bonechill Support now has a Cost and Reservation Multiplier of 130% (previously 140%). https://www.pathofexile.com/forum/view-thread/3152771
Bonechill to have 130% multiplier.

### What is the actual behaviour/value?

As example Bonechill shows 140% multiplier.
![Bonechill](https://user-images.githubusercontent.com/68290738/128611006-d0eec85b-6ec7-4bfb-887d-5fdd34eccb84.png)

### How to reproduce the issue

Compare values in pob vs patch notes / in game numbers. 
I've not gone over every support gem to find all the errors. The one I found this with are: Bonechill and Unbound Ailments Supports.

### Build code

```shell
eNq9Wt132rgSf-7-FT68N1j-dg_ZPSQhKeeElg1pe-9Tj7AFeCMs1pZJ6V-_I9kEl0IY1L23D9SWf_M9Gs2o7f3xbcmtNSvKTOSXHXJhdyyWJyLN8vll59Pj7duo88fvv_XGVC4-zq6qjKsvv__2pqefLc7WjANdx5K0mDP5ecvJ_QqcVjSXCybyEf1LFHcivex8EDnrWFOap5ncviWcluUHumSXnUkCxB2LlgnL0-vdeg1c0iyfiOSJybtCVCstdp2x55FIATMcjT8-PLaEZnlbKOj8pjfmdMOKiaTSKuHnstMH0-mc3dAl_AI3yitg5Vx4YeiR2PW9yI3CTvcw8WTFWPpCRC6c_x9wXLDBbMYSma3ZdZHJ6wXNk50B9jG6c7GjistsxTNWtLTyj1G8_4l5HBzDPgpJ-c140nJ6HDqx7TqOH9mB_7-hE_K03V8yubjiEAgDKYp2OM8zyQyJxyIrRf4L9rVJj4dWLKdZbmThlrS_np9LOqI5vRYlIgT32YzhkIMJDvcA-xuHVFqOWQEVSOKVPYtgIne7yTmuMfu7DTyKu2HfcNzaQC86BhzmEseuDQxf0W4tpC7qGDe-oAL7lRKZvFPYYZ7gmH7KC1ayYt2qrAGSoAnrrvbZrxI-sDlDWnrPWLK4gwPtgUqGS8oXlP-6cxQW5RwFPOAcH0lwhnMU4Z5zLuLXwGe65wstUkStyFkx30wWGeMItPZlmwTl0zYBMh3aJGfaPVjTsr25SPC6NTUclxwMjkAgSNneke7_exTjQvylehh-Hlm_WIqqQEawBqNMHi82ZZbAKaq7wQeWVgmudL20YiOxZkvYE7qPg7Z0F5hjpFccGlpsRwZsOT-Loi8lTZ5uRDpnZwk5i-I2K8BbZdY6-94GCPRHaL6v6QrTrqjNhBWwQ6MF3GfzhcxhssFL2SPB27KgojzDmB0cLeK24hzVBk6esh-Rkk45e2fZ32xvZrs0Ob5VxDMos1AzX4nYWC30iO66EPeoBQXLv2_Q_H-AowQM8rQqVHajZexT_Cym19UzsXoaLleikHrxmvKk1CyH-aqSVq4H2lJ5_mteLadqsqr_3lWJNnKZlcnXaTWbqSm3A8oUejQf3N4Orh-HnwcNyYTpWmUlgnO6KhmMvXnGO1aWNmGeQHVOJAINQ1wzDp_GwrmbFBm47zRUjV4IVfUAfBqnZlMEDOJAOcO66HGzYiriJc5LTXk8jdXDJAJXz34Ys_SEiXE6S-gGgXtpOxDYAWf9jKtTDuOnEaRvfTxi0HBcFdm0kqiM0gMDQgPVOiPMajeHqMzHwJpWBSG-6eROI5uzA5N20CggQ3TDZgySGbWRdXF4pE8sb8retsT19C4qrRJq3x1bllcbOFtulUP3bhx-AMCpU1RQ2VI2oxVX639WlGdy08jcrd_Xl416tVyI50m1WtWc1M4twdv39_WXPpcNEyXmsjOjvGyuALWO-iqxr1s2_a4t0PeJWZ7wKoXhsjlEG3GcTpXojjVXN4_Xospl84Xl6sxMt1bsMVY8ldg3PVCkwd5xMaXc2XKujXLszg-fyZahPimGqkTV1l6JHPYqrHWsv2sTh3qjayc18DEtpLZmzpbq64hJmlJJu0MJ7ugqn3R3zvuZozoG9w17YbzzVVK7AZ7UUaW6bUi6F2Z1JnW1G3Sa1NmhHh8Lxixae0lTkSY28NK-_FW6gyY5nHwg0Y8i1-1YEohb18zEb26Qa3Dt7EEK9TH9oOi69cqnh3v98GYh5ap81-0-Pz9frKhciBn7BgPIRSKW3RWwAZ3ealvfKkHdPvy5Uj_9y0vNqLvl1KuvosuabfOmdVWakMAhEaSTrCPQtBUHcITAvH0aF5DI9TA4z49cBM5x4hjDz4uCMMbwcwlBwGLPxnjFDQKUta7n4awlcYTh53gxxgrXDX2MWJcEOPWC0PERON8nMSZZvNiOMDjikhCDC-MAJTaIIgeFAztQbg5cTDg827NtVDhsjFjiBMRFmeHGqOhCtgSY6MZ-hMkC4sUouXEYhxj1Ii_EiHXikDioZCZxgKporu2jcE4UoSpa6KFqixtHMUpuEGDsIKFDcBUSXYNC3IngoeR6kM-YdPEJFEmMvbbvYvKARJ6LSntQMEQVtSDCnVhhgLLDIQGquhBgiMF5JEDlleOiwmuHro86KmNUkQxigqqRTngoW6B723U78AKNmu7pVCenHj4ImNnUN7W4fdF93ueMPVslo0WymMhCtdDfhVj-Vzd2qlV_z6gc0VXTDatvTZvvNk0-DOQ3GUyQhR5Qtu2oAv5nq19P97VNR6meJ6zuS6uSwSgj8vQLoyuR62Ulp75lqYFHQXra2bbvEy62NzI1zCKTZ7qy-tNNWVJuNW48ELFDpPtkDo7sddSVELI0VOiQLSeUumJcnklyC336k-WiVHIOqeSauRfnBOdfIvPMlAzMpAXm3jTJpxMReM_4kslzBR3IpMBEzon0g8l6ra56z2fsmu8iYiLPM8sFYpZ53unwYBx7LttD6WVoOKru-Ab6GNRA95SYdGPV14Jnhu-wl43yyzchQm1JTCCM7PSN3eoYxD0w20muWfq652eZZ172DXKaGDvfxSSEhwEZqP0LzQ8ykuZRCAyy0jwMv5Au2JKsaJG7Bg818NxDls9xncDZheKoew3LBT6eJua4CD8R8zB4xt7yTazB7BfzJD-hUn9Z8QNnW6_bzJB6FtZDqP4nf5HPsjkget39_zf_D7DqUHU=
```

**Comment by jasonbassford** [comment] 2021-08-07 21:19
Unless somebody has checked in changes since 2.6.0 that aren't part of a "mana"-searchable issue, none of the support-gem mana values have been adjusted.

**Comment by pundm** [comment] 2021-08-07 21:33
Duplicate of #3078

**Closed by pundm** 2021-08-07 21:33 UTC
Labels: bug

**Comment by Kroohpyyh** [comment] 2021-08-08 12:59
Ah tried to look for the dupe, but you are indeed correct it being a dupe of earlier issue.
