### ISSUE TITLE
Death Wish (from Maw of Mischief) doesn't take Minion Life into account

### ISSUE THREAD

**Issue by holmedog** [PathOfBuildingCommunity/PathOfBuilding#1927] opened 2021-01-14 14:53 UTC
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?***
* Death Wish damage calculation does not take Minion Life into consideration for total damage 
* **What were you trying to do?**
* Calculate Death Wish DPS
* **What steps will reproduce the bug?**
* Equip Maw of Mischief in POB and allocate a minion life node - the Minion Explosion calculation does not change
* **Does it reproduce every time?**
* Yes
* **Provide a build code:**
* https://pastebin.com/QEw0LfKm
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by benjaminysmall** [comment] 2021-01-14 16:29
I don't think I have the ability to close this, but I believe it's a duplicate of #1928.

**Comment by Nostrademous** [comment] 2021-01-14 16:34
It's not a duplicate per say, but the solution is that we don't have a way to implement specific minion selection as Death Wish is not deterministic in what minions it applies to. You can specify minion life using Config Tab to and look up the exact value for various minions using the Calcs Tab.

**Closed by Nostrademous** 2021-01-14 16:34 UTC
Labels: bug
