### ISSUE TITLE
Trade for these items finds worse items when allowing for more money

### ISSUE THREAD

**Issue by chx** [PathOfBuildingCommunity/PathOfBuilding#5770] opened 2023-03-14 08:02 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour ingame?

This is PoB only.

### What is the behaviour in Path of Building?

When I search for a 10c bow I get the first item pasted here which is some 16.2% better than Doomfletch, if I allow 60c then I get the second item which is only 7% better.

```
Loath Arch
Citadel Bow
Item Level: 85
Quality: 20
Sockets: G-G G
LevelReq: 58
Implicits: 0
{fractured}19% increased Attack Speed
Adds 187 to 314 Fire Damage
Adds 24 to 383 Lightning Damage
81% increased Elemental Damage with Attack Skills
{crafted}8% chance to deal Double Damage
```

```
Sorrow Reach
Imperial Bow
Item Level: 85
Quality: 0
Sockets: G-G-G
LevelReq: 66
Implicits: 1
24% increased Elemental Damage with Attack Skills
Adds 16 to 35 Physical Damage
Adds 25 to 496 Lightning Damage
45% increased Projectile Speed
45% increased Damage with Poison
14% chance to deal Double Damage
30% chance to Poison on Hit
{crafted}95% increased Physical Damage
```

### How to reproduce the issue

1. Import build
2. Click trade for these items
3. click find best, remove corrupted mods
4. enter 10 to max price
5. search
6. repeat from step 3 with 60c.

### Character build code

```shell
eNrtHWtv28jx8-lXEAZa3CGyzOWbrtNCtvzQJX5EcnLnfgnW1ErimSIVkrKtBPnvnd0lRVLiUtQjB_TaBrhK5Mzs7LxnuJRP_vU68aRnEkZu4L89QC35QCK-Ewxcf_T24OP9xaF18K9_Nk7ucDy-HZ7OXI_e-WfjpxP2WfLIM_HeHhjagRTjcETiTykp9TOQmmI_HpPAv8Z_BOFlMHh7cBP45EB6xP7AjdNvjoej6AZPyNuDHvZHJDyQcOQQf3CWv-EO6I0Jdv1-4DyR-DIMZlNg-UB6dsnLdTAAqO713W3vPreu6-fXBb5_Ornz8JyE_RjHUgT_eXvQhu3jEengCfwXqGFvBqQUXTeUli7L1sFRJd7pLIzijZH7U0IGC3itpckgQwHsXUjOh0PixO4zOQvd-GyMfSdbTBbhbQp7PfNid-q5VM7r4K9WSCNZCHwfxNjr3PUzWKQYqtUyZFVXdKRU4wXxenZ-c-PxqQci3WIVitsd-W5MtkS-C9wo8HfYXx5VrKGZ54Hv1YMNJo-uv5U02iHBt0Nubz08cGdRZtWqCOka-_gsiDJFIasK9I6E4N5xAUNeg9AnTgARIY9i2i0V6UqNlcrxhUu-d4ekPuRGu0kQNuVmu32c9-vCbUx4O4Z6ECTrQfbjLAghBQkJki8FSKSLIDvkNTNkQ6kgmIdEmhCy62fbsKoYzAOKg3yHPAcxZM71omFR4_zqLmPSti3U0lXN0m1LFqeR8TxyHexd41d3MptABL_HTyRbUFM0U2yDo3HsQ_gRISNNR7YI-8INyVaIZ4E32A5xjINIiGmrWpWz5dI40ioSuHNMobu-s0CwK-l-9EMSkfA5l_irVqAoPXAuWmY8eqQ2TrZM4qR1UjRfbET8ZMV5vbj0nhBnfAk1WQ_HGYearLc027JNxbBlrTJrLHB02awUNQXOi7oyX5RI2rbqIazIDJKMYquWpRsy0iuJlMsPaa3KFFUuQiSjllDL5z4JR_P-2CVetkFkKnXgU_7O8LQOKpN9Hr-WDooLbmRVedRy0YiLQBwO6uWgTXl6xlE-NCNaQVVLjGPkhaVYYjMgULoCyoAs1dSW3ULiriD4g_YE3saY7XASzLKkqRprohyHL8Q5a12S4Q1RjwxmTiGrGUKuTj1o6-q2K8CX522E0Y5j7Dx1gsGIbLTI5hj92XQK0YTqfwlPnP1phuyRyM1Xt_p64Fuw34IjVyXS2vQz4GX6-tr6oPYiSxjLK2mVmX1plUNVrgG-vITY3dNm-xriwwSSAWvWr4MsuKgtWSjqC-jTajVpDLBm83cXvADzYzpiiTaDhiIoY1vISkj8r_Pa9AvgtRY49wezkPpC7TWWMcqWuXcnEDmjqINjLEUEh874PSj67cFB7tsF9rxHcH24SrFOjtjkin7qTqZBGLOLZ9hzIkaz609nseSzodPEjZzPj7PhkE6XgGYcsrHY-cXF-dl999N5wkYeJXpyPe-zP5s80ikK___ML_uERUMpmj1G_OPbg08ueelTrA6JseuBaJzA8_A0IoO3B0PsRbCyCx8ZTB_268QV1BgUVLzpQKqcVgYgpnT-SsIY9gtZ1QldIuRrcX8NU3xBmnGp2kTU6LRHTIgH8TMcxbwiEEiKzdbEVOisS7gderMCF2wGe8KVk7trJBHPpySCxOoOXYdafLXK7wGaQ1XIxXHAWZx5hb6TVCSmwcZnIgL8phiZj8BE2MndCqmy8ZtQqvyuGL1DHCzcO78pRl4UmYEPYhJRWUBVULoJfGbk4DRt16OJQ6jZc48sQMQEb-MxCXk2ElK6hhiVglQ6Tug-zmKxG-cgKmTFumOBhOg9MSpv9gR7oPcqIlGh3REINA8jJsVbBGEgq0LtVcTTXnUoTQtugeT53Yr9p-2HYOvJ7QrWWf0jVH1STVWFBii0xaGB3hQjc9daJRGHs5oUmBt0yJBAAKv0gwVMRQCOZ34HYmVcIdCapHhCaz8H7oBX-TtRY5ssJ5ZJaiNaPL6Uym1jiqwL2lX0S83RXsSfTPYEoT8HsoYQxOyriqqgHqVF43BFsEefCwXebgRXJpg77TOII-wPOnT2seNG6ehkNgViKWe3ZWVdZmXLVE-O0oL7hNU4kRRBJX5JJtHpHPqhCxrFl55iYSbYpAiO2XPfAk663IAM8cyj1z_MsOfGc9pj5K6-50-sHegqgCQJ2XegNQ5eqG1ykrTmiiAyv3_P77S9OKFG10sFxsWTcMT2idi15CJ7Vt3O2GZbZoy7vuPNBqTrJ73iQgMefqTM0WfwdOS7kGHkBXRCEgzmUppLlogv1v7pBFhM8C-94BF7SkoleViPrIPCfbRYhRLq0oLLIf0xfez6hW-6y8ooJsEE6g6HXAcjMqF3r6F3GUAXdtSNQUBHVEpHjC_4tEyNKWR5gynRTEhgYT5fg3ZWdBDFGJM4LYZw7fo8sswmkwAM5Q5q3BhHE265exFFYhO8er4PkiI5tzrdcGqQu4lrYX1Li1WIrUxGHFuKA2mV2UxUPYKnJNy_oNqDARnQAVLagJbJpJYURJTqyoHhS5SAlO9162zWrLnZ30CIgQ-1PE206czzR1uHYNENpbPAT4QjvbjxWOL9dVTHZk64f__YeBfQjLxDpKvr3TiKb_1CQbG12Ypp1XZgoCC9jImfqiaXjWtsWl0b3UGbIWge9ONtvtE0qJcRqbvDFFli2H-aPXHPkdBOJrU-NvgueEl0jcOnraWbPdsBnp98qJc3ljFn4--w4-gfkcS4qR3_tJp-Q6ne8qnJ1v6ySqPuDimmdOtLV-nAbjv1Jaaz2NsnjL0rcEGytfZWKdTdEsWUOOqf5hUgiGeyU5hd6xIXYRDFp1DNFxLLYpn9lJm5RTaUOsOUVvjbpa6sm3hmYUR29aASInV3fkVe42DmjGtvTFm3sUVdsRK4NvUiMaXNa5wFib2XgMmpzH4cuk9kJyWW0aldMnBsKUH_02LHFfEmJN4pnxrrBH1DXsD_ItKb-VvbUhmNurJliBLF3LvxdH0nJEB9kE0ktzYgMa3aVVlKQVqQ2N-Or3Ac5prZ3UL9ErHa0Y6jrXhH8hH6NDaa4hMp-vE-JCQdPDEKKJn5wJf8KwpdNvoBL4DEHc6TpzFvD76psqY0DU210PfmN1NW1CZSFcOEL5qmIqOpmYam0G8IGWpTN2VTo98UXVUBzTR1-AZfNLupGJZN76mmLitN1bCBCmwtGNAxlaIohtFUFYTMpqJqJmrqhqEZTV1R4YIuG2ZTRSrSm7qsqlZT1Qy7yRfRNAvBPV22YHVkwzq2bMF_ZRnJTQ1ZlKwqA7QFm2giE_41DV2BmwjptglUbEMDEGQDoGFYZhPZlm41DdmGnSPLlGFblqYApKFqWtNWZACE68CKpgNd09QAQkVIgzUsGfABwmoqpq4aTVuV6WqKBvvRLcqFDCzqBkhOtU1kNW3TMkBQiqE3DZCsCdCWTPdnWk0uYcVWTbuJDEtHTRuY4UpABnzVdFMFOpYCW7IRyAKkA3RgL7AeoMkgOh2BeEB-dlMFWYDg4RKIUaPy0hBsUVdl0IcBi-ggAFMGYVCdc4VqNmwZ-IdtgADtpmHoGsAaCvDI9IgUBGpSTFANvaA1FeAaVgEdgDxU06Lqo-oHDcHuVNXQgEMThGDooA8daYCDqICpYVGCtgy6VYB96ALB2EnudRxFTt60odaqJIPKj7333MXHcTyNjo-OXl5eWlMcj4MheYX2o-UEk6MpIIELHDI_PaRkj9rwv9NR9_Q39GgMf__0GNro8uLq09hQp_ev77o3f-AH7_zhwry4sZ8dfHH77svtu86tYt88Xd9_DoP4Hg8_jvD87l5W-uZI_7Vjfux2Pz9cO-b081f1y-F0bj1hvd0Jns2u-kExtdffXybzh8ntc_SrqVn_jrsDJey9zl_kq_u25jw-zpXO-UB5_KMXnYaHz4oyG355MAZg2s7lcB596t7cHH59CfVrzR6dHb4bzV9vPnxtP_Stnn942O33h649P5vO-qML-4W8M8Iz5friNrztPPa-3F0-hN2vHdW91n99N_zt0027PbRPjQdvNv4SX3Xu7i-Vz-bww7OrPgNd_dR_8vVpZ3J9waNMKuET_tZSdJREHAghLNrQGEM_3AQxYSdQ6MX0C4tA9IBIcp4F8jvNxV-DYPJAjz3pLd0EY9QMsGBD4bPqK4KhMZsuMjgFfr-o3ticO8Zxx4UoFbJnLGnIpIC_A1VLbxmqCqEJjDZ55eOEBeEkFOZnWrOI8PP_vLdml3PDcQoqPePQxTQY6_xhQGJ7Pbgcz4-ljzfdDx_PGx1MHwsFacMKycGlc8wGLUikTohHgR852CMNPgA_lmDDavLlFLJWcm4XbPZYklsQ-qxG8mAUQBXLTL-VwSKl8YkzeSzdhURSWkZLLl5SW_rqJVQChuz8NajNQchxg5_bgdS6uKOv7ix5xHAsKXIjsZZjqXd4Sf81mAp75MuxZKiN7mTquY5L78uNb4mAj1ETYsf3byF9h-4Y9vX9Z2TIhxDMf_kbLfCS5M5FJmF_ICUiySjoTa2IbwG-Uh8fOMjjv_lZkw8N-Rc6jJ7wR1kSPSaQIUCQbOpFFGDZrkJhu1ziU25ph3LLAD6DoZQeQU2mmekUjZ3gAP5xtERQ_65sgvcQzCQvgJIQg_oWp9Sk5JgaH9xBL8bgRlAXg6RWwKTAl95BMM3t6vsC_taPPDwbjWNpGIQSAtenDhZJUxKuElost6CkiCgpm1LiyhFQ0zelpi3ZJugZLZlmtgKvofI6AthKUBpir4MBe4FUYstAWdhKQg5Kiz4hhLIWQl0Loa2F0NdCGGshrLUQ9loIJK8HWS8ztF5oKD2qycr4kpygpsItywltWmLH0kUYTKQLj0TjBlgXWOIp8eIaEbsYnsWhWM2TzeKspuXjLGp8i_EoOv6DvBDPgzL_84CeUYhIMXrZEG8LwYsfTJL4ySQhjTdQR1KsJKJKPUyPXoqXzMJGYXVVP9T0LZbPgkfRSd_8bOqH1iYbCtlZIhoJinQQeLsOzg6EWNxcjGZ6C4SIhcwxfiYS7bnpPMMdFpcDaIfHFwCgB4VDqki4CLS8eTEPGflwkcr1ZQxJPyWfi3TfVbkGONtrRE-XQjjKw6cHxSV29HQJ7X8mMpn7i13L8YJvoixGgKekNeMNieLGR2h4fBA-9eVFAWghtaL-Q4peXntdrtReul6svZBeKI144cCMoLGU60y9kOr4nESip41ZzcEndxJ_eA9kS80xjQo5ygoUaEXKXD60oOFF-zCY-YNGlb2ymyF9VYc-ME8Pxkh99yv5ixlvmVkZ5e1ICOWZT5ynxh3xSRwyyUPtGwYv0ocZdEFhzipUo5gpGFgk3bnUzmj9hwcDlw7UQNH37GcyCjq0DpHyi9CO3qh6aWpYKrP1spo5g2kPoFJjUVhjcD8jyFTwcVH0JtUu3EoOAfATAaewkXQ_AwJwRcvMHx6g5-dYW5CebKbE-Hbh45jME4H8xW1qud01y-0Lmu2hR2Jn3OgFc5ArCHq5pJGXS5ryKmeXHjRbWxwAc4auWHlDV_JNRyHcLRt01WkTic9bK3pCFuS07QkuFTXcFZjTcU8wWM225AnCpjjxJOUQGRyfc7eKn--jmd-JU4W4g1flQ63YJAlShlEM8NjHEnvLlfBRPg0by030d3o0W0I0-kO2SE5HLAcEqLPOXyH-pd8BElNXGEBNnmgh1-MlJOX9kdS3JUmwM16Q-38N9kP6x3VtHSqNfb-5_iCiljpp9IjrD4OQFh6XcOGZRIv5niIrovFenaho1-39SlgQDOLYv3zaXx7E5fxWl2nftDo3WwDV7YlyrV5lDZcLxcWiVASnfldq0Vtedzn0ipIAoqPHyqDN-j2HlkfTqTdfqpPYqYY8t8XCg_5MEfVyPv2hn67Iaxr5t_T2__dbhcLYKjpvr907b9yTyRS6LOkmCEA77REkFak9mUEh02B4zDmgsDCFcxQoGpwQD8EJv7c9L3CAQiSdeQGkb1o7sklM4w0yqVdAhiP-KLnT9WPiee6IPrOAorgA0GBJWaeXkFxR0zaUqr7qjWIyZ1y8mp5zxKT5D0kETuyQpgf19ffFTorFODrU9dVi_H8tBZWZlF1iUu0pGIE3n0ZEOp-TRm_2OJd6VB15gzLlfNzVi-3WG6pVEDf9XYS8yt6orHEqGA4qjIUyTScRCSmFUouexE26MFNfba-YSZA0qjWdwBs08wOwFfPQTAMMREGHisXjPjuenmP5v91IYINrG24oHkoCSxCy5HMZulP4MsVfS4zAFCZfagRI7LwsPCAWHrQVpefjwxtFF88632jmig0AQqntcdvA6Uu1glBBLYGHikUk--sPXBAq0X9_6sI36Q6_NNpRRA8c-Iuzy24cR7mHuYYhnuXZmqk1CloDS5Eb-beDl5FQwcYMu2oUeJofBVpLo0BFPMJBRskE541prJqTZuev0TZuizCj_3WCTJkB6SX28z7AdAAQOuPGmRvjAeFTjbxqLfGUV7qsUOy3IR2IzkI69beFOuYhxmIRQoUowwJCklXYPUVjtyx1NetYaOPZRqpz62-Ss3jhiw3oOsHs0Vss_V-sa_pSpfh8SfF9S6gfJRdw7h4_9t7TIzL811jSNz76L3gqtR_nEFk8iSteomvH_Kzh4mnoOjrLNJQaNKpOVsUhWOoRP9tz1Ac1xrPJ0YNiP9i_d2YPy6tni5nrGGavTu1jx2WSUzagQ5-p7oJ_4eHoSVI351wp41zdg863kKLyI2hoe9iLsQc-jD3pBm1iVWXmvYly-cH1nVgoMWxjZw5-SEAZdZ5-JcHg7EO6dvrKT7pUdtZjM27VPQUUtLPctD0YMtqDQ2kbWlAGrq4D50rbacEyr9mH5DYP6PqubO-ag9SNGFj87sIuNlOuwN1tX9-ZwuZxK0PQ6il8d0Hp-9GYsqvlGXsIE-oenE7d0QO0PeXtXT0R7Uev6sYxSNsYY9et7qsAV39ElfCrf_7h_N_6lbes9GwxYxc7MXZ1vD0Zyr7sfqvESQltEz-2xNtVD3QEmzcAtGXsVvajun2E3i2tKMNSthOBuqnYc4zau-hb24_s9Z0T-MYBIGd3uzjqJpzzZ5kZgpWfTKUviLJzlexXgwN_6I5WfgOYzqvYY2z26gjo8kB6DAKPYD951Wr1Z4OJTybzbnQa0Nfc098ZZn-zahV2-Y9qrUXgf21rLRjjgR76vKN_CyEHf00G7mxSxUnyZ7bWLpFNre-Ij714nv1EcuE3vB0yDrwBCQuc8b-YlcKb8hp4ek4q_XGkFEmtgZP-ZnuKo1ejFH_wPkPTkr8VcXKUWsnJ0fJfUfsPDY1vcg==
```

**Comment by QuickStick123** [comment] 2023-03-14 08:06
This is because local mods aren't support currently and so by chance it happens the 10c limit sorted one are better than the 60c limit sorted ones as we only pull the first 20 results. This will be resolved by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5375 which adds support for local mods.

**Comment by QuickStick123** [comment] 2023-03-14 08:09
Best: https://www.pathofexile.com/trade/search/Sanctum/5d4D2wnua
60c: https://www.pathofexile.com/trade/search/Sanctum/5d4D2eDua
10c: https://www.pathofexile.com/trade/search/Sanctum/aGk2rO3He

**Comment by QuickStick123** [comment] 2023-03-14 08:15
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5364

**Closed by QuickStick123** 2023-03-14 08:15 UTC
Labels: bug, duplicate
