### ISSUE TITLE
Essence Worm not using Reservation keyword instead of Mana

### ISSUE THREAD

**Issue by wratho** [PathOfBuildingCommunity/PathOfBuilding#2635] opened 2021-04-21 13:14 UTC
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
* Essence Worm unique ring has the wrong no reservation text
* **What steps will reproduce the bug?**
* Import a build with Essence Worm and compare to the available uniques in PoB
* **Does it reproduce every time?**
* Yes
* **Provide a build code:**
2.2.1
* **Screenshots:**
Essence Worm from PoB built in 
![image](https://user-images.githubusercontent.com/28812961/115559617-74d83100-a279-11eb-8497-a99988069d29.png)

Essence Worm from character import
![image](https://user-images.githubusercontent.com/28812961/115559649-7efa2f80-a279-11eb-92fe-5d04f7ecf26d.png)

**Comment by pundm** [comment] 2021-04-21 13:19
Duplicate of #2611 

Also #2630

**Closed by pundm** 2021-04-21 13:19 UTC
Labels: bug
