### ISSUE TITLE
Incorrect mana regen from arcane surge (50 flat mana regen from level 1 gem)

### ISSUE THREAD

**Issue by OrcFace** [PathOfBuildingCommunity/PathOfBuilding#2937] opened 2021-07-22 03:32 UTC
refer to above

**Comment by Lothrik** [comment] 2021-07-22 09:34
This is caused by:
`mod("ManaRegen", "BASE", nil, 0, 0, { type = "GlobalEffect", effectType = "Buff", effectName = "Arcane Surge" }),`
in sup_int.lua
It should be:
`mod("ManaRegen", "INC", nil, 0, 0, { type = "GlobalEffect", effectType = "Buff", effectName = "Arcane Surge" }),`

This should be resolved once we have the 3.15 patch data, along with most everything else broken with gems right now.

**Comment by PJacek** [comment] 2021-07-26 08:13
Fixed in v2.5.0

**Closed by PJacek** 2021-07-26 08:13 UTC
Labels: bug
