### ISSUE TITLE
Fertile Catalyst + Marble Amulet bug

### ISSUE THREAD

**Issue by henbe** [PathOfBuildingCommunity/PathOfBuilding#2543] opened 2021-04-15 14:05 UTC
When I apply Fertile Catalyst to Marble Amulet it goes from [1.9% regen at 18 quality](https://i.imgur.com/RpIbuTI.png) to [1.10% regen at 19-20 quality](https://i.imgur.com/2CbxnEj.png)(which is equal to 1.1%)

Version used 2.1.0

**Comment by Nostrademous** [comment] 2021-04-15 14:25
this is a result of how floats are treated by PoB (and actually GGG as well). Proper float support doesn't exist rather the numbers are treated as <LEFT>.<RIGHT> and each is an integer. Seems when <RIGHT> is incremented to 10 we fail to update <LEFT> by +1 and reset <RIGHT> to 0.

I don't have time to fix this but noting what I believe is happening for posterity.

**Comment by ppoelzl** [comment] 2021-04-15 14:30
Duplicate of #838

**Closed by ppoelzl** 2021-04-15 14:30 UTC
Labels: bug
