### ISSUE TITLE
When using "Trade for these items" function, Abyssal jewel in stygian belt is skipped from available options

### ISSUE THREAD

**Issue by ThirteenEra** [PathOfBuildingCommunity/PathOfBuilding#6094] opened 2023-04-20 11:37 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

When pressing "trade for these items", a list appears showing your item slots - weapon 1, weapon 2 etc. This includes jewel sockets - for example, if your build has 7 sockets with jewels, the list will have 7 jewels in it, for you to find an upgrade for.

However many people also use belts that have additional Abyssal sockets - for example, stygian belts. This allows for an additional abyssal socket to be present in your gear section.

### How does Path of Building behave?

The abyssal socket present in belt is NOT available as a selectable option in "trader" interface.

### How to reproduce the issue

1. Create a build that has jewel sockets and stygian belt
2. Assign jewels to sockets, including abyssal socket
3. Press "Trade for these items"
4. Notice that Abyssal jewel in the belt socket is not available as an option to find an upgrade for

### Character build code

```shell
eNrtPWtz2ziSn1e_guWqvS-xHeJFArlkr2zZcbxjJx47iWf2yxRIghYnFOmQVBxla__7NUBKImVSoixN7mY3M1WORHY3gEa_8dDL__k6jq0vKsujNHm1hw7tPUslfhpEyd2rvQ_vXx_wvf_52-DllSxG78LjSRTrN38b_OWl-WzF6ouKAc8GvEJmd6r4OKNFfoNn9zIpRipNLuXvaXaWBq_23qaJ2rM8mQRRMfvmxzLP38qxerV3GxX-aM-Sua-SYLh4fhqrsUoKGUd5AQgjmUm_UNmFbv9oUqSXaQBQoYxzoDeWUXKT-p9UcZalk3vo3571JVIPJdD55dW76_e1vkVJvW8wuL-8vIrlVGU3hSysHP682jsCHsk79SaC1r_IeAJ07L3nK2GPJ1lenMgxfFyPc3OvVLAe7CpTp2Go_CL6ooZZVAxHMvF7kN8U9nISF9F9HKlsDo-64N88Iq3FoQP4fQpzeHJ1s74bJWTag98gM6PjGPjXi66GPr9LokL1Br9KozxNNup1L-DhJI5BnXrBXqtcZV9kEfXsyDAde1HSkyfDNI2D9CFZzOAhxp0TfpQp-S4s5fBaBtEkn-OJTqRLmchhmveYTg15pTIwAMVGCDfKT8FmbNrGhpgXUaj6Q240jgph0948bRynN33hNib8tA5dg53sB3mTTuKekEXNfjHRrVufe0KeqK8LMNdZQbAJ2dnD82QxDMLoCoJ1yJU9_JJqI9HTVJ2-uZpDujbQPeSCYMqw6Bzc1WiaR76ML-XXaDwZg_l_Lz-pRYOC8BXyejcqErB5XciE2riz5ddRpp6EOATz9jTEkUzzLkzEGV6pmXNI6pBVnt9_oaHPE39BurtLGvRDkhl3UAsZVjWhUa5BFXVc4sWqN86imUql-3j4srE7lVQtThfNUX7IVqFdKOWPziB4u5aF6mfEFz2izF3JYg1dZzFzVtFt4TDCoh_GMrP4IWegEwIJR3B7pYdsZxyjh3QV1oZ8O01Udje9GUUqrslPN_vq8LO-DeV9H1TD-Tp-U8j7tdjGkl6D25AvtzIL-vmpTfv0ReZ1k4yRwHg1y0qMOrcI7xQBBcEvYARqKQ53cXcekf6us4h4Q7yjbJxOap4SkTUDKRHq47DX-ZUyZbpWwcRvODKns6XjGJK95RyErehXHLehdCd0RSH9TydpcKf6ophGNse4mdzfgxnRc7-EJ8QhWekYIUGIajGRy9YDvwPxbSiyu8qB9m5gAbzcAHHWBga9W1nCWG7KXunS-49lAb3cAuo2mLMU_RIMhC5bmOz-Mq35kkO306K_hqywnrUhQR2bCHxo28hGzkq0ZuKJOERyHLND7kI6N-tuRf_mUxTHVq7_XskMCOxZOaiqr0oJsd5neqyVgqm8sMqk2Wo0gBCj1EGHDrMJIVs2cDzJ9HxaumiTBI2GXPCexKE6K-Wc9m9orybzVYNz5wMRg-McIsxdwTun8ip9gFkf6dJW3sOE1aAhalwY_M5Jy1TybbpMn_QCrzdAut1hMMm0IendxjJGWzPvozH4nDw_kYW0flcPKn4_vVfngam0BVUG8lFmkUwKbB4aoLImp8EIEVzA5CiZ-aMLUK7XMo49MLJmyuZP9bclcsiQg7Ty80RlabZoV_fs5XNTltSfzsf3aVZYscyLI98HgSreyHwEcxdS5flcYJsyybGkru3wIBTCI34gQ49wGrCQ4z2Deq1kPIZ5HZZfh7O6Y0lLKNe1KQkdl9AQNFy5iiAlXSIp4T6zFXU5CypxfTmUsZ8b9p0n95PCSkxhcxzl_m_eJAx1cVKLa2ZKr6evX58O359_PK04Xkcxkv5bMhl7ujxX_ruoz90o4zatfOLl5cdXex8j9WC05EQVMopzzcA4lve5CuZF0wg-GpgbmFq_WEHNQEE2NKttttNaAHRTOv2qsgLGC5GXn0Wqs1_z92s6VTaoozItoV3UdFGxm1Dp7Id68k3U2MEpU6_tpqKLqJ3D0S9X4ILoyriz5ertGk4UoBc5BGBRGPlauVdPudaiEmoFX3wf7II_XTHfVcjSTcNUabsIlC-7kcsqbBd29XYFV4376uRq-bYb_UT5snPs5ctu5HkikiZmBaGdyhxqBaW3aWKEHJTmKIp1bNE5s6exmoN0E3xXjFRWBiydlC7BRs1AVipOFnmToluNaxAreGUKJx0c0u-6UcuCQMcY9LsVlqiRE3cwtA7TTapMIzsN2SrUMtDs5F8Vta6Ygio962B_-XYFE2Z5asf4q9crlMTY36MvaRSUyUuHuiyBrTIYEDI0yBTZZGMqJg_bmspygrY1wdcQUnzKO8hUL7uxP0D2HhXT7YhohdqOgtar7Shcy87JuV4dPhjbdaJCBXxeabzmMCtmt5gkJ-DgihUK0JOU6dZaJdiIWGnHdzTUUkKrWvYqDS1B1hACT_RmRazTj9I8Y34DAbdecE3j7Qg-qtlvNc60yGUSnOiq35YD1UXDyT0Qm_XsXVuwumxNFlRfPp-lES9N5JZDqpsVZ2qcH08hFX6tfdPS4q80jK1C-8KkTw2cWXOBCuUk1s9_nkhtWnSiW3t6Ue71SNJsPF_8AVKj9EEbxZKiDiRz8DQXF-Wbo7ioiOnmZvwquVN1yAwTmWfVQ7N_42jRazNi0-8o8eNJoM6TKvOH3kSxTs083TO9dUWvb8wZmMep3p-gQHmKvWWq80b_8hL6VqGexaknYzyjW44Yo73GazSnr-mcm_gPcsJxlFTW43M55PKNYd-edafG-vslJGABZM3PzwtgyHPNleemO_CpnYqZhaWBmXy26qTOCXWpdbkXz3c1uDOI-tWTB9XE7j-YEq8cxMuS2noRMTR2KyQadw0nDacuowS4viSvMx7b63gMeAVMnpdqQ7pMz5B6IvtvJuOxIbMgP58Kp-dUlDSsrj7We69Lv3-OSes9NaUFnpnpIwgRnq7g3aT6K8YlZP9f0lglO1OPsrXVrD5Og6k1Sy-24fdac6NLtWWl9olcfkSgPstrmLuoE-_MfFbOsayNvE9nZYhNBzd3sR2ENhikjg4m-SZOgvUcZFXBL-X8Kp7kW4yzm9YGQz160JGTCuZrC_WS5O7GffMQhcVRGMaRCfO2HPkqak8Zu6FnLQjuXLa1whwlAbgDNasJP3nw3bQ2GLomYkGQbWkyG8457TnooyCINDdlbALjLYbcRQn8Puk54NPxvV56-n6uF5jzRSeif6wriOV4LD1T52jwF9IKlUGcq1A_j9BGZxOvUMfvKUbOusEdedM8l_Ewmz7Z07WQ6B9HnCeh5mFsafSdWYT5Pv1bJT8lKs-fPLhuShvM3JyINaeys6EeZ2BhKi1--hRmvkyivDDEnmTlKwJWSeG7GYDj1OQBf2jofe6DD8hHW6l-luaFF0fJpycp_gJ7xxHDiZJBPJ2tz2wZMKwgBj7E2TReKMlZzcWjHYYLZeR6laVxBCboiTWT-eBXUdtgqqvdLU06z3clybMkANLj96lOMrZJAB4TgS6Q3sF_HFhFahn872YtwPrep4mFIBbVidmPhP0Hw78nw39I1W6l6g8WqPnWzluZ3bd7f9KL0-2ENvAKcwKWobBrT_ha5oXeVJoXW_iDFiKbhDgG29LoMMydj9Bs41bBYmX1ycPsorTJbEL8b80JfG-twVtpDVkbLI_HwCipuxs_2TS1Etkgp6zQLYPfU5Z6V1BBRN8ljcXrp8dQnbT6D1bTsB5GKqkKTFZt7XcXVvBjVMjuygfuNZ-PaGygLXPcP0JRZhu032dKvaACuY869Yd6mKssGsv4SN1F-RNm_jFHqo83qjBr9OXSvP6oxzdbgTe4qFr9hi_1Ww50p4yB0NZ4Wm22e7X3T4SYzfYZIzb_1_4_CcYU7RNOGdXfqMDuPjzhNnyjgmN7nzKCXPjmMIb5PnNtV0PCQ873HcpdZr45iO1j7hBNE2GE2T51HYo1FYoF3yc2s_G_YMhpoJfzoQW6T20s0D7GAu-XTWFbcGie2NAJyomDoTkkXGgGO2yfUOSifQq00T4STLB9BBSAgIOEs08Ed9B-2UmMmAsdMA07iCKhsRyyT1zmiH1EkEMBhhOgybig-64gXHOE4H0sXATNCsd2NDECfx3m2PvEYRTvO_olIRQwkU2gOexSCp3EmiDVHXYIAoKUQK-xAKbul4wijuNqdmFkA3FkaDvwmDrQaQbch86ZmcCU6sG40BIQsKkA6pTsOzZ1oVsYmLgvqA29LTnuYpsAPgYIovlCsQudhT8MEIXuppkL6ASAuDAqmE54DqMXjO8jRIHrAADDxDajulvACeiba-vWdd-YAHD9hO9rpYLpsmE8wHFNnMBreCzgJeIuICHH1n1xBTw2c8wopa7Gp5qHAAOdE1jsC_1Rs5bCLApoHxhJ97meCGojmGBmwysQLyBNENWiQKC7wAiG90sRdhGgISQw4HE9Um6jfRgz06NzARkA9kuJJq7GJVjoGQZcGKNNzLQI4DABuQAkxmFGkW3mFXgCgoJd6A6GSYZJQy6H1qijBZZy3UuYU5ArPS8gnvASBABruSLQDUZgmDAcCm3ogwl6jpAWRm5DPxzMwToVoMi1u010AOTPFJdUu1c-XF-UBmpUFPf5i-fPHx4eDu9lMUpD9TWK1aGfjp_fAxJYgwNjiw402edH8N_x3eUwPD7-Nbm9PBeXP_kfwuIf3P32mWDiDn_96KY3by-jb97rf8Q3XhH-Rj-eqmI4-S1Lbw5uHt6_zT9-mFy-HfEhHl7bp-9-v_09o_Ld-U_e8VGIzt4ePPwyzTAenRb-g3v19VycHRTnv7w5D2L2-qPgHw8ePk2Dr-r6H1_ck9_fvo7eH9m34vPPX-Vv4uu7ZHj2cPF6yr_84h-cvPkaTc8-_nJ28feHh4PXx8OzX--_joLP7PTbx9ub0-m3t1fhybtP8c1ZepCP_3701rv-NI7f3__65vrnyLk7yN4V0UGUZONvJP3lfvjt69nB0SQ-eosu704_ReiX29Px-NxjJ87dT9cjOvny6dPr2xOM3yd_n_725ebbm-E_7t2fbu5u0UcRBdnn86P7jIXHry-Rfcwjcf7-NcXZV-8c_3b8ADwFvp4fHUVHwxQ-_3w69E5fP9x_U_zLbzSYymL4BWXf-M3t24R89YR77bmpvEDk1xPo1y_Jzbn38OpVaehnM_uyPMKSV36o_GbMpJYDrevg-orSL6N5KLAEZqxWDU50AWoTsIDDtJOgtqk1QNYFWB27mQPaXYDGDtcAu-CMpa4NhS9c44JR8AW8nXGM2h3qD2_TQpl3-uHsi3GW-qhKdQLopshe7akwjPxoz_qWpuNfX-1xZh8KsADIKKcon1_Ma69mN1ohi5MIPGhmNkLOXLkG_OXV3oE-RAaOyOYIXBAtO_zShE6Vn9afZxvlJrkq77AoY3jzuLaHTYOa_Wu42kt2LTOIJF5Y10fXp4OhzDK9_-86ldngYxoF1o2v7kHjBwbP9PqF5bqDaovcCwvbg4pvL6xj69o6Gxiga_X5heXwwfn4PgZm6LdoQO2_6igrUzJXgbVY6CiD0QFpvDZVv-rNURDkFtI1QGot8tsqhoWnZp9zPniGyV_11zKEsvSZFX0614JZiT4pa3FD0ADjelN6Q7BlDkhXVVRLn6MZPDMtmuFYaWhBfmBKkGVrVhlP6tB18E8_k2Ghgn89Q_yvs0rlrHv6aI-lqyb19gFj4kcQtgEK3hTFcMPVSMhusGkBMh-MsuxD96-6-2aQ90A4N9JRAz5AbNGFcsO-3q_R6KR-r_dOjSdja37czqrO23VClof_WsAOSrByR6ZlziC2QCEQCN_sHTHdA1X7poyqXqbBtUyAU5n-C1HwIdurNmVWytwJgddCkLUQdC0EWwvhrIVw10LwtRBiLQSy14Os5ypaz1a0nq9oPWPnZ-RN6rhk0XDTon14e_7zh4VNgwQqHw9uxlqPh_HE1JD-rs94NmwbJ3UDhusGDC8U3aggsa7KwKi0BXnjtd7EYppqwlh3MKICKLfYn_ltWdap8SDgC6ZacyvqK4iCeU9nlJ8xrSxHALQ4u9Qbl9TVUp-0GCCrxG1gWVFuXaZZEYVTbYiP9LG94k-lma3yQ1rl56dMF0ms4aRoFZ4PSfR5oqzzkxdWSHlo20pK6gpFOZWcup5CyrYlCkLP8zmkjUHIhRfoK3wwF5wjHHgecUkgmOwWRMZXCSLeQhCf4bqNnZ0Vqnzcwv32kh5q3IiGWvj2hT_ZRgp7YjbcnvZqoD0a3_i9MirqFugPSZFOgBXgef7NnEyrsLNWYb8p0mycj7J0Egw-RlkURDJ5LOgUS8iebchxEQqxrU-nE-U6WPiBHwQCORJ5AiHPpij0KQ8Ehwe-UgL0AkF2uyzoNdm2IeyyjRwtAr1aTAJDjUIIh3INMZzLrTm6ZHlKQ9-MdDwaWPL-Pp4-FsjZHoEdzXEbb9si62t5X0wgvjqOozxfZ0hcisBk2Ew6JHQcRwrle0EQYsSE6-EwdJSLnBAh6jmhNjME3vlBaAuPCJsEfpO_9LsYkj_OozVi9Q1NEtYCcKK-ApthLnqjmej6PCnACEZ3OifrNhs3Ey_WofprUJz_BLvRajZuZeGPVPZfkHHm_51bp1M1MOEWTL7_WLwROEqPeeAMhR2KkEqXI9dRgoBbREKRwCYcvoShYI5LfY_ZnIoA2QJ7IOPEbYq3M7iIxpDO6z0iOstsGJOGVI4rl1KeirbKY9HtIMbrtL7Roj0gxPiW2f1Ps8RtmCaQupVdeZyoPoyiWFnSFMoBxJtat-CqRpC2lingiuyvBbe2mg68rb8p7xVYg_JnD9YQbzGy-ppN6zTPzQiHughQtEgfsRkTnpQOt5GwmUsQCSjCnu1wj-LAEcwmTIItlYHtCuEwkEskfSaUooFkTeljTXn7Z6hvWwFDH_zrmdsvsddxykLMauADJOpvmucBBrOTrHOHZgUKJDEoWwKaoVmY-X800a3TKNqqUCNgUQaWAzQ0UeucpXRg7pyQhNT1HcVcHBCbSF_ygGJOHXCkju9xrgJGKYMABYNTJUIQR0lHUBl0O0vH_fM5y2fONumfcZflman-SGui_n_TDPKJ7tNu9Z8XqhgB28BnBmowu6qqRdRB0hmSNPSYxOAyQbgxhIRuCILuQpbJwYa5KHAc6vu-44chcyHbdCV3OGaSOcuOs7wK-4V1oStvTUM2TMdjmeh5i5UMIOAeRfel_UKuS7n1YKoqEIdPACizjj6lUzmopjgH4QamaNqWzIxb1FdflU6oGCnrJ5lNosEbEJEU1Py7TXvrhNAWA_Rmep-kOnQpo3XDnm4DxPzQD3TE7nt6dTRkLAwgvMEe9l2Flc0w8T3CuOcoW4WOB9NHhUABFW4YunYzG3J4PVqn9UkhSwaIdxog3KZy5VyY3ltVyX4Tk4Vwl5v6ww3FMFMQSaZZN8QJRDwZWMzCOMgov4_ldEXIDqKZF_9xleQ28W8veUH8Xi4ZgOhBIAVTloIqX8r806C6UQdyVMxnX45BJKobhCHkfKFrL4S6g0aYDQI0f1Q-eYxlI4rrihV4nIGLpqETBHpJO5Qc-S7nyIHUwebKDQMima-wj4XLSej6nsKQ_zJBAQLJZc8-X7SqrVldH5xZx9ZxTeko6_D65ny_NZK51VypWuG_q3a0esyXi6w7VVjSEkBDXwlv_Zcc3_93A78WHFLuNtbMSoabg4LNLOYZcVsXcWbJhVknqj3HrF73ixJz0rKEOv0KWZyuVUBDb6KiA9Q0tAz6VskMbDx0bRyBGxhJUDtmPzIcuvtLHcrB42TZ5B549WOJ59EST5vqtjmu06TI0vspMFcWg9OvnydRro-IXCip7-RZKC_nolt5MYQMdTX0EHal7QnmU196SDLkUNf1QheclwupvBsqTwQ8cGjAMJWIQ1yNFHOopOAHkRi8mSTaceqeN9eRaypJajp5ewBaaf6_7bMYU9GwghREDvz2XNqs2c1CDR3WqVK5TDmvC5n6MOhJRWnwDCETCTeqAbyzTvCM8Hbdo-2694yuqHAunDjqp_n11edHnf6hSpuvlrYpG2tLU0uDpWdlKPWqyeBGn7uzyoPGC2UDfelWNkFxQ9m4ixlCHrWRC94QUxLYPgpdogLflRKCS4xdDIF_EISIsAAyAIU8LiX2ENLecbk60ebzjkG_jg_qPs-1m7p1vsLI75eVdS22B4i0Cz7qWfuol0u480h6nyG6fnWq3UNeSx0LznvySAVJuVhlLstuVb-l3R9zR36Uni7t-kANB6d_akgjlBtifyjgjhTQaVtTmSR6N47MPg0uJ5lOQ80R34XmYR1ydmoehgx4KUal9soQFdU1Vdi-JAEm2PaxJ5Gi3PeJIq7HiI0dUFgKEC6m2HF9RaSNCVUkRCEJAr19WPTR1DOtpwfXdS8oljTVHALNrWk6mYdmphBYqZ07LwSeQGQAquOnmT8COa2uLC-rxOP0C2jLvrkxWis2qXYJ5Q0NJaxdZ3qp6TNi9PuRfoq61jc9G25o9uxmestcZDxgvN5mywLgQBunBcSdjBLrXZLHcgJe1wrTzKKzUWrL9hPE5zXtd8QPX_p9dh61abvbujexkH48zcfWsZLjwRsInrw0S6ybQoZhXTEVwdIJmbA5ZqHjSBnaPmSEyAuIThWRE_oqZHr_v8tDl0seOpQLRZhwfEYwadZj2hXzFoLU2_JvvV6DmxsezX7AxSq1uRrWKm_rbi4KPWh517Irq-E0gs2GHgmna5eklveaHyqbKZVllgWu3xn5DLt1wTerXe7KfZvQ-WI0b25eiapvViTVZsWl9bIaGGbrF9RKu1Oh_lDG3fjVpWW0y6Oz8-HgOFMPi9XcMy1j5k5cPUW6fvtOO9u6yvmekooESAiJhWCOki4VrmKhFwiOJAJHKbhyAunqczrCh7BVUuowXSJFxGuqHG9uL-5Wr7m1_qDl0pxrqzaRWiCr_sgKJ2DT9abgrDyJOX-t871JXk-2GlpVckOPttxlHRpXGUz0Dx30Cuy2WhMTrTW5j6Bz6WJO5FjvUzJTc60daX13jiQu0z8agUKKvDAMZRCwwBWIB65OEhxIObzAwSjQKTyiAeTvBL5R5rsB8uzlwKQWfHSVxn5NJ3oDb2R-HNR6r_fzAtfMhl1LVcUg7XHtQzz3uaXlA3GamsJ0faHan1ECsYJIu2nYWidn8Izx1Rk7iBREcY8Rsd2DOMHteQ4RK7OL1gT_R-3K-P7HDv5EV6msizS9HxyNVQGuoHgk21wSiLVtQQJ9WEwxEiqBlYS0OETCR8hW0oF_mG97IXUg7uauEzgsoMrh3EfsqbJ9CbkfyG8l2VpaCrX86z9awEk9pNQV0dmZhMeJZi2wrjbgr8qUa5v-0SM3qQNg43_zgZa89mWaZ25bgr16Y__jCFomj8AeR89v0-RAhz2JKtW4Wg0y5eADMwjzS55l5VwXwf9zlGKFK0aovaI7ymTJxguV5FWmq9dj9CrNo8VIj3JOwe86RFJfChZIiXWwK2lIeQCRsG1LSE5VEIBihIEMHc4CH_EQslMPaw_btQeZLtWIMF6XgM0r-jryTQPLB4lICwCaZarwBmQHUtcBWZvNkfL4T7Wkt6QAJgQdxvJhrgdG1hGp4OuhYwswXqrg6P0PVhSapFoLbVK63cKIufYSSpcE4unu1iz-zzcmINwifBBz3CkzKe8fzE6cYnqnNwR_jHJVFzrMFbUD1w8D5hJHeEI4Lgif6zsghpCMgf11IP8SUgY-E4whyVzHCUjIHEJc4g9uZRanWfB4iQBM9DznOmpGf2-kPhNWXShY1ecGiHeaP-J0VxraoofaZnLHPUSLjeTVAarae3ZIHp2vekZQu-GnYp2o_8htesUQpC11OdK1Jwj0fDULlX-eRKDjUay9aiOLOZPfwD81BNkJkLJBLpGiUtkUMxnaHkSmLsh1YNs-k5JT7lNGXIimCXU44txROLQdT4RB85gkYh15DEJPyWOQ053HUNJdA_9ueQuibRNykvq1vOXvMlDNWbiYJl8be5yojYlDfRE4fuhKxGlgMyG573PJHAj3JDgtxnzFicdcFytEAt_DIVgZpWzS3Pvuot2mkvhxPFSNpgqFDKZ2G6YGK5crLYPmWkGzpPn9Joq1TdSVjkfNrb6L1B-YlxXfmhN2CUYKuulFWdBQHVdQFXJbCkSQUI7LlBcoz1eOdEKCfDtUXPhBqHdvhIJQ7PvIY8q2cehD8N7cm-bQjnkj_Knz1qk67uJdyXk90OEky1VeRSebTMx2m5rbVjneQIwBmcVQ_9ZKNniXTL9aR-NJDM6uXvMMQyyY60EOJKgXEiWIFIQF2nxh5gDzEfZDEcAU-DQkwmEitKkCoEAQD63K-e2uTbBxnPpSrz3cjqL8XudFwLiTNB3PqvqyuQu1kfGItRnP7BxQy3LDLpOWllPetaPdnWfA205_M_bvumbwBxchUVu9_ziLxnmR6iU-7cZAIkAOVRZpY_oJotJGAMqoG2LPE66jfB4wD0Fu4_mBpJ4Drpnb-neFOQPZp1Q5oQeBqefCGwchm4eq56r50kqc0zRFzU1hHZX2cjGgoQqY9VCFxzK6fAnB5rcVDEEtTEo-udeoBDprXljzQ3Y12cZ272sKSgzWWYhYLJw3IuFyJbO2JuB2roHU7xtwNr0-gXaukjRvHug4-vMnuDfBaYtS6iTnxu9PYZ5-XJWw1VUJq0BWnVRw2oLEYar3WE90-UlvpdObCxvB4REYPTDZjcOskDZhD3muR4guCriKBdxmTLou58rm1NcrFCHDToiJSwXioe3anhcEmCHleA3bzLoCQ-w-KTBsnL2qlEP_4B2YkOmAopay0PcK0nGbT7yK5R2w9S1YK0hcb8q9DGADfkp0sFEvA4bCcbgSnkQIOC0lceE_n2LMlBA4MHtXhIKkiksPO57yVABTJDFGHsTswXIZsPW-n-uD64ZHbB4uJn12aLasCDc2aqKVK89L2zaf7IHJn8EDVyHzBh4YbeuBy-PTj_fAXapYqflYKuDTOABWg2YdS_3TatP_nDLW_z_nsmRQ9G9Wdt8L1vw5y1irJ-BceR-uL_S9p_oS0cWv58zuTZvzrQthcfH2_Ko1dx2O2b63VNK12ILCnEflq_MAsJevlCsplcecarfMVS2tuuawyGSgnpcXuT0fVmL9_OKTPb3jv39IVrVdXT5Xb7t2H91slOtGr-JiefC4bfCP8Mtb4GbXxpXUSrdcv-mu95SZG_iXe0J79WSJUJ-pXE0D74BG-4CcHQzI2cGAnJ7yXd2EWJex2uWIPWVs3ok2jqANRtOqqmQHLMVPYem2Alv-LOdW_GhRXmfrHuCNKSwQyNOaJLviP9uBMKAd6BfaQT_ohpJQs7p4KyOFt1VJugMObuuEapKwSG3bTFx1N2vdxNWua93Chf-Cr67Pai78KVNBtp0KvKU52awD8x-_3UYfyqhvGwrtRoZtTcHZVRiAdmXvttWSWkf4KiUpr2yu68jiEueeUUA7S-nWgsF2I6GbKEq5FFYzMM5TbTzZgaUkfXOV8j7tRq6yuGJ7i3yBbmlj6uka2mIKnxxFbKlEtfEvSqSbEKjJHu4rSnUc9ylcZ9u6FrQbxaO7soXOrgiRp5r5Bd7aGdF7jOtzKFZpbnnBfV1xF1fe99TbdtuJdzOFO_OLu8jV6dPGtMCiveaubrSe6Ll2FFuxrV3o9k7Y2dSYLOCdJxmfxw2W5cfZTwuZkxT60zBNwuiurEom95OiIqoPiEzP8-NU_2ByXujllVd7V1GSSD-ufimwAa-LmGafUlmvDvRtI9PZltw9y0vTWMmkMu4r0A2eLovPDrhvimsOvKhgU7Tq2MDGrelqvwrOkyP9-8LrcCe5mq83VwtfvZDKdeLeGM0uVhOyKdq7ZHYquTxJsSl-tW-2He0qlr4apbE-Hl6TN7PiD2I9GXsqA7Nu26vhzS6kcpF_gUXWIM3P_5TrLgtE_VNMa9rLoqJcqlpgsdUoWpSXe8jWDQuebN453dLmWGYdaYHA6fqubTqcOcOv9O_jzaepJ9LGzNMyscwHLpz1zNuke1oSlhtZJ3gzPzqfHOoyvJ7dm3Sr7NJ1GsdmKaquSqsRq93JCwRkI7qmsdkycafQvXw-cy4vn1_JYvQuPJ5E5kj13wb_C_cvHqo=
```

### Screenshots

<img width="1075" alt="pobjew" src="https://user-images.githubusercontent.com/111650549/233354606-973f8830-f6de-4d97-8c6a-6c9bc140cfca.PNG">

**Comment by QuickStick123** [comment] 2023-04-20 11:38
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5354

**Closed by QuickStick123** 2023-04-20 11:38 UTC
Labels: bug
