### ISSUE TITLE
Error when retrieving a character on 3.23

### ISSUE THREAD

**Issue by marcusarevalo** [PathOfBuildingCommunity/PathOfBuilding#7096] opened 2023-12-18 18:21 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

![Capture 2](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/8110815/12918c9f-80ea-49e5-aae4-75dc4e026f27)
![Capture](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/8110815/40b7d1fd-743f-4c80-9ab3-3cb379e8b4f1)

### What are your system specifications and configuration?

Windows 10
AMD Ryzen 7 4800h
Nvidia 1660Ti
16Gb ram
1Tb SSD

### How to reproduce the issue

Import build.

1. Click Start
2. Click on Items and Skills
3. Voila - "Error"

### Character build code

Account name: max078
Character: MaxAffli 

_No response_

**Comment by LocalIdentity** [comment] 2023-12-18 18:28
How are we going to be able to replicate this without the Account and Character name?

**Comment by marcusarevalo** [comment] 2023-12-18 18:30
> How are we going to be able to replicate this without the Account and Character name?

My bad. Account name is max078. Character name is MaxAffli -- the only character in 3.23

**Comment by LocalIdentity** [comment] 2023-12-18 18:38
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7070
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7085

**Closed by LocalIdentity** 2023-12-18 18:38 UTC
Labels: bug, crash

**Comment by marcusarevalo** [comment] 2023-12-19 02:43
> Duplicate of #7070 Fixed by #7085

Thank you. Appreciate it. I tried to look for the error but I guess I got the wrong keywords wasn't able to find the duplicate.
