### ISSUE TITLE
[PostInstallation/FirstRun Error] MSVCR100.dll not found even though existing in system32

### ISSUE THREAD

**Issue by parasys** [PathOfBuildingCommunity/PathOfBuilding#1015] opened 2020-06-18 21:33 UTC
Copying this title from the original Path of Building. He bundled the CRT into the installation process to fix it. If you have the original POB installed you wont hit this error, if you do it on a fresh system (I did it on a brand new Razer Blade) you will hit this error. Workaround is install the original then install this one.

https://github.com/Openarl/PathOfBuilding/issues/89

**Comment by thebadteacher** [comment] 2020-06-20 12:09
Was about to give up. Thanks mate!

**Comment by ppoelzl** [comment] 2020-06-26 08:05
Duplicate of #922

**Closed by ppoelzl** 2020-06-26 08:05 UTC
Labels: bug
