### ISSUE TITLE
pastebin link are automatically deleted

### ISSUE THREAD

**Issue by iceandfirewes** [PathOfBuildingCommunity/PathOfBuilding#1643] opened 2020-10-12 05:09 UTC
This is pretty straightforward, generate a pastebin link and it will be automatically delete immediately. this is an example https://pastebin.com/RZi8vewK. i don't know why they did this but maybe to prevent spam/trash data from the site. this isn't a bug with PoB but it basically prevents any new build from being on pastebin and being imported

**Comment by ppoelzl** [comment] 2020-10-12 08:18
Duplicate of #1635

**Closed by ppoelzl** 2020-10-12 08:18 UTC
Labels: bug
