### ISSUE TITLE
Wine/Linux support, or some other way to parse pastebin build files.

### ISSUE THREAD

**Issue by JontomXire** [PathOfBuildingCommunity/PathOfBuilding#1776] opened 2020-11-30 17:52 UTC
I play PoE under Wine on Linux. I am always frustrated when I look up guides and the builds are a pastebin link to meaningless gobbledegook. I am hoping that PoB will be able to load these files.

I ran the installer under the same Wine version as I run Path Of Exile. It ran fine. I tried to run the PoB executable and it crashed. Very badly.

I am an extremely competent software engineer. If there were build instructions for how to build under Windows, and there was not a total reliance on Windows only technology (Win32, Visual Studio etc.) then I can probably build this for Linux. E.g. if you have used a cross platform GUI toolkit such as Qt then I should be able to build under Linux.

Failing that, if you could somehow get it to work under Wine I would be very grateful. Or pop me a link to something else that can read all those annoyingly meaningless pastebin links.

Or give me a link to the syntax/format of those pastebin links so I can write my own tool to decrypt them!

**Comment by ppoelzl** [comment] 2020-11-30 17:57
Duplicate of #1678

**Closed by ppoelzl** 2020-11-30 17:57 UTC

**Comment by Wires77** [comment] 2020-11-30 19:46
Another workaround (in addition to the one in the linked issue) would be http://pob.party  While not officially supported by this team, it can pick up pastebin links when you don't have PoB installed (or working, in this case)

**Comment by JontomXire** [comment] 2020-12-01 07:33
Thanks for the link to pob.party. I saw a mention of a web solution when looking around the website but links just took me to some source code. It would be good to put the link somewhere more accessible. Search engines didn't find it.

**Comment by Wires77** [comment] 2020-12-01 08:25
> 
> 
> Thanks for the link to pob.party. I saw a mention of a web solution when looking around the website but links just took me to some source code. It would be good to put the link somewhere more accessible. Search engines didn't find it.

Well, we don't want to link to it because we don't control that website.  It just uses the source code found here to run it.  If you wouldn't mind checking out that issue, I pushed a possible fix and am looking for testers to make sure it works for everyone.  You just need to replace your SimpleGraphic.dll

**Comment by JontomXire** [comment] 2020-12-02 07:34
Sure. Where is the fixed DLL?
