### ISSUE TITLE
Elementalist - Liege of the Primordial

### ISSUE THREAD

**Issue by Smithwicks** [PathOfBuildingCommunity/PathOfBuilding#1971] opened 2021-01-16 01:56 UTC
Liege of the Primordial's "+25% Damage per Summoned Golem" does not calculate past the first golem active in the build.

**Comment by Wires77** [comment] 2021-01-16 02:41
Please post a link to your build so this can be properly debugged.  Note that this mod applies to your skills, not to your golems' skills

**Comment by MannePylad** [comment] 2021-02-08 13:50
Hi,

from what I can see the Liege of the primordial do update the calculations section but DPS only increases/decrease based on golems buffs, not by the 25% increased damage on the passive node.

paste of my build.

https://pastebin.com/AxgiVdeA

**Comment by PJacek** [comment] 2021-02-16 12:27
> 
> 
> Liege of the Primordial's "+25% Damage per Summoned Golem" does not calculate past the first golem active in the build.

Mods that mention `per Summoned Golem` assume maximum number of golems active. This does not depend on different golem gems being present.

> 
> 
> from what I can see the Liege of the primordial do update the calculations section but DPS only increases/decrease based on golems buffs, not by the 25% increased damage on the passive node.

I am not able to reproduce this bug
![1](https://user-images.githubusercontent.com/18018499/108042501-28396500-7040-11eb-9c5f-7e04a3a211ca.png)

I am closing this issue but feel free to reopen it or create a new one if you are still experiencing problems.

**Closed by PJacek** 2021-02-16 12:27 UTC
Labels: bug
