### ISSUE TITLE
Primordial Eminence is boosting attack speed of other minions

### ISSUE THREAD

**Issue by SneakyBee44** [PathOfBuildingCommunity/PathOfBuilding#5403] opened 2022-12-18 11:00 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour ingame?

Primordial Eminence should not affect non-golem minions. 

### What is the behaviour in Path of Building?

After slotting primordial eminence, POB adds attack speed to other minions, other than Golems. 

### How to reproduce the issue

Select minion gem
add Primordial Eminence
Go to calculation, select minion stats and check attack speed. It also shows if you include minions in full DPS.

### Character build code

```shell
https://pastebin.com/Ct2TfpWq
```

### Screenshots

![bura](https://user-images.githubusercontent.com/93332692/208294619-f88947ca-533e-4d8a-86be-ca2cbc0d3a2a.png)

**Comment by QuickStick123** [comment] 2022-12-18 11:01
Already fixed in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5394 closing as functional duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5382

**Closed by QuickStick123** 2022-12-18 11:01 UTC
Labels: bug:behaviour
