### ISSUE TITLE
Feeding Frenzy support

### ISSUE THREAD

**Issue by JaggerJaxPrime** [PathOfBuildingCommunity/PathOfBuilding#5012] opened 2022-08-30 15:44 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When you add feeding frenzy support gem, and activate it in configuration it's okay. But when you then remove feeding frenzy support gem, or change it for another support gem. The buff stays active in the configuration, even tho, there is no other source or no way to disable it. Since it's not showing up in the config.

So in my understanding, it would be nice, that if you switch the gem or remove it entirely. The feeding frenzy buff would be automated to be disabled. Since there is no source in the build that could activate it in the first place. This solution would give proper damage numbers to the build.

### What is the actual behaviour/value?

123

### Character build code

```shell
When i try to generate, I get error to generate link. This is the only way to extract build

eNrtPWtzm0i2n1e_gnLV3i_xg37S5CZ7y6_Y3rFjj-0kM_NlqoHGIkYgA_IjW_vf72lAEkiAkJyZ3Z3ZSZVHgnNOd5_3Od2gd__3PAqNR5WkQRy930K75pahIjf2guju_dan2w87Yuv__jZ4dyWz4aV_MAlCfedvg7-8yz8boXpU4fstm2wZmUzuVPZ5Sor8CqTGMsqGKo4u5Nc4OYm991sf40htGY6MvCCbfnNDmaYf5Ui93_oSZO5wy5CpqyLvcH79o3KTeCQjVyVbxkgG0U3s3qvsJIknYxhry3gM1NNF7AHo2cXV5fVtZewgqo4Nc__Lu6tQvqjkJpOZkcKf91v7bhY8KgCFuZ8HoyADijKcADmxtdeCAlyTd-q0Amu2wd6MlfJmYGQX4TbIq0Qd-77Kp3OYBNnhUC969Qjrwl5MwiwYh4HmZwmPdlkbxm2cyfDo6mY17QIy7sETEPXwIAS-9KKroc_uoiBTvcGv4iCNo7Vm3Qv4cBKGYAT9YOORE0Q913ghI3kYp3Pe0VbQ88BXNdBWyOObfnDXoMv9IPU0r1QCFpr1Q9CTXQuhHOFGuTF4gXXGWAelso7NBtsA8_hmE4QNBrrJKoZtoVapq4caJGt1AUfqeQ6Gugj2hDyL5svAjHcQrEFS3D7DxzgD_93T3I9Pr-aGhojVOoOr4UsauDK8kM_BaDICh38r79V8GIJts0NV7oZZBO6iFZtiy9wVpPyvjc6HIFGtJCwi-C7hxT_a7otCr5UEszjMgtuMM4ysVhJDGadtNDCxMN0FARX_uoxnhsM47gqa7lsNfRa5c4USpIvwpyhRqUoeK9G2awiNcg1WpUO5E6reOPNhSuucz89cMdidisoRX6oatEtN3oV4rpQ7PIHE51pmqp9vm88JW7STyRq6yuR2NdSQDTzuMPM6xiK7xK4Fs0NMMMaszlGbOUetXbsLa022fZGJ18MnRyq5e7kZBiqsJHU27wM_XcGhHPdBzcVTxa-Jyew3YhPjeqGuyb3jR5lW_S8huHtdBXx1Se0KrSBVBARP9c1yr5L4q86jw_XQ9pNRPKlEREQR61xFgVBdhDBXhZIjOYJ061p5E7cWsazWoQ5CKHgW1sC7rDoMm1DaB9jPMuneH8XeXW9W5aOsj3EzGY_BH2jR98XT0e9apUEl87HEauBLUPmqoVHSFRsXB7BWAy8OgFemAYuD8J4YiyOZnSF6YRRu9YDuPcKsPr0AlzICb55Xt1B8VyrJ9vD_AaqnXtVQDtizJLuKn2DyQ92BSNeDhmRm7q9ap5Ko6NtLb_o18F4DHEfeJNGm0HuMRYxewxRdDsh-1aje5EDdGF19keLecl-kcHGVHITZbNfiFJJl-NiGvNgomdUjr4Bcal5QaiG6a3OCiTlT1Ba0hk7GEmRjJ6PfIMstDUTQLmcICxvZ2BRdYy4jUyoo3-WIMmRz1DrqcmeEM9PexSaxV-EsSJWYSEDqagnaNdGG8QS1oFawCGOmYGiVDKqomAjbBMYibtockzbUps4LF9xkuzYGLpkmbUWtVSiamV2AzekVwnjX7kJrTq1AaXYRXaU0jfknjGj3QehOBztRu9PB22AEOVqaHslMGqmSiTs8h7Dyfmur8u2DDEMH8gy4qrHe7eVtZP3pbDSOk8wIZZrtu248ibJTmQ7fb3kmQa6DBMW-adqUKc81fd_kjIMslU2p5yPi-2QrR71WMhyBsh4WX7VzlG6mkoIWxabtKfBAoABS-Eoy22GeTYUnGZOucl1pUY8U8n53KEM3zZd2Fo0nmRHlnehRkLq_OhPf191mWFqW5K3y4w8fjg9vzz4fl9yooqT3QRj-Gk1Gju62Fv-f-9wbleeARjpx0uLj-63PgXq60VhHKpNBCPHAjcNQjlPlvd_yZZjCyAF8zGFugO1u1kEth4JyfWq8zbTmAO2Ujp9VksF6oU5yk0C1zmt2f8WkigG1KmrtaaOmnXA7oSJxPdTCz9WyhVN5uGinonvircvRNztwQXVl2DpyeXcFJ7KXsUqhnAj8wNXm1y3yW4AuoDr44rqQIbgvHfIu0-92GnlUayNQ3GxHLrx-G3Z5t4OreXRr5Wpxtx39SLmyde3FzXbkmaeLo3x_p5nKDKqD0scyZoLR7AehzpZbJXscqhlIO8HLbKiSIgVvpXQBPmoK0mk4SeBMsnYzrkB08CqPli0c0vfaUYsuVcsa9L0OT1SLgS0MrcK0kyqaPq2OrAt12ixoYV9xt2MR04ZJy_zL2-0EisqtVX5lGdhl37F7327f-mY7cmEfyySyZNKTQq7LR8pX4IU6lXkG0-FFs0l0BA4v62BoT1JFVNp_jAOvaE-8ilq-yGZic06tRatwEo18W5ti3r55LesXujrfhf3l3kKL_66ArCAEjve0I7T3ozRreZxCfqnrmTh8HcGlPZRXrTPOUhl5Rzqz773Qd3vT_PZdnlKkRgr594kapQcvUDN90E5zoYoayQzinRqd60Mft_EsuT4vDoGUg8mcUWVmmuk8t055qqSe8uUk1Nd_nMgwyF50KVG5WlLFcDEdxk9avwoyOvlJwbuenxd39sOspKDHmM6j4FY5i5wDKL9WXswPkezPp5ozI59sELnhxFNnUdmper8VBaEuJxw9HX08Rm8VzWwtDWNd5So5BqmgrUW6BXY-8F_ewfxK9JMwdmSIp7SLpSK-VbuNZmNoSmd53pKOZQAB56FYcHEt59iWcadG-vsFlAwe1GB7ZxmwY0_zZC-fCnz6PAkjvdUVaOQZlYLJC-vKS7ByfrqM0b3u-QT2ClYWhFezNafyL2Bszriypq1LecpyexXLbyajEUS5OFIncahGyzRzchvKoyB-KJMEqJX01xdKQcUoyRjL85yCKK821F4_tZzPo41HH6DuH16Cj9S18MbMaKayBh9yAsaMwu-mowex92JMU8ElNcUdSlq6zJVquloEn6UMCyHf3KtQZbGOBN9TVRsHeKh47mYRoaqANA2j1NbmaepzSAGErund76ejZfzIz73pps29Wp8VsxDURGUNRa2if-8FFjX9bTytvjde4zkkcypZILPGIouJGFlsVEv97ylKvSV8Mw5lOnyNKBuorCNKjW6U-B0rLGisu8TrSTbUPdVXrG-JRNfiatY6w_y9gz1-XRZlrw5XsMajjdRmFqoWKawVpuCjcTRXmD8OZ_Vmj9o8PV1AX4OnJWZPF4NET_vLK9t8v_QVFthAZJ3kTmMbBfrvpi7AlkfdWfhNlaWoSC_L5v_-JJEbK04HqY7cZNGVS5g6JMazlvj3iFW3agTVajZtVG64vmYqa2hRScCoNkP_UxSpT1Ws3CTf_NlUf5YorFcTl8j_SWxdrbpHKlPJKIjKlurGrG2ishZ7qwR-x6IuztLfqutgreL9fhSMQKOKsN1SyFUuar5Pm20bymlhxPXlVBIwGuY8u-mVN_e-Vwz5TywFaiu0_ixl3XqyrB-Ufa1MW6itLdspHaN6UOL37IIaN0_6hOZr3P4qKRyEUvfgw3BjT7JMoX8ONsfd-07rqWbyhzJ1padem8svkum_vCKZn-J_72olbyu5Uh_8fV1nq0Zj3dUdu8P497OMUxWOVPYbZ0J5T1KvMUs2zzEbiazhgnJ8Y0pg77ff-cgH_EVvAKrv20quEd6UEQ0TmzaPy1vfPTDlg-Qb2KnWs6zYz39FaJKvqOg0dr2c-46d1fK8t_-q5S0TWWd5ObYxP0D0e3bJXh9m0cowG0fq1TtmjUTWYLLG_xfsl31HNq-03WPIdsFMjxJ9TG9TPjcS6R8XS3SjwN_7oy_t-2pQGk8SV73fuk2UeosoN8nS1H7T2K9tZLq3uzZ7ljlSfoRiPT-DUxy90R_1-qZnZ3JcVB5hgS_V96HoORG95jRTyUt5yvP91j8wY4RtE5Mj_M_tf1AikNim-nkb-Ib0Q7bbjAhiwTfbFGQbwATRgAhjto0Ysyh8I5QxvM0sZNn6G8YUbXNNC74xTDncs23C_wlrjD19CMciQmwT20JA0bRstI1sZBKgQOECQ9zaJozkHxnZJpwTqj-bAv6a-jOlmG9jggTbpoIAfWxhwKeIWnjb4kAcAbQeQq8HEQtRALSQvY05FXpyGJmAxJkNUwMGICSwCYCmacN4NmLbGJYLtIgFwyFb4G2CbbiAmGnBRE2hB0U2gynBoGibUhtmLWyqh6ZAq1g35oJzWCOjlv7LKBCgJttmAsPEmAXT0QRgYoxgC_7CwiyYGIG1EotxfQXBJBHjBMGAFDiGbf0H-ANsZRRYwBinfBt4hSxgJIflUMqwXgiQg7lSDBOhAsPgMDZMBBNrm9oYZkNtE2ZGYcWweoFgsYQKYeplAklgsAXECqUgXABJhjnctWD62zBVLmCF2AJWYhNWW2gFRcjWFGyYpWXredjA9O1CSYCWxbeRCeNu20RwzUqQJSF6fURLnoJewB9E9CJz5RS20BwwQXC5EgLfYaLABhMoCQIig6VowQHHmP5LTX0XpAK8AEytGpiJnIGEmFpWmr1IqxyioJhaExAMnysuXIU_lgUjY2yDxLXzAL7aRI9gax3U97VpcGwCH7ilhWjqW4xSam0ZkGmryhuNtE9250ZY2Pan6_PC1wyzbJy-3dt7enraHctsGPvqOQjVrhuP9saABJa9k7uVHU12bx_-O7i7OPIPvrmjlw8_RM-_PP4ai4_ffH7w9TnZ-XxFf9jhY3nvfHuQ95fB_gE9-wEdOsHXLzeP93bk-smNs5_-dP5C04vs5McL9OHu9MJ6OY0P7y8npydJ-NOJONh5HL-cm-d__3Zhjb6-WGdXafD1KaM48dPLXxPz4NfbHfyQ3qent1-_mVef-Kfzn7-cm_ic_PJTem_fnl9m4me-83z1y93OkTM--UD2f0l2fsq-sZNf4-H-ZfqLuOPpw8PD6O-Px1-88cPzKAp_nsQ_ju7Y3c_MuR5JeubQ8Gb_YXR48_AcPxz99PTsH9_g2P9y-evo2OT85qP12fvlOb1XH342T44wvbpw_Yuf0dPNt18uvdtPD3aqfhL8y8mj4_vHxwfm59PDqx_ZoUm-Hn36-TAwzyNx_0k6l4-T_f2vD2cX3yaT4UPyw9dvX-IfI_8LdajHrr8-7thfz8ij5f9Ens17dMie3r8vnPNUgu-Kl0qlZegovuWeLpe39l4Qr7IiqOJZIF-Ay73AHI60weWWModD81gxnwV8AfefRwodH_SHj3Gm8nv64vRLHj30Q0Plo1Y3WaJj57c4Hv0MU0V4F8yKcSy4SYtDk6dQPlzI8ewIkgYtT1yS8sBlJrOjQCeH-YHdaaDTgD-939qxzF2wL2pyW5gEF48xv8sTjDKKVXvSE6h885fXFKlffrlyTFODVo9oXssEwuxb43r_-njwIZ6ExlUSpKPByRCiXvhiHL8o4-_qSYWDT1HwMFHG2dFbw3EkuFlPcWZJPStLEuUIiS0HrnmSwPKR8BR1HZ9JpUxfeQ5ykcuVaQmXs0E-i5wHbw2LD_JP1-rhrcHNwdloHAZukKVvDXPwBhGuG6Dl-XzjWupnogZvCNVXR8XR3rx0GRRlTGoM5aMy7L_qbCdREmpUY_rwtJE_mTQD9JQMDVSDLJqNRuAbL_Hkf4B_6f8CsYm-JY2yTirSrGulX64RvuR6dBF71zICxET_hZxll22VTC41rRUCr4QgKyGmD4TmSWddyrhByqdxGMZPxlkSQF7hao3rljahyGPc8nyEHEGRzzmnynYt0xbSs4lvWR5IFUuwfUc5nrQsxbDHIAGwiUd9VJM2syrSpgvSJlVZ6MfMSom9wXa3uN8g868aQuqmWJgLW2oZ6WcydOsgXRA60cDYNKTnBXqvC67pVxmU8v83lylpkOlFnDiBZ1wmTrcspYQcTXqM2oK72LSwoEy4zLeQxExJbluCmYoyyC8h_fLgL9g5V550OGIeseuWW5OlWLBczLtlZvUw0RwQgVq4C1shxnGkRoFKDfh4GmR18eYDI1yV7sJ2wr-5hGmDhH9I9PMEhn4SYDQ4jKPH-B48ofFFRl5VwMKChBAp38NEYEd6FjNdn0jumL4JtapUoACQy3lC2LaLqOMSKCsYJOiSUQL-uiZgQQblcX8t0TJYvjUOjIOdg4roLVwVPaoLg5jLDhbculVVDv0AGlzTl3KqRuznplzzuLqWHmBepaYfRDKmTyIZc62oz0A0TOAfbiL9THn_rEHSprn--6hKBwRbCcHb1Y01qNuXYZCO82ZV_0DhuRAjlBLgMGxQPYWw8rntK9t0XGZ5Dvdd6hJwN8h3CEEYai8IIq5pelI4oKLtzgUvORdrRUCwe8aDHLrmYA7CIPJKv2I8BdnQKB57Tn83TWiSEW-Q0WGcJJNxrvuQhcrx4CZ7uQtkZHwOUlUVDORjWBFIvgh1OcFCclNXbMKWgpqW6RIPbhDmw0VIvF0MuZoD5aGNsRQeMXndKdC5J9ivG_6pTA1k7DsvaapPn-dQgzfUNDVfi84OiI7kotFv9qlIBK6j4rp-TU71BkJLJg8-z8gfeDSmb1eYG_Qbtpwa_vFN2GpQD-BQDGlUGMv7wbnMssAF_l2DRY9kEA4KcUDcZqT8fAAMLl8aB7U0mNmuKYQYFI_2lvsfbw2bDqoP-y4jCWKiqvJhD1FMQet8sH_IFx2umKK2tDxsUel63GbEIkRSSEUIJBu-icBbMIcyLGzPq6ccgs8jEq6GpJ3rnYOdE_h7XXEbOl-Z6yceYFxVpalCFno3V5jyZVBVHeRsGTHXwhpzoCyxWnS70PlG2jVPVJ9hTYnnGi7YH1zDOyCsdhsQDTawfxdHL9qnRNng7DFOQFTjAO5PJbag3ESsUG5e1WzuWJTY3AOnSplPFEY28oULpa9FIXUGZYbSiUjClcU85kL9JH3FbEUxdi3Xs-qFEWvJta5ruRZFHblWQy07AI08rMQ27TSLwwPTVAwXOpvXP1W3K_q43Xr6xLoyrTcU_wkds93YZlHGeRyPB_mmoPbItXLbQoJIwSAyMw7OUnmKOUJ4jnCYA_k8Nz3lE-T5HEEw91yXMdf1ofImHGpyvuAvcbW5Qpt1pyyh2YqU6Q2qRdYF12ctO6U3jDVk-bzFRdrN4X-uP6iSOGhVXARN_-sF9TLNBo37HCeZejZ-iOJscPsU79xkTZqHhDKZywhEatd1IIVXjuIeJxCzlWNJm9ucOdwmNuKu5_g2uDOJfUJsS2FLMN6heWZd86ZakDsdLcumyAgax5dzuTe8QakoafRhNZVp1CmxQueX6sTSVvAKvP9qon6fa1NSmgSjNNe-k0Sm48FtABwzTuQkykIIeL3SUk44q-qtIkJK6UM09pDnItv2oHSBSGs6VGJGHFBbi1iKIdemvmTcs5W09auQsaMIM0W97iRtGeaBcWJUs0u-kF2yhjZV2Z6CEJvoN9CqPGMcvRTx9HaYqHQIujlgqCkx5WJZ-4lo1HRzFzQ99ud9rqJmnTa089cn6SZ2WhjM3ABw3gqF8lFFd1Dqals8Us-Z0iL7rxbrZS600C_2T84OB8fPchRAACz2CFLjx0ng3qdBCEmR8SGU6b0WRjYEzr9Ez7WckfnMhbraRZbDFCgyJr7jSsUxF6ZEkjo2lOLEpswzFWSJNlfYVeBxoX53MLW6dHWumgzX-yX1ttm0Y7ZQWtd7sIY3ybs_xWpUfvjhN-xvINLE5ptgNCqaUEfBI_A7N4I5g28g61yIYb6HbA9hQYUjHcfhriRMuj5hTGHiYl9yZmPkSWS7nhKOyWzCIWd3kCkxFcSt8xe38Hdxm4qxuYHvj_T5lGmKrLwBIrW8eJo7G_o5pgEzc7udXZRj_UsxnnEWacvWG0zgJ6MsNc5Go0kEMynSeBCQ5oofJ4ZlpPl-X6q3rfKtqqchOMoZUBOBsnOk8nw-9jrpyFz08NV5WcT7l3bEEG3SmENQCBCLjKaWqVcfZBWlOYxHcGeS1DpkNhKCOcSiPiIUexKqNN8iBBTH8amEyAFaQiFaQEQRGGxUWkyAbboWlH0WwriuNmabWdKF_S7WaJYEVWu2_H1WhqO0vHXYiBZt8_g3t82mBvHpyxiyycCFgJK4w8GXl2SUQuABvdNPc83iOAJmtMVxS1j2oNzZBUiMpl8amkomqfWULOIqAdJypOViYtkOsQVkrtxSnANZhjl1mAX5LNRSgiPPBPERZIJ9epAT1L2oYM0R_3rnRHeUqvJD9Yifv-BVaTuGKeLckHMHNYYoUBhT_nH2AmmjeIP0YstpKW2lqNYwXe51VwZGu3xxUEDBzcUU7toX74wGxZZ4nv6WppWBTqqiSz7bDH-DzXpev1yjzVMPzv_0bawOCLESwl4JgcwOo27aUThK5B2krAeJDLzBia6a9kcTyMtrERZCqICsBTJ04tp631AJ5UoK9aIFiTilkII7ju1BpYghleHccXzs6XNmrmk7YGA1V8laoyqeq8p-GMYuKHtq3OgTKjryZ0qFCz2qYiX6bnE2xoc4rG2BTku1-Ts2B_sexDmU70sge3F3ODe-cs8H4bYzCU11KKHtfd7KDoX5X8VfqfiNOms1hfwyNdQSmEd5_TbRhdRQOcIR1HFAPV1kQnjHRLmCEcUsTJjNue9QE3sAYjqcwF-BTM_0qSWpJxXFi6eWZkED2R2p4bUa6QfIjcNJkhbnFSC36iXvRg4sNLk_Xl5f7J-D3QZ-9qQzucXzAMj2mWdjk3rU88EoBWTFEDIR8qhFPJMKm9rCdBGnyIP128wkhDhcQlyVzPPri8bN5wFOdvR5gFqDp242tYbzxku3G_O9uEiUoQKTSfatXnz9IO8hVNW2qBF3LC6kJV3sId9W0gRBc9fHNlZa-raFodZhkAyalHsItEHaTHmYceT70u9XHiyWX3U_VSQB8x46E5XuQJ7L5WnqTF903F074XvdqbGmHiKIr3gxgHEaJ1HRuy4eCZwle5i3N20gNtiL2y2MrNpusSmtHV8SkE8qLk3IxJmwXCSlhCqZIGRhlwqQqAnpuatck1nS4T4zfZ8g7CAKsmbmggmL1k7PzsIBF1IPTNrNL0vsZqi3RgqBDUS9HTMNLPkZHi35ybhox-Te3-4Rxvqcjpn2JVfEH7QYpf4M3fRGPW_qUJ4kwaj_jiGzV26Hk1rp4jDXs6FCAX_jcc9zfM5sT3mgoIwiBwuiPNNSPpG-ZTq-pZQvPSks5VCdYfmiywO1ntDq3DVEzSe0zPbNHlIvI3TgnVUk5Sld1aSxhY4V0aCqtqRtT2hp7_KPq5Q3YTz9EYv5i1inJ9anvroCVIQCUjnV3gA0fXnNDAYtwxwo_fzaFIK3jcQqVKxloOnD4bMz-2YboepBfNI8nYUjRFUU1ka28rwAstuAcAUILwPNX902hRLtQOUjlbMFo1ZQtACKGqjqvbjqwA1LqL37dApntZCqctlsopW_cmcG0sDWovKrwExVo3zaoONJg_o7oJf5odmxKOOKfplT82li5QIa7oe2ZErL3NhwQk1rWTGpJhVfgdJq7Y2q2TQnshl_-3EBfyc0utkk-Waj9URr4iZaIeEmhVohgcKDrjtQgyrxTcZZoX9tgaQHZbK5HaFNVkI3Uwa0merR1fJZCq4NnF2XbJN-bbjwXp6nIfqvntAGbpCsWvcsBK4pv2Y2b6RgbBOkXka5nD71y596rJRtzFi8gSryzYyJbKbBZH09o5u7_g20ejl_7ct80sc4G1Lffrnvyom_IgfqKculVLu3HPgGeok2toJXKExfv9xcT6xTUPQWzgretRQjPdwM3pjBG7qM_hJdqpl6LIf04FNDpdVbDnRjdrFNwl0fk1kuCnsr-oo5tRaUe2VFmT98nzc9898EjSM_uFv6hc_89dzp9EdWln_js_4DorrNpX9B9FM0jMOXC93x3DKcOA6VjMrH7NvQ0k-pWvg16pWI-o1--vxO8lHJxHk5jJOxLoenc2QNOGMZZUMVRxfya5yc6F_2nv7O6UdYYAOCIyNP_1DiCjC_OP1TrOBD9Uvx_p7Vq5HV19SeA3p-Eit_beRqZN0XyB--PVBK_7Dj9IjAOkwszlBeRvmRyYqkzU6s4v30yrvJf6tUn8XqFoDS1M_Sg1j_cMOUqfm3jlWBbniVV_RtsrqpChdkVizPrfyYUKFbi2iYdc03Z-H0RFhvC9BvedcPfy6YwWzILnUOon7qPGdIYS16Q28yUt6cpYvCuwqlq_SxWZVURVj-SvkU2jLNbvi8GV3-bOMyF1uQZnsm0_fbzqSGZ13RtvGS2a_A9l1SPsXFkYhJu7H04ZvFddFVzIAr6y9Jj7QZI5YXtXp-665p8VXE_Wc4k3LLkO_2psHp3d6VzIaXfv7b2oDwt8H_Ay94oDM=
```

### Screenshots

![FF1](https://user-images.githubusercontent.com/112500330/187481123-800c5f6f-b4b4-4fad-b1f9-e2609f822d72.png)
![FF2](https://user-images.githubusercontent.com/112500330/187481140-2f63a0e7-93b0-42eb-8efc-a020a798f3eb.png)

**Comment by QuickStick123** [comment] 2022-08-31 12:05
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4468 and mostly resolved by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4716

**Closed by QuickStick123** 2022-08-31 12:05 UTC
Labels: bug
