### ISSUE TITLE
add support for corrupted soul 

### ISSUE THREAD

**Issue by mindyk** [PathOfBuildingCommunity/PathOfBuilding#709] opened 2020-03-31 23:01 UTC
mvp would be to "just" add support for the 
"gain #% of life as extra energy shield" so people could add that manually to their timless jewel bonus points for "50% of non-chaos damage taken bypasses energy shield" which maybe only makes sense if you add an ehp calc like mom has

**Comment by ppoelzl** [comment] 2020-03-31 23:14
Duplicate of #246

**Closed by ppoelzl** 2020-03-31 23:14 UTC
Labels: duplicate

**Comment by LocalIdentity** [comment] 2020-03-31 23:55
The 'gain #% of life as extra energy shield' is already supported in PoB and has worked for quite some time
