### ISSUE TITLE
Crashing Issue that might be related to AMD drivers.

### ISSUE THREAD

**Issue by rockfroszz** [PathOfBuildingCommunity/PathOfBuilding#1850] opened 2021-01-12 19:59 UTC
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
* The app crashes every time I open it.
* **What were you trying to do?**
* I was trying to open the app
* **What steps will reproduce the bug?**
* Trying to launch the app when my GPU workload was set to "compute" triggered it 100% of the time. Reverting the workload back to "graphics" solved this issue.
* **Does it reproduce every time?**
* Yes it reproduces every time.
* **Provide a build code:**
* Version 1.4.170.20 (2020/12/19)
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.
My specs are:
Intel Core i5 4590 3.4Ghz
12 GB DDR3
XFX RX 570 8GB
OS Name	Microsoft Windows 10 Pro
Version	10.0.19042 Build 19042

**Comment by spookyorange** [comment] 2021-01-13 08:47
it happens to me too, it just crashes but sometimes writes an error
![pobiss](https://user-images.githubusercontent.com/77382882/104428064-0c502880-5595-11eb-81c8-ec5fe83334f9.png)

**Comment by ppoelzl** [comment] 2021-02-11 01:53
Duplicate of #1843

**Closed by ppoelzl** 2021-02-11 01:53 UTC
Labels: bug, crash
