### ISSUE TITLE
Mousing over Rampart notable (Duelist) then to Fortify mastery causes error

### ISSUE THREAD

**Issue by ayylmaogod** [PathOfBuildingCommunity/PathOfBuilding#5606] opened 2023-01-17 19:00 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

Build link:
https://www.pathofexile.com/fullscreen-passive-skill-tree/AAAABAQDAQHcAecFLQU8BiAGog2NEYESMBNQFSAV8BfcGJEY7xmKGbQaVRqPG0Yb-iFsI_Yk_SXfJwsslCzpLYMttC5TL8wwfDHhNmI26DfUODA6Uj3iR35I7kkPTZJQ-lFHUWNWyVuvXzlhIWFSYetiF2OnZLVlTWhJdKB07XiueT96U311g7aElITZhO-GDYZghrOG0YjtivCLpo19koCTD5cGlwibJpsto4qkGbCru-O8n702vqfBgsSCxKLFU8cZyX_LBs8Kz3rRb9Nv037URNRS2sHcMtyM3Q3dRt6H4e_nVOfH6drsXO0_7g7uevAm8xv0fPba-hj6gPsJ_MX-WP66_97_-A==

Basically if you hover your mouse at Rampart notable at the Duelist's tree then hover it to Fortify Mastery it causes an error 

![image](https://user-images.githubusercontent.com/66297433/212987856-f1149b9c-3a5e-4b25-ab96-2dd1bfc7ec51.png)

### What are your system specifications and configuration?

latest

### How to reproduce the issue

Hover to Rampart then to Fortify Mastery

### Character build code

```shell
https://www.pathofexile.com/fullscreen-passive-skill-tree/AAAABAQDAQHcAecFLQU8BiAGog2NEYESMBNQFSAV8BfcGJEY7xmKGbQaVRqPG0Yb-iFsI_Yk_SXfJwsslCzpLYMttC5TL8wwfDHhNmI26DfUODA6Uj3iR35I7kkPTZJQ-lFHUWNWyVuvXzlhIWFSYetiF2OnZLVlTWhJdKB07XiueT96U311g7aElITZhO-GDYZghrOG0YjtivCLpo19koCTD5cGlwibJpsto4qkGbCru-O8n702vqfBgsSCxKLFU8cZyX_LBs8Kz3rRb9Nv037URNRS2sHcMtyM3Q3dRt6H4e_nVOfH6drsXO0_7g7uevAm8xv0fPba-hj6gPsJ_MX-WP66_97_-A==
```

**Comment by ayylmaogod** [comment] 2023-01-17 19:08
Looks like its triggered by poe.ninja imports because masteries are "selected" but without any choice chosen

**Comment by QuickStick123** [comment] 2023-01-18 08:14
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5489

**Closed by QuickStick123** 2023-01-18 08:14 UTC
Labels: bug, duplicate, crash
