### ISSUE TITLE
Catalyst Calculation Error

### ISSUE THREAD

**Issue by Lothrik** [PathOfBuildingCommunity/PathOfBuilding#1723] opened 2020-11-13 01:34 UTC
Catalysts do not correctly scale values past certain thresholds.

Example:
0.8% of Physical Attack Damage Leeched as Mana turns into 0.10% instead of 1.0% after 20% quality from Fertile Catalysts.
![](http://puu.sh/GMUJk/7f77c229d1.png)

**Comment by ppoelzl** [comment] 2020-11-13 01:35
Duplicate of #838

**Closed by ppoelzl** 2020-11-13 01:35 UTC
Labels: bug
