### ISSUE TITLE
Tecrod's Gaze

### ISSUE THREAD

**Issue by Spastic111** [PathOfBuildingCommunity/PathOfBuilding#2872] opened 2021-06-27 20:20 UTC
* **What happened?**
The global cap limit for Tecrod's Gaze does not apply correctly in POB. When stacking Tecrod's Gaze, they should add the Stats additively per Tecrod's Gaze, up to the 100% and 50% caps respectively. Instead, the stats add beyond the global limit.
4 Tecrods should = +50% global crit multi in off hand weapon, instead it gives 80% in POB.
* **What were you trying to do?**
Test the Tecrod's Gaze global limit in POB
* **What steps will reproduce the bug?**
1) Have an off hand melee weapon.
2) Insert 4 Tecrod's Gaze into either the Passive Tree Jewel Slots, or any 4 Abyssal Sockets
3) Observe crit multi stat
* **Does it reproduce every time?**
Yes
* **Provide a build code:**
https://pastebin.com/wYZugVw3
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by Wires77** [comment] 2021-06-28 03:26
Duplicate of #2865

**Closed by Wires77** 2021-06-28 03:26 UTC
Labels: bug
