### ISSUE TITLE
OnFrame error when hovering support gem on Skills tab

### ISSUE THREAD

**Issue by randomflyingtaco** [PathOfBuildingCommunity/PathOfBuilding#1954] opened 2021-01-15 07:07 UTC
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.** Version: 1.4.170.22

* **What happened?** Added links to my skill, switched tabs, came back later and Increased Critical Strikes Support had been added to the end of the list and gives an error when you hover it.
* **What were you trying to do?** I was trying to remove the gem (and am able to remove it because the error only comes from hovering the gem itself).
* **What steps will reproduce the bug?** New copies of Increased Critical Strikes Support display their tooltip correctly when hovered, but the original one has the issue when you import the pastebin as well
* **Does it reproduce every time?** For the linked build, yes. I can't find the steps to cause it on a new build.
* **Provide a build code:** https://pastebin.com/BfwDt79N
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
https://i.imgur.com/apOVBMt.png
Error message:
In 'OnFrame': Classes/GemSelectControl.lua:424: attempt to concatenate a nil value

**Comment by Wires77** [comment] 2021-01-15 07:20
Duplicate of #1950 

As a workaround, you can delete the Increased Critical Strikes support box and re-add it

**Closed by Wires77** 2021-01-15 07:20 UTC
Labels: bug
