### ISSUE TITLE
Intrinsic Catalyst not working

### ISSUE THREAD

**Issue by dp101428** [PathOfBuildingCommunity/PathOfBuilding#1441] opened 2020-09-22 06:59 UTC
* **What happened?**
Adding an intrinsic catalyst to a ring or amulet with both +strength and +all attributes didn't increase the attributes gained from the item
* **What were you trying to do?**
Use an intrinsic catalyst
* **What steps will reproduce the bug?**
1. Craft a new rare amulet or ring
2. Add an attribute modifer to it
3. Add an intrinsic catalyst

Swapping steps 2 and 3 leads to the same result.
* **Does it reproduce every time? If not, why so?**
Seems to be consistent.
* **Additional information:**
Abrasive catalysts do work, I looked through the code & data and it appears that they work because they just look for generic "attack" tags to match to apply a modifier, while intrinsic catalysts look for "jewellery_attribute" tags which don't seem to be used anywhere. Apologies if this diagnosis is incorrect, I haven't been able to wrap my head around the codebase yet, this is just what I turned up from looking through ModItem.lua and Item.lua. 

[Build Example](https://pastebin.com/6qWpy85z), you can see it on the amber amulet and amethyst rings.

**Comment by randomflyingtaco** [comment] 2020-10-01 08:12
Mostly fixed in 1.4.170.13 but there is a weird lingering bug where catalyst quality doesn't work on the implicits of items created from the presets in the bottom half of the items tab.  I guess it's probably unrelated.

**Comment by ppoelzl** [comment] 2020-10-08 01:49
Duplicate of #838

**Closed by ppoelzl** 2020-10-08 01:49 UTC
Labels: bug
