### ISSUE TITLE
Ancestral cry not giving max res nor exerting attacks

### ISSUE THREAD

**Issue by Skymunk** [PathOfBuildingCommunity/PathOfBuilding#8076] opened 2024-08-02 20:45 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the value from the calculation in-game?

In game the maximum resistances go up by 1% per 10 power when ancestral cry is used. 

### What is the value from the calculation in Path of Building?

Pob only counts the resistances given by the ancestral cry buff. Maximum resistances are not counted. Damage also doesn't increase with overexertion even though ancestral cry exerts attacks. Also pob only counts ancestral cry as giving 4% elemental resistances per 5 power when it gives 5% elemental resistances per 5 power in game.

### How to reproduce the issue

Enable Ancestral Cry in skills and set Warcry Power in Configuration to atleast 10

### Character build code

```shell
https://pobb.in/nLD6AFMpDkdt
```

**Comment by Regisle** [comment] 2024-08-02 20:53
> Damage also doesn't increase with overexertion even though ancestral cry exerts attacks.

it only exerts strike skills, not slams, and so it isnt exerting the attack you linked in the PoB

>  Maximum resistances are not counted. Also pob only counts ancestral cry as giving 4% elemental resistances per 5 power when it gives 5% elemental resistances per 5 power in game.

PoB scales the buff by uptime, this is intended behavior and a duplicate of many other bug reports, if you increase the duration (or reduce the cooldown) it correctly gives 5 res and 1 max res, you can config this to happen by changing the exerted/boosted calc mode on the config page

**Closed** 2024-08-03 06:34 UTC
