### ISSUE TITLE
Nightblade support not providing Critical Multiplier with Varunastra

### ISSUE THREAD

**Issue by LAVQ** [PathOfBuildingCommunity/PathOfBuilding#5091] opened 2022-09-20 14:18 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

While using Varunastra, it is possible to use Nighblade support with skills that support mutiple weapons (cyclone, flicker strike, dual strike, etc.). Ingame the Nighblade support will give all of it benefits, including the elusive buff on  critical strike and the aditional critical strike multiplier for the supported skill. Ingame this works when using any support (even restrictive ones like close combat and cyclone).

### What is the actual behaviour/value?

Path of Building won't give any critical strike multiplier from Nightblade support to the supported skill when wielding Varunastra and checking the "elusive" box. It will work only when switching to a claw or dagger.
This only applies to the critical strike multiplier given by the support gem. Taking the dagger mastery that gives 40% critical strike multiplier while elusive does work. Taking aditional effect of elusive on the tree won't fix the issue.

### How to reproduce the issue

1. Equip Varunastra (or dual wield Varunastra)
2. Set any skill that can use Nightblade with Varunastra (cylone, flicker strike, dual strike, etc.)
3. Support it with Nightblade support
4. Check the "elusive" buff on the "Configuration" tab
5. The "damage window" won't show the aditional critical strike multiplier and won't consider it for total DPS

### Character build code

```shell
https://pastebin.com/i7BLruBD
```

### Screenshots

![image](https://user-images.githubusercontent.com/114001255/191280981-df130add-579b-4d24-a2e3-59c09d53a1ba.png)
![image](https://user-images.githubusercontent.com/114001255/191281117-88139e27-5266-408e-8bcf-fe1e5ddc5b2f.png)
![image](https://user-images.githubusercontent.com/114001255/191281169-c20fee0b-fe7a-48e5-87f8-ee71694ffce4.png)
![image](https://user-images.githubusercontent.com/114001255/191281400-022a3ba7-97a8-4faf-9b51-8bfe44f829e6.png)
![image](https://user-images.githubusercontent.com/114001255/191281470-49d98f3a-7df4-4cff-902d-e54592c8593d.png)

**Comment by QuickStick123** [comment] 2022-09-21 07:58
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/567

**Closed by QuickStick123** 2022-09-21 07:58 UTC
Labels: duplicate, bug:behaviour
