### ISSUE TITLE
PoB has stopped to show any minion stats

### ISSUE THREAD

**Issue by hwatik** [PathOfBuildingCommunity/PathOfBuilding#2648] opened 2021-04-22 07:47 UTC
In latest build PoB (first time in its history) has stopped to show any stats about minions except these in left column.
It still shows DPS and Life in this column but NOT showing anything in tree changes, skill changes and item changes.

I've tried to create new build, picked witch, added spectre (and type of it) and some supports. Any changes on skill tree shows only player stats on tooltip. Changing items don't show stats at all. 

I thought that maybe problem is with spectres, changed it to golem — nothing changed. 
I've tried to reinstall, tried to import any builds — nothing helps. 

Then i've downloaded version 2.0 and... it still works, so I'm not crazy or smth. I have no idea how did you completely deleted minions in 2.2.1, please fix it.
![photo_2021-04-21_22-17-13](https://user-images.githubusercontent.com/52550424/115676187-c6131e00-a368-11eb-9e6d-e940014298c1.jpg)

**Comment by hwatik** [comment] 2021-04-24 10:05
Still not working in 2.3.0
Am I the only one playing minion build or what?

**Comment by ppoelzl** [comment] 2021-04-24 10:12
So... why did you delete the bug report template? Please fill it out and maybe we're able to help you.

**Comment by ThaPear** [comment] 2021-04-27 09:02
Version 2.3.0 (2021/04/23)

* **What happened?**
* Minion DPS is no longer shown when changing items / jewels / skills
* **What were you trying to do?**
* Get an estimate of the DPS gained if I were to buy a certain wand over another wand.
* **What steps will reproduce the bug?**
* Make (or import) a build that uses skeletons and go to adjust items / jewels / skills.
* **Does it reproduce every time?**
* I've tried restarting, making a new build, importing a build that worked in Ritual (given below), importing a build from online (Navandis)
* **Provide a build code:**
https://pastebin.com/4C18TPgL
* **Screenshots:**
I think the screenshot in the original report shows the issue well enough. There used to be a "Minion" header that showed changes to minion stats / DPS.

**Comment by ALT-F-X** [comment] 2021-04-27 17:19
From the build you linked:

![image](https://user-images.githubusercontent.com/5727264/116284376-a4dc7400-a752-11eb-8e01-744fc64a208b.png)

Minion DPS seems to work just fine. I even changed out all the wands to different ones and still have skelly DPS.

**Comment by ThaPear** [comment] 2021-04-27 20:46
I will try to clarify what's missing with the following two screenshots.
This one is from version 2,1,0
![image](https://user-images.githubusercontent.com/710437/116310003-c3ba2500-a7a9-11eb-8ad1-9e3a2d408cf6.png)
Whereas this one is from 2.3.0
![image](https://user-images.githubusercontent.com/710437/116310193-f95f0e00-a7a9-11eb-9caa-cfbb724c3ebc.png)

I created a new build with both and imported the Pastebin I put in the previous post.
You are correct that the left side of the screen still shows the same stats, even without "Include in Full DPS", but the change in DPS is no longer shown when hovering other items / jewels / nodes

A similar example as the above two screenshots is shown below for the jewels
2.1.0:
![image](https://user-images.githubusercontent.com/710437/116310430-4ba02f00-a7aa-11eb-8ebf-7ed2b1f4c5ca.png)
2.3.0:
![image](https://user-images.githubusercontent.com/710437/116310477-5b1f7800-a7aa-11eb-992e-a16807f078f3.png)

I hope this helps.

**Comment by ALT-F-X** [comment] 2021-04-27 23:44
Ah. I suspect #2528 broke this.

It looks like `if baseOutput.FullDPS and compareOutput.FullDPS then` is always passing true even if FullDPS isn't being used.

@Nostrademous Can you confirm?

**Comment by Nostrademous** [comment] 2021-04-28 00:13
Isn’t it always being used? I am sure it is the culprit but you can’t really disable it so need to come up with another solution. I won’t have time until next week.

**Comment by Nostrademous** [comment] 2021-05-24 11:45
will be fixed by #2778 when released

**Comment by Wires77** [comment] 2021-07-22 14:57
Fixed in 2.4.0

**Closed by Wires77** 2021-07-22 14:57 UTC
Labels: bug
