### ISSUE TITLE
POB crashes directly after starting it in a blackscreen

### ISSUE THREAD

**Issue by NichtDieMamaTTV** [PathOfBuildingCommunity/PathOfBuilding#2109] opened 2021-02-03 13:24 UTC
Im thanking everyone for help in advance:

* **What happened?**
~ Im trying to just start POB after installing (same goes for the zip-version) and it instantly blackscreens out / stops working.

* **What were you trying to do?**
~ Found a post on here with a change trough some dll-files and it didnt worked.
~ Tried to reinstall it several times.
~ Tried both versions zip and exe.
~ Tried to open it as an admin and not.

* **What steps will reproduce the bug?**
~ Same as in the previous question beyond.

* **Does it reproduce every time?**
~ Doesnt matter what i try it stays.

* **Provide a build code:**
~ Buildcode / Version: Release 1.4.170.24

**Comment by Wires77** [comment] 2021-02-04 19:45
Which DLLs did you try?  Can you try the same one I linked here and see if that works?  https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/1843#issuecomment-773520102

**Comment by NichtDieMamaTTV** [comment] 2021-02-05 11:26
Did tried to add the DLL they reference to in the post and it stays the same.
From what i saw so far it only happens on the second time i start it. First time its working fine.
What i do is: I build in a pastebin from my build i want to play and safe it.
Then on the secon startup the "blackscreen"-problem goes on but on the first time its working fine.
What ill try now: Just dont safe it just use it everytime only when im playing withouth saving it.
Gonna report if it changes something.

**Comment by NichtDieMamaTTV** [comment] 2021-02-07 03:14
Can say:
I found a workarround. I use the Zip-Files and have to do EVERYTIME i want to use it a reinstall so to speak.
Then im able to use it, sadly as it is.
Dont found out  the reason for it till now.

**Comment by ppoelzl** [comment] 2021-02-11 01:57
Duplicate of #1843

**Closed by ppoelzl** 2021-02-11 01:57 UTC
Labels: bug, crash
