### ISSUE TITLE
"is the enemy low life + punishment" dont work good

### ISSUE THREAD

**Issue by AldrynTH** [PathOfBuildingCommunity/PathOfBuilding#1560] opened 2020-10-01 17:43 UTC
this my POB, i use profane proxy + curse punishment, it "Cursed Enemies take (50-88)% increased Damage while on Low Life" but :/  dont apreciate that dmg taken while enemy its on "low life"

**Comment by Wires77** [comment] 2020-10-01 18:11
Duplicate of #1524

**Closed by Wires77** 2020-10-01 18:11 UTC
