### ISSUE TITLE
"Match gems to character level" suggests gems with a min level higher than the character's level

### ISSUE THREAD

**Issue by benjaminysmall** [PathOfBuildingCommunity/PathOfBuilding#4759] opened 2022-08-12 13:17 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Expected behavior: gems whose minimum required level is higher than the current character's level should not have a high placement in the list (because they add zero DPS at the character's current level, because they are unusable).

### What is the actual behaviour/value?

Actual behavior: Support gems that are unusable for the character level show up near the top of the sorted list.

### How to reproduce the issue

In the "Skills" tab:
- Have "Sort gems by DPS" checked, with "Total DPS" selected
- Have "Match gems to character level" checked
- Set "Default gem level" to nil/empty
- Set "Default gem quality" to nil/empty
- Have "Show support gems" set to "Non-Awakened"
- Set your character level to something low (e.g. under 18, or under 31)

Add an active gem to the current socket group, and make sure it's set as the "Active" gem (meaning it's driving the DPS calculations). Attempt to add a support gem to the active socket group.

### Character build code

```shell
eNqtG9ty2jj0ufsVDM9JiG9AdsjukEBSZkLLhrTdPnUUW4Aa2aK2nJR-_R5JNjgUGVnZTJo41rnfdI5EB3__jGnrGacZYcll2zk7b7dwErKIJMvL9qeHm9N----__hjMEF99XFzlhIqVv_54N5DPLYqfMQU8t93iKF1i_rkk5X0DUmuU8BVmyRR9Z-ktiy7bH1iC261HlESEl3-FFGXZBxTjy_YDjtcUpe0WykKcRNe7lUnyIycZ4QwWY0SSOQufML9NWb4G_u3WM8EvUxYJyOns4_1DhTlJqsxB-HeDGUUbnM454q0Mfly2h2ADtMTvCQdSiOZA58I7C5x25zD8fI1xtAV1znrdC9c7Vz_7OqRZiseLBQ45ecbXKeHXK5SEeEuld6bFbA49zSkna0pwWpEy0GE8MI7oaDbfwXaDM98vFOr16vHYzmjnOsgvhK-uKBjNgovAnSwTwrEl8oyRjCVv0K-KqlXxOqcUssMMlsWPJLGyxhQl6JplO5trIe_IAr-C1IoznpvB3UOOmEEKKWc4hSzmZghC2EYIBYc5DhlUiiY8mqBU9LBjZoE5ntsgWDCa81118D0d1Aj_3EJ5vg5qknADWvf4RxXQc_RMnxmHneS4EjJHx-9nW0i3r4WdrTYZCRGdop8kzmMo9w_oCe-YuN2-3p3LFU8gv3W4Th-2z75Tfuvo3JAUv5HENaPRW0msEMu0NLo9_VYhwtrEXrBDhn8K4EkS7ijXkv2UpDjD6XNlZ611yALfQ7CLnfuRYlOUHZMiZ3bCnZ_X81rixCzt7zAOV7fQpdwjjs1qTMVETq1JBXDVpLVUD1i0hv5rjAbmEYivzeOedeuAGxroC0ojgyqY4HS5ma8Ipg2hizDaXKO1QdEUXqhiG3njNTujSKqiNDTY-Bll1eLpdOu1UeBmYYWhiwOECO81pPqim7LvoumlzdCGaczy1NAfCthIgXIPGKEYupl7HOWh2UZzRWHmMJUepKK0EcaQcxQ-jVi0xI2YNMeY5-s1ZLlwuSme2LXucUYqXcWp3z8O_RHSyiirxJ5mzmAHbcxgu3-bc9lDMddFbK77bLom4MYstnPkFApXDGVaDqQwAO9SXuscGFOMZpQZewFpVmKuz5pBQ2Oxa_G0cqQ4-bUxpv8K3IjBOInyVIS3MY99jENsHkgMFTDLRoijVoZRGq7uwHOXbbk-6MiDEfE0idcs5fLlNaJhJrEnyTrnrUQeacQkC7895ouFOLdogwipPHUZ39yMrx8mn8cFwypK9kQo_Zbk8aOY69XvnavnWFayVpY_Zurxsv2Z4Je5wBphjggFI4SMUrTOcHTZXiCaAWcCjxJmDpqFvIaahIJ-UdVOHa0dgJ7S-CdOOegLW3uYEqyVa7t-RCjFUOziwkE6auKoQk9IVeBrlHG1y2osJY9-9FTE6YtWHbFYgwsxg6iWc7F6xBJ8s8YZ7IlkQUIR2_UufwBoBVVjlzCEtAg3Nf4u9hE9DXn2oyOgFvXI6vxGh12s1lhVnh1prapW9egjHCKt7mpRj7xt3FgiDxcPU9lC1VD6wBIZ5JA0Q0JFzdd6dkzxFkRP8CNf4VRtJFpKU6hRJUht4qTkMef6NK5A1NhKjpYaC4k1PaoaoTQ6iLWaSvRqbNAYtAqjJ6XmFG0hq0Mtu12N-dRqjRJlw6-Rv1jWE1D9h9Z_RTdTl9_Q6urzWyzqkVV-_E6Cp7khBRnLI7zAUIVqg3kLU5PvcisZPjMSqeb4TdSkZIeJ7dRrREtl9kFlG1OUw8MbNdyfKf4X8xcnUpqiWwE5Qgiq5fua_diM0rbbfo8RFdcJjL6N4G8nb2_Sk_EMJdFInCoYKzrolE3pQPYBWSuDbvUWx9nVBqaDG1Hp9q4pYsRhk8Lxnbj0e2CiR0Yhx-mdugRUsYeknYpuksuruVeES7gIL1BOxft_ckQJ34i2vPK2IOrCy2zFXkR4KTKiYclgN_x4Px3eqcUh5QURwaZUW9mrEETawJHvipfyFnG4k1aaQ8pLkpDmEZ4kxaS0tSNFj0ImcUUqThy3-bZHacvo3QDkKYBvKXtE1N3RUvoF7VfrTklSNvoT2W2iFIriD6XfRHYc0kYFzAylyspLHIvVKbT5EYwmnQkHW3SEQTpSKnh6TUsafE-TLcmdNUKWJ4qDGEHEYctWKAk9JYmqAnkcMwiVGXSCHGWxCliIM8ldOqNTekPGnwo78fiQYlwGjqTvFM6DP6o3wRPpQzB3BlG3KdoS4Y8EBih48B2_554EfvfCP-m6Xu_Ecc-9k-Di_Dw48YKe65943oXrnXSdwA1Out5FNzjx_d7FBbxxnR6s-h68d_o9B94H7sWJf-EGfrvFQcDKzbbTLy6thUBBEVSf7u-U01ecr7M_O52Xl5ezNeIrtsA_CcVnIYs7a0ACLU-l5U4F2c4Qvq6Wn65GaDJ00Nev__4z_xUk7t33yXx0Grn5t9P-agkTYD-8igH0Uhm15DZQ9-BZpzAwWEwaV5hUPHxg0HKJNfGy_EMaXAyGxfw656mw4i_G4q-gXz84g3-B0xffrkoxKHx8itbb8BWwRYp2iwyFIWJEwCepLPBlRAnAf4Hoee_M73Z76kuduAxkiBaOF89lwcgzrG6xvmC0Zol8XcnpArQG7HW2U1aOzwqw5cxf0Lo1fNxkGaItZcEWZCKMATKHzsvYPYC6j-aaodVDXTEo4ZYCHdLliFBXmPKGKDcQ7k8tz0gk95BInp15zYzg_k9ovp2QXTtuXXtr2sTTEQ-8x9BW8qaMDkRS14bPkfCD3fFZtLrNCXv2WeTY8PPtYsGxizz_uHtMDNuU7KHwslTcqO4EFvJY1EDvGJto01KTeEP3HbayVXwFNkhGKWniCCs9A2uzuhZ-79plkmcXvl7zKPPty75FTDvWxvdMAsI3AbIQ-w3Nj6En7b3QtYhKeze8IVxMS7LANcwac1ALy92TZGnWCTQuFFrzWpYLc3_aqOMZ2Mmxd4Nvba3ARhuTfLEP8iMiDeOcHtjbBp1iipTTshxE5UUtSxZk-du16_5HyXeXtfIj5R09QvHB96MI6hPxB8FmFIV4xWiE0wIYJzjeFJ9AL--Ae9VPZx2CFzeP5bVtieQZ4JSfEClxgvL4sDDVoLP_nwP-A-0ZVUw=
```

### Screenshots

![bugreportpob](https://user-images.githubusercontent.com/38334727/184361507-50e02d1b-85c6-4d1a-be18-26a3282476eb.png)

**Comment by benjaminysmall** [comment] 2022-08-12 13:22
Potentially related to https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2830 or https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/3444 but felt different enough to warrant its own issue.

**Comment by QuickStick123** [comment] 2022-08-12 13:23
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2830

**Closed by QuickStick123** 2022-08-12 13:23 UTC
Labels: bug

**Comment by QuickStick123** [comment] 2022-08-12 14:24
Fixed in https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4759
