### ISSUE TITLE
Error when selecting number of minions to full dps

### ISSUE THREAD

**Issue by NaTajnacku** [PathOfBuildingCommunity/PathOfBuilding#3045] opened 2021-07-28 07:05 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

I expect not getting error msg and seeing my full dps.

### What is the actual behaviour/value?

When i select actual number of my minions in skill menu, that error msg appears.

### How to reproduce the issue

1. select carrion golem to number 6.
2. select zombies to number 8
3. select raise specters to number 3
4. select golems to 1
5. and then go to carriron golem section a error msg appears

### Build code

```shell
https://pastebin.com/KJYjffCD
```

### Screenshots

![error](https://user-images.githubusercontent.com/88077931/127278207-c223a6e9-dfc7-4b84-9046-8baa132c788f.PNG)

**Comment by michaelreggio** [comment] 2021-07-29 04:18
Same issue as 2987

**Comment by zao** [comment] 2021-07-29 04:21
Seems like a duplicate of #2987 indeed, thanks for the report.

**Closed by zao** 2021-07-29 04:21 UTC
Labels: bug
