### ISSUE TITLE
Feeding Frenzy isn't disabled properly when swapped out

### ISSUE THREAD

**Issue by KashouC** [PathOfBuildingCommunity/PathOfBuilding#784] opened 2020-04-15 09:24 UTC
If you have Summon Skeletons linked with Feeding Frenzy, then activate Feeding Frenzy in the Configuration window, it will remain active and continue giving the bonuses if you swap out Feeding Frenzy to say Melee Physical Damage and you wont be able to turn it off without re-adding the feeding frenzy gem.

**Comment by ppoelzl** [comment] 2020-07-17 16:47
Duplicate of #559 
This is both caused by the same bug.

**Closed by ppoelzl** 2020-07-17 16:47 UTC
Labels: bug
