### ISSUE TITLE
2.42 beta, determined Survivor gives 93% block if equipping dual wield. (gladiator)

### ISSUE THREAD

**Issue by Jauertussen** [PathOfBuildingCommunity/PathOfBuilding#7765] opened 2024-07-21 23:08 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the value from the calculation in-game?

Only 2 accendency notes should give +3 for smaller note infront.  20 base block x2 resulting in 43 attack block 

### What is the value from the calculation in Path of Building?

40%+3% but the result is 93

### Character build code

```shell
https://pobb.in/3r5MAxT5dP7C
```

### Screenshots

![image](https://github.com/user-attachments/assets/b2a9036d-5632-4fb2-a43b-21bbe4eacc35)

**Comment by Jauertussen** [comment] 2024-07-21 23:09
thinking about its the issue is pretty clear it also adds the 50% from shield block

**Comment by AaronDSmit** [comment] 2024-07-22 01:50
This is a duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7729 which has been fixed in dev but hasn't been merged to beta yet

**Closed** 2024-07-22 01:53 UTC
Labels: bug:calculation
