### ISSUE TITLE
Poison Seismic Traps damage drop

### ISSUE THREAD

**Issue by Vallek** [PathOfBuildingCommunity/PathOfBuilding#4669] opened 2022-08-02 19:53 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

I just updated PoB (no sure what version it was before, didn't updated maybe for month) and damage dropped significantly. I didn't touch anything after update.

### What is the actual behaviour/value?

I had Total damage per poison about 191000 and now it's 59000. Same for dps and combined. 

I know calculations for poison traps were wrong anyways but it should be higher not lower)) 

### Character build code

```shell
eNrtPWtzm0qWn0e_gnLV3S9RHPpFN9lkt_yK48ROPJbj3JsvqQYaizECB5Ad36n573u6QRJIICE5M7O1tTe3EgnOOd3nfU53I978989JbD2oLI_S5O0e2rf3LJX4aRAlt2_3vly_eyn2_vu_Bm8uZTH-HB5Oo1jf-a_BX96Yz1asHlT8ds919qxCZrequJmRIt-B1L1MirFKkwv5tzQ7TYO3e9djdZhFifoIZPYsTyZBVLzd-5Qmas_yY5nnn-REvd0bjWWQPu5ZMvdVEhzVbkgvLdQ027MmMkpGqX-nitMsnd6_3WN71kOkHi_SAODOLi4_X13XZhAl1QyuZCzvVD7eAy7-8uYylk8qGxWysHL46-3eAQhD3qr3UQHkZDwFWsh2mL2PiMBCUIH2XrVjju6VCuZIeJ_ZrAv0OpP31-MsfQQpXEcTNcey94nrYhsx1xG2Q9x1BI7SNAYhJbUhHZt3YVxm6iQMlV9ED-ooi4qjsUz8xcB8v3Oy20NfTOMiuo8jlS1k2I1xnRYyPr4cLfhwHC72QQQUYYduwEsXerI7eU-jPE3qQ4AyidinroM52YAlJ2AOc0TmcoH3iU2E6xJn09S2HfJoGsdgEnW0TqaO0okHjhQcPNwu9GJTgvcpxUhwQTst9SBT8nNYmsOVDKJpvpA97kK6kIk8SvMe4j6PQtWARLST6smoH80rUEI_SD3PS5VB3Cj6T3crhGqEkfJTiE3bjLENSo2P3QbbAfNktAvCDgONikVowDbt1Lr6UYdErDMYHKufC4LEXkOwDrmG4FlSs19nHcEGJEHdM3xIC0iNm4VjosfJ-8taAqKE2PsQC5GDcGdSuBw_5ZEv4wv5M5pMJ5DCriHT1fKDoC7adwVnhNDu4HUe3Y6LBMJQFx3KGMwGuZBtBO1m-F2UqU4SHNn2PraxIC5nvDvGxcFzSYxlmnfRIJi5kDWxywRilK5zqDmOwzBfUwL4rzX0WeIvtMeddYS_JJnKVfZQqx3WDaFRrsDTdJnixao3zmKYymNr1mWvH-y2JjFkE7rPEV8rq3Ol_PEp1GcwVL2QWhvrFpy49lr5auC6fNdSbZGuK_ohrMiJGmtzBWM2x2wdkSWZ4X20DnprcX2VWdAjNicqu30ajSMV15jv9vs6fGVhT0fyvg-q0Usdv66fblE1R6yLrBdTW8vt5EHm9QiMkYPFep5KjIY7404xXKhYKUAJ1HK97HSX5enfdFEeb4l3kE3SaVYvLjFdy0mJ0NAL3ZRIytr3SgVTv5G5aGcKOoyhI1tiYu3E4rgNpbtyLQrp3x2nwe2yqOy1g2yPMZre30Mk0Npfnlx3vNQp70rlUa0E4u5m4M_ganVPY-vyYW_6C-De9Oepf3kQ0RNjeSSE1ublpWEc3AN6eYhub5-1uxcQyiYQyU2DfpEGtaa0sxN7B51YrzbsMn2E-Yz14ke-HTQUJYtCpHMemUr-fFqm3w-81wAnSTDNtH335mEZo20YvagRg_ccy0JauZKZPz4H3b3dM_ffvDKrR_rT2eQ-zQorlnlx4PvpNCney3z8dk_aIbdt4jEpQyZ9CNTEUdQLvFA5AWeCedzhRIJXatQrJeMJSPeo_KonJv0CsoKh5VHsYIRt1wnc0EaEO5QoJBFFyMOSe670qYuDcu5vjmTs54aJs-R-WliJWXeaRLn_3ZuGoV5e2gNJZGaF7OTdu5Oj67Obk4rvOkp-F8Xx92Q68fQ6SPnvwvdGysRUK596efnx7d5NpB5HGutYFTKKQRd-GsfyPlfB271QxjmMHMFHAzMCAfvFGmoGCvLibAWjndYCoJvSyU-VFcAv1B1-FqnOec3vb5hUOaAuMMrFr3Zqemmnm1CZCY608mXRSaNck-umolerOtnRN9fggunKuHPk6u4GSRRP9yqH9ByFka9dbL3KrwG6hFojF98H7_Sf1ui7ymfdNA5js5LZTqC82Y1cLpt1YVd310j1Nom69Vnd7UY_Vr7s5L282Y08LyjTxNST7VTmUGsofaoWDsFpDqJYJ59OzZ7Eag7STfBzMVZZmdE6KV1AjJqBrHWcLPKmRbcb1yDWyMr0xB0S0ve6Uctur4MHfW9NJGr0NB0CrcN0kyqbqM5Atg51Vnx3iK-8u4aJWRvSMf_qdjeBshDq1F9VVa3zbyi5u_1b3-xGLv1jlUSRTXtSMLZ8rEIFUWitMc9h1vi7SSUHD2kUlEX6s6iZmbUTW7C3Fa3Ss1uZ3ZqiaWKeyeFyb_NLxF8tqnUE3RrIBkIQLd-vycf9KM3L_vdQFBbjyzSNn0dwZfHwWXymRS6T4FivdvRm9M2rWVH6xtQBuZVD0XyqJvnhEzQp73SkW2wImbZlIgtIUmpyrjdor9N5RXxebthWg0kjqKqcLHTf3aQ8M9JAhXIa6-t_nco4Kp50e1C7WlHFcDEfp4_avkoyumLJISSen5d3DuKioqDHmM2jlFY1CyMBZK5VF81W78FiqkYYb_eSCBQbJX48DdRZUjVs1eVYenpCejNbr5LOvS2PU71KkabaypbIlqhm3L-8gelVuKdx6skYzwgvOK3fRvMBNKUzHcV_gp5vp1FiqtMfJdNnpggxUtuzbtVEf7-AWj-ANunVWQEieaXl8srMBz61EqmPPmfMtE7VHHX7odd8libxqh9rZBNnlXbBpKLkMtZ7h9tyNzePVRpbMHfwqB1EBZah0pe9zZqrpqe32A-S4AJcatZB7cxnN60t-NVELIgdliZj1Zu2X8j1ESgDwoQe6zl6baGyBacVuqXxq-wDMdA4xT8zLHxV8h7CNXpWZEB4k6RvpIwv0rhQyWgMyXjn4NBFx5yE6SVnTcEqSVgljZ7mRPtaE7Tnn5NGkbC7TXXSMsmon2EBDetxDOyWdKxauv6FTnSW-JmSkNWPoRUvV853Zrub1hYONSdizan8q70KW6NHHQ2e41o9xX8QBJHmUcamLnmG8Lso9be4k8m9XvL914kbZPOg_tnFzQiEMNarmjXJQmmnMl1ooF7R66uhABX_qFA7JYk5ActQ-GU-fKzyexllu4flaZzovflII-_C2GwCv4yjQyVXE_qW6lqhsQVDGtfk8r4s9XV0vc5UPKtQWabQ37FnmFs6Ntq5ZQmerNm604pvo1_m2XrrF7KkLwO1Ww1Y2UsXnS3MZqSifBL521mO-280Hbyb7WxkivXk6UviwXDBbDX5mb3ZOmq7dGkVPau52P2LG7bFmei2UIe3aNdWKG3Dc_Cg1w-DRgPz_53ps5YbbtIouJBJdD-NTQH7TOteS24X89YErTrFf32F_U8u-k4z6e--lNXE7p9nS7xfWN1BLJjoBbGd2rKKmXYq_Zlq4m9izkweXAtgl0qJ_pHjLipgSM-sey7TM6R2lMRoOpkYMgvyc2mgvusQJRGra5L16etDTf86z3qvIFcV_9ym9V0McjiW-XhnHaxS2CKAGWTLYP_qPPVO6lU8vebyjEDdQmQb7gy2pdH1A2e_msPF-kBr4bEdp-XzE1-jJNitWtbYlkH__zbr-YvAz1-uwv-XlquqjyNVmP3IchtSf7zOlJrtIxoSqNrOgy_1xzf17ImWp3bIp-qYytu9vzObMz7EjAr-j-HfMRI2GiKO9RciMGFDhxKB4BuljNpDSmxHf2OMumjoINs1aC4eUu5QrOEcx2FDaru2A98Qh3-HArvCgLkuAeqCaUBGHMSGBMgT-OZQm-IhEoK5GlK4NoGhsUP_AfJJA72LiRwqhsgGYkOKHOHCrG2HDxnC2B4CJHWGyHFhkpg7zBlS6goxpA7jYshsJIZEuPC3JgrDYhvmjzkHEFdwPiSucNCQwD8uzMIBxhFGlAyxnt-wnHk5K5AR3CVMuHSIbcYASzCisbjjDh0sCAjGplpYMFl9F7k2DCuAP2oTBwMdBhSoSzjAEwR0mC24RgKebRvwkYvhAmWYa2jK2VA4egQk8JAJ4GzIHIScIeGOQ-CKTQAOLoMEYKIuzA4zBpggTRgHaQkYaTNCtWRshIalPhHhiA4dhhxtBNgB4QlC9N82gukyBmxT17UB0kVUQxIxxEDLGZa2AtNwgTpiMDEwIhhCuI4eTquTIKIngG2qAQWhmhZMRtsLcQQDbXAX-MLcNhdAD5UdAKsgBYGxxgP2QdUALVwYHTlmsqAM4Fw_OwRwFPCpS2HKmGtpY8Y5_A3iB1pE6GkRBIwizdfQJVo4YCtAgDGu7QBMZqg5oVqwBCZuCy0ExmHKoEYtY6xNV1szsTkhQ46ItjEHrKN0FAZihivAADCIqbE9MDDQLQFBlw7DKKANS58rHQUMTisAgWA1e7ZWIyidEsLpnlWAd9ce6Uaiekpbe7NT7dF_uTovA-K4KO7z169ePT4-7t_LYpyG6mcUq30_nby6ByQIES9N8Hupyb46gP8Ob_84Dh-_PX68wxH--j57OrxKru_Ocu8geng4__3phP344_Ah_xDeFPnfjuTNhH89-TlyH37_00Uffz9Obr5MLz7Fh-8hdH_4Et488MPoVn37Mv3-5UfwY-KSx8-XGI8vw3fs4UdoF7_nn8YPnx8_xVeP3t2XILfvfn6P8ncvH6_V5w8FOeKPh9mV5x7_9diZFt-Pv46-p26UnTo_vK9PT6f-eT7Kb79F8c-Dm1HycDz-6y0-J5OvF-JJJS_vPoenHx__TA8_nH13TlPxM7k_-PQySqdnj74S3qcxjc5_XD4F37zgIbl6eX54eJribx_vr66P_3D_JOnTwWh0fnNOvp3gHxfnxcEN_x3yBnPyq5_y-1X4gR5fPdzGNw8fR9nN2Y0b2T_90R2-uLyZ-t_eFXcTb_xwfHM2_RBOPsbTg4Of7x7ef7l_-Th-ZPTbpf31ZfpJEnGYuTcfvVQejK4-_Pie_jg7vX8nHgoX6E5_BH87_oN-P7369v1jcXf3tswAM-2-KZ-1z6vcV34zkdHYgnYuyLhFmabQvARZgjOxZAGH7S5AEwhrBN1FSlrMA75AljEJSach_eFTWihzT1-cfTFJSh-uro6ij4pM5_8_03Tyh57TPrEhfjguRB5UnlN5r2RxIe_nB2U06Pl8Nc6ccSlkcRxBGsvMGalZWtWAv7_de4mxs-9C6IcgQyEAlMd4TNKukqX-PDtzM81VVfyZ4sNcrp2M0aD1UzFXMoOk_tq6Org6GYzuI_hmHU2zKB0cZdEkh-rlg3pU8eBLEv2YKuvs-LXluJh7wg8Ul0hyDkHPdxkEFoibts9FKAI_9HwpmWdzz7F9zIjyfQXqcpSNSTAwczASeG1xMjib3MeRHxX5awsN0G9WGs52VAu9HmLp58em9yqACkAvisjBC-c3q0hnQProt6XPfluLnwoY8N90xVbtU07KQ1eWrv8GL5BtsCXUeyexeZZDxlZ5zFEvtOXGFvQUl-TlNgX25dPZX7-cDI5SWcAQo3Em7xOQU6fUIEzanvKI4zsKBKVCmwYSudx1lOcFzHdJIHSeCW2f2l4okMdUYHPhQ9h3JPGaUnMH5bP2r63RBDhZkeGC-dkDK5Y5vj4wq4jz9bXcGssHKLkszH6zfHOUW8umPFhtwf_vo2JwWYZbqzouFoFGzNggwjy1bjOZFK-tZbqBAqkSTcyxZBDARGYPglV66xAzePGqXV5IFedFlk6sUZEmao1pMt8hoa2UQCEFqTIFpQLULMoLaAg3FfZDAmUDpwxsVEECc5kLtulKZruUN4XsuP3F-gJuHs3lZw6tWuZ45MxKH8eQvaxxan7zBAReHikeIFonWu7JADFsTFQ_1GVEqhcqGibaMO9KW7Pd-MEaVXbIvEXk0GeAuI_0kcJscD3NfkyBkLIOJtNYFXWRhwrKIsSpkDZGyMc-4lDCcRkqBcIXkvpCYpczgh1iKyiZAqgeg0AKj0MRg2VD5IIOzKcr9UMrsy5_PPi7n8kQnO0fBzHIF9wut67Tn5EPRpFFdyCVF5ibuKB-QlsArBjZnSUFqAEyOQgEIGwNsXRtczghDd1Xh6rBDfRCwEBrazXYlCfHZ3p-IRw9RiMSzfl5gcoZGDXrOc8fhOsRl0hrWDpWUGhBYLuDyZvPd-C25qjioJo9SJSi2ZdDmHr1iDKYKQSrfYQwq6sZFIwgjxIeQqRCyJaYISQpConDQJcB94UQyPZ8L_Q9CXAyoI7vO2AeyINg0AxfdFCd3IRZ2IMqC7-2Tl_qP1c1G8C46YNzmWmR1RzHPMBT-oo-lmOc0opC6ymd_gekwfw_IX59hPCltB9pNuOnali4cmoyKfha1f3CJe-pnKuFkAltA4jUa0zgBcUr6kVsTbxAon7T7HnMfsNnBrEG3QrTzHKhANF5PtfOPUeW5XTbbYW2OPoxjBBYH5OpfxerwY1eSgbX0KxpxmoWAOkdUpUQngcdVqBoaJNQkMBXjvIRUcT2sCLUt6HzCkH50vN96YaEM4eDrbh-t6MLu8PR_4BoaI0g-xfg6Y9gxWW6wg3RXMkEsonoTvgtrmceEFcQL5XlOPvCXLTuwfFLkS4Jv5SXrkvKoivUe4-g89Jr25y17ttsCcoYqX4EtYdzsxaFvUuVdRjBBM6hrhzDnA9V3IjIvoe5z5TkHvY9n3ocKxUG4JYoYJ7nCo8q5YUEsiM4qOtjD8I2lywM_IA7jOHBSRwAWT2Jps5YPTjzpmO-IO6KlF8wVL-2FBFdd51aoI3exyt6eUHFIjPWxP1CB2gdQZfkWtMD5kJDlCnWKGHJh9s14DQ1cHFwenY0OEkC_UCqBWFTxoX1DrrYO20eoA7rwJOxrlFqClFML9n4UPxBveE5fugEnDtIUUGVE3KXKBfqP-y6CPsYCx-52ONe6EnsIJ_Spudw1IidC41Qu6mRazlNitxKoEuBaAbCn0TKxAroEAbErht4-fCtNfuhhgFlq1WJFUzNAamSWWXW3DpkxjsqZchuZxlMAGqSpBic_JlOngq9XXB7C1mqnmts4WMaeIo4XqiYj21fKIExwa6PlE0k0WtdAQugrbNDCm2R5_mMhhQL6QRKNa2WtOeaq5dXjUzjNDINWVhOhW0FKYgvSYu5ZFYq2jnKqa6Jcws1paiktpFytdIYNdR-FfElfZSLvJZ-ZtTQLwucqsAEYzcBxaQnIKgbmflMypqzXM3WaQ2SP1xN0lqrs7b8Fs9UHVTeuqD2fM4xhcQCJQPikvuhwKEvlS8FCT0nCEJEXcUdaCT1M9iMEhdLlwdoOUnMVddbc-h_jSzddaHjxBwjicsINw8gUNnKp6W86xLfFSrwqOsxxAPoWXBAPcEghkMp4EnpQEMjdHmNAp9g6DORoJ4MfehwuHDRck_THj2axbY9wHxdgKgM_GwymSbaN0zPA7PRAULXJojMixMowqaaRNkAzaDaKBylWTa919UX9E9psJ6QNG5UVmpLiF0NfFtneawTyaz4OZioApRfrJY-QYCJ4kQo34a6x2GEgoX7XOEQcwniZ14QOp4LYTzwfeRAtnWZx33CbYQ81AxIHNfEznhH6VPuVudWbrazSz57lUOVSb7ArCMjhvrhrWmmc-Isazbby8FBAOKm-g4ltcJltiiTVuU2NFycrSZ94nSkaN6jXGr2w2vdC6E2_yq9N5JJWfbn1gcZqGaGPpV_gmM3MjQNJTgLtyG_hJCNOYd4BOnFER7zQb8-8pSyuYB4xoAcUgFRvs5S4F5-QEO3oWCKO3wM86aPIbfeqd9KaNFkNdXK4czjBdDDlMspcjmKDSjtbkq2SNgIt4b9UTSX4pXyoqwYD0ZF5Omn5kuqdRHqDtAmPoeszTxhI89DgkP1jwPpIop01SkZfPUdmyDB7MAPfaE9CQvl2U7QGfnXFjlHwLpeCJDWaJLqsB6n00AXOV-gyGmJMeUz_ya00I7IUoIEUIxO9Ol3kxMOp5kxWaMPDTvQTy5bX5JxGj9ZF9qkm-I-WStu0tqHyVuY95HUD9MODvJcr7rN5X8RFfXWHWGnu3W3mb5bL7ZBiGxQf5R9BamuSUgzitMgDFAAHT2GTi5U0NcxR3oQ96AmI9AyQK1K4W9HKvAIYTOIilDYEg4dRTPaOV2t_uFSq89EMxSuWcZ6UcatWdxZjl8vdBRZ4M6eUG4syJVBznTtbLmQa4Q4LAzQ7Kcw5h2_YOvaF_3biCvdyyLK4d_0omi1v74y_PxHsiqLfJf6xuY6rKmtqz8aRxOVRb6lf30ACpdcZYV1mEW3-keSoTspa3otdFF9XrUjzAhZmJyD7G6TM6ANE3KV_h9iKRR_yMdhwENHhAGYExOOQoEOC1KEDAWhxD4kWD-EjpV5RCmqxLpgUKsDSyOCP_VCphEhaJ86fvZs-koBX9lZW8oyesWLAr5xCg_yMthWoww9AOuZRYWKrDQnTkr7qS8FvNC11ybzrVYyIQ-o5BYC8wvkkkV_C7eRsc_ldSqEyWrGri8_tiVlE-v0tgkk0Isapt6QOflZAGMXrS1-h722LWq8f7oHlYC9Hk9BmOfSB0vKdEFnKrOsZoai2wwb2y2UOwJszw4D32MKeb5AjoekDLEXulJhWzDk8jAMGLTjysfMg0ZFMD-E9OTicHnloyOIXb087LQ9NHDW7Rhgt4eWXbtVi7a9NviQfadl6YT20LIwSl4OSHM9l9Xk-rLMaVHvod6w0Vs31kel7geftENN9Ior6NCHeFTMAxLYbWdAcoTDF5ZAyJrla0eghjUEmAsioCBXEowAWk7hU4Exczyb6GVLFPoOVC3QnzLpuVyfbIB_wTpcpZcxmymNt1vD4UpKay6S1dYULmSsHtJYRx0TK5otq97k1CpS2UMZTiBuAA2AftIm1aKgUO-N6Z-7qLZMgaTRc6WpUqu1Ky07q1UocFvtDdHVqIFJe52P6YalOESaRX61b2X63-p5DlPzRkkIoiv6JUHe1gwcp36RZrMaSgf1eek6awbeq-BWjdNGu4e5zZHwHd-lSHqcgR3YwpNM-BLmHiAV2hAqXFfZboDARMB6PNt3INCE0C-EYb-OmzhLHTd5djcAVmQWF-ZbgfXStyqhtihTn7sYpHdYPYQV0ycF4F9wLII48ZQb2DYPuEsZwhJTDrLDUhGoCxwFFaStXICk3XtGjSLgsJn-_-2LQfPViKZYR3E6-zG_xW8DzI6kzH5tuQZUKojUjq20AM0e0J3DkFUYvT2wgGBdI9VO0jirMLPD6_OBnC46Na4Q7gKqHe9xu2BwjRBaBVo8qDKHYt1Q1QncGajohERLkKgFVC8PNQa2W6Ref8ZyDkg7iNWERttomacYZhAtOi635WtnoWY_IVkeDFpzKKj5Czmr4tDSsA68J-hHwfzLc1U1U5mduWqV5BIa7oe24hWrsthxQm28bJiUdp4tUTodt9Uw2-ZEdpNvPyngX4RGd5uks9toPdHapIk2aLjNoDZooIyG2w7UYkrOLuNssL-unNCDMtndj9AunNDdjAHtZnp0s35W8mSLZLcl22ZfOzLeK_KsJvLN89khCpJNbM_z35bqa5fyTvbFdkHq5ZOrlVC_UqgHp2xnweIdLNHZzZfIbgZMtrczunvk38Gq0c7CJ318c7Xu7Vf4bpz3MyqgnqpcrbN768HZwS53V8QzDKZvWG5tJrbpJnorZ4PoujqRHmEG7yzgHUNGf42uNkw9-CE9JLXaZvVWBN1ZXGyXdNfHZVY6wt52vmFKXd3kq6qdNA_JmKOQ5h0HaRJGt6svOZifni4Xnj4n-gja0-LlBfOuuY4FjerSWyq8NI2VTKpnYlYxlKZ6lh-meb54lcIXb_bcaQO2fEXoAsy8KvTVmqmXvwumgpF5P4B-ynUxf9GCufyG0MVQ8zeFtsxqGobzh5o3saubeLNvaKRZilb_vv4mvAVP5n2hWaQX61QwOwy9-k6JVraqV68u2Gq8gnX-jg9f6QcdVFZXUfVG09kwvP7imzZ4va58qX-YcVneHfCNd8DMcMiGQeY7e7Pfq1kg1t_g1jpe7U2my7LrQoEr27BUfwPQfAh78xjbM6NH2k0Eq1gbJF4-TD6XAOuh1eUxuIM2C2FbwTXfU7WNGOZGtI1uV96OtDTPN69mcfXNq-UXJv8Pyc-vHQ==
```

**Comment by Lothrik** [comment] 2022-08-02 20:08
Given that your damage dropped by 70% this is almost guaranteed to be caused by the new Uber Pinnacle boss preset.

This isn't technically a bug.. though it is somewhat confusing. Change your boss selection to fix your damage.

There is already a PR merged that changes this (so old builds with Sirus selected default to Pinnacle Boss instead of Uber Pinnacle Boss).

**Closed by Lothrik** 2022-08-02 20:08 UTC
Labels: bug

**Comment by Vallek** [comment] 2022-08-02 20:31
Yep, that was Pinnacle boss (in enemy stats in calc for those who maybe will search). Thanks for quick answer!
