### ISSUE TITLE
Flask effect \ Bottled Faith calc bug

### ISSUE THREAD

**Issue by Pct-R** [PathOfBuildingCommunity/PathOfBuilding#2723] opened 2021-05-03 09:10 UTC
What happened?
Flask effect didnt increase a Bottled Faith crit chance  at 1% and 2% , but increase at values 1.01-1.99 %

Pob code:
https://pastebin.com/La4D7CUH

**Comment by ppoelzl** [comment] 2021-05-03 21:41
Duplicate of #1278

**Closed by ppoelzl** 2021-05-03 21:41 UTC
Labels: bug
