### ISSUE TITLE
Trying to load build with version 2.9.0 results in error

### ISSUE THREAD

**Issue by Crazy-KSK** [PathOfBuildingCommunity/PathOfBuilding#3355] opened 2021-10-18 19:15 UTC
just trying to open the build makes POB lag for 30seconds and then show this error
I do have 20gb free memory 
https://i.imgur.com/U6x98sT.png

https://files.catbox.moe/gut2hc.xml build file since I can't load the build to extract the code

**Comment by Wires77** [comment] 2021-10-19 01:01
Duplicate of #3377

**Closed by Wires77** 2021-10-19 01:01 UTC
Labels: duplicate
