### ISSUE TITLE
Mon'tregul's Grasp adds damage to Herald of Agony.

### ISSUE THREAD

**Issue by Malentent** [PathOfBuildingCommunity/PathOfBuilding#5495] opened 2022-12-30 00:58 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour ingame?

When creating a character with the Herald of Agony (HOA).  
Adding the Mon'tregul's Grasp to the build should not increase the HOA's Damage.

### What is the behaviour in Path of Building?

I added Mon'tregul's Grasp to the build. 
It adds the "Raised Zombies deal X% more Physical Damage" to the Herald of Agony. 
I believe this is a bug. Unless the HOA does get the boost for some reason. 

### How to reproduce the issue

1. Create new Character.
2. Add Herald of Agony skill gem.
3. Add Mon'tregul's Grasp to inventory and equip.

### Character build code

```shell
eNrtPWtzo8ayn49-BeWq3MqpyDYMb1_vOSXLj7XX9mol727ufnGNpZFEFoEMyF4l5f9-umdAgAQIPXJPpSpJypGg393T0z0zoNN__5i40gsLQsf33h0oR_KBxLy-P3C80buDzw-Xh9bBv__VOO3QaPxxeDZzXLzzr8Y_TvlnyWUvzH13YOsHUkSDEYu-JKTURyA1pV40Zr53R3_zgyt_8O7g3vfYgfREvYETJd_6Lg3Dezph7w4e2GTq0uBAomGfeYN2eudqRoOBQ70DaUIdr-f3v7PoKvBn03cHwPzFYa93_gDgru86H7sPGdaOl2UNov_jtOPSOQt6EY2kEP68O2iBBeiIndMJ_AVq1J0BKcXWlSOi6QfHxVi9KWODFPrItsxS2E7ALoZD1o-cF9YOnKg9pl4_ZSWX4W0KezdzI2fqOixYD_9-hbQilwI_-BF1zzu9BaxqmdaRbNuaWq61QPKj9bJ8daLxmQv23JQFIl6PPCdim2J2fCf0vSyWZmpHpqzba3HycWJr9pGmQLRUybjKTVds68g2LEshdg0bZlEVlchHloFoVRq2Z64LwzWLWR48_uTJ8fL2rylhK2D041CEd5cOnFm4oEDUMqQ76tG2H0aZ2KsC7bAAEkKUw1iH0GN9H3JIjol9VDFIM4yK0Us53jpDVh9yI2VihE2l2U6Pi15duI0JbydQFwZaPchelKY8ItulBNlzFlIxSgmesx8LMEuvoJcFVPRSztdeJg6tKgFzkLpeLuCLH8Fku942PIdcvO-kmc5QYWpTFMWSFaKR0nQ3nodOn7p39IczmU1gwnig31nKUNNtpTwIR-PIg_RThqxq5V66dAJWhkd03SjPYu5gK7wx9cNSQYlsVQ21jEZGVbHQP0Hoa6-fyeNmFeHPXsBCFrxkqowqFojShbGFxcyTy2rjpGziMVqnHhDMRsyLOc4XSKZ9VKnVLWP98RUUcV0asXrJPJ1qiVZpYATOGphYVWQL7EuMmhjLpiL2kSxrKrHF3yoixWYj5MiowioxG4xiWVVMUurhC48Fo3lv7DA3U6wqWh34RMg2ndZB5S7I4mddYSr1OBbZRq6DumFcfYV-ot78s6lMLzTMZmXVlKsNJuCztiofDAxqZEAYsLpNQSfwf8O2w90MrRVM_Fk6TRpaeaLnSgj4fG6T100roo7ussGsn5vH1NKBcOZC47ekg0EqJHPdIpRytaOI9r-f-4NRbUtxJptj9GbTKeQS9HxdPJwUuyx0MtXQoaqvh_4IcZsdwXLV7FmfQQpdm8GiJljiUhehviY4ny-rYtWArs1h0c3fQVqYwEzAVwPu_OyCQGlgXkJjlm88bcUwzSNDlWVDVSvR6nSCMf3ed8d1pRD_dmiA4T3yvbnUDuiry4IT6YE6rtSbOt8h-EIYvn0geJAsDkAR4Q4kfyhxpFRUostQ5MK0Y-jGIqeXMexSJ2QD6Rs2l-xE6rl0ssrK_CFxuBgsbT9VqFKhtdY0w1IXM3kZK54aJSjeVhn0Jk5mRihYGyijuUoKISXRy0tbdOQd_xXia4xLZWGN3J2BhuI01aA0QALm_T6vTT8HXovBhTeYBZitavNYxihi8-BMwHlheE4jKoWMBv3xLYxFbvXFt0vquk-QnOEqYp0e8xVI_HQ9mfpBxC-2qdsPOc1rbzqLJI-vHYZj__XO8fgU8-T7LqPeu4MomLGYfw4Wvf_ozSZPuIQm_g_uLYCcOGH_8Wk2HOLCI8ZHwBdNLy4vL9oP118uYpQe45ObFM6eQvHx3cEXh73yYDtnEYxBMGPfd106hbHy7mBI3RDoOfCRw_TANv2oghqHgsBPlqWKaaUA5ZQufrAgAi2gNuoHDiuVa3F_jVCCIdZN6OIyarhAWE5ITMltGkairiuxFF-LLaeCa6Ol6uDNClyIL-qWco7vrrFENJ-yEAolZ-j0cXRUu_wBoAVUhV36fRhY_XmFv-PCopwGX3EtIyBuliOLLFiGHd-tsCpftC21qrhbjn7O-rRUd3GzHHnRKvgenzCKqSygKijdx6vBMGhajot1QKlnL1y2ACkn-DEas0AUF6WU7iDzJCCVAydwnmZR-TDOQFTYiq9wlFgI75Wjita9RAe8V5GJcl1riUGzMOWkRKNXmsiqULsV-bRbnUqTBqrE8uJuhf5JE1mieny7QnRezpa6Pq6Nq1IDtE3lqQFvliOLobVKgs-5tSjwYXDOhgwSWOU4WMBUJOBo5p1DrowqDFqTlJjQWi--MxA9207UuJLFxFJLbURL5JdCu21Mkfe0u5p-qdXdi_nj1dmS1J8BWUMIcvb7iqqgHqVFH_ieURe3-Xx3N4Irq9A76elHIfUG57iCVVvR0-OkjD7l1UgIXVAQXbFJeDaHnucS8-3ShiHlJojL1Qjr5TxOEn4DNqQzF69_mlHXiebYOWSu3orzBJ4fTBa7DkAK6ncMIkERi6MQZt6P3bvWrbjZcqOYHnJMlBNWiWXimir8WnyRHyRopYJzpbnojtd3ZwN27cV9YSK9S59QOjwigQvsi0EVuj6uTfmDuZSk_SXaC9b_OAUJY_wr13-iLllQQUDRpmTlIbk78UXRnX8c8t4cOvgBC6DzirCYi49kEOUgx0bJsbkeLNFYZc85PwurXvOaijvpINsfA48Rm-DdO2hkBtC-HV9H4IFjdMPxEoPnxONEXrVgQjN1Qt-feYIFtlu4yFiwKJERusoox-tsHxtNXWezOApbg4GDA4y6PGCL7VRhmTSYyyjxcbFkpCKLXEDv-8qC2hqmtl-jojBq0lJurV8hmbrKCWQp27buVUVcMRLEP_KhLkrd7XWtpFdXaUFAAr35WlNaYu_fu5d-fxbiOvEOSp8zGo0nNPi-saKdgAFZ_0-I3WR_Id37iNf14zDMZA3UKZmxdkp2qUXWcd_QTF-cvuPPQiklFy7lvd5sMvFhJu4yOl2kgtNjnsX_xPnuPYNiM9rnVKds4Gq-YpwsGO9_7uJk4FOOzXrPmVnP5Re1cy4T6-LxrT9pdH-EytQL0S2RaC-2HuOXjOGxT7FcvHEAx9hSjP73TLW5inyDSmSRcAcVC8nUVREPMTJc4pYe_Fl_vJc0Ezch6-pqH5u0LdJMbTN_Yd6IlQ-SjbPGKr3a2X6Buf8gmgUhFCZ8wXP7EFolUle19-xHlImcfWh2zsIpdYLN9Un8NHM9PCzlIPLmlVrMfe-ewpoPl9B2dVYxnbrqIbaE6FiLvk92SPY84pP9VZT_xDh5gMafeZF0h7t-Tak3pqOAMU-Kc8De8kMiRm3H8G6yhTs4JQ7Z0LiCFHaykFUlQf7vIf_3EFlbe_93qu34BMVqnb1z2yQIV9i95tLQqoRpY9QZUy-i4WT_YQgDN3CiXhTwMzRbR2EhmdqpBBfNo4C6EljI_VOKT-Dw4Cf7vduPNRaGLFgiU1dLIYUU-VJ2Z3mfeqZLcenW-h7W9VaI1fbrgoS0oLGSX-KPPRbxhXuxXo8fH2DeTJblOTklXg-HL9mn61AVFdNKGLFgHu8qvzv4w1BsmzQVxSTqW_MPTbUUq6mZhkbeQEZ_gCvwRLNNuWnohmU3iWxbZtMwTEXFK7bZ1CzVIE1DJRb81XUTr5uy3lQ1xVSaKkHymk10rUmAlwGfZYtTsy0Or3F4uC7bnIfaVDRZ5zxks0lsVYcruqwZ8NlUOA_VaCqmRRROBWQiMkoQ3zT1Jp6U5lQBn1_WVBRUVVQgpcrASAcOMpK1lKam2SCDRhS5qeomQXlADLws41_FsOEvkZEKGseQVZScm83UNK0JKoDOsmaSpk50gCNgHLOpGKamc1ogoUlktakpCGMaFpCVZUXm0oKiYG2gB7hNHbRFk6ngEc221SZRbB2gDRugdQ2UAUY6mFLRwUYcX-aKonDoHrxigaHAO0RXgQwAW2AQ2wDCRLMIesEyjKatyWh-WdW4EQ2OCe6yTQL8UH9dV2xBXG2qqqmDdLIFdgaRiGCEZtQIadqqZTRN2wD74Uk-7kUZ4FRVRs6awn2pgWIqaApaoHUJQtjgfRAWvK8qFjhOB6daTQWNpQKOBX9tzQapDA20UmUCDtUtYKHI6GLVgtiD0LMNHcXFEDENBe4qSF4F3vDZNFF1UwV9QQ1NRssiFjhDAWMQE91OLIurqjRBOZAJxAEkYpMDKYIBlnnaFdNMPxlQerzP9Ll7K7LUOIqm4cnx8evr69GURmN_yH44Ljvq-5PjKSDBKD3k-egQyR634J-z0efzb5OrD5-HM8t46c_Hv85a2t3Z5Jvbe5ydP037z9-NH96nT91vytfbsa-dtQb-17OL6Pm9PJf7Xz98nH3v_vYS9Bxt_vL0YX4TfHgOPsxeZpYzGlyefXsxz3-7v5z4Z5--us-fjOvW-5HT742n4eX8sDU9f-5-6VO1E3VM89q3bunztE0uHfvesR9u70eHV7_Nb-7OD9vT8PVi8Nuvrt95-vGsf3nuP5CbD_7w6vp--Fm5uZv9qofT59ez6eWvX_tPN9bo8P757PZjpzs9-zKZnX2zyIN3Mz_8Nep4A4VMAzKf94f37mWXPIcj69X42mkNv02NG9Lufvw6vbi2z8LW5FPvW-vDRevmU3va-nDduhm1n1s3dxffX8FoH-5aN6_toNVuta4_taat9nVrOmo9tz7A99e212qHre-t3qfWh8_t2Rjs4ai3YI93Iqkm3joVTxeH8QQjvvGkh77lWQ_qtkhMA9piIlqGw6yUwullcHw8pXCkDA4HUg0wnh_qiIdJtwYcT8spnFoGx4d4HXqYOFfpwdSVGh2-wCzFJzScxvDDvR8xfg8vJl_4JIdnKeNjolBAYcX8u-9P_o8_BHhk6yrkKfxPbBS_ZzS6o9NFA4igt4u9P77PHNHo3IFpMOCHEZIJGgF_ReuaR5AodYX_J5xwyguAeK7N7ifMQiYedfzK6BQqZryc2ZlGUOmFBg7FqZ8cZHeou3A5mp9In--vP32-aNxCkmFz9j9AJvzfUPriYNZptINZSKFvlPguZ0NsPZ9IhGhG_OWMhsmDoJBtTiT5SIf83PgimJ5InYBJ6pF-JKeXoNsDzaOGOHXKBtLiDllmGG-5wx25EXvvROoeLv5tcMt22fOJpNuN68nUdfoOwiTgQP2Kmw7EiEsnuPQ0lziipOhSx0HpG38E1BuxExD_7Wciy4cwnf7zJ2ydAkbxfLnQNgv2y8-GfAizwT-xYpyIgwR8L60hH2k_Yd-dbNNIYkE0XruV-KE_IElDCY-oNf6IPXRC3n5RDFk6h5aWoXMkUGzmBPzsf-PCY5N5dosmllya-zMe3nf-oIvCSVxEfG5LTxweD4BSCLIWQl0Loa2FSI6s83I2jU8hQC4mu63uReMeBh0CNG7xVLfUdmdYP0o37JW5ECd0CJ48kXDsNCDIhs6PEynjndZwCLGAxS0MZSyEu8xjr9RdwOK7Ghq92XAtYrw7dgb5ZAHPkXMSSbwuPpHoAv1xwnvExwH3-hL0PeQqqY0l-YmkkDTO5UxEG3I2otXGH32h9BuU7SFgSR0xrQvWYXqfSAABAZa_z8dALKsYSjmKAN-bUHz0II81CvjQFA1vKA0YxLMiZ4eGCOuGUsRVckIpsXwpQLL_yE38Vw9ltSqU79jAgSyxayx3ZgHjR1Aea4G3oam8ZZhWH_MRvH04P76OIQc9Qu55HNMX9kgfx_xoTEWYa8VRrmtVUa6VBnlpNNFckO81xiWuNWZcPpgob2XFfEIlcTaoPMrRC4fCDeVA6Flx8ugvPxC0qoFwNaZh5M6lizmrOQpk8631NA9D4SRuvvxDnpyMVpzfi5K9kqPHZ-iWN8CnQPiTHpycUhKzcr7WSAIHh4Jk5MoGMfNzihVgyHUJSAShgcUFIRJNV2oWVUWcd_-_4qTIx3phLdmmLp04EaZ0UUeGDTHs8nkPxsJoBiXjOXOdANJi3qZ8-N-C36Q7XNQDkYJaqhaJaRSEYm4fqJHfBmrEh98hH8lK8mW10lUMTW1wJjw0TiRLKatYr7LRo-c1vcLsE8YVKZGloo0bkSEaGslGTSyY1KX4RFXjF1X_CcNl8USrJI7g46pmg-hZzOSJ0jjmFDN7Ew-zS9QbSPwEvZQ8lv6XT0hmVUK6gbwstSYzF6aMtROyWOZNtni545R84lmfhVa_1CgCSWY6c8E70CPBxDIGjcIJNBIRHYUnNHnk5i3XrBD5UBW9yqK_aPyi8HjhgQfhhkNUzETYM_1XE4tV5aszzAribFjakpqktCO1LctuiEd5JPEsDx-E2Yd7CpBMQqojQYnj4DoeOfGuFX8e4c8KjWxWOTvk_2aCxVSzwaLEASEqtqao394Wwucmmp8V_ZDkO954eimIkfgo0ppQUTYMlKIwsIvnFyfoQxkG0tz7kN7ckUMbLQgGmBgjqYupMJeUSTb3kryFFDWrMh5UTfTuzfHtfiF_uDxP_BdFRZOgJdLH28R8Fc_XtsTPQS1MSAhPzOJiJinnHpbnjggl2ypwwtKpdKggoDTOFai4koCkWfDCn0KSLiB8-g7z-jsn7j2m5QoIYy2EWRwni_WtRCG5MGjufE8sbkUBG83cZKELJt9w2vjiOzDv9dkUbubXrpQjkl27wkvkSF29ZCxfUo8Uu96ql55nXz7Ws9OCtTQtJGtISpO8Kbm5_sLlU31aMC5g1abW1N_ycbQCrcPtAN-fAjeTVS7xzDqGY-7tC2FGjLf8HVHz_qLL8spqWbr81VSLsYhchaY3tVJmBWjpnFiI9DPRcZ78KRnh6WgNl2qoHLrUc35nOS80wbpvuGiHtD9AphR9YsxNhB8e6Ailix9TF_rkJk8AWLYR-ae4-nMCLjUuFWZzU6r7lhz02hy4Jm_lVhOzhyVWQrPmWW5TFhS1-tQmPkhUSkhfSwioHCpEL6P0Vypo95E5KyCstRDKeoMo6y2iVNR8ilJV9PGXyAwkKLlecLaNyz5V1krKPqWkeFutwapWhJW3pLobiFaeN0zapqXa6naFKVeUapSzyob3z4qxXJ-Jt9Eki6_lqw77ifIlh-HjjuWbT_knIV0_4ptxnafP3VvcPRMvNxFYktJ7pVOJL8XQZNFO0tPtOzmRcB2dZRpkCxopirIWh68U7EPwIgNsIvwZc6Nd8C9dGn6X1M0lJ0WSq3tw3RZWJH8GDW0Puhh7kMPYk2-UTaKqKLw3ca5o0HcSoSCwjZ0l2GRoiNkmkxWU7Xiqe0oLys7aa3sIR2UPw0LbMA42dtpODItifx-WK4w9fut6AASWj9gIYmI7K3PqJmFWK6_rNVnGh4SyLDPnhpZZFhCIj91kCWRO4tSUudDyu06G6kauX7xiYZewL47B3YevvjMFo2Y8xKetsu7MHMCq6c7kAd6Eo1UvZpWaMuJR0ryI4krNiI0PqGXxM2fW6hAQB_VyBNKzezVtVBwq-n5iluya9Yw95Hp1D5lTrRkS8ZnInEvSY5J1s1BBEtH2VIPtmsyU_QSGunGDoG2Msauq-2qmtom_PXnb2HX87cnd-4rerYogJLRNGtkSb1c_dPkabIpgV-UbcWY6m27SU9Q7TQB1S8X49HSu7EoPVNcuu0ojZx8TwJZBnOm7trOhuqnXlSKvbxFu2n5Grb5zxblx_knhjV3yxCaSi1MXKUJuny957IyfgOfvX_a9oTNaeVUyw-PR1-GZH4bpi5I7jufRvlv0Eub-LIz8yZ0_yIAXgC3_vFwKzH_rbRVB_O7cWjAuLu4ZdfDXPjLw4oRokcC-J46A8YPgnz0v_lWRdW-bFtv-YTtBT98atQ5znH3Z2RcnAC95fXzVC75yM3lttSYXGWE2HJ7RMOKviHnvT2swmyx-VU68BYQNOCN-djTzkmy9AHWQvB9q8aIo8fTyeqYLm4oFc3y_Ee4fuPMNULk7rr3ImTgD8Xq8dajLvxu4NliG2Zfj5N6UU6Vox6V9NvZdPD2WDTrxk4KJRc3s7-8UwecPWaaIRCVrMHO_kJCgqWuQFofXtuCX-SHDBEuvRsEtzw6-AXMD-GWN9HViwZUtlIErm0q2ncmWsdQ6bl1G0q0a-mxqufh9hQm4pdUMnU3stvJ7IUvCnR4nE87p8fJPlP4HIeX5Ew==
```

### Screenshots

None

**Comment by QuickStick123** [comment] 2022-12-30 00:59
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5382 and fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5394

**Closed by QuickStick123** 2022-12-30 00:59 UTC
Labels: duplicate, bug:behaviour
