### ISSUE TITLE
Ngamahu, Flame's Advance's Strength effect incorrectly applied to Unique Jewels

### ISSUE THREAD

**Issue by haruka-kb** [PathOfBuildingCommunity/PathOfBuilding#7209] opened 2024-01-07 14:22 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour in-game?

Ascendancy passive of Chieftain, "Ngamahu, Flame's Advance" cause Non-Unique Jewels to grant +3 Strength for each small or notable passive in large radius.

### What is the behaviour in Path of Building?

Ascendancy passive of Chieftain, "Ngamahu, Flame's Advance" also cause Unique Jewels to grant +3 Strength for each small or notable passive in large radius.
This resulted in huge difference of total Strength in game and in PoB.

### How to reproduce the issue

1. Allocate "Ngamahu, Flame's Advance"
2. Allocate any Jewel socket and socket any Unique Jewel
3. Small and notable passive in radius have +3 to Strength

### Character build code

```shell
eNrtfVtz20ay8HP4K1CqynmxJGOumMln7ynd7axlK5Ivyb6kBsBARAwCMgBalrf2v389A4AEKIAXUUk2OY6rFJLo7pnpe88Nz_73yyRxPuu8iLP0-Q7ad3ccnQZZGKfXz3fevT3dEzv_-4_RswtVjt9Eh9M4MU_-Mfrumf3sJPqzTp7vSLLjqCLQaXiUqKJ4rSb6-c7RONZRqeJ0xwnmv56rXE1DncOPY_gYlDp_ZYgcTMvsPAsBIlJJoXecUuXXunzfdI38Cl3zVRrG5fOd11kKEDcqLcc6S8_Vb1l-loX3fo_Tzu-fY31bNfHy_OLN5dsdZwK9u8qCj7o8y7PpzfMdtgNj--7ZRaLudH5VqtIp4M_znQNgkbrWx2oCf4GSSqZABnHJPbHPXMEZo3jn6VLkw2lelA-jcHWjdThHQvuMUj4EfJHrkyjSQRl_1kd5XB6NVRrMm_TcfQ-7g009DON8mpTxTRIbudZYdF-iIZQX99pArjsE_DYrVXJ8cTWHlUwI6BRDyMWELsfLyhneYAsf4nJ8mACLH9CKwX15ncalfiDyRRYXWbrF-Nqog0M8miYJWO5asJe60PlnVcbdbg3TziZ-nD6Iewe5Vm-iSl0vVRhPi3Nd5rqY0SH7g3p-rlJ1lBVryNdAXugc_FO5EcKVDjJwaZu2sSHmqzjSHUjkLYXdaCQ1Qk9_kOR4nwm8RlMbDujkal24jQk_rEOX4HLXg7zKpsmakOXc1SFC2bAxfeqA8kGKx_rLDAwTvIRgBxINQr5MW9JmaAnBDiTmwz38nBmvsJo71jedvLiYxxAJPdgnHHlCLgld47siDlRyrr7Ek-kEwsRb9VGnrciHGR1W2OtxmYKTG8KmBNPBHp_GuX4Q4lGWhA9DHKusGMLEQiK5zDTnHpK5fEneEPxgoF-mwVwUdBndd2lu3X8r3yCIo2Uol2CKJsXxE702zryZ2qRnmNLdR0x6mCNBuGDLG77Wad363bxp7O2LZWivtA7GZ5D6XapSr-fZ58zD7lJmG-A2s8Uyqj283kNkPYxFtu2hfeGy2X9Lo2Y_37C7j5dhbci2k1Tn13dXUAQk8-FJsQ5407UjdbMGpuV7G73Nf3e99vr4sRbqhkz5oPJwvXi1YZ-qZNDgtJwl3_egvliK8lqXlx0sTNA-Ju6gjwCEmem1ghBUjsuRZnq3lr4Bwj0BrSGYz6pohydJ5HLXWCN0vOOwxWooEQAj1Au1CyPDpVj2mynEkg3xDvJJNm0nDRSxpQOpEDrjwKuCbFWKXupwGnSCOh8U42ECtfLiIJZxOEn6UAbld1CWKvh4nIXXel0U28hGGLPa2KJeTW9uwKUaLVisevGyVAFqpLiVJgq-GvgNWHLbo3G2LKVYu4E58GIDdHWqtHYrCxiLTWGyNMtZaMZja0AvNrFaoOfgKycQE-1syXnWSmD23eG5lVOojNcqcy3gmuX2RXYLvR-bKaxiM2hICOf9HuxKrtOvd2vT74Cv1cBJGk5zYw5rt7GIsVYzB1ZuEIj05FU8iVtFSI3xNp6A1y2KY1UqJ6zLj_cqj1VaIgO2-CO2PxZ2Tu80TkqdH4MumX6ZvjuFVnkwfgU_naok8cHbPN9p_wrfTMPPntrpTfPpba61oxqHERjytmfmSzWv-TK0bU5UAa3dVdpYPN_5NzhtLHY5cqX3n91_Y4EF3WWEcfiCMBF4l1BMMXxjUBYx-EYEgW8EHhFAY4TCN06py3cpJMPuf3acEjrTmhEFq3PSLNSFmT8TWO5yIj2AxpzJXYSo9Ha5-bJLsCvRLpLCdMGTEtqWLrRCoJ7y4LPgaNegil3mIsBiYC94F0M-iXarYWBJGMBThsgu4xQ-Eg-JXSookKGEe-4ujEmgXcwYASRII6T568KQEQBi7iEM_UOS7lYjZC4DJCYolUARkpVdLJhHoSWJ4C_8zKF_HNpm0EFvFzjA3V0qoYLcrTgG1CX84iHPjBADHeRy6Del3DXUiGndFRzvAiuIwfU8-AzkgQsUEWjXxULsEg9GvcsZgY-EUQZkGHQT-iTFLsKeZLuMUcEMGeiUZAiGyZnhn0uEu0u4IYgJMAIbbI64ZwYADXNgNrTCgeNSAh0jYxg6SAB4B01xEBMXlo_CchCIGS4Cd6kL_HMpjAa5ZLfSGEw9-IUJYVhMsPnFqhWVFBrmzCUUxoeNNBl8ATIYOMeJB31FQsIoietBByqtApYBpjT8BKYaLWPwmXKJTNMU9Am7AqQG1QRoFQEcdxeB2KENRl3gOTPcwxiB1Djhpg3ugSwYh9Y7CwLGRIixMzNno_K7g8VHxqS-e_bu8pX98N24LG-KH54-vb293b9R5TiL9BdIovaDbPL0BpDAGPeKj3GS7BmLeHoA_x1en1z4Vzev93Q8ye6-3uzdJvKDiwuaxb_4JPvXxPvgfzj_6f2Xi3_9dPnrp4Pg0-TMvfzl1bWn5I_804ef3yW_TX99_fns1L-IJuNfZPnp5IX48E92-sJ_fbanw9c3UfFieu5OX5_9dn6g3A9SnaeE5b-x6adCTd8kr478k_ylSz6fBD_-KM9--XR8dJXE3i39sidj-ebmp-RHrP3w0-2bi8PLLyc_vvv1R7T35iz79ezwKHj16Wv66ezV2U-vVCx_OTiefjw8O_56eC3yk-D25-nPF_Lrj9Po_CT59frm1cUvnz5fX0eg5ul7fUC85Pr4-vZr_s-r_Oe78qv3lbw_Pcc_3539cvzh6uII_4hPld57GR6O5e1vBwf-9FP06UCc8pMX9F8X7oe909vfDvXpmy_T6NXlxz32y3MrjKeNNJ5VKyRFJZr6m_U71vO5jOAdJwYXbr7iOrTfBwT9EWQO2MwJ3we03qRF0R0CBJ8Czc0pDgKCG5MtiogPNs0BsgXoDQ6GgCtr9XEQEINz4a0-4kFAQb32YAb5SKUrWoMhaLiPUrQG06RoPSL0cHvUWAw2TRFvAw6K0PrwFuDgqMHBt5UCD0tGQHRqSWawjxAG2oIZ5I6JTS16cpA5Juy0CDaAz562zeKZyVbzGEJxlbc8NemBTSRM_mA-XBl3VTjFOLs9SMqfpiqJy7szPSlmC56hjtQ0KeG3V9Wqaprlk9lc6E6ThBg6V7qsk58GpSZYJTlZbn4qDu8gV32-U-ZTvfDjqSmqFxZuTM9MNVTBvb27MWnFwatXdbpTN-vEYZMC1T86OjUzf2HTUJwGyRR4l9aJ9Wx8RZKZGRCtbrLUwdXi68F8TEcqCYo6k-o8sL8lyjcs2amFBD1cbPdzlQAaIZ1nkPilV2Oo73acTxVnzO_HFbt2nOtKmOe6VCFklk9fgnSLp4Y9T22T8KlDo2rqLMl8laCmwVRN6pSwgnVq4HpNHKEuHp4x4lNbVqa5e30OsmlazrLgleM9gtTzTVrV83YauZbj5oOfyf8eyZVMMBjO7Rj4UGE5NVrNDrwRN-qO9PRigTXPKoH9d-vjYZJl4aVd93-gNrYorBCDhXQq0Ib17ka8b7X12MyG9j-bYvJ3ZvVBGl6pNNyO2zMiazEcIJ0KvGY635znBv-qrCahNvQAB4BUlLlKPphKNtbRg8feQ2kFA2YYzhzlYZpXUcpyOyFwlajJ72bu6HfVQajQdf7x4erX4K_SvAbugXbeoG-oa1ZXz9V1HGwfZua0VqtZnmfXlXE8bLx1q-0mNxz5Ra6DuFpheKBoWxRWDLcF-UBjCoJproI78GNmh1ZxAN8e354Os_DOaZYrfj-TMuHoPQhPf4Hk-ecHs39OpmbUhcrLe7lJjzQMolNhOlnk1KYTp9drSGfW0JwfM4HhtsQWB7mhdr5Mg1yrQltxzxd4tjfSAcIrmTbDcxpEp8FcX6VxjwkPdmhDjr3PYvAEaXwzTexut4tkWmzPrj6qq73brUlvgVUG22mjz5hFH8Sr_t5szCiDbBp5DPY0tFYypQ26nca0KW3q9KcJ1PZx8QiGNCO12vvPIbcbeItQ77gt_Hmc2hWFgy9xcQK09FWWhLHOX2jI6sI3kV3821nH9bT3cz6ONQ2SXt-k5n7I0DD-u6Iy4y3bzgvd79njR9ms_F3LpmNd6nwSp7XHeWB4XaCyQj4L0A_LchaIbGjb88X5Kjt64LgXyaw0bghbd0YPDeKDLXyx1U1LxjCMDdNU8vPF9mbapraSASdpYjxKa3aIPCST77a54fDPIDd--HxMjb1inDXUwzS7Rn5sV_JCJxNd_q7lryrLRJuErDgyW9ceWgUvkFlVDM_A_wcq_OL_FY7F2sC2SLs2Xmh8Q-UyO-RKdbO9WdWEVo5-BrdVaTyjsun8c52Gf9DqY6qL4sEyv09oVYwvCrMcnDYyP1cPnw9paBUVkb-e4X0Yx7k55HOYqFA_XAiLZFaIoAF3GviHcX-x1WH21x-vdGkX2KqFNfPRjqVeJjOfm1WyKeTududBNflnf666YskZULusRep9CJfKxOcfnMuDy5PREXApSO6KiXMIifHoR32rE2C_c5rFycii2tW6HxzhjepFuB8c4o7q1cEfnA978G9kgS71px8cLkYvJzdJHMTmKR_9O8hVVOrwPzW2E2a6cNKsNAplE0yn2bFZl89zFPT9DAiSW7t70rG735wbnTvie6emOaJDgCPC2o8qUTnN3JFzCXlVej2CSFs42Ckzh9qcpVnigR8qYoVzG5djpxzHhVNPsZoeINe5KnOdXpfjileFNougUZY7k2kwdiZZbol81mmY5cXoTaqdFyoNoSdXt1kezjn6hLjfjxb4AHzGe9wdnSR221_rd4z2CHVHs2kH6ET8UTvVDs8fHG-fye9HTc9NRyv9AMR9JEf1AC5VamihfepM7KG0mg3I9BjIO7M9kY1coI-DbBbtR_0dGz0xUEC8lsIi1PyQ5WiQ6xdQ8ZS5KrWD-PeO3U7pVEmibWGmOazTVbsV9p52mW3tDmgOJKqvs3SvIlZLXhWO_gINOe1fraGem8Uj4JyTm79g5PtmW0PYMuVBCLwSgqyEoCsh2EoItLoZtLodtEZDfDWItxpErAaRq5nfbO20MWHBM_JvnvGbZ_zmGb95xm-eccEzej2e8cIY6iRL4yn4RihljB1eQ5L-cNcIz1qukf0xrpEP2iz-o1yjpYGowcECffMrf1e_straVxv7altfberIXQ2ymquzI_l9DkP0OIxDOx_qHKr08fOoP8hZiD8_j7I0hE1CEKVdO_k_7yjO4zyHnDL85jH-ah4DLRRf716__Ondyeh9FgeQeb8yp-2co2RqTp851nmM3qXxp6l2Xh6Dn0Au1i5B3He1xEhSpYSSmGqPC4aEdpmLfYkiirTmroooc7XCLla-5C5TbtcB0bZjcSuDI1WjTr1v_qI6nuNU03J1AHeuJgq0uPPMuR3HUOhcAytK643Gxg8cZXk-vSkfTU97Ger1MvTtWDsHUGyl0DjY96QAm73Hz0hGyHVDN8BcYl9HnvI51aFHtUIRxxgTHTKmfC8iWgWRi1joax6FRIUUnvIuP9nIHnsEMy8zqKe63EVdR1CtLxuLX8JvB4o1c-WaSZFmrHTsbrcKrdiQw738Wwhh5wdnL49GF-D8Attum3emvzMH3eKj62qtiAiIZDLgXqT9gDFPMC0Z9zwR-T5xEY0QC0QgdYT9iEolAiSFxAHCXoePHm9zDo1wm2-t26wMDwFIp4Fdfa1V9N-RuYZuCr7xP09Q5eWH3Xvl1lvVuL0VoHbxxegJ4gZ_NuLHVufVbrdXYLJX4d-lqYJxwzBfpgVE4aAcvY_zOIxVj-IrzAgHnUZhGGIltAhYgJGSiHqUMOJFbshcBa7D1xpHCPyL60VYSuUGknih6iq-20pXwCiqq79-qNzEsE3gOT-datt1oFKTx_gaBB4BmHkCcr7LpiMM1pObyw0ssMlYjmGsVg1qiIMkyQJlUHrcUwEUnapflY-auaizymMZDD9LpwXkUqBM71K1Jrl1leIRI22fUkBV22PFs0sbmxW1d3kRpzYNyidmnOXYfpncACM7gUZG4PSYT30eUAquUHq-50PowcxzJQ4DxDGNmCK-plRwRDyNOAo5wFOIRmhRPzqusJOhzYyrMr0XAOOMFTAake_NpZKQTBkbPM3yMo7uHuzlMNoi7Lo-CrjkwqNCaxZ4EBVIAP8oIzIEU9IhV8TzPB_hwGeYeoE5fu1xzInLAhn8HcMuxlsoXA3U5jEVmPAIURlhj3iShMj1vCiiAVGRJJEP3ohIAe6HY9cjOGKBopFPmcc87clwIRSTdTTuCbbhYVIdyasKlVYK_zvyjvTzDrRw7ZBLWEhcQXDAqQAjVWCsPBIh0RSMVQiOlUaCMwSJoQSTZNoNAlcjRhETPg5xN-R63ZBb1x6zGge07_vWdE2LSYshkg1WmKCpiXbGmb1z1lFOdRfQf0lMxbTXPYDX8eMw1KlzmqiJHk4khaCcchmFSkHcJApJqQOqIxlIpFHoMV8FVGHB_FAyFCIIslgFIBrpM8kZXpwZ6AZNCKxTUM7CsWfsnebS3QU_UgcssDlIZdLYrNU7cWRiY-VQjelNVBkYF-FMsjCOTAYEo2mPUhfjR8gpMRvIyVXpfLAe6wPUtfYM4DBPmVBKC4ZJKATWvs8V9QlotC8loyGGNARhX9GQwF94FEKkEtKVJABhmKsJuzzlrRyFecsy9SeItSNPc6dQt3ZHuA1TpyuOuQFWQ5piV35wfUNCYXgMcW1kDlTlsW4yEGbP9dl5D-bYS2M64jIXpYDMIHvDFeTIThMgPGhhtlF31qo9vWnI_dMECgU0wL8BSM3ik1RP7v6L5g969YhvX5tgDWkKYjhEJnNFPigSFMM6ingQRtgVoDkeZDihp1VotI1iITSX8DVwZaDlktrE_UtVG70M9rZnsOdJCtxzoViOfIjFGMoISH8igX1BBfEgHIFJBmHAGYXIjfwgYq6GUB6FnNCALYncUPzRed4_r5mPprlN1KvM_-9f8mGxMjxVjttXSdmTv4pAYajtfEoEVpC_MwhGIaQBmEL2Lj3ki5BDnIoE1OmhS6mrof7TirsohEil7nnSPys62Ri8fXSSj5u6Qv6vQsQZCXw_MFUS_Ak9hVDIAu5pX7hQS8mIeopozBX3XUhwGYEMVgaERPSvlLoSt1cTX2mIVFCbmEszRs01X_cVMfQ8xjg45JAprEEHo4D7NAx5GISQOiEI6opjHQQK6skoEBhDZFcMKkzqBkKqxUKqmWmw9VuXb0fZZFIZeAKOXefFOL5xzPWbDnIJQ86tyvM4ywtnCkA5BMePsSrVqK6ubIGfV_MFJmweZSmMwUR2_84qwj9VPo1HL2JzwDkO_lTnQPpL23N9rZIMeBCrAL6EZvl6sMLVnGuNmfRdjKBYwFD9axkyoiUPIzeKBHhqGYArh6pXBySEEp95hHhRgEF0-F6F21q-cnvKXdpT4Q7NtFTJ0uu6tEVOBdqtguPCOTUZkJHM6TS_GwarL_cA_9_eZDwMDxpdgFuKA0j8jGX98fHgMVZeetUG96rNFSj0pBjn2TRcMn_IXBepSLgulJKEuhDhUWCMlSsWup425Sh3cegJ8HYClAl-DHAU-tJVgRKSLk6c30_Awbv1FpzndWgobJifZeAHn81JS18b6KuxmUUJHXVzk9yZh0ar5punDuLEfCr-kASL9BeWH0yk03mjgyd3ejTXtHvc9gMM4YWFERgh95SPjSlGWHPPXJQXeS6UO-a6N6g7VRiyKPC1j7iSDPgfMMSWV5cd3nd2iTThpbq8t6nYe0HMYYP-J-aq4NETr10u2etzm9rFzvhVkwPKJniVk7UHZkbItauiCwvaTpRnkwqxNDWkWSRtLzPfp9Y9pAUaRleWeIN9-nstufYqLetLkE5VYM7c2hV-58pesmk-ge7O6wPjgFtmm4WdSRKIvIIH4DQgxgRE0sCjTOAIMUW5D76DmukTFbpYyAgpraIQe17ImWLci7xgeNFhMchQ3hZvj2_oLiodZVkSZrep09zQbfYx6NEVUCz_mDXMXidxkWfXOjWub3QwgQTrrihNDlx87FRfkKR7NPR9z0fIVVQgrAIKfI0kpPK-q32sgHtREGDpA889hP2AQI4vI08GPBjck4LFIIPRfOvCu8JO7YEN1jfFQrWmgrETTZNkZIqxpnhrHpvpjmmxuIWjWcwZfTCkwLKdECwW5KWt-e06Zo8a6JdxM06SgalaF9BsK7FOIDObUIoqx6OzWZA4hYxHhX9qqO2dKj9IIAJMIKw1QQA4n5dfKwk3tnQJpYaf3XZCL3chF3YjzwPBQzFN_EgoiMeeWZDgIFktOIQBHCAvhEwacx5FIeHUh9-4dLvzGULMBd4xKNpdqZvJ2-uIrZJOdyOLWYaYSbuWYlW5242GjT7MJN7dfVhTpNCMmh0IbQXveSawSHxLAT_iHpVel9q75d6UIKnZKGbnwc3wTI7btu5QaEJE4GIoWkSIEKcgZMWYoD7k7BGNBKMcynsUQDlPdcQkV0IjxYWprvBiadmSMOtatNdfZ_LudEi1EmV_w6gdcztPsGOuMW-ePDFzOGtttoLEr04PzFU5zWayJ4R8Xyd7A3us6k1Taarta7GaysHOK-x5Bte-HcGmIo55IdC3bVP3tk31Ke1C7np58gr81qUOfXOqz6gt5IVQMcepyY_e2hnsOkes7hD6waEQRarPh6BY9VtOIK0Cb7MPuWxb1bkwmatmnvQ5VP46DCUTkOhqRcwyq5kv8c3NyJDxEqgyEPaI63IznUKlhoy3O0_LOoFstrnycu_SOWvvxGZdP_fEblq0z-10p8VrbzYwZytNnrteUto2A9E9m2KZMnrCUHsex2bRuONi36oplL8zb_mEfd-qeuz7GEbdnUV2leFuKKeZrUFY44jTKDYvu6uWH_6ixe2fZx-9afKBryG-2XO888geBx-L2NzdMg_vL9PqRrDOWkXAfB-0GVHFIsmJWfzGzAsCKJkJQRRLjAXyoiA0M2I6QjxAWivkShxgJoLFsnpuA-6g63-s4E7ousGdsdVbdDcJ7vjPrpf6ztOdTG7uYISpc6FuR8e5us7SAkapnTNj0Al4o5mTRB4ZdJIehqhdB8QKsv4yANre48VMkih8DzNIDRgJWKQp96hGzDdTNFIj4iM_FEHoCRSB2nLQK-oyD7wvoXJYmWTHoZp_be3yFlwqX72aalzeHOYlDGkSh2ZvtVmkNN7KLG3SxfXUzrrP6oIefCe5n8zY9ADyjv5t6nVaQ-qEp-XP20DIG9yOPrMeSjr1TnuKwb51ymQ637zuOl7XW9PrHsdqAurSLaiOIRa2jSQgggsXcmfPo4h6PueSR5JJHEL-YTbPsMALfYyxp12NIdEO4CefhoEfmK1dbHHie2YkiP_-Htdb1-MOK-hfys_2Hbb5kOm-E8vtxJJhqJEhbkINzLAWrqd8V1MZUTekzIcIGmmlESWeyz0EzpAJZtwgRn4Epfa9GmruB3nXD54Nntohf8ypnSeYrVlptV3n-mdh7IkcUjlM9LgncrY-Z8Px4Dmbb2518zMyfeYnBw9avMyrhXpzerwYHeXTwiy5OheJKTlmaQ6ScjDPQUJ2khfEQzOvwUUkNVSFkAEHDCyVMWm2rXu-ICIMfUiPERI-EgFWDDHp-0qFBIWLG-pY_1G7w72zKn3ZO2zvDpNt06XrmO4xuBAzJdVy3dWO3CeonXFYe8Wt2wr4_Zxg9Es2tQWkw1pb3k_sEbB2oblgR2bnyr3KsLHDGs_uNGudsFuE7qx-xGanRjINPoJbAcl1EifZV8qiVnebd7fVHqBBnEXmqolDs9--maBt9jB30iS7N2fxOoR7JwX_dmXrH3vWrXdBwu0radR1Yhx29rGaKzBrqZMplDKd6WkKdqpEqGkYEmmXGoQHFup6WGkcgXVqbc4OUI5RxAlHEIBDzbhkrtSC8XtrlQMhldrVhZ4pS0TWOKBa3ZFaz4J06Cyo7jq3eTyhbrPKDAaXx_60NPbIcc_UqS0k7k0dtWqJJ5j3z3ai7tbqzt2nIyTvPVzMIv6Sk6R_y5OjvQbXvwR4qY3CK-cg8TXE2MaBflC5eZHaqL7Z17E3ys4CLRjVYJwFq8Ojzno-5LFk1H49730kJkgnOFMwWIGpj1zOhM8FD6gUmkZuQAPX9yVF5r1NinPqSZeZIO252I2wF_jcxZFY3E_YnqbqZNSHnZyayoUjlUN741y7DNFMsTZbQhcNqlspLdj9UXUULdRgEenCmeyWKQu3kwa3D7jb3LwVpf7-2wZQ7zrnsfL9ZL7V5WphGtQU5W9ys1-0pWBSc0IhRgQB1wSbvat-CAW-YNSNQNMEYhTquCiC_BAUzfeIlNSczNJSAZYWg1V5exqUit-lKEfrFuUzivZ92NrWOGS-ym30p5rw-kvV6Ij0OrI3eXwdm6Xcqzid72ZYXO7Egd0VCqm9C6L0PbOlSWoPYekFga9w5HOzcdxlCLvUY9INCWQbrk88Br7IVffOY8-Tetxd7nyCBxYVDzp7xWqzPspSUNpqy1S37n2tVe7fNfOUlZLfI2qSaffPPTPcu5R3DiPwzcnb0QutPt85hzopu8e6wbH7ivtmm26koiD0sBbE9TUC6XBEmXkvaqRDl4hAgvNXIDZCQ0ZCIrz7k2Mt26ML4qDdZOkJsxnJsf5S6txObZgpLHMOdGGn8xOMKjmamdn2NkF7SP5d9ZaAytsUrfPFZtsKdCcqJ5DoONTpB4cMEaiVyV2zlXCs48Z11W8GNm2bMwg9BGYg82ZzPYEw8xepU5YZOespD65uYvjmnE1VbjaNmmtwvn6Fz1CqZrfpfBEDMzq8iCGF5y3mJwwvzU9Q92A7lph4QvgSaoqAuwHShISMYYWokkwiEYQhBq1GlJBABJwFAYoiBIgE-ZFZIE0y6LQZ6_DM32Ke0llU9hZme9s32WDRWRSGYj-v14whOJSLamzWkE1dPY6vxxAO7GkwM28Hnsm-Wruxk7ndILzmZB7u1PCVIO2ypL12N8qmafiw3ZcjtMbq3mIJb4-2LRRpjjZXC9cGls9hZ3HziefeWzz_Nte39VyfeS_o8CXL3VeGJmYWDHAu_HeXr8zL15s3q7LqUunnO5UrZM0LT-sbp5-uwhcN_uwVb0_bry9-GQL84ltdK4RqL2rrRa8N7SUE6jfctgm0Xnq7BoH6LcdtAq0XHy8SGBz1jER1vbhz4N8VhZpdC4C2poC3pkC2pkC3psC2psA3oNB6Kdo2AllCBj8OGfI4ZOjjkGGPQ2YTSVUvJN1GSP0U8NYUyNYU6NYU2NYUNrOarCy2s5ceAnhbAmRbAnRbAmxbAhtJASq6rYTQg4-3xCdb4q8hAdTNPtCm2Qfu4uMB_J5EoHoRfTsPmL-afu00YJ6LmPFvwK4mWXKubtXN5nh4TTy0wB-6KX-9Lj7ZFH-pfmxrH-whjNuiD0M0HqMf9BFokEeggR-BBnqoQj-KcPoIscciRB-LEHksQvixCKGHuK_tBYYeQVboEcSEHkFC6BGEgx5FLo9kTeixrAk9ljWhx7Im9FBrIg0hsyayjnQQ6mSJqxF4N7lfjSB7yrPVWHTRLawxFNat1tfAmPG92oHyWIJah-9dSXVO9VZvMfvu2dtchbo6Iv1Bm-PQxVP7djM7uWo-vc21fh_rW6ewQFdlbpr4mmWTV_X71nacYpzdXpWqPI6jSOd2f1nzvjYD-PPznT2B9hkSFFPhMixl9eAXeIBcd99zBUOIUldUBvHMvpyumuZLb6ZlPQr7zrZf0-nE1zmMzP5_fpq1DTmJi-BXfxpF55DsQv9Ksyr5fOfk9PTk6O3L9yc1ypUO7FGpYuoX1cfnO2asdsPJsS5VnNg3wiWJuinMq-9aE4v1u-AS8z7fYWoW6kVczl8U3kdrDjBM6eSLzs1cc3MsaojW7PmKTlUNmvNW5hKcIWrH2bLRVRsIjlRRmhNbg5wy2xSWUDET74PDMQ-X4L6c3KhksOX66QpOlHc3urjRQRzFgdHi5SJ_C9AV1BK-1MsDS-RdrS4soWGvDh4iUD0cRr7I4qJ6LXEfdv10CVevzVG7Qa5WT4fRj3WgBsdePRxGtkdMzCJLlgKbhqjMoJZQep2lVsnBaJqLVIbInSR6BjJM8I25MrFeKh2idA6epwFZajj15rshOi2IJbyKo0Ep2WfDqGbv3OAYzLMlnqi1wjnI0DbMMClwVuESR7YMtVp6HORf9XiZCKokYYj9rRSinwnVsvDg-OvHS4zE-l974Yf1BEPmsgC2zGFAYrA9meMsvH6E3tgd2s3htiWMWp9itdVhiE79dBi93vDQQ6V-i-46RIxRbUfB2NZ2FC4XE4k57uXyFML6r-YAwDIHNoNZIt9ymjabxrYkZbvVbwjzoW1Eq3LlvSPdmGKloPYC4OU6XIGsIASx6MWSbGc9SlV8iT_rF1ol5fgiy5LtCJ5X-xKgZ48xTijxVBoem62CWw7UXAgwvQFiTc_e9KWrc5EuUn32tCkknr3OIJSahsyvzZdnkCBmeenoL-Z_Fyo3L4euewlmaJI0c_hM5y9UMTaT3VxzqRmVPCDM91yPmXOYnu-6IdaBp30VSuGjCvkShDOBZOuo-go5oXmzdEUJqxB7CgcKKxJShZEvXcSgAkKUIMEDFkhXS1EZ8zPbMSfU5l0Zqo5eCYhc3dzodM7XK6jCDsLPxojegkoUzYOqosrSKL6-Vyj5OXDXpvFjHb7N7E3LO44P6Fql7TnuDpbZbmEvvLHwNhkFxd4U72gcm1OQG6C9UJ9haFCZroEzLcpsAuVfMS__9pDXOeS0sodVprtJD025AlqrzVa81WjaNlIcZkWrlxdxmqog6YOfzDZFNdd3X9kCzCjWvCCenZa5SFSgzTX2Om83OLv1rClKG0SMKVqOajZ9bYS1rMdQPEetXrMVTZudqottC8nXHOuFcWsNGlk9yk3gzZayNeGL-DpO3kT2EhPgxLWJTjMOLG9llnHO5QzeYjlOxa9L8JV2W9Uc11tXR-o8ej7b4q7mxaY4diKpJVS6WjybNlHNQbSGvwLe2HFdot-baFqCsqifxF1DqRfHsgqpqVxmBkg9hldLZXNrb3ZTDmJCfK3DyrOnF6ocv4kOp7F9a8Y_Rv8fzeC2Vg==
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/7902292/64961235-e4bf-42d6-92a6-a3898b022055)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/7902292/b977fd9e-0889-4ad1-9188-30628f419cfa)

**Comment by Paliak** [comment] 2024-01-07 15:05
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7140. Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7142. Should be fixed in next release
![obraz](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/91493239/202cca84-97aa-4fcb-bdb9-9f730e1b15cf)

**Closed by Paliak** 2024-01-07 15:05 UTC
Labels: bug:behaviour
