### ISSUE TITLE
I cant Save my Build

### ISSUE THREAD

**Issue by anbeck88** [PathOfBuildingCommunity/PathOfBuilding#3209] opened 2021-09-10 16:27 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When I save builds:
- It said " Error| Couldn't save the build file: Make sure the save folder exists and is writable"

- Try to create a new folder to save "Error| Couldn't create (file's name): invalid argument"

Need help on this

### What is the actual behaviour/value?

When I save builds:
- It said " Error| Couldn't save the build file: Make sure the save folder exists and is writable"

- Try to create a new folder to save "Error| Couldn't create (file's name): invalid argument"

Need help on this

### How to reproduce the issue

When I save builds:
- It said " Error| Couldn't save the build file: Make sure the save folder exists and is writable"

- Try to create a new folder to save "Error| Couldn't create (file's name): invalid argument"

Need help on this

### Build code

```shell
When I save builds:
- It said " Error| Couldn't save the build file: Make sure the save folder exists and is writable"

- Try to create a new folder to save "Error| Couldn't create (file's name): invalid argument"

Need help on this
```

### Screenshots

![2](https://user-images.githubusercontent.com/37860544/132886329-8c55127a-b179-41aa-bac7-3e8212365a52.JPG)
#![1](https://user-images.githubusercontent.com/37860544/132886321-cd847db1-4d0d-4290-afeb-96f80152fe51.JPG)

**Comment by Lothrik** [comment] 2022-06-25 01:33
Closing as this issue appears abandoned and is essentially just a request for technical support, not a bug report or feature request.

**Closed by Lothrik** 2022-06-25 01:33 UTC
Labels: bug

**Comment by Lyn203** [comment] 2024-02-05 17:48
oh, i got this problem too
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/22714065/ee1a1ae1-31e0-437b-8b3a-9939475a834c)
i think default build save path was mistake by the name of "document" folder in onedrive ( for my computer here is "tài liệu")
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/22714065/ab104020-0f0b-42f0-a1a4-dcaa16d1674c)
Then i try again by downloading portable version of POB. Then it was absolutely fixed
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/22714065/1ecd14da-3a90-43ef-9c20-94576ee4aeda)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/22714065/1979f832-e6dd-4e7e-be96-c99224a03cf7)

**Comment by MR-P4NDA** [comment] 2024-07-22 20:59
A lot of the issues are because of "Controlled Folder Access".

Go to Start > Security Settings

Click Protected History 

![image](https://github.com/user-attachments/assets/9c0b09a2-bbb8-4123-9c01-a60cc0039e92)

Click on a instance where "Protected Folder Access" blocked access

Click on "Controlled Folder Access Settings"

From here you can go to the history to confirm/deny if Path Of Building was blocked. If so you can select "Allow an app through Controlled Folder Access"

Make your selections/add your exceptions. 

Restart Path of Building and you should be good to...

**Comment by bbence01** [comment] 2024-07-26 11:46
Thank you, 
It works, this issue came up periodically for no reason.
