### ISSUE TITLE
Unnerve should not scale DOT dps 

### ISSUE THREAD

**Issue by Jenson-co-in** [PathOfBuildingCommunity/PathOfBuilding#877] opened 2020-05-05 01:23 UTC
Unnerve does not increase damage over time taken, even if the damage is from a spell which applies spell damage modifiers to its damage over time effect.[1] - From wiki

Currently POB configuration shows an increase in DOT dps when unnerve is selected. This may be an issue to resolve?

**Comment by LocalIdentity** [comment] 2020-05-05 08:56
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/843

**Closed by LocalIdentity** 2020-05-05 08:56 UTC
Labels: bug
