### ISSUE TITLE
New cluster notables errors

### ISSUE THREAD

**Issue by chimgan-75** [PathOfBuildingCommunity/PathOfBuilding#2273] opened 2021-02-26 10:00 UTC
Several new cluster notables after saving give an error when reopening the build. Everything in the ![screenshot](https://user-images.githubusercontent.com/79694726/109285667-2c852f80-7843-11eb-82a9-cfa6cd3c2292.png)

**Comment by chimgan-75** [comment] 2021-02-26 10:13
Tested on "Medium cluster jewel / Aura effect" with some last added nodes.

**Comment by pundm** [comment] 2021-02-26 10:14
Hi, please share your respective pob. 
I created one and i cannot reproduce it atm: https://pastebin.com/30L72WZn
Used both variants, small and medium clusters that roll grounded commander

**Comment by chimgan-75** [comment] 2021-02-26 10:20
I can't open build for export, but have XML.
[Avajjo_champ_CD.zip](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/6048945/Avajjo_champ_CD.zip)

**Comment by Wires77** [comment] 2021-03-03 07:04
This is happening because Winter Commander didn't exist in 3.10, and because you have a build tree from 3.10, it tries to load that notable, but fails.  I've removed the old spec and uploaded it here to fix your build in the meantime.

[Avajjo_champ_CD_orig.zip](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/6074152/Avajjo_champ_CD_orig.zip)

**Comment by Wires77** [comment] 2021-03-03 07:18
Fixed by #2299

**Closed** 2021-03-05 06:22 UTC
Labels: bug
