### ISSUE TITLE
Timeless Jewels no longer working after latest update

### ISSUE THREAD

**Issue by BlazesRus** [PathOfBuildingCommunity/PathOfBuilding#4576] opened 2022-07-12 21:53 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Either use old manual timeless jewel values or calculate change stuff on tree based on timeless jewel.

### What is the actual behaviour/value?

Acts like error pops up and acts like timeless jewel is not there.

### How to reproduce the issue

When loading a character with Glorious Vanity timeless jewel or adding same timeless jewel to tree.

### Character build code

```shell
https://pastebin.com/WD35bSzw
```

### Screenshots

![FailedTimelessJewelUsage](https://user-images.githubusercontent.com/2676233/178601748-27e6e5e0-ce74-4f91-978e-f800887ac2de.png)

**Comment by LocalIdentity** [comment] 2022-07-12 22:04
Duplicate of #4570

**Closed by LocalIdentity** 2022-07-12 22:04 UTC
Labels: bug
