### ISSUE TITLE
Error crash in skills tab

### ISSUE THREAD

**Issue by skripterasm** [PathOfBuildingCommunity/PathOfBuilding#1154] opened 2020-07-06 11:19 UTC
**Version** [1.4.170.2][2020/06/23]

* **What happened?**
Error on change default gem level/quality.

* **What were you trying to do?**
Nothing, the error is present from previous versions.

* **What steps will reproduce the bug?**
Go to the skills section, specify any value as the default level/quality of the gem and then erase it or write a space.

* **Does it reproduce every time? If not, why so?**
Everytime

* **Additional information:**
Screenshot
![image](https://user-images.githubusercontent.com/45835112/86588037-8f177b80-bf93-11ea-86ca-3f696fcfb9d9.png)

**Comment by LocalIdentity** [comment] 2020-07-06 11:20
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/1130

**Closed by LocalIdentity** 2020-07-06 11:20 UTC
Labels: bug
