### ISSUE TITLE
[2.2.1] Cannot parse correct item name when pasting Custom Item stats from Official POE Trade Site

### ISSUE THREAD

**Issue by jezznar** [PathOfBuildingCommunity/PathOfBuilding#2633] opened 2021-04-21 06:48 UTC
* **What happened?**

Given I have a custom item in my clipboard

And It is from the Official POE Trade Site

When I paste it as a new Custom Item in POB

Then I'm not able to parse the correct name

* **What were you trying to do?**
I was trying to create a new item by pasting stats from the Official POE Trade Site
* **What steps will reproduce the bug?**
1. Go to POE trade site
2. Copy any item stat
3. Paste it as custom item in POB
* **Does it reproduce every time?**
YES
* **Provide a build code:**
This is rather not a build-related issue so I'll just post a sample from the Official POE Trade Site.
I think the reason why this is happening is because the Item Class is now found in the first line
and the Item name is now in the 3rd line.

```
Item Class: Wands
Rarity: Rare
Tempest Branch
Prophecy Wand
--------
Wand
Physical Damage: 41-74 (augmented)
Critical Strike Chance: 9.84% (augmented)
Attacks per Second: 1.20
--------
Requirements:
Level: 68
Int: 245
--------
Sockets: R B B 
--------
Item Level: 69
--------
36% increased Spell Damage (implicit)
--------
16% increased Physical Damage
26% increased Fire Damage
Adds 25 to 46 Cold Damage to Spells
7% increased Cast Speed
23% increased Critical Strike Chance
+25% to Global Critical Strike Multiplier
+17 to Accuracy Rating
--------
Corrupted
--------
Note: ~price 1 alch
```

* **Screenshots:**
![image](https://user-images.githubusercontent.com/13676977/115508831-57728980-a2b0-11eb-87e1-aa397629990c.png)
![image](https://user-images.githubusercontent.com/13676977/115508898-6822ff80-a2b0-11eb-8604-47e907c7dd4f.png)
![image](https://user-images.githubusercontent.com/13676977/115508948-75d88500-a2b0-11eb-978a-ff191244b6f1.png)

**Comment by KubovicsT** [comment] 2021-04-21 08:25
Had kinda the same thing happening when triing to copy items from the game client. Also for me it didn't make it rare once copied but unique.

**Comment by pundm** [comment] 2021-04-21 13:27
Duplicate of #2594

**Closed by pundm** 2021-04-21 13:27 UTC
Labels: bug
