### ISSUE TITLE
LUA error when mousing over any item in items tab

### ISSUE THREAD

**Issue by dudlite** [PathOfBuildingCommunity/PathOfBuilding#2945] opened 2021-07-22 07:41 UTC
![image](https://user-images.githubusercontent.com/17979885/126604761-3c05277f-c2a8-4a5b-9dc7-0424d99f53f5.png)

Attached image.

Steps
1) Created new build
2) Added new skills
3) Selected unique item main hand
4) Error occured above

**Comment by SeikojinSama** [comment] 2021-07-22 11:28
I have the same error stack/trace, however, I did not add new skills.  And it did not start until I went to the tree to distribute points.  However, it is clearly some tooltip/number placement issues.

**Comment by Nostrademous** [comment] 2021-07-22 12:21
Cannot reproduce using steps. 

1) I created a new build
2) I added Cleave as a new skill and put it in Weapon 1 slot
3) I selected Ahn's Might Sword and added to build in Weapon 1
4) No error occurred
5) I allocated some tree skill points and still no error occurred

**Comment by SeikojinSama** [comment] 2021-07-22 13:39
![image](https://user-images.githubusercontent.com/87549441/126648262-b96be16e-ee0d-4aa9-bd26-9b798e93daac.png)
You can check the items I have laid out.  I did spend the points to setup my ascendancy and some of the passives.  I do not believe I picked anything new, since I was rebuilding my ultimatum for damage loss validations.

**Comment by Wires77** [comment] 2021-07-22 14:44
I can't open that pastebin, but from what I've seen on another issue, it's when you have a minion skill included in FullDPS, but a normal non-minion skill selected as your main skill

**Comment by SeikojinSama** [comment] 2021-07-22 16:06
That workaround fixed it.  Hopefully it gets addressed :)

**Comment by SimplePotential** [comment] 2021-07-22 17:30
Yes, I can confirm on my issue.  I had blink arrow set to show in full dps, if I remove it from the full dps calculation the error goes away.  Tested multiple skill sets and this does always appear to be the cause.

Nice catch @Wires77

**Comment by Wires77** [comment] 2021-08-06 18:18
Fixed in 2.6.0

**Closed by Wires77** 2021-08-06 18:18 UTC
Labels: bug
