### ISSUE TITLE
Reduce minimum window width

### ISSUE THREAD

**Issue by nmussy** [PathOfBuildingCommunity/PathOfBuilding#1978] opened 2021-01-16 20:08 UTC
**Is your feature request related to a problem? Please describe.**
I'm running PoB on a portrait 1080p screen, and I can't reduce its size below 1280 pixel wide

**Describe the solution you'd like**
Allow a smaller window size

**Describe alternatives you've considered**
N/A

**Additional context**
The "Items" tab is already overflowing correctly at 1280 pixel, but the "Skills" tab would need to overflow properly (see #1977)

**Comment by ppoelzl** [comment] 2021-02-11 01:42
Duplicate of #644

**Closed by ppoelzl** 2021-02-11 01:42 UTC
