### ISSUE TITLE
Error 'OnFrame' attempt to index local 'actor' (a nil value)

### ISSUE THREAD

**Issue by PpvAlx** [PathOfBuildingCommunity/PathOfBuilding#3070] opened 2021-08-01 09:19 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

No errors

### What is the actual behaviour/value?

When I'm howering over any jewel in the tree I see an error.

### How to reproduce the issue

1. Import this build: https://pastebin.com/p1qRnrXH
2. Open tree
3. Hover mouse over any jewel
4. Popup error appears (see screenshot)

### Build code

```shell
https://pastebin.com/p1qRnrXH
```

### Screenshots

![изображение](https://user-images.githubusercontent.com/657238/127765747-1883586b-f821-41af-9dec-1813f6676e55.png)

**Comment by PpvAlx** [comment] 2021-08-01 09:27
The issue is reproduced only when I choose cyclone as a main skill.

**Comment by zao** [comment] 2021-08-01 11:50
Thanks for the report, this problem is a duplicate of #2945.

**Closed by zao** 2021-08-01 11:50 UTC
Labels: bug
