### ISSUE TITLE
Lua error when mousing over The Tempest's Binding

### ISSUE THREAD

**Issue by whypick1** [PathOfBuildingCommunity/PathOfBuilding#254] opened 2020-02-29 08:45 UTC
Running version 1.4.157.7, was comparing uniques when the below Lua message got thrown when mousing over The Tempest's Binding. Appears to be the only unique this happens on, which I verified by mousing over all of the uniques sequentially. Restarting the program did not fix the issue either. Only affects the build linked below, tried recreating with just what I thought were the relevant bits (minion mods on equipped helmet, Ascension tree, golem passives) to no avail.

![pob_lua_error](https://user-images.githubusercontent.com/5623882/75604183-09d30600-5a8b-11ea-9a95-1b802f957908.jpg)

Build: https://pastebin.com/tF2wCf5r

**Comment by meatballing** [comment] 2020-02-29 09:41
Managed to reproduce this with a couple of steps. The cause is likely around how Innervate interacts with Lightning Golem's Wrath Aura.

**Repro**
1. Create new Skill with Summon Lightning Golem - Innervate Support
2. Create any new attack or spell skill
3. Change your main skill to the new attack or spell skill
4. Go to configuration and enable Wrath Aura from Summon Lightning Golem

**Comment by ae9213b** [comment] 2020-02-29 11:30
This issue can also be reproduced even without innervate support by trying to add a gem to the lightning golem group after following the instructions above.

**Comment by pHiney** [comment] 2020-03-02 08:43
happens in 1.4.157.6 too. so no joy there. Ill see if i have an older version

**Comment by pHiney** [comment] 2020-03-02 09:46
Modules\CalcActiveSkill.lua  
Line 451
Was (1.4.157.4)
`for _, value in ipairs(skillModList:List(activeSkill.skillCfg, "SkillData")) do`

Now (1.4.157.5)
`for _, value in ipairs(env.modDB:List(activeSkill.skillCfg, "SkillData")) do`

So it won't the change itself, but probably the data that is being referred to.
I have no handle on the Data Structures in use in the program.

Hope it helps
P

**Comment by meatballing** [comment] 2020-03-03 10:33
The root cause is known.. just looking for a fix now.

**Comment by LocalIdentity** [comment] 2020-04-13 11:13
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/753

**Closed by LocalIdentity** 2020-04-13 11:13 UTC
Labels: bug
