### ISSUE TITLE
Minion Instability causes a crash when selecting MI as the ability in dropdown if minion is supported by Unleash

### ISSUE THREAD

**Issue by rcpd** [PathOfBuildingCommunity/PathOfBuilding#3123] opened 2021-08-09 06:04 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When selecting Minion Instability from the ability dropdown of a minion it should should show the explosion damage.

### What is the actual behaviour/value?

Crash (see screenshot)

![image](https://user-images.githubusercontent.com/5835162/128665461-12241a2a-f51a-45f2-96f9-76ef14034535.png)

### How to reproduce the issue

Repro'd on fresh PoB:

Allocate MI
Add SRS Skill
Add Unleash Support
Switch SRS ability dropdown to MI

### Build code

```shell
https://pastebin.com/bh5D7sEP
```

**Comment by rcpd** [comment] 2021-08-09 06:05
Also prevents existing PoBs from being loaded if MI was already selected when saved.

**Comment by FloKaemmerer** [comment] 2021-08-09 07:49
I can confirm this issue.

Example PoB: https://pastebin.com/KqXk6sFy

**Comment by zao** [comment] 2021-08-09 09:10
Thanks for the reports, this should be a duplicate of #3118.

**Closed by zao** 2021-08-09 09:10 UTC
Labels: bug
