### ISSUE TITLE
Lua error when hovering over a specific mastery

### ISSUE THREAD

**Issue by SeventhSolar** [PathOfBuildingCommunity/PathOfBuilding#5593] opened 2023-01-15 01:20 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

![LuaError](https://user-images.githubusercontent.com/26511899/212504122-75d5f232-eb27-463d-926f-c0ed48c42024.png)

### What are your system specifications and configuration?

Operating system: Windows 10
Keyboard: Logitech K120
Mouse: Standard mouse, just left, right, and scroll wheel.

### How to reproduce the issue

I'm sorry, I can't remember the set of inputs I triggered it with.  I was distracted while talking with someone else.

1. Shift-select a series of passives, ending in a mastery.
2. Hit or release or click somewhere by accident, possibly multiple in combination.
3. Successfully allocate the mastery without ever being prompted to select an option for that mastery.
4. Hover that mastery to trigger the error message.  No effect on other mastery nodes.

**Comment by QuickStick123** [comment] 2023-01-15 07:38
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5489

**Closed by QuickStick123** 2023-01-15 07:38 UTC
Labels: bug, crash
