### ISSUE TITLE
Hovering passives: attempt to perform arithmetic on a nil value

### ISSUE THREAD

**Issue by RyanHx** [PathOfBuildingCommunity/PathOfBuilding#6024] opened 2023-04-11 20:58 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

When I hover over a passive it should show a tooltip without errors.

### How does Path of Building behave?

Shows an error:
`In 'OnFrame': Modules/CalcSetup.lua:561: attempt to perform arithmetic on a nil value`
Persisting even after a restart.

### How to reproduce the issue

In `asdf` tree hover over any of the allocated passive points around the ranger starting area.

### Character build code

```shell
https://pobb.in/BaVgVdTML0MQ
```

### Screenshots

https://i.imgur.com/xdwyBih.mp4

**Comment by Wires77** [comment] 2023-04-12 00:55
How did you create this tree?  Was it imported from somewhere?  It appears all of your masteries are missing.  If I open the tree on pathofexile.com it shows an allocated mastery but all of the choices are blank: 
![image](https://user-images.githubusercontent.com/1209372/231319768-af32807e-5713-4953-9743-b161f4f98d82.png)

**Comment by RyanHx** [comment] 2023-04-12 03:59
Yeah from poe.ninja I 'enlarged' a character's tree which took me to the fullscreen tree viewer on the official poe site, I imported it from that. PoB didn't seem to complain about the link for the tree at all, as you say everything appears allocated.

**Comment by QuickStick123** [comment] 2023-04-12 04:00
Do you have the poe.ninja link?

**Comment by RyanHx** [comment] 2023-04-12 04:13
https://poe.ninja/challenge/builds/char/Mishr%C3%A1/Mishra_Crucible?i=7&search=class%3DDeadeye%26skill%3DLightning-Arrow%26minlevel%3D90%26maxlevel%3D92%26sort%3Dlife%26lightning-arrow-support%3DTrinity-Support

I clicked 'link to passive tree' then copied the URL.

**Comment by QuickStick123** [comment] 2023-04-12 05:51
This is an issue with poe.ninja I have notified the developer so hopefully it will be resolved the issue is the masteries are allocated but nothing is selected. As this is not caused by PoB I am going to close this.

**Closed by QuickStick123** 2023-04-12 05:51 UTC
Labels: bug, crash
