### ISSUE TITLE
Feature Suggestion: Loadouts

### ISSUE THREAD

**Issue by dsnvwlmnt** [PathOfBuildingCommunity/PathOfBuilding#6592] opened 2023-09-03 18:59 UTC
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Good PoB creators have multiple loadouts for a build's different progression points, such as _Early-game_, _Mid-game_, _End-game_. Having to manually change each of 3 tabs' _Tree_, _Skills_, and _Items_ all the time is a bit dated/inconvenient/error-prone.

### Describe the solution you'd like

Add a dropdown below the tabs and above _Main Skill_, for _Loadout_. By selecting e.g. _Early-game_, it would switch each of _Tree_+_Skills_+_Items_ to the same-labelled Loadout.

**Comment by Peechey** [comment] 2023-09-03 19:56
Duplicate of #4569

**Closed by Peechey** 2023-09-03 19:56 UTC
Labels: enhancement
