### ISSUE TITLE
Top right medium right cluster node.

### ISSUE THREAD

**Issue by BSpawns** [PathOfBuildingCommunity/PathOfBuilding#2864] opened 2021-06-20 19:26 UTC
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

The Top right Medium right of the passive tree cluster (4 pass brand damage, brand loyalty + grand design)
When I load my character with import this cluster jewel in particular will have the brand loyalty node disabled and I have to enable it to get the correct dps. Happens everytime.
```eNrtfWtT3Ei24OepX6EgYjZ2w9jOtzK97rkBGANuY2PA9nR_6UhJKUptlYQlFZjeuP_9nkypqqRCokTZ033vxDrCUCWdPJl53ufkg5f_8W2WejemKJM8-2kHP0M7nsnCPEqyq592Pl6-fip3_uMfk5dnupq-j_fnSWrf_GPyt5fus5eaG5P-tKPYjlfp4spUnxao6G-A6lpn1dTk2an-PS-O8uinnXd5Zna8QGdRUi2-hakuy3d6Zn7auZjqKL_d8XQZmiw6WL3YK0v4nGQ73kwn2UUefjHVUZHPr2HQO95NYm5P8wjgTk7P3p9ftnpOsnbPMPK_vTxL9Z0pLipdeSX8AORAAH1ljpMKUOl0DnjQzvMHYV_pGfzcDH5xbUz0Z4OdFeYwjk1YJTfmoEiqg6nOwhGDfSzs6Tytkus0McUSnj5jbKjJ8T3sGA3iv8wrnb46u9g8ksdC5iO4_DmppvspEHsUXgt9cpUllRkNfpYnZZ49atSjgA_yWZBkI8e9AN67uRoDnKegm9kK8pni_qCaFEa_j2spPNdRMi-X7RgfanSqM32QlyP48zaJzTjIw4txcOegzuMg7SjPTAEGqho_2Ec1uKhWCoXxILnOzdcuJB6CfGW-rcAIewBhB3IY4Um2mgZl6AGEbUgyzPpX5iavwHGMo-YKo5DkAWMZvrDQJ1m4bCDYQ3g_ZoUpTXHTMrIP9dBt0rB4jHGzDc_NlVlNlzzb0M9bY8LpEfi-c12ZcULaGgmlD1LJQrepJB9C20Mk7JNxLe7RSDwTHHFKGFESi4eQdOnF6LMHu3wkuQ4zU1zdXUwTk7ZmRXz5INnardrkI3xMP90JjRraY2d1o8u2TmF_2JjUE6obtOcyLGEG_CM0iMyaU_d_XIuzIv_dhjHp45rtFbN8XowKp8IXNfCoKZ9N78okBGfsgr9zE83DcTZrGY2d5jdmBgrgAjmIWFeseUYHp7OfQri7Hjk9xMg07WsyHNJWlQ6_vMqjKzO2ievkUS1eJwVQrExa_s_nm4HfQ7h9oK9XqiWH4xOrUiM7WAGvd0CHjfDVtMog-xndyVqL9Z7YoLkDmublWjdPh-PqFvh6H8PsmKfjYuaLL0kXstJBal546BsyIY4MGdaW_BYGM7Vp4Sr4w2OgT3UrCBmeQmGyP-7WOxgHPq6HwyyaF1a8R3ey3qLdTy1ZL5-7zNl-Opld50XlQZJb7YVhPs-qY11OAVDi2DcIaGsQoyIMkdCBNKGMaUyIpr4IEYohXHBNz41OZ0C_g_qr7ViHlSlqXBpjIRBTlIa-IBhJRZTmEksaxUIJwgMamIjVtuflgU7D0s3sJLueV17mcu_SisBv2XwW2ESv_r3iZBtylpThb8E8jm0yvgM0KVwd4fD168ODy5NPh02TC-PsphfmaaqvSwPZeZakO14SNfJ2AZ4irEZAQ0rZZOKbYT_rIiwS4OJmUJsjjhiqy8Y3w9lUeQQYiINOzVgSXd5dGyt45TgqNWZ6M6zLekfA1QnsmGm5xHgM0U2o70bALYOgEbCHqdlLUutxx9DpFMS3dtVjoMFtFkkwr0ZJlMtaRozAhu0jptUOV0eMtI6HRuBtAsbNkI13GiNPEImMpP0rExuQ0lEa6rT-Un8xWWNWF7brpVOP0ivBth6ZWbl_B97rtaXUWnWkAwB-rZiDyYpMrOepff5hrtOkumv6XD1_W5c83dNymt9ezK-va0xWJUug9tu39Zu9tGqQ2G5-2ol1WjYlSDdGV8rcc3Gh--5m4OqZSRam8wgS18ZNN92lOrBd73hXtvJ5YD1G88Zk1itHi1mUaW7rTEZfA_nwznpHtg87jL-9hIE1bY_SPNApWfRUT5LudN7iJX6L5cRKVhiCvwvv9rLIWrlyD77teF_rWZ84pXZ0gyGbmf1-aiod6Uo_P6mAJs8tYZ67McGns8KESZ2wfF0QH92bW9iatvU6Noh3Jc-m7fNRMyNo09Qavu5FUWKlUKerAthj57eUEJDoPIs-J1nUmiIZO8e6teea_6hZvk4B_SsIFbbm2n0MLqQaNyXX2HOta52v0W7UkdoO_EgtId7FrQ2c76mKbTmO2I-WqH-efYcs9aKxRYuRpD_MUpufmOyvpjz-Cyjf2OUfQv51XOON1mHWjsr-OtH_LtpvNqSuVuD89T33AC7SFJmuDB5la4ZQPcKI_grpUl4VdyMtKP1vodRoO53-Acw71lVhoq2dw1rz8TNpGv5VmgHkuLH5_r9SL87mhV1B3jZY6rR-hAJ81jfGy2PvIM9ukrp--YNDpoN5UZr3mVtO31oTepA8YpLH5luVz8Ppj57afp5B8gnPvmNm93E8YmKrxj8sAizysgpsir51BHgPwyMmtGr8V-n6fh7deYslg-9QeLyJ0qBx0TypLpKrJN2a2BdVXsz2C71lCmFbe3XzH6wabjnERPXCY5-LJyP1ow_RI6Z4kpXXSaH_FYatVaN-n7mq3vZWYBjXI-bqkHg1Fu995lk8doHqR0-8XTt_n12k-i7JrkBz_zDZYWZm3xNHj0b9GBEIjbe_NCkbycDH-rU8q4o8he5fmRJAnPM8S-3Wlu3d3Eacj5j33q2th5nIW2H1Wmh_MDkgVjXRco2rjsq_kxobUW5DDIfUW2L1OgsGf4W7yavviiw38udkNgNyajv27f1ML5LH6GDT3nMIfmyydaDL6n3WLgFvk1OudHAQ3SPma5F4t1OTNfLlrWrTP9AQn2RhYXQJ1mLeuLjtlW0Y16O8bYPEW2L5H6tYGwO4MyfR26ds3ebtkHGjn3ct_yrKHpt0ZqrvIa3YKN82KD434feYrLq5C2638hiupdcM4l9VHnLLRz-kQtTF9Ih5Hs6ubdz4_1dKWrP0x06yCHVmLrYr3ayY2IPlMaGNa-7V7deMQvPJrYReFsZ4ulZY1xA3q4_wpX3Ewg4YTFGWR3b9UnDp812qJMO7PmNslzEs2S73Gd0VQiqxS5CS_i5Dvi92ORdSwHOF-C7B0GiX-kqpXa645LuASwEuiYna9ZVA8ID7dJcoH5NdLgAXJZTVcHJXYMHpLqUUo10GzylgoRw-MrJLGYaGdmxkF1PsAwTgg5aMADQlihJ4oqAf-5LasXC5q3xlB0phzAJDb4JxSd0gYLSIM7HLfI586FlJbLFLad8K9xP6EJhhwMgJtGJYUO6eM5ivnR1WCJ5zrlSNE1pRxvxdxZCEAUgA55LYIcH0mENsO4F_8ATZtwTGhGFodBdLXyiL11e7WCgOBFfIjgDGhHcJxdASMeSIqeAxoxaLkDBJyqQk0B-iFg0BWhEfaEIEgfYwACyB1BgAYcYEfkofwDFTQBVOOLJNqVS7TPowA7vpFahHgaHwhFB47lMk3LCBwpRgoJzCqh4r0A-GDzwTAtoShWCCgB9GD4i5xWYpCvwSbBfGDR9BaDAQjiNsX3IEnwVMmQBf4AknRDphgM6ZsAMB4kArzplyzwExtUQH9gIbFLyFlxgDBxF0ARMBvMzOiRMYMYxX-IDD5_4uxpRa4RQ-iHoFmtE6qoRZcwrJaoJoXNohmDMTvbNK0diQj-dv3Ye_Tavqunzx_Pnt7e2za11N89h8S1LzLMxnz6_tOaUb89RZjqe2o-d78G9_75f9vTfz6fH5RTnb__XmYzyPL97Njj6Zg4_B09_307PD-Oj4w4fXX_affo5ffbqaivTXb-HN4ZufX8eX7-5uw38KlB98ub1NfYz_efTmy8ezb0e_fvztMPrwoZhdyim9ESy7zL---zlRX0Emwy-3rz-9_f2VPiHfLm5PP3568_HjieAFe7P_9AanF77_C_tNJIdvLn7-EJpY_jrL5u--An8_nB7vz9-nv797nb5_d5Pn33x89_PN0VN29_X3s_Dq6fQtU0fhL59uP86Ok9P06o_gYO_o5-m707eXJ3eX79QX_kclP7_O5c2nvPgU_fLl7WX57rW_f_nu_OjzH1qev8K_p28P9eWb259-coR9vqDsy_pkV1mTufnmDJOzUQJkGYKaqraxzS68HjiMORoBB6JF2Rg4azVWcGIIDlRdjcHHJIj8CDir9SswOQRmzc0KDA-BgY6Omq0zzis4Okhla7dWcGwQH1N4RLccLIk_hrkSlHrMNIRP-Jh-OdjTMUwDYz8GDtvjDGPwCSnHwFkXtgIjw-hgHmO6BScyTjcoGkM-8NWjRJn4TI6iClV0BJwNJlZgapC5Ngpp6cagcoA7HNUvhChilPRJCCzGwDHlo1HSDH6yNZFBOQBnqOSoiYBrHsNfxuQYwlAIGMcIAsQmYgw-7BM8zkZCzDlqfD4f0y8Eu2KUHtm4ZwXHh_VDjKIfJljgUfMQdAycgDhplFUTcpzL8sUo_bVx7Jjp2ii9Jc-DXkYgn45SJODvKMXEHXnBw4QWahyhFR5nT1lbnv1FXvq8FfHAF8jMXBJnUzf74V1eGffOPlx8cYndp8TceqXRRTi9qApbzPkjz2e_uC0WdvfpsdHVqb5ukkf77u2yZuH2rVa6epXEsSncnttFxmkB_7mYx0uXvTYppP18YSqXKs5L02TobguRe7woBrlGbpNus8v0XBeQ377wzvfODyev5-mVySoPhldUk1MTJfOZd5DOy8oU3htza9LJxyz5OjfeyasXnpZ-ZOKYKkjYAsiEICIySktEIH9ijGiEZcAxZUhFIVFEGkPCGHIJKQIlsNETNxY38ReeUBP36dx8feFxNjmZXadJmFTlC49N_l9Y6Bji_f_ci6LSY95ZHcZ7dTa9eo2b9YTOey8BItWj92p-dvAB-MVMA1gXqXdV6Kx64WHyd1uoa-qodRWqLiJPePuNW8Lw6tPUkwfQ6rTMF7ifsL97Vd5a_ag3btttZ5PBqdRDeJvf6bS6GwY7qkcKCK8yJ72W2F0JID0S8D5Ikxu7r3sf5lVNJwe24FLd530QUMjYjK90rHiEwL1gjU1IZBThSBIktPYh1fTjODCQA0rlhxLxwASKRrGPwg7vJWqzG02w36bsYt3UA01KvhivPi3h3SbVtEW6RhSeWH4BTetK0b22q0sRAJI7yGGQgS4O8qKYX4P0DJCV9pAVJCZzBXjvfJ5kGzULcvvQEB6HWvMYcvsQ8wDSbhYTEUtBuWBxIEPsx4IYKUC3YuorEukQcWEEjrvUpYOaRf-batZY_al5fZi6Y5vAwpb-jETRMwZ34nJqMXrw_epPUUXWIzN71zmI5d11CaiAYxlIyrA6Mh3JiKlYU2IY1UiEPgWLGzAfXGAc4EAYSY1QKlYsYoFmQQSiQ5ivGETXvCMwPmkJDBFtgcEr6ff20zyPvFBnWV55gQE6xgBm34CY3-Vz0DBk2QN6ZbIr0KSaCt9gHokll2iT3m0eXazO3U6T1Hiv5sDRz_ZsCCjfGvj6grHty8mCZXefPGxWW95lwcd3Jx8-Hk7AjhRJPi-9Tzqzo75MZiY1ZXmfBQhpwoQBehLOYqC1ZsiPeQjaqpUGD-gj8IaM-BRp34AXNBKTyGjGaaxVEHV1VkxqV_LCe2s3X3R54A6nm0JXxkPP8N_thkF7hMm7BltSOs8_2QfjDXRKMg9-e4FjFYAxJJRX6rBI4iRcvbfVa_v6VV7cwTwnjQiX9n3hxuHpwtidCzDbAtoFd67dJ63TyTGQGIgUDtBV9Ij2gQYVS-_KGdjpZDYDwd5kEQ2NpGYi8gMcIaQEiDH4mEjrSMQg-ThgKvJjLAXXgQ4hrAdxDyFbRYSZOKS0S138b2sR64jCHToeFU10bNMg1HGe3jXcL6sBPvs9fL7I56n3CdQFmDlkujhFONJChiIQMgqlRkhgaevGKo4IuDTBiSZKIxoy7YcxU0yEPJYo8jWhIX44kuhYDXuwfEFQzDbYk_FxBK5pbpE7f9ATzm02P7KHfEdg_adLFRkioMKgF8wgqmUQBhq0xPdl4BvQBh-sDBIB8qVghsaUExYrzBliQFMDBAcvEa2rRsfUWLMa1gEXzHHvJk9A-Y2dXL0NbPJE3bPxJ-Cq0jS5Mk7y2KPM_BMst4vKFg7A3k7wABv6ia96iP82BxPqXUA4DLR3RnjYOsXK5zjkBGvJWaQiwk1siFEoEoaFCoUBiQLwADjUIkIRYxCmcRELFEaSxUx23e_4eE0OWifSp8q1FW9bp3J789RWppHWCbfb1xdbOFa57TnuwHbNXIe6mdEPCAWH47dUZ0AEiz_Lb4fh7Fvr42YD4oNRj_wc6iuQ7jf53SbhCWMaoDCOMZXMBAiSKWZIAA7MNyFmkGMZaxcN1yGjAdVRoKVRELlxqkJhjOoKj_h3FZ6Fa7MtHx_nP-Er6_CnikZfmeUTpNhRU2QBQzcrIWC-7xcDEAipA3CAISOYQsIXUcifAz8kEY-x9iMF6WAAgbyWjEbISCWxUgGSVBkshnNAa2_aNv6XfN4K493ZjkYRL8BAWzI1kfwyeN9k5hcG3uI41WB3vbzwLkJzDW6iXHrMpale42k56QpLG9v7zHjH0AYe19WtzZ4Vk97I_rOuwqkp_hcgKf9v6R3emclZkZQzSNPD-9zwMY-jEDHwn_amjiDExCAjqBLaRJBEmYBHoY59DWwKFLiCIGaMUEmk4kEU-F1u8MnbZGYXsIEMlgP3XO5q8p1d5IttfN3S00x_S2YQPNcXD3j1zQMT0Qdi04QJ63tjd_QDKTPIH2xiEXn2Ak_gzZ0VDlsLWvhr7e5gqHOAxXk9EJ95CVyGrGSWwG9gbqXBa3ensgitiNjo4u_1tDxCPsTkvqoLRNCzABC9L2yCk22uaPq-oAJDBhHDfxQTpGIRxiRmoFuEIdA1HPuxJhGjXEaQbAvIMWIJKUiAwdt3swzf_7fNMqgLBgFodc3Gn1ElwaxXkz_ZoBQSXmDpHehwfj014Z33GdC1eSsRN0ooLhAVMY6CSPOISgyxmuKaYUkpVyYMWah95ttYzg8IZOgBaDtjzO_aU19OmpPFLzyCJo0_fOEdPT16ut9iu5ADbG9ae1EO6mIt74Ij3uIeswVPlk0sgaqyG0St4p3GSNoSAPC3QT9haCj6nkh4VdSnebovMO146mVsNhEdwzGQGdXV2ckThq2MdKzLE_fotHnUNmzlhPDBNMFOqQ08JBz9BZzLqb3CoPjiXRiI4-srjBeuqCMeLDIijATnMRhvEwkIxDCJtS8pSEdEfRb7xoQqUEYyHSnl-4ZC6go5FYWcVa6726V4tKRj3-tKByVdy0_IQ7ydcNRD_wXT4F3zZJWu7acJqNRhY5QhyJgm1aR-uJS72shaM18sKuvQ8hgAF-1cg9oKW2dQ22b7ycaDi5dTe3D1VKdgYN1xFsvs0z6_5NjpSNAGsfLRejPA4b5S0hHET6D8mZnsz4ssKW3V63WedMw6ViEFU60opGbCxIqBo-aCgJVHIcJ-zCWXPpWIKdD8CJIycPARROQEIcMkUWN4e_T03DtqB1moy9snhI8sKLCOKqybA-cvMLeoCK9DqPYb371A_v2Khlqpuzu7BT3PM-9yChHZFOIv0NgHVqMGGOJ_hz3GmEeExTIygU-ZhoAptnVT5Rscc-AUQ8TXimoEdtluiwkjAvoHOU9MqY_lGlNYvz3ef7r_9OhPtMf2ZmVbSK0vqnISzb7TGrMha0weYY05-rOtsewVDXveyNLHFo_3ixx-FdM8jyaXt_nTiyqH4P7cVoHaaRAJmQRZEDFhClJeCSEYMbGhhkYREUpBEqwJiYIg0CpSPgczzWIMdjkAA47WxKSzstHRULJi7C_WFl6E-bzyLu1My9q6dYly7paGnmAxpvj3hBAL1cmYyMMFSNpZA3X2cVn2d-uIEJFPmGyK_93G7voAU9T5RSfXdlMrLT-bSWHUKfBdTHNbk7nSSQaCVpf4Fg5kiNOql9PuMPMiuTpK4mqy-CsBi4enSVWVbVYTzDgjJJRCQBgeQYgdUAkGWgFPQxuYo4iLyK5yQawWcgZm2wC3qe8HzDBM1lk9aBH2O16Yy64cyC1LxqQvac2BD55dNJoQ2eFoc5ubE5pu4vaEkGFDvHDK1v-6yNk6Ycc1MAnud_2uWYwDXkN_Tgycsi2DAZtMJ9B7s2PBShHmQ_sEUC-H96o_kiJZcBPs_CwpwQvNTAUWE4Qn1eWXNnsjLkOuIzDiMfeJkFhIEXGsYh-HMmY8VtJI0PNQEkY1DX0eSIMgSg8lggyMrq9RrtgrBi08mhCnIfWCSMMTd0chsECX9bJZNC9cQdsO2DPOck_sFYae3YcAjdc8gG13-K0qdBdrg6XTnrv294L0MQgGWIH7zaoNworyFqwrRLcfi2xykaRW8u4xAeIZRhAT0kdChwzSGwh1mAqlCQMhIM8NIx9zH-KhiKPIPpeC-CzA1EchYXq9jtHWsaEKE5qcA8GdZ_HwopThTmNaSbU1h_nMFoK8-jbKyAvz4hpEqZuoLm5nbgrFfUxbCPcCTxOxdkAbzzxcnoCxOqWlq3XV5Vh_dhqXNQFUD95l61rsnNneonXddzdufgQamyisYnndWrSxMV-2Tr3DByVurXp2und0cjA5_AZxQGLZsaqgfZgnYH1acmfnYDe6deQvUDgIBCUIfhGKJZGCBgKy7AAppO3duZoHIkSxOyNCrVwGjDKFBI9D1l3t8_GA_GHRlb-T2Wxul-9d1bEw5o-m7mjvaumVpHMzs3cM3QcGiz0H0aSd6tqyLDdAQtqrtPZu3rTUC_JBOPQFOFxXhS_AKoMNPdJF0ImZmXWE2GamUikiZaC0In6EuO-HNEIq0LEQmMac-yEKNTcq5oHPIs1jLMgDJrTlIc9tzOy85OdBu0rGRM6LG0Pvhcx16LmqJq8VLZ74oh2t1jVL1eNck9gphAtkGh-4UgzQJRDP9G5COlre6D-IpmsxWbRrO1anYSDiaR6ZXS8yMCwQEGfMJ-BFk6I2C85_rEVekB2H00U1ve7hY9YuZNbPBgSldxtQFibW7J0USWTssUCIAo7vrgF_Etqqdc9eCa2kVkajWEHyFFAMzpSLgAVGwHehQCiEAXUClcJYY0iLkTaGsiggnIL9Hw6Z2dry-mLRdcQqOUX3eErqXLUpCNZZRh9B7y0S83bIamNVcNEQTUGjOIeEq9kD4yoelpVD1OZ9JWO3U8ZmxRriqeruKgGB-mQDm86WBRFrzaivmRacwQ9IQ1QQQ0ATYhIIY3jAIozAatmNxdSnIdA8DsIAc01Bk47n1nB6diiTg2JeQlTUfFtLapdKudetJhxr60r3gjuIqZc14Cessxa_Fq_2rxJ0XWCHPU8EvZ80NkWC9XW0pYY_obx3mW6ABWKsc9nXpd38sPQrF5WeZ-F0LVmMmMYMCSRRyMFE2rOu4EJUpCHG9BEkjMjXFAIcX8cBw9g3YUjDEOxmpKmMEVnfSzIQ3aBh7-Ju6LaSWK9rdffKPeRpHmy4ldfp25BzpEGZLgsNJsim3Je5DQbc3Qze_24ykucdAfk_nRopN5owTv0wgBieWyfNwIVDtgamJowDDWF9SDiBLE6DvAu7MQsydbuCGYDjCjpyP1S-oR1XdL5WVvOHkvauIK8Fiy1H0aSfdqnTetukWjmKxZ6fTck8lm6rQZPAQSLuNq4Qes_APWG0V1uesAcyvG6ZoTsRSCKHtuPUV74DCO0k9HXwtxCulp4KeW-4A3IkBzc3HOeQaRzPgyIpvYOkCFPTifWIrw0NfIpZFGuCcYBhFAHEMFwqATrnR5QyX0cRJP4sDlBsSOBD_BJqA7bT-JPPukjzIqrl5dxA6jjrlR7RUlTelp6jtVRfqK4ZXZKjdfWa8_elx_pyg65FrSlirVF9EiO2C6bLfeX3mE7oMNMfKsa9g4gQAodFgOKinaeq18qu2OujsexVP6hQFwgWSSRYYDf4QzSqgIs6oFwbhKjd_IoMj5nmMoiDgBKQAD-25yJRxA1VCA3v0PxTC3X80YU6-j-kUEf7yzj7eVXZu8he6wRihot5ej2d9xQOaCxBT4kKgIVCM7t_XAqCBIkEKHKAIqqUD5rOsMC-NNRA_qZDA6kcKDdlZFzhgPK13eZu50Hp9WxMANJ-tD4R9frEngb1LoZm7zJYrNoNQ-AIDhGiVCcq7vTOE_xM9e9CbJLqBdlbK2s9_TXevsmuHxhQB9DT1zZiLj2_J-GxVYvMOZ-HOd1fJdrX0ZXpVep58XUO_sN4e7P5mhGHjDM2kD_6iEWIaoSFiQUnoLIxBFk80qDOERYRMJljexBRRLESHGFuGKIxHk4mxJBa76VpHjq2n2QxxD22JCo37D9y-rKwn_W1hQsDajcXGHuPi0Vx14br2tluBLG4JsdrajJ3TpEt9SB8urEbL-p9ETZ37fQ3Uf3p5mE6dxse6sMR99dRCG7rd5oDN3QX86oENHcv2wNxYcO95p3NQ8vWLmNqhtOVoIs0X_y1oNXfp1iexlz8jasWVK1DrSO0y7841QJa3Ne8RKTuw-wbez_PEgsf6qp12pSQ-0CLy7CWMHIIUWtiBPePZy2_6jQZpEXr-CoRQ0DtGxx6CLa6-n1JMn8YqrmhfwnKB0HxOmjPAK1b7_TcQ8HOpbzL2dIBZG2y9XG-vhluCdIz09oqtWi2_PNW9anXwROv7YOuffSw5Fjncs955l5SrjUj45rdV6f7xNhyRH2T2TCqPinf0GRQ43tls29MdDsCj6MC-UHN2HaDFNv1NrJZHzXxBg73CdQGDtRG9LEd9YiS2KafDfI35ExGYKbb6xHeZiZsO2HA24ke28yf-w62h7SPxdsnYFvOfJTp6YkANg9oCztIN8176QMfycB-Mm8lYXybRqO08n4INS6GGjFTvjVhyRaiKLbTJrqdBNPHyxnb3vZvIdU9MexY6tMx2tkT_o6LfzeO_DuioJHMvB9uj-aE2EIy8dZ68B0iM9Yy9-cUj0kqRnNnA-2GEpIRloZsTeEtrcZ4lt7Pm0bMh46gVE-2NZoTbGt68W1c3hiluZ8Yjhb1DWMaTCqfN1mlu-rJVfbdX1_Oszi5AoiXz890NX0fu78UDRT_x-S_ANTdZtY=```
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
https://gyazo.com/11a08ae5aca618646798ed36400f31dc
https://gyazo.com/8b48c6880948a968ab7625c94650a1a6
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by Wires77** [comment] 2021-07-21 16:34
What is your account and character name so I can test importing it?

**Comment by QuickStick123** [comment] 2022-09-03 07:44
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2728

**Closed by QuickStick123** 2022-09-03 07:44 UTC
Labels: bug
