### ISSUE TITLE
Glancing Blows Damage Reduction Calculation is wrong

### ISSUE THREAD

**Issue by bascuhadar** [PathOfBuildingCommunity/PathOfBuilding#1403] opened 2020-09-19 12:20 UTC
For 75% block chance
Chance to not take Damage when Hit
should have been 
100-(25+75*0.65)
100-(25+48.75)
26.25

But POB calculates as 48.8.

Chance to not take Damage was 100-(25+75*0.50)= 37.5 even before nerf, so new calculation has gone to the wrong way.
Thanks

**Comment by wjdeclan** [comment] 2020-09-21 20:04
Caused by BlockEffect mod taking "You take 65% of damage from Blocked Hits" as block is 65% effective (when it should be 35%). This wasn't noticeable when it was 50% because 100%-50% is still 50%, so the right number appeared even though the value was being read incorrectly.

**Comment by wjdeclan** [comment] 2020-09-21 20:32
Fixed here:

https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/1435

**Comment by PJacek** [comment] 2020-09-28 17:38
Fixed in 1.4.170.12

**Closed by PJacek** 2020-09-28 17:38 UTC
Labels: bug
