### ISSUE TITLE
Importing item data bugged (?)

### ISSUE THREAD

**Issue by ipredictawyatt** [PathOfBuildingCommunity/PathOfBuilding#2653] opened 2021-04-22 15:20 UTC
Build code: https://pastebin.com/KytAPxEr

Importing item data (from the main trade site, and from in-game) now appears to bring anything in as a unique item, even if it is rare etc. 
![image](https://user-images.githubusercontent.com/83024253/115739515-fdc79900-a35b-11eb-963e-525aac73e87c.png)

If I try and edit one of these items, things start to get weird.
![image](https://user-images.githubusercontent.com/83024253/115739755-2e0f3780-a35c-11eb-8167-1992987d99d0.png)

![image](https://user-images.githubusercontent.com/83024253/115739662-1d5ec180-a35c-11eb-8f10-cfdbda300dc1.png)

For example, when I try and edit my boots, my gloves get stuck on my cursor (as if I had double clicked it and started dragging it around. 
![image](https://user-images.githubusercontent.com/83024253/115739902-539c4100-a35c-11eb-9d87-cda45b8d1eb2.png)
I then have to return to the build list screen for the cursor bug to disappear.

**Comment by pundm** [comment] 2021-04-22 15:23
Duplicate of #2594

**Closed by pundm** 2021-04-22 15:23 UTC
Labels: bug
