### ISSUE TITLE
Spellslinger and other proc related things

### ISSUE THREAD

**Issue by BassOfBass** [PathOfBuildingCommunity/PathOfBuilding#288] opened 2020-03-03 09:40 UTC
What irked me for quite a while is the damage rundown for proc'ed spells shows casts per second (which is useless), but not the proc rate, despite it showing the cooldown.
I guess the proc spells should just have their casts per second stat hidden and the proc rate, which is a derivative off attack speed * hit/crit chance (depending on the type of proc), used for average damage calculations instead. Might also show proc rate cap, which is 1 second divided by the current cooldown, for clarity.
Spellslinger will also add a mess to this, since the proc'ing attack doesn't have to be in the same link as the proc itself, and can vary greatly from the normal attack (can be supported by faster attacks, onslaught, culling etc.). So there should be a way to show which setup it has to use for calculations too.

**Comment by Regisle** [comment] 2020-03-03 09:53
This was going to be supported at some point and then never was, this requires you to specify the cause of the trigger which in some cases can be very complex and requires complex multi skill calculations which PoB is currently not good at (and not supported at all)

**Comment by coldino** [comment] 2020-03-09 13:46
I had a go at a generic solution to this, but came to numerous dead-ends. PoB just can't handle doing calculations for multiple skills at the moment, and would need a significant amount of rework.

A simpler work-around that could be considered in the short term is simply allowing a manual override of cast/attack speed in config (although preferably only for a selected skill). This would allow easy manual configuration of fixed-rate triggers like Cast While Channelling and Spellslinger, and allow a reasonable estimation of Cast On Crit if the user is willing to do the accuracy*crit*attack speed calculation. The downside would be the many mod calculations not affecting the output when they clearly should (e.g. cooldown reduction).

**Comment by Nostrademous** [comment] 2021-03-13 15:07
Fixed largely in #2294

**Comment by Nostrademous** [comment] 2021-04-06 12:41
Trigger-based procs are fixed in 2.0.0

**Closed by Nostrademous** 2021-04-06 12:41 UTC
Labels: enhancement
