### ISSUE TITLE
Trade for item Session ID issue.

### ISSUE THREAD

**Issue by xerudro** [PathOfBuildingCommunity/PathOfBuilding#5406] opened 2022-12-18 18:00 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour ingame?

I copied the new session ID from chrome cookies console, and when i tried to search for items i keep getting the sessionID is incorrect, relog...

### What is the behaviour in Path of Building?

I can`t search for items after i changed the session ID.

### How to reproduce the issue

When i search for league items to improve my char i get the sessionID is invalid.

### Character build code

```shell
eNrtXVlz2zqyfh79Cpar5r5EjomFAOmbzC3v1jl27Mh2tpcpkAQlxhSpkJSXMzX__TZAUiJlUZYt-VTNklQlMtndQDcaX3djkT_838MoMu5kmoVJ_HELvTe3DBl7iR_Gg49bN9fH2_bW__2t8-FS5MOLYH8SRurN3zp_-aA_G5G8k9HHLQ5suUgHMv9SiSJ_h2djEedDmcTn4meSniT-x61PSSy3DFfEfphXP3mRyLJPYiQ_bn0Nc2-4ZYjMk7F_MHt-4XmTKA-zfMsYiTC-SrxbmZ-kyWT8ccvaMu5CeX-e-EDYO7-86F_XWg7jesvQ8798uIzEo0yvcpEbGfzzcesgGblhLP3DyyuQJaIJCDK3dhYTX-XplMi22qj68leDkLYRHsqHKRXCaIm8OqXjtBH24nxKhRldIq9BSa32Dt4lOQzp85a5TnIRHZ1eTimJbbP3zHIcjKhltep2OXzMQk9E5-IhHE1Gp2F-LW7lrEFsM9zGexYOhnkMPtnGTB3W2uHjMJVtfBb8aeM7SCK_jY9bJmvlG4oka2NEFjbbtQzkzBymTVqdcyy9XUXdi71al5bJvYlTmcn0TvortaBY-tJLADOEG8mVeWbNXMoUZvfM95BpLm9sIOOyxcfnnfBcxGI27WxnqaUUcd1S2F4mdoGlUHsDTY55pTF6jy3HpthCDmuHESVksQEYft_KdRTLdPB4NQxlNOuqTcxV6KuGDsR4FVZtxjp_3ZzEWa3FFw3wV5H6z1P1xeClnnN0J7I6ziGO2XK1C4a6xu1uKSMpgcGXAAKxV5s3rdB2mSY_pZeH0Qv59tJRMklr0E6XalGQr6REBdSHYqTN60-8RmTgbYz7EQTseQWsJd2KokUsrR3by3Ph3R4m_kCuyqIbeTnH1WQ8hjmtxn1VPhVl-jLTyUsVXFYgvgCvrU9Cc1k0mpPPyPPEK8ufhti5Rtr9ao5jdU1UfJxrZZvwFchXbuIoCNScupPngAojQGQYVelD7jib9u9Rq2ceT8BnVkkSNWGSr0R7mdxD54cqfc5ms2MVakglnp97x6mM_3icl2-uRF5vgLRjuT9J1VRYuY15jkXNXIcjgMwsOxS5MDIpUm94BgP9cWur9tOxiCIXZj48VVwfdnRVoj71RuMkzQ2oIPI9z0smcX4qsiE4bWCZrnQ84THH5dLnjpCUcJdYgiOHBIFnYcQRpBCKtS9FNAKbHxQ_qu4KL5dpIcvxPMk9ZhHmur5P4K9JbGRSx7EtX3LbE9gSVHpF3w5E5GVatV48nuRGrAubUZh5f3cnQaDKF1AtT3XldXR8fHRw3ftyVFqjzpLdhlH093gyciWgfPE_uG1JeSU1JhvZxM2Kjx-3vkB5dKW4DmUuwghGyEuiSIwzCXVRIKIMWg7ho6a5ArN7-RJpmgrS1yIKtMmaEbRLOnqQaQ76Qkj30lC29mv6_plOFQ2qcK-8p00azMslgopQcqAGX-StMjRqLJFykIZ5qzrq5RJecF0RtbZcvn3GEvnjWGYQ3cMg9NTEWz7k10BdUC2xC1Tg4PyPS8a7DIjtMvYjZbUWAcXLdubLJMxUrrGYu3y7xKqDOGwfz_JtO_uh9ESr7sXLduYzKb3hiQjjJAYztUmZUi2R9CmJtZPDpNkLIxW_Wkf2KJJTknaBF_lQpkVQbJV0DhhVkSydOGnoTvL2aVyjWGIrXeq2WEi9a2ctSr8WHdS7JUjUqJhaDFqnaRdV1CetQLaMtb8ET_vLobRK-lssX7xdon9V-7SoXr5e0nWdhrUOfZnULYMGSPfboUG9bGcuptZTEXk6WVGCngaHMpAAYEvnwZRmCQDnk_gQsDJfYtAVRRUBbe8uCf2i1lhLmlZysbCZpV4kq8CXhXZ7sURdi61r-rkSbSPmL5fpWqC_RvKMIMDs0yVZwWqSpvXLKaSm-fAySaL1BD5ZjlxLzyTPROwfqoWXlRX9sFOlxh90NpIZGaTuJ3KU7T9CAXWs8HZujV5oE5Tpaq6S3yZP5X6-DMQkUs8_T0QU5o-qKKk9PSu2L-IkHU2Xn0HUMLlXTlRIVMlRBhB6dla82YvyUphqrtKsMEnZIa0m0s_Kh3rXYm_Wa62x7ncYe9HEl724rC2npoqEq_qm9mPUQut0SmVRolZUEv_RqEB_Tvi07b98gC6W_CdR4ooIz8QXqiO-1SBA02aUpJ6OWVDwXI1husPTX4XmPZ30aCuWlJciLcZhIEfq7TlUGj6Ubju9HKy0o0y1ozsHn04f_TTJmhL1wMxrWgmeWUtXcvqTqoXU-hVknjVxOyvrTZ_Tu_QAvcol_SK3WKT-MoWnTrRIyiKVF-nXi7NxWIaT1fVjK-qnFoQuZSzzKmC9Wsc2SavqqfiNuoDNK9uLvVQKACRVgs1WMtdQ-jmJqw9yKceoBBn18nmjLl1bQrqIdTH6ev3bZa2quZZgFCKMi3iq_wsUt1ZU_BRikweVfbHAnCTZOpovEbb6oOcQJ8OgrB0hEmqIfNu4kagU5E0jxqlMReRfBD3vFTOrihELZKxq1oLXSAKj571g_uCXgsge_HcRFBnZJiBkobyXA4gSo5QvBa2s_6tB9ArK-luV_m8ORedFrgGjlag_bYp9lWIMeTFeb5bZz40G-PahyIavnmHHkDTlbhTGty-2co1189FJLfLkaivn1d40L2FVtSq-P81TwBJ38q3R-CQSXiigs5kn_E2l8C1CV7V0yW5U_DubU_cgEjDzH189Leb5V85eS75_Ked5dk7CTP9Dxmdy8KrSYIY0T4W8AGuA2Si5_2wQR288OTWS7idR_im5E-tB-RMpq1r4C6CmfHiDams_iaU3hGdrYPlTGauqNeP8E-rI_6ZAjdlzKqORzN8em7JcvZTrTZxq1-c1SZBR3w5aSa1Vl2WgsryIGwvQr1-YaZW1cnADCcb9EHC4kGLUFoI3Ulr1RiPoq0ooXoMW5WguFLLytCmZDc39LzVTni_IRZ5K__W1eJN95TK8YPvTTNkP48GfE7BdfZJgrbqrLuFlZdf0nMKGbZolk9RTNyigy7sI7Z4l3jBP4iJNV_tpXaOXQkp0IqBnkVSrSG-Wlz43CkexNxRxrjYfL4L9CEqI7EIdrcCLR-WFdj7yQy9XKyiF5KfWLj9eyVxvXxW7VurjdSpltTmlRaFyYwh-qF9q6en9ITBRlsv0sTxb8XHrH8xE3OwSgrDzz-4_COWYdKlJTA4_IYyw1aWcUazeYUxRl1Fio39C3xNf7VFRZNMucWx4wymlXWzbltPF2MFdZoKwLmOIdW2bkC7hjuN0KXUskGkThruYYxOeY0It6AFBJjxhwG45BEiYTXGXMGrhbtkRh5lAiB0CrMix7K7tUBtIkMm7DBFsdjlxFDEl3UIvi3AgJtBx3iU2pqyLTGQpDTmIsoCUdC2GQJSFHXhJFAXjjgn_OhbtIttmTGlCQZaFKdc8juoWwl3L5tCrwgSYq-4zrIwJrSHVDRsIiZILBoS3iDoExIOJVKcxZl1sWhiaZibIsThmFKRBL7sOZghs4WAwJTdBgEWAt8sIhR5gbEL_CGMcWB2ubcEpdM-CVqltAqFlgrJdbNkExDAEAihhvOtwaBkhilUf1UAzNSZaSUv3mnTBrNACp0gZWo03GJOB7lS1zLBlUmCC8QY1uK3JTQRdB4Mjm0CHqMlMp8u4UssGC8CoMw5-B7gsaxe1sFnewVJuScpty5v-WTFdh3k-znZ3du7v79-PRT5MAvkQRvK9l4x2xsAEvr6tJ-a2EruzB3_2B-f73_r730fsyD8-PeAHl9fZxX78vZec3Lhs2727GP_6TKwfg6GVHTx4d_ndr4sfB45_733dGx9_O-ndXX062N7u7U3O79zt7HdT9reTH19Gv7FRsOcNPoEZbrK9Lweff_w4uLgdPfL9n9_-sAfXP3_ef7XZ4_fA_jGKky_8zMIHR5fp1UU0ePzawwc3h4fugbN9nz4Mbs--mj-E__OzEwTfvtz-uuwP_ZsvvvvjiN_5D-fWrYV_3Bx9tkeXB4_ekF1an8zRw_CbeTr-mn0LguNrdPk5cdj3B27e58ejbZn0xz2Kf13_dr93NBkmd9--H4_Z_S_fo_LnNkGO_fnjxwJGKst-KG6xZTslpABGaDhRIKI-fEpyqQ-MqofVDxpi1HnO8hQspPYKvP9IktF3dasEFZvUp1Lk52I8BVb1vtzsJuUGdy7ywxCQJ9WnICo8VITfPm5tlzfRPugAVkKa-lxtt08yeSW9JPaLQlk_ru2EK9L6LnhfL47sGv29_lHnwo3CO3V04OQxlZ1LMRGGit2dmzj8NZFG73DXcFHg2EhK7kkEM9HF8IBT4dk-c01kMpsJn8NrQiR2pMeZEwD8MJdilxAPs47ugNZ412Ckoz_15a9dg9qd3mgchV6YZ7sG6rwjppEnAMV6899QO7SddwirZ2p7JorCgTJQB-G_qiBalVYqIdaHQDvvrDp_cUisLAtahKtH52GsH9V3v7IO_avh6UOUimQAAdQQDQoDjPY7TLXOP7xUBLn0__mOsHoLaglT-9Z54vdFDByp-hci33trqxyQMpy1UuBnKcizFPRZCutZCvYsRXVbS6dZTb_DTb-7-dT7fHPUgUTGA8gyfhPebeeLSOMwG6rRTETeKc-47RqOzasf9mGwy5tbAHm7hvneNBHpNAZ518Am6tQPBz7hqnu2TanvBggiTuAgKnzHxZ5ncsfD6o9pESGkRyQRpsCSiwCbLoWf_YAiJj1pNTzbNjvlWRTVi04JKLvG_nZ_-2R7X_2tuT7Dddc3O4hYdZ8udTZE7M-7scWfONk7NSHgIVRLxlGkr1JAplic81MeDM7cmDHNXamOZT55WZSWnaOHPBXGIEn_3Rx5kZuSBfB4MAxHMg0940wPZ-dEnYvYG00g5647kuCBb0rfc3yXuJbHBOFYUgsgSUiHSJf7Lvdcjh3uSkwgf7ORjXnAAsuhljCdhiNxq-4nZhMim9BX9FXvrurYEEAG7Xf2fD8zHOUQyDHUJaZqpQCeFEfqsyUQSskSDNV4qXunGlX-pk-KFAWPKq1qaIg0GB_KB8iroZf_AR5EF3jQfqQuYBlXSSQ7x5NBqIK3oXf-ZygH-W87ynFk8XmUA69YCnLv7bp3Imn6louJNB1PUN-2fCYD7vuWb9rYp47rm1QKZAY-pKtuQLA0bcoYhRTaFLbHm97JF8NcX0PcSc11-ZzrgkNolNJXxWroBC_oMpfjT8M2RVqS9u26IGoWLSifbDwn-vn0Llz95dRhMapPiepOWjkt_mPiOG93b6vp3ud7J72DzjEEB1d_R4Uye5JlEHnUIBnHUMXcNvJIxqDwoY7wLYRMwgAbCURbCh5nEu6bPlSeKpMEn8QOciDp9H1EPNcCj6TENxtuSKyZG5o1pyNmM64y1ohtI7XEYJT3kGFYdU-ra8lGou7VZECvXCOPHg2RG_lQGjL2a-FyFVdYZD62yHyX6hJbqI7YyfR_IHvP_jczQLE0_6MwoF76AJwFgK7bklIvkBayhBQuzF_OGA58hwSEYkv63OWO5XoUEw_AA8p_iwrhQNCBCt7FMPebU9qiLba0m7bEEDPS4vBklSUbY8iHof7osEb6oo_46-RFHcCfGdifqCt1Kxly5fmwyNR8ARAfiUEEkXACkeh6mKQhgMnVOASCCmnmMNZiz2Astuoj4oFbE-p52MJQ-UA1BLiNIAXAmDOFutzEDoMCCjEfIfBsaYLD4wCZlk8DgoLmiJD6iDQwto6wQNYYINIM6goFy0SuNXCrA3P18P18KvmO4HYwRaxeNen7DTUx1R2oTl8G6mJjZjCjusdey1H0_fwyU5Fp1jlI0nQyzv_tUHiR59qLUohUjFzw3etUjGH0hbruYezLqIEI0sG-bUubC4Rc4vkEccFNyl0kWOD64GI2_PGZxbmQ2PUQprYLRTo34Z1l83l0rcEAnovj2HlagWDtYFd5KuNBPuxYM6SASTR6LHDgepjKbJjoYvxpqYzsuvdqhurqjqq1lZxQ1hNM4jzJDP79HcRZFEVOQohX2oqzqKHut82t5AgHm1CYMCyhrHWpzSxICV2HgxtAjSI8qIeFCKzAdmzb8QPBTCRsB-KJKZHjBk0fwfbiqIFpE5T6cqQ2IYwDCK3wH4ykihevDaLIXKT_nrplBMDsyVkMDaHMCSMIO08zEdOxMXO4ZSGH-9TEkGVI6lDhUkIYUyvWhCHbCXzXk1CimYIKDJ9cGdge4x5u2AG1ZCIIzVX4Vnv0XMUpF1oDLVxaebJd1GnuFnWKyyq7hlN-mg9uqG4t4mHsWU7ALMf2hMuRSwNHBTEwnysgmeBMQLjjvkCWCx5m8iAAKyk0Mpn03Ya1oNJZFNn21RKJ0W8CzXSmX6fhYACmmtsMUr50GuYdRBo5no4bZdrefFUrc-uj0UAQ9WLxul_XKL6PwUigJ9W3JswvBh4k8CbM_zWAaAnMILxonoF2OjWepfpNzLmSMLRNzIHAIwNwGS58nxLbB5RxJIQkZIK7CEiSJFSZpiMxlcSH1D-wfdNhKFCJrSeduayfrZb1I94Y9mKIqiy0cwJ2gNyjNxpNYrV8AuOsL7yrXCaAwWVGppfToRII1PT0jfshTIsp0SIB0xxF5b6Jv1SO0Okv_Og-zvNtyG8WjihZiBVfVIq2L3K1-QnVSDIeSu8Rgkfs10cRB9QUglPEKKAigABEC-5SKONMSCQkFBWmRwUxqUCm6yNmQfpLmWm60nVtm6LmEoLdtlI6t0Y6tz1AG-uURepa5re2OZvOjRfNpKIGAKyRKxeb2_OntIziWxQ676jTtnVQPmpuHWCrraMa8evE_11Y8PX5sqdZ7--pOtdkfJFh1DmOJnqKiMwLY5lP4xeGRHVxBDPfI8b4bIkNgw-2LrFp0pq3O6bvSeF7ULIRm7hMEEiUbMao6UOJHailMsyQCZNBMg-cHhPGIegpd4e6LmhGPJu07wv0jUY51_B33EG01d8bb9pc652Fmyuw74h22sJiVQ5ebTX0hfr6l-ka2pO1NeIsXFubpeMM_-fufvF19seQtRCZz0VaBNWJOwr1FXrw0UzmTzZogwBzyM6JS_zAc7nvBBaiDueuRX1JTQu8Un2RkilsiL8edVwSmEUURhS7pt3coLVrLlp3ziYWn4rMQEZB2dGpfVWgGfdhPizfgHOeyoci9VfrC1XG9orsX13lbt_obt7yjpLcCIHn0r3pn6kt-eLLmqpz5Ff3YmzsuY86gSk6aqi28-LAmFmN5XNy5mXgFWQsO8GRp5DV7hRnCXauYHblk9HOwHF_-yxZ-Hm-9VljiDzXY73fsAmVF5kOv0COWrVYh7_INMmMw1qx53hRz8kGBv0VVsRvIYNuQBe2gX68RsaisUEv8apF7v2SwS1O_q7VhQWOzdbuwZsgyjdn8JlGv4eXVdvVKdEpnqDX9ZZsCFDQ2najG3BktIEJRd9i_O7vf5xc8NGNW_e9WUP2c50thnsdky2cb5uw-ctDQQ060ev6vW74Ii8y3PSbYtZxt8UjuP60sdaW8HLIq40fXW3I65nPtEIo2u_5QK9PYKu3-oBvxfubvJeRUT6qy36Vra3NDDped9KxDYAU2cDEJWtOIrqhrGHdyYw2M67kxThWMwBbjaOmqvMaVTeV_pO3iHHsazr-cfLz6mR-0GeN8XX8hK078TbkKJvy-1cFXyXoNfjxSr7XjsOLnYccEUlOfhtaVQ_0bbSa66DXgT7ezJhvArPRW9hN2D65j3-_lguUmLWHX2e8zcJELmJfpH7LUNczBGsd96SbGXFr7dzuTebJ2PaP-J28NhtIN2uJroNI1lv0-Pvoa9K_vb36XvWgOIo9a4rU1w6rO4H6bLT-2vckDsLBky9xl-qEylX4h7xUvyEmn33z-7n0w8lowde-z_9GqxmL_s1WO4ub6GX7SZY9Szv_i7qeZSh-g9dCsstIeFKduJFpQ1n9lenT76vn9d_6s4he7YtVX6ZXMZEVeKpfy1HxWMtZmr_TZMbGyt_G9GGnGsEPO_O_Be3_ASwEUO0=
```

**Comment by Dullson** [comment] 2022-12-18 20:19
Unable to reproduce, probably related to #5316.
Should be fixed by #5396.

**Closed** 2023-02-12 13:24 UTC
Labels: bug:behaviour
