### ISSUE TITLE
replica wings of entropy

### ISSUE THREAD

**Issue by afulminata** [PathOfBuildingCommunity/PathOfBuilding#2349] opened 2021-03-13 11:23 UTC
wings of entropy and replica wings of entropy in-game are able to be used with chain hook as they are considered to be dual wielded. That means they should be considered for all single handed only, axe inclusive items. https://pastebin.com/uqzEMQEW is my example of a build that uses one without being able to measure DPS

**Comment by pundm** [comment] 2021-03-13 12:24
Duplicate of #1716

**Closed by pundm** 2021-03-13 12:24 UTC
