### ISSUE TITLE
Leech & Gain on Hit

### ISSUE THREAD

**Issue by tainium** [PathOfBuildingCommunity/PathOfBuilding#2156] opened 2021-02-09 11:30 UTC
The Calcs page has a box for "Leech & Gain on Hit:" but the data only displays leech.  It doesn't show how much flat Life or Mana you gain on hit.

**Comment by ppoelzl** [comment] 2021-02-11 03:16
Closing this, as I can't reproduce your issue. You did neither fill out the bug report template nor provide a build code.

**Closed by ppoelzl** 2021-02-11 03:16 UTC
Labels: bug
