### ISSUE TITLE
Stop UI updating/rendering in background

### ISSUE THREAD

**Issue by simonflick** [PathOfBuildingCommunity/PathOfBuilding#1087] opened 2020-06-23 19:02 UTC
**Is your feature request related to a problem? Please describe.**
According to the task manager Path of Building constantly uses the CPU and GPU in the background. On low end machines just having Path of Building running in the background can hurt PoE performance. This gets worse the more instances you have open at a time. 

**Describe the solution you'd like**
Path of Building should only render the UI if the cursor moves inside the window and the window is not occluded by other windows / is actually visible.

**Describe alternatives you've considered**
Detecting window occlusion might be challenging so an alternative would be to pause updating/rendering if the window has no focus. The downside here is that there are situations where you want to update Path of Building even if it has no focus like in a dual monitor setup or having multiple windows visible at once.

**Comment by ppoelzl** [comment] 2020-07-04 14:31
Duplicate of #604

**Closed by ppoelzl** 2020-07-04 14:31 UTC
