### ISSUE TITLE
Cannot save my PoB or generate a build code

### ISSUE THREAD

**Issue by fDerpik** [PathOfBuildingCommunity/PathOfBuilding#3672] opened 2021-10-30 15:55 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Save my PoB or generate build code

### What is the actual behaviour/value?

Getting a error message

### How to reproduce the issue

try to save a build or generate build code

### Build code

```shell
cannot do that
```

### Screenshots

![obrázek_2021-10-30_175417](https://user-images.githubusercontent.com/93379819/139540278-fe833fa1-f397-4055-a6ad-cb4466ada81c.png)

**Comment by Peechey** [comment] 2021-10-30 16:21
Duplicate of #3645. This will be fixed in the next update.

**Closed by Peechey** 2021-10-30 16:21 UTC
Labels: bug
