### ISSUE TITLE
Does not install the necessary vcredist like the regular POB

### ISSUE THREAD

**Issue by kidsmeal** [PathOfBuildingCommunity/PathOfBuilding#1109] opened 2020-06-25 17:25 UTC
Trying to install the community fork on a fresh windows install gives an error of missing msvcr100.dll
Regular path of building installs the needed files with its installer

**Comment by ppoelzl** [comment] 2020-06-26 08:04
Duplicate of #922

**Closed by ppoelzl** 2020-06-26 08:04 UTC
Labels: bug
