### ISSUE TITLE
'Account is Private' after patch bug

### ISSUE THREAD

**Issue by vietknight** [PathOfBuildingCommunity/PathOfBuilding#8360] opened 2024-11-18 02:46 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

Import/Export Build -> Type in username -> Start -> Characters should load

### How does Path of Building behave?

Import/Export Build -> Type in username -> Start -> 'Account is private'

### How to reproduce the issue

1. Import/Export Build
2. Type in username
3. Press 'Start'
4. Tried with/without special discriminator value, still did not work
5. Tried with special POESESSID, still did not work

### Screenshots

![image](https://github.com/user-attachments/assets/02926640-af45-445d-b5d0-d2404f66bf87)

![image](https://github.com/user-attachments/assets/c947bd09-616b-4008-b5ab-56205148d59e)

![image](https://github.com/user-attachments/assets/991cd6a0-d67b-4e9d-9d87-5aa8032451c0)

![image](https://github.com/user-attachments/assets/ec7e8bef-50d4-4d44-8093-d4d9ba2812c0)

![image](https://github.com/user-attachments/assets/1fb6b565-a065-4a21-9671-7e3f403c4d7b)

![image](https://github.com/user-attachments/assets/43df1ab7-7f2c-42e6-9bf9-c0369a8c3569)

**Comment by ciceroripi** [comment] 2024-11-18 03:32
Same here.

**Comment by Regisle** [comment] 2024-11-18 03:45
If you open the console (`ctrl` + `~`), you should see a 403 response code, this is a known issue and is being looked into.

**Comment by Sentinent** [comment] 2024-11-18 03:56
I did some poking around and the issue is here: https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/dev/src/Classes/ImportTab.lua#L452

`local realAccountName = response.body:match("/view%-profile/([^/]+)/characters"):gsub(".", function(c) if c:byte(1) > 127 then return string.format("%%%2X",c:byte(1)) else return c end end)`

returns `<account name>-<discrim>`, which later gets passed to `/get-passive-skills` and `/get-items` that causes the issue. A quick dirty hack of adding `realAccountName = realAccountName:gsub("-", "%%23")` fixes the issue locally for me.

--

Somewhat tangential, I think support should be added to automatically urlencode the "#" to %23. Much more UX friendly to be able to enter myaccount#1234 instead of myaccount%231234

**Comment by OcularDisease** [comment] 2024-11-18 06:55
Same problem here

**Comment by franciskong-lfasystems** [comment] 2024-11-18 07:29
Also having the same issue here.
Was working fine last night.

**Comment by LocalIdentity** [comment] 2024-11-18 11:49
Fixed now

**Closed by LocalIdentity** 2024-11-18 11:49 UTC
Labels: bug
