### ISSUE TITLE
PoB closes after 15 seconds after launch

### ISSUE THREAD

**Issue by Yokoharu** [PathOfBuildingCommunity/PathOfBuilding#2013] opened 2021-01-22 15:31 UTC
* **What happened?**
PoB closes itself after ~15 seconds after opening. It tries to check for updates and then it closes.
* **What were you trying to do?**
* I'm trying to open PoB.
* **What steps will reproduce the bug?**
* Open PoB.
* **Does it reproduce every time?**
* Yes.
* **Provide a build code:**
* 1.4.170.24.

**Comment by h333n** [comment] 2021-01-26 00:32
Had the exact same issue. because my old 1.4.170.18 version didnt auto update anymore (SimpleGraphics.dll freeze), I downloaded 1.4.170.24 manually, deleted the files in c:\Program Files\PoB Community\ and copied the files from the new zip inside. This leads to PoB crashing after 15 seconds. When I copied the files to a new folder in C:\ as a workaround it works for me and I was able to auto-update to 1.4.170.25 successfully.

**Comment by ppoelzl** [comment] 2021-01-26 01:03
@h333n You can just use the installer instead, you know?. I'm not surprised your PoB crashes after you've manually copied around some files from different versions. Not recommended at all.

**Comment by h333n** [comment] 2021-01-26 02:53
@ppoelzl why do they provide a zip file on their release page then? I do not see any specific reason, why a tool like PoB would need any specific registry entries or files outside their own application folder. And in the end my non recommended copying worked. I just wanted to give the developers a hint, what might reproduce this crash.

**Comment by ppoelzl** [comment] 2021-01-26 03:17
@h333n I provide the zip file for difficult persons who think PoB doesn't need any registry keys 😉 Also for users who would like to use PoB in restricted environments. After you extract the zip archive, please leave all files where they are. It's in your own best interest.

**Comment by ppoelzl** [comment] 2021-02-11 01:55
Duplicate of #1843

**Closed by ppoelzl** 2021-02-11 01:55 UTC
Labels: bug
