### ISSUE TITLE
Maybe don't add someone's Patreon bait into the main build

### ISSUE THREAD

**Issue by noisyreq** [PathOfBuildingCommunity/PathOfBuilding#7943] opened 2024-07-25 16:01 UTC
Merging the 'trending build list' into the master when it's literally created by someone in order to shill their Patreon is an utter joke.

![image](https://github.com/user-attachments/assets/d1b7185a-d5b6-4a3e-9616-9013bc2cf4d7)

![image](https://github.com/user-attachments/assets/4729c920-fd2a-4e86-a2d9-c0d535b413f8)

There is absolutely zero need for this demonstrably worse version of poe.ninja, and that's without even going into the logistics of outdated PoBs, clickbait titles and the myriad of other information that accompanies builds in order to provide context.

**Comment by Wires77** [comment] 2024-07-25 18:51
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7944

**Closed by Wires77** 2024-07-25 18:51 UTC
