### ISSUE TITLE
% increased Non-Curse Auras from your skills on Enemies amplifying your own stats

### ISSUE THREAD

**Issue by lunarmint** [PathOfBuildingCommunity/PathOfBuilding#1167] opened 2020-07-09 21:24 UTC
The notables 'Bannerman' and 'Revelry' which has the effect '#% increased Non-Curse Auras from your skills on Enemies' also amplify your resistances if you have Purity of Elements, as well as your cast rate if you have Haste, while it shouldn't be.

**Comment by lunarmint** [comment] 2020-07-09 21:26
Edit: my PoB code to check it out
https://pastebin.com/ZCzrnq4t

**Comment by LocalIdentity** [comment] 2020-07-09 21:31
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/1152. This should be fixed for the next update though

**Closed by LocalIdentity** 2020-07-09 21:31 UTC
Labels: bug
