### ISSUE TITLE
Crashing right after startup. Issue with ntdll.dll

### ISSUE THREAD

**Issue by tr1pped0ut** [PathOfBuildingCommunity/PathOfBuilding#2718] opened 2021-05-02 21:57 UTC
* **What happened?**
The program starts, and once it loads to the skill tree, it freezes for a couple of seconds and crashes. I've tried reinstalling multiple times, restarting computer, updating the OS (Windows), and updating AMD drivers. It seems to do something with ntdll.dll . 

* **What were you trying to do?**
Use the program

* **What steps will reproduce the bug?**
Opening the program

* **Does it reproduce every time?**
Yes

* **Error log from Event Viewer:**
Faulting application name: Path of Building.exe, version: 0.0.0.0, time stamp: 0x606d1b4c
Faulting module name: ntdll.dll, version: 10.0.19041.964, time stamp: 0xb7db0838
Exception code: 0xc0000374
Fault offset: 0x000e6b83
Faulting process id: 0x24f4
Faulting application start time: 0x01d73f9bcee91fc8
Faulting application path: C:\Users\<Name>\AppData\Roaming\Path of Building Community\Path of Building.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 662eff2c-44ed-436d-b0d4-eb7e3fdc9e97
Faulting package full name: 
Faulting package-relative application ID: 

Will provide additional details if asked. Thank you for your time.

**Comment by ppoelzl** [comment] 2021-05-03 10:41
Duplicate of #2701

**Closed** 2021-05-03 10:41 UTC
Labels: bug
