### ISSUE TITLE
Damage calculation.

### ISSUE THREAD

**Issue by slaidslv** [PathOfBuildingCommunity/PathOfBuilding#4195] opened 2022-02-19 17:38 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Hi. projectile medium cluster jewel has passiv skill "Follow-through", it says "Projectiles deal 15% increased damage with hits and ailments for each reamaining chain".

### What is the actual behaviour/value?

Damage calculation on projectile hits work, but with aligments dasnt worke. 
Cobra lash, Divergent quality has the same wording "Projectiles deal 15% increased damage with hits and ailments for each reamaining chain".  This damage calculation work with hits and ailments.

### How to reproduce the issue

Use projectile medium cluster jewel with "Follow-through".

### Build code

```shell
https://pastebin.com/NaGD1FXq
```

**Comment by PJacek** [comment] 2022-02-19 18:21
Duplicate of #3806

**Closed by PJacek** 2022-02-19 18:21 UTC
Labels: bug
