### ISSUE TITLE
Evade chance in calcs not accounting for Raiders Avatar of the Chase

### ISSUE THREAD

**Issue by Regisle** [PathOfBuildingCommunity/PathOfBuilding#239] opened 2020-02-27 05:07 UTC
Chance to evade on the side correctly uses raiders "more chance to evade" but the calcs tab does not, as seen below
https://imgur.com/zcO29K5

**Comment by PJacek** [comment] 2020-02-27 13:51
Not a bug. The "Evasion" section only shows evade chance gained from evasion. If you look under "Other Defences" it shows the correct values. 
![evade](https://user-images.githubusercontent.com/18018499/75450711-9688a180-596f-11ea-8370-da199d6a1ca6.png)
Evade chance on the side gets compacted if it's the same for projectiles and melee. Try allocating Arrow Dancing to see the difference.

**Comment by meatballing** [comment] 2020-02-27 15:05
Unwavering Stance and other sources with Evade Chance affects the Evade Chance calculations though, so it is not consistent. Melee and projectile avoid chance is calculated considering evasion, block and dodge, so it doesn't represent melee or projectile evasion chance either.

I would propose replacing Evade Chance with Melee Evade Chance and Projectile Evade Chance to make it clearer.

**Comment by LocalIdentity** [comment] 2020-04-20 02:14
Fixed in 1.4.169.1

**Closed by LocalIdentity** 2020-04-20 02:14 UTC
Labels: enhancement
