### ISSUE TITLE
Ynda's Stand, Studded Belt not calculating Ward gained properly when Defense catalyst is applied

### ISSUE THREAD

**Issue by Vagaqt** [PathOfBuildingCommunity/PathOfBuilding#8132] opened 2024-08-07 22:46 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the value from the calculation in-game?

In-game i have 20% defense catalyst applied to my belt. Now the belt states "Gain Ward instead of 60% of Armour and Evasion Rating from Equipped Body Armour". In-game i currently have 3836 ward.

### What is the value from the calculation in Path of Building?

In PoB, when catalyst is applied, or when the catalised item is copied, the value remains unchanged. I have 3230 ward when equiping regardless whether i have a 50% or a 60% belt equipped.

### Character build code

```shell
https://pobb.in/6mX4MgMqa6b3
```

**Comment by nofate121** [comment] 2024-08-08 08:13
Duplicate of #8062.

Looks like it is already fixed on dev branch.

**Comment by LocalIdentity** [comment] 2024-08-14 14:12
Will be included in the next update tonight

**Closed** 2024-08-14 14:12 UTC
