### ISSUE TITLE
Implement Low Tolerance Notable

### ISSUE THREAD

**Issue by dclamage** [PathOfBuildingCommunity/PathOfBuilding#440] opened 2020-03-10 08:35 UTC
Second mod does not parse:

    +8% to Damage over Time Multiplier for Poison
    Poisons you inflict on non-Poisoned Enemies deal 300% increased Damage

**Comment by ppoelzl** [comment] 2020-10-26 22:35
Duplicate of #291

**Closed by ppoelzl** 2020-10-26 22:35 UTC
Labels: enhancement
