### ISSUE TITLE
PoB will not open 

### ISSUE THREAD

**Issue by LordBumi** [PathOfBuildingCommunity/PathOfBuilding#7456] opened 2024-03-25 13:08 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

Trying to open the app should get PoB to load 

### How does Path of Building behave?

After updating to the latest version of PoB , it wont load / the app will not open at all.

PoB will open when downloading previous versions (eg 2.39.3) and then procced to crush after the update is completed .

**Comment by zao** [comment] 2024-03-25 13:10
This is probably a duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7431, take a look there to see if it seems familiar.

**Closed by zao** 2024-03-25 13:10 UTC
Labels: bug
