### ISSUE TITLE
Support Seeker Runes Notable?

### ISSUE THREAD

**Issue by Nostrademous** [PathOfBuildingCommunity/PathOfBuilding#344] opened 2020-03-09 11:08 UTC
Now that PR #328 is in dev and we have Brand Attachment Range accounted for, do we want to add support for Seeker Runes?

![SeekerRunes](https://user-images.githubusercontent.com/1735956/76207719-b2444100-61d4-11ea-8149-470b81f7727c.png)

**Comment by ppoelzl** [comment] 2020-03-09 11:15
If anything, only for completion's sake. It's not a very useful mod to have simulated.
On an unrelated note: We don't know what the brand's base attachment range is.

**Comment by Nostrademous** [comment] 2020-03-09 13:30
I can see them adding a "% increased damage per 100 units of brand attachment range travel" in the future. :P

**Comment by LocalIdentity** [comment] 2020-03-23 02:30
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/461

**Closed by LocalIdentity** 2020-03-23 02:30 UTC
Labels: enhancement
