### ISSUE TITLE
skill from corrupted Prism guardian shield reserved on life instead of mana when importing

### ISSUE THREAD

**Issue by XXXASSS** [PathOfBuildingCommunity/PathOfBuilding#1712] opened 2020-11-04 09:30 UTC
![111](https://user-images.githubusercontent.com/73935865/98093832-0960f980-1ebb-11eb-9e13-7f76c0d5695b.jpg)
![222](https://user-images.githubusercontent.com/73935865/98093836-0bc35380-1ebb-11eb-8705-be67a86afcec.jpg)

**Comment by ppoelzl** [comment] 2021-01-01 18:38
Duplicate of #1339

**Closed by ppoelzl** 2021-01-01 18:38 UTC
Labels: bug
