### ISSUE TITLE
Bug when trying to search something with % symbol on it

### ISSUE THREAD

**Issue by bsides** [PathOfBuildingCommunity/PathOfBuilding#2532] opened 2021-04-15 04:58 UTC
* **What happened?**

Error like in the screenshot, specifically at file Classes/PassiveTreeView.lua, line 795 - attempt to get length of local 'NeedMatches' (a nil value)

* **What were you trying to do?**

Search for any item with the percentage symbol '%'.

* **What steps will reproduce the bug?**

Just search for something and add a '%' on it.

* **Does it reproduce every time?**

Yes, just press esc, type '%' again, it will appear again.

* **Provide a build code:**

2.1.0 (2021/04/15)

* **Screenshots:**

![image](https://user-images.githubusercontent.com/87631/114815204-1f3ce980-9d8c-11eb-92f2-42f9ead0daa5.png)
![image](https://user-images.githubusercontent.com/87631/114815167-0fbda080-9d8c-11eb-9e4e-10adb6bfbcf7.png)

**Comment by pundm** [comment] 2021-04-16 08:33
Duplicate of #2494

**Closed by pundm** 2021-04-16 08:33 UTC
Labels: bug
