### ISSUE TITLE
Wordwrap Notes section

### ISSUE THREAD

**Issue by TuRzOp** [PathOfBuildingCommunity/PathOfBuilding#7643] opened 2024-06-11 03:54 UTC
### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Is your feature request related to a problem?

It would help the readabillity of very filled note section is the text box was able to wordwrap. Right now this is impossible and some text line can extend multiple screens width worth.

### Describe the solution you'd like

Have a button or a keyboard shortcut to enable/disable wordwrap in the "notes" text box

**Comment by Nightblade** [comment] 2024-06-11 06:00
Duplicate of #1693

**Closed** 2024-06-11 06:04 UTC
Labels: enhancement
