### ISSUE TITLE
Copying an item(ctrl+alt+c) from the game and pasting it in PoB is broken.

### ISSUE THREAD

**Issue by henbe** [PathOfBuildingCommunity/PathOfBuilding#6124] opened 2023-04-24 19:40 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour in-game?

Explicit values should copy properly in PoE.

### What is the behaviour in Path of Building?

Explicit values do not paste properly in PoB, but do import properly via character import

### How to reproduce the issue

1. Copy a crucible item in game
2. Paste this in PoB:
Item Class: Rune Daggers
Rarity: Rare
Phoenix Gutter
Ezomyte Dagger
--------
Rune Dagger
Physical Damage: 20-79
Critical Strike Chance: 6.30%
Attacks per Second: 1.40
Weapon Range: 10
--------
Requirements:
Level: 70
Str: 39
Dex: 95
Int: 155
--------
Sockets: R-B B 
--------
Item Level: 81
--------
{ Implicit Modifier — Critical }
30% increased Global Critical Strike Chance (implicit)
--------
{ Prefix Modifier "Mad Lord's" (Tier: 1) — Chaos, Caster, Gem }
+1 to Level of all Chaos Spell Skill Gems
{ Master Crafted Prefix Modifier "Upgraded" (Rank: 3) — Damage, Chaos  — 10% Increased }
53(45-54)% increased Chaos Damage (crafted)
{ Suffix Modifier "of Disintegrating" (Tier: 1) — Damage, Chaos  — 10% Increased }
+36(34-38)% to Chaos Damage over Time Multiplier (fractured)
{ Suffix Modifier "of Finesse" (Tier: 1) — Caster, Speed }
31(29-32)% increased Cast Speed
{ Suffix Modifier "of Virulence" (Tier: 1) — Damage, Chaos, Attack, Ailment  — 10% Increased }
47(41-50)% increased Damage with Poison
30% chance to Poison on Hit
(Poison deals Chaos Damage over time, based on the base Physical and Chaos Damage of the Skill. Multiple instances of Poison stack)
--------
{ Allocated Crucible Passive Skill (Tier: 5) }
30% increased Damage over Time (crucible)
{ Allocated Crucible Passive Skill (Tier: 3) }
22% more Cast Speed (crucible)
10% less Global Damage (crucible)
{ Allocated Crucible Passive Skill (Tier: 1) }
10% increased Explicit Physical and Chaos Damage Modifier magnitudes — Unscalable Value (crucible)
--------
Fractured Item

### Character build code

```shell
eNrtfWtz20ay6Oflr0Cpam8lZUnGvAdee0_pLSVWrEiyvTm3brkGwECEDQIKAFpWUvnvt2cAkgAF8CEqyWbXceKQxHTPdE-_54GX__NllDifdV7EWfpqC-26W45OgyyM05tXW2-vj3fk1v_8c_DyQpXDN9H-OE7Mk38O_vbSfnYS_Vknr7Y8uuWUKr_R5bsJKvIBUN2qtBzqLD1XH7P8JAtfbf2QpXrL8VUaxuXkW5CoovhBjfSrrUuV3uh8y1FFoNPwYPbADCCK09A8DIYqV0Gp89em971xmZ1nIbSJVFIAupGK06ss-KTLkzwb3wJVMJLPsb6rWp2dX7y5vG6MLU6bYwPa_vbyIlH3Or8qVekU8NerrT1gkbrRp3EJqFQyBjzEle6u57mukJhtPV8Itz_Oi_JQjeDjevBXt1qHUxC-S_nsH9EHdJHroyjSQRl_1gd5XB4MVRrMOha7sg9y_dbn46SMb5PYzEsNgXZ7yTl9gB65bl_j66xUyeHF1ayt52GyKwiTxCNsMVg2m6jeDt7H5XA_AQav34kBPbtJ41KvD3uRxUWWNuEod6ncpSAMGBOOlwDOiRFmEtFdyRAThKBFA37YMUaYS-btCsFdROgylrZBXe4RvutSFwna2-_BOEnAYjQhe-fjUhc6_6zKuD3I3vYH2ciP0_b0rUjRXq7Vm6jSkksVxuNiiqFX3M9Vqg6yYgXBMi0vdA4mrFwL4EoHGVi9dftYE_J1HOnVW65FRw2w7mgeR8fR1art1kb8uAFdgl6u1vIqGycrtiwbhrVfni_1z62WqFchD_WXme3otxeAsNkSsV5zdpbOyECCLEDYasm8_hF-zowNWM4ca5eOTi9m2k-lAJPEXcaFYLzXkA7vizhQybn6Eo_GI_BK1-qTnnWIwLjJfoG9GZYp2LQ-aOzCMPqgj-Nc9wESIqjoN3ZJ2NsjWP9-Lz1UWdEL6UmXLFLNho_y6IIoJXhhWp-lQUMGFyJ-m-bW3DfCm0VdGJBL0EUTT_mJXhlm1k2t06tEHlVnNzqte7yfdSfxLl4E9lrrYHgCEeilKhtRjoTIenngZmx6Y3z9DS3DTesmwwlfhLeD30ysBjDPObZLKIbolXmeBHe7CEk3F5HcXehlu5nYb69Tnd_cXw1jnYQNbshV2k_GdqBuVwG1jG_CNyegP4xv99jFkpWIW5Mv71Uerua11h3TZ1U0DTTm_f6m4lgF0GQW65cADTE5QIR6PldYkPFkH02-k6wJt5ePsvHMbUq52MRVzZtUULbMx1Th-qUOx0HLqeFe_7efQPI6RwJxFwwsSbpAeiH2ylIFnw6z8EavCmI7WR_ianx7C0bETP0cnOctcpCQCMSN4Eiw5Y3fgOQ2dZjyRY505Q5mjec7IO7SAGHlXuYg5rvCaKFvX52YWesH1PQ6tWkl4RyMwwjcgC1JnGczy4J3-4PDY0j_VsrlbMN2hun258F3MPqhqTcV67WGMGhGcu9Qcp3-cr8y_lbzlTo4SsNxbtRhvo-VIbq6uY5HYDiL4lCVyvmo73RyfX-rz0LTwgnrmPqdymOVlhiM4lbVqKqU2WbEk96WU2iVB8PXICTHKkl8MBWvtpq_vtoaqRyCyHL4IYX4G4KxDyoMP0SJKj59CKrxbTt01-Ni23Hh3we9I9s75FU_j3We5ZNhwm-FHcxxnJQ6f7VV5mNtiXv53FYbzaez0W2Wlw50Vu4FQTZOy1NVDE3pxaehpixyGYQkoVaUkkAFJPIUVVi43CcyQJxtWdBLrZIRiMZB9fVgUlCscEVCk0AKV2LkU5e5lAoeQjoRuL4KMfZpwKir3bAa24FKgsLOwFl6Oy6d1NYrR3ERfPDHUWSKjkBYmduK6tHx8dHB9dm7o3rSmiDFpzhJPqTjkW-KadX_Qbvqllfa-g-nGPtF9fHV1rtY310ZqENdqjgpDFOTRN0WOpxWQ2P4aNtcgXQE5QJsthVkCJMCUzeuWYN-TEdfdF4CvRCABHmse8c1fb5kUFWHJjgxQt6HzdT8-hFVXu_ATL4Nnno4Zeut_VhMybOXHPNwASyIrkp6e66fLuFECbpSQCgSR3Fg7MPiKTeaVbVawJcgANMS3C-Y79p39-OwRdQ-BNXDfuCqKtkHXT9dwFVbhe3lavW0H_xQB6qX9uphP_A0Hs9SuzLQjWXaagGmH-q6LijNXpwYN9s7s0eJnjbpR_imHOq88t29mM7BRk2aLFScPPbHZb8aN1os4JUtJvRwyDzrB63S4h4azLMFlqiVGvYwtNmmH1WVTfUaskWgVczVy786gFswBXWa0sP-6ukCJkzStR7668cLlMTa373PWRxWUXyPusw1W2QwwNFvjsZmJJujmc9VNsd4bIKh3vmun_aDv4VMNi7vO7DYkGg1JEapNsNgdGszDJfzgcQM9nJxCGHt16GONDB6oQGbtlkwv-U4PQQnVy6Y2xVR2WF1K8KMtLVwVaa8k9K1MVYCWld4F8lw1WQJIvBFpwuindUwTdPHUwi5zRJklmyG8EEleyM6s7JQaXhoyl8bEmqqZ-NbQDYZ2ZuucHU2pfNYXz6fJBIvbexWQDKUlyd6VOzfQ1Z8bLzT3JKnsoytg_uyTqAaMJPuQh2pcWJ-_3GsjGExaxTNn19XuzjSLB9NF0UA1zC7M1axQmliyQKczevX1ZO9pKyxmf4mDKvYU4_I0onsb_WPdm_G3mzYlmToOAahiNMgGYf6LK1rBvXPifLN2My2FJNrTnlYJJkpcWp1CxOBt-YxTzv-20sYXw18kmS-SvAEc0U1drdaj9G0B4PHJKbX2iSdKoE4ODZi8nNF95mNEC0Pt5wbPTLfzyERCyEBf35WAleeG9Y8t-MxHOxGY0oL88TZxLYepkkOTfVxNg6nxvD8qQisZ9kkR2_SlhFZl9SpuPTjWp1eg8O5G-rUqfA4DR18CrIPIZVScf7oCX03TlKzHGWd9SPom_RfEfSywrtcW9AjdQXY8Nl4mAeaYmCfiqenMGf60RxtQ6_OyQruqfVhD2KGWdzwaFU4jD-Dyd43tTlwqY-RE4vAmWJ4ajrt4oQOqzTr0WR2YVmdxrO0uI1rVj81fWdpkGsF_vcJJrMf1zq01jicKZI1TcDGDhNtZAYQWsp5CI_LOLpvcXrPlHVTVWpct7xQeRW2rGAaHmBsCsAShl-Mc4AE1XEgYxmtbCjQf6Lf_KvI2HLttnN5qIrho93NQwyrM9nCOhb4D2PsqYZksfyd2VrJzCR7MT7w0fxdgGp1Rp8rGHqW6GnF5T-G08YslfeP5u4c-OocrQCdLHKOEt0oJP-7M9Yy7jxOwWHOxcOrh6cQryfhm2jvJkvvH2K0yHo81oIZmcO6voOqEJgZeTiwuUFf3cahzi8SGFT419KHZXPzLi5VsolCPECwukpMQf8wju5nWblZMoZWyG91kKsN8rGHGNbKbmvYVcOtVeN5W6-HICdQod4g1OpEszp9FtyZwD9VSPkuA82OE32oVdhN29qRcyfKNVSjBncs_NfQ-Xe2CuG9M1nue3xJcyn7j7Pcj8NQp5dxn3lYW866ca4RUU_gncv4d6jmvMtiU5yIb8fJpkWAXlRruHyDw2kheWqC7dG8QJmtgY-m9CGOdQ3kUTDMnpw0Y4qS-9lOicfX5roRrTGPFQanvSXjKYuQmxP5NvVh6OEmVNYofj8yT3INoUJeHyfVsw3dRXdAjlakfQW8a7ChxuZM0DlNfL-HkyjAEQTm0DLQ9oK4Lw6zW9CqG3tK2jkZx4Xedq5UGIPXOlG5_yiv8pQp7dt0GKc3j7H-E8ivZv-r2f9q9r-a_b-u2a8_XunSbuuodnOYj9e51pNNGxYvqvdLwJfmjRf1nv2RWdTM7-sdmq-2fkUu9dg2p1Kw37Z_xUi6aJszF5lv8AzRbUyJa75xxrDcZsIV1LR0BeHbyJW2JZaeSwAL5vaZh7epgG-_AcFZaLZ4YIw5NId-4C-GoSmTZJtK1_O2CRfwyJNMblPGPLKNmcvFNuVYiG3uwpCgCcZomyCCYKwupe42cwmR2wSwYvNUCvgFAXJqOudMGqJgiMwOCv6GXgkM1zNDA1i2XRMnhJS2PXy2JMFn-IV63LVtDB6CgXDsUjMQLDgQyiXF0Bd1XdMee9tAHvQOvyMOnwWQSTzJYcjm_MM29ITdbSQE9aA9sR1ibpoT6LbmuSTQhEsJ9BBhBss9sV0z1rIeiKWmP-xBH650gWTpcYMMI9cwhwF2z370BDHDZmibYQEDQFJwb5shBD1RzxOGQA8GD78Ld9uyDJmxIMsOYL9neG5mhBEEbEKYIiBYYkM1YnybusB009yzHIBJQ0iiigxkCAN6GfCQb8MzGCKwBLDAJNNtxjEwlREKaDAh0CuHAcPvHrFjoQx-oQhZNAS4gRlj2x6Bv0BogDyQAmjIiQA0lHowYOga2EaxdA07QTIMYRRECMSTWGbTbSKRIUpwmD8Pw8C4ANmDvwSQBDPFpGs6k1agXAECaOgCRmFEjEhiDoMTHAaNsJkwjBlIEQikBGJcCrzHhrwtpwSNbNxYY_LmYKKBuN649PbydWX0hmV5W7x4_vzu7m73VpXDLNJfwALsBtno-S0AgVrvWPu2Y9A-34N_9m_ODv3E5_vp3kl48eV0vHP-5l9H-KoYJkMuro_5l6sfon_dXov9j0dZuvP-oy-vRx-jt-L6gziIDt99__ngM7-Px_7Zl8u989Pj7y8-4A_He3vRh4L-eDxU73-498ufro-z4Mvxu8vR9--ukn2ZXfzv_s_Hd-zDBxrRww9Hx8enLPm4M05vP5x8BhZEwfUvH9999zbQ4d0v-YE4Sq72rq6_xJ_eyS8331_sFB4_P707Pf0Ynqfq9jiK6Uf-w08x__z2p9floc-8wx_f3_sYj6OfA-jl-_ur18Xns1-Cz59-ycWX0_2fA_dtnHz3hnllcsWvT-8v8Ekm1ccf3yOaH_xrP735fPvduzg_uTs7vzn-aZ-Uw3d672LvfbD_vzfHN_uX2f53P77d27s6Oz66ORrtvX-7_93d26P9y739s73jn_eR-PL99_TnC3S09-F9kX34QMi7q1QcnB6m5PPrDzuvM7V39eOryipPZu9ldc6pqP1X9c1aPDPXVqMgGi8r3zI5m9nR0NjCWUPU166WrylC0tfQ2o9GQ9zb0FizWcNehFbjGghlf8_2uNe0YS8t1jY3Grq9RBtj2mBOb9fG8jUQipkPnU0SfAG3aD2o8Zvmww9Zqe0z8-Pki_Wq5iBUfUTtqsxN4vRLlo1-erW1g6jYBeNW_VDvc-T13sZSlYcxeNfc7qudhACm4b8AUlJ3V6BqPl7aIKP23ebzZL_luNDVDSHVmrf9ubET0jS1uyBrY3KpzMrbC-dy7_JoACnfDQRVzkkC6ZtOBwd5PCqy1PnOHMsbvE3jn8faOTt84YQMvBcJAqki-Ch9MI4ocuEfUGWwplxpjokCCUbEYzJS4EC5q2TEQqVceDqww7DEv3AoGZyNbpM4iMviheMOnrG_O2U2KXeaM1aOWax1Zhc7DfjfTZ5ab1kZVdtDHbO9fODuEvp3s2w1Oe3sVMesJujs0RcAUkXV3kzyeRbaW76c3PwNecUu26p3itZi0NsCL20xOQxpo8LZFHyuDh5We-dMV157Pt7-cPbj26PBfj4ugYZLXZQ5ZMml83_BudJ_OIjuAsv_4UB8mWvgzdFN9v8Gk_OW9Xy91upmrF8AyTfgTQb1UccXzl4BIWY5dL45NDvGnbsYPkPyUA6_nbX5QRXxSDnfVKLkXJnjwI3H-yqBGBqeXw-1cw0jK7P820F1ng-YO22HHo4JpvxS__zCwe6guuYIBmhOaA5ex6PYAJeZgWtJxK81t16g3w51mplW5h6IGEYPM2044oT6kzkyCWLhlDAmVX0zy5cVtTMceH0cFTdmKMj6KGqODS4qt1yYFrml31G5dg6qo6eA0b-3kOf1idbBKahilsfBHyapC1rQpS1Yt7TbIaIOi3M4Lj4Be-OkAOnJb01GBzqrnRMFWU8ChndQFYlAJFxUf94Hra8vAIFgB-RjF2JNPKgPDVUt6y89TRuWTLuBCBnBgSRC-BpiM4ypdn0_4DRwFcTujAeQf8D_PUyQH4IVQx4OtAiCkDO_ZcmkO6h3oFv5rn0HkLpj_pw0pL9t8_AATF5gzzQay1edMHTg39O4HDwT1hzao_ILjeIzhJtYJseHnKr8UUEOnhGCzdPJIUvnUplzsYNnuNlNdf7LYFrboP4a5CoC1fjtGecGYcs6_5VkeEELvrSFWKAHokMPzu1Kk7OfZ3eDi_hm51hBLAxGowjiVJdTJYD8plcJqHD5TAmwy_qVgHoENZVAQHDoMYo1Jjr0pQt-OoqIr8F1RyFkUFp4PlJa4YCTiAiCpOcrT2AKCbCQCLeVgHUrwT78OXEuG0rA55SAt-WsFrAoz0ZGEQqnNCufRtDMJRsTgabNUKAGuQXtsJcsONXtBINfI3OafpwbsfTwA7F8hugKmoMQ69Qc4nZrzlQTxGPo-qoq5hafDlU5UHlujjpdma0cwXBgNh7FKUzl93lcNKU60hSFQcSxh2mEXAZpOeU4iATGyg1YKIQWEZM8pIgFkK1jFIZRiEFzAiVZELakWvA-0w5y3ZRp2pRpNGBuUz6r2qNjjuVbUYDUIP6kneo4e0tKMV_R6jPc7GBOyAak1b3dS2AvFBhQ1qE3NhSsvI-F7HNJU8lmqIW-MVjTZhzEfqJ_2wvDwrFKR9v0GFUzGlY0GqP-bqvhtXTyv01JFrSQS1t4C3xSp56Bm0_uixGIq5GYAyO65cNcECGEA8jwApPrKUZQ4AnOwT8EgQolBFNhRJjPqCYupON-oLTmQRgoEYQQclHedh64HfmjVqbXnHvnbmi3AIFSOu_NUURri-nS1FH0po6V-5nIprXJ1RHKPyFdXC5wXdNIOqbxYpjpNP7ifJfdD2yi5RwkY1PGfziTTOgQ4UhHEWaQvgviehwyd8lcJigTAoc6DEOBlQ6xrzGXEgJm6fqc8ABpGc7PZMMqus1pJTMDYm2D59RZkVOtTMweYwcaGLPWem4zJjt6p7bDLYRGUEYKBGUO6iavclLca7MWAKukyCYYnmHXSFkdXi2CGir4jFumtlo8GaAuypy4cN6mxa1Wn8wakHMSR0Dbf5aR6zQ_cqH9mZSjKhb3iq_gEJMKl7ihoBjElPlURpRFKpKRgmAWRWGkRcg1j8BgKamw7wY8YH5IPYQJbft7tyG-jLYD1bb44l7xXUEYW7JRhfYri6ENRw_1F-AGsG1lMGJtpGlVb7avCkx12Fr0i6a988ucWTrIRrdZAYHKX74ogd0uk5mYwplzBblD2F8DDaQfBVIgcHuuQJxxjn3qU4p8zEC6fM8LfOG7HgITirDCgkmNKA4CQagPsC1x415D3Ahux5A_ZWMnUGmalY6vIRIy7xwAh7yCs-OLnF0jaqzCrMnZvwHtD_0Osjwf34Jw_7tPLFqpnjpfn2ymDyGlniulDnjoaixcGRKEMRdCUU5oQD3KFPcFUz6kzVxTCr7REy4lPlgTNhfX8LlqZyvK6agmMvCuy4ua__7VxM656Vp7OFI34PGuSpUPzjVQMloQp7ihYr5COCTEjXDoocDXKAiwG0GAIlnoutINXOrSECvuRq7CVvdg3gIq5w09aZblFsYprNfQ95pM1YpT1vEMLQW119rUocNMTVcOV6pUMkvCZnmid8zHkCWaYLq3wdUtJK2hkbIgs3eN_BeEKLgrtjaX5jsH43JZYK1DJUKPBdjn1NfUjUSIItdnvsdAWsOQRRCIUMiPPBVRygKqQYIxJZESiIQhapsS0huZzAus_KsF1tQI6llaQpoX3-iFUnqdjYOhsYUH-VgnEP4siKjvIAw3gUtyD0F7nPw3iKvodH_vTcVM5_9HQfj2Dwjo7vXgIo-LEdiToCPCYRpywUgoiJ-J8CJMMSEhgbReaRaYrB5SRDC5WuNQethVSgikAvgF05AbW9peG1mwwke7ApXqGjynugdvwHpjmU5gc-vDwNxx6GBpm9mqMKAc3VfFJFs-UNakVo5ycuKuhkKdVVsFXPsCsYMzvSG5XY9oInyfGx_9lw-RZaflg-zBXAe7YI8AAcccQc7lQiRMIO8CZ608Sl1EXCnAHgYITCHiIVVg-6RwBZdcEK2164VItxcVBJvbI7BJoYf9GxV6OjnudSUlCsL-UZaayAg0ItX9nBchoYTwyBWQ9urA51j7LDKLm57nh1rS0BOB62rk8QhyES7A-0jwSua9SToU7ToOF3Oc50s5j2hfbfnqLsvDYnENrj8tIf1pyV9dyWh7xs_3Ts4OBofK95OZtb4cg02pIkEQXxPWv8khE2wFGj7Sikeh8iF5YShioYgE9YTvhTDxIdMgFNIF660DZIRAqwBHxIfwI8JE4fa-HCFaSx6NKFm289NpjPDWzJo9q1jfCu7ATIKXjsZJMiAQHuTVjTyzKW3XxnRVG5tFKXQGYuy5Y95QZIivY4e6HFGX1P5Mf8s6NPYkS-DpPtD2CWbpMrs3Cz6Bvi1z3ZozrWF2_ECCF8UkQoEg2PV0CCkk8kkIGSdGiGpf-WA-NcYm74GIETOOlUtZ2Lv4Or8BoRk2uu0ZxC2NnZWFJkufdvXGglvuW7QmoKt2tztmq_tkn0LdfX-7qmZma1eUVlnJg_UgRGYTX7lsc2Omcz3MdTEEiAFqbZio7lSeX3JC5hFxH3jqr0urFrjD4OxnZZmNbDnkKk6MaW-Zm9PxaARs9OM8bAowUVR4UjNXepr5viZcigiBuyEykkIizgWm5rHg3MUqkAq5bsRA1nEUgI1qGx3UY3TmRXZFoyPnchKTp01eKzPnqGaro-sYlo0WbETnLOTg0KdW_8dxHHwqOmbj7GZsQtzmShwYfexShVToRipQCoJwiTXxfE9iT3saQXhlElDOIy8IAuaiiEOiaWbORaGaTzO7J4L3TcSlHhs2qtIOT6dhNVJTUTDjnhBUG3lj-ScqPpk4E6EDjgGBMMBK4dRPnI1G49SYFVBpe327mR6IiJxpPRJ-zrLfZ-Ye59Jl19weZKkpv5TO3kiXkFqU7Tk9GOeJvmtVIZHwZeQhHSnmeTiQkeY4hI_wOwNV8wRHGrEo9CDcg-fII1xQ33V54GkVtXMwLnvmlPAnmVPkLdI2KhtGvSplmfR9nBcw9RDH3WfjP0zxuiLsfRNPl1mqnfdxMRycqtyE24Epd0GrSRraSkpfOB4fNG9r79hwiFlzPn2NkcARAjVVOAjcEEfY56FCnqIe45pEpiaEOTK_R1oECsxmiAWLXErDuVWDvq1WlzsnO61NKaw9vW2719pR0dyDglpe36692aJOBVDVVyrXj0RzT1U7b3-GOHm444p0FyUbuweX78hq7xppxC9fKlqrtB_EI44gLYEBmDBhHOrmfhPqzoSyWn7bnizsWvvSpmUG94y6_STPmjWtnI1g7XvNdGXVzA6yJhUmgjqY0mxvpG8-xa2tMb6uUyDd7I-32thrwaf28utumUfsllnEMXd5k-VcRcvZihbUCpDbWei7Nic1jdaeGhG7Ure3Q7O30BrtpjnCNPCYrygjkYslVZgzD4EHiSBWU76UkiIvwkhKHUYRlQHyQx_CBUhNKAkjOmeOmrGbbNgf9KiEEdFV9002k4i2B7GlPGMdFpXyOsBrh0Y61MnXdgl8CNbvQaTY3_44z36Bwf45GesjNyrjBduJTsZlCVnt0S_Z6L40m1ZvbtqlCBmwwFVUc0mIKQf7EpJZKQTxQMakORgqIOwMIBUwb8kiWmhMlPZdIkIfa9wvWYs2X84tnJNHbr4k3oqbLwnq2V65uu9sb6Hs2ohJVtmIKVfYiNnjJad6YePpJs2LXWebu_NsajpB8PWjzKxLzxjUHpUN9uv5-bq18092Vp22oGv58wQCZucsj0EsArtYd3p_m2ZmKenoXj8sSxPfNQfpueuZtF97hFIpXeXJiOEwgJSUcB0wcC_K9TGKhJAh15DrKBYGvitl_yoon1sdqMo_tsSEvAd2f1ZmekYeHlHxLBStFxPrK_WaStG177RVjboxPudiqMzN6E6U5Q51CnuMzmY534Pm_5tvI0W0aztelWibsHU_TsPBVXl_E6vUeRcXrXJmxCVmAaQtHOIKHjIaEQGOIGRYRSEnEGj4AQk45DTYw5gTH4kwIC7WAYYHaG6tm86M_V7btp8qU-Hb8--LQk33VzyjvCPVqM5n2MMVjVTjGa02ws3Kg42H1H24_WISopj5Xbb_6a9wHq-rZv0uy0v9xS4MH9gXe1wa8W4GjJL4AjLXEIUuKLKHRQTOWyLf1YqKUGv4hSkkQxoIHXAPsl0dCRa6iriB8vh8_tp_cuIZoQ_msuGk0SqreM-oVWfw9Dq9KYe9Bb_BMyGbndnF46lz_SFLd0yUkJptCSAnzc29OxbuOjPV8ukSxX_Dll3enXcMtXNkb8ax8dX45ibRgzfp_RdnbzROQEObpRDkayQCCYkGloFibsBVxDgzS8ZCcYGCkEbYU5x4fuSHkQbroITwNEfgJMJggSihvl0xCSTVkBEVzsyczVWtJiVHu82uvmTI2G2zDBFD_FOvf847le4TmQy1xO8Zo-0tu8-IeLjjhXYErZNXbQ3molez8y8CQksQPkCQmtLiuQpTE0_FkWOnw14UBNS8z_IEfFBcOGE2ik3TgXFGE8qccqjKSqitbuVOYo_Q2SJKfQKnRnmlVZXGfDH3G7Qwfl1bASK6_OebtEjUGFyNc5XEt7c6LwaHubrJ0urAs718eXbYmfcfdhYEscZhZ77gsLNt2trSylUgQ5dT33NJFMB_JIoIEiqMlJaayshsSxO-dl0mIz-SOJA0kEpBQhbOLxD0nfPcOYE_l73hWUMdkVy8vgvidp-NqyIziKWvdSWGYOeByOR-UGVDhS0dTxQh1DOtBF2N7J1V7VPUzYLjzKO085nJy8WnCR1Z4Yio99BlPZNLCp2IzYUhszSsuSv_az40nw91ql5XUHOudFKUpmz0fgg2sCeygbhU-6YAT5gUyGQhjGDIQ3wVhp6G2FR6giLtm8XMQOCA6DAKggiHiEP0KqIF7kisF9mschCtP5Lh8gHyadEZNGKXVqpm1tqqtASiJNEfCX-NgjbyBaS7Pvvw1tRB49LUmXlnaMExfpcQb349CiG8ZEHKxUQ25d4NXel5GnFfSSYgGsMQuZt6MDgGhSUnkgvmc4jzI-KZF9pDFO9JSM7NnXsew_PnHHqdQv1fUzFkO28_MduAi7pshl2nvoG1ErUBo5MyUmcFr07Mz9JCpXowCWq-r8q0_r3xEXlVNza7nENzAiS7t-XnBhgRdTGqvyhm71-voa4MTEO7TC2ripdMOGiWEisVq2rcs22nFu53V4-N0kOC1q7-9q4F_E4l29WLrFMj9qvlwAtgwG-MfEPZDqPf9ldOZza5AfeM8G8I3SHy2xWLxA1Ygr7B3g7B3_YY70ZTKr6haIe5325wTv-b-qsJiYqOkZYw0m3Ht6iz6oyR-bJA-Ot9Cpa1u7PbR-O0DlPsOkvVaWFuifn2D6sXP22Z29kxB3GhtT2H-04l468V6T9xcXTOQJk3-fbfc9d-yW-SlfZevwv_7eVrcw-fuUR39urR6dWA08FUpuoshObzlyxWoNUBmca9ixPUzxd3OXsJ3bRTvAzGpoVzVU6ncfWhuxSBTsp5eLwSfHW14OQOwgpbVQhtXPrIVyXaubpTt_MDoWsQMkW0ATMm72ZeCUeXGFT3TrbEYHYV5Zpi0MkR_gQc4U_AEb4iR-orO5scadziuR5HcCdH0DrC3qUt5AlYih_D0k0lvnrD2Ub86FB-vvEI8NoYGhZPPK5P8lQTwJ5AGtATKBh6gnHQNUWhMQ10IyuFN9VJ-gQc3NSLNSQBuRuxg2zKDryhTq83gOmbVzaRySp-2gRDt6KzjTE8yoVu6nkW2hy8ojOtL8puOtPG3dnzzrTTG9uru9veeHqb9yoIqiu9Wwhmt3wvdef9ytbgpVgYYVXXnrcirNlN6CvGE91yQTeWbvY0araOtlerpg1LxR_rLMgTmFyyoiDXd803Z7Fx_fwKcljf295CMLvKfUUx6LKUdENL20zeyAYy8Oh4ZtVMxd5n31Kj6Q33G6hxg330MfAN0Zerkj0D8R4zY2xT54yeRuvpU3kT_lSIyGMd5QyOLYMzi2zNKcTscaYXP80kPFls8BRVB_o4mhpv3HBXYn_TZj2S_U8UYLKNXfDmTpyvaw8awksfZUAe9liVMyev47Jv8jCfDrI0im-qKmd6Oy5rpMG4KLPReRbCUIrSbLx5tTWoEbXaZWkYm61Lb83OU2twtxw_yxKt0toYPwQaF9pe62eq9_UGx-VA057s2ezJMaTlcKPposj7uByaC8quzCLBgXnFGbBwbC4UmQlpC9QfR9FeEgz1KC7K4kSn8Xjtgb5JzfHL6hXg4Ulu3iO3Bop9rdPTuJzsPemGvEhUoM0JdZ3X8Nr0bNcwZhQK113c3ix4VYsTMyCyBGZiHaZsFJjL5d1Ua2kzMLYYZLKKMj86hD26GLJexp6BSCKXjK_q5DJLErs80GRg9RKc5xOVefn8QpXDN9H-OLY7sv85-P8CIYck
```

### Screenshots

A dagger in game
![image](https://user-images.githubusercontent.com/20922789/234097775-f29c3ff5-015b-4af9-8a4c-d6b1f16ce460.png)

A dagger that is copied into PoB.
![image](https://user-images.githubusercontent.com/20922789/234098069-36686257-2d38-414f-bbf7-2a374fa1a0fd.png)

**Comment by Lilylicious** [comment] 2023-04-24 19:41
Advanced copying has never worked and is not planned to be supported anytime soon. Use regular ctrl+C and it'll work fine.

Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2684

**Closed by Lilylicious** 2023-04-24 19:41 UTC
Labels: bug:behaviour
