### ISSUE TITLE
The application does not start after the update

### ISSUE THREAD

**Issue by BlackBeard12** [PathOfBuildingCommunity/PathOfBuilding#7431] opened 2024-03-24 11:52 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What are your system specifications and configuration?

Windows 10; graphics: RTX 2060; Ryzen 5 3600

### How to reproduce the issue

1. Download current updte;
2. After that programm closed and does not start;
I tried to delete and download new setup but it still not working.
The application does not start, it does not display in the task manager.

**Comment by Ciccooz** [comment] 2024-03-24 16:08
Hi, can you access the Documents folder or does it give you an error when you try to do so?

**Comment by BlackBeard12** [comment] 2024-03-24 16:36
If it helps in any way. I installed version 3.23, the application started launching and downloading updates. After installing the latest components, the POB does not start again.




![Снимок экрана (1)](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/46569446/2816b160-726b-4596-bef1-9441daedfa56)
![Снимок экрана (2)](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/46569446/e5f26033-10a8-4762-8da8-c13485393e82)

**Comment by BlackBeard12** [comment] 2024-03-24 16:49
https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/46569446/72f3b15a-060a-42a0-897b-8287d4ba086e

**Comment by Yasho1313** [comment] 2024-03-24 18:53
I have exactly the same problem. It doesn't launch. Tried installing an older version of PoB and updating it but after the update it didn't launch. 
I'm running Win 11.

**Comment by racgraffiti** [comment] 2024-03-24 19:14
same issue here on win11, can't start after update, tried run as admin or install either portable/setup exe

**Comment by Ciccooz** [comment] 2024-03-24 19:18
I asked about the Documents folder, because I was having problems to access it (since i uninstalled OneDrive, but the folder was still linked somehow), then i fixed the folder and the PoB now works.

**Comment by BlackBeard12** [comment] 2024-03-24 19:25
I have access to the Documents. The problem is with the versions of POB 2.40-2.40.1. The old versions work

**Comment by cocoemo** [comment] 2024-03-24 19:37
I am having the same issue, I had POB work and suddenly after the update it doesn't work anymore
I have access to Documents.
I see in the event log error ID 1000
Is there a fix to this?

**Comment by Yasho1313** [comment] 2024-03-24 20:17
> I asked about the Documents folder, because I was having problems to access it (since i uninstalled OneDrive, but the folder was still linked somehow), then i fixed the folder and the PoB now works.

I have access to the folder and no issues with it.
This is what I get in events:

<img width="477" alt="Screenshot 2024-03-24 221710" src="https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/135731417/3f5f6962-5ed8-4271-8f0c-6f35941a40a4">

**Comment by Mfortitude26** [comment] 2024-03-24 21:35
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/164804475/2950db5f-3f76-46a8-b8ea-835a7b6e9153)
I have the same issue.

**Comment by zao** [comment] 2024-03-24 21:36
@BlackBeard12 @cocoemo @Yasho1313 @Mfortitude26 The information in that event summary is unfortunately not enough to tell the cause (the offset is just for an `abort()` call).

Could you please see if you have any crash dumps for Path of Building in `%LOCALAPPDATA%\CrashDumps` and share them privately with me at `@.zao` on Discord? They contain the crash details, a small amount of the memory of the process and information about the program flow and the program locations.

**Comment by zao** [comment] 2024-03-25 00:16
I've acquired crash dump from some of you now, they were very helpful in narrowing down the problem.

We've got two distinct crashes here, the earlier one where `SHGetKnownFolderPath(FOLDERID_Documents, KF_FLAG_DEFAULT`, ..)` fails to obtain the true path to the Documents folder when the location is sufficiently krangled by OneDrive malfunction.

The other crash is more insidious - it occurs when the directory exists but is named in a way that cannot be represented in the user codepage. This raises an exception at an unexpected (heh) place that unwinds the startup process into an `abort()`.

One of the causes of the latter is if OneDrive controls the Documents folder but have named it in a localized manner with words in Cyrillic or other scripts sufficiently distant from a system codepage like English (United States).

I don't have any immediate solution or workaround to the second type of bug as the location can't be represented at all to the program and it's computed even if running in Portable mode which stores builds elsewhere.

**Comment by racgraffiti** [comment] 2024-03-25 01:00
Hi, it seems my condition is about the onedrive and the document folder. I resolved it by changing back the folder path to username\Documents. Here is a link that I followed:https://learn.microsoft.com/en-us/answers/questions/764490/i-uninstalled-onedrive-but-my-files-are-still-redi
Hope it could be some help.

**Comment by Mfortitude26** [comment] 2024-03-25 03:12
Same thing here, the Documents folder in my case was in a different language. Just right-clicked, and changed it to "Documents" without even doing anything about one drive and that worked.

Thank you @zao @racgraffiti

**Comment by BlackBeard12** [comment] 2024-03-25 07:36
The problem has been solved. The problem really was in OneDrive and the Documents folder. 
Thanks for the help @zao, @racgraffiti .

**Comment by cocoemo** [comment] 2024-03-25 10:08
Hey guys,
Thanks to @zao I have found a solution that might work for you
It seems that the Document folder location (Check Photo, you can go there through settings)
![Screenshot_1](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/49520482/6d6b5184-f217-406a-9c89-147b06066440)
was going through the One Drive
You need to change the location if it does to default
If you are having problems, it's because you need to cancel the BackUp through OneDrive manage Backups and then change the location
Once you change the location the PoB should function

Thanks again @zao  !

**Comment by zao** [comment] 2024-03-25 13:12
Keeping this open to track the underlying problem until it's fixed in PoB as well.

**Comment by LordBumi** [comment] 2024-03-25 13:16
Yea it looks like i have the same issue , sorry for the duplicate thread .
Old versions worked till i updated PoB and now it wont load at all .
Older versions load but crush after updating .

**Comment by Yasho1313** [comment] 2024-03-25 18:49
Resolved the issue by changing the name of the Documents folder since it was not in English. PoB works now. 

Thanks @zao

**Comment by templer10** [comment] 2024-03-26 15:09
having similar issue - pob just wont start. tried portable version, removed onedrive, changed directory name - nothing works. tried installing from old version and when the app starts it tried to updated and stops working after update.

**Comment by Gadty** [comment] 2024-03-26 15:28
I'm not sure that we have the same problems because... After a failure, the application issues the following error report.
There are obviously some problems with the **glfw3.dll** library.
![er1](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/86926694/ca8644d4-4b80-42a5-b0ce-59889da478f6)
![er2](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/86926694/432b1aca-1b1c-45e6-93c7-6ce50e590cb3)

**Comment by Teasemx** [comment] 2024-03-26 16:01
I have same problems, but only with version 2.40.x and higher, 2.39.x works.

[crush_report.txt](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/14761195/crush_report.txt)
[event_report.txt](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/14761196/event_report.txt)

https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/19271891/178d33e4-7688-491b-833c-923283ceafa0

**Comment by zao** [comment] 2024-03-26 17:57
@Gadty Your problem is likely a different one, where we accidentally save a zero window size when closing the application while minimized and don't handle it properly when starting again.

Until we get a proper fix for this released; go to `%APPDATA%\Path of Building Community` or wherever you installed PoB and edit `SimpleGraphic\SimpleGraphic.cfg` (and `src/Launch.cfg` if existing); looking for `set vid_last "0,0,-32000,-32000,0"`. replace the first four values with a window size and a desktop position, like `"1280,720,0,0,0"`.

@Teasemx Looking at the logs your crash is likely to be the same troublesome Documents location that is prevalent in this thread. As a stop-gap measure you can follow their instructions to move the Documents location somewhere with a simpler path.
If that isn't the case or it doesn't work, I'd need a crash dump file to see the exact failure site.

We've got work in progress to address that problem as well but it's subtle to get it right.

**Comment by ethanc-ec** [comment] 2024-03-26 20:54
@zao Similar to other people here, I also had the issue with the Documents folder being in the OneDrive directory. Even after changing the path for Documents in the file folder, the registry entry for the folder path still goes through OneDrive (and causes PoB to not start). 

Changing the registry entry for the Documents folder after doing it in the file explorer allowed PoB to start properly. I followed the instructions here: https://support.microsoft.com/en-us/topic/operation-to-change-a-personal-folder-location-fails-in-windows-ffb95139-6dbb-821d-27ec-62c9aaccd720

**Comment by Xeverous** [comment] 2024-03-27 04:19
> @Gadty Your problem is likely a different one, where we accidentally save a zero window size when closing the application while minimized and don't handle it properly when starting again.
> 
> Until we get a proper fix for this released; go to `%APPDATA%\Path of Building Community` or wherever you installed PoB and edit `SimpleGraphic\SimpleGraphic.cfg` (and `src/Launch.cfg` if existing); looking for `set vid_last "0,0,-32000,-32000,0"`. replace the first four values with a window size and a desktop position, like `"1280,720,100,100,0"`.

@zao I think I have the same problem as @Gadty - instant startup crash after update and after fresh install. I have none of the `.cfg` files you mentioned.

**Comment by StealthxDuck** [comment] 2024-03-27 05:03
I have exactly the same issue, would also like to mention that I am running Win7 on this computer, like @Gadty seems to be. I can send .dmp if needed.

**Closed** 2024-03-27 05:12 UTC
Labels: bug, crash

**Comment by Wires77** [comment] 2024-03-27 07:41
The PR I merged provides a workaround that allows PoB to start up and inform users about the issue.  We hope to make this more seamless in the future.  Thank you to everyone who shared their setups and workarounds!

**Comment by Xeverous** [comment] 2024-03-27 20:51
Did not help. Downloaded newest installer (from 12h ago) and still the same issue:

```
Problem Event Name:	APPCRASH
  Application Name:	Path of Building.exe
  Application Version:	0.0.0.0
  Application Timestamp:	65fd9292
  Fault Module Name:	glfw3.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	65fcd2bd
  Exception Code:	c0000005
  Exception Offset:	00000000000076e5
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1045
  Additional Information 1:	095c
  Additional Information 2:	095c822fb3614d26d9981359e180c527
  Additional Information 3:	ee06
  Additional Information 4:	ee069775e5793132cce3cb3875cee18b
```
