### ISSUE TITLE
Crash on allocating nodes with Thread of Hope

### ISSUE THREAD

**Issue by LocalIdentity** [PathOfBuildingCommunity/PathOfBuilding#1117] opened 2020-06-27 04:29 UTC
When allocating a node on the regular tree with a Thread of Hope whilst also having a Thread of Hope in a cluster jewel socket, the client will crash

**Comment by ppoelzl** [comment] 2020-07-04 14:36
Duplicate of #851

**Closed by ppoelzl** 2020-07-04 14:36 UTC
Labels: bug
