### ISSUE TITLE
All "Vaal" minions (vaal slayer etc) not working

### ISSUE THREAD

**Issue by LiamHendricks97** [PathOfBuildingCommunity/PathOfBuilding#4336] opened 2022-04-26 17:57 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When adding Vaal minion, you should be able to look at its skills and stats.

### What is the actual behaviour/value?

When adding Vaal minion, error message shows up. This holds true for creating new Vaal minions via "poedb.tw". 

### How to reproduce the issue

1) Manage spectres
2) Add Vaal Slayer

### Build code

```shell
Ey man, I don't know.
```

**Comment by Lothrik** [comment] 2022-04-26 20:13
For anyone else looking into this, the specific error he's referring to is this:
![](http://puu.sh/IX1dT/6a2a189bc4.png)

This error seems to be caused by certain spectre skills (such as ``ElementalHitSkeletonKnight``) having gaps in their level data:
![](http://puu.sh/IX1f1/176fe4293a.png)

CalcTools.lua currently assumes the levels are continuous, and breaks when ``[nextLevel - 1]`` returns ``nil``. I'm not sure what the appropriate fix is off the top of my head; as even if you add in "fake" levels to ``spectre.lua`` the skill in question still seems **very** broken despite no longer throwing an error.

**Comment by LiamHendricks97** [comment] 2022-04-27 14:34
Been looking at the code today and I think it's a bust. This spectre is very broken. The code to allow the spectre to switch between lightning, cold and fire is missing resulting in pure physical damage. Whether this is intended or not is unknown. Within
 `Path of Building Community\Data\Spectres.lua` there is a typo where:

`weaponType1 = "One Hand Sword",` should be
`weaponType1 = "One Handed Sword",` not fixing this results in the following

![image](https://user-images.githubusercontent.com/45033283/165538148-c452c89b-b4d1-40a3-a72a-197b7bf8233f.png)

Back to the topic of `ElementalHitSkeletonKnight`, we can use:

![image](https://user-images.githubusercontent.com/45033283/165542578-e3db49ce-fadd-48a0-90af-cded5b13e1a7.png)
to get the code to work but it's still a band-aid fix.

We do not know what _"level [2]"_ looks like and if behavior is intended to decrease damage of mob as without this value the mob will not scale and always deal _"150% more damage"_. Above changes will get the code to run at least and to add the mob as a spectre.

**Comment by QuickStick123** [comment] 2023-01-17 06:58
Should be fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4230

**Closed by QuickStick123** 2023-01-17 06:58 UTC
Labels: bug, crash
