### ISSUE TITLE
Crucible mod -3% base crit, lowers crit even though Slayer ascendancy Overwhelm is allocated

### ISSUE THREAD

**Issue by Dschelske** [PathOfBuildingCommunity/PathOfBuilding#6078] opened 2023-04-19 09:58 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

In game my crit chance isnt lowered by wearing a -3% base crit crucible mod, while having the slayer ascendancy Overwhelm allocated.

### What is the value from the calculation in Path of Building?

In game my crit chance isnt lowered by wearing a -3% base crit crucible mod, while having the slayer ascendancy Overwhelm allocated.

### Character build code

```shell
In game my crit chance isnt lowered by wearing a -3% base crit crucible mod, while having the slayer ascendancy Overwhelm allocated.
```

**Comment by QuickStick123** [comment] 2023-04-19 10:02
Functional duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/6048 and fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/6077
![image](https://user-images.githubusercontent.com/31533893/233041205-9d94c690-c05f-40ba-9e52-7fa5c55ea6d5.png)
![image](https://user-images.githubusercontent.com/31533893/233041281-0140b21f-68a8-447e-93e2-b7333ef8fa3a.png)

**Closed by QuickStick123** 2023-04-19 10:02 UTC
Labels: bug:calculation
