### ISSUE TITLE
Amanamu's gaze unique jewel

### ISSUE THREAD

**Issue by Kendricon** [PathOfBuildingCommunity/PathOfBuilding#3033] opened 2021-07-27 03:14 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

I'm adding Amanamu's gaze jewel to my build along with 4 ghastly eye jewels to reach +30% minion damage over time multiplier to calculate how much it increases my minions bleed dps.

### What is the actual behaviour/value?

The bleed multiplier does not change and stays at 1x

### How to reproduce the issue

1. Select summon reaper/vaal skeleton/zombie/carrion golem
2. Switch to calc tab

### Build code

```shell
https://pastebin.com/k0fdnAEH
```

**Comment by pundm** [comment] 2021-07-27 07:57
Duplicate of #2826 

I'll leave this one open to shift it back to the top

**Comment by Kendricon** [comment] 2021-07-27 08:05
> Duplicate of #2826
> 
> I'll leave this one open to shift it back to the top

Apologies, i've never used this site before and I guess I searched for duplicate posts wrong, sorry!

**Closed** 2022-02-02 18:34 UTC
Labels: bug
