### ISSUE TITLE
Vaal discipline not turned on.

### ISSUE THREAD

**Issue by BoB3R** [PathOfBuildingCommunity/PathOfBuilding#4106] opened 2022-02-08 12:47 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

I assume that when importing character profile from PoE all auras are Enabled.

### What is the actual behaviour/value?

When I import my build only "Enable Vaal discipline" is checked and normal "discipline" isn't. I have to check it every time I import my character from profile.

### How to reproduce the issue

In character import you can import and check in skills.
PC/BoB3R/Archnemesis/BoBeR_Arch

### Build code

```shell
https://pastebin.com/kNpTYFTE
```

### Screenshots

![image](https://user-images.githubusercontent.com/58575145/152989916-b577ed93-ee1f-4888-92d5-d15d1685a71a.png)

**Comment by LocalIdentity** [comment] 2022-02-08 18:29
Duplicate of #3077

**Closed by LocalIdentity** 2022-02-08 18:29 UTC
Labels: bug
