### ISSUE TITLE
Perfect Agony + Elemental Overload + Pneumatic Dagger is showing a massive dps loss

### ISSUE THREAD

**Issue by Zarni222** [PathOfBuildingCommunity/PathOfBuilding#5598] opened 2023-01-15 23:56 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour ingame?

Taking EO while using Perfect Agony and a Pneumatic Dagger (and have good +flat ele dmg) is increasing my dmg

### What is the behaviour in Path of Building?

Elemental Overload, when used to create poisons via Pneumatic Dagger, is showing a massive loss of DPS when used with Perfect Agony. My personal PoB is going from 12mil dps to 3mil dps, presumably because its removing the DoT multi that Perfect Agony is trying to grant because of the last line of EO. But in game, it doesn't seem to work that way.

### How to reproduce the issue

1. Load the build code below 
2. Go into Custom Modifiers and add/remove "Elemental Overload" and watch the DPS/calcs change.

I tested this in-game as best I could, by running Baran maps (white) and comparing my dps against the boss. If the game reflected PoB, i should be doing 25% of my normal damage (while using EO), but this isn't the case (it would be pretty obvious, at that point)

### Character build code

```shell
eNrtfVt327ay8PPRr-DyWvt7ieMQdzJfss_yLbabOHHtJG32SxZIghYbinRJKo67V__7mQEpiZRJWbKd7tOepm0qicAAmPsMBuCL__42SZ2vpiiTPHu5RXbcLcdkYR4l2eXLrQ_vXz31tv77n6MXZ7oav4v3pkmKT_45-q8X9rOTmq8mfbnlyy2n0sWlqT7OQLHPAOpKZ9XY5Nmp_iUvjvLo5dbbPDNbTqCzKKlm38JUl-VbPTEvty7GOsqvtxxdhiaL9hcPdssSPifZljPRSXaRh19MdVTk0ysYacv5mpjr0zyCdienZ-_O37dGTrL2yDDz_3pxluobU1xUunJK-AuAAwL0pTnQE_gboOl0CqAYcemOt_VsZZ-9aVFWG3W8uDImmrdVO4z7VPKh1meFOYxjE1bJV7NfJNX-WGfhYijiukM9N299Ok2r5CpNTLHoMdT-eBPg7_NKpwdnF_O2lHou26G-ZMynq3vl1bzXIPyfkmq8lwJaNx7j5DJLKtPpxqTY4ZR71CVCrBqxp68g0ttRlBDhs-HOZ3lS5lm7o0-ZR3a4qzhx5R3durwmXJdQCcsUnHmrZnt7UCZ9j0m2wxX3hCB3kaHbVSmfih3pMsYGJ7w_TVPQFu2Ow_yXT4Ik61KQKddV1NvxfF8qMUjDU53p_bxcg0-w5ZkpQLVUG3W4MGEO2mjTMTbs-SaJTaelkquabrSQpkPPdIgnd4hHmOAS_qg1RtxwWYcX67bbGPD9JnQO8rNey4uqpQnFIG7Oza_dloOSf2C-LZQF91cAbLcEbTKov7IWJZW3AmCn5aoZfs0rMOB3I8fqhcPjs4UqklKIHY8p6nqcDk75bHxTJqFOT_W3ZDKdgCF5r7-YxYCeclfw_eW4ykCnDHVmRBI21PtVUph7ddzP0-h-Hcc6L4d6-r7nrxK3eUPuklXeRPgcW59kYcsUe6sAf8gKU5ria8sNWTUEdjkH-UKHJ0jN2n0WwzRyuo6rUA92abJmxJuFvPg7YlWvN8aE4yNwDs91tZikR3dcH3Sc9MAqrzQhbeyplejG1m10U28V3B5sM-6u12MZcYzsUOWBvfbA7nO5Ckg_Eom_qk8_Cn0YlDDiCSbk4EoPM1Nc3lyME5Mu1kn4MCbbHWbT3NdXa_W1VGgDaFODrzdiH3bcdbr2I2nYN9VFtJ5N2nROX3XZVtSeIHcgrO7QwdUw5xrwp6FHZJbc_FWhSv4LBirphv12i0k-XZhPf7Wuq1u3F-HeZWlql_ncRNOwY9oG1cFeCvHl0vwpXzGtNO3rogb11W5V6fDLQR5dLqPJXTnK5j0upldXoE2Q8Ev9ht0PtJPnpkzarqi4u_E74NuOBK-0p2sPsGh8awB-p5-w9ihLPZaHomqliV8ahpM1Wi8PMSzos_j_FDTDBMyBzSCc5gu1QndWhLivIApbKwSzDbtx3rBo5dcw-zGmfMrNWoM3tDBng1MpTPbbzdrwO83XGuAwi6YFisPaYyz3WGuYXUs38JTN5E0ySapbeZX3yQQUbVke6Eo7v5hrk76_uTInEbZwSqOLcPwGeOXl1let088ZuNzggX0OkYs-R1atfSbbTv0vpXKrhlGnxxAK49xjbUivdJoGoHtebsGvttmrJK1M8XKrKqaYi8uzX6emyIvZPGq-evHM5vvw08nkKi8qJ9VltRuG-TSrjnU5Br0dMB5HPCA6lsLXPncZ5TIksXYjI30aE5eFsYi3bNdzo9MJcMZ-_RWRqkOYRw3L9byQS6OldJnwoZcXahIJ36PajxUhisaGUVHj_cW-TsPSovMku5pWTmYzhpOkDD8H0zjGxCAstipsTvPw1avD_fcnHw8bCrS7lF-SFLA8nQSYAqv_v6DuhbHmwymnQVl_fLn1MTHXF9jrwFQ6SUtEYJrqq9IA6mKdljByAh9tmwsgdVitgGZbQZwwy_H0w1o0GIZ0-M0UFawXvI-wSMzgvObP75hUPSB6JsixQ9AwWTcMqDZ6-0h86zkNYMqmR4ehYKJycDn4cEVfYF2dDo7cPL0DExXIRQmOSBInIUr6apKjFNWtVuAlDEGzhDcr6N2Y7mEYNvs5BKB-ONy5Tg0O9W6ersCqzYMOYrV-Otz9wIR6cO31w-HOc2c8z45RvfZDmbdaAeltk1oFodlNUjSzg5Q9TM28yTDAd9XYFLXtHoR0Cjpq1mSl4BRJMK2GxbjVYgWubE5hAEP4bLhrHR8PrAGfrdBEncBwAKHtNsOg6lBqUJGt6nq-Qp-er1als_BkAPP10xXrn4VpA0tvHq-YuvUWB0nfuJ6rVAOY-WHVgA-HO9eidRtE7SysA8GKwYGJDSiwlXIwb7NCAVfT7AB0ZbUCoWuCqg3a7tc8ieqo6EHQ7CL7gS0wtRGsWr_04m1jiDZqfCjql4LJR0F_kw8dUP2tJncAAp19vMIrWA_SPMw6BtcU98vy9GEAb-V9H7TOvCp1Fh1gjuiBC8UU0_QKgM1m9q7PrVtw2TLUF89mDvcL6-OUEEgU1ZGZlHs3EDy-Qi2-tKGnLWIbJ7iqg5t2n9lwkYn1NMXff5zqNKluMCBr_fqmLjfI8mIy30AAUOP8GlmzhoguVwmK-c2b-sluWjXAcLgZvmrsNBOyyyT2t-ZHW2Wwu5i1XTEMnABPJFmYTiNzkjWRdfNzqgOcG9ZPYJA2R2GZ5pgGNPoK6EC3liHXve3Q__UCZth0P0rzQKd0BrteN9nqPCXzIRDQifXVikpD-1_rBZ9YD8oib8u5NBP8fgqBSgTR5rMTCErLZ4iTZ3Yi8Gmpu0X-0mpswNfMCoMmzMnNx332SMtoiImhwrvswOhqvPmS5vzQB2X9lWFvBwhX968X-KJG2B_BLs7FNaaIHsAzYk1kf0zCJJ-WiyRueZZOywfg_Q6ArZndQYLda1Q9JnIaiE4L5KYUIfekx14e3TgzT_AWNciatKB3cv6rIi-rvVRHZgD1tuWZLmoluoZM90GEmdzm_znkBar66WEhOg3IZ4-18oZxMBCpkOXvzXfLEHoX27-yWdfHXtTZNAurKeafarl-wOreYp46QNzfZ4Gt3uuu0V1zjbZ4DJNsX8wDltcHZYP1tbs_e1z9CAYgSm9mcf8DdeMKYBusdq4Ya3BONynxeEv_kAUwfvRIa18F7T6Lb-Atr_6PM9LkQfb5bgF7lcKiD3Q5vrdfdxvCBoi2nR3b-7F1xvdQ9vfT9X8Atxwb4M_qO_OK3Wqye_f3Zhbb28K5l1hi4F8VOkUvrQIvLS8enW1egU9uino74QG80wtmE8Gw_Z0aQPl4q_xpnBRYN7vKDVyDjgNgNljgDMKmvt66dLSb4TP0PSDA6wOzyTITzLjhOt_n0_APDPL28hyTVg9JCNyJ6h-nSfjlaGoz5_dkpIvKmBQAZm3ksjWRu-j8aNyznxcQgSC6xkU-vf-6zlJ9OTV7Rhe427s539T9nQbA98l9tNOkD82A9MDaMA9yPTaZU8NxWlnGu1fN1lz1bhQlmKTUaZOye8Cqh2FtQOPDrLXz-kfoBEDQV1N-Zy_ho9bpUaHD-zsJtyFsgFTs7NS9vxv__Hz2KKzTArMR16QYaJtHVHq11M0y9bvTQnfWt4s1PJmuDF2LfCugbRJta5h-nposfMR0wtm0uJfcz5R6t_sGKWzb0clj5zA13y-QLPNpEeI5RZj6c0aeX-TTamwD2G3nIk-jBDzKmQ74XgriThv03mCNl07Bs0qy8h7IvI265uOFqewOUr1xhB_fF8bM9odsX9LszcCX9jHQpiZuYp3um6Zo4uXWv7nyvG1KXSF_3_43JZ5LtomiCr4wQny1zbknfXzk-S7blpxKjt98us0VfIPPQjDubTOfCHwihaDetlCuwm_c96i7zalL8JuSjMMXIRAggTG3JYDFsThnRAJ05pHfARF5hFtQRAJcwqFZDYZ5nuTbVLgSpoU9YXI-zJ4QDhPFqYltRiil21ThqpjvemLb95TaZswXfFtQf7uenxSUAEBopWDxiuMvHnO3CXRh2_Vaqeu5atunrtwWnku3Pfi4LXwJ3zk0BqwJomAUpgSz3cm2dBWDmQBAvi0ZoHGbMgZrhqcuIEUSBZ-lxwB5giqKaxEwf494dLtGI7SkMFFOOIXJcLFNXI-zbSY97gMwFx96rvS3GSUE0AD_g0VjlSK0oRSmQBhO2GUMB6S-gPYU5sdgtjASZxJGpdLFkQAFlvwcKMLsxOxUCUzJF76Hv8A0pELsClZPDrrXTOJ7OHVLRIEdhedLwAZhApDsW9AcSMF9X-ESlXK3kWsAmo8UA-oBNCQI4EwAyhXgAFYNTYDKLmAbBsRToDB1wmC9AvgGICB4wB3hsGpABvOkBNxxFxsrtm1ZjFCcIUV-ARpLCT9T-EsgWuEhJzAty3CcE-RIlxDAHvdhhpRK_EyRLwD9gA8XeI5ziWwBvIXc5kFzwqGdABHhyIrAYdxzcWE-NpGuD3ir5UeCmPi4Bh8mC4ARIS6wHoWZwhS5q7acCmS4dfAblXw4k1nZbKt-OH9Ta6dxVV2Vz589u76-3rnS1TiPzbckNTthPnl2hWe8v5qnVhM9RbDPduHP3uWnvWj3X9d7P7P97If4x09m6rr6qffmXab2f85ocHLzqbjQH8evT_YP48_8c_Hr-8_kl_Air64FeXV88vnTT78mbz7Jt_q3g8kP-tLPqh_jD5-evvODH6pqWr4dj_mX8IgevH8fX5p_vU6nZ97H7JpXH_1I_3I2Lt69jY0vv71-E4hv-rP_7e3J3tHr8rC4uDn6cPPuKHf_laQfrt7_6-SwMv_6ZDJPfy6-PL3-7eqHD5eHX45yr-TG_RweAdX2j3dPpvmX5LP-JQmim8Jjvx78tP_z3vjD5Q8_uJH7y8nezx_k--Nv32J6_Ok6fu2GxdGns1-5fP3x609vv7LTd6_U3oXa57_sBT-fgQl_NX369s3xO_7ORMzfjQN9cPFmXx1_Vj9R783uxae9H64Pf9w739072T282DuHqV9-0LsXJ3uvL6dfjsvXIfv65vPTs_IkfGc-edWl-zG5vKh29eePFxkpf7wg03G-98PrT5-Pozcq1jAf96NgP758Wev4GWVf1GXHZWOE6m9WF7YqkZOqtuFUzF2GpYZWxlsN-VBDy4Ktht5QQ6sgWw3lUEMryq2G7uDQqDNbDf1BiD6G6PN2amEYF7iCL2DrrFlEY4gf3uaVsc_wx9kXayqx4Lgp576oipdbZVOSs-X8lueTT3gMyN1RkkhKFKhuVtdAHBtdneqrebEItm1qKVRTP1Hp6iABq1rY0p2ZeceGPwNNqNoRoA7AwFHVHB59Yb2vxnTj51llx7Q09XHcOj9uf24VXWDTuuDCr1XDuUbP67nz4e3Jjx8ORx-yyyT9f9Cz_P-lc6yLSZ7djN5Pi1-neVIaZ3cyTU01slDsEp47njuyn87Nr88dykYnk6s0CZOqfO6Q0RMinSp3Dsw38BvQw9NZ5JxklUnBR8e1jphw_4F-W2F0aSKndoocLCXGw0POhd1OcuoS3NETrhDcpK49cTCLPHrCaPs3LIgc8Q5MLFyzA9tqOWd2yGv0CbzB5ZFKJ8qBfyonMvAbTLvQTcxtOec0j851BgF4gX-DS7Yjtpr6lYa3BlvQO1uwO1vwO1uIO1vMzi1a_32JJ1QvTxwD7kr0zauxcY4htnLQRU11MdovpqWO5k7zqN6jf-4AUZvPe0CB5hwlmJnnjrsDvos3qmtOnbro9Lmj3FG7CvV2J1A2HvBm8uvUOCcHzx3DRKwjqsDjc02kpNaRjGLiBTziREWxG0uX-n7ETOQpGQTCcM20CXypjQxN0OVgNWqSFDDUqNENz52fnv70dO_pXou7pWxztxg9sZxnnyN66p7AcKdJhmVfGBoNtsGwr25BOsxap1IdW4gP4oOdm1Irpz5o4zRHYEb70wIkEvA2SYBtr5OqpguGDk4dO2DpzHFSjfZ15gTGmeRREicwxvUY0OpgJm96BXOxz8f6q3GmVziecGardE7rLkXZ9LFoG-sSWCEp509HRJHOGizprch1CD3y2q26Ukz5P3BsPNBmO86PhDl1jS3KP6x5Pue_iDR6d7bw72xB3GGRpqxXpBeB76gb985F2PcGJViAx78swfQuCRZdkWO9InfutMVNkLa40Q0YvtmPqJn6ibsjmWWuAauyG4F6U1ZOfeLgicdZmhV-aUCNiBzmXe7X4LHngltBsDuSDeJrfjPOrIQa59qspbZEWETrhBofpDfOa0x1vCry38yi2V-O-1fZIq_LuOe754ejd0GafEXcXQAVr0w6OsvMdALoDIFil5egiVo2IobAKsIjbFEcaa4CrmUE0adHY1drF1xpqrnPpBuGFALFUAsF3yBEFVrHRqMn02ZYumBY2uLYvafnT49aPAuWrOMA7QIVG2aKi3xSE7lmXdSgTREDUr0-6QOqtM0zs0PUMx_kCRWW1RqQ6Mc4mER0FrdH1ezsMWxGmGzz84jSFabGt-zeHIdyzjWeYBtx0e7RDGvn38yXAY-HVo6we_3jTAz_HRY6Bnb9fcbatWNZoTGyp9T_aoy8ooV6PFPQJy7M7RGXE-vENpJxS1T2a-I8dzDYGJ0VJk6-PXf-bQd97u4QIX5_kwPvAT-ZaG6OaxYg7u0OTMpWB2S7WdvPn-et8R640cU07nb1vabryYzVat60rKlut6eS1O1nGr1W6LU-l_P2drBesT16evS4YmuFzrc2BEK_jtDZR3UcxFzWcmxmQikGhZJ1jM6A-fp3pS_L59PsqwFTG30GL29bWyC__5-Tv14PyO31gH7SVTg2xSzUPbxBEUjKWkJ-wHPcbVuiQyY5ZUrQyI8kGIowFtSE2qcm4oaGEPd7xAvj2KdcEKN1GKiAsThkQEafxV1bIkb2PDqQtMqR21qs545En5_RdaPFoCvS66TYkJiA6of4Y8mgtLi7wi1lB1z7tgNUe_3a5vsBYnDj3N6pGc1OAc2LAJ2bfArziGFRTSDdgCMw87gu3LkNubWh9adiy16m471M9yovggS0Y-bYuj5QwckE7eUtfjPAPiCf2jAZcSoDn-pYKT_g4M94hHLXFSETQRS5AoJbHnqSxAHn2g-BPX1Du_wml_gNVN4U4iwgNeaJnfrazy4XggIE_VpBm7M8vQGpGDtJbOlqfWrMBExQgpDsTVxZoNlvr9CU4w1d1l5Uil5UQrhS2PMIH3UGv49mdzncxqWCwJ8HhAjJY0YAWwHIZWgAoZp7JvQZPuUkCoShMWc8DCIjiPJjIWXsK7OMy3MdJVNA0hsMw7tY2wM8AZaTzCIoSPM8QknhXDmlDgs8tb54jBt2-PQgL25gDaOzOv1e4vPCjuHoAsN0eydELSPYDzfwR8cQZAACwj9MUnpJI-_k8poHAp1WtwkTmTCQHmFBwD3fF54b4x0TVHCgDPF07LpMhr7C3SRJJFMhjaCFgqcRcRWLlpM4_xEmt2L8cCZXPe7bub6qpsAB1i6NTg2wxARWM7X68xY2g4h7HqApCrkvaaSDwI_AHglPuVQoj0d4QaBUInY5xD-RB_oidn0_1NIVnHK6HJ-34nDeRhtbuPXWsxFOw7hOva28eEwc6wl2nzvgPul69k0yrAMP07UTDc26QJ1LQGYFZO0EMLb28FYsNFoBRqdlPoNFeyKbjYHYa8MMRPTGAZfZmlg0xM4VwKnz8KNBNBxrMwHOGaMTONjoTX7tvAeraG-_-T8XLvXKSl9m4ExnEWAzQxE5nybZyGrnYWkhOiYx9f2YhJJj5pgZpr1Y-opLCS6bUpEf89DEgUvjwPhRGBADQuNJT4O1kB1pUf6gtPAlafEGpYX2cUBtAtrSUm4iLqD6rmcZrNoRI3QonrdOoG4d5RjdDb-OJL_LCIOS2gmQBsXmlUFDAAr81bS4WdFsCoi1zTAqG253qosqqcvqr8HJ-FsO633X23J4NM6nwKrA_xnI3Z1GSwW-0b4A39Zjwvc9KSIuwFeLwSaJKJREuxIMGosImDbhajeIXBOCLxd74OeG_rpi-JcxWuQxjNaTOh2OrZogDli7vc3yt8l6XFEhvX7yuUH-1M4p4P0aiAE2K2xc_b1p-AUQOGouqAG6M0Zm325vrijidrZHI2nA-4uoCJXwQhVz8LKhDSFe4IE_6AZEhsR3fSNNKJnQkQoYmDoiletJ7S35gnwo9X3U3R1dyqF1chGz2xNnept1ZKJZ2Czp3N0RXer6BDPk7Z3CpW2XcvREiX80yTFsWO_62ytUZhLT9vJxs982MQgFkZrewCCinda2l8usyJ3UyYyzMawCpv9pBrr5oTPcraH-lg9cxG1L8rqwCamjm8KM3l_nTy-qPDPOOSK4bUA0VVRyIQSVkRsoX4OHJiWEQcSnTDFidKi9iIdgXVQQBJ7PgOchAPKV1sp0Y0jF2wZELZeysHV2qOtEsM0D81sc09pPfCJ7Slnam-CtjcQnnPduMD5By4LVBT0zWTJ4xO4HUTG0vfk3F-IUO1x4unt0sj-6MKayCYCD5GsCDGijOwj7yy-2nAM83iWOJNzlJgSV6kc08ElgXGZAz7KYUOFhCA7hgwhcEoLHw7Sv3VBE1BBp4tB4nHV1rxQt3SsHla07kqBtC7xjGT3kCZaFz-qckMcz5IlqUfl0hH5A6ZxMJlNMntVaEpQrrjPOC0c5pY1dS1Rd03JeMjJr1AdgngRBFZdHK-G0075L_f6jCS3eo4cO9SXM-OIq-QL22B6ewaiqo4P8GGkHMaRPlWsCxgkLuOY8FgyoDFbVl5IqL1ISokcIJ13DNeUxcX0vjrRe1kF9lRFHT4-c4VIkMlrK7jdBUiPn9gZGQLAuGz2DBhZI1gzUqUtqipZYp2yv2cPC33jP3pZ9QF15e2_rz57H7889vx9jWvaryUAIRsAZEVZfp1-c8zwwy4UxnNI7KmMkKIIOO8U6UMbn3IsFDQn3KGZHZURDYBkZmFgJHillpAu6xRjjUzBwUkJzNxBGBst7TXN2Yp3itqOn-B_83eIq7ne1SocrbCqiOaZVi25d1Ub9JhBoRzbAQta-dWo9Ke8UN3Q3tbpOX8cuzsIpnWQQhiEGazWM75FxDJ6PsfYWy22Ale1z3POyz__0LCh7dNKewQOhezozKytgIgZKKZCuL0zsKsa15zLtRsBNIVgeBuFByKhUGjgupsSVQkN8oIWWnueTiPlrhQHnS0WSj7OVrqxOIUJ161fU8Fa5WmerfOYTLVU8MqcphlgUPLYyAtRdVZLzV9lkf5Dr1Ld9cZhV40Lbl5A578JpOi1Hp9MCdCXu2h3emNvZIMmMK1xNpBsGQehLHUO0Ggjl-dww4GWuA-s9GRJ5AY1lAIyrrIcPTCtE2DWk7bp0IZd2fhZ2i_hDPrFtZEs6mH_LtHVqA20jOsvgdjbQkdG7adKRta181voW4L4u_3s4qI_6fQn5n0C4r-qLHS4A75gLXE18DwI2bfCkV0yiOApiFQvXD7Q03FVCccGN9GKPC98FX0sRqgSeqYP_giCCGG94_0qSPuLXARFfSfyZZ9NN2rUpz20D2dDSBm4ryGj5hLt_Hcr3HyI50MWXDPfirQqAsD0aXVQ3lwko3Y9JaTpFmsbTgS9EQN0whsicBaGmxgO7BFF9QEDwJYk9E0ehYZJANOV5ofAiFgLpBVNLJspfmKVdZ7drh441erC7wU1Z6nkWt_dH1amvqQ-7dmv3sX3NweV_NF4h_bVNZ0WOu5JlAmw8gfD1BpwFG7K2MS8C6VOPIjajiEa-hBAGXFHcYg-YlAyiU0-FkSBUgoAFOgavwQ-iyDMsCgPBBo9QUHdFUnBuLT_U0aDJZucZIHzV4diJp2lqi5Vm0ezsMe6oQgg5oqyTAm-qqUHfGFt06kT2qj_HWLJtO1hdN9uUTXMgm3VCZpJsU0w51ryWdRqdLyJWCJqNjv6jvh8hDzik1aa1Lzh1acgI6NbIQBgRSQbOH6jNUDAmNUSsRLkghkGoOFPc50xrroQBmsQ-XffAF21lnea1FU2Aj0S6-zgYp38fB_sT7WvQ4YRJpYvRXpr89psu0B_Pr7PFbgYFtTC4mSEVYctRtLgriBa0E0OHAthcKqW0CQjoNElNxCAE8iMeUMHdkCpDvZArGboqNIboOASD4gmCJWIBHzysQr125HOrjFgMbDoeG_CEbS3Y7iUIqz1C1TUzNmA9t28erI-HgN0BOCAUN52Kfto5odI6OVIBoGo5RYwpHwysx-BqgHarQG7wzChGzPZdSKMnvn9LhFo1Lfj-30VBS60aR08kuSVi5ybG1-ugv9yT9La32jUuDcZWSxs8w0u3Zndph1a5fQbA4rav_rTOOL7KQ8w__n3e4JHOGxDWI_nHeYbs2Pj778H1A44ERRAE3bxEIFXoxZxERukQRC8Gs2QY5ywWkR8GbiRk4Mc8DkMS4v0TsaJ-QKT2PZdHOujGeR7pTZju4T8rHJEmgw3O-Jy98ZjVjT24cmeCdDgP8YST3r0aRm7ZoL6TYH_2bBXpS6F_TBC9b3WSLvzR5Y08CU6noUR5Uej7hkZKa6mESw3zQ1dHyqOe5lGALqovlM8pjz0tqStV4AYmMLcq7BeUF0sbebQ5DWhjuvaOWYxvQZuC4_n7E2m1LTgBJrusxqMngt7KZja_dVRnV7HVSEDuqU_rx_bA5RO-zq7d2zx7im5OZuoMSpMDtUmrp9aLsq-A_pMmOr-bQyL69vD28qrKJ3V1uI5a23dY-WVfPKY7xfc61oEmHvU9yXzwjYOIsCAOgTOJCVwasEDKGDOnoI94RCLc3YkNuM-gnCBWXZU2bbGluk9k1FUjdYOFCyu84aqKWWBUx7PfMSdAZB8NDr9hNgjN8-LQDSCmqH7rkuMAVtJJCwWGM8-oCMJUpoikjMYU5B7w7wqsAw-V9EnkCx9cdOZ5QDtOBZGhF3A_iumjEQN9CowvNYq1cfLCaWZpzcY27nBioKBTwH50g0X8dQi6FH3MA1YyaEM2odTDTqmQPkqdoRa0N_AtKHWQaAgyowWpTrIwQebqRJlgzpWgLpM-dyNjwlhqE4dAI7DcNOLwDTxwV8eu50chPA68wItAd4MDbiAMXZNU4j5yQ8lwRkHwu7cO_jDpoX0hFR5zN2A0j_M8Hu3rIoPp2ftrOwViK0IqofitjUl2R0ilXAh8WuTlJgiEkhA1aUY19UXMpKu92EgiOROUMkIiEmhPucQofD-9odqNReAbo2gkBvclu7tJeO1GO6YSYqCe-olsl2jN3o7VV-hVczHolTrf02kxr8Oqd5-Gz67J2dG1UYdddutXPNXOX9uD8OTt3ESddO4_1NccwO5EVU-4GCgIIsMuBFtVPbfAHhFLIGwt3ZJPVP4dMP1xd3Uw8r_mro72JrLwhM9o4LvcFdoPhe8GlMbgd2sW4oPIdVmEhU5MuT6LeEyx7iWS-JpgF-_wuPvejyPcQ376990ff9_9ge-DG77CrPuquBTcLbzc7Sz4cP4Gr3et3yM9ezEIvrxraWvHad0vN7te7k44yzDoPWAsusi7uli7_hjz7lv_JnPfM2m1or833L--lW52i10NrfYc29f2kTUXQvsWwh6BkPdAKv0eMHgfjOYl8gBg-YLEGlh9GKV1Z-JssHsiQz7CQuSaC2kumWwvpHXv5GYL6eUOsgmb98nbJuxVv1rmQVPokTT54BlsIuuze61nHRi535jskfQUefDq-SPwM3kEJcM35INFc389oj1owD7efwzMrcd7w3aipVbJ_VbxUEvHNkLj_P2UD2Ghfno-XBTEgyFsroxa9KOrTEFzl2_bFLSu9102BX0A6nuIOwAWVxOvA6C-GrkDYHFb8p3GaJiHW4Rj9yO9eBwepA_VCPIR9CB7BK3C1vQvmiun2yRt3UK9Bk_UF0d3HK35VdJruid9OuU-mvV7ePEtzlQP4Cv2QCXfQgeR9wHQwgMR90HEY4VV92Hu1twfwgvyocJNHkfJPBZv38v7qN_TPevH19ZR3X6EPYQHNiEEbn63OYDezz7QxyHdY6j3e3LRope4HwrYplhvTZTwh9CbPw7yxYMdxI01QIvv6ENEdZOp1zWpLdx3LsOavZjIlkngp_08i5PLOiuYXU2rBgomBe3OpD3RCOTccoI8T43OGvPw7FYXg7uzJ-Vejm9pwJdTZ5cvt_Bi0J624bSs8slpHrWa2uy1vULsuXOhM7BF9gr1c5Mm4Wi-caov4dt-cVNW9sCLudXUns4sTLNp-rT5M7ukzFatPR_NDv26iwZLe2bz3xf3duB7xNJcR4tn3Q2gdrUgE2vsdOLB3Vnmew7zLNW4z4YntpCEmMDG3fp6bbtppQt7o0hdK3-DfB6ONW6GmWIBZJHDnv_0IasvVsPXWo16SHKlMxgnz071L3lxlEd30jDQyCJ3k3rGSXb3_l0GDFeaEGseo6MC91rW5KyL5DcDdC1Na8j60ptVi0myNRczjeP5S5bvms9kfgV0_U5VE10gEffxMDiI4XQSmKK1AbU8zmE6xWtc-sex5B8DJ5mis3rcU1zAVq67uj1yXM2Ki05sjT41Zy76iNVdZhWoy0MR6tcq_8WzmYJ58exMV-N38d40SfFk-z9H_wNCuge6
```

**Comment by QuickStick123** [comment] 2023-01-16 00:25
Seems to be caused by us setting crit multi to zero while using EO which is probably happening before us correctly handling perfect agony.

**Comment by deathbeam** [comment] 2023-01-16 06:36
Well EO says that ailments never count as being from critical strikes so you get no bonus from crit multi either way. If the behaviour in game is different that sounds like a bug.

**Comment by Zarni222** [comment] 2023-01-16 09:24
Yea it seems odd... Its very hard to test in game in great detail, but I would _certainly_ notice my dmg being reduced by 75%. 

Anecdotally, I stopped using it for a bit because it did start to feel like my damage was less, but maybe by only 10-20% at most? Idk though, might be confirmation bias at that point.

**Comment by lvlvllvlvllvlvl** [comment] 2023-04-10 02:35
l tested this using plague bearer, with Winds of Change and Plume of Pursuit to ensure that all of my hits were crits, and l can confirm that allocating EO definitely removes the crit bonus from poison. Without EO allocated each hit added 10 plague value, and when l allocated it that dropped to 3 per hit.

**Comment by QuickStick123** [comment] 2023-04-10 02:43
This sounds like you got confused then closing.

**Closed by QuickStick123** 2023-04-10 02:43 UTC
Labels: bug:behaviour
