### ISSUE TITLE
Add Atziri's Rule skills simulations to PoB.

### ISSUE THREAD

**Issue by nayerre** [PathOfBuildingCommunity/PathOfBuilding#2722] opened 2021-05-03 07:40 UTC
Yo. Add "Flames of Judgement" and "Storm of Judgement" to PoB for effective dps calc for the skill, so we can check dmg of both skills. Ty.

**Comment by pundm** [comment] 2021-05-11 14:34
Duplicate of #2677

**Closed by pundm** 2021-05-11 14:34 UTC
