### ISSUE TITLE
Bulk upgrade all trees to latest version

### ISSUE THREAD

**Issue by Wasabi375** [PathOfBuildingCommunity/PathOfBuilding#2563] opened 2021-04-16 10:15 UTC
Upgrading old PoB setups to the latest version of a game is kinda anoying when you have multiple leveling trees. 
Right now you have to select the first tree and click "Convert to 3.14", then select the next tree and repeat.
This is fine for builds that only use 1 tree but when looking through build guides with leveling tree and multiple endgame alternatives (cluster, no-cluster, etc) this takes a lot of time.

My suggested solution is to add a "Convert all Treees to 3.14" button to the "Manage Passive Trees" Popup.

**Comment by ppoelzl** [comment] 2021-05-03 21:35
Duplicate of #1392

**Closed by ppoelzl** 2021-05-03 21:35 UTC
