### ISSUE TITLE
Granted skills in passive tree does not show up in Skills list

### ISSUE THREAD

**Issue by meatballing** [PathOfBuildingCommunity/PathOfBuilding#213] opened 2020-02-23 03:57 UTC
Currently only affecting Bone Armour in the Necromancer Bone Barrier notable. Not a big deal since Bone Armour doesn't affect POB calculations, but something I noticed when adding more support to Bone Barrier.

You can grant Bone Barrier in an item modifier and it will work fine, so it's not to do with the skill, but the source of the granted skill. 

**Repro**
1. Update the below string in `Data/3_0/ModCache.lua` to grant the Bone Barrier skill
`c["Grants Level 20 Bone Armour Skill"]={nil,nil}`
with
`c["Grants Level 20 Bone Armour Skill"]={{[1]={flags=0,keywordFlags=0,name="ExtraSkill",type="LIST",value={level=20,skillId="BoneArmour"}}},nil}`
2. F5 to restart POB
3. Select Witch class with Necromancer Ascendancy
4. Allocate passives to Bone Barrier

**Expected**
Bone Armour to appear to Skills list

**Actual**
Bone Armour missing from Skills list

**Comment by ppoelzl** [comment] 2020-07-17 15:48
Duplicate of #88

**Closed by ppoelzl** 2020-07-17 15:48 UTC
Labels: bug, duplicate
