### ISSUE TITLE
issue importing pob or viewing old pob..think cuz of glorius vanity

### ISSUE THREAD

**Issue by straylightd** [PathOfBuildingCommunity/PathOfBuilding#4572] opened 2022-07-12 16:15 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

i expect to view my profile/pob

### What is the actual behaviour/value?

i get this error https://i.imgur.com/GLJcAYw.jpg

### How to reproduce the issue

import my charactehr
or load my old pob
im pretty sure its vuz of the glorious vanity 

### Character build code

```shell
https://pastebin.com/KLkJkRks
```

### Screenshots

https://i.imgur.com/GLJcAYw.jpg

**Comment by zao** [comment] 2022-07-12 16:24
Duplicate of #4570, thanks for reporting.

**Closed by zao** 2022-07-12 16:24 UTC
Labels: bug
