### ISSUE TITLE
Windows 10, window scaling issue, changing size of text, apps and other items. 

### ISSUE THREAD

**Issue by Silvok1** [PathOfBuildingCommunity/PathOfBuilding#977] opened 2020-06-12 12:12 UTC
**Issue**:
In windows 10, when you have the Scale and Layout setting, "Change the size of text, apps, and other items" set to anything greater than 100%, the display of POB gets cut off at "offence/defense" pop-up menu where it shows only "offenc". It becomes exceptionally stubborn in that it won't allow you to run minimized correctly. 

I know you can scale back the resolution to accommodate the change in size. I just want to give others a heads up in case they have run into the same issue. 

**Device Information:** 
POB Version #: 1.4.169.2
Downloaded: 6/12/2020
OS: Windows 10 Home 64-bit
Resolution: 1920x1080
Laptop Brand/Model: Acer Aspire R7-371T
Graphics device: Intel(R) HD Graphics 5500
Processor: Intel(R) Core(TM)i5-5200U CPU @2.20GHz

**Comment by ppoelzl** [comment] 2020-07-04 14:15
Duplicate of #644

**Closed by ppoelzl** 2020-07-04 14:15 UTC
Labels: bug
