### ISSUE TITLE
Show Node Power doesn't calculate for anything but "Offense/Defense" since the performance update

### ISSUE THREAD

**Issue by vrtrtr** [PathOfBuildingCommunity/PathOfBuilding#7472] opened 2024-03-26 14:09 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

When I press "Show node power" and select anything other than "Offense/Defense", PoB should calculate how strong each node is (e.g. Full DPS, Hit DPS, etc).

### How does Path of Building behave?

Since the performance update, PoB doesn't calculate at all.

### How to reproduce the issue

1. Select any skill
2. Tick "Full DPS"
3. Press "Show node power" and select "Full DPS"
4. Nothing happens

### Character build code

```shell
eNrtHFlv4zb6efIrCANdtGgOHZbiZJMuHOcEkpnUTma2TwNGom02tOhKVBK36H_fj6QkS74kWe7bpkBrS9_N76bRs_98TBh6I2FEeXDeMg-NFiKBx30ajM5bz0_XB53Wf37ZO3vEYvxleBFTJt_8svfpTH1GHsNR9BlPyHmrj4MRCVsIRx4J_N78xWcekBZ6o-T9gfvw_e7h8Uv_qYUYeSPsvNVpoSkOxJjw4AH_zsMb7qc4E0yDAfdeibgJeTwF-VpI4HBExNdUYvs7SPyCA5-KFCujRoMCNW-MQ-wJEt5Lxt1YcC2PCGPSApU-nT0yPCPhQGCB3jCL4Z3pHFuH7nHn2DJPzJMWiuDdeasLBsMjcokn8O_W0Ta4F3EYiTICgN3upIiDKSH-Wlj30EkBH0NyNRwST9A30gup6I1x4JEqmBWgzSL0Q8wEnTIKB78WwzBSjNtS8pZr24cnlmVbdts9yYz2xAVml4-DtXhGEZKLuhy-UTG-YGDhTVw24N6NAirIlsiPnEY8qKVfJeBezBiEayXYPolI-IYF3SzIGi16fPJCgxLrHdpZEIQEfxlqL-1jn8bRAxEhiTY4UYr6gAPc45Eo10hCPpIQspHYiGC6h7kwS7AGxOOQxeoyqol5T4ekOmQVZRYR6kqznR5Xg6pwtQlvJ1Af8mo1yAGP2Wb3aGegYn2W61gp1CX5WB8CpjWPtz82Qc653gUVtLgkb1yG7np6dufwxHQtx4Wy5LYL6eTq9nGDHGZWV8aziHqYPeAPOoknkMyf8CtZz7LTmTvWaCwCyET1Ua9pSOpj9Tjzt8AaYx5VRbOsXMqgwS20IF3Pi6HDmFUxpoy1Cs45Jd6pBL0LvKpUn4NQpfINzcICRh8CS3YlL4xUqeJFJkl8VssufTIiQcJuVg3lnhBvfAMW7mOxXrzOST4ZVzSsBN1k2CLRKnY1jNUYZUaCTi-PWNNMEqWameZ5NSDhaDYYU8L8etCpWD08rWjmPPYmc69hV8sUedSaJvmGQ79aYakmk3mcCfWGo025ecFcGrqSpR4ItKyA4JOSvtqYDwf8dzkasHpo3XDC47CiBhq4kgJpTdGTUJ_4sScqmeqCwVxYVXqQirFaGF0hsPd6yf0RqcWkFkY2pSnUQTydQr6QZ19C4MA18uUROndapdOZw34Bx90UvzkGspJWZTCHrcEg6w2qcllAqKOLrO-VlZkDl7Ewlw70AVLDBBK-mtkfuF93nLqGwa3S1KYA89Nggjl4pYyVMLnzCBqMYVRGEYSrB4DwSeI94lCFfMjfK0QwfwfrjOVWZv34Zq-Chk6rgoIhCf6cVaZfAK_E4CrwoWmDcKvMYxFjzuaJTiAhR9ElFhj5SUv-FYcUB8JUfrLw0NLOQ3Doje_B09QRqIXXNWWChJfwTHLS8mZg15ixF8hPAC4Znx2pZZz89JkLEklZ5NP0y9lTSAjCaarxJFMlr_yCYO4muXWa1ZZ7twiYz7Q7R1Ko3FLvzlfSBNwn8KptnbjtfdexrPa-Y7Sdk33nxD429l37-MTZtzuua-23HcN24K1tQ8vspTTkJKQmOhzOukXyAWVKwE9nz_179eHTWIhpdHp09P7-fjjFYsyH5AOK2KHHJ0dTQAPVDpTzHkh9jrrwdzG66164w-fv0e-B-_b6J3vHb25nQOHVuSJ-lFI_00vG6Eh_k_EeUlBPn-qRNJMys7Sj_KCiK4LDHOKYiRsyuderzICHk2w-AvXG_L3LxK8xZlTMAAzsNcQsIvKQQ4kXXcwgWJMVZHpCkviACO0aebhr2dUUdy2Kh6wcGu5pNpWH0r2_b-WkSwQAkxvJuScsEPVTX0geIoZfpCZyCyznAT-VTa5iu3P5lHA08Fjsw2ySJJ01sD3MvCjj8-kMJJrnmewlhJkKCXn-kJl0YvojJ3k-N5mpfDeMv2BmpZzzD830ocfjQOMk5CSLS22dJT1HZCJfPxCBfYjiozsB1j-SR3CklIFPmXRKoIK8yUpbShvgSRJsWZ5N3EsTSlwrOQnlXtqt5Me7iTxQRD7kf6TKs9RzVLz3eDCkozRPeWQMhZeEiuV5iwRkMkv6Kc6YWsuDOPHkhYTnrWNjnuAWECfZLlfuJElI_IFsgnrSfAPChnMiprOWiOKe2yNnOCUoSYOZgbftzfDFxrG6aGkvniFYprkWI6Ijyr4MVdECW8jqMGdUboJF2WxjM47e8OeOykjSe3beKpN_peQd_cn55DfobkzbOHScdvrXUi-SdOQm6QGq1iWFXA610ZPpQXu6BPwvUGhDc9Bpm3byl9aZgQjT8qIcEOHpFHJ0lsEGMrn5b_KQnzhn89QGeVPQQC2SIRMxlrisjHOl_F0wjUVqYOnx37XCy6bNQ05o5H1_iYdDeWcjK3Gobqiurq-vek93X68SlAFR84NKbElsMXgkkwBjeBqRuQJR_BJp6POWNKkCv4S4pyxaQe12fp6baSk6c-hlSjBoeiGVvrSZ0NUHCcGSowx-mZS86KgijpZFzquyRVllK-16m0npoagHzUFuos5TkU5fRkTCrFIFUh5mpcZNoNYctix_0tujSkYRslhChqZD6mmslaeeJrIS2xR3f3ka6lqpDF8DLSPrq6Ey7ARqhVXVtVSpVTXUCv8iHp6VYWugZeRs_1JGIAPkAdh7BaUrRrqUyYGq9GQ_80A5O8RNhrJM8AGySdLdlhH8IkthCrtMCWIipC-xKA_nHOQKW8l1cJmZ5ivjgi5y4VmCmluKFuya3wKWZaPljeFCUislkduw5VGTibwEWUOtPIKkdSgxf36DVTBC2hGU6F9Y4hWCRCXX7hunfpVMsQjemKBabO1ALrm6ak5mcZe1guI1zHmvpfGSQFVC1x1NHvtZUNnqNyMiI64ZBRl4ayn0F7uJZfz-6hYi3VVsRi5uNOrjZ4uOrSnodczW6KrxXpO-YYBT7Wyl_J0BN6M1EHFwCSYRq_16LallzZRUm3JAbVq62G1QVMexvtSslKLy959NCEEpvl3d89WglK1Wbwlm8hcznDUjuPqed1s9uYhw4F_Ki6E6iq4IeOLxeAq0UsG-5Jt2GAWTOepMLSaSlZH8nG6M4ojoH0p8I3jKA_VYS6xnKgBNVy1yKM-vgPrwWMxO0fPnu1-fr_a64QsP6cdeN4rkgi1AF_x9L1lcnqLHkCD70Dk0Fh-dLD8yzRXPjvPPenEIqULs6XGN-Ch74-wl66tTZBl7yaLuFN0cZP_sqXG3T_44Ra61BxMCox6VMObeX4mmp_bff4VyEXIK0_LfP_9oOgeW89MPSHCkl0VIjiVyn4Bg7qWvBM1_2DYnYuaJdH0_Qj-6xsGx8ZOk86PZMQ4sE76kqwmkT32Ob-3b--1lGifOgWk6mojVBiKus4GIs0wAGJtGIoVlAAFrEwFzH-TIE0nxf5ALvZBg8EyUdDsIBj0I30VkcASkh8EIDSkcp4Ww71PpwcBQXRxEizhX8rIUmW6y9I3QjMdoBE0_ugslIzJk5IMAPR6iTgq0SMQ2fkATDgy1UuidirHmh2SKQVigHuMRQWrrhd7HlBHFaIzfSJHRKtJz_bV2-0gOuwiiEaU3OkhNyjnKPkcBFxUY_JaKcY1DtQ-sR8QB17mBQwMtlb8j2wArRGOkZtkiXJXzQXSYWSb4F6SK6N9Cq6uohkT-YIHNioTzXmMZB3bRaTTLxEJNyYNHHpjuJq9MWGjiYLhmwi8ccE3aTyGWZ5JcDHBZkZEY40DjYOmxNFKL5iJe8bDldviB-9p5dWJGSujzFkid7o8LEFYphF0K0S6FcEoh3FKI41KITinESSmE_KFoGUi5Vc1ys5rldjXLDWuWW9YsN625wrZn6upiRc23W4njrKr5XzkT0Bh5qE-HUI2nNCCryv6KGm8Z1eq5Xauet_P13Cik1KU6aOoCeOwc2LIAZr8TWKqA9hpUF1LOsWOsQi0kpgPTWZv3iiK6UFT4cIke6vEAyqG0C_BVvzRYISRkwK2xJXMT0D21vJRwUHG81z0oQmEBBXmQpPS7fJ_ytyqnqryKMY2QbiY1ILoKyIRCqcYRvOTxaIx8aMqlgLZRLNBFmj-3DdVyJa030j29VFEL8P_0Vz_9LYT5_FK3ZBCA-YTx9HJFbSgQ2JIKff1p6I-PL8_9--QWqIiR-IOFBu94irovM5gRoPypaEZ2DULQfr-BKy1QaO9KFHcbQjtXx64vhblSHbMGoQvuz5Deei6ScbaR55_Sqb2DI7J2Yxer8Umbu3LcWidNmGhyPBeci6iJLW4JmxDxj9mi3VQXp7EubsPjcHcQcTvLz86uQtfaQejuwjJmUwexax7vFjLPUawylO4kZkTU9tktDmO7tFk7S9Y9nhrwfdl2mnURdlQv2jvw3Z21OlbDFLV1VqiBpxtNewdpo72rHNa8NuwiC-6iI2uuSeOmwdzVqbhNJXEbt3LNzdluTGEXbuFum2AaW3AXw5dZO7s4tTEatw_t2ix3lr7s3VQyu2Hx2FFB3dF827Rbbzp8tRuHTok99dZH_25c_igY-2SgfrX7jchlYaTvitUV8S97Z0eL__eW_wFepCdL
```

### Screenshots

![POBug](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/7561379/5e00d8a9-ff77-4e3e-8279-914f47a936e3)

**Comment by Wires77** [comment] 2024-03-26 14:09
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/6764

**Closed by Wires77** 2024-03-26 14:09 UTC
Labels: bug

**Comment by vrtrtr** [comment] 2024-03-26 14:10
Not a duplicate, since in the ticket #6764 the power report does indeed work.
It doesn't show anything after 1 hour of calculating for me.

**Comment by vrtrtr** [comment] 2024-03-26 14:10
But thank you for your """"help"""".

**Comment by Wires77** [comment] 2024-03-26 14:12
Putting that you let it calculate for an hour would be helpful to put in the initial issue description.  That does indeed sound like a different issue, so let me validate.

**Comment by vrtrtr** [comment] 2024-03-26 14:13
Oh, I missed hour, but I explicitly stated "It doesn't calculate", not that "it doesn't show colors".

**Comment by Wires77** [comment] 2024-03-26 14:14
It seemed to work fine for me after less than a minute: 
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/1209372/0d00715d-a5d3-4d05-b3f7-57242b5c3fad)

Is the window in focus?  Calculating power slows down massively when out of focus to save resources.  Otherwise what are your computer specs?

**Comment by vrtrtr** [comment] 2024-03-26 14:30
Thank you. Sorry for coming off a little harsh in the beginning, but it felt as if you hadn't actually read what I wrote.

**Comment by Wires77** [comment] 2024-03-27 13:09
Is this still an issue after 2.41.1?  We didn't fix anything specific to this issue, but did make improvements in performance, so it's possible this got fixed as a result.
