### ISSUE TITLE
In 'OnFrame': Classes/PassiveSpec.lua:671: attempt to index field 'nodesInRadius' (a nil value)

### ISSUE THREAD

**Issue by jfo84** [PathOfBuildingCommunity/PathOfBuilding#1627] opened 2020-10-09 16:18 UTC
I wish I could paste error text instead

![afbeelding](https://user-images.githubusercontent.com/11723485/95607121-9307dd80-0a5b-11eb-9571-0e30990cbad4.png)

**Comment by jfo84** [comment] 2020-10-09 16:20
The error occurred while selecting cluster jewel nodes with this [profile](https://www.pathofexile.com/account/view-profile/Casie0046/characters?characterName=%E3%86%8DWTB%E3%86%8DSULPHITE%E3%86%8DSCARAB%E3%86%8D)

**Comment by Wires77** [comment] 2020-10-09 16:25
Duplicate of #1562 - issue is with thread of hope in a cluster jewel

**Closed by Wires77** 2020-10-09 16:25 UTC
