### ISSUE TITLE
LoadDBFile error upon launching

### ISSUE THREAD

**Issue by Felkin1** [PathOfBuildingCommunity/PathOfBuilding#2740] opened 2021-05-05 17:17 UTC
I seem to be getting a LoadDBFile error seemingly out of nowhere when I try to launch the program. I've tried updating and looking for the db file itself, but no cigar. I was definitely able to run it a few days into the last league after updating, but then one day suddenly the error popped up. I assume this implies I managed to corrupt the db file? Where exactly would I find it to have a look.

![image](https://user-images.githubusercontent.com/19386764/117180816-40b65180-addd-11eb-9852-19f12195a35b.png)

**Comment by ppoelzl** [comment] 2021-05-05 17:37
Duplicate of #2678

**Closed by ppoelzl** 2021-05-05 17:37 UTC
Labels: bug
