### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by OrdinaryGermanGuy** [PathOfBuildingCommunity/PathOfBuilding#8157] opened 2024-08-11 12:19 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

Import my current build

### How does Path of Building behave?

It shows me an Error Message "Error retrievieng character list, try again (Response Code: 403)

### How to reproduce the issue

1_ Import Build Button
2_ Type in my account name
3_ Press Start Button
4_ error Pops Up

### Character build code

```shell
dennis_rezer is the Account Name
```

### Screenshots

![Screenshot 2024-08-11 141904](https://github.com/user-attachments/assets/6d6c76a2-71bc-437d-8bbd-a4a52b8d098e)

**Comment by zao** [comment] 2024-08-11 12:24
Duplicate of #8152.

**Closed by zao** 2024-08-11 12:24 UTC
Labels: bug
