### ISSUE TITLE
Unable to save/export build after import

### ISSUE THREAD

**Issue by jordantoine** [PathOfBuildingCommunity/PathOfBuilding#3670] opened 2021-10-29 23:26 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When I click save, I expect it to save and not have an error message pop up.

### What is the actual behaviour/value?

Error pops up, save and export do not go off successfully:
Error: In 'OnFrame': Classes/PassiveSpec.lua: bad argument #276 to 'char' (invalid value)

### How to reproduce the issue

1. Character Import my character: account JordanFH, character JordanSteel
2. Import Passive Tree, Jewels, Items and Skills
3. Attempt to save as any name

### Build code

```shell
Same error shows up when attempting to export build to create build code
```

### Screenshots

![image](https://user-images.githubusercontent.com/10980525/139511110-83aecfff-bcbb-4425-b7ee-6c1b9b311a5a.png)

**Comment by LocalIdentity** [comment] 2021-10-29 23:28
Duplicate of #3645

**Comment by LocalIdentity** [comment] 2021-10-29 23:28
Fix will be in next update

**Closed by LocalIdentity** 2021-10-29 23:28 UTC
Labels: bug
