### ISSUE TITLE
Auto crash on start

### ISSUE THREAD

**Issue by Keinaku** [PathOfBuildingCommunity/PathOfBuilding#4340] opened 2022-04-29 18:32 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When im launching pob it load, and after the green screen it appear 5-10 sec and then close it self

Im on :
W11
i9-9900k
amd radeon adrenaline 22.4.2 (and tried older version and without)
rx 5500 xt
32 gb ram
nvme for the disk

i have tried compatibility with : w10-w8-w7 administrator or not

### What is the actual behaviour/value?

When im launching pob it load, and after the green screen it appear 5-10 sec and then close it self

Im on :
W11
i9-9900k
amd radeon adrenaline 22.4.2 (and tried older version and without)
rx 5500 xt
32 gb ram
nvme for the disk

i have tried compatibility with : w10-w8-w7 administrator or not

### How to reproduce the issue

Start
See
and it close it self alone ....

### Build code

```shell
latest version
```

### Screenshots

![image](https://user-images.githubusercontent.com/89117196/166004161-f726e9ca-a6a8-43da-a922-1e30fb5e7919.png)

**Comment by RocketPop** [comment] 2022-04-29 23:08
I have this error as well. After installing PathOfBuildingCommunity-Setup-2.16.0.exe the program will run once. If you exit then restart it, I see what Keinaku reports - green loading window, then the large black window frame and it crashes. Windows 10 (locale is en not fr), 32Gb RAM,  NVidia 3090.
I don't have any crash logs. I can reinstall the app and it will again run once. Then crash on subsequent invocations.

**Comment by RiNkzI** [comment] 2022-05-02 17:05
> 

Hi i have the same issue after install Windows 10 Pro 21H2, the program will run once.

**Comment by RocketPop** [comment] 2022-05-07 00:14
If I create an empty file "first.run" and restart the app, it will open, check for updates, then run correctly. You can put the "first.run" file back repeatedly and this lets the app load each time. If I do not put the "first.run" - it will crash again. If I can help debug this w/logs or something please let me know. I poked around and enabled SimpleGraphic.log - but nothing useful in there AFAIK

**Comment by Keinaku** [comment] 2022-05-07 17:17
> 

whats inside your first.run  ?

**Comment by RocketPop** [comment] 2022-05-07 18:00
@Keinaku it's just an empty file. As a further experiment, I right clicked "first.run" after I made it - then went to properties and set it to read-only and now it doesn't get deleted after the first run :) So it's not great, but it's a functional workaround. It makes the app check for updates on every run, so that's slower but... 🤷‍♂️

**Comment by GamerysHDD** [comment] 2022-05-11 05:56
Hello, i'm experiencing the same problem, my Path of Building start and then immediately close itself no crash just closing is there any solution to that (I can rarely use it like 1/100) which imply that it depends on something maybe. My PoB close itself like 2-3 second after my screenshot

https://ibb.co/XFdqv2t

**Comment by Keinaku** [comment] 2022-05-13 08:32
I have some news, when i launch w11 and direct launch pob community fork, then it stay open, but if i wait a little, it crash immediatly, i think something make pob crash, but i cant found what T_T

**Comment by Sargoth9** [comment] 2022-05-21 06:37
Same issue. PoB will start and will crash within 2-3 seconds after each startup. I can click things in PoB in those 2-3 seconds, so it is not "frozen".

I tried using Portable version as well as installed one. Same result, even after a fresh instal.
I updated my Graphic drivers, restarted PC and the result is the same even on a fresh PC start.
Using latest version (2.16.0)

I tried using the "first.run" as mentioned above, then it won't start for me, but I get the following error instead.

![Path of Building](https://user-images.githubusercontent.com/105964302/169639241-c21ae5f3-72a3-439f-87d1-c9a98337f850.jpg)

PoB is completely unusable at this state :-/

**Comment by gamnedon** [comment] 2022-05-26 23:28
I tried a few things, like blocking internet access or the `first.run` file, but nothing helps.

**Comment by xerudro** [comment] 2022-05-28 06:34
I have the same issue with the latest release on W11 I5 3470 CPU and RX570 GPU, using dual monitors, one running the game and in the second one the PoB, i have 2 graphic cards, the onboard one and the dedicated one. I tried change the SimpleGraphics version with the one from AMD drivers issue, and i got this error on starting the app : --- SCRIPT ERROR ---
Runtime error in 'C:\Program Files\PoB\Path of Building Community\Launch.lua':
C:\Program Files\PoB\Path of Building Community\Launch.lua:64: attempt to call global 'RenderInit' (a nil value)
stack traceback:
	C:\Program Files\PoB\Path of Building Community\Launch.lua:64: in function <C:\Program Files\PoB\Path of Building Community\Launch.lua:17>

**Comment by gamnedon** [comment] 2022-06-11 19:22
This is weird, if I close Path of Exile, then Path of Exile works fine.
Does that make any sense to anyone?

**Comment by RocketPop** [comment] 2022-06-22 02:12
This issue no longer occurs as of PoB 2.18.1 
I have removed my first.run "workaround" and the app now starts up fine repeatedly.

**Comment by Wires77** [comment] 2022-07-18 22:50
Anyone who is still having this issue, can you find the file `SimpleGraphic/SimpleGraphic.cfg` and change the `con_log` line from 0 to 1? Then the logs should show up next to that file as SimpleGraphic.log. That way you can catch what the console is reporting and paste it in here to help narrow down the issue.

**Comment by sbsrnt** [comment] 2022-09-07 04:29
@Wires77 
Started experiencing the same issue however I don't see `SimpleGraphic/SimpleGraphic.cfg` file 🤔
Happening on `2.21.1` (initially started experiencing that on the `beta` release channel but I doubt it's related)
![image](https://user-images.githubusercontent.com/19862545/188788967-ba6ea90a-4045-4977-b7ff-05826518c96a.png)

**Comment by QuickStick123** [comment] 2022-09-07 04:33
That is odd it should look like this 
![image](https://user-images.githubusercontent.com/31533893/188789433-78f7a314-4259-431c-b9f0-8ce12d530e1a.png)

**Comment by sbsrnt** [comment] 2022-09-07 04:35
FYI tried clean install on 3 separate versions, granted all of them update to latest on initial start.

**Comment by Wires77** [comment] 2022-09-07 04:41
Here is my file, for example, if you wanted to copy it into that directory.  PoB might just be crashing before it is able to write that file though.  You'll want to rename and remove the .csv from the end (GitHub only allows upload of certain file extensions)

[SimpleGraphic.cfg.csv](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/9502750/SimpleGraphic.cfg.csv)

**Comment by sbsrnt** [comment] 2022-09-07 04:45
Well, if you want another ammo for the solution - missing `SimpleGraphic.cfg` could be one of the solutions to the issue as that fixed it.

Not sure why would that file be excluded during bundling though 🤔

**Comment by sbsrnt** [comment] 2022-09-07 10:07
Aaaand started experiencing the same issue again. Sometimes it bricks the GPU right after initialisation, sometimes after some time on window refocus.

In all cases the GPU goes to oblivion
![image](https://user-images.githubusercontent.com/19862545/188851702-247722bc-75d4-47b7-bd4d-c936992bb20b.png)

The config itself

```csv
Creating context...
Loading WGL extensions...
using WGL_EXT_swap_control
GL_MAX_TEXTURE_SIZE: 32768
Loading OpenGL extensions...
using GL_EXT_texture_compression_s3tc
using GL_ARB_texture_non_power_of_two
Loading resources...
Renderer initialised in 182 msec.

Loading main script...
Loading passive tree data for version '3.19'...
Loading passive tree assets...
^4Warning: 'C:\Users\seb\AppData\Roaming\Path of Building Community\TreeData/PassiveMasteryConnectedButton.png' doesn't exist or cannot be opened
^4Warning: 'C:\Users\seb\AppData\Roaming\Path of Building Community\TreeData/group-background-3.png' doesn't exist or cannot be opened
^4Warning: 'C:\Users\seb\AppData\Roaming\Path of Building Community\TreeData/background-3.png' doesn't exist or cannot be opened
^4Warning: 'C:\Users\seb\AppData\Roaming\Path of Building Community\TreeData/jewel-radius.png' doesn't exist or cannot be opened
^4Warning: 'C:\Users\seb\AppData\Roaming\Path of Building Community\TreeData/line-3.png' doesn't exist or cannot be opened
^4Warning: 'C:\Users\seb\AppData\Roaming\Path of Building Community\TreeData/ascendancy-3.png' doesn't exist or cannot be opened
^4Warning: 'C:\Users\seb\AppData\Roaming\Path of Building Community\TreeData/jewel-3.png' doesn't exist or cannot be opened
^4Warning: 'C:\Users\seb\AppData\Roaming\Path of Building Community\TreeData/ascendancy-background-3.jpg' doesn't exist or cannot be opened
^4Warning: 'C:\Users\seb\AppData\Roaming\Path of Building Community\TreeData/frame-3.png' doesn't exist or cannot be opened
Processing tree...
Loading item databases...
Checking for update...
Loading 'C:\Users\seb\Documents/Path of Building/Builds/prototype_trickster.xml'...
```

**Comment by sbsrnt** [comment] 2022-09-07 10:16
Decided to record whats going on and one thing that caught my eye is the first few lines that are not present in the log itself

![image](https://user-images.githubusercontent.com/19862545/188853306-266dff74-c578-44f1-8fd9-47400407e013.png)

Could you throw into csv `SimpleGraphicAudo.cfg` as well @Wires77? Maybe someone else will find out that those 2 config files are missing and will find it helpful

**Comment by Wires77** [comment] 2022-09-07 12:14
The Auto file doesn't exist on my computer, so I can't upload that one.  Interesting spot to crash, I'll have to see what is happening at that point.

**Comment by zao** [comment] 2022-09-07 14:31
SimpleGraphic historically looks for three configuration files where some of those have never been used for PoB and cause a bit of log noise.

Those are:
* `SimpleGraphic/SimpleGraphic.cfg` - for persistent runtime settings;
* `SimpleGraphic/SimpleGraphicAuto.cfg` - unsure of purpose, guessing it's for commands the developer wants to auto-run every launch;
* script-specific `Launch.cfg` - for config settings that are particular to a specific application as there's a shared runtime for both PoB and things like the Exporter.

**Comment by sbsrnt** [comment] 2022-09-07 14:42
Hmm... is there anything else I could enable for logging then 🤔?

**Comment by zao** [comment] 2022-09-07 17:14
The logs you see is everything that is logged, there's no additional levels of logging.

I consulted with @Wires77 and we think that it might be worthwhile to test my alternative GLFW3/ANGLE-based SimpleGraphic runtime in a portable installation of PoB.

Download and extract the ZIPs for the DLL and its dependencies from <https://github.com/zao/PathOfBuilding-SimpleGraphic/releases/tag/angle-2022-08-23> into the top-level PoB directory, overwriting existing DLLs in that folder.

This WIP runtime has some visual glitches in dropdown lists and the passive skill tree but should otherwise be functional. While it's present you should not use the updater as it will try to overwrite the files with the originals.

**Comment by hgranthorner** [comment] 2023-04-03 15:28
Experiencing the same error here - none of the above fixes seem to do anything for me. Any new thoughts on this? Seeing the following in my windows event viewer:
```
Faulting application name: Path of Building.exe, version: 0.0.0.0, time stamp: 0x606d1b4c
Faulting module name: ntdll.dll, version: 10.0.22621.1344, time stamp: 0x56ac692c
Exception code: 0xc0000374
Fault offset: 0x000ec67f
Faulting process id: 0x0x3798
Faulting application start time: 0x0x1D9664075282F1C
Faulting application path: C:\Users\Grant\Downloads\PathOfBuildingCommunity-Portable-2.26.2\Path of Building.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 411e247d-ab42-4b2c-af6d-625ba45d880f
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by Wires77** [comment] 2023-04-03 18:04
> Experiencing the same error here - none of the above fixes seem to do anything for me. PoB was working fine until a couple days ago. Any new thoughts on this? Seeing the following in my windows event viewer:
> 
> ```
> Faulting application name: Path of Building.exe, version: 0.0.0.0, time stamp: 0x606d1b4c
> Faulting module name: ntdll.dll, version: 10.0.22621.1344, time stamp: 0x56ac692c
> Exception code: 0xc0000374
> Fault offset: 0x000ec67f
> Faulting process id: 0x0x3798
> Faulting application start time: 0x0x1D9664075282F1C
> Faulting application path: C:\Users\Grant\Downloads\PathOfBuildingCommunity-Portable-2.26.2\Path of Building.exe
> Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
> Report Id: 411e247d-ab42-4b2c-af6d-625ba45d880f
> Faulting package full name: 
> Faulting package-relative application ID: 
> ```
> 
> Edit: I tried cloning the repo and found that if I ran the application in Dev Mode, it launches properly. If I disable Dev Mode then the application crashes as described.

Are you running LuaRocks or have otherwise installed Lua on your machine?  Seems to be an occasional setup that clobbers the search path and uses the system Lua instead of the bundled one

**Comment by hgranthorner** [comment] 2023-04-04 13:41
@Wires77 yep, you're absolutely right. Are there any other ways to fix this, other than un-installing lua? Could PoB ensure that it's using the bundled lua on start up?

**Comment by Wires77** [comment] 2023-04-04 16:27
@hgranthorner We'll have to take a deeper dive to see if we can reproduce it and see what is going on after league start.  Just to get all the details, you're running the portable install on Windows 10 or 11?  How did you have Lua installed?  Did the issue just start once you installed Lua?

**Comment by PotDucky** [comment] 2023-04-05 23:38
> The logs you see is everything that is logged, there's no additional levels of logging.
> 
> I consulted with @Wires77 and we think that it might be worthwhile to test my alternative GLFW3/ANGLE-based SimpleGraphic runtime in a portable installation of PoB.
> 
> Download and extract the ZIPs for the DLL and its dependencies from https://github.com/zao/PathOfBuilding-SimpleGraphic/releases/tag/angle-2022-08-23 into the top-level PoB directory, overwriting existing DLLs in that folder.
> 
> This WIP runtime has some visual glitches in dropdown lists and the passive skill tree but should otherwise be functional. While it's present you should not use the updater as it will try to overwrite the files with the originals.

Is there a more up to date / better solution than the above? Although this does stop me crashing, Interface is incredibly slow to respond/use .

Any more information I can provide?

Windows 11
Ryzen - 5800x
RTX 3080 ti (Driver 531.41)

**Closed** 2024-03-22 16:35 UTC
Labels: bug, crash
