### ISSUE TITLE
Bonuses from Animate_Guardian equipment

### ISSUE THREAD

**Issue by Ruba87** [PathOfBuildingCommunity/PathOfBuilding#1620] opened 2020-10-07 15:25 UTC
Animate Guardian, equipped with for example Dying Breath, does not give any bonuses. Is this a bug, or is the minion equipping feature not working?

**Comment by ppoelzl** [comment] 2020-10-08 02:01
Not supported yet. Duplicate of #1260

**Closed by ppoelzl** 2020-10-08 02:01 UTC
Labels: bug
