### ISSUE TITLE
Feature Request: automatically show minion frenzy/power/endurance charge checkbox when minion gems are detected

### ISSUE THREAD

**Issue by Ydoum** [PathOfBuildingCommunity/PathOfBuilding#2003] opened 2021-01-20 19:59 UTC
**Is your feature request related to a problem? Please describe.**

- Yes. Whenever I import my build, those options are never visible despite having multiple minion gems active, including raise spectre. Choosing spectres that generate charges doesn't cause the option to show up either.

**Describe the solution you'd like**
- Options should automatically show up when PoB detects minion gems / at least raise spectre gem active in the build.

**Describe alternatives you've considered**
- There are really none.

**Comment by Wires77** [comment] 2021-01-20 21:20
Duplicate of #1994 and #1691

**Closed by Wires77** 2021-01-20 21:20 UTC
