### ISSUE TITLE
PoB Accepts Multiple Watchers Eyes

### ISSUE THREAD

**Issue by Cyan101** [PathOfBuildingCommunity/PathOfBuilding#2801] opened 2021-05-19 10:00 UTC
PoB accepts multiple watcher eyes in the tree/jewel sockets, inconsistent with in-game which limits you to 1, IMO it should disregard one or have a warning on the stat bar

* **What happened?**
* Equipped 2 Watchers Eyes, Both stats/eyes were calculated for stats
* **What were you trying to do?**
* **What steps will reproduce the bug?**
* Equip 2 watchers eyes
* **Does it reproduce every time?**
* Yes
* **Provide a build code:**
* Latest

**Comment by pundm** [comment] 2021-05-19 10:03
Duplicate of #818

There is currently no mechanism to achieve this.

**Closed by pundm** 2021-05-19 10:03 UTC
Labels: bug
