### ISSUE TITLE
 bonechill

### ISSUE THREAD

**Issue by Wythe116** [PathOfBuildingCommunity/PathOfBuilding#1057] opened 2020-06-21 18:22 UTC
According to poewiki,bonechill suppoert should increased cold damage taken by Chill Effect.
Skitterbots-bonechill can't work  in my Redemption Sentry pob.

Please fix it.
Thanks

**Comment by LocalIdentity** [comment] 2020-06-29 03:55
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/190

**Closed by LocalIdentity** 2020-06-29 03:55 UTC
Labels: bug
