### ISSUE TITLE
Increased Damage with Claws on jewels don't work with Rigwald's Curse on POB

### ISSUE THREAD

**Issue by Schmidter** [PathOfBuildingCommunity/PathOfBuilding#2236] opened 2021-02-22 12:47 UTC
I just checked. The in game dmg calculations work with this mod. So it should work, but is not working in Path of Building.

**Comment by pundm** [comment] 2021-02-23 15:28
Can you provide a pob?

**Comment by Nostrademous** [comment] 2021-02-23 15:48
This is a ModFlag versus KeywordFlag issue I believe.

**Comment by pundm** [comment] 2021-02-23 17:18
I tried solving it, but i'm to fresh to understand whats going on. The mod seems to work at least for nodes on the tree.
Took a random pob from poe.ninja to see if Rigwald's Curse works when i spec into the claw wheel next to the shadow. And it does.
![Path_of_Building_r35jPx7q77](https://user-images.githubusercontent.com/54453318/108880804-ee013200-7602-11eb-8692-867120b1c3fe.png)
![Path_of_Building_qG2TUuaE8b](https://user-images.githubusercontent.com/54453318/108880817-f0638c00-7602-11eb-9baf-b3188d5f2968.png)

So it just seems to be the vanilla 'increased damage with claws' not working correctly.  Maybe someone more veteran can find out what mask to set for ClawDamageAppliesToUnarmed ?

**Comment by Nostrademous** [comment] 2021-02-23 17:32
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/012220f0030e163101583399d1d37c7bcd63507d/Modules/CalcOffence.lua#L424

I believe the issue is on that line. For example, if you look at some of the Attack Speed handling right below notice how it doesn't use KeywordFlag but ModFlag. Needs testing to be sure but I believe that's an issue. Would test myself but at work.

**Comment by pundm** [comment] 2021-02-23 17:44
I used the working attack speed version and pasted it into the damage one and it seems to work. That said i don't fully understand whats going on, so i rather have someone else do it.

Going from the ModJewel Flag:
	["ClawDamageJewel"] = { type = "Prefix", affix = "Savage", "(14-16)% increased Damage with Claws", statOrderKey = "706", statOrder = { 706 }, level = 1, group = "SpecificWeaponDamage", weightKey = { "two_handed_mod", "claw", "specific_weapon", "not_dex", "default", }, weightVal = { 0, 500, 0, 0, 500 }, weightMultiplierKey = { }, weightMultiplierVal = {  }, tags = { "claw", "specific_weapon", "one_handed_mod", "melee_mod", }, modTags = { "damage", "attack" }, },

I changed

{ flags = ModFlag.Claw, keywordFlags = KeywordFlag.Hit }

into 

{ flags = bor(ModFlag.Claw, ModFlag.Attack, ModFlag.Hit), keywordFlags = KeywordFlag.Hit }

![image](https://user-images.githubusercontent.com/54453318/108884513-f9eef300-7606-11eb-80c6-82c996b2cda2.png)

Don't know how to test if it messes with anything else, but if you think its sufficient i can sent a PR?

**Comment by pundm** [comment] 2021-02-23 17:50
If i remove the keywordFlags completely, the claw wheel next to the Shadow stops working.

**Comment by Nostrademous** [comment] 2021-02-23 18:04
The `keywordFlags` aren't needed at all. KeywordFlags are used to filter and scope `active skills`. ModFlags are used to filter and scope `modifiers`. Everything you are dealing with there is a modifier.

That should be proper:
{ flags = bor(ModFlag.Claw, ModFlag.Attack, ModFlag.Hit) }

**Comment by pundm** [comment] 2021-02-23 18:20
Ok, i already said i don't know exactly what is going on, but when i remove the Keyflags, the Claw wheel wont increase damage anymore, see:

![axUdC3zQ2E](https://user-images.githubusercontent.com/54453318/108888796-0295f800-760c-11eb-9b11-90d6268a3241.png)
![JmnhLFYMwK](https://user-images.githubusercontent.com/54453318/108888894-09246f80-760c-11eb-9a89-dddf8759ff8b.png)

Maybe i'm doing something wrong?

**Comment by Nostrademous** [comment] 2021-02-23 19:16
No, you are doing fine. It's complicated. What you find happens b/c:

Modifiers that end with following map to skill-type keywords:
	["with hits"] = { keywordFlags = KeywordFlag.Hit },
	["with hits and ailments"] = { keywordFlags = bor(KeywordFlag.Hit, KeywordFlag.Ailment) },

So your keyword inclusive solution is needed.

**Comment by Nostrademous** [comment] 2021-02-23 19:50
in `ModParser.lua`, IMHO, we should change "with hits and ailments" to:
`["with hits and ailments"] = { tag = { type = "ModFlagOr", modFlags = bor(ModFlag.Hit, ModFlag.Ailment) } },`

Then you can get rid of the keyword in the Rigwald and it will still work

**Comment by pundm** [comment] 2021-02-23 20:00
Can you do it then? I'm already struggling with git right now. I didn't use a branch for my earlier pull-request and now it says i'm one commit in front of the origin/dev, so if i push my changes to my repo and make a pull request, it would add the earlier changes again i think. Have to figure out how to fix my repo before i can commit the rigwalds fix. Sorry just started with all this today.

**Comment by Schmidter** [comment] 2021-03-02 14:14
Will it be fixed in next update? :D Thanks for all the feedback.

**Comment by Peechey** [comment] 2024-01-06 16:01
Fixed by #7037

**Closed by Peechey** 2024-01-06 16:01 UTC
Labels: bug
