### ISSUE TITLE
Power Report crash on Full DPS

### ISSUE THREAD

**Issue by AlphaJuliettOmega** [PathOfBuildingCommunity/PathOfBuilding#2619] opened 2021-04-20 13:23 UTC
reporting an issue.

**running version:** (2.2.1)

Please try to fill in as much of the template below as you're able.

* **What happened?**
* Trying to view Power Report is very unstable, at least 1 crash attempting to see Power Report
* **What were you trying to do?**
see power report for anything except offence/defence
* **What steps will reproduce the bug?**
select anything in the dropdown
* **Does it reproduce every time?**
seems like it
* **Provide a build code:**
```
eNrdPWtzm0i2n0e_gnLV3i9RHPpJk5vslt_2TJw4dl6zX1INNDZjBA4gO87W_e_3dIMkkEBuy5mZqp2a8cjonNPn_Wga_Opf3yepc6uKMsmz11to291yVBbmUZJdvt76-OHwudj61z9Hr85kdfUu3p0mqf7mn6NfXpnPTqpuVfp6y8NbTiWLS1V9mpEiX4HUjcyqK5Vnp_KPvDjKo9dbb_NMbTmBzKKkmv0WprIs38qJer11EQLyliPLUGXR3uL6jrkA1LaciUyyizy8VtVRkU9vXm-xLec2UXeneQSAJ6dn784_tFZOsvbKwPkvr85Sea-Ki0pWTgk_gDooQF6q4wTI38p0CnSooHibe9wjHtt6sRZtX07g56MwL26UiuYYaFtQgv9q2LNCHcSxCqvkVu0VSbV3JbNwIYbYxoPsbwB-Ok2r5CZNVNFibxDjeIU-ct0h4A95JdP9s4sFLz7m2y5GHseM_xlY-cJPBrn6nFRXuymY49FraMyTyyyp1EaoZ3lS5tnGkrURB4XbyydBkm0g2wxx5_bycYinMpN7eblQPEZDoG-SWHVAB8U4uLCDO4f4toPUbJ6pApJVZYegmX0UwkW1iCDs0kGW1bc2JCKDkPvq-4Ig9dYQbEMiPsjhSbYQAzF3DcEOJMXDHN7mlakLNtqcQxFMyJpEGb7U0CdZuGBhOIVp0I9ZoUpV3LYy7LoluiiNjW3ymUY8V5cqazGGtr31Dv9GqfDqCErjuayUnZ_OobjvrdWTBm7rSayj2qMlSuwQlnXEtxH3sc994bliuJhqIl19EbKN1kE_UlkHmSou7y-uEpW2TC_W6qyN09YdYTardMWxYuyxMt3Ksh1SPuF4vUA1Qide3GHDKih9gBKppTrOfibKWZH_oRuY9JF4O8Ukny6SI6UIrZW9hm-LjgfT6dnVfZmEUEpNV3iuomnYyV3EHzTJrBs7zW_VBALBdHPQ1i5W3UbuYIXcTaEpXlIBXRfYadqHgobb3aqS4fV-Hl0ua9pdu8qjMA6TApRWJq1SOBz5C-B30IrvyZtF6hhuQHR0WdJfAC_Tx95wMr68qjIYkqxXWcJYXmrQNUGlebm0yvPhstwCX15i2BrTtNMjc0YE3XYRp4IzdzgDXiddvEoGqXrpuN-RVIiGdHDBs_wOWLvSo2T5MHtt6FO5aE4GA_-wUNmPe2v6HXCrBQ6yaFpoT7deYxljdZlXL8ysrT-dTG7yonJgLq52wjCfZtWxLK9eb8mYK-n6zPcZlqEfemEchoxHGPnS86F1EJHLsfK2DOq5kukEtLdX_6oXlmGlippWGCESs0i5VKKY8TD2XRohLjmKvcgXkrkAgZrO89WeTMPSSHaS3UwrJzPj-iQpw6_BNI71UL4FkhZmP-Hg8PBg78PJp4NGGW2UUvvM12w6CfSIWP9_4fwXymRRJ8zTVN6UCub5WKYl0E6ixt8uoH6ElRU8jJfN0G4D_VkWYZGALW2A9WxoxbKZ1G0g9fRsBQjOIVNlr7AP9zdKO2Jpq7Mmh9tAm8nXCrIeV-0ENEOxnRlUKO-tIOd9kxX0Qap2klQXZzutnUIg1HXdDh5qbJEE08rS28y8Y8WH7vetBGz3ulYc172UFe2m57SBbeqana9BF2NtjX0VK_Biy2g2WeKDvFZZk4pn-e6VCaHSKSEfH6lJuXsP9e5Qa21pd6QDAJWwmALtSMVymurr76cyTar711tZkravv6k3Vs3V8iq_u5je3NSUdNiWoPc3b-pvdtKqIaKXmbFfC6d5NBumO6axNL8bCXRmdZIsTKcRjMBNmZ9xl8pAr73lXOoN1j1dZhpOVKYLeTQDLNNcb9YpCIhmY7a1jl5Cc_HLK-CrwTxK80CmeK7jZvsYeVsdADRfQBM60a7zvZTZ5TTJzHDzrZb3xAS60Rjwqib691NVyUhW8sVJBdp4oVXywrADn3qJ6NK8LFdYiwwq0rVJjwDLHBjGTpPMbHVfTCeTHOx9BvmxkuWkdq2fIrdpoMsUqqeuihvK3UvEVu4OsrVgbEWwBmAu2ScpU2g4nmDOVQq2MmlMp0a1log8aKo6QqFIQi15tEzz8O7i20pUY9UprVbQX5gAQCO3utV9QgJgD2l3Ly-K6U0FbngIKJvHwhAdvZthp-k5AaemYO1B3NKDdotpZXh6ghet0rD1pAXm071ppoC_3J0ezKvvp0mzlbGxJ-3DtPRo7Rqkn1geaoPvRFGiuxiZ7uV5GuV3T0lA0BHlWfQ5yaLH1wqD6hjcvykX7ebRvTPb33uCB4mHVP8bdHhVEu7mWrEbulAfDVtdN7hOjfyX9SO1m7Q3Rt5lF6m81wm1yH-oDAaIyVMylzXprqIaQfo0dRIqZzd5TK0X9nGnIr1JODsCsLHUQ5SshTQEHE3BaW9t_FSj64apqHeBn2LgPjLWctbYTo1eWguJXUsh36iyVEWzKbG5kL1kbEO7RnbaOyM_U8RdWRRP89ZlCta9RYP300V6l5WpnF5eVfOMcXGljwhFT81GloRtFXCSZaq4lfNNrL-8PH5W8ibPHPTn1kZI12X1pMq4SsFWxQYz-IlF0cIJs-RGFeWpLK43FnhxKxNMdJ1BBnh892XY-B8wcPm_pWO4-emBtjctSijL5qRcn6QG_kwWNW92A-8qSVuJj9X3Kp-GV3_bqNKEE_5zh5W6JXpCLHXQ7QPJoP30NkLvWVf65uPmxXWJAiyO7Aprg_jTR_ajQkFSL5pDjmoRzOUTxLQgamvLhpQzo-W0if3dweNc3Glj_pkR1Cj1II6TUIZPaQhWSFjvH88Qf3pA7cHV9Em7RcsUrHcdG7y_2YPQ0z3o4Ynv5inVvYutDzta7r0_pog_KMOfs-XON9py_zt2hvLqT95V3E3zPIJUe7Oxglcp2MbiuXpMYbPNLefyJonqm-mbp5ceItY97V0SV85OHKdJfYzuv_vW2n9lVByrQqbRu_gk3Dzx9NGwnxI0rpPHzkn4V2SfMp8WoX4UCcR4yV8eF8mkzIsivxs7R7msrpJIObN7HD_7Bkhr5F2SY2auB--0Z6GekPURl3fxuYrT-oDE5yulRzSyuoSh2WfWx94aUWGhlDbTYtWlGX4v1c9wLVmw-WQOZXzQFGStMkMUNQch4Jf2Q2WaT714HumjFJwJj40x4j4ZI4J8NCaMkDHlwudw2Rd0zInv8TESLlxHyBVijAmj7hhT6uExR5yRMaMeImOCXSBAue_SMeNwQVPHY-pzl40Rcz0AYR6jY-Rxb0yRD2tQ-NYbY8yRGMPylI49juiYEOr5gEMBEwtCYDkCS8F1RhmgYg7MYM_FY-AI-2NCGZBhyMdkLFwXuBAeF2PCGR8LH9AZo4KNfcGBNeJSYJy5hAKz1BVjil0KkgtGfM0h8UBcj_sAg4AqQQiuUAYa0BIJII6ZACX5BHgkAvlAHkhivagH1HxGMChPKwy7AmFQjIdckEaLRzkDGCwE_GQ-FYDFXR_kAC35Yx_UAIoRPqiXU8AHNYBiBBBHgoK4WDAP1CPAQIBOXFCJ8H0GbIM8oAbsepptLRQDcOqBZcaIazlACtAsfAKLgxiaO6AL3_pYgHwUGAZtAkVGCQHmBIgAlgH1jTlQJVwwuIo8wcHq2m049j3tBy5zx6A0bTUPHAPsqvVIPbjCXMG1hD6Q4tiF1QhiIBEhvmYX_AB8sQLXbT08qTvEcOaqbhP3B1FSqeit9tqmDn48f2M-_HJVVTflyxcv7u7utm8gyeSx-g7T3XaYT17cABmIiOcmlp7rhV7swD-7-t_DC_-Uhm9_BOHdJ7XP-MG_v_-GdgP_8Pnv4u2XT9MvKKh-XH7ywuPDd9ODI8bfnxY8-v3zdXFyHPC97z_uquDbTfj-5PTX_EJ8z5Kbt1d38W_ud3_3Nt95d7H3JsFv3ElyKu6_Xn5DF7-9Z2k-fTP5mJ5_zX2WB2-KmzTeoezj9PuZfJ6Uh-Jjkp5_OP569O4-QSLbf8cPv7n7B_f_3mHyevfz7v7vb-nx8XWcBIx_OVHq2-Tw3W8F_Rx_Td-fp0V6e3Yfouvro-PgD_TmE_9-vPPc-_h--jb5_Nnd-0K_8vvr4nv59Qv_AtXkR352-kG9O0alnFY_vPvzL9X06uj5h1_vXr82Cn4x0_Cr-pnTslZ385vJICaZcKxnCDDPpDbYiwE4pJ-IehgOfItQGziISGIBh7Hv29Cjgnu-DT2it1weBPMhsViAEc7tpEXEZTbc6Zy9gEODcNS3kQIimtkomWNiY1vMPWwjBYNMbkWPQgayYQ9qj826BHErn_IgWdu4FGRiG5eiLnVdK2twYmU15NosC1UUESsxiG8VaeAs3Ma6PhM21kDUt1oXQf9ioxYsqGflfdBfeFbeDEXbKnah3Nvo2XeFjRswBEFu5S7QSFjZVwhso2cPI7sM2clBa_TCuZ3-qN262KNWlciFBs1GL7rNXMDhQTgK_bONPSi1yi7QEgu7igU9bou_NYIApI1iBCVWcARZpV3oe7mNwL7ne1a10rdKf7rbtHEX30M9bgBD1aLdgV9gfjKjlh6w9Ie3eaXMd_ri7Bczfn1K1J1TKlmEVxdVoQfkH3k--V07JtuG5plzaNJdXU_14fVjJatTeTOfXzVsc_S9gdBPqOwncawKc2x_NkFqwC-vt56D220L6PQ9gV2ob_UpfbOB0MyB-vOFqofNaama021m49hcbh2X16Dm2H8zZ5_LAubXl875zvnBaKfQp2qiKM8cYKkYnaoomU6cvXRqDqT8qu5UOvqYJd-myjnZf-lEYRSGsRAihsHP8xHUBWj0qauIH0TE1-HMuXC5p4IwokR5UMWjmGMv5iIM3XBkuDG6eOkwMTqZ3KRJmFTlS4eM_hMWMoZR4P92oqh0qHNWd_hOPQkvvkZOfS6o872TgG5qhp3ayh16AH4xkQDWJepcFjKrXjrP6D-cKndmj7k2p42c_BaU8CGZKGfxpo_RGmqg9XxOkhiS5vBS_dyHfs5oNMj8bgG8R06c6zMyFbjF_TDsXlKEeofNeRekyS0MV8aftW67Jsddk398e_L-48GoPnfmfChkko729IZJtWrp0HNlpDhCnvRE4EsRqyAIVIh8FsZUhLEUoUJC8ihUMCcT4RHlwhgsAxp4HPOOpSkbnUvwLDBz7WGjN8lET32goZcObruBO_L-obenCiVLLfr8ll5jk5F-G4gjKycFgMqhrnOSVSpNk0sdSYDp1CuNnfmZCSdOClU62JHzE6XtW4WbUGyhO5cSQKg7wLV5JM65AT8qTZAOWcrtNdVenoFBinx-AMLccEuMd-yZLbisx3QxDQWKfMWFjFHsxn4ohOI-WIgRGIVwLBFjJGZ-zDwexnEMBvNUiCllDEdex3SoYyrUNRW4eKGfBYdv9bNYjn7Zh97raiKWtnVSO2_92JizPy2ktsQILyicmxcmmMstGv3qIj257HOunDd5fjM6nwb3zjmER1spKkIgNaUkZLHCiKkQxh8oYoyHUQD5KcQI0pYQQeT5gR-7LnwpAdT3FPIVUx2lcDIyn87VN3DuThpDo2fENZGvn-NuR_4zxvTlifyeTCDH6tv2I_NKBAW6UA7bJrUSW76C_bYGzbdzDK0m_VaE0TPM-9cj_RlonhafUdpmSJMfUDftqvt05-hkb3Qms0QfGnP2IQVlygjkHKayvNbm28-n5ZIJoLf1XYkFuBtiMiQh9xmjBFOpOI-gkKAAKUQ9j0gvjn0oHb4kHDNo_QQORdcvuTdqHhDTjriwBne7LorZwsN2JnqHFnQR6sSuotFJpnUyv3Lv3F1BYgTFvsnvagOdTCbTDBbRiqqf1HSiaWGekzCSKuPPYMeJ3t12dqeFfuZdk4CyPKBN1hvquv5e59kfchbq0EVEo4skvQaWjvM8aqsSMi5WHEdxHIRI-hiBT8cU1OdFLvYipAREtAxhiqFxiALOAZxFUsCMHvM4Yh1VenShSuyOmh4Jour57vOj50eDykULV2rqX3N3DFQNEdi-EeRcSahfpJMkZ6f6F9qv3bkOk331HToQ4GnE3IUFm7q8YibUoVyfo61Tr3GAxVf1DQJHP35sCj10c8m1cuqHgEcwHLaBm0c7NV_alZ-J1QBGzO0h30VcZbffL3ivXyzutIyWbrS0HYLzUCqK4yCGEVcEceQxqSDLQWjFHqFuQEI_VDIUPok9vQdDKUcKhxL-9WPhd8t1K7b8tj-cO11_8Afc4UORXGqr9939qLVxnFSQuEz-AROo7LK6Gpm2z9OXEG0f-jZAxpkcmc2sW46eQaWGb5aNhGlv1tN2Aj6WOzwosOB6dXlrrzlqGC4d5C7zYt7p0rChiqES5fVa8_1UKVPeqitIljn0JdVoH34k2T1oH8wLDWbLrDGBYo3j0HdjLFwE_XaAYkxc7AeUB9CRQY1CMYchOlCKscjHXhBT7EPjDeOI7KZMz22nzLlZj1bCnPlLObQbuMsa56th8UwMlCTWa5xnyDfX5y8NaX_ZzuCzl8g0sY065bHznSmj3HWXuB070xu9ksf-MXpO-Yo_VPqpaCcu8ol20VLnsZ0sgV5_yMyipxOZPU1nQj68Hu2lOXSYuyqt2rb1goDCPMUgXD3sxwSFMUfchcFKYCUJWDqCXzxJJQp0r81I5HPmSl_wAIWELZfDVkdCunGJu41YNc1MIJlHzOfZd4TQQs_mIHgN-eEKnPQKDNab_5oY7vQQz3C_lZFnw0a_mv3eaPpNFtPE-SyLaPQrTCtQ4Kep6ihZcMlCLgkMJRIigjEvkMKF7BjBFOt5MKwEoGAJUQT4PmIBRJnPPRSHTEEi7Y4xqN1osJWur1u2nmG3k92eIddc2AlDaH7D-1n4kLWTw1JlW_L_QdwmifXrEvXPGh8gI53lqpr1H2cqG-1J_Qoz0HDWaT8iaN_8SEYsoNDJUcgPNHZDqpROVgymReirg0i_WwW7gRsFXoSRFKBwaLr9GHWrDeKLtMQWaWkX0tJuS98IdxWOOsFv6sNM7GfIJBONaiYJQ1L3BWbvpJlE9EkMkyQwc-r319QY5WhWveQCsyZvKtd9Pp01GHd6cISKXDr11su4viIddxuxpoeftzl1eSOaM7aadvJZWVshangkSywiPNjvDNgc9dp8X0Jwl_nM5Hv5VD_KMtqVRa5tfQ79Mghv3pvRiSoFVoz0TXrPC0NoKoSC-hQyV0Ezyv0IJlAKwUShJVWIYBxHkvMACyWg_eReONjJgy-06tJ5tyrRJQfAHe9fSiNmCqvbOq3d-tu2l4A1daS02zLc18stmQoCknR0b57KNImsqTTgfp7Jf3qD6CA18Qroi0QIrQtb4U3ni1WGG8s2HCex8T7TS5vvlxxfSw-Lpfc1sXCd9H20uqvNiQ14FO6pfLuFnASg1UPT9fdP4ghjEkE-xrELc7UrJAl8wSAjcxxEQjDmozD0WYgjBg0qdDRewEOfKxYQighfch7R8hCy1I8aLfS1IaJds-qXw8y8_Bknq0VO55r1BkVs7Qze29gsBnHCLQdxRPomcRhFL8G0MMnOZ0dgNdfbid2hHGbMaRZeLRkkCGCAFJxyz4ckLpEvCGdeCF2mi2CE9BCD4QKGdF-gKHI9-C_iIlLYE5izmMnu7MD753K6tMunX07kIKd-JHaRWSEf6cZL910yq9uQzgxuXsGk9ShNajV9Vh38ebR-Ml-HuHZcR727HzA46PDQWzcDOyB7hpuO50OnxzwY0sHB48gPYlCokjz0OJJYep6MY9C9L2KX-yLEHgklimQIfYse8km3GeHIbgOk2yOsbIHgTiVpXtemtRHVejf5o35os6vfg65-G5D1mmR9mtyZ6Gc3zLsLyiTVO-5zFeobKZ1xCBxSchFSzIiI9A4SlBomFHFd3-cx9HVeHFMXGucghKGXUOVyAi1IEIWeioKlKbez69HKIl39PUMmW5w2wdloqOOUhzDk_lC1Z13p3mKdI64Ar1cZ78myF3nq7OrX612N9oskru60Dy_3aL6HXH1nCnOYG0OkAhgcEOICvCwSjAYx02MljbkrIhrDwBhL-MoNcUwZE148pCu33aKddxOuGG7JfLOD1tpYH7E1_dsjbsd4g51QZ4E9vbdfX4f6bJtuvR7tHxVJ7QaTNdqHCoYFkqEUVI93ikIHxFBIUSQoZaHnRYQIcMzAQ5REgXQ5dNEhVsKPXAmTYXdwH9D-0XJD9HM0ijrjoilpDRnTwprmGvdv0AzqvNutD-1kszqF6jsqymTl3yBAhmwj-pLJxRSiM89mdfAIokTv2c4zyk4E4xjoMlOdCggtLK43ToTgCIzkS0RDH9HA9cPQRXEsYSKnBEHkQIrBjPoe9LnM8yNtyu5tTTaQWLC3tK3S6dHMbSTZcLpcFqFMpPDl0rblUvJe2gDpS0IDqvT7bqeAZa6cizS50Y8Bj95OgylEljlZ39l4dHkM7UCI_DBQHEEXpxh1A_DqGJo7GkUcsnLEI0-4lOIYwWjgEXBwhTwhIhSsaR46k8Cu054FCF1O0l53-m7dWMHbqHar1o2VrovXcpuz9OYee6zHnvlO4uCm1OBYvmjs8OqOSccEF2k-e1Xo4iH2-Qm_2etVDVR94392UqDGqW3bOoeBaBulBpodvJ_B8FUQvTW1ABB2y7bOW81fr9yiOXuB3gyG2VFty0_sUNqHIi15bx0O6dHY4gHoOV00DNU8pzcH5YOgaBnUWwXV01J7ZdJjrfbbgGZwQ6Ta-sR9tMyTMnMQfxWk3lRbwMxAmjMoa86ftI-d9KlDa8PZCe7LUs4ObTg9p_h6NbmEhu3QVoNrVRsbctQnzANc6bCzRnlU_Pc6ah-HZDN12-kE_yQ0uhmTfLPVLNH6tIkesHefez1ggTqNPnahHsfim6zzgAMPlBYLwmTzoEKbCEI38wW0mefRh82zUm57FPtYsn3utaHgG6Shnn7gYfY2yJDkIS3Mq-Mjrdmv9I3cjW2CZBWhKw3VJh2VhdhsYy3jDbyUbxZnZDPnJo93Orp5UdjAxdHGyiePj9ue9nmD_vlBmZ7QRlmaebVdt7YR38BnNzfSE5zJNp33zySPGUqsrfOA7gYGGosUhDdW8IbpxN6iK3OXhTjEQk8905q1HejG6mKb1EWbkFkdLK0d_QGehobSF81Uap7rMLs55u-55FmcXK78dRY9tJoD4ebPZYD-t5wgz1MlsybnNX8docF-9WL5D8b-P4-xDPU=
```
* **Screenshots:**
![image](https://user-images.githubusercontent.com/19306746/115402966-3cd6dc80-a1ec-11eb-96ed-5213aae8a9d1.png)

Additional note, looks exactly like https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/1627
but with a different field failing, I hope that helps

**Comment by Wires77** [comment] 2021-04-20 21:15
Duplicate of #2492

**Closed by Wires77** 2021-04-20 21:15 UTC
Labels: bug
