### ISSUE TITLE
Molten shell showing poison damage (which it cannot inflict ingame)

### ISSUE THREAD

**Issue by fbwhytee** [PathOfBuildingCommunity/PathOfBuilding#6165] opened 2023-04-29 17:19 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour in-game?

Molten shell is reflected damage type, and cannot inflict ailments (such as poison in this case)

### What is the behaviour in Path of Building?

With the consuming dark dagger (pictured, and possibly other similar items) PoB indicated poison damage can be applied, which is incorrect

### How to reproduce the issue

1.Add molten shell skill
2.Update configuration tab (Skill options > Molten shell > Damage mitigated) to any positive value (I used 1000 however any value above 0 should work)
3.Add Consuming Dark Dagger unique item

### Character build code

```shell
eNrtfVtz2ziy8PPqV7BcteclTkIABEjmS_aU7Pg2Y8ce20km85ICSdDihiIVkvIlW_vfv26QkkiZlHVLzmZnZmo8ktjdABp9x4Wv__d-GBu3KsujNHmzQ16YO4ZK_DSIkps3O--vD587O__7j97rC1kMzsO9cRTjk3_0_vZafzZidaviNzuuvWMUMrtRxYcJKfYZSI1kUgxUmpzJf6bZURq82XmXJmrH8GQSRMXkmx_LPH8nh-rNzseo8Ac7hsx9lQT7s9_PfX8cF1FeAPRAZtIvVHaKbffHRXqWBgASyjgHYkMZJVep_0UVR1k6HsGYdozbSN2VQCdnF-eX17WORUm9YzCwv72-iOWDyq4KWRg5_Hmz0wf-yBt1HEHrtzIeAx2LWC-IxaydlwtR9sZZXryVQ_i4NOrVSKlgCm12gV1k6iAMlV9Et2o_i4r9gUx89TTeqrBnyPdRHKlsCk-64I8fkSZmJ_HrtJDx24urp7tRQqbFEkxJozxN6kSJ474wqbBNmz-B1JwlZjsvTM4swp_q1Yqt7Y_jGFRoqYFfqlxlt7KImmPqnq906EWJCvq3N1Ng26UviCuc7oHsp2kcpHfJjP4LTp0u6DOZyP00X2IyEPJCZaDJxUoIV8pPQflXbWNFzNMoVMtDrjSOCmHV3qw3joOrZeFWJrxehy5BjZaDvErHcQOSd4MWM_PDqNutMF8bkKbognyr7mdaK-gCgg1I3tn0STIbB7MW9bABuaiHtylq_pL28eD4YgoZJWGnsRs85JEv4zN5Hw3HQ7DY1_KLmjVCmejmxml0MygSsF5d2Iw51O7CPowy1YVomdxl3QYqDtZDHMg078JcwCTUxqe9HThq_xWCniR-jQOLiL5PMm3Saw6eLIK_BL3DSMKL1XIIswYq5V3GE5ct3aikau5hOXt1qpQ_OIJwC5qqx0YLjXW9P3whZxG6ztmFHqmFsZRby2HMc4ryF9RmghHHMm1XLCLSzjVKF-GszLaDRGU3D1eDSMWz0VnMYcsgTDq3L0dL4WrW1wnUp4AId7k227hCbP5iKfSVGfRRZsFyfmlFKS9DPMRZEvadKi4b4MS1uwcN0FPVe7oBgJ6K3BKiBuCP5mTJubiVed3vLHAIpbSU8HVB6TYBKlYKEAK1bA5ykaX_xCwnXg2tnw3T8SwScKnpLDY3JUJD2i3ylBctk4ZLFYz9hqt2O_u1F0NuOjcIe1HP4rgVpdPL9otC-l_epsHN0rzSrayOcTUejcCG4twvi4chACQ1US3m6x78DPgc1LVuwLpjDAwV5hpwzKeB5xsgzpMh0PwwxJIY8005C4OXuVYEXwJ6voVuxzKpH5yBPRyCC9Slh7O0Fpy86J4dyGOXSko1YDNNXpC_30HfB1hJyleDhihvFoN1diVTybeHpek3wJdq4CAJxhmqwtJtzGO0NXMdDcFs5vlbWUgjqNKCDzKLZFJQXeDKlcz8wSlM_qGMYw8MwJud-q_4bQ6RTCLJ1y91KQ8_nQxHaVYYscyLvu-n46Q4lvkAOkKIx7nygyBUtknhLyG2sBSXlNsgMk7IlGQQ-mrUSyXjIczO_o6h7pHghcyKh2mBDkH2JzW8kn5gScI8RVhgsdANGTX9QITUkaEnhOd4nhSBKYUq-6vJwXDyIkp0bQSMXhzvGFeD9K4f3CIzr9M0zqctytFIJcHkq6ZxnSllSC38aP2RF5rV-KVefTwJNH-H0GeIGEqFAcL_sjjnzi5kb4T-e_dfDJhBduEvsfCbyVy2Kzg38Rvnlkt2BTFdG79RS9Bdy7GpiZCOS8muZUGgCd8EZE-7jHAu4Atl3LJ3ucttJGLZEEjscgH_x2c2M21onAORHSNJgRUQ1AnBxC5zHeyJaxO2S2FyAMmygBBlJrV3XebSXUoABroA7ewKy6KAxBgxdwVDQN0Jy3Ytd9eitst3wXEy6LEer2W5AmgJ4opd4rrE3SWUWNCS7hCMHn4pOy6QQDlYRi0C3YCBMEBiNrRdjoaZ0ElmE4pPNZNMyzKBPLWhN9gSAGOHbRPa4yaHnyE7tR3oNtUd5i72mnLsmIndoyYFLgmbwChNm-8SDoK6C73mwGYGFLkeNqPU4rs2cAa4SICU7hw0b2NrhEH_ARDatCmwx3KAnTAxjADDYKZ3qSsojM5lHEmbHD4KDkRMB4ZLXG6SXZvBQ-aAlkCvGP5sQ2YN_YG0Avpm4fS48MdyCIVOwDzD1Fu2ABYR4PWuoAAErHCE2C2li0IYBmOmNoxC6JllwsE5EdA9HC4DahbBqUWxhMYdaBCmELpaypnLHPiBCa5_MOEzTAFMocOApdyhxNktW3IcAIGRE5RwlGUQGZg2EAHNWKTouJYDo4HsGyefMhi8iQ1p2aLcgVHCSBnC2AQ6A03DMEEQCIgMiAVA4vxilqU7AyOzYXoJELSRYzCNwOVdm5tI2qIUOw78h9mDmbKoiwpAXUZ3jAJUubbqQEm1oICqy7RW_-31-8tT_eFvg6IY5a9evry7u3sxksUgDdU9hJYv_HT4cgRIYA-e51-iOH6OZF_24Z-9m7O90P6UD8WRd_Lh5v5jePYlP_z95lZ-s7-mJ8p1_U93WfFu9FBcfjo9ppkIhh8O2MUpdb9-ff45-_g5937xv43Dr8d_3Jrj8fiQXRz-cXBMzy7yoyOpjr6pq-Ao-XT_6evF5W12dfQuZHfSzbNfs-B38sv1-R3bc-4PLvjpvetemu-DP6yP3vM7S94ch1Hmnqr4N-kdn7uHD5_37tWX_fuv_Oz08iGJr_aLqy_v3l_85l6PfisG488PZ0Eanp6efv62N_znw5e7OPl88f7WPT66eJ759--jYT789YbE9mVx9MfNL7_8OvIlD8Wngv1TDtgf_mnx6WMi-YfA--OAfByd3P7mnH78at-B4DhH14n79cT93bo8Gfye35Kb-_CGPP_d3Rs9vBt_uXy_d3V3_P7zgRvf9-mHcTK09r_0fzvs7yfFwdHZLywGvgXfBsCviH78PH7-_uzbmP2irN-VGNGz8yt7dPZL9hB92g8_3wTZlzd6Ul9OZvV1ud6Tl1NcfdN2EWVA27sdIyrUUH8tnepjOC2MMzirC06bvxkc6YLT5nAGVzlz6Hatt_AFHI52wuiR8MO7tFD6Gf44-fL6CmUyN3LwpkdqmO89QDh1iHndrOivA6zKpSH0lSrK2KCO82anyMYKg4FQjmP8_bexjCN0z2b919NyXS9Js-G0VgikwMNi1F9SvH4YoePpn56WT_pxURHD5ibutnSrVYeMKJi42upHvV7Xn_V6X8Z-rvsdJX48BlYmVaQJvYliDB887BkuU2JZLJiMKI9TGO9RDKFsvjNPFae9miXoW4UKsJ6M6YRuOWI0H_XHZEof6ZxofmdZiobiapClY4iVv5aDxmdvSwbuGDflpJ-pQgYQtb08ASnIXyJfXuoOwScIBW_Gag9iNFxa-zqZBmo-GpqOxKpuJnJYRSwlvlEReLnk8MynhvdBwoSncaGSq4HCsGrN4XXRWWGESMIoaRglka2NspJiSPczJXMV9OF_52EZ360-5KlKLKa3wtCnhAykZKShUdFakgPWkgzoB0GEIbSMtcZvMPQuStqwLDXmA8g-7qai_LqUpKdNhaaylrG4hKTcIC3GAnG3JWmHMQzwLaQ5a2vSYwrL81TjGhr5h7H1WMVDVXxntqJteBvlPm5NwD0kG1ipFjKrGqkaia2ZqLK2iMUczP_740yuPcoFpJYXpTMJXU9jhYW-72aFfr_YigmqkVnB_iQxlupUssU5VIXKhlWZYv3pa6Wy_MCa-D_MDuylwYMxqcN_V2NQicClHEXBW-XLhw2EqIXICtbg6i4KC6MfhnHk17i9vTF-SKPgTCbRaByvKVTTkXaSWsX6AQ2jQWTbA95PE1ydzWShgo3jswXEVhh0ncqKcdnSwwaykS_9TST5EYkVhjjF_Svi_unsJVlyKnDtucB1orWZP09heZc0wfxhzP2o5ChNDGpc3WGHv6s7-lGRG_2OoRtZPnRTAa7Ulj29iMf5ZhFcJ7Xlhat_hxu9UJORnIH0jGp777Kjd58e_nCYJpfyBnLIq1GURcXac7yA1CqRh6ZilGSMis6PVi_yI9QL3O9t6m8WUrfRwM2Py0cAU_T_Sh73vTyNxxuxuIXEChyuYW8vG0vT4R4uP689pmN17zUIrDCiKe4PDCjSIv_evk7lIxll6xdgxnGCG1wjRF6HrZMObDtQ3YvTFNKjm8jfwJ-1EFnBpPezLL2RKzhtSv5Do_AfVfZeYXZlPhqo4cNGkztPY4W5nSH_8BD4exdjgBMDtb5F-KjRMRYq1Ggd1k4JGJrCkqLDfvoVk583Sf95cvRJDLaZDpGnvWoYoeHfk0mygSp1kFlBlyYUjIrE1iStnwHv_Em1Y83xvVN3rXRWiTM1_qTs8lOta9B1Fza2qyc5MM7Ho9XQ9VfOq7dKFoP_AS3J_19unMPnXaOfF5mMjYtYFmqt2hfZXu6I26T1iQ6spbxPoq9jtdaKCgzM0OWYl38tYvy1iPHXIsZfixj_DduG_uxLBw1fxl9dqhGoCMY_u8Z-Ns5loDJjssVwtf2HW1y-OUj8gUwKPLBzHh6Os4fz5DgqrDVYuZ8OhzIJkBLKCtL6Dmw9T4xfkcBZmuApCuPgfhSn5QnDCb_1T8Hj4GCrbNRPa1yE5Hvarv4ZD5ZoxJUZ-Zhr1ccrVejdveX-Xfyo-aYhTpLRuNBE3uwMo9z_7I3D8KzsTpHpC3gODg8P9q9PPhxUJ4HqKLrLn5Px0MPQvvz_7HT4ldKu28jHXl5-BD8XqTvdkbegQFGc42jiWI5yNT0cozfoVj2Pp4ajlZqGAsGbXJzSTmsG0E3p4F5lBYz3o8z8LFKd_Zo-f6JTZYNptWjWRQ0vlOkmVB6j3MfjTDpq7eCUvqunmwpeoNM5nP3pCk0r7slwJOPOlqunT3CiwC3aIKEROEI8dLZ4ynFDdwm1gC--D1Ev-uPO-a4Og3bT2Iv1DUftBMqH3cjlbT1d2NXTBVy9SaLu-ayedqNXMXWHROmH3cjTg-1pos-1t1OZQi2g9K66rwiUph_FaL87Z_YgVlOQboLnWDKrjrd1UToDGzUBWag4WeSNi241rkEs4JW-gqODQ_isG7W8ZqJjDPhsgSVqXLXQwdA6TDep8lKCTkO2CLU8xtvJv-pM8IIpqPLoDvbXSh3tTJic_-8Yf_V4gZJo-9u_hbSqPBbeoS5zYIsMRup_2ZyMPuK-OZn5w--bUzyMZf6lc76rp93o7wu9etZCpYxZliKCSrUZBdStzShczgcSM9zLxSGEtl-QgeAWl4UGbAqzYH6LcfIWnFyxYG6XJKW71a4Is6GtRKs05a0jXZliKaDVrUiLZLgEeYIQ-KLjBdHOcpSmVxIcKxkXg4s0jTcj-Oj2p43GmRY55Eu6frjhQPESmvEIiE16dt4Wrs6mdJ7q65eTREKfZcfQvjrvf1VkmMp-S9Phpzc73DLLz6fTZS59ig_CvLcRMDvTQjJpCQF_x1vJymsfXuvUvTpUiJ8nZwrHuSqvhCvXQ_TPk9RMI9UP-l1KCHQfXhmX_cuD3jEMLr0zLrIoH_aOBhBfxw_GwYMyflF3Ku6VFVnj5O0rwwx8LnzXtRgRjsl9M2TSpqFnWr4N_wbCsn1GTc8iAXG4LyT3lOuHbhAI1_VN0dP90MN-ZTispz9dqq-vDMvsQfgcRz6IK7TTe0aEUaTGW3UP6Sl0tfeMUvxhWMqOgaaxdxYlMHG5EYBgGvqxbchpYd7QheVql1mP2X_Ha0px3QTgtP4bOq4FHelZf6_jTW6SqVCN6V0yhryBGDAvjL73kOdymj7nPTyAOB4VKtApJySMlzIBzAz_6ssbdyruV0lpJwR9EoI9CWE9CTG5QUTXgZoCQpsC8v7dyW_vD3rvZDHG9YJ-GALPYTquhjIGDsdjXT54JCjUthgXlIZm6CoimVCBIxWIgxCBcLjnSVOGrsOETQPHdxzphXjXAXXhkVLKbQpKQzZIj5IFU9kPgtzQ3VWTFY8LcBuoUlufpTb-sRYFO0zHMdaoPNU7fhglKa5uteoXCwhjgelbkkvbdYnFCfUcxqhP7ABvWxBSX64Qmq60LCsgfhAGrunYnqNCqqwG22xe0y8xx8MpKwy9H8bwZQL9MjxlRIleY4AnIPAP6bjkqIusJqy-cRN_0XFX3nvGWF05y3DcKOPxnlZkQqqdnxqjoZrG3SCK4S8C4w4BaVzfpcYx2GEAL41Zz6ILpvy_R_msFuH5OIjyUbl3orTQV9ql4PdWGXLDkFAiwF84JiiY5VPm-JbjWpb0hIfXfHjCIa5nctN0WcCZJQPTDkHslPScQHXbaCHmbDS1tFiU2QsIgdktBKw-f3txlAQIMIxUjmIGDhfmH5fvdIkn71Hz71jBrArnlZxEIcpjqdW3Shcw4SF4bYi-4of_oMlvm1realdn1ezeXDG7V3IVpoDa1ec9YEZ1MSIoDMzACwdsZq_BaNBt2-zV8-HHWK4jnIbEmA78E7JQgWR4XFFbhK7pBZ6SAfdJGJoelwFjoWk7AQuDwHKZYwbccR28foQ3JYb3qhsHwAuYvepihVfG0fPL53vPLzvFifT-5WcyBC3-93UW3dwAI1pK4ZWw9EB26wIyLV-ANHwdg4nStZUeaQBBEKaSm2LQsxyngayZa8hSJGsye5JBax9Byn56uyJa7Epp99_JCK1HrgoDj143nJHJwQuZSriU-J5LXMp4ILgIAmk6HnWJafvcNbkLX6zQD7jHeWC6XJmSWLZymmJhzURhryYEvC4DdCYDn3BK9sEx4MXcxjVuqcqNEKLqb8pQleEI0wykmUKMjWFvXvkRSMkeDAleSuq8BSbYewDbU1ECmR7mvWOZ455t3aHev0K89wriheDfz7j4Oxqo6f1wRlnY0Qr6zOLd9u0ZJxpT-8c6Euf6d7zXrv77dKDPrIbVxIR99hB6A4I_cbeYaBhlkgKjgiFo4P8cyVsAIZ6EsJ-EcLrl2-6U71-VGvWOxx54TmM_yvwYJnzOYFLBnjCYJuGsrhm2GToQyErwqL5yPF8KcLKBCWrACJMSZEyCw-WOTZTwmMs4mFcRKrA7buiYYi5Mc9oN5t7zvXmD6daVhc3EpHHtiM6GprGVp00cpi5JPcXhWrAqvA94tV3PrttElCyjdtW9odftMYp-QMRy6azXMKO4LmPoxRcQeqtbU2xRx5rTIsEfKcMzq0OzGGvVrGfE6dbhP5uyLIBwu9XJaY1VHu0i69U3kU3jFWoRsytgaUQdPiEWJZDwgTO3TB6KAGIP13ZtDsmiCWGPyYWAZIcpaZGQm5YjFCFC0JCYvttMEW2rK-o40mq0ZzQUiTYjj2eEapHBlPYg1sEDDGsmNnlvEpJoGtCCMdttBm4HzPIBhB2jEcq-JSakZosqPWLNhSsQ5VbKQon7OBoBTWCPyh1EK22FXOm3XpkqvYGGAb-pHYVhcbOZZUEOUXlK7TjZ1G2m5V6A3lEKCnaYpsUIkg2Inn6moOf_zvW4La7nKH4YDYw9mXmQm0aYpHyE6LIu_J4ZcuIrywxsiKSVaXoOuAmPmb4HmZuEUMsh8N11If5iDkRgApJ_mwSucCC3s_l8oj8V_oYDgYi7XmJzm1LPmtGxzsurYhln9Udz9bBeU2Brdt9t-BBcS9doEHhHIJHlGrQWvknZgNIF4ZYok8tqcdu4lLgf4b9MKtskiphNkTrrH53s985knkIUmxcTCwzGVcaFoRdw0C5A3GtcQCspxLmNmq3HIC63IGuzFCOmE0K8wyDZCyHlp5ZkoTAVhWCFSk4sRc0QbLLwA7C_3HbgwXwYX7eztTje7Ajk36MoaBNZ3aZrgHj4AyMcg8m5lmOwNEYCgQsE6bWCwDhXPVxvN-gUTdOA_F_H9lgwAAwIavSeoR6nLRldMNZVk3L94jtmV4S0-strmBBcQQjj9A77AQMB_qje1TgeDaB7euYaHpHzkFKHEye0iU9dRiDR4g6nLnxR1DKF6RAVCiWcgDMiLKK48jxfqDAUtnxUuWmfKcbXmal9-AyODKItyBX9cocqvswr0cEloEKy3bAnJQ1jcrF_jzSCxclaXjtWbmCdvczc9BJbyat8bkZRQEB40ilW4zHqhEwe2qagYv1_uBmgbWagj0vcEE750-r2EdCMCtU0BH1PxmmimnYgoKZQnLieZQsQJqkIpw78Z1PI2znFG6VDx_Ic37GVcoUvQfsF2gzTZaopXRbtkC5qdxR1FkoX-oEMV1lqIoDxCpqBplNZXbU3qtqRtnL-nhqoYQrh3x7wvYfH-mWbj7cppoWh7SgTkj_CHal8cN2mCr2Qgcm1CYR-gTSV5_s0wPAWy3AuCRwIBqjwGgwHvrb6eKPp46nVZD-hnT4e8iT0rydJAT9GN3qBpOnZG-CNiKC2CgABr_0oZ_vZ62XEarXoJ74KgYhxnnlRUZYH54tm3PRtFirUJunK0PaYgDgOQjePhDZlCtJ_yvzAg7-Kwo8yIL4vCKimcmzfaxbNbNIZvs2Xys5UoSCwqgplvrbWxt4401FVZagfhf1YSZ1dk2cMIIloFt51flMp2TNqN1dkKa_X9MtdftP6rNNSv9cV_hJO5ynoyHWJb2IZJt69hIGA8l2aPJ9ATKIDBKoaqxHoTXAacHqPs24Wt0EYVwNZQOeXXTD6GWJF3uYkwBXcgOrKZBos9oeqgCh-Llw8AzMC8uFFWcNwUbD3ps3M0OOE4yXknnR9ISQk6CC-XBDuOm5oecSWkLRQYhIQ9pBxqTyhHCtctB5QS8KtdTyFDgrZckGhxWZeZRYT7I-zvAwyEe-HORLRGSNeFXI4UoHq9fMcrztPphE-3hXRq_b2QeCGCzvll_nCCpmvadrWU2tAzG2sAYmAK8pNkylwQCq0Qp8S5VkMZt4OpRt4JnE8CE8hl-DM8U2bWMJB18WV7fhUzC_Yt1ZjLstaTF0IWIcQ9OMYL3PBiBOmOsqHsgctNiqHJSta1m0Yay77jEsgvWNxFpDaDajJCzenzzHfVCgv15nEmk9V8mS8pUwKzlOV8WyJVS5EDNNbdA6lea7e5lImykaUG4SbupyDdgmLtOULRkAg4BneT44r8rgcL5M0SqpVjH0UD_mnK8y06pPdqk99dQP8A7eVZrIHkjMcRbq8BZNSCcekTEkIoZ3rqqYJ8db8MsH0pw6daoQBHtpDMI8-c8F6mr5LQp8TMyRUKhEEzJchdz1HmmYoLaqcwGc-gcRc2UKGknencvZMnT4-h387y5pmj7nmUuucz3CddGH581m5iDWJ8R6V3EEx92ur-9DBXqVHzaYMhcd4EIiWtcyyS1MrXqKSRsQ_61E9jJiUUEut_Dl3gKzp8tur88ACFJF04jyuoptE74KCCE8Oser7qN7AAhsMPrFD0_NoYOMnjzmc-bgzhIcWkZS5LLBMSQPBOUhxKFQgVSiICUmNWs7Pr5kRdgeXcz67XClu1hpzI0gN3M-kdwZCxAphbCU9TeRn1NKSXT3UEos7Po3ZK7Z12Fx1IMzSYUtbDZK4H9SgbdX3cnvmdwk5vpuwuZ1hC1aCxkMcyVuZfekdRirBSB-XSRrBJPF4QCFe9KyQBkzS0BGMmgGHMMP2cX-bFNT2IOIAK0iUabmWKwkkUY4nbE_4nULWiCuOGlEFn4squN2SjUznerK1tJEJW05nvkt0yVovBGGJCYymflxmy-W5TDxYq-vruG2ltmMO76hTGXrzIm1uT632O9QkBrMxYbZoQZXg_KmMHjVb6jD9oTfOBzAVMh_09jNIb0Ap91RcNDwxD1VAheM6QnmMUo-I0KPMtkzLt_CNZq6rlOKuzQOPu0L5lrL8wFK-G5gSMoem_Lk1KbPn1lOeuWLB_pBym8d0D9IzYTr1vXPc7sadq8p0xLPNAmuZ51VZz7TaOrW9rJYalaDNyusMsqq8yhEaQy236KgHEBMbzUXNZezZX6uGE3luXzIAecI3IKMBOk8e7iFtH-OGlZo4B0TygFmSUcjTPNexmBMQF5yxoLjlBPJ1zwG3zkRoQwLn2CHlfhgG8CuuFYS0dxDjHkPsyHzK1pWa07as7H0xTPPCOMOVOzCJbsuat2UutLp6W3FZg6RW0xjObQPRC9uTbR0lYC34rC4b1PYySRubVqKwXJ2EJ5BMYTGrrB-cySBQSbmjtmS3dvLErG0lqyJSXUGCHA_rCwBSzURZX_iT52H47qiuQyfNl0rFEIlhTnvhvb88xYMw5Wn5ycUMk9dxTbvahTC76Wv6pi_3KRxdRJke2KjeB8ZnFMwpAf3oJADs-feKlZT0Tmuj9qqxSUsLCFQvHKsTqL2DbJ5A1xDApc2PgLaN4BF-eUpocpKopFaae1bj4dJ817fczvfEWqonc4SWmY_FNOgWaLQPSGxhQGILA1qLRtuAyAqEWtWFbYEjdFujWUXeytcebcSPFt0TG_eArkxhhmCv1yTbFv_5FoSBbEE9yBb6Ya0oCbVXVm5mY-imKmltgYOb-pCaJBC6ETvYpuygG6r0ah2Y3ou4iUyW0c8mFNoVnW9MQSwZHVVvZ60HN7UXti4Z3CyUC7Ito7WpqNdDTrIeV62NZYNvR0hX0ZUyAa2ZPbKuqWVbMFhs2bC9fL1wI2yfvXF4g6jb2tDMkO3M4Nq-fIbnrqMFteGTtdSoJnrEWbbnNRx7HabzTZ3LlmbN2pYx21piwNZNmWpTwp5C1G90rU-itZ71o9uZBbGtNHEbOau13phmWM5S3K8JsFiP-VuKj_jGPnBzLypWNQc10RVr2Y_HLZaVtMlFlPpGF30PZZqE0c2jWyWxvqYP7pUn3icH3ncML01jJZPK0r7sRsQ7QJv3qC2NirfS4JnB7KF2oaXZgjGcrpiWL3tQwZW-rhEv56yh8kWNHctbtWY_S96cyrxgZUUyb0e-iKWvBqmugpck8DjxQ3lr5LSbtmkuhi8r1ZdpHOuSaR1zMeJEg6cMsalwFqPggnN1geMUjT-NMrkEdILCnujZ9I65CYLDnCd6NjkZNN8Uoa41uRKpkunXLy9kMTgP98aRvubjH73_D_0HcP0=
```

### Screenshots

https://imgur.com/a/i8THTjs

**Comment by QuickStick123** [comment] 2023-04-30 00:50
Pretty much a duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/3838

**Closed by QuickStick123** 2023-04-30 00:50 UTC
Labels: bug:behaviour

**Comment by fbwhytee** [comment] 2023-05-01 00:17
not really but whatever keep it broken forever then i guess

**Comment by QuickStick123** [comment] 2023-05-01 01:17
That issue was basically about it being incorrectly handled and states it cannot inflict ailments I thought that made this mostly redundant. Sorry if came off too aggressive.
