### ISSUE TITLE
Herald of Ash hasn't had its buff updated to 3.25 changes

### ISSUE THREAD

**Issue by RealByteBlaze** [PathOfBuildingCommunity/PathOfBuilding#7857] opened 2024-07-23 14:13 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### What is the wording in-game?

In 3.25, Herald of Ash's buff grants 15% of Physical Damage as Extra Fire Damage at level 1, and 20% of Physical Damage gained as Extra Fire Damage at level 20 

### What is the wording in Path of Building?

In PoB, Herald of Ash's buff grants 15% of Physical Damage as Extra Fire Damage at all levels

### Screenshots

![image](https://github.com/user-attachments/assets/42b3d4d9-7229-46ce-8ca7-00ad52c7e013)

**Comment by Wires77** [comment] 2024-07-23 14:22
Duplicate of #7838

Will be fixed in the next update

**Closed by Wires77** 2024-07-23 14:22 UTC
