### ISSUE TITLE
LUA Error when try to set skills gems

### ISSUE THREAD

**Issue by bloddymane** [PathOfBuildingCommunity/PathOfBuilding#636] opened 2020-03-21 23:09 UTC
![image](https://user-images.githubusercontent.com/62486460/77238563-7bdccd80-6ba7-11ea-9d02-7afe31e897db.png)

![image](https://user-images.githubusercontent.com/62486460/77238567-872ff900-6ba7-11ea-8448-da1bfc792e0c.png)

**Comment by ppoelzl** [comment] 2020-03-23 02:00
Could you provide a build where this happens?

**Comment by bloddymane** [comment] 2020-03-23 10:22
> Could you provide a build where this happens?

Here is https://pastebin.com/VM2M7Yjr

**Comment by LocalIdentity** [comment] 2020-04-13 11:12
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/753

**Closed by LocalIdentity** 2020-04-13 11:12 UTC
Labels: bug
