### ISSUE TITLE
Ice spear Greater Multiple Projectiles

### ISSUE THREAD

**Issue by BladesOfExile** [PathOfBuildingCommunity/PathOfBuilding#1763] opened 2020-11-25 03:45 UTC
Choosing All projectiles does not update the damage thanks

**Comment by ppoelzl** [comment] 2020-12-02 14:32
Ice Spear does not [shotgun](https://www.pathofexile.com/forum/view-thread/1927387/page/1).

**Comment by ppoelzl** [comment] 2020-12-02 14:38
Duplicate of #1506

**Closed by ppoelzl** 2020-12-02 14:38 UTC
Labels: duplicate
