### ISSUE TITLE
Minion skills cause crash when "Is the enemy on consecrated ground" box is checked

### ISSUE THREAD

**Issue by Amountstax** [PathOfBuildingCommunity/PathOfBuilding#1328] opened 2020-08-18 08:12 UTC
I should reiterate this is happening on MINION skills as attack/spell skills seem unaffected.
To reproduce
1. Check the "Is the enemy on consecrated ground" option in the "Configuration" tab.
2. Now go to the "Calcs" tab
3. Located in the "Crits" box, mouse over either "MH Inc. Crit Chance" or "MH Crit Chance"
4. Crash

Mousing over "MH Crit Multiplier" or "MH Crit Effect Mod" are working fine.

Error shot :
![Untitled](https://user-images.githubusercontent.com/60943070/90487798-f2570a80-e108-11ea-9492-e6ff71a5ba33.png)

**Comment by Regisle** [comment] 2020-08-18 08:18
Known issue already fixed by #1301 which has been merged onto dev

duplicate of #1311 also reported at #1308

**Comment by Amountstax** [comment] 2020-08-18 08:20
> 
> 
> Known issue already fixed by #1301 which has been merged onto dev
> 
> duplicate of #1311 also reported at #1308

will delete

**Closed** 2020-08-18 08:20 UTC
Labels: bug
