### ISSUE TITLE
Importing Flesh/Flame jewels on wrong class causes them to not properly recognize class.

### ISSUE THREAD

**Issue by weebkingmarco** [PathOfBuildingCommunity/PathOfBuilding#5610] opened 2023-01-18 20:23 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour ingame?

If you copy a flesh flame jewel for duelist on ranger.

### What is the behaviour in Path of Building?

When importing from a different class then the one intended, it causes the jewel to be incompatible with the pob tree, even if selecting the right class.

### How to reproduce the issue

Copy a flesh/flame jewel from one class, then paste in into create custom item, then try to use the proper class for it.

### Character build code

```shell
https://pastebin.com/xyG2EByJ
```

### Screenshots

![PoB GG EZ](https://user-images.githubusercontent.com/123022067/213286644-001f526c-d0e4-46a2-b9a9-4dd84fe5ebdf.PNG)

**Comment by QuickStick123** [comment] 2023-01-19 10:28
Where did you get the (unmet) from?

**Comment by michelrtm** [comment] 2023-02-02 21:36
@QuickStick123 @weebkingmarco I have had a quick test with this Pastebin and it looks like it's not an issue, the item text that you copied actually has the `(unmet)` which causes it to be red:
![image](https://user-images.githubusercontent.com/8795161/216454236-819f30d4-f424-4c66-b13a-b94fad4bdf3d.png)
This happens in both jewels.

If you edit the text on both Forbidden Flesh and Forbidden Flame and remove the `(unmet)` it becomes green:
![image](https://user-images.githubusercontent.com/8795161/216454409-4715a3d2-1a84-4e3b-b027-1000bcbccd7c.png)

And when you fix both Jewels then Unstoppable hero is allocated as you can see on the bottom right of this Screenshot.
![image](https://user-images.githubusercontent.com/8795161/216455043-00791f3e-c43e-4351-8c44-5ca08d3a115d.png)

**Comment by QuickStick123** [comment] 2023-02-18 02:56
Closing as doesn't seem to be caused by PoB unless you can provide further information how this jewel was caused to have "(unmet)" on it.

**Comment by QuickStick123** [comment] 2023-08-04 14:46
I have determined how this is occurring you need to copy a jewel from a different class ingame sample text.
```
Item Class: Jewels
Rarity: Unique
Forbidden Flame
Crimson Jewel
--------
Limited to: 1
--------
Requirements:
Class:: Templar (unmet)
--------
Item Level: 87
--------
Allocates Conviction of Power if you have the matching modifier on Forbidden Flesh
--------
The minds of those studied utterly by the Cleansing Fire
continue to think and dream and beg for silence...
--------
Place into an allocated Jewel Socket on the Passive Skill Tree. Right click to remove from the Socket.
--------
Corrupted
```
Should be fixable by trimming unmet.

**Closed** 2023-08-13 06:37 UTC
Labels: bug:behaviour
