### ISSUE TITLE
created timeless jewels doesnt work since latst update

### ISSUE THREAD

**Issue by kisskacz** [PathOfBuildingCommunity/PathOfBuilding#5539] opened 2023-01-04 23:49 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

created timeless jewels doesnt work since latst update

### How does Path of Building behave?

created timeless jewels doesnt work since latst update

**Comment by QuickStick123** [comment] 2023-01-04 23:50
Assumed duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5521 and already fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5522

Unless you can supply proof it is a different issue.

**Closed by QuickStick123** 2023-01-04 23:50 UTC
Labels: bug
