### ISSUE TITLE
Chest ES% (maybe armour evasion) not applied globally as in game. Also an item import error. Origin possibly unclear, possibly implicit related

### ISSUE THREAD

**Issue by totalnewbie99** [PathOfBuildingCommunity/PathOfBuilding#4538] opened 2022-07-08 22:12 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

On a chest with 100% global defenses and ES % eater implicit (possibly also with armour and evasion - did not confirm), the implicit is affected by the 100% global defenses.

After some testing:
In game, ES% implicit is not applied locally
In PoB, ES% implicit is applied globally when global defense mod is NOT present

In game, ES% implicit is applied globally always
In PoB, ES% implicit is never applied globally
(in case the above contradicts what I wrote below, the above takes precedence)
I honestly can't tell if this is just a straight PoE bug instead.

### What is the actual behaviour/value?

Wearing chest with global defenses and 11% ES% implicit.
In game ES is 7803.
In PoB ES is 7598
Adding "11% Increased Maximum Energy Shield" as custom modifier increases it to 7803.

Items with the implicit are also incorrectly imported into PoB

### How to reproduce the issue

On further testing, this may be due to how PoB is importing the item. The implicit is being read as a local mod and being applied to the armour. When the item has the global defense mod, it IS applied locally (whether correctly or not) so the imported ES value matches in-game ES value. But when an item has that implicit but NOT global defense then the imported value is higher than in-game (the implicit is applied locally in PoB but not in game). Then, the implicit is applied globally in-game so if you copy the item first to notepad to remove the implicit and add to PoB, you get the correct item ES but total ES is not correct until you add the implicit as a custom global modifier.

Summary:
ES% implicit with global defense:
In game: applied locally + globally
In PoB: applied locally
Correct import, missing global effect

ES% implicit w/o global defense:
In game: applied globally
In PoB: applied locally
Incorrect import, missing global effect

### Character build code

```shell
eNrlXetz00i2_7z-K1Sp2vuFAP1Wiwt7y3mRDARCEh4zX6ZaUisWyJKRZEJ2a__3e7ol27It2bJhdvbuhRrGj9Onu8_zd_ohP_-f7-PE-abzIs7SFwf4CTpwdBpkYZzevTh4f3v2WB78z98Gz69UOXobHU3jxHzzt8FfntvXTqK_6QTaIWhXqvxOlx9mvOjv8NlEpeVIZ-ml-pzlL7PwxcGbLNUHjq_SMC5n74JEFcUbNdYvDj7GZTA6cFQR6DQ8Xnz-Rgd5NlZpoPMDZ6zi9CYLvujyZZ5NJ9A_PnC-xfr-MguB9uLy6u31baPzOG12DqP_y_OrRD3o_KZUpVPAPy8OhiAEdafP4xJYqWQKfNDB03bam4nW4Xayq1yfRpEOyvibPs7j8nhkxj9vh8kTxhnvar1fi8tpUsaTJDZiqlvRJ4J0NbnNSpWcXN1sn0xFmfWQDqhwdJSAhHrxNdQXd2lc6t7kV1lcZOlOo-5FfDxNErDufrTZ2I_TnnM8zrIkzO7ThSKfIEK7qIe5Vm-jynKuVRhPi3k7wboaXapUHWdFD_W8jiPdj_L0ph_dNfhNP0ozyiudg2-X_Qe7U4O6hxsdZBA_duljlyaNeezX2R4tT2_2abBHRzflInZg0a11_XWJknfGpRP9vUEmNjBcpuxkeJEupsEQ2cCwSYk91j3Cb1kJWatnQDk9v5pTxmnUGf9HD0UcqORSfY_H0zGkllv1RTeigETIdZ-41R_ZbTJ3ozKFwNTFx0OIyiey_uN18TmLc_2DLI4hjv0oi5HKii4eG4RpHGchuQ2ZOXhmSC_SoJ8zvk9zXej8WyOh40301-BJBir4ie7XYNFB7Y6LZght7umuIRr0BMlN1K-1DkYvARhdq1L3i2CLgTCXbpSooW5KlG_k2yJSwvET7PVrtCYm9wnixOMUYofsTpuGybLIMOJPyCbyHWX2UeU9UN9pqvO7h5tRrJMFtSBI9GlQW9fDsZr0amu102TQ1JLn9euyKTPmiSdM9mm3o_BOv6miGWE52jyniryXG19qQJvQINQreHkDMs8-G1ye7NZsmI-z6SLlSeF1Jx87i6pBcxK4W5ezdHGixgCornU4DZZyktct21mVcQnGMwbfsQUKFEMNwCk7-z1KoJRaEYHLN8wrSXZrMixLFXw5ycK73pK2veze4mY6mUAYMZbTt53Jite6iBvIyOtB_Ba8tOmkfGPO7N3BgnitA7wVH_TuZaXFaldUbEzeK9087oaIDfLVPrpFDEVYr6LqKrsHliOz6LAokGgfakAf2xuc5Tr9-8Mqf9SLvFcHp2k4zY2N9p7Daov1bp4_tcsy5tXFeJLlpZOoohwGQTZNy3NVjCATu1wIH3PiMqW0Fowi5fs0IoLAh17oo1AHrk8ObNNrrZIxSO-4ems6VkGp84qX8iOsqELa84JAeCqkWiMvCAX2hE-E9KKAKBJUgeH5sUqCws7sIp1MSye1CzvjuAh-96dRZNZuDmCmuV16Oj07Oz2-vfhwWguj2aT4EifJ7-l07JtVjur_CxB2o23YdIIsSdSk0OGLg0glBfCO4eWNaXsDCSMoe9EDRK3icS9qQAhBHoMu-xCbxZReQ7arTX0ozQJQL0IwDpXo_gK7fZhoY4hFX5nV0bcPtV0q6kVZrfv0m6BdUeqnBh2oh16Uc8TTi_o00cM4Mdm4n9QuwRGqRN6PHrJqHvvTsqe12fqp1zhMZdBrgk2g29M7-hHWOKvXIGpY2Ye2Tlz9jBIATm-1nehIg7n3dHsbTqq6t4rZs8D43Ppa4RQQuF_qcXH0AInwzIh3Zb1xrEowRD1-bVbfb7N5VH5drcbXnS2xeXFQ5lP4MNSRmibm83dTlcTlg8lpjU9rFgQ-LEbZvQFUFRsTAgpQzevX1TfDpKw5mD5mnVbzN9Owi_RDi0rtezvJFwdpnIAY0iCZhlCj18m-_jhRvun7wLkzq_rHJmfV3-jU1NvhbBJFkplyTKsJSBk7N_cGWKz0V7U04_nLcxhhzeJlkvkqIbMO68keLH2L590YPhcmBlZSGIZhbBSrkk9XB87XavYXNoRY8cHA9di8v9SlClWpnl6UIJunRkBPF5JsZVOJfGWeQUMEJvWZmsL4XWLwm54Z_VM733-l5M81xLXyh0SOtsn8OMvBdU7z6aQqghriBtPTeQpVJ63pr1ReGgCwUf6GEF518N1B_se5BgecB52tc-U9zcsUF1c61WVuuV8lZuF_byvbxG2HyQ7vTaDSoWP4OQ2GPSe_XdGzIecaNJrX-1d6UaEX7brHPeXQg-8O4qi5OTN2TpPfT5bIRRpAb5A-DKxbLAz8gE1s42hzQS85zDk5M1bOEkz-18ekWTb4Y6PSsChUUcQp1F75l901MYtBtcxgzF9SXeznmPVI_gumXfx34dgB_TQLBPRextFDu-uRPcLuGscdpno1zaEllIXOWQIf_oeb2FGW6rdQB5g6uFP-PSTeymcHqZv2zpzBnyVzkNI3E6p_QOK4j8RfV6uFHSijp7iXmewg6_epBl8a9fRftjNetaj-p0DWZU67oNbxxCzB_WTM1J3dfxA-9WS8D5L6CRiC72wBda32g1I5Te26zg-LoObzp0WVoywriz82jL_R99XSSLVYuzdWaGWyg8yr9k7N4CdD1DNVgCVX-zs_Uqu0sdlhjlV7p2JQ_CdblQVAJ6oY7W1P6xx2EbRp7NjW_2eFvBUODINgmqvgYZjaOqkYwru9atBa4le5DuJiz8WGReM_GfWSPxaDLTY-18S9U2XVzqZ_YWtqjfLBySLnItD_t2W-NZhcZmDI6c1IJ8neAm_jAX3TnuKumjtV-5-cnI4hK7xNm8vtP7SQ1M1ul7VDYOLcj2DKFSNnsQ_w5wTT8MGZnWpZMzX8s5wbDCo2eO9IpanZst3T1jrY7CD-GQenZvGzLO7cAJC957Xcun-sqtr9UTXjv9Mex09Q0YkGfx_HqVrbTtjNBNu49FfZcvufNbdbPZ7oopydOdx_zaid0Q56qxk4zV3hn6G8uAjMrZZU_wgQa-GyMrV657RDd4vm_4J4XUBMDsxlJpjHM4KfvczjsQP_TA6dKzVVzrVd1muN6uarH1ulxH3qkLHyYyPDPdxgVYD1K7sJfptr7ahq2JYY17vK8KZ5L8wMg5pJmtrvoT458eLgH5S5-JByidE_D_-BJWHokGLOBbwTHLmHAiPPhTecMw8fEimohHeUEFceche7nvmOMnlIuJAY3nhcikPiSdMIeHvuIWVUUvOOcy4PKRKY_BOml4Vmh9ylEj6TLsKHgnFJDzljzD0kCDgcEoqIe-hRjxwS7El2KIA5Oqy6EEzCyBmG8XPXpeKw4i89GAxzCTfT4tAEM-wdMkwEPSSEufSQCgptqrEJ5MK0OPYI9FxNkWL4x3Mxgd44sKXExQi6Iy46rAXEuP3S_Cu4Kw45jIgDRwqNMMVACN8KGAYjiAADAgwwYh58jqgH83WFGQEH0kNMCEeHLsz6EHsYUdsUhIFgDoccvrOdAPtK5qAUM2z4ALp1CRGHGBOEYIKue8ika-ZKXBASoUAJI6MwME8gDlykB7MBncEnyEwMdO8ZVtKw5XbUoHEmKLMTgN6w5C4DOcL8YHQCeGEMYraT53by0J1ARj8upjAu4dU9mc8ljBSmTkHwruC2K2MAxuKAAXTiesJK1oiEE_OagCpBJJhRI04EaiYCS9MrCA-mB2OCiYFkiDk1d8hBOdCTNBwIZ9QDSg6ax9L0yjCGVpIaHQiYFWgYTBYGwzA3n7jG8jDoz-UezFJKEApBnMDHnoReGbYz5oQYAUnP6B80Z1TGhJmTsRQpzcwQg-kQbFgK10pSwpAEM5oHqxTCGDABfRhXocSjoFWEDEeYCD30GJIHTgm-3LgQimV917Py3SoUnQJS0OEb4zx1unh__dq--MuoLCfFs6dP7-_vn0xUOcoi_T1O9JMgGz-dmN2vb_qxDUmPTUdPh_Dn6O7yxP_-9yB5oPIan7sfo8svxdmnu18-_ZIGv35w2a_xdy9-jaa_XL5h09_z7Mb79PAru52e0VfI-3xy_C5Ep-e_v_xtws_fDbEUly8ZOnnzkL-aeCj-LMRjcfuLe3r22svCs9OvkXvy-c1Zyj7-_iWN4vjb8PTs5eNbEVx89N5_ei3Pz77cBlffL16fv_w4xUen8dvP579dFg8Pv5fD71-HfvD9fZwUx_fk6vz7aDzNxvLjyek33_386uNZVrBcvPp0dD3-8GYYfXs1-fzpAUXX6cs7Hh9NP3_PfzslxafPSH24OCJfE_f63eUv01fZ10s3Ok2uXnu_5YQeu-7R6H0-mjw8Ll-rt8nHydnbm-Hk7Vdx-f79l_ujd0fXVmjD09Ph8G549OX05buz4dGH4dGvw2E8PM6Gp_fvbo8-fDl7f392PBy-O_r17uzr8btpDvKkyetzMvrymH36-Lsml2_c69NwSHH5-GwqJjDf1-yOXP12dvqeD1-8sIp9OtPs8-r2blGpuX5nA6ixDBs2IWWWVUrH9Rn7dUIT2Rp0qIuuMsYZnewisy7V4Ic7-zXBdEHYPT4T4hd0oovORvRGx110JrosyLwuMhu8F3S0c3gm4jS67SS0uWZB6HbR2UyxoOOddCZELOjYDCc-bZgFvIGEb7GBQQTmxZus1PY78-HsjcULH2J97xRa5cHopsxfHGh7NNEpahz79ywb_wr9UPQE8ursT3WO7Vyr8lJN5tjP0L6e77LYM3ClKk9isxFqD_nNkI0h_ATS9cQTyElzpvZInwWfNYgxr290tVE-LXR1E7Na4LEfNw7OGVJ7RpB4VXC8VmY16plzPbw-HVzHUemYM5SDD0olzrW-A9SlBtUxzBpxP3MA-AyaJzOPVDG7cAqh85mDnlAsxOB9Gn-daufiBD4RYPhgCQjyLuZhGMmIKOJSjSjygkAjprAgPBIscJXSIEFPeFow7UnlC58N7LCtzJ45Ug7qraZnDkWDWqEwg8cvHx89_gj_HQ0s6bX--swRcnAxBkgdxIaGDDD-q0HK9dGScXVL0Fma4YCQJo22uM-s1822qovBPyJzHHKa6_CfGKEmdQVnndl5zcEjTp0ycy7SUidQcJoPB488bD5r7_wRE381385vUDjVaqNZVBjgpb7MOVrzrc6_2WrPAYgKE4U-7PJiBXgH_whyFUH--6fLmo2XezXeYIS8bCSYtRjJqbpLtHNkrgmMBrej2PrdUXbfVDjHrsYRooSCG3IUAAjhUgdeEPEIcaVZIHXIfC_kPiI-9V2fRwr5GAHYCOC_ZYWjhcIb-j4yf422naa-uWjqGw8eVdKsGVixWAZGVeBBAwq6zs1FKPhgft4ZhPp1Guf2olMxGIZh4VgtCses_tYLa9Xn2KqSMNJQWP39XPCP3M1j6BA-Xxb--zcX796fDo6yskzMaTkVl6PBzTSZjKa5ObZSfGlqwAco6PsgdlfKQMnQDYQbRG7kKY_TKPAlpjT0fR8FYeB7XiAD7KtA4hCQKVbuist5Cw0Q2ZA25cveNZ_ye2NidhWyvkkCQlbByImgNh0c2-3pAoSZFhpaWEFAdZqGDhgxNLUeONPKybQ6DjhoIQ8sp9DxH5xyFBeVGJyRKpzb3Gx8h071eINNbcOp8WmnKu8cNTGPtgC9LnlavZRamqVUo0pwnjFQDQBiN8nmJ9UgRcRftFPdUXDUHZTJRTlrZSbZMp56HNUUqqDTZRmixS2P7HIW-CV44vnUz0Eax3EeJLpcjd9YsC3xmwvGmsYUcMZ1RDzsM60Qh2IpCqAaopKEKKA4QEoF2tcBhHfmQqnCFTU-HXoa-SoKgsHNSE107pgZDE6TcPZyycZYw8bWwvrLZkj3ll18YXTVGRfnZqLu08IJ7DncwrkHR3Ee8aqjwZLrOSrXTr2mWJmRJXKwNBoyEqlUVBlHv7YEOZdxasJxHQf69Sic84dJVo7M4p1aaRNqsCkKFjnOoPVpYgPT_EDkgtjeUCzA_r9p5xGxQafdJAfVCGvOhK7b-koSNE8MmX2Dl745nadHGxtnF1IWWhHezmnHbbHvV7l1vuN8WoCMBm8nZk6BnkBd1jRVKDZ9MEzP5dTTEfyPidBDIQmhEJaEIIXCQPlQVnJJFOCMwCMhhRKUEeGFCslum5SN1LOSdARqWiRdzH0W8sMM7DDNyrkgnNlV3LVk8RISawnxZ0loKxp3jDOBFmr2A4Y2Ua9gHnvMuv7mkc1elQWCBlWSVDZUYYcqO7XQzAe_RjyfxrFKKzucTkxzCoqzXziXWRhHMVTsC1qI1Xd3MCPlLFtylUAesqnJCeZb089h5c_KkQDHDdB1Zs--WTCs_aDmC-xscrhXD9WQMJ-5knlcyaIZ511ympMQaBlUUd2gOnsHrMuKZVuU1mZ77gwCvZHATQZRN4eZV2cQ1wI12haoBQaLbQbqiLmKQkimBGBWyKVgEXyksZJCU3AAFSLA1RjKVV8yj_uRzwBlC6WIz6QMl6xfuN0R-eWGiEwGF2kEb8pKhKffJ1kBUNmkvfO4PLQp1p61fYy5jVGWrIFy69A1w8c2rjS_XjbIhc1AKEjvwDbazHZOdaK_l9ruwFdkpJ1smJ1WBC7tDl-PWIXsVkco10InsK5ziIH3a8DCmjQIp5hjheMR2HrVoUUaCzDZMa_FEb8VT2yc_XOuYmM-Dvimmm-fObf2qWpdVtxWJ17BGGEI6m6qFzZsj82smjBhaIsJewjzpglDhSAAM0CA9rRkgFfBNGkAZo2wppRgKil3meTSoyHiAVUQ0iNhCg3mkkhHywG824ShelgyYbcjhNcamt1LqaGh0Sdo5qERbBf6L5w4smHLRJv6-HzpvKoUeq3N5JOHAV0KJcNvWdwM3fM8epJnkwJgXWxg_wwr3o-MnsfZN3CjQ3tv2vgTrSPiUn36iMkNxSbm3V-6stvyabdXmBlazO-Yx3ZAF6LZhalZB5T3mvrC5okd5tzBVdrw4w7DJWjZcC-HLy-OB8MkGIFDFeXsUsO7KRSwRZx803URZVR7q1MVxNm0MFcnlupaz0eUUk0i7klGBWCGKCIQWonyIM661PV8H-BExKQmbsiRS6G60lpoFkpBg2Xj5M26tmGKrKOoWkZSdYmwAA4mcADImFdcSwVFHX2IaCmsCG_hy9hfZ_XLXEe-Ngxvymma6rCVf4cucEsQmW83Dua7jU1RE4QFFKLg4Z7GEfOgelUe4lpK6tKQBIHyfJCzIgDapKu1lm6AkR94Pg8iTfEqkOtydTw4nuYAL2bFmQ3Fzc3Hed6y3xC0Dn4HjzhaX-Qh2OaGekFoFYcvnqI42OyhhK65DzRozZtzU3iTpY-N7lJtHzdYrwRV4Oexa5rah4xVC0gWA3XojbT6EFR6OoSP1PxqkAGtgIQWHnSRVmcKmxrFMhKRVoJjV4BLgJ-A10DMhtLRk8SHItMn2oWojzh4lAyxxBpTDpoPsCc8vqlcbGi3a0lCuD_sPbS39yxDyY51gR0ciLauBV1CZvKTLAsH51p9e3COdFIuFUPgJiG4EGOeh6NAca0U8uEFVpxIwRUUS_BtGCElwd9clxOlQ-wCPGSBCOmyxGlDyoytLLMx0ozQ4BHWphdB-hFh7VivxoCrEAqmFgfO-7JyQSsiqOjBpKGI8rUpCEIYTlSOwXod5rSTQ4UL3CDZVpgTygAd50vyLkzfkKrb-puTLLrNNeRc3VW3EtaqpaG-g-pjOM2zXA1A9eOJWRx4ZfyldvLqfBzIERNcv2lZVHeJWINXxN22FE84WVoXVGGAJcLS81w_EIgSP2SRFqHkXLgiBA8lkMi0hBQWhBBTIdNhztzQYz60Ur3WbF4CwLpu-iRZ9slO0A0-VaHXpqM1196iPBs3b7MM6PKqdiU8CxBWkQ6ydmbK11bMBia7ueoQzXxon94wuNaTRKdxMYJ4sYyB_AdTn8Pc6gHNK9mqIXY3lvc201R3DWar-MdZbi6Ud9sebwvVJ8r3E53PwvRRXIynVXqrwjQ4hPM2DyEJNYtIQNM0QBHHGpFQKRkqobDHNQu06xKJlCv9INQR4HPhKw6APdTapQhBsKGe6AQ5GDcjiOyK0_LH4zTqG6cXhT1fNJmnxcUuyi6xum11tnomgPMqnQZfEj24vc8e35Tm-uMq7NGBC8lOgJhppAjSyHdDggIRRUq7GsAnDwF5RsT1kQoEDkUYUVPRYx5SDI36w55H2FtEZOMwbTtOy6UE591bU4_MKmI_vMPZOqThojU9uBu18gcgHrcj0SagrIf5TWhT4YDfjwdv7eFAU0V8W3YiTwYeQiySKgqJEFGIzWEWADvgPBxcKuI-A3_yQLchpoELgEcp7lPIv1QSD6860SK2Pj5aiq2ML6v1XBXmgSWW3L4h9Zti0LLOdpTd18t38whVx516lQ0I5itueG3FbXmhow5Y5mFSMwAwU7J5NtBgqeo7Aj2FzS0RwNjNwNcj5MleFd5JrMZm0EtBD8KyCmHaWVNnzEMY_koa4AhzQZVZRJaepm4UYKah3sBCaR-80vWABvSlIwGoimsiPJ95_ao794_Dp8YFe-JTtyVr9t-Boqgd6dhMWIv4plR5MXibPnx3huOp2YdqukegQsE0k0J5XEBlDFCDR9JngcfdICQswoBBkPQJuIQUkRCYS1-65oAc5mpF1KJzLb4h3yFoO6j2HUGE4LzKhMAZJlg862qwnJu_TwDAmorOMSowk7MABS_V4ls34dsW2htL7BSt7hCvUHQszrVqAeDEHaBep9oFHNzGYw1IqXB-0fc6WS4PGBRaUHB5AUcaoo4igPAE1GMhBsELFZEg5K7nasxIKDVFrpRhAJqCQgIcY1UJ1V7rM-e1sdCmFhD48hh80lSEIC1zJAABOjcWDbMO4DvA1WZxzTkGFnk2uKqO3hUgYie3XO2-2XGWwtjz2YYvFO32dDYgOsDUuR6cg9tneRxsDx1ti5qjDLDcd4PgUqg_NPQKKDCZ2oufa7IL_MAlvqeUr1lIsEIAkpBgMtIMkrb0RRAxX1BhkzKHQC8jiPGKKQDR2KNoQ2nVtZlkzxswp5bNWgrEDhCYheDm9w5UHqoa_SwnNPmZVfOx3dFZYurcmU0oyCY9qtjBBjYqKbIZr0e4dT-ygQs6JwC1WWr3jLpJrswzWc0mwxVYVdnlL-1V9FmW-zGwTSHy6WIExgMAplxXuc9R4CMGiEtCRAqYIFA4YwYKhVKZ-dwnHoWARr1QCI94UYR9LCUOXSwjqlYX_yBmxWNzLhWkYvJ2feQEopM5vurYXylZ9qFFAAM4AuZZPQKusdRsXcI-uc2E8XG90WZya3OKaqy3-kfbuZ9jBWk5eSjGzk2g8kGl8E7_8BWTELmJDATVIQ6oiiIZcXOs3Q85ka7nI6BRnh8KFEQEM-NGNPS5DhnVqC-OJSv-QTr9Y1dzr5Jib_O2mPaydQ2vt4csr6F0Grt9SqtRMUTVam-tQ428bQcyV2OoCW163hrlmAx9SLgC0E_IQwnqgdgWuAJDdRIKDuUepsqH2oS5YeRDXBdaCuwxl4UuCsnybrrLm-e02H9mlKuKoLYVhm59HqkiDixuMhtrPxrk2srPs8ysNZmDnTY3dyvc7Kghj3HAvKFkjCkfFI3NThtzoUyRvq8irjiYBYPShRClAimkD19IzACqdae1zQqXnQonbdKo4EBT4bs5Ouna6P8j1XwSF5mBknavDt5MEvWwSdkGooIpOufmVFM34Q3go856tqOc1fZHtmZIfXPaMwlNCQ8qn0gTAO0R4hCkFVRIXAseMUA8iuMQ6iLX3NHxlEuDyOx5hQGSaHVDtgnVyWoOXIrrrOVQ0jxvmXW0LGyszMbVkQNtjxCaBd3H7rYFv_atW2NYgZpMKpD5YOqiUXw3MlcO59G9paFjdu21CremVtmaWvPc5PIP4N8g_G1RmSCzlQI-SV0VBADTBSVYECR5SA24hMIJC-YB9OSA6QOJXB5AhPYRV0FEV50UdTop-7ePyrix0HetI_PMbTOK5bNV1dLxH-raPw2htp22MGsVdzoMwUBuJir_si2GB1RzJgKoSZgkHAJ3FDIUYqWldgXiPKKccuaHiArsB56p8DhlAGehmCGE0_8vMZxtOGffGcOz_EGl8Wxt6TXoNEv_6CCO0da6xYL6PB7DaFriheTUbPiZozVgEJEvQo9gKGewRppyDMULIz4NNcJQyCgduspc6wwic3BfSX_1SM2fVLhUSWpzdMXtSyIfDe_FPsjpgx4sVLMmL48LkEdEfSkh9yHwEhz6HgAiEGQkfa2hqIOyz6XwoRI6gNIPhxLQL_cRdSO0udBbWq3FLSdhlk5ZDMT2-yqsjcSuuLY2tgvuv4LozVEz521aJGpqjo5HWQ4hvj5C5NgtSrsubI4aKbsaWOVE-1AIy8Dq7moE8BUG3EVYH5daDcp2J88eeat29lTRvFzRwm3puTld6iedF1Y-moNT26pWiRWBykUgoojGEBCZS5SQTFPqkSgQQSgjn4V-ABWt9DHxQxJ5lESSIviYr5weJp1boKuhk_5A1drDQHBjc2txXvtmBFF3Bpd2KnOHywumvetbvHwmYEOBa0d_ZkzkjTXOLn3TNn2nZZ5NHuqFvM7VHALljflZMqFCBH_Bm7kMsBcB1qUcQBOOlK_ADgRhkmLtY6G9yFcUKwaYiiyrGi9HvMamWQ_1zPame2ydYbllFa0-v2TS4XzpmfVqs0A8dcOONbS2s1yXNkz3uTq47UQzYsgb3ECytHdyvpv7lvW1EftESzDbj1megMusXyDpOOv58bH5e716iWRl-_nvXg836rgXaDcf7SEyc4ChqEKbrRxm3tzcQ93xPiBGZNMBZNINYpb2tnc5bkm2JqUO02iLvh8za4npRrugZNsxYYJdr9_R3k4lo-16QBsO4vH1c6yPaPsB9iXx3CTZ7GeFFo93nt-Idme_6LGgqvbfGreXiVwnmj21eM6ohcYcB2twoV1dNW5yE7RONPsthnlXootRc2K8i6hxXZ10EjXvvpN1osXT6-ZUrJuq_vmOOanbSYpXSHELV_vsm2bPLeJYeurZnNDrYNYQG8FtzOzzKOdjamFTbbA2LuTP1FhfDd9wLby5kdgmESMQZ-g_FIWa1WlNg5k9EaFVmCvNSL9m696xLo49R9Q2mS2jMk60Y5NOB261zrYx0f0E3E8K5Cc1Y_sNUuzXW89mbdLEWzTcZlBbNFDFxF07ajElsU8_W-yvKzf04Ez39yO8z0zYfsaA9zM9tl0_6_myRbS78m0zsD1n3iv0tCT07QPaIw7SbfOeZ8EdFdgu5r0sjO_TqJdXriOifpCox0z53oIle5ii2M-b6H4WTHe3M7Z_7N_DqvHewqd9nLMF__YDwFsH_gMgqKcu1_F2b0WIPQxzf038gMX0DcztRcUuVUVv7WyRXVdF0iPQkL0lvGfQ6K_S9cKpx3xoD0m1lFu9NcH2lhffJ-P1cZr1yrC3qW8ZU2dV-bQuK-2z0-yTyOyvL2dpFN-t_ZayNvekL4qjzPwK2ezHl2_ifFq0_PCyKVHtvXTzgJzpWIfVxYnZpekDx8-yRKu0fkTaOoPxfFXzjVa5_1C1b_yGM0ItrUJdZuYg_4lWdY_2x2wXrVwkKNk03up2d_9xzhvaVXgd2tvkezSvHkGxc_NpUWbjyyxsqMT7q3PReLTY8hrYeeMneFvHYR46vPRzvTtoqpL4TOOLWSx01tJ8Wujl32fvLbJl07pIr1RRkhsd7MKiejrDjlKHIa__JHvvPt-mjYdGVc8B2MXMzDOR-rjT86czP37-9EqVo7eR_cF3MJG_Df4Xa4P43A==
```

### Screenshots

implicit w/ global defense in-game
![image](https://user-images.githubusercontent.com/108958398/178076036-4de51095-d7a9-40d3-879b-fdf111f23d83.png)
implicit w/ global defense in-pob w/o 11% ES custom mod
![image](https://user-images.githubusercontent.com/108958398/178076147-3bd1937f-4377-436d-a3e7-c249f28aab1c.png)
w/ 11% es custom mod
![image](https://user-images.githubusercontent.com/108958398/178076223-1c97d832-96e4-4771-97d9-65efbe298287.png)

improper item import with increased es% implicit in-game
![image](https://user-images.githubusercontent.com/108958398/178076315-43420c62-38f1-4ce2-b2cd-51a4f462ce1c.png)
in-pob straight copy/paste
![image](https://user-images.githubusercontent.com/108958398/178076391-96cafcf6-e66d-4546-a054-29ade81e3d65.png)
in-pob after editing out implicit
![image](https://user-images.githubusercontent.com/108958398/178076490-a4d1d1ec-20d6-4964-98d6-1d04bf0d7e72.png)

**Comment by LocalIdentity** [comment] 2022-07-08 22:48
Duplicate of #99

**Closed by LocalIdentity** 2022-07-08 22:48 UTC
Labels: bug
