### ISSUE TITLE
Checkboxes aren't visible and there is no bottom scrollbar

### ISSUE THREAD

**Issue by imTheSupremeOne** [PathOfBuildingCommunity/PathOfBuilding#4268] opened 2022-03-07 12:31 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

you should be able to see or accesses checkboxes...

### What is the actual behaviour/value?

There's need to be a bottom scrollbar for non-widescreen monitors like 5x4 (1280x1024). Without it you can't access all the checkboxes. You can't even rescale  window to force it appear... 

### Build code

```shell
-
```

### Screenshots

![image](https://user-images.githubusercontent.com/13508453/157034508-8f750283-7fc8-4c17-91b9-db432ac3510d.png)

**Comment by LocalIdentity** [comment] 2022-03-07 22:50
Duplicate of #4179

**Closed by LocalIdentity** 2022-03-07 22:50 UTC
Labels: bug
