### ISSUE TITLE
Font size / Font rendering

### ISSUE THREAD

**Issue by carlostling** [PathOfBuildingCommunity/PathOfBuilding#2028] opened 2021-01-13 17:38 UTC
I am having massive issues reading the text in PoB. Does it support ClearType? Is there any way to increase font size?

**Comment by Wires77** [comment] 2021-02-09 20:54
Unfortunately, the UI is fairly static in PoB and we won't be able to increase the font size easily.  Can you post a screenshot of your font so we can determine if it's an issue we can solve?

**Comment by ppoelzl** [comment] 2021-02-11 03:21
Duplicate of #218

**Closed by ppoelzl** 2021-02-11 03:21 UTC
