### ISSUE TITLE
Sadist passive

### ISSUE THREAD

**Issue by asschun** [PathOfBuildingCommunity/PathOfBuilding#4303] opened 2022-03-22 22:34 UTC
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Cluster Jewel with the Sadist skill active adds no DPS

Didn't there used to be a section for chilled/ignited/shocked recently? What happened to those boxes?

### Describe the solution you'd like

add chilled/ignited/shocked recently back

**Comment by Wires77** [comment] 2022-03-22 22:52
Duplicate of #1614

**Closed by Wires77** 2022-03-22 22:52 UTC

**Comment by asschun** [comment] 2022-03-23 02:15
> Duplicate of #1614

the solution posted there literally doesn't exist

**Comment by Wires77** [comment] 2022-03-23 02:47
> > Duplicate of #1614
> 
> the solution posted there literally doesn't exist
> 
> this needs to be reopened

It is there as soon as you allocate Sadist, I made sure to check before closing this issue:

![image](https://user-images.githubusercontent.com/1209372/159613969-fa1cdd67-91f1-4f93-9b13-ee134dd44c49.png)
