### ISSUE TITLE
Cluster jewels not showing correctly

### ISSUE THREAD

**Issue by tyreec101** [PathOfBuildingCommunity/PathOfBuilding#716] opened 2020-04-02 17:43 UTC
After importing a character into PoB via the GGG API or via a pastebin code, the cluster jewels are no longer showing in the tree.

![image](https://user-images.githubusercontent.com/63068072/78280785-eed83380-7519-11ea-851f-8022d7ebe02b.png)

**Comment by Thousandzzz** [comment] 2020-04-03 03:05
The Claw and Dagger "deal 12% increased damage with hits and ailments" large cluster jewels will not "expand" in the tree, like the screen shot shown above

**Comment by endym1on** [comment] 2020-04-03 21:33
Same here
![cluster](https://user-images.githubusercontent.com/20949166/78406745-90877f80-7603-11ea-92d4-1c5c6915a3f6.png)

**Comment by TommySheluby** [comment] 2020-04-05 17:27
The issue is resolved when you change the order the mods are in for the implicits. If you edit the item and swap the text so the dagger mod comes before the claw mod the jewel will function as intended (This was only tested once but worked).

**Comment by tyreec101** [comment] 2020-04-05 18:12
> The issue is resolved when you change the order the mods are in for the implicits. If you edit the item and swap the text so the dagger mod comes before the claw mod the jewel will function as intended (This was only tested once but worked).

This worked for the Staff / mace jewel I posted, but I guess each time I re-import it will break again.

**Comment by mitant** [comment] 2020-04-09 18:04
The parser is not interpreting the jewel's enchants as two separate enchants, whereas the item is being treated as such.
According to the POE official trade site, it's meant to be a single enchant, not two enchants, as POB currently defines the cluster jewel probably for ease of handling the mods.  My suggestion would be to align the parser and the cluster jewel definition, because they're out of whack leading to the rendering/id problem.

**Comment by mitant** [comment] 2020-04-09 18:07
FYI for clarity / temp workaround without code changes, just editing the jewel
{crafted}Added Small Passive Skills grant: Claw Attacks deal 12% increased Damage with Hits and Ailments Added Small Passive Skills grant: Dagger Attacks deal 12% increased Damage with Hits and Ailments

change this to
{crafted}Added Small Passive Skills grant: Dagger Attacks deal 12% increased Damage with Hits and Ailments
{crafted}Added Small Passive Skills grant: Claw Attacks deal 12% increased Damage with Hits and Ailments

**Comment by LocalIdentity** [comment] 2020-04-20 01:56
Fixed in 1.4.169.1

**Closed by LocalIdentity** 2020-04-20 01:56 UTC
