### ISSUE TITLE
Error Loading Builds - "attempt to index nil value" re Timeless Jewel

### ISSUE THREAD

**Issue by alaindwight** [PathOfBuildingCommunity/PathOfBuilding#4562] opened 2022-07-12 09:41 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Expect to be able to load builds.

### What is the actual behaviour/value?

Loading some builds fails, eg. https://poe.ninja/pob/8C9

### Character build code

```shell
https://poe.ninja/pob/8C9
```

### Screenshots

![Capture](https://user-images.githubusercontent.com/12209350/178460708-1bd1affa-32f2-489f-bb60-4c79d27982f2.PNG)

**Comment by QuickStick123** [comment] 2022-07-12 09:44
We had to remove GV due to an update issue. You can manually add it to Data/TimelessJewelData which will fix this.
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/dev/src/Data/TimelessJewelData/GloriousVanity.zip

**Comment by Halicon83** [comment] 2022-07-12 11:48
When I try to open the zip file, I get the error message: "The folder cannot be opened. The zip compressed folder "C:\users\.... .zip" is invalid.

**Comment by QuickStick123** [comment] 2022-07-12 11:50
The zip is not an actual zip you just need to paste it into the directory and not unzip it we have a fix anyway so it should be fixed relatively soon https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4567.

**Comment by Lothrik** [comment] 2022-07-12 19:19
I was able to reproduce the error you encountered @pascalw99, it should be fixed once #4567 is merged.

**Comment by pascalw99** [comment] 2022-07-12 19:28
> 

FYI i was actually on Version 2.19.1, and when i disabled updates on lua and stayed on 2.19 it worked perfectly

**Comment by QuickStick123** [comment] 2022-07-13 03:26
Fixed in most recent release.

**Comment by XEnvyS** [comment] 2022-07-13 04:56
Auto update broke all of my builds and won't allow me to upload and view and build.

**Comment by Wires77** [comment] 2022-07-13 04:59
> Auto update broke all of my builds and won't allow me to upload and view and build.

What kind of error are you getting and what version is shown in the bottom left?

**Comment by XEnvyS** [comment] 2022-07-13 05:00
Version 2.19.1, the error is the same as the picture above.

**Comment by QuickStick123** [comment] 2022-07-13 05:02
Can you show a screen shot of your timeless jewel data folder

**Comment by XEnvyS** [comment] 2022-07-13 05:03
https://imgur.com/xEH0OjJ

**Comment by XEnvyS** [comment] 2022-07-13 05:04
https://imgur.com/gBek5vq

**Comment by XEnvyS** [comment] 2022-07-13 05:05
the last one is the timeless jewel data folder.

**Comment by XEnvyS** [comment] 2022-07-13 05:11
Am I doomed? Respectfully.

**Comment by Wires77** [comment] 2022-07-13 05:12
Do even new builds give that error?  Do all of your other builds have timeless jewels on them?  Can you upload one here for us to test?

Can you try clearing out that folder and restarting PoB?  The updater will redownload them for you

**Comment by XEnvyS** [comment] 2022-07-13 05:14
They are the same build, as I'm a new player. What would you like me to link exactly?

**Comment by Wires77** [comment] 2022-07-13 05:18
I was asking if the error happened when you tried to open or import a specific build, or when does the error occur?

Yes, delete everything in that folder in case the issue is some bad data.

**Comment by XEnvyS** [comment] 2022-07-13 05:22
The app auto-updated which kept/keeps giving the error when I try to load/upload a particular build I was using. After deleting the folder and reinstalling I'm having the same issue.

**Comment by Wires77** [comment] 2022-07-13 05:24
Do you have a link to the build you're using?  Or if you look for the .xml file of the build in `Path of Building Community/Builds` you can upload it here

**Comment by XEnvyS** [comment] 2022-07-13 05:24
Here's the builds pastebin to upload, if that works? https://pastebin.com/ATj6THEm

**Comment by Wires77** [comment] 2022-07-13 05:37
Yeah, that was perfect, thanks.  Looks like that build has some older trees in it with nodes that we weren't mapping properly for timeless jewels.  We'll work on a fix for that, but in the meantime, here's the same build with those older trees removed: https://pobb.in/VosM_MnY_2Er

**Comment by XEnvyS** [comment] 2022-07-13 05:39
Thank you so much for helping! I extra appreciate the temporary build. < 3

**Closed** 2022-07-15 05:38 UTC
Labels: bug, crash

**Comment by message** [comment] 2022-11-13 21:32
I have an error, when I press `Generate` near `Fallback Weight Mode: Sort by Full DPS`.

P.S. UI-wise, I thought `Generate` button, does searching from the beginning.

To reproduce:
1. Open PoB (v2.21.1)
2. Import `https://pastebin.com/n6N2Gb3w`
3. Press `Find Timeless Jewel`
4. Set `Jewel type: Brutal Restraint`, `Conqueror: Any`, `Jewel Socket: # Wind Dancer: 60735`, `Search for Node: Total Dexterity`, `Fallback Weight Mode: Sort by Full DPS`
5. Press `Generate` to get 
![Screenshot 2022-11-13 221935](https://user-images.githubusercontent.com/492026/201545299-1e29ba1c-7f85-4442-87e0-b43d20335ef4.png)

**Comment by QuickStick123** [comment] 2022-11-14 22:17
This is fixed in dev by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5055
