### ISSUE TITLE
Multiple configurations

### ISSUE THREAD

**Issue by bitflipp** [PathOfBuildingCommunity/PathOfBuilding#5933] opened 2023-04-05 10:40 UTC
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Configurations have a strong impact on calculations. You have to micromange configurations to account for different scenarios whenever you tweak your build.

### Describe the solution you'd like

Analogous to the (excellent) multiple passive trees implementation.

**Comment by Peechey** [comment] 2024-01-07 23:55
Duplicate of #2794

**Closed by Peechey** 2024-01-07 23:55 UTC
Labels: enhancement
