### ISSUE TITLE
Crushes after lunch. 

### ISSUE THREAD

**Issue by Seawed** [PathOfBuildingCommunity/PathOfBuilding#6444] opened 2023-08-23 22:39 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/27236645/12b68772-0060-4780-857a-6d962d7a066a)

### What are your system specifications and configuration?

windows 10. 
latest version of PoB (re-install can't help with this problem)

### How to reproduce the issue

download latest asset (setup version)
install (default)
run

**Comment by Wires77** [comment] 2023-08-23 22:46
Duplicate of #6394

**Closed by Wires77** 2023-08-23 22:46 UTC
Labels: bug, crash
