### ISSUE TITLE
Incorret Marble Amulet with Life Catalyst Calculation

### ISSUE THREAD

**Issue by TheoreticalGer** [PathOfBuildingCommunity/PathOfBuilding#2561] opened 2021-04-16 08:38 UTC
Hi there

Just noticed that the Implicit Regen modifier of the Marble Amulet is calculated incorretly when combined with the life catalyst.
It doesnt go from 1.9% to 2.0% but instead from 1.9% to 1.10% thus lowering the regen.

1.9% 
![Regen 1](https://user-images.githubusercontent.com/82643194/114996994-b47cd280-9e9f-11eb-9bb3-756d570c1df9.PNG)

1.10%
![Regen 2](https://user-images.githubusercontent.com/82643194/114997007-b6df2c80-9e9f-11eb-8401-082aed04e0a8.PNG)

**Comment by LocalIdentity** [comment] 2021-04-16 08:39
Duplicate of #838

**Closed by LocalIdentity** 2021-04-16 08:39 UTC
Labels: bug
