### ISSUE TITLE
Ignite chance incorrect

### ISSUE THREAD

**Issue by Tank-Destroyer-6** [PathOfBuildingCommunity/PathOfBuilding#5821] opened 2023-03-31 19:23 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

Using a skill with 0 chance to ignite and 5% crit chance (armageddon brand for example) the chance to ignite should be 5% because crits are the only source of ignite

### What is the value from the calculation in Path of Building?

Using a skill with 0 chance to ignite and 5% crit chance (armageddon brand for example) the ignite chance is calculated as 40%, not 5% because crits are the only source of ignite

POB claims:    0 * (1 - 0.05) + (100 * 0.05) = 40.13

### How to reproduce the issue

1. select a skill which can deal fire damage (ie arma brand)
2. check chance to ignite in calcs tab

### Character build code

```shell
https://poe.ninja/pob/VsD
```

### Screenshots

![ignite bug](https://user-images.githubusercontent.com/68885117/229210956-da28c079-caaf-4f62-a0c2-12224c2561e7.png)

**Comment by QuickStick123** [comment] 2023-03-31 22:38
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5380 and already fixed in dev.

**Closed by QuickStick123** 2023-03-31 22:38 UTC
Labels: bug:calculation
