### ISSUE TITLE
The correct value of attack speed is not calculated and affects the calculation of damage.

### ISSUE THREAD

**Issue by ren130302** [PathOfBuildingCommunity/PathOfBuilding#7090] opened 2023-12-18 15:35 UTC
### Check version

- [x] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

In the game, the attack speed is calculated to be 4.12.

### What is the value from the calculation in Path of Building?

In this application, the attack speed is calculated to be 1.49.

### How to reproduce the issue

1. No buff effects from auras or potions.

### Character build code

```shell
https://pobb.in/pbSKBJAoAi04
```

**Comment by LocalIdentity** [comment] 2023-12-18 17:35
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7078
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7066

**Closed by LocalIdentity** 2023-12-18 17:35 UTC
Labels: bug:calculation
