### ISSUE TITLE
UI Improvement: build sets

### ISSUE THREAD

**Issue by sampaiodias** [PathOfBuildingCommunity/PathOfBuilding#6349] opened 2023-08-15 14:49 UTC
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

When trying different build variations or leveling stages of a build, users have to click multiple times to "synchonize" what they want to see on PoB. For example, if I'm looking at a league starter PoB with a tree for levels 1-12 and I want to see the next step, I need to change the tree, then change item set, then change the skill set. This is both annoying and error prone.

### Describe the solution you'd like

Add a dropdown for build sets. Ideally this could be a dropdown somewhere at the very top of PoB (see image) that enables you to change the skill tree, the skill set and the item set with 2 clicks (one to open the dropdown, another to choose the option). Build sets on this dropdown could be automatically filled by looking at trees, skill sets and item sets that share the same name (kinda like a dictionary/map).

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/14952766/d2bc62e4-d864-448b-ae78-52a75f483486)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/14952766/870004af-72dc-477e-aacc-23b759d2bb8d)

**Comment by Wires77** [comment] 2023-08-15 15:22
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5633

**Closed by Wires77** 2023-08-15 15:22 UTC
Labels: enhancement

**Comment by sampaiodias** [comment] 2023-08-15 16:24
@Wires77 while I agree both suggestions are very similar, perhaps the simplicity of this one (instead of managing build sets in a separate menu) could be easier to implement? Mentioning this as #5633 was created more than 6 months ago.
