### ISSUE TITLE
Strength wrong when using ngamahu, flame's advance

### ISSUE THREAD

**Issue by Dreschau** [PathOfBuildingCommunity/PathOfBuilding#7247] opened 2024-01-15 03:15 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

Strength in game is 2346.

### What is the value from the calculation in Path of Building?

Strength in PoB is 2543.

### How to reproduce the issue

Allocate the ngamahu, flame's advance ascendency talent either via forbidden flesh/flame jewels or spec into the node. Socket cluster jewels with +strength and % increased effect. The talent only gives extra strength for passives on the tree. PoB seems to be giving extra strength from ngamahus onto the passives of the clusters.

### Character build code

```shell
https://pobb.in/32zizv4ZB4u9
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/155371477/845f08d6-8d92-4d58-afd1-3b3d162be6f5)

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/155371477/822d406a-756b-4c86-bc06-e796eaf7ebdb)

**Comment by Nightblade** [comment] 2024-01-15 03:37
Dupe of #7140

**Closed** 2024-01-23 21:01 UTC
Labels: bug:calculation
