### ISSUE TITLE
Attack Rate Cap? Don't know if this is because of main game or PoB limit.

### ISSUE THREAD

**Issue by Amountstax** [PathOfBuildingCommunity/PathOfBuilding#1367] opened 2020-09-13 19:26 UTC
Theory crafting an Unencumbered Cyclone build and hit a "Attack Rate 30" wall. PoB doesn't go any higher. 
I tried looking for a PoE max attack rate, and couldn't find anything on it, so probably PoB?

Should note that, I do not have any attack speed on gear, nor is my skill tree just all attack speed nodes. I'm theory crafting a non-troll build.

Essentially my attack speed is Unencumbered + Cyclone + Tailwind boots + Onslaught + Berserk + Ancestral Protector + Punishment + 219% from tree (120pts used -112 on tree + 8 in cluster)

Without Berserk or Ancestral Protector I drop to 26.68 Attacks Per Second but, both will be used in boss encounters.

Curious about what the tree looks like : http://poeurl.com/c0fD

**Comment by Regisle** [comment] 2020-09-14 02:20
duplicate of #1266 there has been some discussion on removing it untill it can be re-verified ingame

**Closed** 2020-09-14 02:23 UTC
