### ISSUE TITLE
Two-handed weapons have one-handed influence modifiers in 'Craft Item' 

### ISSUE THREAD

**Issue by Seikah** [PathOfBuildingCommunity/PathOfBuilding#5934] opened 2023-04-05 11:22 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

When creating a two-handed weapon with Craft Item, the prefix/suffix dropdown lists should have two-handed modifiers. 

### How does Path of Building behave?

Two-handed swords, maces, and axes seem to use influence modifiers for their one handed equivalent. 

Non-influenced mods appear to be correct? Damage over time multiplier has the correct value for 2-handers, at least. 

### How to reproduce the issue

- Craft item in items section 
- Create a two-handed weapon, e.g. Two Handed Sword, Exquisite Blade  
- Add any influence, e.g. Shaper 
- The prefix/suffix dropdown lists will offer mods for One Handed Swords, e.g. Supported by Added Fire / EDWA instead of the expected Supported by Cast on Crit / Cast on Melee Kill. 

### Character build code

```shell
eNqtW29z2jgTf10-hYaZe3VPA-ZfQ4bcDQGSZia0PJD2nudVR9gCdBEWteQk9Kbf_VaSDQ5FxsbOzfQM2t-udle72pVF78_XNUPPJBCU-9dV56JeRcR3uUf95XX1y-Pt-8vqn39UehMsV58XNyFlauSPyruefkaMPBMGuCqSOFgS-TXm1PwGnDbYlyvC_TH-mwd33LuufuI-qaI59j0q408uw0J8wmtyXZ25AK4iLFzie4P99xHhCgfYlSR4UFL7oeRj7sGoDEIYXWPqz7j7RORdwMONntQzJS-G5n48-Tx9TEyJ-skpgUbvehOGtySYSSyRgH-uq30wDF6SIV7Dv8ANsxBYNRrdi26327q8rH_ofKjWUrE3YSDkWQxmG0K8Hca5aLZtlJOAjBYL4kr6TAYBlYMV9t29uPaFVcZR6k6rmUY_DpmkG0ZJsFfIRv_xF_bdro32kUvMhpPZjrTp1C9a3W6zftmtN9vtdByXO1zdRvkXlasbBlY9Q4rC3i99KsmZ4AmngvsF9EtCrSoOQsYgQDPRTokgwTOW9O207Lz5ek79s6w3xj4ecJHBR4pyQgKIf5kLMCMuh5SRV0ZO5ANdkOyUufSIAHlnc54eo1lWutyMz5vQFPJjNsoZD1lGSpnIUClR8D1J6DjWBDUkr9n4JQmdpmOjvPdlBn5D8syl3hVP6asTxejjZJ_KuxeO02zW661uo-NY5zFZbQV1MRvjV7oO15CzH_ET2QvspCzA5Ur6kG9s0OalDXpLA5IfNeDMOwO1wlzkh6nwymAE2KfdK0V777vZYvaLH-jUm9jeO6mAKUSSKifmjGRE7EVE8bhfkPUTopbEj-Rts6nzQIi7uoPqa4olyZZ990s03ayKNpNZFeERs7YzAnIYSQEtRrropoFymmnkk2C5na0oYV4-6nhiA7zJkCSVmZPoTOZ-Ky7XiklCc5rkLxx42baSvHN6xiKZYp1OurkMebaFSaDgBIBHDgrhur2a53-rWp7lg_WDNQ-DjA43xJkUiHcH08NMiRe62bajGwbNWNbZw6wYy4XoS4ndpyH3liSXkPyIWbjZQKJQLs-KU7sblNc0Uaa872Sg_gzrNVPYqo0wu4A9dWYBu609u5QDSHZd1PacQ5k9eWYRu_Z4DBlhDZleN9djnuivrc6BjipTe6QJM7ZpE_4CM1-pIxORjxrKmH3pYp1KQPwf28z835BnEjDyvTBQoZBZxiHimJhHuoZsKcQQS4y8qO79igOKfdnQ5zmC4MBdPYDrbzFjc0gA19Xkt-rTAdCJfdur6SMr9XS_3vBA6i8HmLlCS7_3N6FEvj5vWlPhfpuHi4U6PAIBMtDnYaPb29Hg8f7rKJpwEiKeKGPf_HA9Vwcj5v_7ZTUjOmsiEc6FebyufqXkZaZQQyIxZWBElzOGN4J419UFZgIkU3jUNDOwjCtTuGkqqG7js6bjvPYEdk6jVxJI0Be2WzegxDqv3fiJSRmBaitWDrZxUyc4dkYm2w-wkKZUsFhKH5nZuajjK6s6ajAFC2sGM6vkaPSEJeR2QwTsv3RBXRUb6S5_BGpDlWIX14Wwcrcp_o72LDsPfSRmY2AG7WBzrGVDR6MpVtVHalarmlE7fEhcbNXdDNrBu-qT-2AmG5cdVQqnT9zXixyCpk-Z2l-snh0xsiOxM_wsVyQwm5aV0xhyVEySGjgBnYfSHsYJihRb6V7YYiE1Zoeafs-igxpLyURveiCLQZM0dlamd7AmsjSoqTWs9osqlxQXRJW5xfxmNMUIcXNi0T8aTgkSnX_7z5x6pnq1hMsBWVrCgDq9OBtdiRdnc1ijF-d4y7B4svo7GrXDv0DvRuX2CBfzoioTExVUxTio2CrGYXpYSOyx0_QSQuevIVkQMHRqAtvRpPhXhv4QNjmZ4tuMrPS0jgfCXrVcvEwqP6ppbo5mgUank2lr2JCcYAR70ceUaicbp13f9JFgpt5hcVaM4S-nsIX05FJg3xuqw56CiqqzonADzOKZfT5Wru5desi1V4sbiZ6u3QQS0GHckbW42UJHeKt2p4M3aFgbNirupWlvkphYnEcWOGTq-_-GWCUW1WUlvn0wr-B9Hqx3Z_jAasVfVFI0HFUpKWCveXgwI30mI2ZKXGwvY51oQlrNuHMyOqnHx4CQeOpQySoSA4MPyff2956e5hoqdhJsozpFtWc-dFTw0L68bDarSAK7xJ2BhhNdBzBwxfld78v0QT-8W0m5EVe12svLy8UGyxVfkFfKyIXL17UNgGBO73Ub9l6xrfXh72bZ13-aUS3m1DP3BIRZDzU1d62mUk49fOJQDakx9WX8Qauuerao35zJQOnzg_P1_7WuyrAQJ3KMN-AOysxY5J5m5BKo54cUrBHobBD7WBH-L-6ee_cSnBIZWT3HyyMUxLxT-4vgDff110qO6UWBMPKZ1nEK7a_cXqFpfzqqfIJZK4LK6PV7SAUU1eiGYY9UZiu8IYEZGwR4IYl3hdScKpOALOjrFfoHuvYluapftH8-cBeze98NCIZweHswGJ2g9z2PeOo86wu0v41DJs5PM3MoglXajLHROiWeAjk7kLqYUZlBE_6Gwx3j8xgYB-n-SkJj1f4GfzvYGx76Q7Tur1CjXomWwRW6e7_7r6IdNiXfr9CHegX6OkZdqmicyj8SL8WVp0X_B1pfqdT_-Xu7_huSHJmJoUH0PYL1QZ8I2s8tEkc8dKf9GxC00xzNt0gLRs4l0kZEyorI6HkEKY4id4aNgOiFyhUyzbOoOA3nN0Rj_6HYgbGQ31ttrUgEVQ07UtZNqtBsJDmkiUMmZ-hwG3NvqtyHtBPVm5J2NZFf0igaJymaJylaJynaJyniNwI1FSq7gFN50haVyWDszRiHjAqIyRySkM6D-tQIFs2zqhvUkMl5tXSAEYKcPcQ5BbnhsE-i_nwrhFqWeimhdg6ZN4TJQ3wjB14Xmqh5hpZo9oI3h6Jb5zAqoH7Eo1ECj-MKdUpQqFOCQmfxOKaQk2dxHVudzRIs0ihLmzzr7SOBhkAWsseRYOsUnkEjN4fCIptl2b9dwmJwSggPp4R5tHKuhLJSTKNoRLZKMGD-PaO0FNssqn-jYAjnm4C3ReZcsMgaNLVFEQ7HA7tdmEOnLLc6ZeWY_EuzuB1bhX3ZLmdR5VG-vw4ZkSVkwmYJCaVZMChbBfFOOfY_e6fMvWhbuRHnVFEFrdoumqtLckurrORSWl19dguVAzel_jKXC4-npkY5Pihtpyij4Wudp1Ne4xff40sqNtqFJ1J8i-vkTQZFk8evAs2Zz4xIfUasD2f1zSHuL-jyl3tAh795298e0j80-_XiUEAE2N4l6o7B2-tG_a-jaf_u2GWjw1-xnRRCfLLe3osbLkQ22hn9QSbqerTc04-JR8P1EYT5Pd9RxhOGXbLizCPBG_bmx23xNakPyfvWx-jVqWp8sykGNU9g4uiL6RuN0zLiC54xpp0OiS7Fcsb0qWFSoXTg7qV-DEj-DvAY4O1pe0JQ_PopWo292uFPNf8Fi35yUQ==
```

### Screenshots

![ss](https://user-images.githubusercontent.com/2880033/230065412-23b21167-14a0-4c3a-84b8-f2c0ea564afd.png)

**Comment by QuickStick123** [comment] 2023-04-05 11:23
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5448 and fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5375

**Closed by QuickStick123** 2023-04-05 11:23 UTC
Labels: bug
