### ISSUE TITLE
Curse on hit effectiveness incorrectly adds to Curse effect mod globally.

### ISSUE THREAD

**Issue by Cursees** [PathOfBuildingCommunity/PathOfBuilding#3161] opened 2021-08-20 01:06 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Select Despair with blasphemy level 20 in the Calcs Tab. Now equip a curse on hit despair ring with increased effectiveness. The increased effect incorrectly shows up on the AURA's Curse effect mod. This is a bug, as the more powerful version of the curse should overwrite the mod completely. Also, the inc effect is local only to the ring's modifier not the aura and is being counted as an increased effect modifier globally like a helm enchant.

### What is the actual behaviour/value?

The curse on hit effectiveness is adding damage globally when it is clearly a local modifier to the ring's despair. Level 1 curse on hit + 32% effectiveness = level 13 despair. It should not be adding damage to the level 23 Aura.

### How to reproduce the issue

Select Despair with blasphemy level 20 in the Calcs Tab. Now equip a curse on hit despair ring with increased effectiveness. The aura shows the increased effect adding damage, which it should not.

### Build code

```shell
https://pastebin.com/F6bGJQje
```

### Screenshots

![curseonhit](https://user-images.githubusercontent.com/89230972/130162963-bde9aea6-3b6e-484f-84f4-593dcd459616.png)

**Comment by PersiaDark** [comment] 2021-11-21 17:34
Confirming that I am able to re-produce this with other on-hit curse rings, specifically Flammability. Self-cast flammability is benefiting from the "increased effect" of the on-hit ring, even if the on-hit flammability of the ring is turned off in the skills panel.

**Comment by Prodavec** [comment] 2022-01-28 15:49
Confirmed.

**Comment by rybufc** [comment] 2022-06-01 13:08
Confirmed, this bug is still in pob.

**Comment by QuickStick123** [comment] 2022-07-13 13:11
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/1774.

**Closed by QuickStick123** 2022-07-13 13:11 UTC
Labels: bug
