### ISSUE TITLE
Sleight of Hand notable and the surrounding One-Handed Damage passives don't increase Poison DPS

### ISSUE THREAD

**Issue by Teaf** [PathOfBuildingCommunity/PathOfBuilding#5921] opened 2023-04-04 19:27 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

Can't check yet as Path of Building is based on 3.21; however, in 3.20 the poison damage scales in-game with the Sleight of Hand notable and the two surrounding One-Handed Damage passive nodes. See screenshots examples.

### What is the value from the calculation in Path of Building?

"Poison DPS" and "Total Damage per Poison" does not increase when using Sleight of Hand and the surrounding One-Handed Damage passives with Viper Strike. It only increases attack speed and/or the Hit DPS (depending on the node chosen). See screenshots examples.

### How to reproduce the issue

Level up to 9 on a Shadow. Get the "Viper Strike" and "Chance to Poison Support" gems in The Twilight Strand. Allocate any skill points on the way to Sleight of Hand then test the damage stats on the character sheet with and without Sleight of Hand.

### Character build code

```shell
https://pobb.in/th71nDFjnY2S
```

### Screenshots

![1](https://user-images.githubusercontent.com/5672556/229898538-0054c2bf-c215-46f8-99ae-e5cc1fe35fe6.png)
![2](https://user-images.githubusercontent.com/5672556/229898541-27582690-428a-40a5-b6bf-45ab19d4403c.png)
![3](https://user-images.githubusercontent.com/5672556/229898545-f1b12bae-4223-45e6-bebf-e8678a92469c.png)
![4](https://user-images.githubusercontent.com/5672556/229898546-4f4a3e22-189b-4fcb-994d-f4d49b6002cb.png)
![5](https://user-images.githubusercontent.com/5672556/229898549-0e0ec2aa-21ca-49a1-bd43-42e3253fa62b.png)
![6](https://user-images.githubusercontent.com/5672556/229898552-022bc60c-6e05-478f-94e5-d34d253dc2f4.png)

**Comment by Lilylicious** [comment] 2023-04-04 19:29
This is caused by some issues with handling the calculations of the "one-handed" part of the mods. It's known and a fix is in progress.

**Closed** 2023-04-22 14:10 UTC
Labels: bug:calculation
