### ISSUE TITLE
Wrong folder name C:/ProgramData/Path of  Building  Community

### ISSUE THREAD

**Issue by feydreva** [PathOfBuildingCommunity/PathOfBuilding#1016] opened 2020-06-18 23:27 UTC
Hello, 

Trying to run PoB C with wine. Did work at install, but not after.
After troubleshooting : 

PoBC is looking for the folder C:/ProgramData/Path of  Building at start up 
But during install the folder is created C:/ProgramData/Path of  Building  Community

Renaming the folder to C:/ProgramData/Path of  Building makes PoBC works again.

Thank you.
Hope it helps somebody :) and maybe it can be solved here too

**Comment by ppoelzl** [comment] 2020-06-26 08:40
I cannot reproduce this. How did you install PoBC?

**Comment by feydreva** [comment] 2020-06-28 08:32
I installed using Q4Wine, creating a new prefix, and run pob installer into it.
At the end of the install it would open the pob windows without any issue, Only later it  not work.

I tries again into a new prefix, same issue.
on Q4wine, if I use the explorer to launch it, nothing happens
if I create a shortcut, same.
If I check the box for output terminal, I get this error message : 
``0024:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
Error: input file 'C:\ProgramData\Path of Building\Launch.lua' not found.
Appuyez sur une touche pour continuer... 
``

**Comment by ppoelzl** [comment] 2020-06-28 16:26
I've made some changes to the installer that should fix your issue, as well as any other open issues about it. We expect to be able to deploy them with the next update.

**Comment by ppoelzl** [comment] 2020-07-16 15:01
Fixed in 1.4.170.4.

**Closed by ppoelzl** 2020-07-16 15:01 UTC
Labels: bug
