### ISSUE TITLE
Imported Darkness Enthroned socked bonus effect does not work

### ISSUE THREAD

**Issue by Nathaniell1** [PathOfBuildingCommunity/PathOfBuilding#3761] opened 2021-11-13 12:56 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Expected behavior is that if you import character or copy and past Darkness Enthroned belt into the PoB, the bonus to socketed abyss jewels should be applied.

### What is the actual behaviour/value?

There is a difference between Text in Darkness Enthroned you can add as unique from the builder (increased Effect of Socketed Jewels) vs what is actually in the game (increased Effect of Socketed Abyss Jewels). Builder can't parse/work with the second one and shows it in red as inactive.

### How to reproduce the issue

Import characted with Darkness Enthroned and abyss jewels in it.
Check some value that is modified by the socketed jewel.
Add Darkness enthroned via builders search.
Equip it
Check that the checked value will be different (and higher if the modifier on the jewel was positive)

### Build code

```shell
https://pastebin.com/sUj2W8Sn
```

**Comment by learn2draw** [comment] 2021-11-15 13:21
duplicate of #3708

**Closed by learn2draw** 2021-11-15 13:21 UTC
Labels: bug
