### ISSUE TITLE
Skill Preview in the Skills list does not update when searching for specific nodes

### ISSUE THREAD

**Issue by FWidm** [PathOfBuildingCommunity/PathOfBuilding#1824] opened 2021-01-08 14:40 UTC
* **What happened?**
Searching for specific mine supports led to only displaying a specific gem's tooltip regardless of the hovered gem:

* **What were you trying to do?**
Looking at gems that have the `mine` text in their name
* **What steps will reproduce the bug?**
* add split arrow
* click into the next slot, type `mine`
* Displayed gem tooltip was always `Minefield` with the (probably) correct "selecting this gem" info

* **Does it reproduce every time?**
* yes
* **Provide a build code:**
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
https://pastebin.com/gmqJUL2j

* **Screenshots:**
![grafik](https://user-images.githubusercontent.com/3480240/104027351-8fedcc00-51c7-11eb-8267-a49f6d91c49e.png)

Thanks!

**Comment by Wires77** [comment] 2021-01-08 18:38
Duplicate of #1818

**Closed by Wires77** 2021-01-08 18:38 UTC
Labels: bug
