### ISSUE TITLE
Custom Mod visual bug

### ISSUE THREAD

**Issue by SabanPRanger** [PathOfBuildingCommunity/PathOfBuilding#1101] opened 2020-06-24 21:28 UTC
I am using the most up to date version (1.4.170.2) and after I added a custom mod to a belt (to simulate the new belt enchantments that have yet to be implemented), the custom mod from the item craft page stayed on place, the remove button beside it also works and if I click on it will send me back to crafting the belt and remove the custom mod. Removing the custom mod will get rid of the visual bug but as soon as I add it back the bug will happen again.
Here follows the PoB for the build as is and a screenshot of the issue:
https://pastebin.com/YnKDd7Mb
![image](https://user-images.githubusercontent.com/66331214/85629220-73c97980-b63f-11ea-9367-f9c950be90e5.png)

**Comment by Fish013** [comment] 2020-07-11 12:41
Duplicate of #1073, will be fixed with the next version.

**Closed** 2020-07-11 12:42 UTC
Labels: bug
