### ISSUE TITLE
Awakened Curse on Hit not recognized

### ISSUE THREAD

**Issue by Otep3210** [PathOfBuildingCommunity/PathOfBuilding#797] opened 2020-04-16 21:48 UTC
When Awakened Curse on Hit goes to level 5 which gives it the "Supported Skills can apply an additional Curse" PoB does not realize that the extra curse can be applied.

**Comment by LocalIdentity** [comment] 2020-07-10 19:24
duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/333

**Closed by LocalIdentity** 2020-07-10 19:24 UTC
Labels: bug
