### ISSUE TITLE
-528% unreserved Life although i reserve no life ingame (Mortal Conviction?)

### ISSUE THREAD

**Issue by Sykh** [PathOfBuildingCommunity/PathOfBuilding#3817] opened 2021-12-02 23:34 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

My reserved life is 0% because of Mortal Conviction on the Helmet

### What is the actual behaviour/value?

-528% life

### Build code

```shell
https://pastebin.com/PW1TZYDQ
```

**Comment by QuickStick123** [comment] 2021-12-04 15:40
Duplicate of #2360 / #1007
This is also a feature request because Mortal conviction is currently not supported so not a bug.

Also your herald of thunder was not in your essence worm (essence worm ring 1 but herald of thunder in ring 2) which made this reservation higher.

**Comment by Sykh** [comment] 2021-12-04 17:38
Ah sorry, i was looking for reserved bugs and didn't realize its really from Mortal Conviction so i never looked for it.

**Closed** 2022-01-04 16:28 UTC
Labels: bug, duplicate
