### ISSUE TITLE
Feature Request: Layout options for Portrait monitors

### ISSUE THREAD

**Issue by cbftw** [PathOfBuildingCommunity/PathOfBuilding#2262] opened 2021-02-24 17:53 UTC
As a user, I would like to have a more efficient use of display real estate when the display is in portrait mode. The current version is built solely for landscape view and does operate well in a portrait mode. The Configuration screen has inaccessible options while there is a lot of empty space available under the presented field.

The main tree page also would work better with the left panels under the tree while in portrait.

**Comment by Wires77** [comment] 2021-04-07 03:53
Can you post a screenshot of what you _can_ see with it on a portrait monitor?  I don't know if this will be possible with how the UI is designed, but having a visual for those of us with horizontal monitors would help.

I'm going to close this issue as a duplicate of #644, so feel free to post the screenshot over there

**Closed by Wires77** 2021-04-07 03:53 UTC
