### ISSUE TITLE
Import Custom item gives a LUA script error onMouseOver of the Create button`

### ISSUE THREAD

**Issue by jwusch** [PathOfBuildingCommunity/PathOfBuilding#7175] opened 2023-12-27 21:55 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

DOing the copy and paste of this item from POE, gives a LUA type conversion error on this screen.
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/5559521/bb55c973-818e-4536-a937-6de3f5100991)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/5559521/176f046f-061b-413c-be16-8ca277694a16)

### What are your system specifications and configuration?

Windows 10, 4090.

### How to reproduce the issue

Paste this text from POE into the "Create Custom Item" dialog box

Item Class: Rings
Rarity: Rare
Kraken Twirl
Unset Ring
--------
Requirements:
Level: 67
--------
Sockets: R 
--------
Item Level: 84
--------
{ Implicit Modifier }
Has 1 Socket (implicit)
--------
{ Prefix Modifier "Vaporous" (Tier: 1) — Defences, Evasion }
+163(151-170) to Evasion Rating
{ Suffix Modifier "of Cinders" (Tier: 2) — Damage, Elemental, Fire }
14(13-17)% increased Fire Damage
{ Suffix Modifier "of the Lizard" (Tier: 6) — Life }
Regenerate 7.5(2.1-8) Life per second
{ Suffix Modifier "of Light" (Tier: 2) — Attack }
15(12-15)% increased Global Accuracy Rating
10% increased Light Radius

**Comment by Paliak** [comment] 2023-12-29 21:52
This seems to be caused by precision mod parsing logic
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/9d56a02f42792fb7a069c27a4e190f230665a3d9/src/Modules/ItemTools.lua#L96-L103

Turning the line `Regenerate 7.5(2.1-8) Life per second` into `Regenerate 7.55.1 Life per second` which is parsed into a mod with  the value of `"7.55.1"` making this line:

https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/9d56a02f42792fb7a069c27a4e190f230665a3d9/src/Classes/ModDB.lua#L111

cause the crash.

**Comment by Wires77** [comment] 2023-12-29 23:52
The real issue is that PoB doesn't support advanced copy/paste (Ctrl+Alt+C).  Use normal item copy for now (Ctrl+C).  Duplicate of #2684

**Closed by Wires77** 2023-12-29 23:52 UTC
Labels: bug, crash
