### ISSUE TITLE
Trade for these items does not support abyssal sockets on belt (possibly on other equipment too?)

### ISSUE THREAD

**Issue by stoyicker** [PathOfBuildingCommunity/PathOfBuilding#5419] opened 2022-12-20 21:52 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour ingame?

You can buy abyssal jewels on PoE trade.

### What is the behaviour in Path of Building?

The "Trade for these items" functionality does not have a row for abyssal jewels if they fit on the belt (precise case being using an Stygian Vise).

### How to reproduce the issue

1. Create build.
2. Add a stygian vise.
3. Use "trade for these items".
4. Observe how there is no row for "Abyssal 1".

### Character build code

```shell
eNrtPflz2sjSPz_-ChVV-9VuBTu6j3zJewU2PhI7dsDOsb-khBhAsdBgHXacrf3fX_eMJCQsCWHY7JG39Z4DUnfP9DE93T0HL__zde4JdyQIXeq_akv7YlsgvkPHrj991b6-Otoz2__5d-vlpR3NLia92PXwzb9b_3rJPgseuSPeq7ZptoXIDqYkep-SUj4DqYXtRzNC_XP7Cw2O6fhV-2pGeoHrkzdApi2MbH_sRq_ab6lP2oLj2WH41p6TV-2hA0Tagh06xB8fLJ932QOg2hbmtusPqXNDouOAxgvoRFu4c8n9OR0D4On55cXgKtcD10968Cmexl4bWPjXy0vPfiDBMLIjIYQ_QB4kYU_JiQv072wvBkKWJlrmvirKmijLitZ-Xo45XBAyzpCkfc2QVNnkf_UqpMuA9CcT4kTuHTkI3OhgZvsOyagY-r5ShfoE8PPYi9yF55IgQ1H21UqOTh41IIliFfAVjWzv8HKYwZqWrqvyvmiKhqIpej0eXYq7soUPbjTreSDkJ7SCuKdT343IE5EvqRtSfwv-8qiVLB7EngfDohksnY9gGD1FGgeUemN67y8b2ZcVqQr63PbtAxouNSRJeh3sJQlgiEYFFHENwpA4FIZ5oRVT3k_HD_xt0GI5ncqmz9wJaQ65EVcJwqa9eRof_WFTuI0JP61DA3CgzSCHUZCzqkpHNCC3RchKazgkXzMwWbJqCOYhJa2y6VN_yYZS7f2AYB6yhuAhuaMRm9rWCYd5jv7J5ZKqLoGH103FMlRZq_T0l7OH0HVs79z-6s7jOXjxK_uGLBtUler56MydziIfXFAVsgQNV0r_yA1IJaKoqtWTE_ijSkRVl6ud4MymYSWjhmzWDbecpahizbTuvEDoU99ZTrRyHd1rPyAhCe5y4UBdC4gygOGFkcfII41xls0kw7TJNM0bmxI_afFhKS25OnhArDNCnNkxhFwDOyLNHHte-UatgBE6L-BqcIQsEXBdC0WUDYSFiOXC0uT92jlwQ2H1fRJMH4Yzl3g5lgyzCXzatwN70QSViTuPnxe7JDdrsUwkjZjbUC4f7CCvYlmqm3I27BYPzBBnOaw1c9-Q5VqMtyQaFJD2dF3ZN6uxACEbdEskVZL3LUWpw8qsb4kFKci-Cf_VYD1SVAMF3dlhfkZStXrj4eB5u5HVysFAIGIHjDFZSSXE6pSIfsGEyNsMrRvMaRw0CDmQBQ7cjIN0Oj2058zIxrHTbP7ueZCbrnS_Nn30vDKU6jHZjSLbuTmk42ljKbFWNscYxosF-E9Ue1M8jAUGJHRzYaCurAe-gMGb92RiXciwQt_Q1gOv0q8OJbNQaLUVsSFGc1YwiFlppbpfOejGLWQ1hnNwjnOY_Vix4pzm6xV6pVc5gqw0n2VKimxZsrZvSLqim1ItWjHxhfjVEPc1XbU0NQ3OE-rDG9fzhBD_XtoBGh7LOIQjGsw7QhfeLR1D2BZCGL8OUGyncbpDBGDKDtbkwlWtPaZ4FBDyDZQpXMZemIvKDEuywHfLlqlKurwx2QMgu0CyR0E-RbJ0wzL3RcuyoMNZJtScbP-BCHQifHD9KF_dsXQZRKCKlmxK1uZUEVI4pFfCOiU-9pr0HmxzhhXBcNmdJtAQza9HAOX43x5W6YuNwBs10PfHcYCernEbqxhlzVy5c5gPw_DQjmzhC7kn3tXDgpyOEUIIwXqd2RmM61ftuR1AKhPNPvsQc0BS8Nkejz9PPDu8-exw8h1BEjsC_C8gtzG4TxjKjCAviDKSEqSKebJHtueNYMaoIG-7HrqGz4Q5C6C9rykKa0JslSMAvzlo3TTroIFxJG97n8dsJu0I4EFUtQ5l6tERwDuBGyHbIFvgel8za3tF_dCzY_DEAGvsW6JRB7zIfEquV7pWhxKi6-wI6r5qJKRx3KDQj1wPBt-rdhTEWMum_m1MAhosVYxG8PI5q5vjp9P5ggYRe3hge07ITOTUX8SR4LNa99wNnc-jeDLBijaOyYAV5ftHR_2Dq9P3_cSq8ihsOH_24_kI3QD_F4ZsAjkkLHYRwngU8o-v2u9dcs9cwSGJwARC7Lnn2YuQQJ8nNvN9LnxkMEPQohPVUGNQkInzaKmK1hKgmlL_Kwki4BdyADAAUtmv7P2aTvEGMTnAUVhFDSvR1YR4xHVghxHPXyokxVYCqqlgKb6SHXxZgws2Y3uVLSdv10giAoMEK3bcieugA6tXOZovh6qRi-OAL3AeavSdxI3VNFhpv4oAf1mNzMvzVdjJ2xqpsqWBSqnyt9Xoh8SxK3nnL6uRs5SY-mzVqZxKBlVD6S31mZHDoOlyX16p2b5HMpBqghfRjAQ8dqykdA4-KgWpHTiBO4qj6mGcg6iRFavaVUgI31Wj8npUBQ_4rsYTFaozFQLNw1ST4gWNSkdWhzqo8aeDelea5sYVkudva_hP6wMVrCeva7rOspVK1SepT51rgPm12jXgy2pkPrS2IsHGwSGZEPBgtQMhg6nxwFHsH4KzjGok2pAUn9G6d9Qd85x8K2qMyd0S4x5mR4JjVYtthb9SzNiJApJFhwrvnwNZQwjc9klNYNCMUpbpnxDbw2Vr6m1H8NHiylZ80ii0_TGrujZm9OXzNDp-yQKSEMLtIDom87D3AHnpEbrcleVwm4kgiVgjjH-LOGmMPiYTO_bw-bvY9tzoAfJ7Mf_4jO9u8WkwzxbUgNaM3qMVcZIYIIXgRs_O-JuuFyXUsL2UNS6TpEeMT4k9Sx6yzSzdZbcZy6zjru948Zic-knansnKs0fYt6E7dT3M_VkSLfwMsdpkIujRLMlKfsH9PJi9jFOuQ49ibZ3YC1CP1F5tOuvZv14CAwnyMUvF5IwEAp67Pmh1pbu5N8nDYTyfU9DMqUOOKSSB7XTPkCy2C9SlAnVMmQ7cwPHIxYSx9rhV1uAtl_UpC7WY3tr5ogZATMkc355DfjOGxPv5aQR6eY7Kec7IwCcmxKyd29QYxMeySykvOXZo7POGMAXD-vKqUgo9LxHIc24IvDdPNArevdQmmA2wobB73TfWXlpBSwpoO1FUOc18b8bLBPyxXlaLeqV6uYRUJbLDVC-7EEXiLXpA3pnBs3Jp1PGfuZvHNBpzv0TdHWf9BxifadlxU6YSpZbRaMzUSuXzO2u0Gzi2T4ZxMCVb6LSMSmMBcGSBY--cQSx2XPiFSOfJbFbTaswskhDuZ8QXOBkhF3Js6UGL02qF5-xRiiHaTqfMxip5S-7BkkMyiP31k2EXi5G-HZFmjrVAe1OtMExhtVvQh1FIvRhjvysyX3h28Doe_xFGeuo7AYEujJeZ1ZONtJpWY3FkJISMxnczUJDUHQn_2Il96LsLEoTndnCzo2l9ubYHocmND9nZ5lLnvfo_iGzC_w8F1rn_ecO_v7Gd2BFb3dqJna0QayzoBG_n9nQO_7e9A-rfuU6132rOZmZcfeb8vR6uNrKDFhuHVZyAkFH4G0yxjaU_wJ0ahMYhbjx5cthaTqWxhDN0geH_k-R75AGXh3Y421XW94he84wPUQWGu_M0u1LA4wchrbk_ErPcVMyS9Q-clHZhXZDwRK7TgxArmj158JYSac7jyi6e75V1njok2eW0ZlypjYTwiFzzEHe53-o7Z9zHqDISJGfZSGFX2JPNvgHRxqJJaAkpscLGtd1HpNQbXxKfRFsnPlWUmg8KICDkKTRlVmlabBmPXSRse6wuXzA9ZCmt9e8ohnrUXLlAkkm3NIiaL2rqvwNiQ8Ly_Sb-E-LNSfTHFC-ktSEBDUbueEz8Adtp8ceV8lcaqqnll4YLKbbwqJ9bODdJa5oPcInwo8RPKOZktltGqPFA5shCbh_TdrYhreceBTu8IR6JKK4M7ri49Yj-xrUFRkAo7yHuv3BDMk7fNjYL7S8W4P3lig7pfmTk5IWkvzijEK0JuJUs6gjH8CWt9pzQwF-z1iUM73Gr_EbOL-nPDkq33ID6YYh7CoYLl28BbOwFN1QR_oVJ2BPKWlr6sUJ3_lcs-4On320MsTibrJP_JasqPTk1WkFvvgrA8X5oO9rNujnklPhyd4vmQDDdv7j5kjkgC_mdjd9xsMhbD5aG4u5RL3pL7-wnD5pyKo2l_B7ME28k-M7JNDIysMH7P2yzYvaYSPM6AuAKCfLuHQe_TmUYBe7NNsvz5XSaOwyOLiT4j8ZQ8hGyV7bbjW9yw49XASHpXjZGSUq2kcGX_M1Ip2w3GQySEKLih2Q39qv2b5KsiUpHkRRF-r3zmyYrYkc2NdOCL5JpaGJHsyxRh2-yIVlKRzV0VUZARTU7iqiJ-EW2LHglS4YiIpouyfDNMg38IkMDHV1VTCQva5KpA0VRV38H7ukYN8UZigmk8Khcx1JkoyMrsqR1ZBEIwGcRnii6rqgdSdYlpaMrlqF3VF0zzI4KjUgd3p6iSoYEb1XVgLemKgOWqskd1ZI1taNoBv5VNNHsABkLKBjQmY5mirLVUU1TNju6pEoWUENIzpEkg2jgFbShipbYkUyQBbQEXYOeSRKAGRI0Aa0pHUsyO5psWkBfNsSOjm8URVWAew1a7-iypMv4GTqlQ_d16KClWsgcsmIoAA-ylUR8a0JnDRUVo6F6AEuHJpn0VFkEDi3D6HD9SKIKnZKhTeiJohsdXQRhdlRNkYyOoapqRzNUUJwlGdhB0FjHUlEMmix1VAnkgHIEWKZ7VTZ00LluyDLYgQJPEg1Cv1EF2BvD0lkngZ4sWZrJuid3JEuCxrDzOjJuWIxxIKYCn6ATkBuIygBGdFlU8TF0VlMsDf7iOUH4bCIPlqYAMdmS9Y6syqAedkgNVGApwD3QRZmZoBTF0IFzbIR1wVBZL3U0CKCsmhrvDbCgScAf_IX-qaoEwtXBArH3aAIgF9CUqYPqNBNYBr5lEI0iGvBZM2XQqy6imNDywBQUUQQlq9AcHxKSYYCSNWgI6Cooex0lCQ904MBUQfdstIAsAF2RNAv1IFpMPjq4hwiGcO5GNPQYTjpkxWQD6PXgjHu-WRQtwhfPn9_f3-8vINOhE_LV9ci-Q-fPF4AEfmCP-bg9JPu8C__1pt2e8_WbM9f7NyPp9u56Ev1qqqZ9fv1R088-Piz2rvf21PcgWCLvUe3m_tg-0I5_vY5fX7rBSDeNvajn-NeL3tn59MOV82bo6kfn05uTce_Aen1_8eHojTf3Z1SdLu4exEXv_RfRVsXLYHgzi98E8mu3f2xeOdc3e28uF5-CWf9S39O_9gbi9dH8c_c4FD-8Pu--lu3T7kK_vh7dOqfKr6_jW9can791JsdHH4-HoXvw1fowj94N96a9qSl9uht-Hdu3ohv0Joev9z7evjfuvwHtu713_V_P9csHZ2h9Cd9ePLjh_OIbPTievBksnNnoi6Qekre3xqE7ur46GxzYi9uL6_cn8uSbspjNPshfFncXX69ulPi9MQrjw8P7rt_tdfv97rtP3YNutz99N-z2aP942nW7B7T7etq97vXedY-7N2e33wzj_cVr6Q2x1U_zs9vuzc3eSBevR3eRdSZJ-qdvhx_jGbT30ZkfXbx7xd17qtWX_ERmmExu_Bvzj2gD6GogSIr4NJTeWPQYDod1Dk6ugmPuNAeoVgEy95YDVKoAmWteAqZ3cDwGRNeRI1gJx4ZNDlCrBERnnmu5kmnmeXKAlbwkR2KzpsUqQBzlOYLVcDiv5ADV5ey-1Dp8gQmbze04o-OHtzQi7B0-TL-w-R6PYyZndiFewPj4G6XzT6_a4Of2RVOyTPBRsmryveYnxI7O7UUWVCNssmfdSPapR3Z06EJIELDTDGmcgoAfX7XBr-3r4AUMU9TU5DaSlywGSuKOfFk9Dgk_lM-Dc_Y4t7mdhXK5je08qnshXL89fXfdb13NiND1fXfmejae6xTYdQmtdzEkMuAgccdyi5Fg_X8hmEYr2Ub_QpDFViLPF8JgbyD09np78G-LgQ7I7QtB1Vqn84XnOi7CSK1nkvmTwM8cChEV2AkfgR_fTNO2e-gJ_MW8BrtjC2zXdEsXfxICvOWDjIV-emZZ4GeUkFzYOiTw4CpgazspLTea5aB5CMcM4ZyOB7YPIAH-xav21HYipcRUKiHktRDpuXIWthaVIJcqATrm427ZCJRxRh9srzV058jHALLNovjlcvEfc9HD3-O8xDMIwbF9n0bCiAhzOnYnLhmDMlAHjDA2ziFBvBhmtyQRBO5mO-Z4SC-kp2_-QAkpRQkNuoN-62LkuXes9k090hrEvusIQ3tkY823hQf0wNJEjX3qQXeTu6TAjkAC-xAlGq0hDF00p_5XHMICttbqs_VA3KRMA28c8ocFYWtLYSsFWz9GW8_ZuW7lpS632MFYbO-BxiDFCbyJhDEYaJiapvaTMGGJAahB_QkVgdtNcgbdemaI-BiZaplmXhnskZpRQKSI8sU9xg6-fqYajCpb_ctRlaw8JTz2Jtj-OBmJ6TVNrd-cwJ6ALfwuy3nw9J4Svgbx3QZSDYS6FkJbC6GvhTDWQpjVBq2WGHQvcOegM58I792QBolJHwT03k_tWa20Z8iddmvPPeY4CvZsFu1Z0gpWg-f1EkNudcfQlIympuhCdtdOaubwmEGHYJAafjv1I_jqTgk3cSkzcVV-bOJmrYmrahNT_tGMtMwEtRITPJ7RGOZLGjuzxPyO7diPPLCI1ARlq8IETcjxdmuCxxA-gFutcamniRdlDq3_dUHDGPwlmMOJG3UEe7HwHrA3e5JU7vfAgp0s8Lj2fbx1UOj7ZO6SUJjQQFAhvsMwKkyItp4pJsIekq_AFPQYzFXNzNUyHplr6nKXgyDX_j_LDMuMTC8NbS68gEazdEEQBEK9OwhpApDxEV6cU7QOJRfd6Pk4UizGkdwdgOJQ8KgvCIJbZ-AqQkETeDQctg4gOojnAKSZws92PMWZi4x_QfPURSG5DyhFPogDCMUj70GY2aGQvW6pBT2nSAuwcsRizY8pPMHgCret3QjjmA8LVu9rGRBG4V5d3tPiuz9zVjJKtQWJSxCNaAxu9IzSReucggzZPDWAfq-O5KV-5BX9PJPZSJnzo7kCv4YhWa1IVSz8nN7hx9w2u0AtnTbOeYwahL-8EJ7JIMKc_lrs_kQCkwERJHEfJ50JYRrh47elFEIcvEVCyFBw_sBLYlq8mB-CtsENFKe3tNdIdwWuEBN34V80pkSbqiwKGUfp9IdrUGhiyd6NQ9zXCIYZBPEi2j6C-htMPea2dmbotXYmfh870x5bmfgXt7J_vm1ZJWHNYRzewOQP0_Ewepi6to8RdjGHNsxl3NEt2tMJ-H5J6I4ewhDrBQwKEjSt2sieSUr-JdOm3CgwxUwsrWiwqTCbXWBmGS9TMKkQGKc_EpDR4Yb2zw8vJLHUk_SCOCkERYHt-lErvcxPeI337hWnLL01sMduDKo-Q0m3zty5ixWPiKLyC3WTQwIzOrzC26ldh51llkxRgST-BrRkg0ZYtcbm3-Btz_ZGtme3LvmKQIgQAWtNsCFQPeD3zgHF0QPDPE9usWuduBjLuM6fWpeSpJKx1A3QvYzH4FJ6nhuGLSY14cCLWU5WImAl56s1NS9RZWnQLGM0hURQaVVuWXIQAADkVHzPhMhaTIZlWCCI42xu43WkRawpyCAC5a6MIcgNlulrFa7thTQl8EwprdFIZX0V3BAGPQ3mgTsmQTXMB3gdLqBP0Bk0X36D8Y8wlOUSYzuhPo0DdKs-zIcEBs68xtI0pTI7WLU0vdLSKjVjFyxtE0PT83bGvTqfuLMzx40tTq5OJis7fggQ8BFfkWDC7_ephj6ChAnDrR_A4mqryty5rbU5_Z9vc0p57eR_5rahuWnla20UNBJGkP9BpBCVz5-FIARXy9IQMd3GvlRqmjTgusLKDJdMboVVg4xAst7Ga_jFZCODYbspOYRSCrCyFLCzlPa7ardUd-rTdKfKK7rTm-tOLNGdtV53xjrVaT-Y6vQSL587nNBaPZtQUKCkVK1s94TC2kgxZSwOvMLSyFXgTqckCJM1VsjcV08A8A3L_dvYXSxwMBZc-Uqaz1daWCpqPXqnVsW3zyRWxE6vAsZs8QfxweUVzg8zwpe7MQdjUXpou15rQCPM9gasJJWk9vysOEzuumolXx4thbSSa1Zh_Cu6lX57DFaIXcvtjO2eyOdPRTvTC05idb2WCeYFyOX3Z4r4syzuqeIvTO-s28X3eu590uHULHJwqvizwsDyzXJhovj4bpQJymt1r0Dq5BDsIA5CXmR_oHGhG5r5sybuGdovP_KaibRSHj3vHp8etLojArMGPLL91Fv13HAegx_j4V1ivhf3XuXiGlhWzmUZRVvKgstr1BfzQWntCXTozIRJ7HnJeorRAb-VXz55tLwiadghtfGSiqItZ8ZsQpQLcxX_-YKWLuU2_fCQdtWm_kJLKlJZPZI7eoEVvFvv4fMYa5KPwwfDKoYPhZngKrAXwtUsoPdsw3pJ4FYe9j9LFkNZ2QJLkGXDLMzA2LxRDfZXDBRK91iJZTsuyIzMKW4H46frWge4BYOWqcJcKQU-Q1GDeDB5Kt969kjOKxlU2CoLz_n2tKt7KpwADq4isw18f_IGtbJC4LH3sJhBxLQg1fGvYRal9tsE4o0oDjDnLRozRawsPElSTrYqk_P9SvnQx2sy09nkTxVTWQnrLJ67Pt4cdOwBG8SvG-_myvQu5_hlu8dy0yhnt-Ag83lAsmXyEFy_8CHZN7mVYP82A12pdrhDCI4hFq9VgbiSsalVY3R4TwOY8Yp2jD8JwkJwfoAo3dbKEJgjSEo_T3Af5f73L66Msn1u5zbxwiigc-E9Ab_r1XhdY1UbSom9F_YIz2i2RThdi9veUf-pTkWv3KJ9iTPEnPpuHLZe22MidOcxZPMQ49nTGDKMHovb8iGfWtw-tawnepA62BHB6t2d6xOBXf6Jsmr9FtnT8AX7vSoPsorPdvrjH7_nA3fMHhSePSy3Rq2iZj8rlUdNMKtS1VUaQaaWYvuKxtOSkkold2O4q-uB7emSktV6HuPipq6e57JNALxsme7_SnZ8VXORGF56jQ6g4G6BleYFe2q7fhitkv97JDJPXYrHi_OrzyAU79T3aMROZVyOrgdneIqC_zxWegYfTxWvrL4LuTMp6XmPtXRWachPoJE7j7IOhV3dt4t-l_G_Sd97BEKzLfB5FqGUYSS_Xwfgq6dsOCpfvMgdvElJN2NdLmNd2YHqn6AGuRGNEoEkR6jyAsmdqloVSJlE2fmmgkCzE08bynOVB3UHstR3IMun0CizDWmTYVE2PjcxLn5F11ZdKBmZ-tY92GRsp5cCpwja05pUduTWpK2ZV3dgjdIORoW6oRkswa1mOtuqwTLT34XkNp9WtG27ve1MqGzUgeyy2G1splyB29u-tjWFzZ3PEkGtm8OSw7z5SSx3vnftLMbPt6bnYfP2k5OaXtcBfiY73_7ylHaDOTg53lyYxJcnnhvOwuV613ZjgPK2A0nfgddTduBDmgaa_DR-QSPZ-fwGGk0O3xcscnkev4lJ8EP5hQ4sz-k3NIkyj6TuKBiSGwoyuTQgz0juHoEtGJF2Y9nKxpNKMwlWO5X8XQvmUzjfVZr3lPG0I-vRt_UnUkPzSy6EyJtf7o6IpuZXbT67Gk5Pio_4jWiZMRmNHesKor6NFW2iSjxpk7chs051_BaRvOaW94psNSfKu_Ecu5jSnujEcveMPE0EyqZKy3XU2MZa1N3IXts6IN7YAy3hlW0G-iY95wX3nLIL2zrSW-LYthj8dED9iTvlRVJ_EUcJFayRstvL2S-Hs5-AGVHqEdtPZqfn1Si44DQgDttSsR6NYBH8NOxR_NGmMMJNEq_al67v245X28w1_q4Mmx3XN7Kw_WhGqH9uf6HBMR0vW7qakR58Im-yH6kpII5sbG0J_pb6lUwM3W_kMiAhycHzzdp1bLBFgOSc93gDKTO8pIDP10fBAuL5iARgbGJTzPUNxiFhv0Ka7IpZjxDmfgx1GNkMJ-2Yur5f1Bunp-Y3lcZwhsNlvIE5uP6KOXyKp3FyB-3LS892CC7ekaCgZn4resqSIYr18OkWSL40s0SUFXkNJlsTT37e_LFuK5CyNdkntAcDl68OL7G0hq1d4l24DZFwVXOVLW1d3-DJEzjiP0rRnB3-Sw0ptKmuF9hqp5QmSl1F0swGjGwqMhTz5iJDrI1EllpARfdePk-nmJfPL-1odjHpxS5bEP9367_yobei
```

**Comment by QuickStick123** [comment] 2022-12-21 02:27
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5354
You can just search a regular jewel socket w/ abyss filter in the mean time.

**Closed by QuickStick123** 2022-12-21 02:27 UTC
Labels: bug:behaviour
