### ISSUE TITLE
Importing custom items no longer works-Version 2.26.2

### ISSUE THREAD

**Issue by stoudtlr** [PathOfBuildingCommunity/PathOfBuilding#5890] opened 2023-04-03 13:08 UTC
when copying an item and pasting into pob the values do not match.
Pasted item:
![paste](https://user-images.githubusercontent.com/36058236/229518729-389bf73b-0dad-42c0-8b92-5b88d1bd6a88.png)
results after import:
![result](https://user-images.githubusercontent.com/36058236/229518827-7231cfa8-0811-4eed-9829-dba74af352cd.png)

**Comment by QuickStick123** [comment] 2023-04-03 13:09
We haven't ever supported advanced item copy. Use regular ctrl + c and it will parse correctly.
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2684

**Comment by Wires77** [comment] 2023-04-03 13:09
You copied the item with Ctrl+alt+C, which PoB doesn't support.  Copy it with Ctrl+C instead

**Closed by QuickStick123** 2023-04-03 13:09 UTC
Labels: duplicate

**Comment by stoudtlr** [comment] 2023-04-03 13:12
ah. thanks! got used to alt+c for craft of exile and didn't realize it didn't work for pob.
