### ISSUE TITLE
Can run POB once after install and after don't work on the second launch

### ISSUE THREAD

**Issue by RiNkzI** [PathOfBuildingCommunity/PathOfBuilding#4344] opened 2022-05-02 18:28 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Since I installed the last version of windows 10, I have this problem with POB...
When I install the software it started fine for the first time but then it stopped working.
However, I have the same hardware configuration, the only thing that has changed is the version of windows.

### What is the actual behaviour/value?

Since

### Build code

```shell
.
```

### Screenshots

![pob prob](https://user-images.githubusercontent.com/104785923/166295574-cd5f6e5b-b702-454f-8567-02ea7e6620ff.jpg)
![pob prob 2](https://user-images.githubusercontent.com/104785923/166295582-58a09673-c745-4c46-9817-b464c6218da8.jpg)

**Comment by Lilylicious** [comment] 2022-05-02 18:35
Duplicate of #4340

**Closed by Lilylicious** 2022-05-02 18:35 UTC
Labels: bug
