### ISSUE TITLE
Incorrect calculation of skill points for a level

### ISSUE THREAD

**Issue by XaksFlaX** [PathOfBuildingCommunity/PathOfBuilding#2998] opened 2021-07-24 18:15 UTC
* **Incorrect calculation of skill points for a level.**
* **At level 65 with Alira of 86 skill points, PoB shows that 86 points is level 64.**

* **Provide a build code: https://pastebin.com/Z55bjNPq **

* **Screenshots:**
* poeplanner: http://dl4.joxi.net/drive/2021/07/24/0006/0345/434521/21/7bcd0b59b0.png
* Pobc: http://dl3.joxi.net/drive/2021/07/24/0006/0345/434521/21/60cea870f5.png

**Comment by ppoelzl** [comment] 2021-07-24 18:16
Duplicate of #2968
Please check for duplicate issues first before opening an new one. Thank you,

**Closed by ppoelzl** 2021-07-24 18:16 UTC
Labels: bug
