### ISSUE TITLE
Error 403 

### ISSUE THREAD

**Issue by BMXManiac100** [PathOfBuildingCommunity/PathOfBuilding#8154] opened 2024-08-11 11:04 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

it should allow me to import a character from my account list 

### How does Path of Building behave?

when I try import through my account list for my own characters i just get an error 403 that has just started happening and i don't know what the issue is or the fix

### Screenshots

![image](https://github.com/user-attachments/assets/dc821cd7-41d7-453f-9a16-d7bdf32c9e38)

**Comment by zao** [comment] 2024-08-11 11:06
Duplicate of #8152.

**Closed by zao** 2024-08-11 11:06 UTC
Labels: bug
