### ISSUE TITLE
Gloriuos Vanity Timeless Jewels display wrong curse effect values

### ISSUE THREAD

**Issue by marc0sap3** [PathOfBuildingCommunity/PathOfBuilding#5634] opened 2023-01-27 10:07 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [ ] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation ingame?

Ingame "Incresed effect of your curses" are way below the calculations of the PoB, I tried with 2 jewels, both of them with totally different number, maybe the change of the timeless jewels wasn't mentioned on the Curse manifesto.

### What is the value from the calculation in Path of Building?

Glorius Vanity Jewels
Socket above Eternal Youth keystone
#218 Ahuana (DEX and INT nodes)
PoB:
10% Incresed effect of your curses (DEX node)
7% Incresed effect of your curses (INT node)
Ingame:
6% Incresed effect of your curses (DEX node)
6% Incresed effect of your curses (INT node)
I've tried with another one with the same number, but from Xibaqua, same values
#7981 Doryani(DEX and INT nodes)
PoB:
8% Incresed effect of your curses (DEX node)
10% Incresed effect of your curses (INT node)
Ingame:
6% Incresed effect of your curses (DEX node)
4% Incresed effect of your curses (INT node)

### Character build code

```shell
eNrtPdty2ziyz6uvYLlqz8s4Ce4gc5I9Jd89GyeOncvMvEyBIGhxQpEKScVxtvbfT4OkJFIWZUp2ZpLsTqo8kthoAI2-owE--7_P49j5ZLI8SpPnO_gx2nFMotMgSq6e77x9c_TI3fm_fwyenati9Crcm0axffKPwd-elZ-d2Hwy8fMdj-04hcquTPFuhor-DqgmKilGJk3O1B9pdpwGz3deponZcXyVBFEx-6Zjlecv1dg833kfFXq046hcmyTYX_z-SutpXER5seOMVZRcpvqDKY6zdDqBnnacT5G5PksDADw9O3918abRc5Q0e4aR_-3ZeaxuTHZZqMLJ4c_znSEQQF2ZkwjQf1LxFPCgnSdrYfemWV4cqDF8vLvN5cSY4G6w88wchqHRRfTJ7GdRsT9Sie6BflPYM0vKSRyZbA6PH_OuFie3kGPUif5NWqj44Pzy7oFUkGkPigNPjPZioGAvvBb69CqJCtMb_DyN8jTZaNS9gPencQzS0g82HftR0nOO-2kaB-l1MoekjxklXdBnKlH7ab6gNMHrQM9NBsJXtFqgOxpcGp2CvDabiMcYu66L6789elyNp7PrF1Fo-kNuNKu6waaj2W4eh5d94TZGvN2ALkCn9YO8LBoaRHau8YX52IJknQgPzOcFmPDWIGxBMtEFeZospkH5uhE2ITH3ukf4KS3AwPVUFYcn53NIjyP6GGHMsZSUderb89FNHmkVn6nP0Xg6BvX7Rn0wiw65RG43F16NigR0TldjwjiRXa2Posxs1XAf1NF2DUcqzbtaRkm4TtoWq7XG7OqnFvQ00Y21XYf0bZKZ3GSfGuYar4O_ALmyDoEfm34NFh3UwtnHqlY9XZmk7u6mnz56YYweHYO7dKEK00-XL5iVsbVktcBNsrrrsK6iKu_X4BaVHnPX9VyKOHKZXItkNcWweLy21YZEO0xMdnVzOYpMvJgcEaRXg9ng9tWkV9uS8k0EzRXo1r_tLlcRhbHHrE_rDYnzXmVBP3uzIXcfflJ5Uwm77h00q-Cb5OoWAwO-JjQITF-f-jxL_7Bee7xZs2E2TqcLs0iRS9dOooJv6TJxlxGpIpQLE0x1y2qxTm9xL4bYatnhX6di43izJsOiUPrDQRpc9aZU2cvmLS6nkwnoEbvyfdtZE3hh8qjh_XQrmQXwK2DbphBTd52p7N3BAvhWB_hOF6B3L0st-ndVWu-lbh5x1AN8uY9uQZ_Fw2egGcZgCMpQGkL9hkFYs0AQgPUKqErAnlHdeXoNgx_ZbEe-GTQ4Oguqdg4lM8mXm974W-C9OjhMgmlmpaF3H8stVnXzJhqD3szzA1UoJzcq06MXsNDPd3Ya345UHPsg_PCrbfXsSZlEsp9Ox5M0K5xY5cVQ63SaFCcqH1lBYoj50oRE-r7rKj_wQ3CgXV9Q3yc-ZtJ1A6HQTtn0wqh4DDTfr77a4SpdmKzCZZikAVdUMRT6KBA8YMxQF2FEtO9xFvgcEb82o8_2VazzcmqnyWRaOEmZhxpHuf7dn4ahzTbB1IqsTJQdHh0d7r85fXdYU6PZJP8QxfHvyXTs23xL9X_w4mvIS1MqZief-nn18fnOu8hcX9pWB6ZQUQwrpNM4VpPcBM93QhXn0HMEH0uYSyC7LtZgK6HAuZ4lq1bjWgB0Yzr8bLIC5gtmXWeR6RzX_Pkdg6o6tCbfck8XNpsj6kZUWZN9u_ilS9JBqTIB143FZsU6p2MfrmkLrKvizp7rp3dQoriZmBxsfBRG2gre-iV_A9AV1Bq6aA0yq2_WrHdtE7txlEm3LgTVw-7GVVKtq3X9dA1VyxReJ1Wrp93ND4xWnXOvHnY3nnu5aVKmhFdjmUOtwfQyTUomB6EZRrG1X50rexibOUg3wlfFyGSVUezEdAY6agayVnCyyJ8W3WLcgFhDqzIS76CQfdbdtIo3O-Zgn63RRK2oq4OgTZhuVFWM0qnI1jW9WKNPL9ar0pnv30H56uma-c_in46p14_XDL10wzqXvnbq1qkGcPm7VYN92N24Eq3bKIps2hNDKQYHJjSgwNbKwRxmjQIupskB6MpiDUF7oqoM2vBTGgVVuHEvbOUkVyNbUGojXJV-WUm3jTGW4dh9Sb8UpT0I-eskYofqb4DcgQh09skar6Afpnn8cgKuqd1pSuP7IbyVLL3XPNMiV0lwYJMv95yozd1MJ4BsNrJXq9y6BZctY332ZOZwPyt9nNzJISA4NuN87wbCsiOrxZd2yVRJ2NoJLmzetd1m1l1gQjWN7e-vpyqOihsb6jR-fVHtYSdpNp5n3QHVKL22rFlhtC5XDor5xYvqyTAuamS2uxm9KurUAyqnicvf6h_LrevhYtTljKHjCHgiSnQ8DcxpUses9c-x8u3Y7Ka8zTHPSZjHqc2vGTWBdcA7y5jnHf_tGYyvbnwcp76KSY25DEvOogRWrzkYwFXv6RO002qI531b8FNrppJoDE73zJYtY6xWZPHjaWHGs4X6WBGvxBJDhJYAHrLjXJmx_ekM4p4AAskntkn-xJL4SYkSPi11-nG2pITeIlIZR9bTtbGYzaLNR-0cT8G6RyppjXH-OGja4DVknBEL30WsmpeqbiqvqUGEg4ob11Ngzo0rkDTX6w4CVK2dhXd29_Roz9kNgyCy-kDFtXTcY5LduDaY62HSCHK-xjxL5fEgs2xj2mSO44lNMj04q15Ox-M0gbjEOg0qrnxCVXkOW8-3E-lWM5-hcUBab76SrJaOR241a3ucW4itUcUsZtlCbKG10wxnwGaWSvFrWpgTAy5jscK-2LY9yX2nHTnK0rzwy3B_lV3AvezCbSQb2IRF4ycPNan9NCk3XT4ta8EN57USzwZTa7V_sNkdxWo8Vn4U33N2K_FssnDN9g8m_-fTJMpH43LfeVNprye2AsUGst5o_aeJ-l6a2mjnlqSTnnKO-_CMOVD5aGui3sZQuvK9OcU4ZeMHk4JatUOQF-ky17qFIMytwy0smxjCWdueU8Pyrqm9NNfnI5Wbi2my9XKtwrGJENi2jm38YLOqqX2a6MwA8mCR99naqHfj2mCqcyTOHMufJvdAq08m3yaE7Os0n6UgC8nlyMTx1ry0Ckd_4a9aO1XzJw-kz2oesHtPr5JW7mlrZurG1X-uFodzPYLpVnicRurma0RAv5w_SPjTQGOryfqGd7EtXlg_vQpBt1Kvc13zGb5TKj6Icm1L5BOzNcd2oOm_kBaB08CwoUbAW_sBwY0zS6_cx--_U4AOk9CYsnJySxLfQrBRZqBu-2Be4xtjixhUvD8CouVbT6oDzQZTm2FwahTflejThxT95vR4z-ntxSqfjMz45jye3ifTsRrPBss4vLaKG3yCOabvMY31tbJYdzrn8-TQe6M-JCbfXiK7MW0QqS5yVXMsX8PFy0Fta3sODqbxFPOnb0bgAKRZBl3_j5qk-f_mzoXREAuVXuausw86f-TsGUuK1eagfLS1c9jDi7IJwROV-VFyZbJXod00elvWSm3MQ7cpWn-8NEW5x1RtLdmPbzJjZjtIZVtc797Al-bxw9NyEwfmn0M4d1OXVTzf-ZfgEu1SJgT99-6_CJWe2GWUcATfmMSe3OUC_g_fXC53KeZc_BtGmgZ2F4liytgu9VyGdwXjLgVEhPBdzhiTuwR5LvyliMBfDEC7DCO-K7grEPzlku5Cr5LsYgDAWHBvV1DbkBKKAZhIj--6HnNhQAijXSYwhn4wwx5gIoLuSo6gS8Kw3K3GSuEP3cWuFN4u8Sinu8wVEvAixgCBK6UL8BKQEUGkHYXr0XIsMC5J4KFkHoGHEhP7M4fPEgFJBJBJ7HJUEksIi4Zxz86aADIYNsyaMQzdMkYQ2S2JhaSwk7EQ2KXSzsP-AL_i3YrSEgi1C63KoXCB7UCBIBzoT2yfbkkuDj1LQuwoqAAssD7lyIHQHHvQFGhHYaCWghxmveti-MM8AdSGXhCM2xUE6OfZkXgcQffIxRaH65azt93bmZXomIsJjAozDh2QcvIIxi2EB_hgANyF5USU2gnDotoBAhYhLC5YT6Ct9IgH88RAVRg2BmJRQTGQwqtHDhg4o7BGhFNeTt3CULsu2BIX2EUywMOwfSpgDIR7MDuPIegEE-gKU2xHXPIVLJQlKTAgLgdbDsqz8wZ2BEawqwnQdiDAdUADIWFomGNgHDtxAZ1LYBDAC51gzmCiMG7olvKyLyztRIVrfwFuwyUMCHMBwtc4KGx1uZ4JG613TN9evKg0zKgoJvnTJ0-ur68fT1QxSkPzOYrNY52On0ygEUjwo1KbPLJonwzhv72rs73f6OR6LE7cC_b-89uw-M3Fv1wdDj8MwxvywvOCR68-6uz002U6zF6H8tF09OIzPg8_HrNffvkSX747uvnos0TuRY-i5Pfj3yZMXf78M1JHowk5e__PP5A6Ofk9u_Tc4zxSNx-HOGYvKL08fP3ozc_4Czq5uNi_nF6zLxd-GI2OXmPuX-P31y-Obtzws3tydPL5j-Ms04_e7KPT04vxx-gXJX_fv_n96MX--aP4dJL9PCqOfzuk748-HvzC9j_8ir1f99ipefdP_g6P819-e68_XL_y0jP6s-u-_PDmt1fhoZe8fv06-fjiw4fjk1fX5ODLyb4838fjd6fJry-uoiPz5To9vjo6HO6_PbgYHsXDfT08HL5-Pdz7cHj8-mg4RMO9366Prob7p_uH1-9-G749Pbwavtwfvk-Hp8P9q-FouPfr1f7HvXfDQ_qzAToVh0M8Tt34CxoR_dvHq-fPK-U7W7ln1SntvDYU1bdSB9p1LhUf2LOisr90bviX4EpNtIDzuuAsjy_ARBdYydWNbkknoBWRBSDuBCyVyQKwE86qlAY-1AVXSugCkHUO0EraAk52wZVyv4DjnYS2ergxwE44a0MWcG4XXKm8GvMg3QME09RYErww4wsGgi9gmUsjbk23_fAyLUz5zP44-1IadltAXZedXxaZdYu-pOn4V0t18lgSDlbMwx6uSjlOjCrO1GSeB7CgdUkILFJVB1Ko4iAC25-VJUgzJ8RC_gJQwHqPXYxcj9QHcp6VTmTtXjTLHqa5qU7iVpUb5c-N0hELWpWNyEoLXqgMHKCnztuXp6_fHg6GxZcoixZ-XBhX5TeD4zQOTOLsTfWH2GSDuv7vqQNLT2bf9lQ-O6EM6vOpgx57nicHVZlkvbH41CEMDZqVk8ut8OBtEn2cGuf0AL6wUAehDDwVeNRHmhqwPJpLMKbMcG6QMZgrRWVIBEIUUe76WhoT-Fh72g8H5YRLYj91XDSoN_phFGhQr_1T5-IR_BuUQBfm41OHs8HpeBJHOrJP8UD83TrFdfp0dkzEKSu-Bz8x6RSpc5oUJoZw0a7eACx5s0VNHedC2dL2wU8EIdtkXNUBOS3ywFP2d_tUgZO-cOgbO-ODE_O5uTBvE1W6jNCRf-PsT7McYLDXGkAJ4KShcwO--wzG8v9ZGlwocIqdzP4FN_gx36mrimoJ6YQgd0LQOyHYnRD8Tgh5J8TspFQZeC1JgbtSCg5tLGxsfuMwuDKDg2n-wYbIgWmyplGeCcEF1SzwuEae1iALIhREaSpC5BrDQ-nzEDy1wJ4qUchwI6nxifRDT5k2a_LVrLkHrHncYE1K2qzJUHOhqwjImVXmzzkOo1s8CuF07mD7s-TO_HxWndAd8FVo7SkFe-LPAY0XfTBOVd0_YLgJu5qrCQhEZo8INiBsddCgOlyRO9cRxIjFKMqduuJspD4ZBwZpJW7eoD1Kx9jwzU6BwHBn3H22cgA_CLOLvuKwktnbvH4xvAB9n1lKBgFQ_DIGU5INLsdW9ezHUxuOOj-baxO3FDJXxNfEME258JFldzfAHDS00cKEAchAoIihglCXYB6APlZC0ZAhLZFRqM31rMHaosXaZPAvnakQ1Nq_S1alznnliTtVhN16DExSDbsN41wBdQrAdbcyXIMEjGc6w_QTsew2BKDF0YXebUWp2O2RzoY-790aM9t6NXevwVHKEeG3KfCDicQqhicrlfu7NLJm9IU9aNjN56CpiOu7NMBuSI3yfa4FROtSKK25cmlIKae-B06IKyCc9qX0mDKKU4JCD4dem89xk7XRoOboslOn9lWX2LsE4avX9HoU6VHFGODigtYEHb-fZtl0AvLwQOu6ip50hQI5TIosndw4B8DRmblLe7gBE6AaXA-BGsFYIMFdHWoUMvDuFKaCGcx8HOowkDwIA8b8UBKkFTUBZoy3qUr_k7QHplvJfxsHaeKwJ6B6Ny29XDD8JrkqRv8BuoOt1B1n5krF6VglkdLwJYiAjJ3MHtDQBCEmyFcE-NpopIlmVICZNF5oXBxyP3AhbNGaQYjjcqmNSxUlCnFBzBpT2Q5Qan3CVqiQtaztvKx1B64drRaQA77YuQIf-AZMVTfIu-hTFDgnU7MG5ijN_Ciw4eP7NAvyB9dVfw4freISvkIjXqbT2HmV2T2DpLhLIUpNILZ1OXW1C1EsMACmPMAhU0pKzQR2CZIGlKaxyXzhU6mI5-nA1ULaIHg5iGgoRPkdKER6b3eqO07urRTRfx2rDZWjuL9ydJFyQ860j5DLOIJIwfMgOBaGhZ7GlGmNiKI-Av2Iwc_CoQwJ9V2iXY4xRNV_vXK0V6c82ovT1D79J_wIwVO3Js2i3G6IaufEqKz4T9SVclX4OUk1WJhJDhQo0sTAdH0VF7fZhRHjBT7SRmmKPUp8H_tGaCx8xYR10DH8C70ArCwmnjBGuMi4Aec68AMws8t6ssUh4u4EBmiJUt2UN8w0wzfayg2CR2UfmuxTufntlFWzkUn0jdWQNev9WQu5ahHcFYuwr7KszE9Oo6R7AVyXMB9cGYzBY3c9nyshBJGu4hDzkJDKAIXUVSLUQgmIhVBASeC6yiU4MFQuy2sri2VPcl6PTDy2tmV2sdQsyzO_WmqAW5anfmwv93Dsjv5A3r2MW6zWtyiAq1bWu79OtlJFlGQBIxjiWENcjiSSIRIB9ilGhkOI5ko3gDBXBjLklImA8UBAsOz6Sv71OvkF6Ey7dgdZOr0arVGzZ_Y8h7JK-T9RFWN0j8wIphiimpAIHmKmtEGYEUqVYjQg3CUg7n4gfKQCwUAxGI6ML8IgCIkKpGcEXqMJvtvMCF6VW33lxxAc2cxqGgOdOlWrBFnTwmCltSSSSx6CfSM8CDDoVIFBnUJ8yDlYNulKRgRxjcc842PhehSxdqpJ4o1tW1utXo6A6vNDAo5Vi4kZR8AX7O-OLlP-ZSrAgn3L1m87LYrvkzOEyC1QWlLgd3BWQ9fVSnAsuedKxEkAzq5QQchd5vrgyHjgy3q-EoEJQ88HCZI_omRQvN7tO47BkzLdfocbEGM3F5gGhaKVRhADYCmwQp6PGCI-dQNJAyGYT0Jfg6unQu77zDUBLAESbZqSNk1_8ppZLUcl4FWYz7C2MNReksOaMEeZMV_M3aJTwf0ovsh2FoiSBwghPeQbz-MB8rmgymOBIb7GJnRtoZzWBuQRgR_quYIYLD2mBfijEKIDT0nN8V_vrpxBKBiBp3uepdcmX5NBs_X2JoMnwwxAR0YF_5HpNkxXcs3FdDwvWdlPE53WJSuAOSqMcxSr_EOTcTziMxkwqakyXHqhZJ52hULcC7n0wbvhAaVU8MD3jPQ58qTn-a52NeHg8Lpy3c59IwHntoOceYbtrRX48vhUfdulA0oAlHM4jWMINPHf6511qyvKa6qcapd8FvEEU3sl5CzbZPNgy_DlrUerwb-i6VydMv8ndD5WH0w2ODD5JC2c4edWGYXv6dLZAS-RIAYxB_KR9EMQWSGR8HxPaFgIWBuXehDjB5qjkGnJjedLrVk7speNCh_aKqM4fnTxaA_-Net8hGiLOUWtEHIpEF3yk-o1qaqAaEuZdxRKvDQq829suhNMQpU_pK06i3ImFflWAdcv-6ixDk6TfFobiaKyH0Fq8qQShMKZZDBPeFIVRdgbp-sh56tw_8Tr_MbS0BcvclnZCiOrbQp7qWRptv5bVBSUF8-vEoT15yQGi2MSrW3okCJwcBT2BNOaC0RdjKQRhPsgHiaQ4PVgAmEDEVqGoK9c5WFs_UmMaBDeqn9rMD9q7w-4PdydFpdX9qbO_8-cnlLpFrlTnblwjgHW2u754QvrzNhkTdV6gFu1Q63enNld7UD6AoSvlWm3tUPLAGiFdFqPrjytWokpbsn37B03C0T2gldQU_b23dy6byA7jvk8sRUbGOgTlkc0vlN7-hBVRVvKw-rtgnOTfZxG8UwW3qSmLDJ1huNpbFpCIBECC2AkptgnGgfwXYGVFjgUyA84cKAkyhCjXFcwxexRBxZK35UhpV7ght1VA6xlo2ljFywGQwrckJc22ubuB3y9nR38CsyiVeKoySS-ceyH-Ym1alts8BPjtu0ixHDXFJbeqnYDyanDCeckKmxhX8mfNus11R-WLEZF1VnTsrrOXjW4gP7hmHhd4dvq3OgJeNRg7GYM-M5EMQg_8EIAds-6jPMiZ-bhNTXOkpJbNc50gxpn4nPDiQedGFcHEMQqxoTypPKI9IwXohAzBt4PVcDiPgoCDp6SzyCmgbBYhe0QV9KuQtJb3o9s-6dVdUr5vAw5y5aN-yIce2KxE6rk8Apk_ttxWaIOyrM-xVmVKFdtCVkcOh2swLLKP1odH4PmX1lubXX_0iYOc7sLr39Urb6yMG4p_3s2PD7dH7y3jH8J6mtkDV4ZNdklLkZ2c05lYZSPWjtCAcRQCtQwC8AbgfhaG2UouOeaa-x5rqYQniPq25wvcRn3vcBowmiIQ_hyOw-8Oori3nZRlNvc1K8hBhTsv32FwMJdOR2PpxAk3pT10eWV30vx0oUZ28tLnL1pVipjYKwpqPJvu9KX4FXre_h5AmbHmhiTLazuRH1ZrPU7aGCuVH2wYKGhhEc8PwgpZ9xlPtYkMIQGxh5x4SGiWihFOBKhh5GhzA0IC3wpdeCHyEUy6Bkwy22WmrZ8uvnCUtAJDQO8skRkk9D4XnkLQlatxzCxxVWLYGAKyrEldadXU1ui10x5UYSNZ9M-HhECabAKGKkQ1kcobWigwOnRru9THYKlINKVIGhMwhJwblyj-8lcOzTouxDtWpjFQnjrZK6849-uQempz1SwU5ZVfJXl2VJh0lULeG7f_VFy2EKgWkmn2UKeQ08pxO6tzQKfIlvuCgbfpTjQCLQm80PmQgzHBTYYIyZ9z4eVpKBHCfNN4PKAcQqq1nDUbymZ2Gop0eK4xuwx6I5S8_FWyFbd4vKn5ZjI6hzT-ygJcjukMejrKAnTzI7cBp-fbCFYOUbrlOH6820nTjAqm6ujtLZFmGHohTrEImAgYszzfaC_oKD6SAjrxYkOA2N8TWDNDIgdLF_oC8T4WuPW8smOWz4Zpe2MlPRuExuMG7-j9I2gNYHF3XFK-_TPEP5fBh_zSj97Au2b283bUjOvztW8iz6bZCbStsRdTcpqzsOxn6XgJmXVqSjLXUueP8buWs8fPabAH233H4EZlRgrEYBmd4MwEBwpGUoqBfU5WFyiwbtyPcuGSGIT6gDMLkCHIQC03X_ZYDXZPuII7NZkNdHP_R-mh5Vb_yaLrmwGZ8lZr2LgUpPYcLTMtqjms90q_FQwdcKdvDycOs-9DH4Sstsnhxblwa5WPrt8Kwp0r_KlhBGIvVPqsKrzevvtpgfD16NtFHbi1u5fI4X0YGHCXx8ErE7LHKQmyMyM94Hm1u0dnKupci7sp6YJQ8IzmLsuslXrzFcuZQFXgU9CLY2PFIQBTCOIYxVlEvwWhFyNKA0VN750xZqiPMuPXpMxysMK9QGG1kHGnwi6Qxval4GA3q1y5NaMlWxRlWz2UYffvY5bqrx8-eribPhicKSmcxV3kmYt50RQ7RpfCZ_4oJ1C8DkoF4IGnm8kDamBeI9jxRQWHpKE2-IGoaTnSuEz4Yt2SQpt6KTljERTIS0xAGltrrdSbX1WZCUl3JWUuJxEmQJecN6DF9raKAyJG_goDHyhvICFhBoiqBeQQBFQv0gEiKgQvvpUYk-F4Jphw7VvvFDCX9yTDE6TDGSpNrJ9lPthyOCtrAItlIZ4BHTwjRmcpWmS24rcW0Jv62tDsEEGuEAH9ownCm1s4VPfDZhx7aY7AvfInsZXwiXCeB6mRmMuSUAhxtvPprkCE1pud605DrqsD-i6U_OctTOrP7HbR57BbxL2x-Xz-Jx3I_bu3hWZu9Q_2Q3CtZrov6eQ7UtoV5udCMimZvroDMQxVNU2_iWw-jxGTn1zy-NC4g6PS3AiWmJtgoC4ijGuGPjsrnBDwoCDwXaFhntca2qMwFIgGTLhceZJRSE6A14PA4_R7nQGXbpUovzXOr8v2w5-meq05sc3C8cKzFV5FL6i2VWSlsFVXfO1n8Y2CCgbNltcWO1QdV5vzi4cutvQEBvZ22pb8LQypPVsbrfZi6dm3uTKGlWMWpFClWAqZe0EvLMkXRzrgeF9nEZZKRS9K1Iegt_X1SCtriYBvz6L0mnuvLOR_M1g9t7RugCptfZicKGCaApLWZYGDl5E48hSq0itymqt9J4qRrO1NY5fJjjAtSXgIjm50pndQ188t6fH7ONfIl99nKpBXeST2-dZ2WWZWN9PE2DqrEqs23b2RtfBCSgcmIP-S08aUPYNUFdYlf9DUpd_A9TFiK_j3YM0u4FhfI_UFd-CZsDgw_yQvCu_AeoyBvHlD8m77jfBu-4a4g5H5b7Gd0hb7xugLRXoR6QtQ9-CRWOI_pDExd-8Uvh-7Rkjfx5xcTsjsf5mto51kJ6Lv5rp-w6Oy9o3p3Zfk9l-qWqcFuW1oef-24sX9ppPS6XFa1Evr9XEGfo3ea7mh7L44qLR2Q2s9X2kpwEgWb6etkJYHetq3Fg76_BJv4EsD4KsGsQdOBo3s7K72pSv8uo18y0ouMngbcH0du2ru1NnN61W2Kpd-8bds2T9Elb3yraWcHHV7GZLSFZRgm5B0QdYFfI1cLAHmIt4gHFsg2PV2uBNuHSVuGyyuNVbMu81hBWCIu49gk1EdfYasLls8e36pA-kZvC9Z88egB3xA4gF25APGpqer9Nv9c3oTf3WuCy9p36rlv1eQ14lPQ9B-_saioZaJGQtIasbzVuEXFxyvkzIFQjqK-CbCBq3wvdAUN-93hrB4jr2nku5ciHua63pRpwwf3PYfeRoNUveXx_we2MQPZ3H-ur75nI2bsPvuZyzVy_PlYG3jRA0_Ua6bszV-xOaQ168UaEHB9dvI2i2b7yg4F7KiD8MC5L76jTxALaAPoBepD25sH6DRWtJFi-16LGm9ZsomggaL6fowxTVyzZaI1i8f6OvWluhldgDeYn31Y74YViT3tPSNchB8DYIGnQgdBtCPFRwuY18PBAviPvqhwdihofi7a1cMIuowQtubz231FDehwk2WQlbANViX7FOIVXv4Gnqo8VbeXros_pVOu2MwvztOvcycuRhmOchbNSWfNx4g8-WLh7ddN0bIyXefTiOPQz1-b293I2VUIMC7D7aYpOhV2fAG45lq4559q7F8h1I9tN-moTRVZXgTSbTosZi87tlKW9ZMg7LueP4aRobldQW6smtJsaWBp_me6l9BWde2MKr5zsv02QVrJ7mRTo-S4MG6AqwiUqKkUmTM_VHmh2nwZ14fWWHfSdYOdTL6Is5z0xuGvDVvUnrRhIl3SM5t3fVjezbnrJWR7b6HZZnOvZNBmoOofXwdkuiKlNdNKI92lRbF4s2fH2T2R0ty11h4lXM-uzJjDmePTlXxehVuDeNYnvk7B-D_wdjjn9s
```

### Screenshots

#7981 Doryani(DEX and INT nodes)
Ingame:
![image](https://user-images.githubusercontent.com/123731007/215060186-8690798b-d0c1-40b6-bb5b-1a169885613a.png)
![image](https://user-images.githubusercontent.com/123731007/215060222-b3c640b7-11e5-47bf-bb1d-57bbb90e3fb4.png)
![image](https://user-images.githubusercontent.com/123731007/215060239-838c6cf9-6154-42c8-87c4-499d79ae5bf9.png)
PoB:
![image](https://user-images.githubusercontent.com/123731007/215060902-f3cd8a72-139e-4493-af8d-9f160986ed06.png)
![image](https://user-images.githubusercontent.com/123731007/215060928-cd2a26d6-8cec-4f87-bc17-91eba3470a8d.png)

#218 Ahuana (DEX and INT nodes)
Ingame:
![image](https://user-images.githubusercontent.com/123731007/215060281-ade5ced3-7d48-49ba-bd09-e193ac3f6f77.png)
![image](https://user-images.githubusercontent.com/123731007/215060299-530851f8-7ad6-4586-88f8-d05c0d89cee1.png)
![image](https://user-images.githubusercontent.com/123731007/215060313-a0dd9246-4e73-410a-a98c-b35240bb6efb.png)
PoB:
![image](https://user-images.githubusercontent.com/123731007/215061138-64dfedc4-7c0a-4958-9b91-145d5ace7dd8.png)
![image](https://user-images.githubusercontent.com/123731007/215061169-a988664a-1892-4795-934c-6e831da144f7.png)

**Comment by Regisle** [comment] 2023-01-27 10:10
duplicate of #5413 but more detailed issue

**Comment by marc0sap3** [comment] 2023-01-27 10:15
> duplicate of #5413 but more detailed issue

Thanks!!

**Comment by Regisle** [comment] 2023-01-27 10:18
to give a bit more detail, it was mentioned in the curse manifesto but the timeless jewel LuTs were updated separately and before the league so we didnt have ggpk data, PoB uses look up tables (LuTs) of precomputed jewels becouse computing it in real time is very slow in lua

**Closed** 2023-02-18 02:50 UTC
Labels: bug:calculation
