### ISSUE TITLE
Pob eat my GPU SOOOOO HAARD..

### ISSUE THREAD

**Issue by kyllapra** [PathOfBuildingCommunity/PathOfBuilding#5304] opened 2022-12-12 09:23 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

s

### How does Path of Building behave?

s

### How to reproduce the issue

s

### Character build code

```shell
s
```

### Screenshots

![image](https://user-images.githubusercontent.com/120372023/207008833-d81d32c9-0b41-4826-8f5a-c4da62720c59.png)

**Comment by QuickStick123** [comment] 2022-12-12 09:23
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5292

**Closed by QuickStick123** 2022-12-12 09:23 UTC
Labels: bug

**Comment by QuickStick123** [comment] 2022-12-12 09:40
Hardware specifications please e.g. what gpu, cpu and operating system. Is it on battery?
