### ISSUE TITLE
Fonts can't read anything

### ISSUE THREAD

**Issue by F1T1L** [PathOfBuildingCommunity/PathOfBuilding#4955] opened 2022-08-21 11:28 UTC
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

w10 with 125% scaling:
 normal: [https://cdn.discordapp.com/attachments/924621314621313055/1010869034864083045/unknown.png](screenshot1)
with DPI change(any): [https://cdn.discordapp.com/attachments/924621314621313055/1010869447717822554/unknown.png](screenshot2WithDPI+)

### Describe the solution you'd like

Maybe u can add option to change font size or the fonts themselves? 
Im newbie wanna try a build. but cant even read anything...

**Comment by Nightblade** [comment] 2022-08-21 11:41
#4545 
> We'd love to change our graphics API to support all kinds of resolutions and font sizes, but it's out of scope for us at the moment.

**Comment by QuickStick123** [comment] 2022-08-21 11:53
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/218

**Closed by QuickStick123** 2022-08-21 11:53 UTC
Labels: enhancement
