### ISSUE TITLE
Additional Skill Trees are MASSIVELY inflating file size

### ISSUE THREAD

**Issue by LargeWaterFowl** [PathOfBuildingCommunity/PathOfBuilding#3208] opened 2021-09-10 01:30 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

I can export to pastebin no problem.

### What is the actual behaviour/value?

Pastebin gets a too large error as the filesize is roughly 800+kb of JUST text.

### How to reproduce the issue

Load the pastebin https://pastebin.com/aS2uFhTF and add like 5-10 leveling trees and the file size massively inflates. I tried having a friend load it in and do the same and it happened to him. I tried re-installing and it still happened.

### Build code

```shell
https://pastebin.com/aS2uFhTF
```

**Comment by Wires77** [comment] 2021-09-10 17:44
Duplicate of #3156

**Closed** 2021-09-10 17:44 UTC
Labels: bug
