### ISSUE TITLE
Mana reservation of "Impresence Onyx Amulet" is not calculated in pob

### ISSUE THREAD

**Issue by Odin099** [PathOfBuildingCommunity/PathOfBuilding#3675] opened 2021-10-30 20:35 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

the amu should remove mana reservation of Despair if cast as aura, but PoB does not remove it

### What is the actual behaviour/value?

the amu should remove mana reservation of Despair if cast as aura, but PoB does not remove it

### Build code

```shell
eNrtPWtz2za2n1e_guOZ3tkdOw6eBJmb7I78jFs7cS3HSfolA5KgxZoiFZKy43T63-8BSEmkRNq0ku7ezradcSXx4ADn_QDAvvzXl0ls3aosj9Lk1RbeRVuWSvw0iJLrV1vvLo-eOVv_-ufg5bksxm_DvVkU6yf_HPztpflsxepWxa-2XLxlFTK7VsXVHBX9BKimMinGKk3O5K9pdpwGr7bepInasjyZBFEx_-bHMs_fyIl6tfU-KvzxliVzXyXB_vL3t74_i4soL7asiYySUerfqOI4S2dTWPSWdRupu7M0AMCTs_O3F5e1maOkPjOs_G8vz2N5r7JRIQsrhz-vtobAAHmtDuQE_gI2Gc8AFXfdXSQcl9kupcLdet4-eDRVKlgMwruO6_J_N-x5pg7DUPlFdKv2s6jYH8vEX1Iidp2ukS3QbNeh9kPwZ1oU0zhSWW15Nuka8npthm7Yy7SQ8cH5aIkYU7HrcsS4KxASf8y4tFgSj4Sgu4QxjightGsc6OkYhtVnZNjFeBe7zLWJ-_DIvRhEu8Fq9diT6yQq1IaDz9MoT5Nv4FOD4H6s2k8nXpQ06e3Jq_nQ4e31Uxc8zJR8G5ZGcSGDaJYvMBDUNehMJnI_zYvaZF2gp1GoGqCdSA9H_eAuwPf0g9TLPFcZuMii3wC92CcNGBU103Y6mXyhPjchOxEeqC9L_nf7UkDYgMSdjuIkWZJBiP0AwjokZg-s8DYtIHL14-ZSk5ljP-DB_Rca-iTx-yxBg75LMpWr7Lbm-h-aojmkkvFyLvTgXBfqWi3ppRTvEvrgTKdK-eNjiL8XslA1I9mF8PioRWqtXYxxbf4g1zRwnWvEeQhtC9OeAZ93Oek3apVvMHiX29jmDqIYOQ_O3WQiFrv2Q9DtHOyU0nuZBT08TKKy6_vROFJxLWFwyYMcrg-qc5q5faZpUt1rZU8k_fBW5nVzJIi7DxNUDqjT0p1nnCkIwTAiUCupCf6eQ86z9FedlMVPHDfMJuksq4kEOQ-SXsI37IV1rml8n0c-BHOT7F6oYOY33B7rNMxFhnmW3qoJ2IvJUCHtrmeBnQvdiyFnX-EAeoCqOH7SiGFRSP_mIA2u1ZMmefqI0Ww6Bcehda3vuKMoA07nUS30Cv448FsoS_bldOmhRXeipE2y5wRL4NUJGO32_tfjIoHSr_csKyNWp8KdxgxMTfOVaRzcA7o_NUezuFEsdAv8JmpCFtKL1QsLfSEhwxh7nep-nt7Basa6Js4fn6cOfSaXCVA3BZlKvt73xt8A7zXBYRLMMq3dvedYHbE-zcvnpmmgP51MpmlWWFDgF0PfT2dJ8VrmY8gLqGSCEcV96mMSeog7fhBiigTHQiDPUcqGegNKfj30Qsl4AtzbL7_qiaVfqKzE5WBHMUUCJWCQcIh0ievIkIRK-qF0iKeUg4RXEvRyX8Z-big7SaazwkpM3yHXCvApmU08XeyW_9Udh-drkJMo9z95szDUfYgt4ElmWiiHR0eH-5cnV4fVkJEy7tby0ziW01wFr7aSKN6yoqDSthGEGb_oAQ1lddWweBwW8gg_i0CKj4PqYrjHUk1z4nE43S7oAQbqIGPVl0WX91OlFS_vx6XKSz8Oa8ryHnBlFd2HLFOr92G68uV9D7hFDtUD9jBWwyjWcboPn85AfcsA3wcaom0WebOil0aZeqnHCnR90IOserLbS_P7gFUZV4_pq7T0ccgqhPVRO8hzeoroQIUKlLmXIRvncClvVFJ537mLe2msKLdycMHHapLv3UOIO9IMXenWNAAg-GUz8GyBCuUs1r__PJNxVNzrmFD79bRsCZt15OP0TudLJR5ttznw-vS0fDKMiwqFnuTVVijjvGrRmhWaVu_QpJzmu1m_6fdGiR_PAqirq0heTRdLT0-9ZV3rzvC-DivVE5XowB3MacjjVFdXSk6BecQa3em0YWU2PZFey99ewuoqBMdx6smYzKcrKYVUpvEYL2bRaE60KgDmt-EI2KAD6eeS5hNj94ZrsGA10d_PVCEDWcjnJwVw5Llmy_PWwYbnK0T5NXp1TNKlge7cfYl862LhM_4i5_8zOS-fG9171AZKK_-eVoC7rECP_IvT35PTfyyTy-xkmGXp3ZN5bFYDn9pwmMZ5P17vy1leALdLBP3sdIm8i7AqkJwkfqYkxLoDKDfK1sVTqVxEpG5c_RVrgcNaIPnOFOsEqtC2uTGdqxj6Uzcf2dPZOj1JupDTKCiz3s2pakHyBCUd3UVhYQ3DMI78J0jtcQOsFniVRgHktNF0Fn-rmnaiegK5GofVQPKdRTpvLC6bnlVPrtpV35j6noifwovIj9JZbi0x5v-xoLCXBvfWvOH7R8aFP5Va_hcIAqpt0Gr_WxzgGoonMH4x9ju7gf000XtpEAlVUDYUvoHAB5A9JR2pYbEqNH92LfsvCLS9SdR7WN8lHezC9ARiT1WePzUR7O0y_ohEkGyUCf5HLCct8o1sxrDxLEpAIit9pP6qdhMVhco8s4RVfAbVhpXWaDaZGDRL9BtYmEFidS2yvny9-fe965NFm3lzvXyXeEBZsIapf6FSYbBWet5_Jj2da6P9GN9_nkX-zfHMHA7ZVO8KpWJAuEnFuxzb07_hvrmDzIu3Sb1x_Q2pQyeu_oRqHNbdWCVWicdadtP_E5oF3LtV-R-bNhyofCqjbGO9uprFicqkF-nBm_iy-QK-c5KwF8t8OlaTb0mD1nE8ga7l4D-v-jweEUo70ScxLqOJGkIetLEmPYCqvwWfSVh6GqvFBvB3oPEqKmRDu59sI6sI-tOzGPqfUqLXCsJr8QeXLkDhWG3ug96b4VFyDYFqo1R3gcAyGHoqzn9hN_coBtQHMh9vLKt1DE-QkxlsmdHfi6I36u58LHN1MUs2pqkNxxOoMmMtPfjfYOR5Ost8fW8KyHiB6YsDJYvx_8hpmv9vbr2FzzvWMC8yGVvnsTm3-0d2NR73vea434E-fKwDwrsk-jxTG9jBX73-v3qXf_Le5V8twr9ahH-SFmH1yRw9u8yUsmQZHcwYXB34gi_1a796neagRF6o7L46mfhq6zeCHYR3OHIp_X3nN5tz4uxQgV0E37ArCN_BLiNEfyMYvjFhM_2Nc-bCOJsJDN-YIC7bwZgT_DsQkAb6XBrFlLEdQgFkx2bcoTsUYYx2CHHJDrMd194h2HXYDqUCHnJBCPwibO7uUGa7Owygd2zuuFT_dRzz2dlhroAfGLH5jr5SZB66CHBT6uxgigXMIASAU9vhZpAgO9XiXRvxHeo48JdTjNkO4xzQ60FULwbgXeEKQC-Qu-O4DMZTh8EcFNiwQxBn9k7JJBsxhjRe_ZTD1ITCcnZgLTZ8LrnKOZBOBAHkHBOqeamXxCnjgAYBY3coYVjALwjrBTgA4zo2sATwAENdG35gNkOwLoJsDYcI4KXAQewIYBLIigggzBVAvEAYsBvJEGzrX2BWgHFAnnoFrh6EYDq9Ulu4-jsheoVaOMBFtMMc4J3mP_xlgtogqVK2iGJYCXE0W4BaxlxgMSMuoGPYsW34S2wKQtNjCCzUBbzItY0AYDxwXdNvNIpo7riUgyxs4AThSHPFIaWgNWmwLliEAISgHBrOKApmQCuoleYzYww-CxtAMLAZKCY2UO_C-o1GgLRgzZosWy8IIwFYCPwXZI70D1RLSOsFTAcKCKt1gUEElglscZHhrS30RXwwsdo1fN1O9OcmRatE7DCIIKC80YpfOaB3F6fmw9_GRTHNXzx_fnd3tzuFBDAN1ZcoVrt-Onk-BTRguc-M13mmJ3o-hH_2rs_2_NfTu_f2J-eCvlf75yN6dvTh-voTBOrJ3enBR3T--cub4tldcoc_yP0z-mP-68kn-xTTvS-_qKuv9PP98YfbD1f-x8lF-PXo5PaSf_zkyXeHp5-evb37eEqcX6L4y5DH46ufgptLeXN-coLICL05mB0k9vjrl6ur0b08-fXgl7NcXJ2cfPLO94vx9ejq-GLPObN_TrKPd3g0--mZujod__zj6OLsytn7fL73hX--4SG6TT-_DrKb_dkpO9wTlxcns8-3tz8pL2Wfx6ecfP5Y4Ck5-Ohe_ozuh6PR6cHNeMzG8tPFnXx9z8698Hx4dEOn726-OO4HPJY_Tq9GP_3iH7-L37hofPz-3dcPJwfH6Bf_tPgp_OUs2R8excP3wz15fRQNr4Z7766P5PD9x-PZOL398MvR8adPvx67V--m9Mfw49092pud8lN6g94YQT2fS-pl-RaEvBRb9c04My1p48GgIChKn1_dNVuHMy5tCUe74AT4ohq6TnzaHy3hWBeYcXxLONwFZ2OmY99i3s71GXOuAXbOTMFl0xZKIEot-QlfICCZ2KUjlv7wJi2UeaZ_nH8x8ewqUndWrmTmj0dFpsusr2k6-ah56-xyzMGrCYYQL089v4YK60xOq-CpIasT06w6L13I4iCCgJeZk97ziKsBP-irqZzsMmSDrTMuWHn_6KUJ5FVY1Z9HqjDhc5arkfLTJCiPHpqf59WYGWROilfnnC9kBuH-hXUxvDgcHMsYKmuVR5ka7GfRJE8T60d1p-JBWXRZJwcvLCk4RrYTShUqxmXocklhTWEI3st2kRt6gnvCC23X5uDqfckD5QfwgBNFpesNzBIM-S8shwxOJlNIAKMif2GhwTb-wSqvblhFaplD8pa5gDdvxt-NI71GyFKs9_rwepRcDzD5QdfA8wN5JWB6qzJLNxEH2K4_LgtWI229kCZTSAtTDiERT6f31mgcJWpwpoJoNrH245nOUda5A9E4VNLzpQx4KEKImBBSVRiAJignYNJ2lI89Smzm2FhIEGroEmn7gfB8z8eiwR3bHZhPF-rzC4uzOqvo4Dc_kyH489-HQZBb3Dov3bRVpl3Lx9gCACC88dyKQHPK1VulBTTwAfhoIgGsidS6zmRSvLCaDDfl-TrbH0Aj4zyd49pmP2hRl0jK6xNa_H2Hs_pK9G0Sy9xSVmWibelrx4NODuxlwIDACtPMOgfbTvz7h2Bn-di6i4qxZdolHRpEWzRoOE19Gd9Pc2Ud5rk28MGpvi3XrUUkAO_h2zR0fc58bGOJmALLwg63IW_kUtkOCwKOXXgYIlAlh_kKsi_uIx-UqaFFnNS0iKGHtMjp1CLSxhcQRaYaWpR_HzXqrTy0XXk6pfguGafxvXWcyYeh7uSt6QUD7OFtFHeDvo-AbP17HHdoBGvRiDOp4hzcysR6nU7VoKSzUxuw8ANIQT3uhwpy0dD3iXJB_OBjw0B5Om2E2BBQihyCPB90x_ZdB7lSCCa5aPoUbndqA1nRBtKpDY_LltZFW1ZyVhpa9-B7rf1Zlqv8W2Xcc_jCHSgL7UJ0gUXoitWaAqfLMNkt3LMohzoUNEBl-qqpjjXtMuZNGb97c_Lzu0PNWv2yCb3Yt8n9F2s4mcXgaGuSZRi7AWfcJSFVKHA5Dz3JFXURg_oFh5T4ricVQxBdA-mBuQfKwQhJKFd9wr3BYRwAHXodzbDKa0K2WZeQY4ivwJjcgvQkM_I5kNlNovIcAjHTXNfMXd77G1D2YKQ1WoOFHkicpkFv20j_PJFfognETy0CmMNpF221HWyNZQ4ZnH6istvSoUehZTbo4YlMLN0PHuirkeD6QYT65rl1XvHcuHWMIEfTQs7LLX3QP-snLV2IE9p3AUgljsNETe47xGs3xfvm7cXZ8HRwnM6uVdYwVOwRwqBudbF0sJKESIcEYKsstBFVgaOvIGNElMRCUChCAyS9EKp7oSBvV7RpqGhQXZTTiVHlXl9Yx8_g304TxoNtwkoFv5b6Sp_hgpL-uCTQGkeF5d1b5WHqvINe0UrvaAY2EwG64V3DPYXStd1QIfBKkOtQ29FK6iuqFCfUVoGnJMMoBHfEkCMd6ds4FCIIBSRHAQq7qcZujWz9b41sTFbIFt9MtdOk-mx4fLJv8j1_vjXyowyUdQSu4EbbSjFW1rH8CsmpasRuCWbreo6LAha4LPQgQBNfQonk68vpHCEEVb1EIaah4zARyCAE3y6x5ODbPdxgByNLdhBUo5-IJv0Lo36nLdPoenUl38oMI8IZRCgM9usv0mvNKzCEkqASemklgZLaSvRdbn0O34IiJ7pRA4Ybjr28GKvTLG16wczsn5YIlXH6Hbx223g9ktOpHn8IUTCBKY1AF-w-j1VS3Nc57QUB9RgwVLmcgvP0oSrhEPCIA7WGIxX2EBXI5z5kTY5v6zrFDwgRiBPIlhBvukzawWmbN0sU7tY5YNZ4AS4GnKAKBhdqos9bgN9ZRprFUyvUEd8kqYbNUKjpEeap9mbgwiLt5IB0UkYqQ_xc--rIQJcnuhtbOt-alwP_OCs1QNdJSQoQiaX3BUuX2y4NjFpylAvdnT-eRYHS9IPlw7L20ruGqiPqQtmiCEQjm_qQnjp2EHLQ_0AgTwREUHB-4PqEB9HMcRSIRAhXIsWB_Z7dEACEtYYEFqZ_8ezi2fGzVb9n200DIE3FjM3LauSybtSJe2n_82xmm2gjMBg1r8v5YCwQaen2-GCbYQ1xoL6AQsKyBjpeLeeYX1FZhLgy8g19H6KSf18ZxdIytwmqhbvV4GktX7DYJSXcZjRD_WKaBGxUzfUEklv9BoKmo3qtgms1Tq_r4vMFD1lIoVKVjk085CJMqAi4rZNGHniBEpBauspzHLAkCq4r4CJwbM8VlPuMNcQncIf9UPtRT6X9jQcKDFwoLyGCXWD-A3gus--y8GQ6ZwPtHjBgZFzfUIEZJjMg-l7zt0TRdEaHDzkj3Fb2n8fyGvh0HGUB-PdTXfLB7HsqbiRwLjAJe5IyzqXt-qD0LiTpkHrbwoHI54cBFSxk2PVsN_BtFeIQViJCbCtP53uD12DErRkc6szgINhR3pJMGXUGN62SayhPKeosrrYZqQ8vX65glW9XGGzz9URNn8cCQcUTSweQFb23Fq-Tqqk6do2q69cagWeD-dM4qGV4XSEY09ZEeu18wqB-PGFQtnRA7ThkD-WXPaC6esFbZN7ds-uIRs5CFPN4wBFD0ob8mwnGiOdDUo1B3XGoXRVXxHOo47h2QJFnKwpxXLgQtV3aLLBt2u64jq29Z3uQsIEDqwtzNXPB-Id5qr10W3VeaYMu8spTEVT2H0zuW7oyEChqSdZxwyPOfZ9-hws4S9TSE9u28ZroyzhUDa4Ebl5IAsNkGZMGH8F8C3mjLIjFTe-mDbaMTCYjo4swBfap03DIoUFBjtK0mIKxFp1q0VZDH6QQTM91HX95lz671E7DMsewrb-X9DyvspN_LBUEMsp2_cCDCrgEqr6sQ9VUSOcd4BwllRx8o_AlC3RLz2WEUt8PAgYVG2Wh9IjgMsAQCBGjNoWSD1TLRmS1D9qqQlqBmuojULv6dJsaxeuyNpAVlYNtp8WdML5EWyvNtqkog1hzllqjqKFZ87fGVXq3gHLW8tC3SR7L2fW4MJrC1jSlQzN4i2aMUn0FHZaeF7r3Bo7bl9n9IjyaE7ELncBOt8_QmlB3jiaY1d9Fsz6E8LqOOAHn4Fgk2Bv3qYSCCJwHFH-hlDYOgjAAPZGQJBGGoFQK9JuqfAFRltkethES3eGBd-vL3oP60sxh1kr4_knKNnVNulP5DmJ36tCqrmzTjp7vMn7Yzhq2DgWw22K3VqiRzr5gnecqUfoojU4GzLsJrJ9n0W2zcLehdvACYTvIdsFapfI4hSwnICiQnAuo6CiHjIe6DpYeFHVKSI-5vvAh9EPkp91ysh8I42Y1uXUeaQ1aKQAuzYvVga28nzjaElza2PhYqeTm2yxmHKS8uuVDyrlWAFcnMcBNM--Tbi-Fy3oLV7T1TiNwXXvAucEb_bbBiW7jgB36UPcXC6sGoXVaNTxaOHuBeZezB0DWqDZD6gfSkYFN9Ya8dBAW4NA9xxdE2D7SZ0hc4em6hjNHEAoFD6e2ZLYUvvKbXVjR4e91srDXrHO6Cv2qmVGyunJTe7EMIE-eq7wyLfbFSxkbNlja6yJd3MbIqZszxlR_bRb4A2E_FkqI3R42WBk2WtdCTY6xmlaaYvk1UG1yi6TMNuajq0y2plNuX51qbfMMvVkSQJZlmVtWeRRrE2sUUKfRV5kFjY1QKZTPPN3nQDanShIXskNBpSCIqBBKY0-5nHghE-DQOegKg3Qg8IgXMA_cSlMhWEf5xNxe5ROwMiss8zI7LahtalK5s4ofVQE10A65u3Caj67SiCybTU09HKdp8JRyym1N4o_SzIt0kxZ8Ww5ZO5CbFV9LhI2YyT0l3SBwGBKSqUDHTMyQKxzi6HTKD12bucjDTsAC6vmB5zIHsirmhlhIn3baGX5i_-x-ntZCmi1vtUqCNi76Na5YdnhS08sZaF8NP53VlHCpux15cddGdFtHZk-N1QTSGZBNFJusd1RA2mtdaInXOEg9KFdCqQIJ3okw5rmhi3jgeCQgUPI40kdB6CsO7KK-9ljcF4w7RAKbMVvZL2psJXDRsZVQ3jnNrdxcSgUOevfWR-0cRn46K6xL_arT3BrLW2VpLq0mIHq7YZkqaPVrcxSLjszSa4kHCllCOlwR7XZFNYdCezoU0naS4ijVQQnE2y0l5kC6oYgKsA9_PRCMLbl0dCchcELkB67nu74dokD4RDeJpRdKRG2fcewhEjZLUKfPhs-3S4k-Umtsi_UScp5SrgmC0AfTw4cFVNvXI3y5pVdZVU2OjdpGN19b5HgLspP6bCsrX6NISKsLuxwDPwJt42bbtnlE5qrE8aLakjTiXvxWHRtp_lgeAmj-dqV7u7UH5ZthQQQLCLYyb_k_unhRAnixanarf6tIe4F_f5vE95YsD9XO9zpzS2fKywUvwEk3eJ2WBTzthq9RswBn3eCrHKg_K2m1fMiVPWXN9y8DkwNpDfaUVhfQgKRkGkje7DjrQ4uD3zIJBcELyOt-f_Z3gp5h9I9HGi_6gNhZGlzocZYZ_WoLhm9Vm4LViecOVaKVKrW3tC4BnTn4rItjndIO9vUR76IS6qnS3ccX1kniz8yhzqWGnIMV0V1nF63-hFH9t_1ZpvvCLQpEm1PN9acUa1N7nmFYQaHiOLo2W6rawlZ-Aj1cymFdVjUF3CG_o11mQmTDU9e26IPatrzuAwyU2evAaNM5f4e8FrV05UtK1tG-g9qrD2ICiAn_AxDT32nLiaZqz0efZuqaYNgTPVm21fsj77_66rTGQ5XqZnN0BF_Wal3HcZqZl31d6a2Q-4Fegsl7187WcOXiIDRb1UJvDboKsk3uY-pwhwfIdilTVGGPEyFtW_mu5xJ4rCO14_syXG3az63JOLCVzguvN72Gt_q-VumwjrL0q0oGe3qPIdA064LDM2k3GAtGhFm59LMojPzlc30DQz_-EHny80w2_GRW-kldGu-nCdCalcFej7uSMh68Bh8HLPK72MrbiqS9tCjSScnHtZ1w8zZv2UxwkC0828UOD13XhorZQY7vitAPGXZ8xgIkiXSRCIQXKEId5XmhA8LwuId56DRZy-qnIXqUxw_ugzO6sjliok1lCQNuf8se9yhO56-HX777c3Hkef4m_RpUiap2Ohk760Dze_wLGL4OozenahCkaypeA3LXgea3vRcwogtRjTC3C6Z2zJzwLiBSmw2vA83f2VyDsruhqnfazkG7IfEKZAudOgOpz0taVte4B7tYIO1AVuMZQW3IzItkFmjYOkh5jGwJM-dqdQa88_x3_dh3Gzc0M6yhd5_ncn6cs64qaH5kvo2RK8NIv2HrdrHOiw1X1EbMI6vS5vPEIZ2m26qYbWuimzG4HxfIdxrGNlukvdlsPYe1cRM_IuE2hXpEAqU3fOpELapkbzLPI_rXFRV6YKab2xHehBK2mTLgzVSPPS6f9UjZwtqn4m1TsA0p7-V6WkL54wvawA_Sx-hehMAnCrCdzRtpGN9kUC-rXM-FeiVDPQjlG_OVbKCJ9mbGRDdTYPp0NWObu_4NlBpvzHzaxzZbMt9-qe-jC_-GHKinLNcz7d6CsDdQzM0l8Q0a09cvt5YTT6gnesvmEc511SI93AzZmL8buoz-Al0vmXrQQ3twqqXQ6i0JtjG_-Cbhro_JrNeEvRX9kTV11ZPPq4LSXIg2l43N_zIvTcLoGiBePj-XxfhtaP73fsDwfw7-D-4c42k=
```

**Comment by LocalIdentity** [comment] 2021-10-30 23:14
Duplicate of #3619

**Closed by LocalIdentity** 2021-10-30 23:14 UTC
Labels: bug
