### ISSUE TITLE
СoC Effective Trigger Rate is Broken now

### ISSUE THREAD

**Issue by jan3ry** [PathOfBuildingCommunity/PathOfBuilding#6539] opened 2023-08-27 21:56 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

-

### What is the value from the calculation in Path of Building?

-

### How to reproduce the issue

- Effective Trigger rate before update was 7.55
- For now it 4.55

i fixed the trigger rate by reducing attack speed and get 6.06 effective trigger rate, and then i goes to test is. 

Test result:
- Old 7.55 attack speed (now 4.55 trigger rate) take's 8.5 sec to kill boss
- New 6.06 eff trigger rate take 9.5sec to kill bos. 

conclusions: 
- The new POB changes about effective trigger rate is NOT correct. 

question:
- why for now it's not count 14-51% cdrr?

### Character build code

```shell
https://pobb.in/eZNYzTXTc1fz
```

**Comment by davidank** [comment] 2023-08-28 03:46
just wanted to chime in here.
seems like the calc for effective trigger rate is not correct.

prior pob had trigger rate at 10.09 and now it is 5.68
`https://pobb.in/yK9IAeBAQQIE`

**Comment by Peechey** [comment] 2023-08-28 04:05
Duplicate of #6492

**Closed by Peechey** 2023-08-28 04:05 UTC
Labels: bug:calculation
