### ISSUE TITLE
Hex master not working

### ISSUE THREAD

**Issue by QuickStick123** [PathOfBuildingCommunity/PathOfBuilding#5704] opened 2023-02-22 08:18 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation ingame?

Infinite

### What is the value from the calculation in Path of Building?

No effect
![image](https://user-images.githubusercontent.com/31533893/220562188-90214f74-5960-482a-9624-cdb915f1d51b.png)
![image](https://user-images.githubusercontent.com/31533893/220562319-0b921edb-5d1c-496c-84a9-a3e554257d75.png)
![image](https://user-images.githubusercontent.com/31533893/220562417-c8eef863-6532-44c5-a946-2a92e6901186.png)

Was working https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5193 but got broken at some point?

### Character build code

```shell
https://pobb.in/e_qCFf-Boy6T
```

**Comment by Paliak** [comment] 2023-02-22 10:22
Caused by math.huge being saved as `inf`` in modCache.lua which when parsed turns into `nil`.

**Comment by Paliak** [comment] 2023-02-22 10:53
Changing:
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/7127369ad2e8bdf481e22e095af317461ed8526e/src/Modules/Common.lua#L344-L346

To:

```LUA
else
    if v == math.huge then
        out:write("math.huge")
      else
        out:write(tostring(v))
      end
end
```

Fixes the problem. I'll make a pr later today.

**Comment by Wires77** [comment] 2023-02-22 15:15
Looks like this just needs a ModCache refresh, actually.  Refreshing current dev with Ctrl+F5 results in the proper parsing:

![image](https://user-images.githubusercontent.com/1209372/220665801-84d29610-99b2-4318-999d-7e757934a5a9.png)

Still not sure what messed it up to begin with, but it's fixed now.  Reopen if you can reproduce it with a fresh cache.

**Comment by Paliak** [comment] 2023-02-22 15:41
@Wires77 When you rebuild cache with ctrl-f5 pob uses the newly build cache directly. It does not load it from file. If you do ctrl-f5 to rebuild the cache the value will be correct. Then if you reload with f5 or restart pob the cache will be loaded from file, which causes the issue.

`tostring(math.huge) == "inf"` but assigning `inf` to a variable causes it to become `nil` then during mod eval the value property is defaulted to 0.

This is how the mod looks like after being written to ModCache.lua :

```LUA
c["Your Hexes have infinite Duration"]={{[1]={[1]={skillType=79,type="SkillType"},flags=0,keywordFlags=0,name="Duration",type="BASE",value=inf}},nil}
```
This is the result of it being interpreted by lua:
![obraz](https://user-images.githubusercontent.com/91493239/220673621-767a11d5-5433-4d9a-95b2-a2d6a8a771f8.png)

**Comment by Wires77** [comment] 2023-02-22 15:45
Ah, okay, I thought Ctrl+F5 rebuilt the file and then loaded from that file for some reason (probably lack of caffeine).  I'll go look for the errant commit with that in mind, then.  I'd like to see what caused the issue, partially out of curiosity, partially out of feeling like the proposed spot to fix it seems a bit hacky

**Comment by Paliak** [comment] 2023-02-22 16:34
I'm not too happy with that explicit if statement either but i can't think of any other way of fixing it. I don't think lua has any built in means of serializing itself into a valid lua file like the mod cache saving function attempts to do.

**Closed** 2023-02-28 05:17 UTC
Labels: bug:calculation
