### ISSUE TITLE
POB doesn't count my weap DPS

### ISSUE THREAD

**Issue by BlejzKing** [PathOfBuildingCommunity/PathOfBuilding#5513] opened 2023-01-02 07:39 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

When i importing my build from my account, POB doesn't show DPS of my main hand weap.
I trying everything, also reinstalling app, create new import of build, removing builds files, check all things in configurations tab, check all items i have.

Problem is also when i try to replace weap for any other like unique weap. There isn't any DPS from weapon.

I installed a POB v 2.21.0 in portable version and when i import character, all working perfectly but there is old tree of course without update. Then when i try to update, bug with invisble DPS is showing.

It very strange because any other build can be imported correctly.
I tried to relog on Poe account and also change again to private characters to public.

My friend also try to import my build and the problem is the same in new POB version.

My nickname profile in game is: rzezniky

### How does Path of Building behave?

POB doesn't show my main hand weap DPS when i import my build on sanctum league.

### Character build code

```shell
https://pastebin.com/SPfRg1ZT
```

### Screenshots

https://i.imgur.com/kaRCWmw.png

**Comment by QuickStick123** [comment] 2023-01-02 07:48
Already fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5359 and duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5356.

Basically energy blade is turning your wand into a sword with no applicable stats in the offhand when it should be disabled just delete it and it will work.

**Closed by QuickStick123** 2023-01-02 07:48 UTC
Labels: bug, duplicate

**Comment by BlejzKing** [comment] 2023-01-02 10:12
thank you so much for help with the problem, god bless you
