### ISSUE TITLE
Asthetic Issue with new WildWood Ascendancies

### ISSUE THREAD

**Issue by CloudTekSystems** [PathOfBuildingCommunity/PathOfBuilding#6934] opened 2023-12-06 05:27 UTC
The new Wild Wood Ascendancy points are counted in the same batch as your normal ascendancy points, throwing a warning.

Purely aesthetic, but still should probably be separated.

**Comment by sida-wang** [comment] 2023-12-06 05:39
Duplicate of #6928

**Closed** 2023-12-06 05:50 UTC
