### ISSUE TITLE
Unknown stat provided (Trader Interface)

### ISSUE THREAD

**Issue by mikemcleanuk** [PathOfBuildingCommunity/PathOfBuilding#6122] opened 2023-04-24 11:09 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

When doing a 'Find Best' search in the trader interface for Body Armour it is meant to provide a URL to the trade site with a weighted stat weights search.

### How does Path of Building behave?

When searching for 'Find Best' in the Trader Interface for Body Armours I get the following error message: "[ 2: Unknown stat provided: explicit.stat_4215039317 ]"

I looked it up and the stat seems to be "# to Level of Socketed Active Skill Gems"

For my build that would be a good stat to have on body armour and for some reason it is erroring.

### How to reproduce the issue

In the Items and "Trade for these items" interface. Try searching for "Find Best" on body armours.

### Character build code

```shell
eNrtPWtzm0i2n1e_gnLV3i9xHPoNucnekt-exIljO5nxfplqoLFIECiA7Hi29r_f0w2SQAYJW5q5u3tnttaRRJ_Tp0-fdz948z8_xrF1p7I8SpO3O2jP3rFU4qdBlNy-3fl8ffzS2fmfvw3eXMhi9DHcn0axfvK3wV_emM9WrO5U_HbHBbBCZreq-DJDRX6F3yYyKUYqTc7l1zQ7SYO3O9cjtZ9FiXoHaHYsTyZBVLzdGcZRJncsP5Z5_kGOFbRT40kssx1L5r5KgoPFk7Pk-zTKoyKFh_5IZtIvVPZe0zGcFul5GkCbUMa52rHGMkquUv-bKk6ydDp5u8N3rLtI3ZeNzs4vPl5e14iMkorIm-ntNN6BUf7lzUUsH1R2VcjCyuEPkArMkrfqNCoAl4yngAg5HLl8DxHq2lTsvFoJuD_N8uJQjuHjExFcTZQK5jBsDzHiUF7-xV1AF5k6CkPlF9GdOsii4mAkE3_Rs0P3bNwJ_CyA82lcRJM4UtkciO5h1gVy-qgLZNtdja_TQsaHF1fzti5zOeZ7mBBBXE5Ww6WLKevs4eeoGO3HwOhn9KJhz26TqFDPBL5IozxNNhhfHbRziAfTOAbt69X2UuUqu5NF1CSrG3c69kC7n8O9c5nIgzRfzBFBq5peqAwMQ9GAsNcAXCk_BVtSBxHunjPXIsR69NiOp7Pr91Go-rd80qgqgKdS87xxHF31bfdkxM8j6BIsaL-WV-k07tmyWBgt3C1_l-p7vSVinXJzqH4smlF3BcJmS6er5VlSU5CVFNZbYoS7KbxLtXqvZ44xMkenFwsysesitOcSR3DH7vRbF6OHPPJlfC5_ROPpGAz-tfymkhoa4bJugb0dFQmYqy5o7DLcya3jKFPPAjxI46ALkHAXdRvAkUzzLkgqbLZKMxddYIFXhAH-a936LPEXbtldhfdzkhk7XgsfVvWgQS5BE3XA4sWqN8yim0qj-7j0srNblVQ9PiwmiPNVQO-V8kcnEOFdymJBI2d0j66y4guaiE1X8li3rvOYrXRdLTx2ewIsc0tAJIhcGznUhoDQWYWknXOOsydWQbWzrttCJyq7fbgaRSoOalrbbX3qADPiDuSkF6xhfR1BfQqI3a_LdnFiey7vA_9E9vwss6Cfu2onrHtMdzKvW2a82iZUzev86g6IFMS4ABCopeDb7k4k0q86jYifBjbMxum05lSF050KmFGUAPVBcLbOs5Tp1KUKpn7DlbmdZO3HkBYujYE4KwiL4zaQbo8-LArpfztMg9verDK9PB3iajqZgCXRU98XTrtFiOyjehzM1jf-CGJbV2NKVrnPpQ4ce33jRx24a8OC3sNYgnjUFV_p0Ze6eYloj-bLfXQr-ixDPwfLMAZXYFL987Rmbfe6I7hjyOfq-RZ2HAyp1h64EMEFWQnWnjJWGK--RXFs5frvhcwAZMfKQTd9ZT4ZJOSHdTWR2bendn6R3gNvRrpklC8UsE9riK3WAxxnKvntoTf-RvNeHRwlwTTTyta7j2WItm6uozHY5Tw_lIW0giow_yKzSCYFBiEAriuZ-aP3IFzHMo49MDFmLua_6m9LgEgDavxvXpmanf50Np6kWWHFMi-Gvp9Ok-JU5qO3Oz5FMkDEtz0WYp_JwFWUhhiHxCHSYYGjYFp9j-8Y0Esl4zHMzkH59WBWjCtxydDFjqTK85XtOD4PwtBhhDsBDwVXgaCSew5RpYq_OZCxnxsmnCWTaWElptY3jnL_V28ahrpip2UuM3XJo-Pjo4Prsy9HFd_qIEZcf02mY08XoMp_deGvbHmljIew8qmXlx_f7nyJ1L0R9UNVyCiGufTTOJaTXAXzSmIEH02bK5ggv1iBzbSCyH9W4mvHtWjQjenoh8oKGC_EF34WqU665s_XEFV2qGMPLWdd2HSVrBtR6dYO9OSb2KiDU6ZS2Y1Flwk7h6MfroAF0ZVxZ8_V0zWcKB4mKodgIwojX6vo6im_htZlqxV88X3Qbv9hxXxXzrkbhyk7diEoH3YDl6XDLujq6QqumrJlJ1fLp93gh8qXnWMvH3YDz8PtNDFV9XYs81YrMH1IEyPkoDTDKNaOtHNmj2I1b9KN8GMxUlnpnTsxnYONmjVZqThZ5E2LbjWutVjBK1Ml6OCQftYNWia_HWPQz1ZYokYC2MHQeptuVGWy1GnIVoGWQVUn_6oQbcUUVKlIB_vLpyuYMMvGOsZfPV6hJMb-Du_SKCjD9A51WWq2ymBARrI5GpNybI5mORnZHOMxRBXfOue7etoN_hmS1ah4aMFSZNO-SLRSbYZB69ZmGC6XA4kF7OXqEMLYr0MVKmD0SgM2b7NifotpcghOrlgxtz1RGbLaFWExtCfhKk1560ifjLEU0Kpyu0qGyyZrEIEvOl0R7fTDNE8QTyHk1uuEabwZwkcV6o3GmRa5TIJDXd3acKC6ODadALIZZR_bwtXFlC5jffNqlki8MbFbDhlrVpyocb7_ABntsfZOS6uU0jC2Cu6LMsuqw8y6C1Qop7H-_dNUasOi8-Xar-_LrRBJmo3nax2AapTea6NYYtShZA6-5v378skwLipkursZv0ruVASZYSLzW_Wj2dYwXFBtRmzojhI_ngbqLKkS-PkExNLTtOm9HbqiP2dhHqe6gKnkBOYB7Sxjnnf8lzdAXwV8EqeejPECdzlu5O40GqB5HxrTmQ6mk2iiMkh8dbngeznsMxMfGhbuWLdqrL-fQxoWQAb86qwAprzSnHllyIFPiyokEP0tAU8zR2WmY2l8JrU1rNHJoa4vzsj4Lxhy_t-5Zah51XeQeO0Yy6keZr5M1NU004b7qUOdS0sblr6jLGGtErj_-Ox1AwRnNVaHkOA_ewofY-g7JgNpGdByRG9KpL-nbuynqTbeGyjGep5-zLyP4VUBhiN_NlfbcPTlK8BaaWhV0FsUlkqUIdfS3lnGoL0xxFOzGOLZirEGYd9xz9FYTTzb58DHJI_l9HYEH65i-QAxwdVI70sLIGsaP2zAiZ6I-3LkLEnMdh_1O_CgXmSdU3ucpb-pZFMu9Ebdmw--svbnJY8_ws5UPhhv5oPXTcV1miUySJ9tZZbh-_JzBvdqayMBqiOdPOxLLbLPHlAHmr7jmoFbFfz2xlcJd7VX76rIom-bhBLtePoOs4K2KvA_TClOFaR1xe_sfT-o-7JqVdqPZ4tSK5LeQakBtiro_mLE-xpfmReQJpvq_SaGtg1Nncmr4zcDbZXg-b-VGK3Pbr5IyPrSuFDJ1UjF8bPFqAtPX0nS8FaJwCoxbN-V6_Wfj0mjTvJ8y9SJq7d1AgzW_QjGW2KxakWGDcWr7HRdhhA8WLPa8iaWar1PmGySOjehVyktaVimyZMyZMR6ypA5JuBLvani2bLzGEdvW2Sq1daRP3pCUNJ3aMMgUMF8v0kplBfxNN-kFLAOpd6v3K8wcK-1QwWWQWnNcVr19egtFXxK8s8SP1MyV4Fe2V1s19qAG-sw9k93KjzWDNEfyIUymMq3yYZllBvwYYZq-6GI2aangnI58tljb8PSW_nPknwSNZL9PyAKAbbcqfx3jkL0sTmVF7Ol2uemea1Yeid7JbRVXwveanE1CCI9dTL-5WIzk_oYjd6q3q92lMTacqrtVovMDtByfXSayQ1cfTuevjP4dyVBZLOHbY7tUEHsP46SZ9b-5vl6G5b-6Xod-pHmVx-vVGFWksoFJP3xOlNqtk5kEKFqjQa-1A-onpmlGtBwnec8VJtC3u78gzLGnF1ic4T_ufsPBP-QXdd1OHyhiGG8i4TDzCPicPiGEXLhGyPU2aXlZ-xwx97FhAqkoQRyxS5Htis0FEaY7VLBqcbBCWPuLqeOYP-EwaeBXnESxNGoHLorKKW7TFCyi23XEbsutYE0zgndpdCA7FKHAA2U6f4oogLvcuJytluSzRkTTP_ljvkMf6FfIIVh8zPDu8wlQA13KAa8FH7ABKHdikgXM2jNmeC7BLsE688OIKc2RrsYucAn_dQFBC6ydwlxoVNG4ScYIGZoV3BEd5Ftc-gT2KBb6_6BlPKvbYjDhhaqIV3d3AGSsCsQMNcmCMaPNdexTXYJAkYBLQ7iuwABtMBwgbqS4cjlejAwCneX2RiYaCYFEcqBIcKF3jARgIkAycy1bQ2u-Y8cBATBtHMOLIZxCpcAsAPj1INlevYcTT6zgfNEUIeboWieG4kwkkAIhe65-SQY0527QLKNNSupcIFNjCCYRGgN9DmY75aiAUMA2ij8A7RhTSyxbaDQwcjMNswbFQTYASzXjKMY6eYgobsEmAOyAC2BfhAbuouFZpQ-kwLTiCgGOWQOcBEzPXYsCExRKeLAEmAm5nrUIBC2GQFwBgmhxyH07MCUQkN9sgX-au4iGDHMKyDYJfBRAKuADdzW7UDmkNixClDA2slynSr5M4Vj1dro58v3pbUaFcUkf_3q1f39_d5EFqM0VD-iWO356fjVBIBAi18as_RSo301hP_2bz_vy9Fv_tHxbXC8__e7z2H-7f7MkdlPyuHZT_fp7SEj10KcjO9_eS88_nX86af9Bze4P5HDyaF3_MWX5CK9OkQ3J_TbD_xy-FLcn7o_j9_FH-yj4adTQm-OcvJweHt4eHMXJqk_HJ3nnPz4cTr8zIZfDj79_ebml-t9jyWEXtreS_w1_Yb3nQN2cIZ5SN99G_Po_OvN-HaSH8TphWdffMFHUvyaf_r87Xsu302PseeNjor37s2DrT58_2pLah__8vPL4l364WZ6fnfsXYUnk8Nz6ufJyXVyM_nyfSpO8aebIHVy--fbPDi-_DF5cPlN-jIav_9g-8Et_VKc_viaiakzOvw0TIYHw-G72-Gn_f3h0cmnT9f7w0_Dn26H0XA_HR7dfhoeXPkHF3dTfhK5wc_cvT_YH_5y_PHalb-OTi-9h-g8cn_5EHnT794oCNjVD_f27dvSAM9m7k15Vj-vnE75zVgwPc_aikDwVZROAs1901Izbc8WzWhXM2PxFu1IVzsti4tmrKuZsS2LdnjhXBZDgi_gL4xr0Q5Ff_iQFso80z_Ovhh3ozclV_u6IRR_uxNEd1GirK871m9pOr4BihnaIwSX36u9B7zab1DI4jAC75OZrS4zj6gb_gKNhLvnknJD9BvjYivXpj_PdkBMc1WexS3XJczPtc0Juml9Y8KlhLzh4bV1Obw8GryfgotNp7l1MC0GV2MJsfQBpKq69PeTulfx4HMSfZ8q6-zwtQVGUsggcEIJHHQ8pMD4gpkJqOP5IgTmK7A9YD1CKhkYfTDMYeC7MoS_yMaSDwwlZvivLe4OzKdL9f21xejgbDyJIz8q8tcWHvzDz2RYqOCfEPflFrYuSktglV6-8RjyoJLsZhvrNpNJATSzv-ocoMqYysrPYAUYsC2dwb6gf7WK1DKHRKxyx6JeP-gNjg24brVYvFygyQeoSusbOKwot8zxA53mH6TjSZpPM2Xk8zwNLmVyq6xM_4U4ao_tVBNbSXBnC7y2BVnbgq5tMTvPY4LBpuzhFtn76MWgKGkCspdF6eBcBdF03C1-TPqeT8EtgfsOBWVSikDYzCeEhC7G0sEh8UPPtz1qI24rFOrDEQykEYvAdVRD_ITTKX5kSfxYp_h1TqAsqbdKg_IkebXr8rrYQVPVOnrLHtlIdBtKo9N2y5yGrNbcLX2coFt6hypLgwcI5CN_hYxfqokCNNm_lWSvaMHXthDd2kFatOMwk7ea19MoGRzoNK14rBKCSOkrO7AVd0M3gGjN9YgH_3CX2L5QLBAQd3PlSpv6ro-wzxzhYQUWmUJq4DRUwqE1lcC8rhIIKMiy6QRk2NqP0zSwfJkkaWF5CgQlhGb6CVD7kE4HTZO7XLMckPpTsxxgTqAMXqDK3DarWtbiihrrPipGNVtaqeN5lIBQ5lYAibCFeB191eWc-H9xI0lbxEDfhwF2JIZ5XmshuSMFQljYDuSFPnFVGBKQAxW48Bv3kS9cHLjScRHhyPWkjyhVtvRsMJFYukFTHEhvC0n_HS0k1sI2hEaLsxx9YXEHBaUgb2gYQeyVHMd6y-uftnGRMjaj1hRSResKwgdwIO_1Mny3UkhGiZAeJ5L42OHM86SLbBEqJj0P4wA5vsM85BEfngiskIIM1xVgPJ0QOSp8rlI4nUqB26YeJCxTDaV4WpzbkEl9SvvJEYPWh0P1A5gIjO6Wz8M0e5BJNNuT-17leZqsEOckvc_1ZsVVEg-Psyj4MxiogB8LPHiwSa6sY_CjwKUrOZmMIhCXS_hel3VChCclClyPeVx4rvQcaTNEBKchwYh7nmu7rsOEL4jtBAy0gYchdZDLKYQIpCnrrCbrnHVkaDeQUFlHkKbcK5OyXOsPuTWSMMO4EQmUJdbBC-yWfl7LaC00fcFQUwIxqkOXpepH0UF5UBOQGvEdlzv5rfJ8W7WoMXjBWf2hjmcHLwhqj5BfEHtdGBKFOs4pFUDL8UgWQDLQKBPLbGEEfPqOmPhhwaYX1KnToE8q_YeJ8ooWztoWbrc6iBZ1-DnT9l9vwBoPPk5gkn6WSdBQBKVc5noB9ZBLqS18yBClz5SLXd8Wju9ySaRyFPZw4PhcBgHoDfUxaEaIbPuRIlQHP15b9qAyzq-tk5f7L_frKoI7VMRpaMGPsslCwIApUajlCsx1EhXToAxEcgsJLTJU1M25_sWsGIH1ToLZ9qwBshthdblhYuEAcsvVgIjaj-LxBcIBcjtCc-BI40mrDlphms0wvcD0kcbR1VETcGvqR16sSu9pbAF5TG6t3Qt7j7eqamUT_r_5km0o4CqO2d066rS5LAmiGT_kY-sa5jwAvcl8sJKZZU5pDBomGpRHDOqHkvdBSKqbtkBEQO32uE1xQ8O5zVwlbQzJDvEC4fuYBo7NPd-XhEvlQpqrhOBYuTYLbURC5UiFQbd9SgLWDOsEWmg4rqn4vlbxlyd1JRfNvHiu5MCnv-qDGZVWmRPw2iXkxtYv-4x3EPqoYOEnXnD7kXuYJcTHxtPXPBQtPdRCNWoPcUNTZ1fULHSs8kaIzEqTteznP0th2uTU7fQl-5mMgsFBpC8tUdZwPI0hK62n1l6IbeE5DmPKdhQhXLkIhUohkENMHB1C-aEvOeVE-J6DVBjYCrlB6AhPMNYUt3qlhS1VWl4gY6t1GpjcAmXazC-CIhCKpSjJ7jT8qKvUQnBLUfyFgx6LIF9Twv4zXjeGsSFVnz-cffp8NBiqW53zT7M0kwNwSeOJLp2-iwo1i0tLxsOcgwxVXx7bPSIYXjaWmLA11pIQROviS6krPO5JjhzbY0qvxvsewlKpECEqmeSuR7lNlPBC6bkhZcx3QKId5SDIg8lyobDVWp68vGzaykZAZA-Iix7LnZHvpXgd2WvE7gX7a11WH6USILZVUAKtzM0Lg-omv2ZXltKbUnQjbIx3RZLZnwzmugJtVpwWFFWm3lQly0Bslur_51tShFqF_kDPGTCyGCkwqak-7j9K02BwfZ--hDQ_aUlZA88RjkttIihxBHJCCNF9xELhu9KngWeDy4ZvkkDgjpkkrtJ7EKSQ1OG-8rtL2IR3lGdMynquCgUBa5Wu6skFxdyfZsah6hvoQSx1REus3Kyt5rq8fRoVA32tjcXLVZFJKVCQ8cGTuiDkg8b2JUiHc6tpqfVer0VKbNzxWVKA9Y5ulXHkdHUV3e2xRKMDBZiMRyH_QZqAKuiS_SwPr7AazuRlemEyeBP5-3NVMucVLXkLLABnUh7aMwyIQCn_Favsv5vNb1vPvJSTYgqx2slUZkEkk8GVHOu7mKzyTMvc3nPX6TT3zBYNwx24iiskKUMB5KjYpa4SEhJWhBzmCUcFjHDIckPFGWIcPEkYYrOdLAgDZSPcVA_emsiC1Yb_X9ZjEtYR5dKGDFdqchXL8SLmaI8tHlc_XlDRHt4i0lofQqIR6BTTxLgOY6Kt2T2t9RCXL9Drhkv4_oxdzDBJqxlfqvGeJXdRYezK4FTJuwdrX8XN6Nhh2EfSZSwEicRMOJjr-gr2QggpIORwMQuwBGG1iY09AnacQiRCbOFwx2fNhSeB6zGEsxQd40Z0PMBipZl8QTA36zyVHBLSLnOzot-SzJkKQ5sFXUrvBth5bCarPRwyebDMrUEza_-n3OlL85tydz48OTuAmDbQN2qCXZHGbpZsq8KJg2kWq_tGUOspSOVDn_GA-1gvZkoXYwgSBA2JjUAgCfFDlxLpUQ8T6YQeIZQz31Yh46FsSB2jddvYFUVAENsshZkzoAvzQ8EtZ-Vph2q6NflAeq7yan18Jhd9pKH3XLfymLXx-FplmS43gs8vd6mZ8sSc00dJkaWThzqbPcdFvi9sHti-Q5nrU8H9gIJmSb2pgAnheQh5XLqu4xJbwn-ce4ghKTjirttUbrudzZABNdisNxHMGDkc6-3hMyZDfHGWaP2c__JQBuzA3vfpfamPWoIKMFzj8RQk6aGs9OvlJh3SQQo9i-miUO-eCwCBrkSaJoC_Bfo4U-o3tRq8jIc21e_e2ts657xtzvW-AX9mzD9NI4hPo1gnQ_NpP07B5C1F5p4vhBKE8wAjhX0dfCMbIRVI3_cDiNJDGsL_AyTsQIASUtcTVEkaqjD0uE8b845EI2dcTLy7NO-kbkh1oGnJisxK1-bJmdnvIZerv2bZaIGhnLfdWeQKcUB5P-Yfp4WibUb0aaSXXhp06qG-XnFpPoQrbT-0KeG-DGiAVeARigLsCQ6_wU82CQnYQRwi10MeFhRhmB1EiRe6EjfNHe-ph6zhXx9povanMzWda2Omc49LNdZHqGq2DzTlD_N9rTPRVqU-nAK_r6aQ152m8YOWsSgZyyheBOuMdwbrjhDOcm0GMbKmNuMIV9Tn1aeeQzzHUSJADvJCxJRPmHQhGQ4cZWObuly4VDJdwgkkR8TxJGTLobCx62B3eYPCikq2_l89zidLq7otSSvtSlrLmxBnKloppzICMM-ZIbBijXDtBS7XYqt4rFmh7C4IcbFidRfhx4XLp-YKtSVp3bCttJ7_uaC0pRVd1FaG_5JmhfoBoV80AQG91fJXHsKcayK2UacmCkgpljWR4nWKiNxGri09hwUyIK4ADaUBkUKg0A2Uw21FIOeWEtsMB0y5ROHQV9LzpBco4iksGPLd5Rp_W679WAeZaOrgYmU0ty4iTbDeVyDnByCta_PuxgF9vNHR1KPK-5UqhRyIfho2rx0pi-7h0hdpZKUeL_ZmLhdaidu9FFVTL9NGj9hcXWZ40VwD1ucGFwB9WfCnQi4rZOvWe7stArlSqhiZjLYt_BhCHHwXlSl_YxWMguOhjh14yIdww3FsxoSCEDAUxEWMcwe8FlZYetwJJPUoFZ4PuXLAJaO0medz3i8E4fwJqUBb7G6uY9dD1dG72xG8zxq1pg5Lm59X4ZHGO8JX72EZ7v8q-tEXk3afEWreWRqnhTkYdeF9vnz_dmfV8bwik4F6VR57enVQ7cp49WWy73z5nl1Ndqp3PMyO0s8Pg823GmzemXP590_K_XL8ZdbZ4nbUWXeiq7cZiNmOYA29hzyXs62XFlsgsNciUHGxDI-fAF8qHalxaC3Ns2FaV_dystw3fULfc0QbjH92G94WcLQPiG9hQHwLA3oWjrYBoadIV5t4ki1wBG9rNE-Rt3IlZCN-tGgb35iCPsx4unk6-uJg9svlKWt2XtN0_Dxyybbmjm1BkNAWVAttgQ76u8zh-28_3zg3eJTUBbA2g2Qj04Y3tQR0C8x_urOqiQ2iGzGAbMoAvKHteBoB89vjNhHgMiLaBEO7VWAbY-DbctloWwbq6bJZ6xovQAy2swDaL10-UIKW524W1xHMMD-Li3RjWWDbEcrfx6tB0H14eXfiz4Pucrfkoi_3uRacbMGYteJomf3yhor67C_urFie_Rbw6kqKOnztlooeCKpLKBoELO6l6Cl_bQaNbmgQ0XZk79khypMVvjZgxPuB1BQDsb7U1WCexVi2qavb0szQbdnmreVD5Llu5wlwet9hYw7RKu0sb5KpK-fibpmeutlu2fF25nBrjnobiT593phqc-H0mr2a_PPncX9LwR7b2MFvHiLw38W3f7rhk58uxfS-YYgWXTnPMlyPaS0rlLPL-8zFRubFsmkSRrePXhOr65am9P8xgRa58vVCRVDuPtyxvDSNlUyqm5Mev2TWkxp68ULaYRxlsqXdYZTrSwmPTi_0Ft-PSfXGvnXoo9lrOGbv4zCXHa6Dmg_JbB-uNp6UK6uLF-ESuwVymqulNyY_q6-ngj2L9UDr45cv9-53frDWEDA7K7UegdLNT2U-e-N87V3zM85ie1XH5ems_h3CMJvvyF4HMJFJMVJpch4laXaiXx0-E86b6e00XgUhvy5BXI_Uvj609A6-reYmiHMvCWtOfPWOmh56Ng3Dxluw2gAu9EUmozQOVFafrfIlxHOyhG2vbl-ud16mcWwWQuqQqwFnrmfWHgnMndUgeoNR9T7gORhbDzK75voRqztg5q8snQE4xFlD2UzAl7tC2KWzN-xVFvXNqwtwAB9D81ZxkJS_Df4XMNUqGQ==
```

### Screenshots

![image](https://user-images.githubusercontent.com/16876798/233979439-a216e2e5-aa41-465c-a72c-f6b81ba53f17.png)

**Comment by QuickStick123** [comment] 2023-04-24 11:12
This is caused by out dated trade data which is fixed in dev by any of the recent commits that rebuilt queryMods.lua
![image](https://user-images.githubusercontent.com/31533893/233980090-61df22d7-ea90-44c9-852d-30e75648d3e9.png)
https://www.pathofexile.com/trade/search/Crucible/DnEzOdwS5

**Closed by QuickStick123** 2023-04-24 11:12 UTC
Labels: bug
