### ISSUE TITLE
Crashes when importing item from game

### ISSUE THREAD

**Issue by dc1wh** [PathOfBuildingCommunity/PathOfBuilding#2617] opened 2021-04-20 10:10 UTC
You can get the latest version number from `CHANGELOG.md`
VERSION[2.2.1][2021/04/17]

Please try to fill in as much of the template below as you're able.

* **What happened?**
![image](https://user-images.githubusercontent.com/18496163/115378338-bfea3980-a1d0-11eb-8a74-b6e862762b3d.png)
Enter or Escape is not working, F5 works

* **What were you trying to do?**
* import character from poe homepage
* delete all items
* copy item from game and paste that item in PoB
*  click "edit" to change item from unique to rare (item is always unique after paste)
* error as shown

* **What steps will reproduce the bug?**
* see above

* **Does it reproduce every time?**
* yes

* **Provide a build code:**
https://pastebin.com/Rqn6V6QK

item i try to import (ctrl+c from PoE game:
```
Item Class: Boots
Rarity: Rare
Dragon Spur
Wyrmscale Boots
--------
Armour: 141 (augmented)
Evasion Rating: 141 (augmented)
--------
Requirements:
Level: 60
Str: 48
Dex: 60
Int: 134
--------
Sockets: R-B-G R 
--------
Item Level: 61
--------
+31 to Strength
+34 to Dexterity
53% increased Armour and Evasion
+17% to Cold Resistance
30% increased Movement Speed
```

Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by Wires77** [comment] 2021-04-21 21:31
Duplicate of #2954

**Closed by Wires77** 2021-04-21 21:31 UTC
Labels: bug
