### ISSUE TITLE
Nonsense shown in tooltip

### ISSUE THREAD

**Issue by ZzZombo** [PathOfBuildingCommunity/PathOfBuilding#2846] opened 2021-06-03 13:21 UTC
* **What happened?** Nonsense shown in tooltips on hovering flasks.
* **What were you trying to do?** See what my flasks are.
* **What steps will reproduce the bug?** Hover on a flask in my build.
* **Does it reproduce every time?** Yes.
* **Provide a build code:**
<details>
<summary>Spoiler</summary>

`eNrtXelz2ziW_zz6K1iu6q3diuMQFwlmk9mSz7hjO27LOXq-uEAStNmmSIWk7Dhbs3_7PoCUREqkDCvu7umtnaNbsvBwvPv3AIJv_uvbOLHuZF7EWfp2C-3YW5ZMgyyM0-u3Wx8vD1_yrf_6--DNuShvPkS70zhRv_x98Lc3-rOVyDuZvN3ifMsqRX4ty0-zrsgVdDURaXkjs_RU_JblR1n4dutkmoo8LrYsX6RhXL7dOstSuWUFiSiKMzGWb7f2pzKJi3LLEkUg03Bv8ctRIsJYlFm-ZY1FnI6y4FaWR3k2nbzdYlvWXSzvT7MQGh6fnn-4uGwMH6f18JfT2-xGjMUWLOFvb84T8SDzUSlKq4B_vN0aAifEtdyHFtcwqzuRTKE7yglh7o5HXA8jF2-96iYeTaQM50R4xyEu-6PbnufyIIpkUMZ3ci-Py70bkQaLlRB3h_aRdjXHO8hZS3A6Tcp4ksQynxOhHd7LoncrQ3Cnr-1lVopk_3y06Bi7lDNnhzkIO5z9PnRZOaez-1p-jsub3QSE0hzFUEkU7fF1GpdyQ-LzLC6ydAPi2fqapL1L3JsmCRh6sy0jru3sUFA-ClzkvZTZ2I_TNm80Kd0xJR3eXT91cXtZloTZfbpYGWhhr6hPRSr2ssJA1CdxJM1aHozM2l2AZzFrqWZ5LnNwgqX5ZJ9EMCrzhoy83inLr82WiPd2uC-_LZr1ew7osNWS9sr1OF0sAyFnTYfNlh7rn-BdVkJ8MmPmgjmYOmvcc_BatT5Og8Vc-7mpmn5Mc1nI_K7h19cN0SapRbwYy167iAt5LRfr9cAOkUfXEZxIGdwcQYCFgcBhN-ROnB20TlvnTR1sr2WXatxk11ob6GCWR8wIVli11iW0OYXsHW9d6z42OY944LY4-A52PUo4XUt0Jsv25Ljr7HBEIaT1Kg3QrIqfO2zHe5TuacwAgoNU5tcPo5tYJmGbsN9fNkgWRuCuVZsmTcvajEbZYGJ9Mu4nvhNF07243iMrqtqb2YKEnAMIQrmUQz0jxXme_aayx-RpZMN8nE0bsYS6691l1b4lwn6PcX7zUMQBWI7Oyi9kOA1aLpz2OoN5Knya3ckxOAKdSgNGaGTTxOmd6m4CCGM5X12X_ifJ00iGZSmC2_0svF7mNFs7ypMoDuMcmFbEjYTANWj8AaDQnpgssIDXn3sp2zIcYNF4eQCE-oPS9U2ZQjpqPMoShflQwNSsWBqGYIPWy0P0avMhZNYtdEJdxF13ByMCqW6_2dzGbbpS-Il8bdnfsOO7JJS9WfV5dg9Tu1HovFisyaT1qfj2OMFhLtPvD8b9t5obDXCQhtNcqfryGLYpRXOYXpUZakcB0VaOT-JxM-3RFG9e6YKH-nQ8nmR5aSWiKIdBkE3T8p0obmA-kWDSd5FLbd9mHiHUC93A9h3BqXCJj0NOHUe6W5r0QopkDPzeq76qqYqghDCj-6JIej4XHg-wE9gs9EPEfeaSCPmY2w4SYegILEQ1tz2RBIVe1nE6mZZWqssl47gIrvxpFKmiyBYsM9dFnYPDw4O9y-NPBzUnmiSF0rKrdDr2FaCv_r3g2Uhqx2sFWZKISSHDt1uRSAroOw5rDR1BxAlKo_YQT-s6i0nrzyIP8hikb9JYoXijKevKiklLVeswagjKIRJpzrDLh4lUWliY8qx2-yatdY3CqGVVVDBboC5emIlBBuLBqOU8zzJqfZDIYZyoeG7GtVMwhCoVMGsPYTmP_WlpqG0aKRrNQ0EkowU2c2OjGVf5l1HfdYZq0rYOhGa6BomPsTT2ZSRBiw2tWXuJS3Er09oVz_zdG21ChVWAPz6S42L3ASLkoeJaI862foS4mU-h31BGYpqov_8yFUlcPkAqSJp_PqkK2xhBBzfZ_Wg6mVT9KIMtAPR8uDgdnlQ_DpOy7kWNUw9RLUzNTxerq_Civ-vZq7hixWmQTEN5nNaTnS87Eb4afcu6VtXtPRVj3m6lcaKK8yruh7N1FEmm6oJSTIB9yBrdqxRkaTw1lJrN397A9OoOjpLMFwleDFgvd6v1O5oPo_o5Vj6r4sMwDGMlMZF8Od-yvlaLP9YmrxkIE5dj9f1UliIUpXh1DHG1eKX482rBy85uYBb2yjqDigXAMxWoFIZQVpKoNK_Wiv_ry3vzSgvzL6lWniHfL_Suy8b8bpGrzNqIzxeLFOQvzGL0KI_fyVwk4YdoeJ2lD0_mcje1MZMrciuLrKqDvz6_H2P3OeikSJ6uzYoePi2RK7Rjwuea7MfZWw2xIXd_X0X-JNNrWdU-GsyFICzzVJQSGfF3tRNjx7wgffVsa6qdWJXqDK-BewoSwo-q6L2xQ1zbnalKvXuYZOWNzMexMA-0tuGCdYWyXeD7gfWu6810uboPa9aJ1YSoz7nwi2l5k8ii-JFwt9yF6RLnhM--qt18Wuqp_MCyVvswXdeC8vn1VMTjH1HMJrmxJiqiP8mT72bhgzWr6v8AnniUv3tZWsggB78dqjNGT-ZxH70pkxv0VtWBntppnOpTTKPpeJyl0PeNSEtRjJ9fsw7h_3H0Iwaz3EN76fW0utY-I3z1fyuNf86AfCgKSCuqfZofEVFXN6YqWhFbFfXv4LSriuJlVpULN19kdz_GhqiprTKzGmXLZxHlUFWaSsAfo0SM6-n-iCzVbk_0WeRPFyRQKgikaI2liExDbwIDVgn4DyxudJMFt_firpUWE6PVNUgNXOifgP0u4vTawk8LZ3Xw7FW1eiYLbCJEMtc3tWdxE8voyfJY34upuqlerHk31ryfP4v_72QyluUPYUPnMWP4ZRrXG-obI-99UTw9jdBEj9p0wy6WeGwel27jEqKBn5XFan-6qw2XXZlpq_sn8qDqweqbYXPu6hTAMwayNuQbTnOxed0lj8Ong8aK6vlC1q7MC5nfbryKZXpjBFXTma6E_msU1IlZvrvBhsGj0XeYgycLZkhp83rUmbzv7Mp8dRW51doK_GOcfN1yxa_jrX9hgzDMap5qEX9GiDJcyiJG_QnBfzfT8eD3rAtfSnUwRySAJOK02Ji5Pd0Yl4dn9FbdwfPjNcCDH1J9IuUHwNpqJ8ZIDUitD6mliHWNdFTm8a18RhPZTbIs3KyKMLP3lR6MQ6CitJ5WTeCPLeginmQA4jdezjK9caW3pvuzrB74cSe7zJ4Ymz17jLcQOQFaFvJimm7M364-jHM_RWgpyuezdH2CEeDqXv6w8Zq6-jBd04zWUsTP7sAWadzisa3NKxYyyNLwc5yGT68ZVrSWJn6-VR4DDFK7sGBOm-__dnZiKr4ZsaWp_wDjLyDlDNSDt7CQ18h7fSCuE2ldiiRLi21rJMo4tWa-4GmO4vk25A_SQFWg1LHBD9FoEpfy841M38Ul7RbSkzcSxmORhqp7VePTAyyzvv6kj65d5lJaolqq7gDXR8bgS_PRZzUnDANloTp2hpnHtwnGlG1janOyTbGH0LaDuAN_Z4RsY2Jjd5sgD8MfHM68bQdzbxs7Lma6tbuNHMLtbWwzhraxi6i9jWxGMXwmNtpGBBoym2IMA9lAT10HvnvcgSEZ4dsYQwOiGm87zLXJNmIU_kxsx4P-qIcozIQSZxtRD9pQ6jnuNgzMYXzuOkCFiUO2CcFczcWF0TiHbhwH5qK7dPRnmBD0CytysAd_dxHXP2L40fGgF4SAF4g5BG0zxLAaAuaCXY_ByDbT43tkm1HoTFMy1Ro528R1iOIIwzALdf4ePnMH2nMP-sVYrQl7wE1gJvK8bU4xrN2zCVVrh2VglztqRhRpPniwXsz5NrU9292miAENzBH-QghyvW29FkJtW__ZU5_hCyxADe3YXLEBKXYSzmy-DWLxFNswLJV6VNEiGwSG4J9cCRIpFrg2sNnxKPTJ4AdYFIc-gd4BKpeAyJHDKAWWKzY7lIIQOcgClkCANwwo4UeXYsUbx4O_UJi5khZ0Bh8dDybiwcKBt0ytkMHaHGyD_lDbBW5BjyAoRlzgMXEJtFTPV8PUKAceczU2p8jbdokLA8G8gJDA5y2rBNVv3BOgnHUwU3Va2_sBhAgZnimtrz3zx4sT_eFvN2U5KV6_enV_f78zEeVNFslvcSJ3gmz8agLdgEW91Fb_Ug30agj_2R3-sjccZuMo-iQPHBlxcX_2_VP6PTqJz19-iy_E0ed0cnnFPx6EX3f3bqfi68fDk-ASR5fFLjm8EnsnB_wyjX779dP79_7-ZJQ74cPQZ5Sz6d7uvThh_ll0jgU--s292__NPj_cG578evnOPZteO7fh55PzX_Yud7H05dTL-G02_fzee_j66Wt0_GHyDfzumX92LT59ufotDuPowfn56vofhfhwfPmPm_H-_buX5MtJ-P6zfyY_5-_z3d13SfYe7Waff979dJWMLr-eiun0Ag2zk4foaOTefvwUfnSOBPvFG53n-KGIwwl--CzfF1c_76bfnel5eXxzG7h3l3f2_fHn4TX99v1D6nyY-Ndv32pGv5px-k11w0JRsb3-pj2RkhRysEp8QUw6mNVPY3S0Q4jZBu3AhxFq0o4yTgzaYex5Jv1R0EzPpD-CkEEzD1TdoBlxHKPVYg_M3aQdOEOj_sA_GzRj4HZcE-FycPQm7bCDTISmfd-iHV2zDNc2EprLHCPlIzYzaWe7xKQdBadsolQEIqGJPAhyjJQeIoXZsC4jRssgnkk713NMpME8xk24B0HVIUZahRwT7mFOXZNxdZK0aIdxf0PkmaiVCqZmvg9zE6_BVM5jJF-Pm_k0M6-BXGykzhSSHmy0XkiETPpTeUhDIP2-3qVGschmxGR-4P2MFBBSODMzp9TIfCFV5mYxy3W40Tqgock6ADWYdGdD3moSA9Vj7wbSgOzYNoqVnpGTBPxh0p2GBYt2ZAb9XzXSHfgCOGwByMq4TKSq7S5dTLUZOtNqWCffNUZjKqXW-XKVS0MAcfkMr-nEXzXBddZd4TUCQaZOt-FH167xGnyG3nsQG2AfQD3QBNJzE8SmQc4KYKuhC9NoDv4J61WeZAbYoMc5XqtQIsCzCh3UeE3DSw3YKnxSATZoCKi1AmwKdVYQtYJrFb6pwBmkTp5dQ68KxlVwrYIwK3Ctxrsa42n0VOGjJlwD6KegrwayNRbTeA0RhUlhPSCMCp1VqIqp3L8G1QwzxRKFFdt4TcPJCtvWIKqJ1zQGrPGawkU1MFPMok28ViHaCq9pnFsBXwKZCKnhWgXZNVqrYOMqWtNFgBqs6dpABctAjrjCahX4r8oBFVrT0PhfCa29H43YL_TKPf7w4eJ7_uVh4nzMP76nL9-P6Idfruz76LKM8HX87fYuJBQfjuLxvfPx68s0uD4Qn6IP_vV1cBRfDaMv_m50fj92FVq7BLT27fzXk1_9h-hs-tun-P5d8PFAXu6yD9nn91d0mF799g9WPnwNR-cztHZ-9S3jNxmdXmCN1kbhR34Zk9HN2S26LYYiGX8bZmexJ46-nH25Oru7_-WCiYNsyvzzn__BNGo7-hVQ29fP7Mun3dspOzz49vLlzfhwb_9uP70-y_H94Qmgtvz91xq10V9vw-Ob6OQ6-P71eHj8effr5HN2kDpnjnv__6jtr4vaTGGRcWJqittM8URPrNwYt5niRVOAYppCGGYkzw3bTBMmQ9hmmqb9a6M206TUGLWZlj4MQZspGDMFd6bJvyloMwUdpqBtCQSSHwVFpqDNFAQugTbs_CgKNEWppmj7uVGbcVnDtLhlWLQyLYKZFt-eGbe1S5ezq_x6cNubV2qDTX04y0qpf1N_nH3R22-fYnlvFVKdix6V-dstX91hYQX1vVrfs2z869utl4x7OzbANg7Iw7VpdeXDOynKUzGZbQiqtvWNEay-MKIU5X4cRTLXF100G35RYYvuEEi-uU0Z4JLqWgu9C1xvCarPI1ntMU4LWW9y69P9-s_V3md1fw801fdkQODXDLkQeVw-vLYuhhcHg908HhdllkoLqO9kPjgVMinKPBtbMMUoGnxM469TaR3vv7bCgMjI8xzJCRGch8yXIuKAPuBPAFGw4wUuAowShQHyOQlCIRj1XRwyJwT04Q30VDQfXluuPagvxXhtYXtQy-i1dfTyYvbfgW56Ib--thw6OB5PkjiIVRs0eIHZT1bzkRAlmeoJmPqRTOv-BmCEda9u-1AnFUS9nhdIEeie9T6sHleGVvVcp9pjHyD-k5Wra-Tgz_O7XiyYxzTO9TVxxWAYhoWFiOoK4-WnQQfI_kntkudSFNDF0jmoetqD_w5yEcHI_0Q2bTZf7mzeDkOvQWPJcRpaB6kcx7KwstS6iUut4IrJbcE7bbmfDo-O9waXN3FelA_Wvgym-Z20drP7pqxtAISh8B038AgPI8Ecl0uXOgAqfUGli_xQwD8cAVEYY-ZjTFFAIuR6nDDArC1ZM7SQdUPUuy93rQvrCER-1BA14U1R2wN7B9gDkprzpS1mfTUQsE0Ulro_p4cFkB2v6v7nHPCmdZGJVa1vaarXram7c0096tVUshBf3YcVZiCvNCvnIu-XOHpcjayJzC1gUN37DxjG0ixgrcx9yRC1_l1Mr5XWy_A_BgeJNoBGK-clRIVWm-6Jvrb4jkN-arWsH1nTa6hcGNj2DuWtRvWlARciVcMhMoBu4d_w4Tgtqw8vCFWLhR9kel3eDBDh6yxKGy9xFYnjdf_qqB_VwuY3Bc5-xvhJtt2aSC0Hfa3YQIWa19b_TPIYREV3mCW_iQRoejS4y3mfZrkfq0lk9-lgJMbq5i2reoymacsoijAOfOQxBqk_wRGOWGALAgg5sFWSKgMSSukR6aFA2K7vESokuHPpRp7jOW1rcDtt-ejl7pLLZqztsuc8md-PYN2A0ZK2r6wPfIG3DTIIRw8g91KCVttKICBwmSTxtQqZ4Mi10Kvz7PANeerrWHyLx1OYbRyBH3abfVesU66kiqRRNk1D0B3vJx0R5oKubrXScmyLb1ROU0uA162sajbFHoEh2hlu1enR91JOBmdqwLHIwfWKIojTtsywDCNqS2Z7GP4naCDAFTPfDSKAgn7IEXF8xNwIYmsQOZjZUUTB_UY-j3wn4maxFjzXy7bzddy2831B7SaTCVbf6ivClGiAX4MXnrvCebDIfq5eyEjdAqisbMn4FEkViCtTkXmx0JsXmOs-1cNBze562M_b7P94dvzLxwMIe8DfHCavHm7OZVGAu5oWIgQPdJ4oVWvIAKwlcAMIczS0fQDqIsSh70Y8hFDnBlIwgQJHQhLkixBSIrCfELOQhMijmHvMbcmAkz4Z6AiybDzekhzQY15d-VBmL3zgcmt9MeyscVxYH9NkGtw-KMPBLefptbKRWvIqo5mlRLPLcms_NiP8N3DTxX8WsyF2s3RaWOpiESlC6zoXkDZZpNm1FvRy2NHrQI119EjX6zCu5qnCQfNQYVOoxEa2C6kKkogKO7RtGnLKKeQ5APtQGOKIRFxKbAeSMBYyKWlAPMGdkAYeR0HbsJz-JBaym4ZAKerxhpd5fH0Na-46HwihWqbWO0jsXlCda-7Lb6XMdZxHqLLMANI3ETzMjdGlK8Zo7-AnpVAvVKbZMl7l9PRltg27a1imDplMkfAui67DfF9q1uUnT2NYFAjzKI8ng3cPYQ4uUqjvYpqWCfC4hUuEjFwagjlCvHIFkVggbMN3EnjMByl6PiFSeMT2eBBFQUgjm_k-_DsAuBKwtp3ifpEerbdR6rZlhJze4P_CZas-c3O2u09nO-_g-nFae_bRBGx-BJabQIKsH81pmRAlgkR2wH2fEURw4PoOd7kvA4kx5AzcxoBcpUuQ7zoB4GMWMc8F8AAuNIrCdnbt8D5-r8QmvOwTWWc04h2cJZqz6vbqZuR4gavYv8zjgUqiH4_7C2TWcplL_rFH61FveBqmd3EyGKq7da3heJq0EwPA0sBD17EBg4PL8hABhrsBjQCAQURyXQFRiUP84Q7jkBQgCa4tcOEDlg6QtZlPmy6qlbDhhp4lsG6IjYVVPfwyiic3WQox3m4FDv5IiGoFkZY1NH_QTw_VRkJt1Mw-ABgocVrqvipoqZ3jQzatxgJhUu2--n6uVGCmF-tnOs9QcJX_ENvutzBIUhT-robpCVeow9qObrJpYl1O83RwMfXBgyv1bULw0GMCu7bLXTewbdfxvYg7InQAmjvCDR1I4p2IkYghJh1bcAG2B-m9DALbl8RvS5o0PVdXNaXLPkgrNdA20MrBtQfSXg_hdS7oBWnyvrq-1qrur1VmrAcXkJ4s4GXT4cE0Oqe3yAzZatDrFkR_GUDL4WNayHJFECEKAw54iDDPcUMsKY1cj4gQ-QgSb8gfACUxScDFeZ4N2AnQFkeuglaEcyTksiAWuV9TJm2RvINgjOrqFEQLuyPDdjuz4ZlP68y8IRNwn5QJINQyOVDz93GSLIUgd8PIj0gXQtLPYFu7MWCzEynUzXLWrkzaPhDiCxecIWn7AvGAgywA3UoqwTnaYWgzQEAy4Koei0NlKYgRl9nSjtQN6e2A73jr6oxkFVW-4GuUmZMOSTk91uV0SnCh1rVl6AbduUBPcCFdFb9zkcagTqG1H9-BNCvBHiaiuFUasacf6GqFeYgmdoQlcDqSRHKfuzYD5UbcJr4PGg-stKUXClUaVOeAOIQlHAri2JS5iLczZdYK8w2O2-2orlzRPEiM1YM0s4ALEeE4VQsvF9UB7eRBK0-y-4rZx-PxNNW6V91ZbtUPqlXrrG75Bvc-VrBg1gT-Ny16caTbxcs9MS3jDADOO3Bb2T3Mtc3NUQmJanCzxFGGuR8gB0ccSxQFnvSxLUgYyiiwA5tC3irhG_UQizw7dHHg-D6lACaVnofLRdU-jtKlPAnZrRLLI7xTJZLZJUvzHDTL8-lEVcmrBKDFU9nm6VrC9ZzGXZwewlJ0iQRy0QV_AfYAegTHDZlfk8ORF3pBJBzkCFBCx8eYRUgS7IbUJw6hAhJUD7wFcfyAcqJ0GPx2hDxkMwa5Um_Zus1hezkT1fXC00VuoV4rsbQN0Mx4OjnYw5XO6v1oCiNk6Qxzj-IERLpgz6FMw2XdI66qDckIQ84eSJVPcO4JlRqq2j1BmEeuy-0wAIAcgD1zL2KAdzGJhM8xanGGNkESbnAG4x6YW4ewJRbtWC91hlfexEX1Po1KK0FJwkF7v0NFIEvUS6zIFyleCEgFflyqxlbpyfsUgqivWL9UXCqeIAVsd3pUmU9kCYyw9KUNxZIU1CZgq6bHqevxELm2YLYPKQKg0oj7xLMhy6O-54KIiAM5nxMhhxKKURBwJBmFlI47YbsOSxsSaO6etDWTtqurFdvmAKZp8Ie5lN9lHWbU85_rjHyl8XrDtte6UAhvWQHmbeRC7QAyYB6GkJH5wnNQAGCUBhBuwL4lBH8OWYCIPM4dTgMcQeRHPnVlSEHhESQDLR6SVi27wUT7L-pBu9LbM3mvC96DEy38vWSqrwv8Wd7LZLBXmedrS20_D85zGcXfXlv_nevNFnuH_XMYRcAH5WbPMv1KIfUioyTLw-XGqNFU9z0aQ2g8r05wFkeq_qdYhK_Ad0WPjnIq8jIWyXkOsbUo5iTqZcCD1gos_cTsa0vMe7gai0BeAe-uCrWvdRVWkK5NpY6iWvoJ5dcW71aCdmJClnJeSHerpVUTaFRlsAUN9G2hzd8tVeivZ1yl_60OVZVB8WuZStdNX1c7dAu3pbwdau1Dzbb2YkAy72DCWndmL0EZPD7AKfDMynJrFMgJoL3fZSiRFNlsvBduMxpUmzVdfFOV6loXrJky9Dacq2aPD3fWWccp2JwKTD9oHp_j4ibK8n2FXK6MKD6pb-NTcSvz9abRY1Wzl4zhVWrC3Mfp9-U3_KhNBdO8kFe1o-o3JdZtSoyuMyXWa0q9khYtU3qKJbV2ICo4oIINJBG5gkCFNFdh2l07NCZfKhb3rbXSD6tSkN5WSu8sUDxLa16PBXTh7dEkhm_AyQRcwKCadtsIWkkkRwKJIAxc2-MUCxqqWgiXJJISkIorUOQLQDlu6EeBD_oXuSTikHd7kWTO0q4k7lURvKQipFdFHpf4YztnxgJrb5OtoboR8LldQq6BZ6_4LjJ9wihOQYSBroH1OTHcIUNA9iEkD6lyYLtJDD7yEwg1jEW6KkI7wI5rY9-O3CjiQlUMPUxcG1EqI5sBzCcCYQBGniuJ5yFAB5FHKfI4wYL47QTKXTqrg1qLrm7aWDlg0WrTrpQg-5FSIGtCAp3Zz49A7SqRrj0H1VWE3RN5rnYPIBMbS3V0ZawqAitc474fehi4QTAgJcgovTDwPSegzA2YTWw7pDiySQRwHUfECX0sPIQhL2V2QLwlXEmXNo681fA6QGQpcc9mO6uD3l2lKiZf3mfWO6UQszNt1QEaiJu4vbErxazHbnZ17csdjCcPQJjO_EVXTtk8ecKlFAQzjKSP_MB1keMhR1KA2m4kPYI4ZQED1gbAM_AVAZUiFIgwrnhLg-USkmlI8f7Q7KwT5z_RuVDzfAhg5d2DSr3KdQEBwoZGV6NbWJYu7fU4lA4pH06Ta72BpQ6GdmdGzTqhI5CDwX0w7IaCMRoFCDvgYKJAwD-R6_iOzT3XURsWEYsQDcCPsACiiBfabMWjmArZ-SPzhjraL9e4FQ60LuOxtE6nSRnDXEEmpjJ3VmRuSKnfVK2qX9Kyd5Au6GvsvDhH168X5zeJ9LMyG4NP7VGJrrMVJ9NxnCp9Os_jYrzkKJeieqsCRFecDsx2kXipy3hn8us65NI6ttJ7pLfeClk6jLcQySOe8QVCuoM6YPX302dDXZvp1a4lLEgCo4fVHdvVEaNuVHGSwZDHM1b1vNS62uRmq8ACs3_qDnaBuBp5mIZKKci87bxv9WevC2vMkhu2_CP6Z-NVxqQNx9ecalo5xb1cHVwM_eLf-UuE_-PRncD2lvMLzN3WIUDcf6xiJVFXzwacqlsgYQ6WnsnbLZjKVp0r1HdzzaU9SrLZa3AX77GaP3Qye417o1VV3Gk8EYPwaqPZxWbzNt5qG7X91WhB-oZqPgForzaa3a8-a9M75ea6egdrPNCCnL5GjadoUMdwS29bmzXt6G52N_-sCevgUvOVNPP5856-mk-KoK7O9HW0syYdvVQnMxojzXqpH81Y81hGMxntYofihjX0H3RRtH7IpeO5m05OLpFhM7JVRV7lxoYz6lrMI7NS-v5Ekl5b65oT7poT2YzBZlzAz0RGN5uks9lohmRd3ESPSLhLoR6RQOW-njpQhyo5m4zziP71uXGDnsnmdoQ2WQndTBnQZqpHH5fPamjrYO1T--1SsA1XbuR6OmLv4xPawA-Sx9Y9D4JPFGA3mzfSMLYJkZFVriQvZtmLwULZxnzFG2iis5kxkc0UmDxdzejmrn8DpUYbM5-Y2GZHqmqWqz468R_IgQxlubkcnA30cnNB_IDCmLrlNkhYazedeMJYNI9wrgeLGDgZvDF7N3QY5vJchUwG6yEGjOoAWsaCoBvzi20S7EwsZgUTGqv5I1PqxZOvakCpLy3QTy6qT3tZGsXXFeBMJ9NZLwpv6rvz9Ule4P-W5WdZIkVa3zDwaoXkMlN9zt7Ct2WlU_XkwaIC0mzrT6No_jrRxzqez-VD2niL6lGuHrt8ArXa33k4ze6MFjOel-rOpMj9h3pzaLEq3kEktAqpC-6niT5ReJqpd3wVpSqbg2Q-HVwMjw7Wjla9SmQ2CLPXLUgXNmX4Li4P82xcFdL1Io_Tc1GUyB7J4An8UdXKCxnItEwensrW-Tu_jcnqyZsPKNU4w3txK9VhdF0LbDCqg2BayMNcpt8f6jOCT5iculRDvTdCvdFiNgTuIJio17FVNeiFmE-HX_qmf1zsZuo92rOmozifFl36oKrK-3V9cf0ql9RbxGP5ZKPYyK6aOjuetNQW2Xa3PM6ze5kbi6PQruRdljxcyCQODvS7EeZfwYumj_dRq1nDHuby7JpjEkdSb4qYWu6ckcNyL8kKqYvAT-W_fqPp06xH6jdKrLOeN69mrv3NK_XC6Q_R7jTW-x1_H_wvmPeWeQ==`
</details>

* **Screenshots:**
![image](https://user-images.githubusercontent.com/10889612/120651418-55a40480-c4b1-11eb-8ae4-fa266275c53b.png)

**Comment by ZzZombo** [comment] 2021-06-03 13:27
When I went to craft another flask in PoB all tooltips there also exhibited this problem.

**Comment by Wires77** [comment] 2021-08-09 02:00
I'm going to assume this is fixed in 2.7.0, since I can't reproduce the issue and it's two months old.  Feel free to reopen it if you're still experiencing problems.

**Closed by Wires77** 2021-08-09 02:00 UTC
Labels: bug
