### ISSUE TITLE
Error when mouse over minion crit stats when "enemy on consecrated ground" is ticked 

### ISSUE THREAD

**Issue by Dodgy-J** [PathOfBuildingCommunity/PathOfBuilding#1311] opened 2020-08-10 14:38 UTC
When "Is the enemy on Consecrated Ground?" is ticked.
On the Calcs tab, showing minion stats, when you mouse over the crit stats it throws an error, I think its because source is nil.
I believe the line that needs to be changed is the following, from Config Options
modList:NewMod("MinionModifier", "LIST", { mod = modLib.createMod("CritChance", "INC", 100, { type = "ActorCondition", actor = "enemy", var = "OnConsecratedGround" }) }, "Config")

I think it should be
modList:NewMod("MinionModifier", "LIST", { mod = modLib.createMod("CritChance", "INC", 100, "Config", { type = "ActorCondition", actor = "enemy", var = "OnConsecratedGround" }) })

It fixed it for me, but im not sure/familiar enough with the code to pull request it.

**Comment by Regisle** [comment] 2020-08-10 15:04
Known issue already fixed by #1301 which has been merged onto dev, ty for the detailed report and yeah your fix is the correct one

**Comment by ppoelzl** [comment] 2020-09-29 00:03
Duplicate of #1308

**Closed by ppoelzl** 2020-09-29 00:03 UTC
Labels: bug
