### ISSUE TITLE
Quick tooltips wont show dmg of gem enabled/non enabled- gives error code

### ISSUE THREAD

**Issue by Easko** [PathOfBuildingCommunity/PathOfBuilding#2940] opened 2021-07-22 04:45 UTC
I tried to add a few gems into a skill setup and check via "enable" to see which gives highest damage output. This popped up on current patch (2.4.0)
![image](https://user-images.githubusercontent.com/87795641/126591059-fee172e0-4de2-4a3f-af59-ea0fd7b4d1a1.png)

**Comment by Easko** [comment] 2021-07-22 05:01
Tried brute forcing restarts. worked after a few dozen attempts

**Comment by Wires77** [comment] 2021-07-22 14:49
I think this is a duplicate of #2945

**Closed by Wires77** 2021-07-22 14:49 UTC
Labels: bug
