### ISSUE TITLE
POB Community Edition NOT Updating like its suppose to. 

### ISSUE THREAD

**Issue by SirTwsted** [PathOfBuildingCommunity/PathOfBuilding#2982] opened 2021-07-23 09:32 UTC
When updating Path Of Building Community Edition via the Self Updater, trying to update from 2.3.0  -->  2.4.0
It gets stuck and never updates and remains at this stage forever.

![POB Lua getting stuck installing](https://user-images.githubusercontent.com/15247713/126763497-e09e96b3-ecf8-4421-b008-fef23b3e8c4c.png)

**Comment by pundm** [comment] 2021-07-23 09:33
Duplicate of #2948

Please use the search function next time.

**Closed by pundm** 2021-07-23 09:33 UTC
Labels: bug
