### ISSUE TITLE
Lightning Exposure from weapon mods is not appearing in the Calcs screen

### ISSUE THREAD

**Issue by scottord** [PathOfBuildingCommunity/PathOfBuilding#1285] opened 2020-07-29 18:39 UTC
Version check - 14.170.7, up-to-date as of just now.

I had noticed the Crusader mod that allows you to inflict Lightning Exposure on hit - I copied a weapon from the Trade site into the build to check the numbers and noticed that it wasn't appearing. Wave of Conviction however, was correctly adding the buff to the "Curses and Debuffs" section.

I had tried by just editing an existing item as well, no luck.

PoB: https://pastebin.com/ZDStfUwN

The equipped item (denoted with [Exposure]) doesn't appear in any of the calcs involved in enemy damage taken, from what I can see.

Orb of Storms was added to the Skills list to test if the debuff could be applied by Mines or by player-cast spells - neither is accounted for from what I have observed so far.

Wave of Conviction is disabled in the Skills list, it should be simple to see that the Exposure from that spell is present as expected.

If I can provide any additional info, please let me know - thanks for your work on this project!

**Comment by PJacek** [comment] 2020-07-29 18:59
Duplicate of #52 
In the meantime you can manually input the correct resistance reduction in the config tab

**Closed by PJacek** 2020-07-29 18:59 UTC
Labels: bug, duplicate

**Comment by scottord** [comment] 2020-08-01 01:14
> Duplicate of #52
> In the meantime you can manually input the correct resistance reduction in the config tab

Thanks for linking with the dupe - didn't see anything in my quick initial search. Also, nice one for the tip on the config!!!
