### ISSUE TITLE
PoB sometimes does not display Combined DPS for Poison-focused Toxic Rain

### ISSUE THREAD

**Issue by wolfie-poe** [PathOfBuildingCommunity/PathOfBuilding#1314] opened 2020-08-11 04:32 UTC
Hi,

PoB ver: v1.4.170.7

The Combined DPS is not displayed on this poison-focused Toxic Rain profile:
https://pastebin.com/QFini8ZX
![no_combined_dps](https://user-images.githubusercontent.com/64553042/89857300-e24da100-dbc5-11ea-845e-a7a17674df49.jpg)

However, the Combined DPS is displayed for another poison-focused TR profile:
https://pastebin.com/VEBFyZSN
![with_combined_dps](https://user-images.githubusercontent.com/64553042/89857304-e5489180-dbc5-11ea-9b6d-4e0871c400f1.jpg)

Some folks also have a similar experience with the Combined DPS not showing on their poison-focused TR PoB's profile.

**Comment by Regisle** [comment] 2020-08-11 04:35
Duplicate of #1108 and #1293

**Comment by wolfie-poe** [comment] 2020-08-11 04:42
It's indeed a duplication of 1293. Please close. Thanks.

**Closed** 2020-08-11 04:42 UTC
Labels: bug
