### ISSUE TITLE
Ventor's Gamble Resistance and Quant/Rarity rolls can't be adjusted by the slider

### ISSUE THREAD

**Issue by AndreWohnsland** [PathOfBuildingCommunity/PathOfBuilding#4891] opened 2022-08-17 15:08 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When moving the slider, the selected stat should change accordingly

### What is the actual behaviour/value?

When changing Fire, Cold or Lightning Resistance, as well as Quantity and Rarity of Items over the slider, the value remains unchanged. Saving the item will also not apply the new value. It works as expected when changing the implicit mod, or the maximum Life mod. Changing default item affix quality option and recreating the item will apply the right selected percentage, this values still can't be changed. Strangely, this happened only at this item, other items work fine.

### How to reproduce the issue

Select Ventors Gamble 
Try to change Res or Quant/Rarity

### Character build code

```shell
https://pastebin.com/BSpPCMSk
```

### Screenshots

![ventors](https://user-images.githubusercontent.com/50302161/185174807-a71e6908-1210-439d-b66b-b9c38c8f0cca.PNG)

**Comment by Wires77** [comment] 2022-08-17 16:01
For anyone who wants to look at this issue, it's caused by #4836 not checking for `(# to #)` formatted ranges.  As a workaround, editing Ventor's Gamble to `(#-#)` format would work.

#4836 was added to fix symptoms of #4603, and I think the fix for this issue should belong in the latter PR's code and #4836 code be reverted.  Otherwise we have patterns everywhere that we have to keep track of and update if the range format ever changes.

**Closed** 2022-08-19 12:55 UTC
Labels: bug
