### ISSUE TITLE
Importing character from public league causing error, but on just one character

### ISSUE THREAD

**Issue by frizlite** [PathOfBuildingCommunity/PathOfBuilding#7088] opened 2023-12-18 13:49 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

Attempting to load most of my characters is a success, but one character won't work. (I have seen a similar error from another user on a private league post, but this one is not private)

### How does Path of Building behave?

When attempting to import this one character, I get the following errors. The character is a pathfinder using two new skill gems--Caustic Arrow of Poison and Scourge Arrow of Menace.

Scourge Arrow of Menace is on main swap, Caustic Arrow of Poison is on second swap.

### How to reproduce the issue

Simply trying to import the character. Other characters work fine, but this one does not (only one using trans gems right now)

This happens when I click the "import Items/Skills" button, with or without deleting skills and equipment checked. Checking item swap button makes no difference.

### Character build code

```shell
Unable to grab character build code as it will error out before importing.
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/154240492/683781a3-35d1-423f-a511-9870924e9723)

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/154240492/310d980a-cbf1-4a46-930e-8d383f82f227)

**Comment by Paliak** [comment] 2023-12-18 13:53
Likely related to https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7083, https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7070

**Comment by LocalIdentity** [comment] 2023-12-18 13:53
Duplicate of #7070 . In the future, provide your Account + character name otherwise it is pretty much impossible to replicate the bug with the very limited info provided

**Closed** 2023-12-18 13:53 UTC
Labels: bug
