### ISSUE TITLE
Impending dooms damage is being inflated in PoB from Awakened Void Manipulation in lvl 5

### ISSUE THREAD

**Issue by ChristianLind** [PathOfBuildingCommunity/PathOfBuilding#5533] opened 2023-01-03 21:38 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation ingame?

Ingame value of impending doom levels does not increase from being linked to "Awakened Void Manipulation" in level 5 or higher

### What is the value from the calculation in Path of Building?

Path of Building is at the moment inflating impending dooms damage when being linked to "Awakened Void Manipulation" in level 5 or higher, due to the "+1 level to level of socketed chaos skill gems". 
Impending doom is not a skill gem and therefor shouldn't get the level in PoB as it doesn't in game.

### How to reproduce the issue

Temporal chains
Impending doom

### Character build code

```shell
https://pastebin.com/4jH2pwwL
```

### Screenshots

In PoB:
http://prntscr.com/Yk549sOm_HCp

In game:
http://prntscr.com/r8W4UviE-R0F

**Comment by QuickStick123** [comment] 2023-01-04 00:30
Duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2719

**Closed by QuickStick123** 2023-01-04 00:30 UTC
Labels: duplicate, bug:calculation
