### ISSUE TITLE
Negative dmg with Deadly ailments on bleed.

### ISSUE THREAD

**Issue by Graybb** [PathOfBuildingCommunity/PathOfBuilding#2950] opened 2021-07-22 10:35 UTC
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

image here:
![negative dps](https://user-images.githubusercontent.com/22441144/126625936-3c260a9b-f339-45e8-84a0-9bc88dff0898.PNG)

so im guessing its some kind of bug with calculation of less dmg from deadly ailments divergent version, and the mod already on deadly ailment.

incase the pic cant be uploaded here is an imgur link : https://imgur.com/a/AhUqjQA

build code : https://pastebin.com/SJ6YEim0

* **What happened?**
* **What were you trying to do?**
* **What steps will reproduce the bug?**
* **Does it reproduce every time?**
* **Provide a build code:**
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

**Comment by PJacek** [comment] 2021-07-26 08:10
This was caused by a nerf to Deadly Ailments from 10% to 80% `less damage with hits` which combined with Divergent quality `less damage with hits` resulted in negative hit damage. GGG has since fixed it and Divergent quality now gives `more damage with hits`.
Fixed in v2.5.0

**Closed by PJacek** 2021-07-26 08:10 UTC
Labels: bug
