### ISSUE TITLE
Siegebreaker belt bug

### ISSUE THREAD

**Issue by amc9732** [PathOfBuildingCommunity/PathOfBuilding#1253] opened 2020-07-22 01:05 UTC
Hi, it seems after the latest 1.4.170.6 update that hovering over the Siegebreaker belt on the Items page generates an error. 

I was able to determine that the error only occurs if a minion-related gem is active on the skills page. (Summon skeletons, any golem skill, Herald of Purity, etc). You should be able to reproduce the error by just opening up a new build, adding a minion skill, and searching for Siegebreaker on the items page.

Here's a screenshot of the error:
![ABeltThatLivesUpToItsName](https://user-images.githubusercontent.com/11061617/88122034-77481600-cb95-11ea-897f-3e280a5756ad.PNG)

**Comment by Nostrademous** [comment] 2020-07-22 01:36
Roger. Reproduced. Turns out there is a small spelling error in the code we submitted. Will fix soon.

**Comment by LocalIdentity** [comment] 2020-07-22 12:54
Fixed in 1.4.170.7

**Closed by LocalIdentity** 2020-07-22 12:54 UTC
Labels: bug
