### ISSUE TITLE
Blood Magic+Mortal Conviction not allowing free aura

### ISSUE THREAD

**Issue by Rapturebird** [PathOfBuildingCommunity/PathOfBuilding#3132] opened 2021-08-10 00:20 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When using mortal conviction, there should be one free aura for the player, but PoB shows reserved life when having one aura.

### What is the actual behaviour/value?

Blood magic with Mortal Conviction are not granting one free aura. This includes items with BM/MC on it like Malachai's Simula.

### How to reproduce the issue

use Malachai's simula or spec blood magic mortal conviction and then add an aura to your gems

### Build code

```shell
eNrtXetz4riy_7z8Fa5U7a3ZWkgsyc_czDlFIA9mQsJAnvOFMiDAxNiMbUKYrfnfb0syYMAQhWRmt27t2VMZYlqtfqm7f7LlHP33eegpTzSM3MD_uIf21T2F-u2g4_q9j3s316cFa--__8kd1Zy4f9U9Hrse--Y_ud-O-GfFo0_U-7hnw7DYCXs0vp2xIk24NnL8uE8Dv-oMgvAs6Hzcuwx8uqe0HL_jxh_3ip4bOntK23Oi6NIZ0o97jb7TCSZ7ihO1qd8ppb5wWkFMx-GeMnRcvxG0H2l8FgbjEUi9pzy5dFINOkBXqdau6tepqV0_PTWI_ttRzXOmNGzETqxE8APkAAs4PXruxsDK8cbAByEdWfq-rlumqmt7B1sHlp0h_Hzl2MaI0s58DN4nlv5rSa9DZ3TdD4MJuPTaHS7kV_c1ZGPLxAiZmqpu1KAW0pNul7Zj94mWQjcu9R2_vWCjG_sa3jR2F_rq2IvdkefScD5G20cb9TtfmwGp6kZjBLHjlWuNhelMzUQmONHUESbWzxkXLAJuo2R3btw_9sCr6VnkQowNrfR8N6a7ja0FbhT4rx87Uy49cqN-pWDYcv1d1JuNLD71XrtuQ-pcdUXw1p2OO44WDDa6rOr4TimIJFx24XbpEuVmSU4acizrkGDkKJmYNRpC_ozlpX3VgEa8WIBIszeKTL8tUSK0ibJMnxfrxyJbGKYptzCs-OlMvo1hmhIjvFnCpyCGwiZnzTkV0Ym9JVO3Dxl1xW8vhDX1bYxv_JBGNHxKpfgCMm1Dbkzi5MVQXd03Ncu0bdXWTXsbkzrt0YXyxLL38Vb6C0rb_TOo1DBnuqxujVqJyGM2Y6Rpm2nGNqbLkm8lfbXQd07YeZnqxKdhb9rou9RLVWbL2KpkelBaWazLTLOstJRkr1b-5MmJ0isCWSrZrpIYkNbG2pgXqxRKHozo0NUu4T2H1MJgwPoX75XjiuEwGIeS8SqIl5y4WaD-NHLbUDx5R1mnnXFbLu3MG7Fq8ESHsMp5Iwg98cI_-6q5afSxBw31WrO0v63L9LysQRvlK8ax034sB53eqpU1dessWUPIxiGnbghWi9xUGdO0l4mvoI8vOSOZZoUtrmX-9svE0vwv3F4_9qEhX5kE2ZIj5DXpO0G0MksBYwly6SlOx54n1QI2Ht1lythpefRQUZ8RMhzVNjb2ZLVgAsL0GfZctHBEhrrqPL884DSk_vfpKn9Nijw9web2z--MQxbbq3OosiPW9Tg64OCcfaoMR0EY84slx2tHnGXFH41jxeeweuhG7WZr3O0y9LwHU4Qc-Z-cnp6Uriu3J4kU6SERc1bTHw9bDIeJfxkIF5QNyhOW0g48zxlFFIB31_Ei4O12Ekc3IE-3Yyl6KEQJtpahhnLcDl0wogwxw15SInNALUPJIKoUIXjF8ai8wa6nI8oiIJK1WZIuZag5spSiFGBQTkGOOeXcQNvOVIpy3qBIUZ94tOh6rBDKWa0KC0HUUDl6qGeh2xrHktHGUYGUHKwPllIw3VVKrg45wqS5kRIi6QFlaJNaIxeU0FlIu61MuxTCXXLZ83Ry7TxSP0mWs8R4xNdapESQMc_oMDqeQkU6ZeZd2aNYIoBaFY6Bd4d2nbHHrn8ZO54bT1kKT129EDulGC5G_WDSGI9Ggg1b3BEY_eJCfFP04oQDm2Mmu9CMCcj3P4u81eO_c_H5Jqjrt71xB-BkUnfnentOi829p_TYhmkpGPtQR3zXY3u9rNB2ZkqssGZc2cS_HYEoCe2ZF7QcDy94L_RKE6AZS14tKiwntCnbcNxTvgnt2DXQlYa-E1OUENacMOa69OiQEVRp7HSc2DmoxGCMA2aRAy4afFplmBZirlFbKIvgG1a9WD_ORVHEUD5p1fX5lnVjPBwG4OQaZM_YiYYint5F-cTdbNKi34EJ51vGKWuURbBsV34RNxt58cjbYIe0GRgHxfE7CuOhpOvse-pc8sYReHnN96_TNouLrJ7JWO7y6P0VBE6i7-Pd5ZXPt9VDt9dj7dGbg11-jq3xv2QP3jh2Entkr4E6dUY0fH9jAQoOqQNJmTVLDOg2oIw-sr43KzR2MNOLE8hGzZyRMuOkzFn9UpMVOx3QBqDkm1PGJk6yJuHjFcZgKVsciZT8jy1RKW-tiCPvCr4TwXUujtkty1WenN3bQjgpa2tTvdJJX6njBXE4_cVRCi1b0Kk6Pbf9hgDNYCIdm2EY9FKo5x8ek9LmLYY7GDQJpfRYeTu2_5a26I2d0E7Nz78N3rvVp_ku5PsUqU3sXlep5lx-mu58g552xM2rnVXO4iLfpkQjN3TiOQr_Fb37G1vZ7GYe79LNv1zk_t9Ugnk0XzMMsDlnvrrj2MJYNgoXK60B0fgvuv43-f6C5LsG9d6s_ksc34Adfx1gioJx2GZPQoKGh0g9vKQThX3OKw1nNOqz5VkHt6wpEgFs-LjHvlLQWzIZesl9p2EQxS12gyDTU6-09YLbim2TT3xr9zqkVHGEOnwUSnZU4Zf0s6ZMEALcgw7bkyXENM08xoaaR6qF7byGDcvII1PDKI911TDzuoVJnmiaBT8NDJcJIkjPG4ioRt6AX_S8bmBbz2uGblp5XSOqmUcatnFeUxHKI2IiLa_rxFJhkKET4MvmM5Btobxm6kCOLUJUYICIAfMZmp1HcJnkTRuzy5jLqFlWXtN1m-RtCy5oyDJAUs0G7giG5jXbVkEN-J1dQCrIa1tw3SAGAYaWAZIaOkZqHiPd1Lnsdt5kcxIdC_UsE0iQwX6qBNjYlm6BdDobqtoaziOY0GSWYddVi6lq2JoKHCwbtCTwfd4mup4HyUE6bKkor9sY1ECWadh5HaRTmahgKmwaOuhrmCCwrqmgHfgA7GshW2U_wR3EYAIYmsWmxhqCnxbGMD-C8UQliJOANYhmwBUDjMYcYRt63lIxGEkFpfKWTeA7XVdhOPwDztAsHaxgATF4DsytE42JojL9kWHZoLMJnjJUTQV-WNMIyMzMyK6DXQxmI2QT0MsymHFBLGCIwTYIYaAzgLnGpIKPms6NYIBBdA0iI69pBjM3e_g2Twi3mMl-1wjXEqhtNlDDOpAh2wZ-BHxpM7uBUTDTBqssQk0TggLMxacxVXtPiWEdpB7RRnry8DWLeyNZ4CcdWEydS7YEkpR9U7_gH37rx_EoOjw4mEwm-yMn7gdd-ux6dL8dDA9GwAaWV4Ev8wKb6KAI_zsuPpSLldpz6fLLt2vHKdSLqG88O81-eHXZvR9dmyTEvv3kx92Lm8r37k3ZiNBj3L-xLm_dsFbpjL9ejr-FXzS9_mhodXMSV2_v8UXl66fR3cAdjErHrfuSeRJWLp9pK-66981wdFNvOoOzQumTquFmM2gWSo-40SLdcdn9Pnqgn-p1tRINyq0adRsXlebDtEg7N43b84pVrRqt4qDz7fimF5wPby9G18-DZmg3BsfW8bPu3vlfnx6L-LwzVpsxuene6fhbZRw2Se8rwRfotkEuY_WyeE2aZb19eh7azv3FhHYmNwPLb5Be-etN--zm-0moN88-lx-IadPBnUp0u_Pl-_TTJ1SIysfPn2p4eKuSQb96Xy59KY-tx9tocDKym9Wbj9wZBzNvHImH4CPhmuQ3nrqYN5EBEQz1IxZ1L3mcIIMOQTKRoOMhK0OnQVhK0GFs2zL8NMswbRl-kFwkyCAbyViFGIaUtrCkEZahg1wpxc8wsS5BB5kCmzLetTRiSHmXqFLz6siWihaWamXkg5wlEy0GJjLTIgyKyAQVlDGZoCJQHGWiCkOdlWGHVKlZWTshpQWRMh4mpi4TBLqtWzJOI1CapeRjRV1GPgv6HBnvEmSqUosI2TLzaja0KFKLA1tSqVTVCZaKKqjWMvJp0D3JzGtiqWiGvsLCUn7DUv41oI-0pegMQyr-EGRJqdJhalJ0RDLpQtOqSsWLYcmVLNOQihcMnaJUvEC3KTMv9KMyepjQbMqUStM2pUqlLZUjDRupUjnSyEp-AOYW3Q78ArhtAeBiN_bYg4lt_qT0CpxDcziXAnICXLCqB0ABq_asWRYgS7MxtPGinSY6b-k5kBJwLIFmBIoD9OMMSDFeAi8IoCPQjUA0HL8koEXTTXuGS4jGsAi09nYCMviJu404AnIzTKJx4Aadvwb8dZiXoS9TE4AAoIGuLsECAQMEimUIQ08wqgZjtTmGYtMmiJTYgIcEJBVAT4BRAUAxhuoP0zLBAQsBpcZ8uoQsEyDLMaUGqI0wejYv0TU9AZIgPNiIqJqJEgjJFwyYAZEZ-DIYeoUhJkONtgDLMEkC-DjuEoAPUCbCCQgG9GRicA9nzDGXQHwC20EDC7CWg2OBojTNtFkkMJ0BHRkz-AdJ0kzgusZKxBLmQyrUPkZDSIJzBTjU2BQcVHIICg4F0QXk401EgjUF8BOYT4DoZEeAA3q-mcDAqyEwu8B8ugHuYtaEacCXAJAFtBbAmSCOH_m2gNhAME2c7DkgENzaDvrUnwT62P8HN58fUVS6sq3ubRwNLr5ok7NWuXQ9Ko2_1qbnjlc5vqheNU5vLwblh4H96NWJ495eBO3rzrBQGlrlQRuji1vr3G-fVpqf1FgzPjeiuvEwrRVvn3z32r7vfuZgyXq8K1t0cDu4x26NgbaWRdDnsXH59aIwwJ-j1rfRw-n354vnbwapRRdRIxo83Nbc--g2si4eqp_cTu125LfPr79-LvSKcR_AXGDFN2N17LZHlaZhNG8m3dPTaly9c4u1Yrc-acW1ZpNarerQuz5-Dp_s-Crs3h37XW9q3k9D_H1SuD-uf-7FfS0ufzn5-tC9m7QpCvXr6sNl13fCZ_fpCTV7IYDesH8aNj83eneoG5Zbd62zLz3ruV4vdG7ohHhn3fJtcXLd0qc4-BcA_tMAoGyv_ncBwA3l9KcDQNmeRRI5_U34T7ajkkVEkgBQFpj8XQBQFrW_NwCU3m2RBIDyuyN_DwCUBViyAFAaEEkCLFmAKgsoZQGgLKCUBbz_dAAou5smu131jwaAG3Z5sgHg0QG7s8c-XAYx5d-xi7Nf-H2_W5dOlIg6YbvfiEN2y_R7EAwfPu4VwE_7hgn9twYBzzILO39xTp246ozmdzUZcXJ4Q0_ObsROXHa7XRryYyezm5OM8J71U9a-rhoAtGAZ2eI85RG_25zcgGSfG1TcxhxHtEHbgd-5o84o8Pnl1IEPRspPrSQ3X-tO6MbTQ-XmsvLl5iR37fqP0Nc_un6u4XTcKFbOnLCVS46PHCpYzSVGO1SOC_P_clydOv12qBhWrjIceW7bZTRq7q_Q8Xv0UN3Xf3xAmloAV_zxO7sJndzOTs778OcaxAEkRZxASo_884OhFmz1DyUOlKHz7A7HQ4Wdf1rmDsz1Jd6lIPA6wcRX6mCRJxoCa3b0TukGoRInr6kRT_3kkP670uZn3NgcPccFiRTxgLwinm5XJn3qK9NgLB4UUtwIYBB_Xh44tqagAJN_OM0RdY1VrQ9KwlxsYg0ih_knkmaYSK8AXuVav3qgri6bVpoBWyXVoFNnRla4qdmrfPS9JIKSdbSRAr9IMTsmyx-eWAToE0Slw-7LkxmjzGDtU-XOjahy5Tzmjt1oOI77ying0MfcrWBwqNRCqpB9dV9dvYT09LXSOARfxzlxkBSsMP-GrHBOL4VF1K8GfaLAIcrjH-UxOwErhiviQGAefPm7EoqH9JIHOZSYnSBTgq5CnXZfOfH4mXseMpO-C1e4v278tjMasXUjvnc8RZyC4_EGjvSCCY3ihQQke37jF02PsqdP5qxRn8ahA6kVzPl7mtVb5ei7vf6SIPhHKldIyjRPKT9TMLKLYHrB-jlibV2t-ovr2chez2KpL63herF-kps9SJS7GoFEd1ADcqXQ6cICPFRYCczBWu26z4dKykTiGaD5s2D8cAN76IovRrQ-ApEfnCbrQTRrTs5e5ZZrjLsrY1VDDF4--iMOQ2tz-qXB_JfNBTNdKnE6a6DcX7HTiw7bDnsYtdnhAuaTf8TFWaSgHx-IVdDwUrHjciaxkgNlI6g0UH-Qaq49OMeuc_IoZ-Clgrl8LkkRivJgSuj_RGww14HFnANTpp_UZCKI58-YSzJjBS1Vj42ZHwsyLTPzVx0Pgt1x_wdanOh_I6U4YckLRMhVQuglqhklwJRL9zjFIdOJZwX-X9qN6paORy8QdbOb_sQq90UM0vTiPlgXsiBcYGbNWqlRmjn38QcNF3SNN0YfTKtgWX-kT1MtHM2SgUehJRYdBKz4evIKp3WWulYwEpa2UYAA-kNh7zV5G88CSlgigzWB5I8tUbmFMT_Po_ADPencXg1CZqlS4D-5_Kz2W1sX7UWKNyVDfVsyLLL3XyjF4dij8YZ8yJPM5l82J6bsLJVuZfR0NOPcX20hwI-i5wVtXn2KYdvxoR4BJPLb0yRtObO3F_xY6tuxyhbAUpDLtIxZNjPepYAQS0vVg8XRRWtzrWFEK2Wm-TZ7_5SqwBOOTF3AFvOHTrIzRVaK54RS2X11iWU50szM6Y2x34K2ByLeC6DbPqZenLIKMVesspxk8TLwa8TjBehboiVqQVtOyBwBJeYRth46vvOD9aMLInaQRuGvQKPiZIxSh6WQ0A_oBCwDMzXDeabOWgU8tfNMusjoOSsFBIQoYzFDDutpCXi2VMSbJXMcs84wm-LEgGapQgFBg7_goxsuuPx0CKfJQTgr0-nF-Lsbzst4LQyGgOcgAdK4P43inwDmVlhno7nVPQzokcCw_H1Vs-XCXx0DrJ1I1KhOunGnvHFPg6B0TmEbAh8wFjELfGcvaJuxBpYnz9DoL0-YTLDKGq-zZstBfQfWZJ21gB1vZZxhDkQE0ALWi77nveyhvhPvbQbZibPM1siv6VG2UJgvUlhyGcDesIkDCY4nrvNgRKF6u8MI0usnllMXS7oxZGWInSRZXKtSyIXDlYsXfKtu-dot2_lLfZGVF5bnFWn2UBC0PLppd-fHle9NFUe85EmpiUcXIsjaaYFTsbmRPK1LKt420qe0mZNrm8lXLZD-TuiqQEuntKgy6_I6ysSN-8E4hossYtuB7wujQQ3jWwrs0Yx0aS2wKoeSKrcZwOzaMSN1W_u3dA4pV6cdCnOH4rs3ddCLrQD8A-pKRK_8czeenxCq-F1vzPbs8WvbbEPLavPozGb5NrRc-fV-Ai13E7wxS3UTXES-eeuCd5kLlbmsCoQ3yJ4Xl8kS8D_ZnJA24vUG9GnJC_zEvQYldc9m5klOJO5SzO5qiCGiUqbu4eH0CEHDesAFgblOcE49qOcLEk1u1tQdN2udaaIM3qBMIlrQmSqzd7bO6NA63ezw25xEXacRSG9BM3tHanJbZ8stnfSdnCx_NCbQUBZb0yhiezrirljGbb-soavDsNywNaOtWC2AzLSbQFm6vCAUix_pIa8J0sx4yRKQ7GZsOZPgdxqm7SaksdtsksOyrIlecHdWdL3gAZFBXjtRRlwZu8zzQvyeeQBgo10Yk93XFNplPm23WEC7RZ72snvWykaGYV_LNiu8dlT8BceLvKPvIM8OGZG8NM280r3SfdlW3im-9F0GSS3JteYhwxE76anvbFa8g9-N3VYS2S18yeujTNs97e8Q02hn45PX9wfr7WRGDO2gxBsaI0m_bu_WtvnE2CFGd3fKG4JHNkGzsZJrSJ50B8txwIB3STh4Z_PumDzk_bkGkSTUIRJ2ygBW0n7QdjaXvot3ZBbM7lH-gkibEOZBAjH5c4_8iUL-Xv_A77q9tbf0MwTqsnsKjT5MKnYMUm_r1zNe7A_IdeXvHbSCwKOOn6TRg82T8AfQSn3X89hfJnrdMC6gzDCQb_nPPbw0YDj_e3Hsj5mx5-Ua7I-Q8JflpGyhbh2aetUue7EY-wNK3vSF0csKHnuu38lW8Ohg5r6jg9W_sfh_UMW78w==
```

**Comment by Wires77** [comment] 2021-08-10 01:01
Duplicate of #1007

**Closed by Wires77** 2021-08-10 01:01 UTC
Labels: bug
