### ISSUE TITLE
Feature request: Earliest gem source in tooltip

### ISSUE THREAD

**Issue by Readie** [PathOfBuildingCommunity/PathOfBuilding#6137] opened 2023-04-26 22:53 UTC
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Knowing when/where a gem becomes available is good information to have both for levelling builds that are being followed and for late game builds (to grab the pre-levelled gem).

Having to poewiki each gem in a build provides a poor user experience.

### Describe the solution you'd like

When hovering a gem I would like it if it would look at the currently selected character and display the act and quest where a gem becomes available for that character.

e.g. I am a witch, display in the tooltip for the following gems:
Summon Skeletons: "Act 1 / The Caged Brute"
Vaal Summon Skeletons "Drop / Corruption"
Fork Support: "Act 3 / A Fixture of Fate (Siosa)"
Detonate Mines "Act 6 / Fallen from Grace (Lily Roth)"
Empower Support: "Drop"
Item Quantity Support "Removed"

**Comment by Nightblade** [comment] 2023-04-27 01:45
Sorry, this won't be implemented, it is classified as out-of-scope for PoB.

We recommend [https://heartofphos.github.io/exile-leveling/#/](https://heartofphos.github.io/exile-leveling/#/).


> Path of Building is primarily focused toward build planning and optimization, and as such there is limited design or UI space left for leveling guides. There are other people who have made specialized websites for this that do a much better job than PoB could do: https://heartofphos.github.io/exile-leveling/#/ is a good example.
> 
> [...] we don't have the data for this and would have to manually keep it up-to-date.

Dupe of #5975, #4228

**Closed** 2023-04-27 02:32 UTC
Labels: enhancement

**Comment by Wires77** [comment] 2023-04-27 04:44
If it helps, pressing F1 while hovering over a gem will take you to the wiki page for that gem.

**Comment by Readie** [comment] 2023-04-27 07:36
That does help! Thank you
