### ISSUE TITLE
Power Report Crashes Program

### ISSUE THREAD

**Issue by GenShinigami** [PathOfBuildingCommunity/PathOfBuilding#3895] opened 2022-01-15 03:25 UTC
When I attempt to show the Power Report, I receive this error.

`In 'OnFrame': Classes/TreeTab.lua:844:  attempt to index field 'power' (a nil value)
stack traceback:
Classes/TreeTab.lua:844: in function 'BuildPowerReportList'
Classes/TreeTab.lua:733: in function 'TogglePowerReport'
Classes/TreeTab.lua:133: in function 'OnKeyUp'
Classes/ControlHost.lua:54: in function 'ProcessControlsInput'
Classes/TreeTab.lua:177: in function in function 'Draw'
Modules/Build.lua:934: in function 'CallMode'
Modules/Main.lua:270: in function <Modules/Main.lua:240>
[C]: in function 'PCall'
C:\User\[Me]\Path of Building Community\Launch.lua:107:  in function <C:\User\[Me]\Path of Building Community\Launch.lua:104>

Press Enter/Escape to Dismiss, or F5 to restart the application.`

I end up with this issue intermittently, sometimes closing and reopening the program seems to resolve it.  Sometimes it doesn't.  Additionally, the Power Report itself intermittently does not update when I select different criteria for it, even after 3-5 minutes of waiting.

Version is 2.13.0, the specific build is: https://pastebin.com/Yv86ABaz

**Comment by DocPaintfull** [comment] 2022-01-15 18:00
I have had exactly the same issue for a while now, tried reinstalling as well

**Comment by DocPaintfull** [comment] 2022-01-15 18:07
duplicate of #3464 #3599 #3738

**Closed** 2022-01-29 03:24 UTC
Labels: bug
