### ISSUE TITLE
Sandstorm visage is worded wrong

### ISSUE THREAD

**Issue by sickbeastdude** [PathOfBuildingCommunity/PathOfBuilding#5642] opened 2023-01-29 17:55 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the wording ingame?

in Poe Sandstorm Visage reads: Base **spell** critical strike chance of spells is equal to that of main hand weapon.
I think its screws with the calculations too, i will link screenshots.

### What is the wording in Path of Building?

Path of building reads: Base critical strike chance of spells is the critical strike chance of Main Hand Weapon

### Screenshots

pob:
![image](https://user-images.githubusercontent.com/76535932/215345753-efc89b3c-2c7b-416b-8846-9e66166c54b3.png)
in-game:
![image](https://user-images.githubusercontent.com/76535932/215345769-78cc0a03-1d5a-477a-ac30-f2d1891042a1.png)

Calculation one:
![image](https://user-images.githubusercontent.com/76535932/215345827-0fda8475-d34f-49ec-a330-6e5b33a13f57.png)
Calculation two with same everything except for sandstorm visage:
![image](https://user-images.githubusercontent.com/76535932/215345860-298a2670-a097-4d17-aea7-85294b51414c.png)

**Comment by Wires77** [comment] 2023-01-29 18:45
Duplicate of #5583 

For now you can use the old version from the unique list in PoB

**Closed by Wires77** 2023-01-29 18:45 UTC
Labels: bug:accuracy
