### ISSUE TITLE
Test aura/support build with other POB builds

### ISSUE THREAD

**Issue by Junp00** [PathOfBuildingCommunity/PathOfBuilding#2084] opened 2021-01-30 22:08 UTC
**Is your feature request related to a problem? Please describe.**
I would love to be able to check how a support build (Aurabot, Managuardian, etc) buffs other specific builds.

**Describe the solution you'd like**
Be able to import two PoB builds and see how they interact with each other.

**Describe alternatives you've considered**
Alternatively, have a button I could click to generate an "Aurabot Jewel" item, taking all of my buffs into account, so I could import that "item" into another Path of Building build.

**Additional context**
I love playing Aurabots, but am always curious how well (or poorly) my theorycrafted builds work with friends of mine. The best I've been able to figure out is to list Minion skill gem (Golem, Zombie, etc). However, I believe the information provided from that method is very basic and doesn't accurately provide information on how well or poorly my teammate may or may not benefit from my specific build/gem choice. 

In a perfect world, I would ask a friend for their PoB link, slap it into my Aurabot PoB build, and see exactly what I can do for them. Then, I could tweak my build's gem choice around to best benefit particular builds.

I don't know if this is possible, but here's to hoping!

**Comment by ppoelzl** [comment] 2021-01-30 22:24
Duplicate of #1260

**Closed by ppoelzl** 2021-01-30 22:24 UTC
