### ISSUE TITLE
Error in Maxhit calc?

### ISSUE THREAD

**Issue by Smeagol001** [PathOfBuildingCommunity/PathOfBuilding#5223] opened 2022-12-07 21:36 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

suspecting errror in formula

### What is the actual behaviour/value?

i think there migt be a typo in conjunction with using unbreakable when calciong the resultin cold max hit

### How to reproduce the issue

enable/disable the asc

### Character build code

```shell
eNrtXW1zm0i2_rz6FZSr5tbeiu30O5Cb7JZfE2_s2LGdZCdfUg00FhMEDiA7ztT893u6QRJIICE5k62Z2UlNIsE5p7tPn37OSzfi-T-_jmLrTmV5lCYvtvAu2rJU4qdBlNy82Hp3fbzjbP3zH4PnF7IYnof74yjWd_4x-Ntz89mK1Z2KX2zZbMsqZHajivcTUfQTiLqVSTFUaXImf0mzl2nwYutNmqgty5NJEBWTb34s8_yNHKkXW2cyk-NAZVuWzH2VBAezW_8a39yoLJHjYssaySi5Sv3PqniZpePbF1t8y7qL1P1ZGgDlydnF-eV1rfUoqbcOvf_b84tYPqjsqpCFlcNfL7b2QAnyRr2KQPydjMcgB209bae9ulUqWE12kamjMFR-Ed2pgywqDoYy8dVqvnVpz8ZxEd3GkVZbRY93eRfHdVrI-PDiarXskjKdKYQ6lPNdzF2HIoFpF9-HqBgCW72NNTj3Y1Bur_5p6pObJCpUb_KLNMrTZK3RbzCMg3EcwzLp1cxBOvKipDnivs2kaRyk98mskV1OnC7qvUzJ87A0yEsZRON81h7rYjqTiTxI8x5r4jQKVT_Ko6t-dJewHPtR6l5eqAwAo-jf2bUYqhaulJ8CKK3TxjostXFs1tgGnEdXmzBs0NBVMYMn4uLOWVdf6pTY6RR4qL7OyDBfIrBO6XbKO0lmo8BELJHXpMTdHbxLC3CGPbHm6NXFlJIh-K_Trwwf8siX8Zn8Go3GI3BZ1_KzmjWDmXD5LueIckwcp9tmboZFAjjVJYcIwKFdCpiCOXU7FXIcZapThEtdvIsRshHhtuhGsjh4ZC_AYaZ5pwyHIXuXuQwzjl132SqagaLbrToIAPxnmvok8Wdqp2KZ4HdJpnKV3dUiByro0r5cwvLSYYkXq948s2aqZTqzfLxLmGMzQahjY7G84RuVVK0_1Naii3YZJYxhIYS9TMCpUv7wJURpl7JQ_YBvSsUZXqp3TVzX-1KpLVrHbj-Gef3RXVhOCDMbdEiRvUxIu_6IvYuXca2ptA8y6xGEHiUqu3m4GkYqDvrAW51-MoIDeduH1cxOnb-xOki_FtsU12twa2rv6E7mdWwGiFg-rpK-n-EpiGGBIVB9w_iLLP1FJwrxemx72Sgd19wqd9lyzCoZGvNir_Qzh3IEodilCsZ-w53xzrb2Y0jO-g4COhbHbRyk02T2ikL6nw_T4Eat1cr6HFfj21sABD31ffm0P7xUeVQLirpta0Z8DiZfX2jMXeYt5xsgq4nnG6D2ysigdytzHPNNcbTUbc81Y7s9qOeb6Aa0SQp-BqAyAkA32ftZWkPDXdypimNI5XrlcYawmS12L6z0Hjo_1AWTfD1qCHBm89fZlUwl3x56y2-Q92rgKAnGmV4M822Ivhz1ZiZM19EIcDPPD2UhrVzJzB-ewkS_2NqqfTuWcezB2oermuv5U1OH0p9ORrdpVlixzIs930_HSfFK5kMYdxByl3LkK6b8UFIlGCIecUTgOb6wfYmJDbfdLcN6qWQ8Ap0flF91d6VfqKyUxbDn2Z7PJXd8jwvlcocEgYsVdamNApfZru3JwC_7diBjPzdDO0lux4WVmDrWKMr9T944DHWxCoZWZKbWdnR8fHRwffL-qNJGnSX_HMXxp2Q88nSJp_xX17xKyitlYNnKx15efnyx9T5S91ea61AVMophhvw0juVtroIXW6GMc2g5go-G5grU7hdLpBkqCKpLR9Ala0bQLenoq8oKGC_ELn4Wqc5-Te-v6FTZoI4WtPV0SdM1rG5BpTM50JNvIocOTZmaX7cUXYjrHI6-uYQXTFfGnS1Xd1dooni4VTm4-CiMfL3wlk_5NVCXVEv04vuwZv2HJfNducRuGaaY1yWgvNnNXBbruriru0u0akqDnVot73azHypfdo69vNnNPA1G08RUlNulTKmWSHqTJsbIYdHsRbH2X50zexSrKUm3wPNiqLLSKXZKOgOMmpAsXThZ5I2L7mVco1iiK5N1d2hI3-tmLfPGjjHoe0uQqJEXdSi0TtMtqkzEOoFsGeskgO9QX3l3ySAmSUxH_6vb3QLKWKpz_qrAbNn6hrC9e33rm93M5fpYFFFk454SjC0fqlABCi015inNEhQtxskhAF6xRKE9RZVeae8ujYIyZXiUNDPIdmEzTa0lqwSJVr2tLdGkVI9V_Vym9V3UX1UAO_C7RrJCEADvqyWuvZ-kaRLyCuJLvQ2Vxo8TuFDpfNQ40yKXSXCoiy-9B_r86SS-fW5CitzKIf5-qUb5_gNkQccaNOe2t0ayAH-nRqd61_g6nQbXp-Uucml70uipCkwh-sdbTcETukCFchzr62_HMo6KB53i1K5WQglczIfpvTavUoyOfXIA19PT8s5eXFQSdBuTMZfKqnphFIDNteqi2YLem3XV6MJ0Nkr8eByok6RKHadKjKWnO6Q32HVFd7rY8jjV1Twlb2FayNa85GnDf3sO_auYX8apJ2Myk10OFoutBgGetqElnUxn8bwKmPcA77asL-Xoze1SfVvWjRrp72eQPgSQjz09KUA3T7WCnppewaclosxUzA3TpGRGQzqp0dUobcXQ8TRW0yCy1yDtVYO8GEO8_bDxwObY-w6mZLPS0IJArBaFfZ8xQSKnslGUVP5p0zlrldJ3hE3ucnDPS9m_59J4pcBfFY9bGCv1qwtx15kuKG2o2gUB5lRKD61qRstwfkdzqeBOx8_FJoOaouW8hL62MuH7_mPSqtpLgjNwK5OCxMaj65bVd5xaggXO09IyrHoB5LsOusy0r9NJUrvxiDsE9R2u9ufj_Meu__001fHX77r830eF0cPGy39BQF-NThm_v9FA-pQGZxDC-o8wmBYhfYe2l2XpzaxC9GexlT3vIc9lfJBtbi0tIvoq9SQJ9THI2NLM_W3mD-YwfoipBA_WpADz-4KLlPGl3iFT6TjX7n5zlOmU1BtuQII1FWEZGd8feaoIWMbHqa8PGm5sTR2C9K5Rn9FO2a2S_68dYdGeY7qUt1FQ1b83HlaLkL4ju7qPwsLaC8M48muhxvectpPEz5TMVbA_zvS-9aMjyRUC-w694m4Gkn8EMDQKhhgYpmuuR2tMzWiUJpep__llCut2UaYRtyFyLghf1yYNv3VVpBDmL_ZvQqACQ1ES_LDZq4pH2Lq610Dyuzqzt-MIdDg2ex6bzkWhVAwC169AzDh_tG7Jj9AtiCwKlXkmhv3-1t8Qv6H9d_Sw3nd95OjH2_7jpoatrA_FoIpDmQ83LxAtSHix5fSrEGlOy7A-_b5R6VkaFyq5Gqo4flRM2ianrtXVIWkpwSpF_Det2Xw9gCbu1CNT4B4F9hv1mPr6BpHRB3mndHH9IE3u1g4LRd8y2zjL1Xl5ZmPzEtuikL6DfKW-FunY_67rXKPHSHrRo8pbrUL6jqrB_IdY2_w_vrZziMR9_TArdPgZFs9MRGm9zKLbbetU3egt3MlK_4_BwFHiD2VS6Az7PCzrUul58hru0vbZWHu_CXIqs-gr4Yuarj5eqcJsSZc70frjteas9pKNMFxt6cKX-sPFJ2ZnF9SUQ_DyUB16erH1K6WC29sUU4p_2_6VM8rQNnddKuAbcYizjTEn-hYmHNFt7DJCNCHl2N5mtmD6m2AYKAVGrg3fGCOus80c6vDfYJhpoLehbcbYNseuvc1tRuEufHAdgbcJRQQ6gOCfbUEoc7dtLPRHx92mNiVim2FmE2gL23ybcNdG28zFHGQQW6BtyrCNt_XRVy0eGi476mD4SDGi0GfuCLgskAufmUvRNhHYFZqQim1KCfRFQBsYeoUxcFEb_i5HQRh16DZxEfRU6MuEEsyBXItnwmgLFAScRgpFTI-cMxDCoEcC6a5z5uoriDrQXaNvTqiWSmEURsmUcQydo1iAkoxqMUNcbBMiQDmlejlyEYMr2N12XRdUAbcQTI9NzYwBBUMCBHI9fVqtLrQmXFAoY7brghoQSMcOIlwPFMEVmzKtI-gWcxxCdHdBrS40Bx8RxcAvbGiZ2loiTB6DvhAMCuQO3GXEQdAGjIOAMm3hahXpqePQPU61LrFtC76NjTDuELjCOWh8uzQ00LGedca17gjSw7ZdR6uDET0QYcP8MIHwtiu0SERgBILacFPAtIEYZGZAIAKjJEifbi5gQdSezsdu9eD9Se1ow7vL0xIchkVxmz97-vT-_n73VhbDNFRfo1jt-uno6S0wwaraMTCwo8U-3YP_9m-O9uU-end8hD54968SEbz_6NCPymHI2xlGl599Ee29fP9wv_cyOTh5bx8_fDp99cvhv0_2PvLza-pcFEi8G318d3YRHex_2gvHn-Rh8QW9_vc39-vwMt358OXT3WH27uj44MBJPn08ObqTB6Ode4a_3JLs5A0_fnX88OVtfjYsjr55b47evBkPf_7505e9r8XNyZcH__TjLSvQOP05yakcv08fPh9_GH_6lv18ORrZ9lvvpfoQ7RRD5d2_vf4SMvclio7f47vs6uO5Ss5ODj6fqSN5fnF1-I2y5HTnzRdycP3u8vXDl09Hdw9v3308Gibhx_DEv_1X8Onow8Uvmfvt9Oj2TRbc7n_e20d36uyNcvckeq1G54fqCu0f3D-Il8XRG_tLIm7O0xt89PZFCW6TWXhe_sRBXuF1-c3ghp4zs1bBkxSlh5s8wqBBcMYGXwDvDDRqQNQf3qSFMvf0xckXA5f60Hh11P6qyLQT-pamo59fbO1g5ri7roYFsFvOynMzr5QszuTt1Gto4urQjVuduSlkcRgBpGbmyNYE6jXhv_XjcITtAuwQBMBGy4cNnhv_XOG2_jw5AjTOVfmwcZnumcu1gzqa1LqTWSS1E2HliSUwcaORS6kPZjyz3r05efvuaHA5HkX_A0Ly_8t1MOmnJpgcvMyk3hG1IFjJPw_el7KeWReZsvAu3UXNS2SXz1-iu7hxDcJAGHcxKI_Xq8Ca3mFzjVXHj55ZBA2MBi_Vl2eWcAYno9s48qMif2ahwa_V-J7h334F9hv1DO3y3_5O0Q5D__uTVW7sWkVqmVOTVjDWDxaULVjK-LWZCNIQQdAOXVsEbYjAbIesLYJNRODf_u7sYLIuf1MRmLd3wZwuzNfRB0Y7mG8oqakWsYM37VJdOWxHrCdF48BZGlxqAZYRY34dolwXZIIUnRR0JQXrosDlfb5SglhJYa-kcFb0YvIgmQn7Z0ARlXjZBg4ACF_GKkuzCUJARAgrEPDrYXCQRaMc4u5_qXsVD94lEVBaJ4ewbMHl8pBLZMvQVyQMmITQAnx-wF1CQoRwSJFQmEOkYVPuEUFdqrCrEFJISXdgemVW_jMLD06jUaTxokj1twYG0J-sTD-HCXf1-XZL__SCjo_LuHfAftKZRbkPUV6zyojWmpxsbpIYGZfmeWdztzbamtSlU4BXTlJvc2udptZZupIwqjiezNFxBinDYB_EBjCo1xpYy0P7g3JHA9ToiOrzPgy8erIbAhqt0_KUf8XxzKLOoH7uf5G-NvG-jRyCAog6EcSloe9AkObbMOMeCpEbUimRjwMHekskzHQghK-Ei0joYw8-4sbEO3jmCNCgcuLPrP2d_Z3Lmlvgbt0k8OAJzChAgtRzPd3tLA_ua7jIB4R0QEe1yTSgqGE29VtPMFohvdb8qDyT3Lh9IJMkLapWyyetfpxBbYJfU4reCNZmtqRptmd7L08ONLYUUTLW2-57I1UMH2DtlqgNaw1CT-uNzO6HsgEtkCU4zAkhUQg9h_gBCXzXD5iAlIb5CEtPOkHgcwFpEvIdH9IawRxlh4EIqXIEalgYIx2hBqVNmCG4bhHlM5vW5LH8AeM_Wf7UoMyTCZantA86GAJgAEflkkrsWUJ_nKXfVDJH_qPmvm3eaHPeLvcuIV7Um9G6Ll2obHAqfe0fYIzlqdQpwhDciTC7DLkAKuXDOCVl9aWDtDb_IoBUVQgG6XbgCDeUvmf7geIO9wQk-8h2w9ALVRDIICSB9CDRVpDbe8pXDrED3ph_GzXmfwoxlzsv4c9-HWTm_A5uGERZD7ImDwhal1I_0zkgbp2oVIY5GlmNdvDEcbUFTHBCl88AYUoAMY9216BjwOvCzPPlVvmzVYNf_UyG4CB_e0JKdDInaHVD08fQGxj054cb1gY3jRxDQ8yhuo2VCQJqBkZDhh3PlYFUAWYcghQAER8QxbMJhCq-S0WIJNOxjc25UkiC38LMltgPeBA2DYyzDoAhdtOeYFA_mQij5mws8zgkTLaEqKvukzfAhzYl8TYlHWfmKFQCzR5Gd_oIr7bKmc7083vatmsaU5wI5VOtDpd5YUBCQTz9gzghR66LPOU6itm2o7B0MXWZ77tAHkri2RABOqqhMUG7sj80B8liFvrtjXSxdALIKhicJNrWp1cerPshwCrEc6fpfbnMLtVI14MtszeR61uQUT92ZSyJ20QLkO5naQprVMmbsRrsJTrOLKyXsMKhYzUc5Z04qn8RrxF-cRUQ7rlUAkL6ruM5yqHECTDE1j4EWxyiLeVzyvTT_15IGIIo3HEQ9QJbOrhpu0J0geOl_r82NUw0I7ApHolOR6cfLtQ2FoXWQzou49Y7Zb0u3SVMGwwyfhhgpzbJk2dn4faXMSCceaRkgFtAFoCVLAAraQDo5McvLPMcew1CK_idIafG0Xkw_itgqN1isUdJkaW3DzoRSgZ7eZGB17uIZaFmiQWFfKHLXm1GeN1eEaG-GzIWUqYAQKWtPD_kVLkuoa4X2qGAvCAMMdMJg2MHPpGB64GvFwoSGzds2qvTbq8mXwB3DlZbhxMylzWsDuyJY6y4tDDWanaCL_pzWvnzNA7q7nzB4qZO-69obE6Lsb3O9LOV1odhmsWDaYJwOed9bJdj8CcYMdvxPaQElb5vU4mxhyVxBOEOJJ0EoDAkIXchJfV44EP6wDjYnhfM21DNRNiciRDaHpntBUFu2foWRuU8Vw5cm0uV4j0RdctouPNWs9HPglu8LEjcqkxzjB4qfKzbDv0vWlWVrba6yOvos_wms_HgOr2V3xZsx2Uhx44viZKhCLmDQiElQgH3nUBB7uArKQLmK65sRhn1GQ0C19EJBhGBy5p1Ksrq8R2atx0-N1E1-3mCyQR6Zj8QMaBuS2XqBiKzsnClkww1EGjmIKvKlj4SMg1qwLkOplzKomU0pw0qN7sH5qPp9h_KRlorY6hpAm_OL8_2Tgf7sQyM_kDRddhwqCQuTD0TkiriQdCPKKEslDJEIrQdXaKkCCHsuzZWri09GQIPdpQdBLQZKhHRWqmCKKkRJ5E5QMH1yTPrW4dF1vUwU_kQYKTXlLSqAreqAvqYFd-sK1_dFllDGyrwfaKo8hgnPAi8QGDsOJyQUHFKFHK43s93HcptFwGFBl3kCeZwxw6Jy_poY75up8PNujZIo-o288FV5W1jXZBWZDhOMy8KAvAv1_qkw0Q35f5THSJ816eeb3vIhjwQe0opNwgcId2AAnigwJeeZzPwQLrmDc4GIhglIJRxbD8UjmzWm5y6ZrqywVoA_U6rwuQusJCtAvyhJa0reaedy6uoGFT5jeUKkz2axV2lMo65clbzKYY_0dlk6SAqJzUDg82XXluZaO8mTR6s_UxGweAg0r_qpSBRG0PGXdcvViGCNBcg1ZFBQBhEe54LcSAOEWQ3CDJuTxeLISNndqAoCUKf6l_PxYENs2LbTffN6yWbefeNTbHlCkw_uSmGxlMeqq-F0n2eRHeTu3XQxGzXnsdNoCftwYC7zIqt-whaLmOCyW7CzJlztBAG_PkdN2YttnOhdy5GaRKBHvbj9H5w7gMotiEXgcQVMgVIfH1PwbqEv203QL4UynYErFEmwIAcm4e-_jU6LJkXmpQDgwvHdne5BtM6dK0AcrEUunQWO7tt4vzqjokcsQkNKa6HjpP4b2p2jfiPkrrA5iMyM3tq1igrAzRwoX-f4q9gWq0VrjOZp_4Qlutkt-xy7D009x2u06xIo7xhaJIyTwkihU4f_MAcZmIEQoGQ2MTzCESLcIu6BJwkDZgbMPCaLheQDzvgDdSyXLUGWqjDE1yqsZ5FWZgOKsAu09coL3s-GUu13W2sh1QbFfnMg8jM-A0LBiyT0qYGzGmpUq9RYXxc0NZWF5sd7Rw0TnbOigw277t7ydbYvbRD35bgXQLsh8gDFwRBIg8BNZQvZBi4FCPp6DkXPtU1C84FRx44ojDgekuiiSV2dzlibgOzy_tfZ5F-xYu1cOxT-3gNBRV-aPgg1uTXiduST0ZrpYvKEXbkosxecEI1X8h33UVXSPGsgFFPa6qcZ77y8ecCnu9xXqN1ZTitcevJaATgpJ_fjSFJACuS-hfMrH0VN8IqGnjCo9QFTEKCSxeSWOT5EK0rhFyPMEU9Im0bcU9KF_4IJRSXvucHtmK28pumTJYg1BOyaDBPbGeZEdl4wYbq4RaaVT2quzvagy4tzu0wvLgATLgbZuloEnHp3y0bMNSCd_dDgANL78yXvwMSbE_2YtMMloZevMFfznBrZnkVp5Mf3509XzY9ajnZQK5Rlf6U1oj4ItHkTP6URizSaMuuUThdTfEZUUt3Jj-ZNCGhXWJqw-JdNKzWH9JFRGZELTSzXzebSuomqp60nFJ2k-J5UrRIqotg9YbdFp3XH36e0Nkdomoac9pEmScjJxQtE1zmhLU-T-amOu665Khr82foFrWhlWFVPy1iVceFa3aCJguhTZFzbKQf2-KiWNTGhj1qG8yKXum1syZL57pttcy2PtHNFNxPC-Q7sbHNOik2a60nW5s28YoZbjOoFTNQYuG6DbWYktiknRX21-USekimm68jvMlI2GbGgDczPbZ6fhbdZItq15XbZmAbjrwX9Cz68dX92QAG6aphTz3gmvPXruWNDIxvwtRrUS4EQr0ioR7j5BurlWxgh2KzpUQ3M1-6vpWxzYF_A5vGGyuf9lmZLWFvr7h3Zb8fEQD1nMqFMLv3NIgNzHLzeXiEvfTF5PZcYp1kovfkrNBdRyLSA2XIxgreEDH6z-hCvtRjOLSHnhazrN7TwDbWFt_E1fVZMQsJYW8zX9GlzmTyaZVNmkc_zUOV5o1EaRJGNwvvF1K6MN5829vsNUO49irSBabp-Y6-XDqvjfR5jvMEOpMrX9fAAv0W7yTYsrw0jZVMqgdFF7nn3yc-e32SebP3IkP5ovGVZGYsup671uDNXujaAze7ENUe1uoRj3O1-LatVUzNth6n6erd6StV2Gyzqiqubsco8iTfT_N81sRFlCTSj1c3U1UqezajC_Pz01V7K5qv9CEUldVZqje9T6httIK-axERSlZwNl6EN2GjK5g6l1-P9movmZ9_o9iq1i70Cyd6MtXfhjhlWdW3lonqMSK4sk7PWpcvd3robZ5p5TTp3YQZef1tkF0DWVdlbeC1WmWaax2VLbwYcq57z59OPMzzpxeyGJ6H5vV8wPCPwf8DoCTSNQ==
```

### Screenshots

with unbreakable https://prnt.sc/FQ4RlwjCs9rj
w/o https://prnt.sc/oXcK7gJYtsdg

**Comment by QuickStick123** [comment] 2022-12-07 22:20
This is caused by you setting your cold hit to zero and it assuming you gain full mitigation from armour in max hit it should be fixed in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5196

**Comment by QuickStick123** [comment] 2022-12-08 23:06
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5196

**Closed by QuickStick123** 2022-12-08 23:06 UTC
Labels: bug:calculation
