### ISSUE TITLE
Flesh and Stone + Maim Support not working correctly

### ISSUE THREAD

**Issue by Phab1o** [PathOfBuildingCommunity/PathOfBuilding#1662] opened 2020-10-16 08:01 UTC
When linking the Maim Support to Flesh and Stone, PoB is no longer showing that they take the added "Increased Phys taken" from the Maim Support. The 16% from F&S is working, but the additional 14% from Maim Support is not. 

I see a report from earlier this year where a user reported the stacking of these two as a bug, however it is not. It is intended, as was confirmed by Mark when F&S was introduced, as it's not a stacking of the "maim" debuff, but rather a conditional increased damage taken while maimed.

**Comment by dambrisco** [comment] 2020-10-17 00:10
Do you have the "Enemy is Maimed" box checked in the Config tab? This appears to be working correctly for me.

**Comment by ppoelzl** [comment] 2021-01-01 05:58
Unable to reproduce this issue.

**Closed by ppoelzl** 2021-01-01 05:58 UTC
