### ISSUE TITLE
PoB interprets local negative base crit mod from Crucible tree as global

### ISSUE THREAD

**Issue by Blubberinoo** [PathOfBuildingCommunity/PathOfBuilding#6048] opened 2023-04-13 19:30 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

There is a Crucible tree node for swords that reads like this:

-3% to Critical Strike Chance
+60% to Global Critical Strike Multiplier

That mod lowers the base crit of the sword by 3% and does nothing else.

### What is the value from the calculation in Path of Building?

PoB reads that value as global and applies it to crit calculations that have nothing to do with the sword.

### How to reproduce the issue

Easiest to reproduce would be to just add a sword with that Crucible tree node and then add Spectral Shield Throw. Check the crit calculations for it. In the "Value" column it says "-3 base" with the sword as the source, which is of course wrong since SST has nothing to do with the weapon base crit..

### Character build code

```shell
My PoB: https://pobb.in/a6mnzp7F6TpG
```

**Comment by QuickStick123** [comment] 2023-04-14 03:33
Are there any other local mods pob doesn't correctly support on the crucible weapons/shields?

**Comment by Hrogath** [comment] 2023-04-14 13:35
This bug also affects the positive base crit chance modifiers as you'd expect. Here is an example of an item copied from the game with ctrl-C. The correct crit chance is (6% + 0.4%) * (1 + 0.33 + 0.1) = 9.15% (which is also shown below), but in PoB it shows up as 8.58%, which is exactly what you get if you don't include it in the base crit: 6% * (1 + 0.33 + 0.1) = 8.58%. As @Blubberinoo pointed out, the base crit does show up in the crit calculations as a global modifier.

`Item Class: Claws
Rarity: Magic
Noble Claw of Penetrating
--------
Claw
Physical Damage: 21-56
Elemental Damage: 1-6 (augmented)
Critical Strike Chance: 9.15% (augmented)
Attacks per Second: 1.60
Weapon Range: 11
--------
Requirements:
Level: 52
Dex: 105
Int: 73
--------
Sockets: B-G B 
--------
Item Level: 85
--------
Grants 40 Life per Enemy Hit (implicit)
--------
33% increased Critical Strike Chance (fractured)
--------
Adds 1 to 6 Lightning Damage (crucible)
+0.4% to Critical Strike Chance (crucible)
10% increased Critical Strike Chance (crucible)
--------
Fractured Item`

**Comment by tylerK1294** [comment] 2023-04-19 13:24
This bug also appears to modify the critical chance of spells.
Naturally, since the mod modifies the critical chance of the weapon itself only,
we have confirmed that the actual critical chance of the spell does not change.

https://pobb.in/FmoYAmgWJ5ff

If you check this POB, you will see that Blade Vortex itself has a -3% spell crit chance,
This is incorrect and does not apply in-game that way.

**Comment by QuickStick123** [comment] 2023-04-19 13:26
This is also fixed in the PR.

**Comment by tylerK1294** [comment] 2023-04-19 14:18
I fetched the fix_crucible-base-crit branch and confirmed that the critical chance of spells issue is fixed.

**Closed** 2023-08-26 15:40 UTC
Labels: bug:calculation
