### ISSUE TITLE
crush 

### ISSUE THREAD

**Issue by yoshieq** [PathOfBuildingCommunity/PathOfBuilding#3561] opened 2021-10-22 14:59 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [x] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

just open

### What is the actual behaviour/value?

crush program when i try open her

### How to reproduce the issue

click on icon 

### Build code

```shell
all versions
```

### Screenshots

![opsMDMbZsRQ](https://user-images.githubusercontent.com/92996969/138477084-4b75903f-cbdc-40a8-9362-6a5e510d11ba.png)

**Comment by Lothrik** [comment] 2022-06-25 01:27
Duplicate of #1843. Closing.

**Closed by Lothrik** 2022-06-25 01:27 UTC
Labels: bug
