### ISSUE TITLE
Crash with Penance brand build, arithmetic on nil value

### ISSUE THREAD

**Issue by ezora5t10leib** [PathOfBuildingCommunity/PathOfBuilding#7259] opened 2024-01-18 15:17 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Screenshots of crash/graphical issue, version and options menu

https://i.imgur.com/tBWFd4I.png

### What are your system specifications and configuration?

Windows 10, 1080ti 

### How to reproduce the issue

Crashes when attempting to view/add best support gems for the main skill, Penance brand of dissipation when max pulse per brand is selected. 

### Character build code

```shell
https://pobb.in/DjEFaiN4tzct
```

**Comment by sida-wang** [comment] 2024-01-19 07:33
Duplicate of #7236 but would have been hard to tell based off issue title. 

2 current workarounds until the next release:
- Take out sublime vision when adding support
- Change to energy pulse instead of max energy per pulse when adding support

**Closed by sida-wang** 2024-01-19 07:33 UTC
Labels: bug, crash
